### ISSUE TITLE
Web Services Functions - Exception - IOMAD 34

### ISSUE THREAD

**Issue by fryeguy63** [iomad/iomad#1003]
Attempting to enable and setup web services to integrate with a 3rd party CRM. All worked in previous release of Iomad. When trying to add functions to a service, the following exception is thrown:

> Exception - Argument 1 passed to external_multiple_structure::__construct() must be an instance of external_description, array given, called in [dirroot]/blocks/iomad_company_admin/externallib.php on line 315

The same exception is thrown for all "Functions" links for all services except the default "Moodle mobile web service".

This exception currently stops me from defining functions for my service.

**Comment by turf212** [comment]
this was fixed a while back.
