### ISSUE TITLE
IOMAD Company Select not visible.

### ISSUE THREAD

**Issue by jacksonp2008** [iomad/iomad#1004]
<img width="265" alt="screen shot 2018-08-13 at 16 46 54" src="https://user-images.githubusercontent.com/1813327/44064161-90c21730-9f18-11e8-9e6c-ff52125b06af.png">

I would like to make this visible to a regular user (not admin) and allow them to switch between companies to view different content.  

According to moodle, the user has permissions to view the block but it doesn't show up on the page for them.  Likely you have restricted to admin, if so can you point me to the code.

Thanks

**Comment by turf212** [comment]
The switcher will only allow display to users who are in multiple companies, such as company managers in a parent company will see all of the child companies below them so they can manage them.  Users cannot be in multiple companies at this point in time.
