### ISSUE TITLE
Function returns incorrect type

### ISSUE THREAD

**Issue by fryeguy63** [iomad/iomad#1005]
https://github.com/iomad/iomad/blob/119c91506eb67b8899c3b7ad446e19822c487239/blocks/iomad_company_admin/externallib.php#L295

This function gets called when trying to create functions for an external service. An exception gets thrown for L315 where the first argument to this function is trying to return the wrong type, an array instead of external_description.

It is completely broken for me and I am unable to create a web service.

I see the same error in Iomad33 and Iomad32 as well. I was previously testing on Iomad32 and had no problems.

**Comment by fryeguy63** [comment]
I see the same error in Iomad33 and Iomad32 as well. I was previously testing on Iomad32 and had no problems.

**Comment by turf212** [comment]
Fixed in later versions.
