### ISSUE TITLE
[URGENT] Certificate Plugin 2016 Error affect Completion Report

### ISSUE THREAD

**Issue by bambang150** [iomad/iomad#1007]
Hi recently I tried to use certificate activity and it returns error like below.

![image](https://user-images.githubusercontent.com/24808678/44419769-a96a2b00-a5ae-11e8-9cf0-d700971d322d.png)

Then I tried access User Completion Report and click Course Summary and it return result like below
![image](https://user-images.githubusercontent.com/24808678/44419815-c9015380-a5ae-11e8-9043-4409b99b0a8f.png)

When I check on Activity Overview, I found that Certificate activity return error. How to solve this? It is urgent because it affect the main report.
![image](https://user-images.githubusercontent.com/24808678/44419842-db7b8d00-a5ae-11e8-8f6c-8336ee38b8b3.png)

**Comment by plogue2018** [comment]
I'm also having this issue. Exactly the same.

Is there a fix for this? It seems the table is missing from the DB (after a clean installation).

**Comment by turf212** [comment]
This was the issue.  The latest certificate module from Moodle had been added but the tables had the wrong definition.

If you patch and then remove and re-add the iomad certificate module this will fix your issue.  This only is on a fresh install and not an upgraded one.
