### ISSUE TITLE
Extend IOMAD Comany Managers to some site administration features.

### ISSUE THREAD

**Issue by ken4ward** [iomad/iomad#1009]
I am wondering if this is achievable in IOMAD, that Company Managers can be granted access to some site administration features. I have a scenario whereby the SITE ADMINISTRATOR would only need to create the COMPANIES and allow the Managers to do the all other setups. This means that Company Managers will have full Manager role like it is in Moodle Manager role.
The managers should be able to create COURSE CATEGORIES, USER COHORTS.
It seems IOMAD streamlined Moodle functions to only focus on COMPANIES. My project is for conventional schools.

**Comment by turf212** [comment]
You can use the client admin role to do this.  This is designed for a sub site admin/manager type role which can be applied at a site level for a user.  The issue with applying it further than this is trying to not break the multi-tennancy parts of users not being able to see users they shouldn't.
