### ISSUE TITLE
Share Learning Paths to other Companies

### ISSUE THREAD

**Issue by fryeguy63** [iomad/iomad#1010]
Learning Paths are a great feature. A major option missing from learning paths is the ability to create a path and share it across companies.

I currently have over 250 companies that all need to access the same courses and learning paths. I have seven learning paths and therefore I need to manually create 1,750 learning paths.

Learning Path creation should absolutely be added to the API for use in web services.

**Comment by teddielong** [comment]
I'm interested in using Learning Paths, but we haven't yet had chance to do so properly.  Would love to hear how you're using it Kevin :)

**Comment by fryeguy63** [comment]
We are moving from another LMS and beginning to self-host so we can build out some additional services in the platform. I work for a software company and my team provides training services to our customers. We have a small number of eLearning, video-based courses and Learning Paths allow us to present a "path" for training instead of just a list of course to students. On the student dashboard I removed the "courses" block and added the "Learning paths" block. This forces students to engage with the learning path.

Again, my biggest issue is that I need to share these learning paths across all eLearning companies and currently I have to do it manually. We can limp down the road for now but some better automation is neccessary for us to be effective.

**Comment by ericlund9** [comment]
Hey Kevin, were you able to find any solution to share learnings paths between companies? Creating the same learning path for each company will not be scaleable.

@turf212 Is there any plans to add this functionality?
