### ISSUE TITLE
Report user logins gives an error on an Oracle database

### ISSUE THREAD

**Issue by thierryVergult** [iomad/iomad#1012]
Running the report (iomad/local/report_user_logins/index.php) gives an error on line 730, when running on top of an Oracle database.

> ora-00909 : invalid number of arguments

Reason: the concat function at that line has 3 arguments, while Oracle supports only 2.

see also: https://www.techonthenet.com/oracle/functions/concat.php

Probable solution: nest the concat calls

eg: concat(c.id, '-', u.id) becomes concat( concat( c.id, '-'), u.id)

thanks!

**Comment by turf212** [comment]
These have been changed in 3.6 to be concat(1, concat(2,concat(3,4))) style in any reports.
