### ISSUE TITLE
mmap() failed 12 cannot allocate memory

### ISSUE THREAD

**Issue by mschinzvende** [iomad/iomad#1013]
On trying to run the installation, i get a blank screen and the error log shows mmap() failed 12 cannot allocate memory. The reference url is ../admin/index.php?lang=en. I am running on a Linux VPS with apache and php7.0

**Comment by turf212** [comment]
Sounds like the PHP set up didn't have enough  memory allowed for execution.  Try adding this to the appropriate php.ini file

memory_limit = 128M
