### ISSUE TITLE
Can't setup or add any new Webservice function IOMAD 3.4. Can you help?

### ISSUE THREAD

**Issue by f2dwire** [iomad/iomad#1014]
I can't create a new webservice function in IOMAD 3.4 to integrate WordPress with the Moodle. Whenever I try to add a new function to any service, I get the following exception error:

 Argument 1 passed to external_multiple_structure::__construct() must be an instance of external_description, array given, called in [dirroot]/blocks/iomad_company_admin/externallib.php on line 315

Any ideas on how to resolve the error or export users from WordPress to Moodle periodically?

**Comment by turf212** [comment]
There was a bug in the external lib file.  You should be OK now.
