### ISSUE TITLE
problem completion by course report.

### ISSUE THREAD

**Issue by rroijackers** [iomad/iomad#1017]
When we want to create a report of the course completion, it said the following:

The State of the stuednt is not started, there is also no start date, but the overall score is 6%. What is causing this problem?
It reads the progress of the student, but still it said not started.

**Comment by rroijackers** [comment]
This problem has been solved. Only now the users in the course summary disappears.

**Comment by turf212** [comment]
The reports use Moodle course completion to hold the data which isn't particularly intuitive in it's reporting.

Have you checked the reports showing historic results too?

**Comment by rroijackers** [comment]
I've checked, but also in the completion report the status is Always not started. It doesn't change to in progess. Strange is that the scorm content gives in the course a result. But when it's higher than 0% the status is not changing to in progress. I can't find the problem.

**Comment by turf212** [comment]
We've totally redone the reports in 3.6 and now have a central datastore for holding the users course lifecycle.
