### ISSUE TITLE
Company can not be switched by menus

### ISSUE THREAD

**Issue by syusanjun** [iomad/iomad#1018]
Even if Iomad dashboard is used to register multiple companies, it can not be switched by menus.
Moodle 3.5.1+ (Build: 20180817)

**Comment by davidpesce** [comment]
Same here. If I select the company from the dashboard, it defaults back to the first company in the list.

**Comment by kilo8ytes** [comment]
Also clicking the Manage Company button on the Manage Companies page selects the first company.

**Comment by turf212** [comment]
URL being used for the autocomplete form form needed to be /my/index/php  Also, the parameter being passed to the dashboard wasn't being kept in the check company status code and was being set to the first company in the list.
