### ISSUE TITLE
Creating course in Moodle vs IOMAD

### ISSUE THREAD

**Issue by ndalpe** [iomad/iomad#1024]
Hi,
Congrats to all the IOMAD team for there effort. Great product!

I would like to know the difference between creating a course in Moodle then assign it to a company versus create a course in IOMAD Dashboard -> Company -> Courses -> Create course.

Does it change anything in the reporting? Licenses? Enrollment?

I am using IOMAD_34_STABLE. In the process of upgrading to 35

Thank you in advance for your help

Take care

**Comment by turf212** [comment]
It doesn't change anything logically just creating the course in Iomad will automatically assign it to the company and do all of the underlying things there.
