### ISSUE TITLE
Error reading from database on Moodle 3.5 with Iomad Create user

### ISSUE THREAD

**Issue by smezei** [iomad/iomad#1026]
Hi everybody!

I have a big problem!

I use Iomad 3.5  from https://github.com/iomad/iomad on Centos7 with MySQL 5.7 and PHP 7.0.

After I wes created the second company and a " company manager" user in Iomad dashboard, I able to login with it, but cannnot create users: 

Error reading from database

However the first company's company manager user and the admin account can create users.

Have you any idea?

Thank you,

Alexander

**Comment by turf212** [comment]
Did you get any errors with debug on when creating the second company manager?  Also with debug on, what error did you get when creating the users?

Debug:  Site administration -> Development -> Debugging and set to show errors and full developer.

Thanks

**Comment by smezei** [comment]
Hi Turf212!

Here is the log after turned debug logging on:

Debug info: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 7
SELECT COUNT(DISTINCT c.id) FROM mdl_course c,
mdl_company_course cc
WHERE c.visible = 1
AND cc.courseid = c.id
AND c.id != ?

AND cc.departmentid in (1,) 
[array (
0 => '1',
)]
Error code: dmlreadexception


Stack trace:
line 486 of /lib/dml/moodle_database.php: dml_read_exception thrown
line 1245 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()
line 1571 of /lib/dml/moodle_database.php: call to mysqli_native_moodle_database->get_records_sql()
line 1644 of /lib/dml/moodle_database.php: call to moodle_database->get_record_sql()
line 1854 of /lib/dml/moodle_database.php: call to moodle_database->get_field_sql()
line 565 of /blocks/iomad_company_admin/lib/course_selectors.php: call to moodle_database->count_records_sql()
line 208 of /local/course_selector/lib.php: call to potential_subdepartment_course_selector->find_courses()
line 283 of /blocks/iomad_company_admin/company_user_create_form.php: call to course_selector_base->display()
line 204 of /lib/formslib.php: call to user_edit_form->definition()
line 73 of /blocks/iomad_company_admin/company_user_create_form.php: call to moodleform->__construct()
line 428 of /blocks/iomad_company_admin/company_user_create_form.php: call to user_edit_form->__construct()

Thanks

**Comment by turf212** [comment]
The SQL here is being formed by department ids being added into a comma separated list using the PHP implode feature.  Either there is something odd in your mdl_departments table, or your version of PHP is doing something odd with the implode command.

Can you please check how many departments are allocated to this company in the database.  (select * from mdl_department where company = <companyid>)
Can you please confirm what version of PHP you are using.

**Comment by smezei** [comment]
I try on Centos7:
PHP Version 7.0.32

And I try in OpenShift 3.9 OKD (Origin):
PHP Version 5.7.21

**Comment by smezei** [comment]
Here is tha all table of mdl_department:
-------------------------------------------
mysql>  select * from mdl_department;
+----+----------------+-----------+---------+--------+
| id | name           | shortname | company | parent |
+----+----------------+-----------+---------+--------+
|  1 | First Company  | 1st co    |       1 |      0 |
|  2 | Second Company | 2sd co    |       2 |      0 |
+----+----------------+-----------+---------+--------+

**Comment by bbonamie** [comment]
I've come across the exact same error. I'm running XAMPP under Win10, with Apache/2.4.35, PHP 7.2.11 and MariaDB 10.1.36 running on a localhost, for testing purposes.

The contents of my mdl_department is this:
![image](https://user-images.githubusercontent.com/44568175/47640286-8ab28280-db63-11e8-90d7-fc6362510cc1.png)

**Comment by smezei** [comment]
@kingdavid127
Is it working for you? I try what I read in the third commit , but not ok.

Someone has idea for this proble?

**Comment by smezei** [comment]
@kingdavid127
Is it working for you? I try what I read in the third commit , but not ok.

Someone has any idea for this problem?

**Comment by kingdavid127** [comment]
Yeah this is working for us, we tested and released in several production environments already. Did you copy the entire new function? You should also purge caches and log out and back in after the change.

**Comment by kingdavid127** [comment]
I would copy the function from this pull request to make sure you have everything necessary.

https://github.com/iomad/iomad/pull/1042/files

**Comment by smezei** [comment]
@kingdavid127 Thank you very mutch! 
It is work on "classic" host and in docker container too.
