### ISSUE TITLE
 Apply role template does not apply

### ISSUE THREAD

**Issue by ndalpe** [iomad/iomad#1029]
Hi Guys,
I think I found a bug. I can't apply a role template to a parent or a child company.

What I did:
 - git clone the latest version IOMAD_35_STABLE and install
 - Create a parent company
 - Create a child company
 - Create a Role template (Dashboard -> Company -> Restrict Capabilities -> Save as Role Template)
 - Edit parent company and set  "Apply role template" to your newly create role tpl
 - Edit child company and set   "Apply role template" to inherit

Go back to edit any of the company and the role template is not set but curiously, below the field it says "Previously applied was Inherit" but the select menu it set to none.

Anyone in the same situation?

Thank you in advance for your help

Take care

**Comment by turf212** [comment]
did you check if the roles for the company had been given the restrictions from the template?

**Comment by ndalpe** [comment]
The restriction applies but I have to go to edit the company, select the role template again and save, then the restrictions are applied. 

It is unfortunate because if you edit any other company info and not select your role template again, your restrictions are lost.

does that answer your question?

thx

**Comment by turf212** [comment]
This is desired workflow.   The role template will be applied when you save the company and will replace the companies set of roles.  You can then change these further in the company and it will not impact on the template you started with.  If you change the company settings for something else, it will not change the role capabilities for this new set.

If you want to update the template and reapply it you have to do it explicitly to the company.

Think of it like a stamp.  I stamp the design on a piece of paper.  I can then draw on the paper, which doesn't change the stamp, or I can alter the stamp which doesn't change the paper.  To change the paper, I have to get a new one and re-apply the stamp.

**Comment by ndalpe** [comment]
Hi @turf212 ,
Thx for the stamp example. It explains it very well.

Just a quick question:
In the company edit form, section : 'Advanced Company Settings' we have 2 confusing fields:
Apply role template: select menu with role template
Available templates: also a select menu with role template

Would you mind explaining the difference between those 2?

thank you so much

best,
