### ISSUE TITLE
Hidden Course Can't Be Removed From Company

### ISSUE THREAD

**Issue by smuglet** [iomad/iomad#1030]
If a course is hidden you can't remove it from a company as it doesn't show up in the list on the "Assign To Company" page.

Unless it is fixed, we have to remove the course from the company before deleting it via Site Admin as a trigger to clean-up properly if just deleting a course from site-admin broke the company level reports.

Can't do this process if can't see the course.  

Work around is to temporarily make course visible but this is not idea.

**Comment by turf212** [comment]
need to add either a button to show the hidden course or denote them as such in the course listings.  Capability to ensure this can be explicitly added to a role/user

**Comment by turf212** [comment]
functionality is now available - can show hide and see status and hidden courses can be seen if you have the rights.
