### ISSUE TITLE
I just upgraded to the latest code and iomad local iomad_dashboard is missing. 

### ISSUE THREAD

**Issue by Markrico** [iomad/iomad#1031]
I just upgraded to the latest code and iomad local iomad_dashboard is missing. 

When I try to use the old plugin it does not work.

**Comment by thepurpleblob** [comment]
The Iomad dashboard block as been moved to your "normal" Moodle dashboard. It should have been added automatically. 

You can add it to your (Moodle) Dashboard manually if you need to.

**Comment by Markrico** [comment]
When I click on the Moodle dashboard I get This Page isn't Working. The IOMAD dashboard is still present and gives the same error. I am using the code that said 3.5 just before the 3.5 no dashboard.

**Comment by Markrico** [comment]
I also tried to install a new IOMAD with the 3.5 NoDashboard code and get the same error after the plugin check page, which is all good, and then I click update the database. This page isn't working. I am using php 7.1 and a Centos vps server that has been running IOMAD for about 2 years.

**Comment by Markrico** [comment]
Hi, I tried a new install of Iomad 3.5 Nodashboard and it will not install properly, after the plugin check page it goes to a white page that says this page is not working. 
I tried to install a new Iomad 3.5 with the same results as above. 
I installed new Iomad 3.4 without issues. 
Unfortunately I upgraded another Iomad to 3.5 and now it has no dashboard and I cannot go back to using the 3.4 working code. 
Can you please let me know when your 3.5 code is working so I can use it to repair the above site. 

Sorry to be a pain,

Thank-you very much for any help you can provide!
