### ISSUE TITLE
incorrect $user->company->id after login

### ISSUE THREAD

**Issue by semteacher** [iomad/iomad#1033]
Environment: 
-fresh IOMAD_35
- 2 companies with 2 user (1 manager + 1 user)
When I tried to use different logo's per company:
- for admin - working properly, logo changed when admin change editing company
- for all company's users - only company1 logo shown.
Note: all secondary/third logons was done using different browsers with "incognito" mode
After investigation I found that row 
``$companyid = \iomad::is_company_user();``
in theme render's class function
` get_iomad_logo()`
return value 
`$companyid = 1 `
After further investigations I found that the following code
```
        if  (!empty($SESSION->currenteditingcompany)) {
            return $SESSION->currenteditingcompany;
        } else if ($usercompanies = $DB->get_records('company_users', array('userid' => $user->id), 'id', 'id,companyid', 0, 1)) {
            $usercompany = array_pop($usercompanies);
            return $usercompany->companyid;
        } else {
            return false;
        }
```
in the \local\iomad\lib\iomad.php every tine return value 1 in all my cases 
My solution (which is working for me) is the followning changes for \local\iomad\lib\iomad.php
```
        if ($usercompanies = $DB->get_records('company_users', array('userid' => $user->id), 'id', 'id,companyid', 0, 1)) {
            $usercompany = array_pop($usercompanies);
            return $usercompany->companyid;
        } else if (!empty($SESSION->currenteditingcompany)) {
            return $SESSION->currenteditingcompany;
        } else {
            return false;
        }
```
Also I made the following changes in  \local\iomad\lib\company.php 
```
    public static function by_userid($userid) {
        global $DB, $SESSION;

        if ($companies = $DB->get_records('company_users', array('userid' => $userid), 'companyid DESC')) {
            $company = array_pop($companies);
            return new company($company->companyid);
        } else {
            if (!empty($SESSION->currenteditingcompany)) {
            return new company($SESSION->currenteditingcompany);
            } else {
                return false;
            }
        }
    }
```
Given solution working properly for me

**Comment by turf212** [comment]
SESSION has to be first otherwise a company manager in parent child company cannot select and edit the child company.  The issue is that you are using the same browser (so $SESSION)  and this is being retained across log ins.
