### ISSUE TITLE
[IOMAD 3.5] Courses are not showed in the "My courses" block

### ISSUE THREAD

**Issue by fortarrigo** [iomad/iomad#1034]
Hi,
as you can read in the subject, in my IOMAD 3.5 instance, courses are not showed in the "My courses" block.
I tried to create a course via IOMAD and via Moodle, but I can't see them in the "Courses available" block.
I tried also to create a new user with Student role, but it's always the same.

Any suggestions?
Thanks in advance

**Comment by turf212** [comment]
It uses the course completion underpinnings to show the courses ass they need to be in progress/completed and so on.  Make sure you have set these up on the courses and they will appear.

**Comment by Nab59** [comment]
Hi
I have exactly the same issue. Could explain how you do appear the course into the block course.

**Comment by fortarrigo** [comment]
Hi @turf212 
Thank you for your reply
I performed a manual cron job (I'm developing on my local server) and after courses appeared in "My courses" block.
@Nab59 try this solution.

Have a nice day.

**Comment by NCTPerth** [comment]
Site Admin > Server > Scheduled Tasks > Completion Mark as Started > Hour > */2
Site Admin > Server > Scheduled Tasks > Calculate Regular Completion Data > Hour > */2

These 2 scheduled tasks are critical for many reasons and may help above issue.
 Also is the user enrolled into the course or the teacher assigned to the course?
