### ISSUE TITLE
iomad 34 stable and imod 35 stable installation not working after entering Database setting

### ISSUE THREAD

**Issue by haseeb200** [iomad/iomad#1040]
I have downloaded the stable build of imod 34 and 35 both are not installed properly. After asking Database configuration like DB username, password, port etc. As soon as I Click install I got an error which says "This page isn't working."

**I install iomad 33 stable builds and it's properly working while 34 and 35 are not working. What is the issue in the installation?**

![1](https://user-images.githubusercontent.com/10439778/48056362-6c87fa80-e1d3-11e8-884c-84a22373b2ca.PNG)
![2](https://user-images.githubusercontent.com/10439778/48056363-6d209100-e1d3-11e8-96ec-1534e5658a24.PNG)

**Comment by corei3intel** [comment]
Try to delete cache files on moodledata directory.

**Comment by haseeb200** [comment]
I deleted those but still having issues with 34 and 35 build but not with 33 build

**Comment by corei3intel** [comment]
I use 33 with php 7.0 and run ok.

**Comment by haseeb200** [comment]
> I use 33 with php 7.0 and run ok.

Yes, thas what i said 33 is working fine But not 34 and 45 build

**Comment by turf212** [comment]
checked all OK installing without a config file in 3.6.
