### ISSUE TITLE
 Uncaught Error: Call to undefined function current_language() 

### ISSUE THREAD

**Issue by corei3intel** [iomad/iomad#1041]
Hi, thanks for your help. When i install iomad, apache return this error:

 Uncaught Error: Call to undefined function current_language() lib\setuplib.php:701

this file exist on my directory not run the installation.

**Comment by ghost** [comment]
I'm working on IOMAD_34_STABLE and using try-and-error I found out that commit `f00097a7b05da9abb4572bf39a57a9ae932e4d29` is working while `6b0f096cf83c2ef47d05939a29e02c925d837778` is not and throwing above error.

**Comment by corei3intel** [comment]
Hi Philipp93, finally i use IOMAD_33_STABLE and work ok with php 7.0.

Thanks for your help.

**Comment by turf212** [comment]
fixed in later 3.4 branch
