### ISSUE TITLE
Manager can only see report from main company

### ISSUE THREAD

**Issue by rroijackers** [iomad/iomad#1050]
I have upgraded from Moodle 3.4 to 3.5 latest version. No I have 2 problems. The first is that all managers from other company can only see the report from the main company. They can reach this report by the right block Iomad Reports. 
The second problem is that they didn't see the Iomad dashboard. In Iomad 3.4 they saw only the iomad dashboard with reports and not the manage part. Now they have nothing.

**Comment by turf212** [comment]
Check the capabilities for the company manager roles as it sounds like they are missing some required ones to see the dashboard.  In 3.5 on the reports are now in the main Iomad dashboard, which it sounds like you have disallowed.

When you say they can see the report from other companies, which report?  Users? COmpany? completion?
