### ISSUE TITLE
The company manager can not display its own company user.

### ISSUE THREAD

**Issue by syusanjun** [iomad/iomad#1056]
The company manager can not display its own company user.
$release  = '3.5.2+ (Build: 20181107)'

**Comment by rroijackers** [comment]
DOes it sees in the report no users or only the users from the default company?

**Comment by turf212** [comment]
Is this in teh reports or when editing users?  Users can edit it's own profile from the standard Moodle profile pages.

**Comment by rmeske** [comment]
I may have just encountered the same issue.  I created two user when logged in as the super admin under a child company with the roles: company manager and department manager.  Realizing my mistake I unassigned them from the company and the switched to the correct top-level company and assigned the two users to that company and assigned them the correct roles again.

Now when I sign in as either user I see the correct company name on the Dashboard but the theme shown is the one from the parent company or the child company I had created the user under originally and if I go into Company and Edit Company it is displaying the original parent company information.

Some of the other Iomad blocks will show the company as blank and give a database error.

I am using Stable 36 version as of 8/17/2019.

**Comment by turf212** [comment]
Not sure if this is the same issue.  Iomad makes a fuzzy decision as to which company a user should have as it's primary company.  (which we likely need to tidy up should we ever look at having user's belonging to multiple companies).  It sounds like you have broken something within this, probably by it not completely clearing the users out of the child company and it then being the dominant company even though they are now in the parent company.   I would suggest that the simplest solution here would be to delete the users and re-create them in the correct company.

**Comment by rmeske** [comment]
Unfortunately, deleting the user and then creating them again under the correct company did not fix the problem.  As the "root" user I can see they are listed as the company manager for the correct company.  However, when that user logs in they are still showing up under the other company, and can not access any information for the company they are assigned to.

When logging in as a department manager, it shows the company field as blank and has an error mesage: "Error reading from database".
