### ISSUE TITLE
Ecommerce question

### ISSUE THREAD

**Issue by Nab59** [iomad/iomad#1058]
Hi,

I have one question and hope someone can reply clearly.
Is it possible for each company to sell its courses with its own paypal settings ?

Thank you

**Comment by turf212** [comment]
No its not possible for the tennants to sell courses through the system.   It's designed for the tennants to buy courses off of you.

**Comment by Nab59** [comment]
Hi Derick

Thank you for your clear answer.

So do you have an idea how to achieve this scenario :
1/ instructors create their courses in moodle
2/ Using Woocommerce ? Commision for admin site ?

Thank you. Ii hope i can start asap.
