### ISSUE TITLE
One user working for multiple companies

### ISSUE THREAD

**Issue by rajephcote** [iomad/iomad#106]
Is there a way that I can create a user that works for two different companies and have the same user assigned to both companies without them having to have a seperate user account within each company?

If its not possible where would I begin to create the functionality to do this

**Comment by morfjord** [comment]
Yes, this is a functional as I gladly see resolved.

**Comment by turf212** [comment]
It is currently only possible for a company manager to be assigned to more than one company.  The issue with users is what to do with their data if they are e.g. deleted from one company or are added to a shared course which they are already enrolled in/have a license for from another company.  Not a simple thing.
