### ISSUE TITLE
Bulk user enrolments

### ISSUE THREAD

**Issue by smuglet** [iomad/iomad#1063]
Just wondering if there is any advance on #680 for bulk user enrolments or is doing a subsequent upload with "Update" set still the recommendation?  If doing this, what is the **absolute minimum data-set required** (columns)?

Or is there now a recommend, Iomad safe, way to handle bulk user enrolments onto course.  Either via the UI or via CSV?  I looked at "Learning Dashboard -> Assign users to course" is limited (depts) and the search struggles with larger numbers of users.  I thought this might work also: https://moodle.org/plugins/local_mass_enroll But don't know if it is Iomad safe and if it would be available for Company Managers.

**Comment by turf212** [comment]
CSV upload handles this
