### ISSUE TITLE
Add Fields To "Completion report by course"

### ISSUE THREAD

**Issue by smuglet** [iomad/iomad#1064]
Is there a nice / recommended way to add custom profile fields as additional columns to the "Completion report by course" without tinkering with core Iomad code?

**Comment by turf212** [comment]
Yes.  You can add extra report fields in the local iomad settings plugin.  If you are using an optiona profile field then the name will would be profile_field_<shortname> exactly the same as if you were using the CSV upload,  These get injected into the Iomad report columns after department.
