### ISSUE TITLE
Upload Users - Department Change Not Reflected

### ISSUE THREAD

**Issue by smuglet** [iomad/iomad#1068]
Hi,

Upload to update seems to be the way to handle bulk updates.  However... I just ran a bulk upload to update user "Department" and it has updated the "Department" field as in the "Optional" section when editing that user but has not updated the Iomad department.  Does the column head need a different name to update the Iomad setting, I'm using "department" or is this a buggette?

Thanks.

**Comment by ghost** [comment]
I noticed this too and also in the Bulk user download file, the department field there is also the standard Moodle user profile field, not the Iomad assigned company department. 

So there seems to be no way to bulk upload or bulk download the Iomad department user info.

**Comment by turf212** [comment]
The user profile "department" field is not the same as the company department.  When Iomad was originally created this profile field did not exist (yes this was way back in Moodle 2.0)  There is a setting in local  Iomad settings which allows you to keep the department and/or institution fields in sync with the designated company and company department.  This is kept optional as site admins may be using the profile field for another designation.
