### ISSUE TITLE
Bulk User Export - Department (is not Iomad department)

### ISSUE THREAD

**Issue by smuglet** [iomad/iomad#1069]
Related to a previous issue I've logged.  Upload not updating Iomad department.

I've also just noticed that the "department" column populated when doing a "User Bulk Download" appears to be using the users field "department" and not the Iomad department... or they are not in sync.

Noticed as I have manually moved a number of user (via the UI) to a new department but the previous department name is being pull into the export.  So Iomad has updated but the "department" field for the user, which seems to be being exported is not.

**Comment by turf212** [comment]
This is the user profile department.  If you turn on syncing between Iomad department and or company to the profile department and or institution (site administration -> plugins -> local -> Iomad settings) then this will keep the two in sync with the Iomad company information the master.
