### ISSUE TITLE
company branded login apge

### ISSUE THREAD

**Issue by rroijackers** [iomad/iomad#1070]
I am running Iomad on a webhosting with directadmin. I am trying to use the branded login pages. I've created a subdomain in direct admin with an A record also tried it with a cname record. Both are not working. I'va put the subdomain in the company settings by hostname. Can someone tell me what i'm doing wrong?

**Comment by turf212** [comment]
You need to point the other domains to the original hosted site.  You also need to turn on the local iomad signup plugin too with the appropriate self enrolment plugins you want to do.
