### ISSUE TITLE
Automatic company allocation on self signup. Can this be set to depend on custom question?

### ISSUE THREAD

**Issue by bguillia** [iomad/iomad#1071]
So in the build, I am doing the emails for the different groups are all over the place. Can it be set up to place people based on a custom question, in my case what state they indicate working in?

**Comment by turf212** [comment]
Not at the moment (if you'd like to sponsor code to do this please drop a line to info@iomad.org and we can talk about something which meets your specification).  You can specify the company directly in the URL for /local/iomad_signup/signup.php which uses the company id, shortname and, optionally, department, to allow you to specify the user's wanted company.
