### ISSUE TITLE
Unable to assign user to a company group

### ISSUE THREAD

**Issue by mittra** [iomad/iomad#1073]
We're using version 3.4.4+ (Build: 20180817) and have three companies that access one Iomad course.

Using Groups, we have three tracks within the course, Standard, Analyst, and Assessor. The Standard Track views the entire course while the Analyst and Assessor courses access 5 of 6 "modules" (we called them modules when we first created the course) depending on the focus of their course.

I import the users with a csv file upload through "Upload users" under Site Administration, then allocate licenses to users according to the company they belong to, and finally assign them to the appropriate track Group. This has not been a particularly easy process to suss out and I miss not being able to assign the users to a group during the upload, but when I tried to add a new user to the Analyst group for one of the secondary companies I received an error and the users were not added to the group.

Error: mdb->get_record() found more than one record!

- line 1583 of \lib\dml\moodle_database.php: call to debugging()
- line 1543 of \lib\dml\moodle_database.php: call to moodle_database->get_record_sql()
- line 1522 of \lib\dml\moodle_database.php: call to moodle_database->get_record_select()
- line 656 of \local\iomad\lib\user.php: call to moodle_database->get_record()
- line 339 of \blocks\iomad_company_admin\company_groups_users_form.php: call to company_user::assign_group()
- line 447 of \blocks\iomad_company_admin\company_groups_users_form.php: call to course_group_users_form->process()

Can not find data record in database table groups.

[More information about this error](http://docs.moodle.org/34/en/error/moodle/invalidrecord)

**Debug info:** SELECT * FROM {groups} WHERE id = ?
[array (
0 => '117',
)] 
Error code: invalidrecord
**Stack trace:**
- line 1546 of \lib\dml\moodle_database.php: dml_missing_record_exception thrown
- line 1522 of \lib\dml\moodle_database.php: call to moodle_database->get_record_select()
- line 197 of \group\lib.php: call to moodle_database->get_record()
- line 663 of \local\iomad\lib\user.php: call to groups_remove_member()
- line 339 of \blocks\iomad_company_admin\company_groups_users_form.php: call to company_user::assign_group()
- line 447 of \blocks\iomad_company_admin\company_groups_users_form.php: call to course_group_users_form->process()

**Comment by turf212** [comment]
The system keeps track of what groups have been created for a company within a course.  If this group is removed from the course and not the company then it could cause data errors like you are seeing.

If there is an entry in mdl_company_course_groups for this company id and a groupid of 117 and there is no entry in mdl_groups with an id 117 then this is the issue you have fallen into.  If you clear down the entries in mdl_company_groups where groupid not in (select id from mdl_groups) it will sort the issue.

**Comment by turf212** [comment]
sorry that should be mdl_company_course_groups.
