### ISSUE TITLE
Disable or Customize the License Allocated Notification Message

### ISSUE THREAD

**Issue by mittra** [iomad/iomad#1074]
Without modifying core code, can the notification Iomad sends to users when a license is allocated to them be customized or disabled to not be sent at all?

We send new users a custom welcome message when they are enrolled in our course, but since we converted from Moodle "Prime" to Iomad, users are getting messages sent to them when licenses are allocated and/or unallocated that we don't want sent or want to modify the contents thereof.

**Comment by turf212** [comment]
The language for these messages can be changed in te Moodle language pack (to set the default) or change be changed per company.  3.6 will have an updated email package which will allow for individual emails to be switched off per company for managers or users.  We are working on integrating this now.
