### ISSUE TITLE
Company users log on wrong company

### ISSUE THREAD

**Issue by fortarrigo** [iomad/iomad#1075]
I create a new user and assign to a company with the role of Company Manager.
When I log in with this user, is assigned to a wrong company (the first company created).
Iomad dashboard for this user is related to the wrong company, as the branding.
I need to solve this issue as soon as possible.
What can I do?
My Iomad version is 3.5

Thanks in advance for help.

**Comment by rroijackers** [comment]
I have the same problem. Has someone a solution.

**Comment by turf212** [comment]
There was a fix for this in #1060 which was pushed to all branches.  Please check you have the latest version of the code for your branch.
