### ISSUE TITLE
Assign license with csv file

### ISSUE THREAD

**Issue by fesaner** [iomad/iomad#1080]
Is it possible to assign licenses via upload with a csv file?  The capability seems to be in the uploaduser.php file, but I cannot get it to work.  

I've tried several field ids, including 'licenseid' and 'license'.  For values I've used the license id from the database, the license name and the license reference.  Each time I get the following error message:  
Debug info: 
Error code: csvloaderror
Stack trace:
line 482 of /lib/setuplib.php: moodle_exception thrown
line 178 of /blocks/iomad_company_admin/uploaduser.php: call to print_error()

Thanks for any assistance you can provide.
Floyd Saner

**Comment by turf212** [comment]
There is no value in the CSV to allow for a license to be uploaded, however you can select a license and a course from it (where appropriate) along with any manual course enrolments or specific company role on the second page of the user upload page instead.
