### ISSUE TITLE
Unable to assign company manager if manual plugin not first enabled plugin in a company course

### ISSUE THREAD

**Issue by kingdavid127** [iomad/iomad#1081]
```
if (!isset($manualcache[$courseid])) {
                if ($instances = enrol_get_instances($courseid, false)) {
                    $manualcache[$courseid] = reset($instances);
                } else {
                    $manualcache[$courseid] = false;
                }
            }
```

The cache is populated by grabbing first instance from the array. The problem is that enrol_get_instances is sorted by sortorder, so the first instance from the array isn't always the manual enrolment plugin.

**Comment by turf212** [comment]
Tested with latest code and no issue found.

I don't think we were ever setting the cache here - to be honest.  It looks like it was trying to but further up in the code it only ever sets manualcache to be an empty array.

Tests undertaken

In course - delete manual enrolment method and re-add (so it's at the bottom)
Take existing user and promote to manager - user is enrolled on the course with the correct role
Create new user with Company manager selected as the type - new user is created and enrolled onto the course with the right role.
