### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by vvolz** [iomad/iomad#1084]
Hello, I cannot create a child company nor create a new company on the demo. I get the following error on your demo site, when logged in as Iomaddemo: Exception encountered in event observer 'local_iomad_observer::company_created': SOAP-ERROR: Parsing WSDL: Couldn't load from '/wp-content/plugins/wpiomadsoap/wsdl/wpiomadsoap.wsdl' : failed to load external entity "/wp-content/plugins/wpiomadsoap/wsdl/wpiomadsoap.wsdl"
line 79 of /blocks/iomad_commerce/locallib.php: call to SoapClient->SoapClient()
line 24 of /blocks/iomad_commerce/locallib.php: call to iomad_commerce::docall()
line 2597 of /local/iomad/lib/company.php: call to iomad_commerce::update_company()
line 138 of /local/iomad/classes/observer.php: call to company::company_created()
line ? of unknownfile: call to local_iomad_observer::company_created()
line 155 of /lib/classes/event/manager.php: call to call_user_func()
line 75 of /lib/classes/event/manager.php: call to core\event\manager::process_buffers()
line 835 of /lib/classes/event/base.php: call to core\event\manager::dispatch()
line 883 of /blocks/iomad_company_admin/company_edit_form.php: call to core\event\base->trigger()
Skip to main content

**Comment by turf212** [comment]
The old demo was missing some patches.  We are updating it with the latest 3.6 code once we have some data to use to highlight the reports.
