### ISSUE TITLE
Add block/iomad_reports:view in restrict capability

### ISSUE THREAD

**Issue by ndalpe** [iomad/iomad#1086]
Hi guys,
I noticed that I cannot find the capability 'block/iomad_reports:view' in Restrict Capabilities, so I cannot show/hide the Reports tab in Dashboard. I can set it if I go to Moodle -> Users -> Capability overview.

/blocks/iomad_company_admin/block_iomad_company_admin.php
Line 218
if (iomad::has_capability('block/iomad_reports:view', $context)) {
...

Hope this help

thx

**Comment by turf212** [comment]
This is from the blocks/iomad_reports/db/access.php  file which is part of the installation.

blocks/iomad_reports/db$ cat access.php 
<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

$capabilities = array(

    'block/iomad_reports:addinstance' => array(
        'captype' => 'read',
        'contextlevel' => CONTEXT_BLOCK
    ),

    'block/iomad_reports:myaddinstance' => array(
        'captype' => 'read',
        'contextlevel' => CONTEXT_BLOCK
    ),

    'block/iomad_reports:view' => array(
        'captype' => 'read',
        'contextlevel' => CONTEXT_BLOCK
    )
);

**Comment by ndalpe** [comment]
Hi @turf212,
Sorry my post wasn't clear. 

The line comes from:
https://github.com/iomad/iomad/blob/67385a39eb2608fa0d9fab9bb566163e711cfb03/blocks/iomad_company_admin/block_iomad_company_admin.php#L218

My understanding is that if the user has the block/iomad_reports:view cap then the Reports tab is displayed in Dashboard. Shouldn't this be treated like other tabs as well?

Example in page : Restrict capabilities for 'xxx'
View company management tab
block/iomad_company_admin:companymanagement_view

View competency management tab in dashboard
block/iomad_company_admin:competencymanagement_view

View the course management tab
block/iomad_company_admin:coursemanagement_view


There are 2 cap missing in Restrict Capabilities
E-Commerce tab
block/iomad_commerce:admin_view

Reports tab
block/iomad_reports:view

What do you think? make sense?

Thx

**Comment by turf212** [comment]
Possibly?

The capabilities which are listed for the role in the restrict capabilities are only those which have been given the capability for the role in Moodle.  In other words, if the role has the site/moodle capability to do a thing, this can be further taken away at the company level.  You can't add the capability to the company roles, only further restrict.  If you've turned it off at the Moodle role level, you wouldn't see it.

I can see the Access to Iomad Reports (block/iomad_reports:view) in my list of company capabilities when I go to restrict them.

**Comment by ndalpe** [comment]
ok I see. block/iomad_reports:view was set to 'Not set' in Moodle therefore it didn't show in IOMAD Restrict Capabilities page. I thought the IOMAD cap were independent from Moodle ones. 

Thx for the explanation

**Comment by turf212** [comment]
no, the Iomad caps build from the Moodle ones.  It's just a further filter of them. :)
