### ISSUE TITLE
Odd message on install

### ISSUE THREAD

**Issue by thepurpleblob** [iomad/iomad#1087]
During install, noted...

local_report_user_license_allocations
Dealing with 0 new allocations Dealing with 0 new un-allocations Dealing with 0 new allocations Dealing with 0 new un-allocations

Possibly implying it's executing some code it shouldn't be?

**Comment by turf212** [comment]
This was fixed in commit eafe92a648238d8d5d712365e7a581056c054da1 and pushed yesterday

**Comment by thepurpleblob** [comment]
Different mtrace() calls.  Just removed them
