### ISSUE TITLE
Privacy providers need to be updated with return type and user list info

### ISSUE THREAD

**Issue by dthies** [iomad/iomad#1102]
There are changes needed in the privacy providers in 3.6. The IOMAD plugins have to be updated to provide return types in function declarations to not have errors in 3.4-3.5 (https://docs.moodle.org/dev/Privacy_API#Difference_between_Moodle_3.3_and_more_recent_versions) and also to provide lists of users that have information in the context (see https://tracker.moodle.org/browse/MDL-62560 for examples and https://moodle.org/mod/forum/discuss.php?d=376082).

You can see error by going to Dashboard Site administration ->  Users ->  Privacy and policies ->  Plugin privacy registry.

**Comment by turf212** [comment]
Fatal error: Declaration of block_iomad_approve_access\privacy\provider::get_metadata(core_privacy\local\metadata\collection $items) must be compatible with core_privacy\local\metadata\provider::get_metadata(core_privacy\local\metadata\collection $collection): core_privacy\local\metadata\collection in /var/www/html/iomad36/blocks/iomad_approve_access/classes/privacy/provider.php on line 42

Thanks for letting us know.

**Comment by MrOli3000** [comment]
Having the same issue which is preventing the CRON from running correctly. Im using Moodle 3.5 and IOMAD 3.5. Is there a work around for now?

**Comment by turf212** [comment]
I've fixed these in 3.6.  If the 3.5 settings are now the I'll merge these into that branch and push.

**Comment by MrOli3000** [comment]
Can I update to IOMAD 3.6 and stay on Moodle 3.5? Its a pretty big process to upgrade our whole system.

**Comment by turf212** [comment]
No.  If it's a big process then stay on 3.5 for now till you can plan it.  Some of the report plugins have changed in 3.6 which now hold more/different data so they are not compatible.

**Comment by turf212** [comment]
I've pushed the 3.5 changes too.  You should just be able to pull and merge these into your current code.  There is some lang changes so, if you aren't forced into an upgrade, you will need to purge the Moodle cache (php admin/cli/purge_cache.php or via the site admin menus) to get the lang changes through.

**Comment by turf212** [comment]
FYI - 3.6 has a bunch of nice changes in the reports to make them faster and more intuitive.  I'd recommend planning and upgrading when you can.  See https://demo.iomad.org for an example.
