### ISSUE TITLE
Learning path course search errors on enter

### ISSUE THREAD

**Issue by dthies** [iomad/iomad#1107]
To reproduce
1. Edit and learning path course list from IOMAD admin course page
2. Type something in the course search box
3. Type enter
4. The page reloads and displays and error that the learning path id is missing.

**Comment by turf212** [comment]
Confirmed.   Will get this checked and fixed.  The Javascript shouldn't need the enter press as it's sorting the page dynamically.   If, like me, hitting enter is habit, then you get the issue.

**Comment by turf212** [comment]
was fixed a while back
