### ISSUE TITLE
Images in dashboard not visible. 

### ISSUE THREAD

**Issue by Markrico** [iomad/iomad#1108]
![Capture](https://user-images.githubusercontent.com/32987870/55127149-6afc9780-50cc-11e9-8272-e0d631b181a6.PNG)

I updated my Iomad to latest version. Now the  images under the tabs of the dash board are gone. Any idea what could be wrong? Thanks for any help you can give!

**Comment by turf212** [comment]
If you are not using a bootstrap 4 / boost theme then there is an issue with the .fade for the panes which hold the menu items.  I've made changes to the iomadbootstrap and iomad themes to reflect this but, if you are not using these then you will need to add

div.block_iomad_company_admin div.iomadlink_container {
    top: 0px;
    opacity: 100;
}

to your custom CSS.

**Comment by Markrico** [comment]
Hi,

Thank-you very much! Worked like a charm.

**Comment by anhnt17061986** [comment]
Hi turf212;

Thank you very much for your css code. The icon on iomad dashboard now visible.

But there something wrong with "mycourse" block; When i change tab (available course, course in progress, completed course) i must refrest or move mouse to content area to view course. It's like iomad dashboard block.

![image](https://user-images.githubusercontent.com/49820468/56461507-819dc200-63de-11e9-9f90-ce81b50a517b.png)


Please help us to fix this bug.

Best Regards.

**Comment by turf212** [comment]
fixed in #1119
