### ISSUE TITLE
Event restore data must contain key companyid

### ISSUE THREAD

**Issue by ni-ght** [iomad/iomad#1109]
Hello,

When debugging is active, the following error can be seen in livelog:

Event restore data must contain key companyid
line 398 of /lib/classes/event/base.php: call to debugging()
line 132 of /admin/tool/log/store/standard/classes/log/store.php: call to core\event\base::restore()
line 78 of /admin/tool/log/store/standard/classes/log/store.php: call to logstore_standard\log\store->get_log_event()
line 332 of /report/loglive/classes/table_log.php: call to logstore_standard\log\store->get_events_select()
line 1630 of /lib/tablelib.php: call to report_loglive_table_log->query_db()
line 112 of /report/loglive/classes/renderer.php: call to table_sql->out()
line 62 of /report/loglive/classes/renderer.php: call to report_loglive_renderer->render_table()
line 426 of /lib/outputrenderers.php: call to report_loglive_renderer->render_report_loglive()
line 88 of /report/loglive/index.php: call to plugin_renderer_base->render()

Seems to be the same error captured in the testing suite:
[https://github.com/iomad/iomad/files/1304898/iomad-phpunit-failures.txt](url)

Many thanks.

**Comment by turf212** [comment]
Which branch is this in?  (So I can go and look)

Thanks!

**Comment by turf212** [comment]
Also, what were the steps you used to get the debug info?

**Comment by ni-ght** [comment]
Hello,

IOMAD_36_STABLE - Moodle 3.6.3 (Build: 20190311)

Site administration > Development > Debugging
Debug messages: DEVELOPER
Display debug messages: Yes

Site administration > Reports > Live logs

Many thanks!

**Comment by turf212** [comment]
Thank you.  Fixed in code and pushed to live branch.
