### ISSUE TITLE
Add report only type roles to Iomad

### ISSUE THREAD

**Issue by turf212** [iomad/iomad#1112]
Add client reporter which is like client admin but just for reports and companyreporter which is like department manager but only has access to reports.

**Comment by moxxuk** [comment]
I now get an error on a fresh install:

**Debug info:** Duplicate entry 'companyreporter' for key 'mdl_role_sho_uix'
INSERT INTO mdl_role (name,shortname,description,archetype,sortorder) VALUES(?,?,?,?,?)
[array (
0 => 'Compny Reporter Only',
1 => 'companyreporter',
2 => 'Iomad Company Report Only - similar to the company manager role but allows for access to the company reports only',
3 => 'companyreporter',
4 => '15',
)]
Error code: dmlwriteexception

**Stack trace:**
line 489 of /lib/dml/moodle_database.php: dml_write_exception thrown
line 1329 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()
line 1375 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->insert_record_raw()
line 1283 of /lib/accesslib.php: call to mysqli_native_moodle_database->insert_record()
line 275 of /lib/db/install.php: call to create_role()
line 1732 of /lib/upgradelib.php: call to xmldb_main_install()
line 276 of /admin/index.php: call to install_core()

**Comment by turf212** [comment]
fixed under #1114
