### ISSUE TITLE
Duplicate companies after upgrade

### ISSUE THREAD

**Issue by rmeske** [iomad/iomad#1113]
I upgraded from the 35 stable branch to the 36 stable branch this week.  I had 1 company that had 3 child companies and another company with no child companies.  

On the main IOMAD Admin Dashboard, the drop-down correctly show the list of companies.

When I go to Manage companies, I am seeing the 3 child companies repeated 3 times under the parent company, like below.

Parent Company
 - Child 1
 - Child 2
 - Child 3
 - Child 1
 - Child 2
 - Child 3
 - Child 1
 - Child 2
 - Child 3

If I click Manage company for any of the duplicate Child companies it appears to take me to the correct location.  So it seems that only the listing of the Child companies is incorrect.

**Comment by turf212** [comment]
Sounds like this is an issue with the new child companies layout on the manage companies page rather than the companies themselves being changed.  Thanks for reporting.  I'll get this looked at.

**Comment by rmeske** [comment]
I added another company today and now it shows all the Child companies repeated 4 times.  So the repeat seems to be tied to the number of child companies.

**Comment by cmersinli** [comment]
+1

**Comment by rmeske** [comment]
Is there a time frame we can expect a fix or this?

**Comment by turf212** [comment]
Yes.  I've just pushed a fix.
