### ISSUE TITLE
Create categories under a company

### ISSUE THREAD

**Issue by rmeske** [iomad/iomad#1115]
I have setup a structure of Parent company with Child companies.  
 - Courses are created and assigned to the Parent company and then set to Closed sharing.
 - Courses are then assigned to Child companies based on which courses they should have access to.

For those students that are at the Parent company level they do see all courses listed under the Available Courses, which is expected.

For those students that are at the Child company level they do see all courses assigned to the Child company under the Available Course which is expected.

What I would like to do is be able to create child categories under the Parent company and Child companies so that courses can be organized by a topic.  Thus creating a course catalog that can be browsed and self-enroll in courses.

I tried create sub-categories under the Parent Company and moved the courses into those companies, but Categories are not used in the Available Courses list.  When I added the courses block to the default dashboard it is showing all the sub-categories of the Parent company to users that are in a Child company.  This seems to imply sub-categories cannot be used the way I intended to build a topic catalog of courses for each company.

I did look at using departments but those don't show in the list of courses.

Is there a way to accomplish what I am trying to do?

**Comment by rmeske** [comment]
Thought I would check in on this and see if there is a way to do this.

**Comment by pradeepchittimodu** [comment]
Hi friends 

How  can we create a Child companies in iomad

**Comment by jbrodo** [comment]
This is an important thread. How we can visualize sub categories courses in the home page?

**Comment by turf212** [comment]
Child companies can be created in the IOMAD dashboard.  Course categories which are under the company category appear as normal to users so they can browse them.  Functionality has been available for a while now.
