### ISSUE TITLE
Upgrade from 3.3.5+ to IOMAD_35_STABLE: Coding error in block_iomad_company_admin

### ISSUE THREAD

**Issue by erazorbg** [iomad/iomad#1116]
Discovered while trying to upgrade from IOMAD_33_STABLE that is at version 3.3.5+ to the current IOMAD_35_STABLE.

`Capability 'block/iomad_company_admin:block/iomad_company_admin:edituserpassword' was not found!`

Updating to the latest IOMAD_33_STABLE works fine, so one workaround is to do a two step update, first to the latest IOMAD_33_STABLE, and then to IOMAD_35_STABLE. 
Another is to comment out the section of (blocks/iomad_company_admin/db/upgrade.php) that is causing the error and manually update the roles.

The full error message:
```
-->block_iomad_company_admin
Default exception handler: Coding error detected, it must be fixed by a programmer: Capability 'block/iomad_company_admin:block/iomad_company_admin:edituserpassword' was not found! This has to be fixed in code. Debug:
Error code: codingerror
* line 1319 of /lib/accesslib.php: coding_exception thrown
* line 132 of /blocks/iomad_company_admin/db/upgrade.php: call to assign_capability()
* line 1005 of /lib/upgradelib.php: call to xmldb_block_iomad_company_admin_upgrade()
* line 514 of /lib/upgradelib.php: call to upgrade_plugins_blocks()
* line 1857 of /lib/upgradelib.php: call to upgrade_plugins()
* line 182 of /admin/cli/upgrade.php: call to upgrade_noncore()
```

**Comment by turf212** [comment]
Thanks for reporting.  I'll get this checked for you.

**Comment by erazorbg** [comment]
I must investigate further, but would this be a bug introduced with this change to assign_capability() (e389c5cd317ff79610fbe1c3dc8fcb5da06bb10c) in Moodle?  - https://tracker.moodle.org/browse/MDL-64971

The function was updated in 3.4, 3.5 and 3.6 branches, which would also explain why updating to 3.3 worked for me, but not to 3.5.

**Comment by tminina** [comment]
Hello,
Upgrading from 3.4 to 3.6.3
Have the same error. Any suggestions?

**Comment by edloomio** [comment]
We've been struggling with this issue and have temporarily a nasty quick fix that will perform the upgrade BUT WE DO NOT RECOMMEND IT as we don't have a clear view how this inflicts the rest. Attached replace the file with the file in your update folder. It's located in /blocks/iomad_company_admin . Then perform the upgrade. 
[company_edit_form.zip](https://github.com/iomad/iomad/files/3165337/company_edit_form.zip)

Again, at your own risk.
Cheers,
Johan

**Comment by tminina** [comment]
Thanks a lot for the help!

Tatiana

Sent from my ASUS

-------- Original Message --------

**Comment by turf212** [comment]
@tminina Are you upgrading from 3.4 latest or some revisions behind?

**Comment by edloomio** [comment]
Hi Derick,
We're upgrading from 3.1.
Cheers,
Johan

**Comment by turf212** [comment]
It does look like we are failing foul of the assign capability check.  The 3.6 branch completely redoes how the Iomad roles are defined and what capabilities are assigned to them.  We've added them to core and given them their own archetype to prevent this from causing chicken/egg issues on upgrades and installs.

I've regressed the Moodle fix in 3.4 and 3.5 so that their is no check.  Please use latest versions of these branches or 3.6 (which is now at 3.6.4)

**Comment by tminina** [comment]
> @tminina Are you upgrading from 3.4 latest or some revisions behind?

Yes, @turf212, I am moving from 3.4 to 3.6.3. I commented three functions that stopped the update and got to the point when the page showed only the message, that the website is under update with the invitation to come later. 
As a result, I installed an empty Iomad 3.6.3 and pointed it to the empty DB. My DB is in the MS SQL Server. I am building an SSIS package to move data from the existing DB to the new one. All goes well except the Role tables. They have discrepancies which I have to fix manually. 
In my DB:
![image](https://user-images.githubusercontent.com/22622677/57780899-29b15d00-76f7-11e9-86a8-8bed6bc1e4c8.png)
Which is not the same that in an empty new. 
Similar situation with the functions tables. 

Last year the migration was from 2.7 to 3.4

**Comment by thierryVergult** [comment]
Same issue here when upgrading from 3.3.4 to 3.6.5

Please advice

**Comment by turf212** [comment]
If you upgrade to the latest 3.3 branch first and then 3.6 does it work?  (This is the path we have used with our clients and no issues so far).

**Comment by thierryVergult** [comment]
We opted to comment out the part giving the error, and will create the capabilities edituserpassword, 
deleteuser & suspenduser for the roles clientadministrator, companymanager & companydepartmentmanager.

change was in the file ../iomad-IOMAD_36_STABLE/blocks/iomad_company_admin/db/upgrade.php

**Comment by royko** [comment]
You may want to comment on this Moodle tracker issue, which is likely related:
[https://tracker.moodle.org/browse/MDL-65668](https://tracker.moodle.org/browse/MDL-65668)

**Comment by fryeguy63** [comment]
As noted by thierryPopay above, I opted to comment out the part giving the error, including the capabilities edituserpassword,
deleteuser & suspenduser for the roles clientadministrator, companymanager & companydepartmentmanager.

I am upgrading the 3.8 so I edited this out of the file ../iomad-IOMAD_38_STABLE/blocks/iomad_company_admin/db/upgrade.php and my upgrade was sucessful.

Now I'm not sure about how to proceed in creating these capabilities manually. Can someone point me to the process?

**Comment by turf212** [comment]
You can add the capability back in by going to Site administration -> users -> permissions -> define system roles and then editing the affected roles.  I think these capabilities may no longer be on the system, however, so it's likely a non issue.

**Comment by accena-group** [comment]
I am upgrading currently from 3.6.3 to 3.9 and I am getting this same error.

![image](https://user-images.githubusercontent.com/36938919/102376091-7ec2ee00-3f80-11eb-84e8-bb2b83932742.png)

I'd rather not comment out the capabilities. Is the zip file from above still the only fix for this?

Just FYI, I am unable to upgrade from 3.6.3 to 3.6.10 first because I have mysql 8 and php7.4, and 3.6.10 won't accept php7.4 and my database won't work with php7.0.

Any help is greatly appreciated!

**Comment by turf212** [comment]
If you comment out the capabilities you can fix it later in the site admin menus.  This code is simply trying to add new functionality to the company manager roles automatically.  FYI when you edit the roles you can click on the Show advanced button which will show you what the default role capability would have been.  (You can also reset the role but that will remove any changes you have made to it).

**Comment by accena-group** [comment]
Ok, thank you! - I will do that then.
