### ISSUE TITLE
Version 3.4,3.5 and 3.6 of blocks/iomad_company_admin/db/upgrade.php are missing a fix from 3.3

### ISSUE THREAD

**Issue by erazorbg** [iomad/iomad#1117]
Discovered while trying to figure out #1116 

The fix from cf9f8e216511b21eaa521ddda385487341c23fb9 introduced in IOMAD_33_STABLE is not present in blocks/iomad_company_admin/db/upgrade.php in the newer branches IOMAD_34_STABLE, 35 and 36

This causes an error during upgrade for databases other than MySQL.

**Comment by edloomio** [comment]
W're updating from 3.1.5 to latest 3.6 and getting the error of #1116 . We tried the fix from cf9f8e2 but it doesn't help, the error remains. We keep digging...

**Comment by turf212** [comment]
I'll get this checked and tested against PostgreSQL.  Which database are you using?

**Comment by turf212** [comment]
Looks like a bad merge.  It only has the version upgrade.  None of the code changes.

**Comment by turf212** [comment]
I've added this to the 3.4, 3.5 and 3.6 branches.  Thank you for reporting it!

**Comment by erazorbg** [comment]
> 
> 
> I'll get this checked and tested against PostgreSQL. Which database are you using?

I am using PostgreSQL, thanks for the quick fix!
