### ISSUE TITLE
Moodle Workplace vs IOMAD

### ISSUE THREAD

**Issue by rmeske** [iomad/iomad#1118]
I understand that IOMAD had an influence on the development of Moodle Workplace.  

What is the future of IOMAD, will it become just a branded version of Moodle Workplace?

**Comment by turf212** [comment]
Hi there, 
Iomad as a product was developed in-house by E-Learn Design approximately 10 years ago (it was originally called Perficio), long before Workplace.  I can assure you that Iomad will remain a product of its own accord and will *always* remain fully open source.  Iomad is definitely here to stay and E-Learn Design will continue to develop, maintain and support it:-)

**Comment by ghost** [comment]
++1 

Very glad to hear this. Keep up the great work.

**Comment by edloomio** [comment]
And a major difference is IOMAD is open source and Workplace will not. With ❤️
Cheers,
Johan

**Comment by turf212** [comment]
Thank you all!

**Comment by tsmbabu** [comment]
Hi, Will IOMAD keep pace with Moodle core version which is 3.7 now?
