### ISSUE TITLE
'mycourse' block bug

### ISSUE THREAD

**Issue by anhnt17061986** [iomad/iomad#1119]
Hi 

There something wrong with "mycourse" block; When i change tab (available course, course in progress, completed course) i must refrest or move mouse to content area in order block shows course .

![image](https://user-images.githubusercontent.com/49820468/56461567-464fc300-63df-11e9-8475-aa4c4ab14047.png)

Please help us to fix this bug.

Best Regards.

**Comment by turf212** [comment]
This also looks to be a CSS issue with the older bootstrap 3 themes.  If you add

#mycourses_available_view, #mycourses_inprogress_view, #mycourses_completed_view {
    opacity: 1;
}

to your theme custom CSS it will work.  I'll add these to the default Bootstrap 3 themes for Iomad too and push.
