### ISSUE TITLE
Unable to install Iomad 36 stable

### ISSUE THREAD

**Issue by nickjkings** [iomad/iomad#1120]
I have git cloned the source into the web directory, but the installation process is not fully proceeding

Initial page does not have the correct styling:
![2019-04-23](https://user-images.githubusercontent.com/49906805/56577713-8ff90300-65c3-11e9-99b0-1d900408c4c3.png)

The second page is not even detecting the correct environment:
![2019-04-23 (1)](https://user-images.githubusercontent.com/49906805/56577757-bc148400-65c3-11e9-88a0-86f5d4cf94dd.png)

The PHP environment is shown at http://campus.courseindex.com/i.php , and that satisfies the moodle 3.6 requirements

Can you please suggest what the issue may be?

**Comment by turf212** [comment]
I have to confess to never installing Moodle or Iomad without copying the config-dist.php file to config.php and changing the values inside this directly.  You are installing this on your local host so you will have access to that.  This skips all of the "question" parts as it builds the config file.

I've just checked this on latest 3.6 branch and it looks like it should

![image](https://user-images.githubusercontent.com/1685229/57067447-f3bbb400-6cc6-11e9-9167-2bcfdbafe5da.png)

Could be something not caching properly.  Check the permissions on your moodledata directory.
