### ISSUE TITLE
Email templates list does not retain slider values - non English site.

### ISSUE THREAD

**Issue by ni-ght** [iomad/iomad#1129]
Kind and dear Sirs,

It seems there is a problem with retaining slider values for the email templates list page 'local/email/template_list.php'. The problem is encountered with IOMAD_36_STABLE, for sites with non-English default languages.

It is as if '$CFG->lang' is used when reading the template settings from the DB, whereas the optional page parameter 'lang' is used when saving. The optional parameter seems not to be passed to the page, and hence defaults to 'en'.

Many thanks.

**Comment by turf212** [comment]
I've changed the logic so that it uses the SESSION language (so the drop downs for the language switchers work) or falls back to the site default or the selected language from the specific template.
