### ISSUE TITLE
SQL query issue in Shop block for PGSQL Database

### ISSUE THREAD

**Issue by syedmahtab** [iomad/iomad#114]
I have installed iomad 2.6.2 and enabled e-commerce. I added an e-commerce block to home page. When I click 'shop' link in the block I get an error as follows:
# 

Debug info: ERROR: column "c.fullname" must appear in the GROUP BY clause or be used in an aggregate function
LINE 9: ORDER BY c.fullname
^
SELECT COUNT(*) FROM mdl_course_shopsettings css
INNER JOIN mdl_course c ON c.id = css.courseid

LEFT JOIN mdl_course_shopblockprice sbp ON c.id = sbp.courseid
AND sbp.id = (SELECT id FROM mdl_course_shopblockprice
WHERE courseid = c.id ORDER BY price LIMIT 0 OFFSET 1 )
WHERE css.enabled = 1

ORDER BY c.fullname
[array (
)]
Error code: dmlreadexception
Stack trace:

```
line 443 of /lib/dml/moodle_database.php: dml_read_exception thrown
line 239 of /lib/dml/pgsql_native_moodle_database.php: call to moodle_database->query_end()
line 744 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
line 1428 of /lib/dml/moodle_database.php: call to pgsql_native_moodle_database->get_records_sql()
line 1501 of /lib/dml/moodle_database.php: call to moodle_database->get_record_sql()
line 1672 of /lib/dml/moodle_database.php: call to moodle_database->get_field_sql()
line 161 of /blocks/iomad_commerce/shop.php: call to moodle_database->count_records_sql()
```
# 

Could not correct the error myself so am submitting the issue to get that corrected.
Regards,
Mahtab

**Comment by turf212** [comment]
Thanks for raising this.  Will look into this and get back to you.

**Comment by turf212** [comment]
The SQL statement should have a group by clause in it.  The lines from 150 on should read as follows.

$sql = 'FROM {course_shopsettings} css
            INNER JOIN {course} c ON c.id = css.courseid ' . $sharedsql .'
            ' . $tagjoin . '
            LEFT JOIN {course_shopblockprice} sbp ON c.id = sbp.courseid
                                                  AND sbp.id = (SELECT id FROM {course_shopblockprice}
                                                  WHERE courseid = c.id ORDER BY price LIMIT 0,1 )
        WHERE css.enabled = 1
        ' . $tagwhere . $searchwhere . '
        GROUP BY c.fullname
        ORDER BY c.fullname';

Notice the extra GROUP BY clause in there.  I'll fix this and push it but if you could please confirm that that patch works by changing the line?

Thanks

Derick

**Comment by turf212** [comment]
fixed and pushed.

**Comment by syedmahtab** [comment]
May you live in peace Derick!

Thanks heaps for your time and effort. I added the line 'GROUP BY c.fullname' and tried but having no luck. Please find below the error details:

Error reading from database

More information about this error
Debug info: ERROR: LIMIT #,# syntax is not supported
LINE 6: ... WHERE courseid = c.id ORDER BY price LIMIT 0,1 ...
^
HINT: Use separate LIMIT and OFFSET clauses.
SELECT COUNT(*) FROM mdl_course_shopsettings css
INNER JOIN mdl_course c ON c.id = css.courseid

LEFT JOIN mdl_course_shopblockprice sbp ON c.id = sbp.courseid
AND sbp.id = (SELECT id FROM mdl_course_shopblockprice
WHERE courseid = c.id ORDER BY price LIMIT 0,1 )
WHERE css.enabled = 1

GROUP BY c.fullname
ORDER BY c.fullname
[array (
)]
Error code: dmlreadexception

This occurs just for PostGREsql NOT for MySQL databases.

Warm regards,
Mahtab
