### ISSUE TITLE
Assign course license to user throws exception

### ISSUE THREAD

**Issue by philipp-ranft** [iomad/iomad#1140]
Hi,

we are seeing an exception on assigning course licenses to a user. The issue appears on creating a user through the Iomad dashboard while assigning a license and courses to the user. The issue also appears through editing the course license of a user (Iomad Dashboard -> Users -> Edit users -> User controls -> Change course licenses -> Enrol one or multiple licenses).

This is the exception that is thrown:
```
Exception encountered in event observer 'local_iomad_observer::user_license_assigned': Field "courseid" does not exist in table "iomad_learningpathcourse"
line 1350 of /lib/dml/moodle_database.php: call to moodle_database->where_clause()
line 2351 of /local/iomad/lib/company.php: call to moodle_database->get_records()
line 3706 of /local/iomad/lib/company.php: call to company::license_ok_to_use()
line 237 of /local/iomad/classes/observer.php: call to company::user_license_assigned()
line ? of unknownfile: call to local_iomad_observer::user_license_assigned()
line 155 of /lib/classes/event/manager.php: call to call_user_func()
line 75 of /lib/classes/event/manager.php: call to core\event\manager::process_buffers()
line 835 of /lib/classes/event/base.php: call to core\event\manager::dispatch()
line 356 of /blocks/iomad_company_admin/company_users_licenses_form.php: call to core\event\base->trigger()
line 467 of /blocks/iomad_company_admin/company_users_licenses_form.php: call to company_users_course_form->process()
```

We are using the latest version of the `IOMAD_36_STABLE` branch.

I was able to fix this issue by changing following line: https://github.com/iomad/iomad/blob/IOMAD_36_STABLE/local/iomad/lib/company.php#L2351
from
`if (!$DB->get_records('iomad_learningpathcourse', array('courseid' => $courseid))) {`
to
`if (!$DB->get_records('iomad_learningpathcourse', array('course' => $courseid))) {`

Should I just create a PR here on GitHub for that?

Best regards,
Philipp

**Comment by semteacher** [comment]
@Philipp-Navis Thank, you. Got same issue Your recipe is helpful!
In addition I noticed about following error messages:

> Notice: Use of undefined constant id - assumed 'id' in
> /var/www/html/moodle/enrol/license/lib.php
> on line 223
> Notice: Object of class stdClass could not be converted to int in
> /var/www/html/moodle/enrol/license/lib.php
> on line 223
> Warning: A non-numeric value encountered in
> /var/www/html/moodle/enrol/license/lib.php
> on line 223

So, look like typo error has available in mentioned above position of /var/www/html/moodle/enrol/license/lib.php file:
`if (!company::license_ok_to_use($license-id, $instance->courseid, $USER->id)) {`
And I fixed it to
`if (!company::license_ok_to_use($license->id, $instance->courseid, $USER->id)) {`

**Comment by turf212** [comment]
Thank you both.  I've changed the code and commited/pushed.
