### ISSUE TITLE
Permissions not applied correctly in reports

### ISSUE THREAD

**Issue by andrewhancox** [iomad/iomad#1141]
In most of the reports e.g local/report_completion_monthly/index.php line 185 there is a block of code:
```
if (iomad::has_capability('block/iomad_company_admin:edit_all_departments', $systemcontext) ||

    !empty($SESSION->currenteditingcompany)) {

    $userhierarchylevel = $parentlevel->id;

} else {

    $userlevel = $company->get_userlevel($USER);

    $userhierarchylevel = $userlevel->id;

}

if ($departmentid == 0 ) {

    $departmentid = $userhierarchylevel;

}
```
From what I can see $SESSION->currenteditingcompany is always set to the user’s assigned company - local/iomad_signup/login.php:54
`$SESSION->currenteditingcompany = $company->id;`
So the else statement will never get hit.
This has the effect that even when a user is assigned as a manager at the department level (Company Department Manager role) they still initially see all department's data when they hit these reports (e.g report_completion_monthly). 

From you email:
That code is likely in quite a lot of places and the issue is fall out from changes to the login process which sets the company id for the user.  We should have already set the companyid before this code, or forced an admin or capable user to choose one (which is the only case when the company id isn't set on log or at least not set to the current company (which is why the session check).  I can likely be refactored from :

```
if (iomad::has_capability('block/iomad_company_admin:edit_all_departments', $systemcontext) ||
!empty($SESSION->currenteditingcompany)) {
$userhierarchylevel = $parentlevel->id;
} else {
$userlevel = $company->get_userlevel($USER);
$userhierarchylevel = $userlevel->id;
}
```

to just 

```
$userlevel = $company->get_userlevel($USER);
$userhierarchylevel = $userlevel->id;
```

without any of the checks as these are being done already on the get_my_companyid() and get_userlevel() calls, although the get_userlevel() call doesn't check for the edit_all_departments capability, so that would need added too.

**Comment by turf212** [comment]
I've refactored the standard reports to the suggestion I made yesterday and have updated the get_userlevel function to also include the missing capability.  Tested this with a department manager and all appears to be working as expected.
