### ISSUE TITLE
Latest IOMAD Moodle Version 3.6.4+ (Build: 20190628) Company Managers can see all participants

### ISSUE THREAD

**Issue by Blacksheeprules** [iomad/iomad#1146]
Hi,

Since I have updated to the newest IOMAD code I have noticed that a Company Manager can see all of the Companies when he views Participants or the grade book. I used the latest code from July 3, 2019 Latest IOMAD Moodle Version 3.6.4+ (Build: 20190628).

Thanks in advance for any help you can provide on this issue.

**Comment by turf212** [comment]
This would be in a shared course?  Forced separate groups should be set on the course and the company manager's course role (likely client course access) should not have the capability to see all groups.  This breaks the multi-tenancy.

**Comment by Blacksheeprules** [comment]
Hi,

Thank-you very much. I changed the course setting to force separate groups
and it fixed both issues.
