### ISSUE TITLE
local_iomad_track\observer::user_enrolment_created() - Duplicate value - IOMAD_36_STABLE

### ISSUE THREAD

**Issue by ni-ght** [iomad/iomad#1147]
Dear Sirs,

There probably is typo in line 488 of '/local/iomad_track/classes/observer.php':
```
if ($companies = $DB->get_records_sql("SELECT cu.* FROM {company_users} cu
  JOIN {company_course} cc on (cu.companyid = cu.companyid)
```

Should say:
```
  JOIN {company_course} cc on (cu.companyid = cc.companyid)
```
When I try using the API call:
`\company_user::enrol($userid, array($courseid), $company->id, 0, $group->id);`

I get:
`PHP Notice:  Did you remember to make the first column something unique in your call to get_records? Duplicate value `

Many thanks.

**Comment by turf212** [comment]
*cough* yes.  Thanks for reporting.
