### ISSUE TITLE
problem "block_iomad_company_admin_create_companies" service

### ISSUE THREAD

**Issue by fsaravi** [iomad/iomad#1149]
when i use "block_iomad_company_admin_create_companies" service for creating a new company, this works without any problem.
but when i want to add childs to the newly created company this error shows:

Notice: Trying to get property 'uselogo' of non-object in C:\xampp\htdocs\iomad\blocks\iomad_company_admin\company_edit_form.php on line 176
Notice: Trying to get property 'usesignature' of non-object in C:\xampp\htdocs\iomad\blocks\iomad_company_admin\company_edit_form.php on line 177
Notice: Trying to get property 'useborder' of non-object in C:\xampp\htdocs\iomad\blocks\iomad_company_admin\company_edit_form.php on line 178
Notice: Trying to get property 'usewatermark' of non-object in C:\xampp\htdocs\iomad\blocks\iomad_company_admin\company_edit_form.php on line 179
Notice: Trying to get property 'showgrade' of non-object in C:\xampp\htdocs\iomad\blocks\iomad_company_admin\company_edit_form.php on line 180

i figure out that this problem is because of when company is created with "web service" one row should create in "mdl_companycertificate" table but it doesn't.

thank you

**Comment by nileshnpathade** [comment]
Hi 

I am trying to call this API and showing me error. pelase let me know what is error. 

I am using IOMAD 3.8.+

<?php
/// SETUP - NEED TO BE CHANGED
$token = '737a60f427dd055e2825ddd69f022e';
$domainname = 'http://localhost/iomad';
$functionname = 'block_iomad_company_admin_create_companies';	
$restformat = 'json'; 

$param = array();			
$param['companies'][0]['name']= 'India Pvt Ltd';
$param['companies'][0]['shortname']= 'INDIAPVTLTD';
$param['companies'][0]['city']= 'PUNE';
$param['companies'][0]['country']= 'INDIA';
$param['companies'][0]['parentid']= 0;			

header('Content-Type: text/plain');
$serverurl = $domainname . '/webservice/rest/server.php'. '?wstoken=' . $token . '&wsfunction='.$functionname;
require_once('./curl.php');

$curl = new curl;

$restformat = ($restformat == 'json')?'&moodlewsrestformat=' . $restformat:'';
$resp = $curl->post($serverurl . $restformat, $param);		// For get course detaile by field (core_course_get_courses)
print_r(json_decode($resp)); exit();

******************************

ERROR IS : 

stdClass Object
(
    [exception] => invalid_parameter_exception
    [errorcode] => invalidparameter
    [message] => Invalid parameter value detected
)

Please correct me if I am wrong Here..........
