### ISSUE TITLE
problem in response of "block_iomad_company_admin_enrol_users" service

### ISSUE THREAD

**Issue by fsaravi** [iomad/iomad#1152]
when i send  "block_iomad_company_admin_enrol_users" service, it works but response is like this:
{
    "exception": "invalid_response_exception",
    "errorcode": "invalidresponse",
    "message": "Invalid response value detected",
    "debuginfo": "Only arrays\/objects accepted. The bad value is: '1'"
}

thank you.

**Comment by turf212** [comment]
Its sending a true.  It should be sending an appropriate response.  I'll get it changed.

**Comment by turf212** [comment]
Actually the true is valid but it doesn't match the expected return definition.  I'll change that.
