### ISSUE TITLE
company vs child company vs department

### ISSUE THREAD

**Issue by fsaravi** [iomad/iomad#1163]
Hi
I have some questions about iomad

what is difference between company, child company and department?
can i access all users in child companies when i logged in as parent company admin?

i notice that in database two table exists. one for departments and another for companies.
when i add a company or child company, it adds a row in company table and another in department table but when i add a department it only adds in departments table.

i saw there is no web service for adding department in a company.
what can i do about it. can i add child company for this or not?

thank you for your help.

**Comment by turf212** [comment]
Companies are entities which can have departments in them.  The departments are the same as the organisational chart within a company, or can be used for grouping users into similar sections.  You can have a department manager who can only manage their own department, or sub departments from there.  These are used for management and reporting.

Child companies are separate company instances, with their own department structure, which can have their own theme definitions and company attributes.  Company managers in the parent company are also company managers in the child company and they select which company they are working with in the same way as the site admin does.

With the right permissions, licenses can be given to the parent company and then split up amongst the child companies.  So, you can use them for re-seller purposes.  The "super" company admin needs some extra site capabilities other than the company manager role to allow this to happen, however.

The create department webservice hasn't been asked for yet.  If it's something you need you could write or sponsor it?

**Comment by fsaravi** [comment]
how can i sponsor it?

**Comment by turf212** [comment]
If you send an email to info@e-learndesign.co.uk we can pick it up from there.

**Comment by fsaravi** [comment]
what should be in that email?
