### ISSUE TITLE
upgrade to 3.6 on Oracle : ORA-00920: invalid relational operator : SELECT id FROM m_course WHERE true

### ISSUE THREAD

**Issue by thierryVergult** [iomad/iomad#1166]
The upgrade process to 3.6 on an Oracle data base errors out.

> ORA-00920: invalid relational operator : SELECT id FROM m_course WHERE true

Stack trace:
line 486 of /lib/dml/moodle_database.php: dml_read_exception thrown
line 277 of /lib/dml/oci_native_moodle_database.php: call to moodle_database->query_end()
line 1220 of /lib/dml/oci_native_moodle_database.php: call to oci_native_moodle_database->query_end()
line 1666 of /lib/dml/moodle_database.php: call to oci_native_moodle_database->get_fieldset_sql()
line 1917 of /local/iomad/db/upgrade.php: call to moodle_database->get_fieldset_select()
line 636 of /lib/upgradelib.php: call to xmldb_local_iomad_upgrade()
line 1852 of /lib/upgradelib.php: call to upgrade_plugins()
line 694 of /admin/index.php: call to upgrade_noncore()

offending php line: $validcourseids = $DB->get_fieldset_select('course', 'id', 'true');

Oracle does not supports booleans in sql. Replacing true with 1 = 1 fixes the issue.

**Comment by turf212** [comment]
Probably should leave it as PHP true (which defaults to 1 anyway) as the code will read better.  Thanks for testing.  We don;t use Oracle anywhere internally.
