### ISSUE TITLE
Typo in Restrict capabilities

### ISSUE THREAD

**Issue by rmeske** [iomad/iomad#1173]
There is a typo for the role "Compny Reporter Only".  It is missing the "a" in "Company".

This is the latest Stable 36 version as of 08/17/2019.

**Comment by turf212** [comment]
Where is the typo?  In a lang file or in the initial definition of it?

**Comment by rmeske** [comment]
My apologies for the delay.  It is in the Iomad Restrict Capabilities block.  I am not that familiar with editing the language file, but will look there.

**Comment by turf212** [comment]
lang strings were sanitised in 4.3+
