### ISSUE TITLE
migrating our moodle site to iomad

### ISSUE THREAD

**Issue by jaysonjcleofas** [iomad/iomad#1176]
is it ok to use the same database and moodledata of our moodle site when changing to iomad? or need a clean database and moodledata?

**Comment by turf212** [comment]
It's perfectly fne to use the same database and moodle data.  You just need to ensure that the version of Iomad is the same, or slightly above, the version of Moodle you have.  The Iomad code contains all of the core Moodle code so you need to make sure you are not downgrading.

**Comment by anirudh74** [comment]
I am unable to use the same database and moodledata of our moodle site when changing to iomad.
Getting "Error reading from database"
![image](https://user-images.githubusercontent.com/20712756/85948783-4d257e80-b970-11ea-82a5-46bdef6d92b8.png)

**Comment by santoshedfibre** [comment]
you need to first install block_iomad_company_admin and local_iomad plugins to create company table..

**Comment by turf212** [comment]
upgrade issues fixed a while back - the check on if IOMAD was already set up/company tables were not there on upgrade were not tight enough.
