### ISSUE TITLE
Invoice email shows html code of table instead of table

### ISSUE THREAD

**Issue by syedmahtab** [iomad/iomad#118]
Here are the steps to reproduce:
Go to shop
Select a course
Go to Checkout
Against the Payment method, select Invoice
Confirm the order.

You will receive an email. The email contains HTML code of the table rather than actual table of courses ordered. This needs to be corrected. On further probe, I found that the base method which sends the email is provide 'messagetext' parameter only and NOT the 'messagehtml' parameter. This causes the email not to display in HTML format.
I hope this is a quick fix.

Warm regards,
Mahtab

**Comment by turf212** [comment]
Thanks for raising this.  I will investigate and come back.  One thing to note is that migration of the messaging within Iomad to the new Moodle messaging system is on the development road map.

**Comment by rajephcote** [comment]
Any luck with how to fix this?

**Comment by syedmahtab** [comment]
May you live in peace!

Is there any update on this or any pointer where I can correct the issue. I actually tried adding $messagehtml parameter and setting email format to 1 but no luck.
Warm regards,

**Comment by turf212** [comment]
3.3 now allows for HTML emails so this will now work nicely.
