### ISSUE TITLE
Department manager is able to add other department users to Learning path

### ISSUE THREAD

**Issue by sumitnegi933** [iomad/iomad#1184]
**Issue:** Department manager is able to see other departments users in the potentials and added users list. He Should only see his users under both lists.

### **Step to reproduce** 

- Create a company
- Create several departments in the company
- Register users and added to respective departments
- Assign department manager to each department
- Create a learning path with Company manager and add courses into that, once you done with course listing editing then activate it.
- Login with company manager and assign Learning path to users (From different departments)
- Login with the any department manager and go to learning path
- Click on Assign students link under created learning path, now you will see the list of potential users and added users list.

**Comment by turf212** [comment]
closed under #1609
