### ISSUE TITLE
Dashboard - Manage Iomad course settings(ver3.6.6)

### ISSUE THREAD

**Issue by syusanjun** [iomad/iomad#1186]
I deleted the course in action.
Clicking the Continue button will give an error
The course cannot be deleted.

 [[couldnotdeletecourse]]
 
Debug info:
Error code: generalexceptionmessage
×Stack trace:
line 651 of /local/iomad/lib/company.php: Exception thrown
line 251 of /blocks/iomad_company_admin/iomad_courses_form.php: call to company::delete_course()

Output buffer: <div class="notifytiny debuggingmessage" data-rel="debugging">
Invalid get_string() identifier: 'couldnotdeletecourse' or component 'block_iomad_Company_admin'. 
Perhaps you are missing $string['couldnotdeletecourse'] = ''; in /lang/en/block_iomad_Company_admin.php?
<ul style="text-align: left" data-rel="backtrace">
<li>line 349 of /lib/classes/string_manager_standard.php: call to debugging()</li>
<li>line 7239 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()</li>
<li>line 651 of /local/iomad/lib/company.php: call to get_string()</li>
<li>line 251 of /blocks/iomad_company_admin/iomad_courses_form.php: call to company::delete_course()</li>
</ul></div>

**Comment by turf212** [comment]
Functionality for this has been moved to a pre_course_delete hook function which stopped the race condition you were experiencing.
