### ISSUE TITLE
Parse Error when purchasing a course in shop using paypal

### ISSUE THREAD

**Issue by syedmahtab** [iomad/iomad#119]
When I purchase a course in shop. After checkout, I provide details on the form, select PayPal as Payment method and click 'Continue'. The following error occurs:

Parse error: syntax error, unexpected 'public' (T_PUBLIC) in /home/rtwmatters/public_html/learning/blocks/iomad_commerce/checkout/paypal/paypal.php on line 21

Not sure what to do here.

**Comment by turf212** [comment]
Thanks for raising this.  I'll look into it.

**Comment by syedmahtab** [comment]
May  you live in peace!

We have developed our site using iomad. It is an excellent work particularly for its multi-tenancy and e-commerce. Now as PayPal is not working, we cannot go live. It would be great if we can get this bug resolved soon.
Or
if you can guide where the issue could be as I can try to assist in resolving the issue.

Warm regards,
Mahtab
