### ISSUE TITLE
Create course for non-admin users

### ISSUE THREAD

**Issue by cdouglas97** [iomad/iomad#1190]
Hello,
 Very new to Moodle/Iomad, using latest version.   I am attempting to create a user for a company that has permissions to create courses.  The only roles I have when I create a user under a customer are  User, department training manager, company manager, and  company report only.  I found the plugin setting that enables the "assign as educator". but that didn't enable the "create" or "edit" course block when I login with anything besides the super admin user.   Can you please let me know what I am missing?  

Thank you.

**Comment by mountbatt** [comment]
Hi, i need help on this too! Is there a solution today? @cdouglas97

**Comment by turf212** [comment]
You can add the 
block/iomad_company_admin:createcourse capability to the company manager role then they will be able to create courses.  The educator roles (defaults to company managers if you haven't used the option to have managers as ordinary users) then are given the teacher type roles (client course editor / client course access) to non licensed courses which the company has access to.

There isn't a separate Moodle educator role as these roles are applied at the course level only.  You could use one of the other company roles to allow this and assign the educator as this.  e.g. rename the department manager role in the language pack as course creator and change the caps for it.  User is then assigned as course creator and given educator role too.
