### ISSUE TITLE
Webservices: Call to undefined method block_iomad_company_admin_external::get_department_parameters()

### ISSUE THREAD

**Issue by williamwithin** [iomad/iomad#1202]
When testing out the Iomad webservice block_iomad_company_admin_get_departments as below:

`curl -g -X POST 'https://example.com/iomad/webservice/rest/server.php?wstoken=TOKEN&moodlewsrestformat=xml&wsfunction=block_iomad_company_admin_get_departments&criteria[0][key]=id&criteria[0][value]=4'`

I get the error:

`<?xml version="1.0" encoding="UTF-8" ?>
<EXCEPTION class="Error">
<MESSAGE>Call to undefined method block_iomad_company_admin_external::get_department_parameters()</MESSAGE>
</EXCEPTION>`

Note that block_iomad_company_admin_get_companies works:

`curl -g -X POST 'https://example.com/iomad/webservice/rest/server.php?wstoken=TOKEN&moodlewsrestformat=xml&wsfunction=block_iomad_company_admin_get_companies&criteria[0][key]=id&criteria[0][value]=1'`

Version shows: Moodle 3.6.5+ (Build: 20190816)

**Comment by turf212** [comment]
Typo in the externallib.php file.  Thanks for reporting!
