### ISSUE TITLE
Course not started Report Emails

### ISSUE THREAD

**Issue by Aelrath** [iomad/iomad#1204]
There is an issue I've come across where [course_not_started_warning] emails does not get sent properly under the following condition:

Course is part of license that is Instant Access : false

This results in referenced code below not picking up users that have not started the course since they still need to click the "Enroll in Course" on their dashboard. Since their timestarted is null and timeenrolled/timestarted is the key decision maker if they started in this case (both being null) rather looking at their licenseallocated time to calculate the rule defined in the course settings if "Days to email after if user has not started" is valid results in emails getting sent properly.

https://github.com/iomad/iomad/blob/af9e92f0a7bf1aceceeb9542217198f789ea9b01/local/email_reports/lib.php#L271-L275

To fix this issue on our side I have changed the code to :

`$warnnotstartedusers = $DB->get_records_sql("SELECT * FROM {local_iomad_track}
                                                   WHERE timeenrolled IS NULL
                                                   AND courseid = :courseid
                                                   AND licenseallocated < :time",
                                                   array('time' => time() - $warnnotstartedcourse->warnnotstarted * 60 * 60 *24, 'courseid' => $warnnotstartedcourse->courseid));`

This would only work for courses which licenses are Instant Access : false 
_(which all our licenses are - this type of setup creates a much richer 'Completion report by course' since you can see Not started, Still in Progress and Completed users properly, where Instant Access : true assumes all users are 'still in progress' even though they haven't even logged into system yet. )_

Possibly doing a conditional check on if course is part of Instant access license and changing the select statement accordingly might be an option (haven't had time to test a solution).

Another issue which I have seen is this report email does not follow rules set within the email template for when to resend email. This email gets generated every time the email_reports_cron runs which is every day at midnight (as default in Iomad task settings). I have not looked into fixing this our side yet but just disable the email template for the company and when we want to send reminder emails to users we enable it and it will run on the next cron interval (disabling it again next day - also had no time to test code fix for this).

**Comment by turf212** [comment]
Thanks for detailing the above.  We would also need to check for courses which were not licensed as the license allocation time for that is stored as a null.  It's fine for your case as you are only using license allocated courses.  

Something like - 

SELECT * FROM {local_iomad_track}
WHERE courseid = :courseid
AND (
(timeenrolled IS NULL AND licenseallocated < :time1 AND licenseallocated IS NOT NULL) 
||
(timeenrolled < :time2 AND timestarted = 0 AND licenseallocated IS NULL)
)

Which would allow us to match for either condition.

I'll split the other issue to it's own bug.
