### ISSUE TITLE
Prior (Before IOMAD Install) Completions Not Showing

### ISSUE THREAD

**Issue by davidpesce** [iomad/iomad#1207]
IOMAD 3.6.6 (latest as of today).

Prior completions/grades do not appear in the IOMAD Reporting. They are still there because config reports still show them (and I can see them in the DB).

**Comment by turf212** [comment]
The iomad reporting uses, for the most part, a local_iomad_track table for all of its completion information.  It requires course completion is turned on within the Moodle course and criteria added to the course completion which can be met.  If you didn't have this on your Moodle site then there isn't much for it to report on/get populated from.  If you change your course completion criteria to have something sensible.  Be careful of using just a matching grade, especially if you allow users to go back and retake activities which could affect their course grade as the record is created the instant a user meets all of the completion criteria.  We would always recommend having soemthing which act as a gatekeeper to completion such as a feedback activity.

**Comment by davidpesce** [comment]
I do have course completions turned on (prior to installing iomad as an upgrade) and those completions are not showing up in the company report.

**Comment by davidpesce** [comment]
I reset and did the upgrade again. This time I noticed an error (recoverable) within the upgrade process. See the attached image. I'm wondering if it's an issue with there being no default company when you do an upgrade to IOMAD from Moodle stock...

![iomad_upgrade-from-moodle3 4_err](https://user-images.githubusercontent.com/3988068/66774723-4a413700-ee90-11e9-9889-e888045e2147.jpg)

**Comment by davidpesce** [comment]
Is it possible to set companyid NOTNULL="false"?
https://github.com/iomad/iomad/blob/723ec38cc120d7c72ff16b88f80c98c4d6e205c7/local/iomad_track/db/install.xml#L17

Or would it be better to set it to the default companyid? Is there one?

**Comment by davidpesce** [comment]
Hi @turf212 - any thoughts on this? I'm happy to write the PR if you get me pointed in the right direction.

**Comment by turf212** [comment]
Thihnking about this, I'm wondering if we should even be doing this at install.  As you say, the company doesn't exist so we will struggle to tie the users to a company when it's not there.  Two options strike me:
1 - Build the user's report data when they are added to the company and there is no data there already. 
2 - have an admin tool to build a companies report data from the current system state.

I think 2 is probably my preferred route.  You create the company, add the users, hit a button and build the reporting data.  Does this seem like a decent workflow?  The build tool would, by necessity, need to clear anything currently down for the company first with appropriate warnings first (like the current Moodle course completion reset warnings).

**Comment by davidpesce** [comment]
Hmmm. 
> The build tool would, by necessity, need to clear anything currently down for the company first with appropriate warnings first (like the current Moodle course completion reset warnings).

For the sake of simplification, let's look at it as mdl_completion and iomad_completion (tables-ish).
mdl_completion would never be modified and only the data in iomad_completion would be wiped, correct?

Does mdl_completion contain all completions, regardless of what is in iomad_completion? If so, they really wouldn't be wiping anything out of iomad_completion, it'd be more of an update.

Thoughts?

**Comment by turf212** [comment]
mdl_completion wouldn't be cleared down, only the mdl_local_iomad_track (Iomad completion).  The risk is that that's also where we store previous course completions for users who have undertaken and then retaken the same course (which Moodle can't handle).  So, down the line, the risk is that we are removing past data and updating it with only the current data.

As I say, if there is a scary enough warning that the information is going to be wiped with no chance of recovery except restoring from backup, it would be OK.

**Comment by davidpesce** [comment]
Is there a way to handle both scenarios gracefully? 

If mdl_completion.datetime == iomad_track.datetime (or even compare datetime & grade) they are considered the same. And if it's not found in mdl_completion, leave it in iomad_track?

**Comment by turf212** [comment]
We do that in other places using enrolment time as Moodle can change the completion time.

So, go through all of the current completions and add any which don't already exist?  That way we wouldn't even need to remove anything.

**Comment by davidpesce** [comment]
I like it!

**Comment by davidpesce** [comment]
Heading to a conference and have some time to start poking around on this. A few clarification questions:
* Do you envision this as a separate local plugin? Or within local_iomad_track?
* Do you want the (re)build-company-completion "button" to be within the plugin settings or within the iomad dashboard?
* Should we set this up as a cron (mostly for larger installs where there are a lot of prior completions)? My instance only has 34 completions, so not a big deal.

Thoughts?

**Comment by turf212** [comment]
admin tool to import completion information from DB and file was added.
