### ISSUE TITLE
'Show all Courses' link on shop page does not behave correctly

### ISSUE THREAD

**Issue by syedmahtab** [iomad/iomad#121]
May you live in peace!

Hope you are fine. I found a little bug and I believe its solution too. So, I thought to share with you to confirm if it is correct.
The bug:
If we go to shop and select a shop category link. It will show the courses within that shop category and also show a link saying 'Show all courses'. Ideally, this 'Show all courses' link should show the user all the categories and all the courses but it does not.

Correction:
In shop.php, I altered the line no. 69 from:
if (isset($SESSION->shoptag)) {
to
if (isset($SESSION->shoptag)  && $_GET['tag'] != '') {

Apparently it works but I thought to get a confirmation from you.
Warm regards,
Mahtab

**Comment by syedmahtab** [comment]
I found that above correction should be 
if (isset($SESSION->shoptag)  && $SESSION->shoptag != '') {
instead of 
if (isset($SESSION->shoptag) && $_GET['tag'] != '') {
to avoid a PHP notice on the page and proper working.

**Comment by turf212** [comment]
Thank you.  I've added this to 3.6.
