### ISSUE TITLE
Small tweak to block_iomad_company_admin (uninstall references non-existent table)

### ISSUE THREAD

**Issue by davidpesce** [iomad/iomad#1210]
While troubleshooting a few other issues, I found a small bug (I think) in blocks_iomad_company_admin. 

I tried uninstalling the plugin and it failed (see attached image) due to a missing table mdl_iomad_modules.
![iomad_err](https://user-images.githubusercontent.com/3988068/66766733-d2b5dc80-ee7c-11e9-8a6a-b07afe2313c1.jpg)

In a fresh install of IOMAD 3.6.6+, there is no table with that name. Figured it's a leftover from before. Removing the following allows the uninstall to proceed: 

https://github.com/iomad/iomad/blob/723ec38cc120d7c72ff16b88f80c98c4d6e205c7/blocks/iomad_company_admin/db/uninstall.php#L26

**Comment by turf212** [comment]
I'm not even sure why that is in there.  Hang over from a very old version.
