### ISSUE TITLE
Font files missing in IomadBoost causing fallback to system

### ISSUE THREAD

**Issue by Aelrath** [iomad/iomad#1211]
Have been testing clean installs to test installation scripts and noticed that since https://github.com/iomad/iomad/commit/e4f19362efd2f40dcc8301a801da648af2cd1789 the removal of all font files in the \theme\iomadboost\fonts\* css referencing Ubuntu font (e.g .iomadlink) is falling back to system fonts like Times New Roman (my windows system) because it use to use the font in folder (ubuntu-v9-latin-regular.woff2) but cannot find it anymore.
<img width="92" alt="Capture" src="https://user-images.githubusercontent.com/7330765/66810816-48c74b80-ef30-11e9-92aa-c4bb6b138457.PNG">

**Comment by turf212** [comment]
Thanks for reporting this.  I've added the fonts back in.
