### ISSUE TITLE
Error while resetting dashboard page

### ISSUE THREAD

**Issue by Chelsy29** [iomad/iomad#1215]
Hi,

I have installed IOMAD version Moodle 3.6.6 (Build: 20190909) and restored the database of Moodle 3.5+ on IOMAD.

Issue: I am not able to reset the dashboard.I'm getting the below error when I'm clicking on the dashboard after resetting the dashboard for all users.

![image](https://user-images.githubusercontent.com/56966301/67490420-d8879b00-f690-11e9-8718-170e30b01ed1.png)

Debug info:

Invalid parameter value detected
File: /lib/externallib.php
Line: 332
Missing required key in single structure: classification
Error code: invalidparameter
* line 332 of /lib/externallib.php: invalid_parameter_exception thrown
* line 223 of /lib/externallib.php: call to external_api::validate_parameters()
* line 59 of /lib/ajax/service.php: call to external_api::call_external_function()

Please help me to resolve this.

Thanks,
Chelsy

**Comment by turf212** [comment]
As per the ticket you raised with us, the issue appears to be around a block you had installed under Moodle which may not exist in the Iomad code you swapped it with.  You can reset everyone's dashboard to __default under the mdl_my_pages table, which undoes anyone's changes.  Or you can install whatever block is missing (check site admin -> plugins -> plugins overview -> additional plugins) and re-install it and try again.

**Comment by Chelsy29** [comment]
Hi Derick,

Thanks for the information!!!
And it worked...

Thanks 
Chelsy
