### ISSUE TITLE
Error in "License allocations report" for licenses of type "program = yes"

### ISSUE THREAD

**Issue by pozor** [iomad/iomad#1220]
Local Plugin report_license_usage, only for licenses of type "program = yes", return this error:

> Unsupported operand types
> 
> Debug info:
> Error code: generalexceptionmessage
> Stack trace:
> line 413 of /local/report_license_usage/index.php: Error thrown

Lines 413/414:
`$numallocations = $allocations / $coursecount;`
`$numunallocations = $unallocations / $coursecount;`

$allocations and $unallocations are arrays (return of $DB->count_records_sql) and should be integers.

I fixed replacing (line 401):
`$allocations = $DB->get_records_sql("SELECT * FROM {local_report_user_lic_allocs}`
with:
`$allocations = $DB->count_records_sql("SELECT count(*) FROM {local_report_user_lic_allocs}`
and (line 407):
`$unallocations = $DB->get_records_sql("SELECT * FROM {local_report_user_lic_allocs}`
with:
`$unallocations = $DB->count_records_sql("SELECT count(*) FROM {local_report_user_lic_allocs}`

**Comment by turf212** [comment]
Thanks for this.  It looks like I'd changed it for ordinary types but missed the program type.  Ooops.
