### ISSUE TITLE
Iomad bulk user upload via csv is not sending out new user emails if a password is defined

### ISSUE THREAD

**Issue by nielsharma** [iomad/iomad#1226]
A random password is generated and the user account is created if there is no password defined in the csv. The 'Create password if needed and send via email' option needs to be selected - The account creation email is sent to the new user. The email can be seen in the Outgoing email report.

If a password is defined in the csv and either option ('Create password if needed and send via email' or 'Field required in file') is selected, the user account is created and can log in using the password defined in the csv, but no account creation email is sent to the new user. There is no record in the Outgoing email report either.

(Moodle 3.6.6)

**Comment by turf212** [comment]
That is correct and it mimic's Moodle's behaviour here.  The password is not sent out as the password is known to the person who created the accounts (its on their CSV file) and they can let the users know.

**Comment by nielsharma** [comment]
Thanks Derick,

Would it be possible to trigger the automated email to send even if the password is defined in the csv file? This would save me from emailing each student manually and will also help us resolve log in issues if we knew what the students password was.
