### ISSUE TITLE
Upload users to departments

### ISSUE THREAD

**Issue by malinskyt** [iomad/iomad#1227]
Hi,
I have a few (12) companies and inside cca 77 department and 6000 subdep. 

How can i import my database of users from moodle. 

I try it with new users in IOMAD, but when i download new users to xlsx - dont have some informations about their dep. and companies.
![image](https://user-images.githubusercontent.com/54175727/68532231-17695200-031b-11ea-9594-b178733e166f.png)
This image was after export from IOMAD. Student user isin company and subdepartment too. but i dont see any information in csv file after export.

I try fill shortname to institution and dep, but dont go it. New users are in moodle systems, but in IOMAD nothing after import. It is very sad, beccause dont be possible use with many separate users.

Can you help me please?
Tomas

**Comment by williamwithin** [comment]
Like @malinskyt  I also have a large number of companies, departments, and users I would like to import. It seems like the only way currently is to manually create the hierarchy and import users, which is unworkable. 

At minimum I would need an SQL template for creating the company hierarchy, as I haven't dug deep into the database yet to see all the tables where records need to be inserted.

The other way to accomplish this would be to use the Webservices API functions, but there are required functions that do not exist yet in Iomad, such as "Assign user to department"

It would be great to hear back from the Iomad team about how to best import an entire hierarchy of companys/departments/users. This is a major blocker for me in implementing Iomad as a LMS

**Comment by williamwithin** [comment]
Disregard what I wrote before. I'm just starting to figure this out!

From what I can tell, when you import users with CSV import, that is only affecting the core Moodle users table. There are different tables that Iomad uses to assign users to companies and departments.

I'm no expert, but I think the way to accomplish this would be to use the Webservices API functions. What you are looking for is block_iomad_company_admin_assign_users "Assign users to a company", where you can assign a user to a company/department.

For example, I created a company and a user with the API, and then I assign the user to a company as below:

`curl -s -k -g -X POST "https://localhost/iomad/webservice/rest/server.php?wstoken=TOKEN&moodlewsrestformat=json&wsfunction=block_iomad_company_admin_assign_users&users[0][userid]=7&users[0][companyid]=4&users[0][departmentid]=0&users[0][managertype]=0"`

If you are creating a company hierarchy, I believe this is the way to do it. You can code it in PHP, which is what I'm doing, or use your language of choice.

I hope that helps.

**Comment by turf212** [comment]
The profile fields "Institution" and "department" do not match the Iomad "company" and "department" and were actually added after Iomad was created (some point back in Moodle 2.x)  If you are using the Iomad upload users page, then you can specify the company department in the CSV (you already have the company chosen) and it will put them into that department, assuming it already exists.  Iomad doesn't use these fields as they are user editable and therefor not reliable.

The core Moodle user upload knows nothing about companies, so you can only use it to put users onto the site.  You could use this and then some SQL / script to put the users into the correct company department by matching what their profile field says to a company/department value.

**Comment by turf212** [comment]
You can import department structures to a company within the edit department page.  Or, as you have already mentioned, you can use a script and webservices to do all of this.  If you have something which will take a file and use it to set up companies, departments, and assign users (so basically an import company) then please could you share to help the community?

**Comment by turf212** [comment]
CVS upload to named department was added a long while back.  CSV upload including departments was added a while ago.  Auto assigning user to departments from their profile field was set up in 4.3
