### ISSUE TITLE
Course created and not showing up in course and category management

### ISSUE THREAD

**Issue by Bri-Bri-The-Science-Guy** [iomad/iomad#1228]
![Screen Shot 2019-11-13 at 11 58 41 AM](https://user-images.githubusercontent.com/46726847/68795019-56462300-060d-11ea-91a4-83d2b8a75989.jpg)
I have created a new Course and assigned it to a category but It will not show up at all in the course and category management page, only on my side bar.

**Comment by turf212** [comment]
Iomad filters out the courses which a company cannot see.  Simply moving the course to the company category does not make it available to a company, you need to also assign it to that company too.  This is assuming that the course will only be available to that company and will not be shared across companies.   The easiest thing to do to achieve what you are looking for it to create the course from within the Iomad dashboard with the company selected as that will create that course under that company and category.
