### ISSUE TITLE
Docker-compose needed

### ISSUE THREAD

**Issue by nehagup** [iomad/iomad#1229]
I'm trying to install Iomad, however, with docker-compose it becomes more convenient and easy to setup different testing environments.

It's not a bug but a request for a feature that makes developers life easy.

**Comment by turf212** [comment]
I've never used docker to set up environments (old school, I realise).  If you create something can you please consider sharing it with the community.

**Comment by nehagup** [comment]
https://github.com/bitnami/bitnami-docker-moodle

For Moodle installation, this worked pretty well. For multi-tenancy Bitnami image needs to be customised or we can write our own.
