### ISSUE TITLE
Can't see company appearence options when using iomadboost as a parent theme

### ISSUE THREAD

**Issue by moxxuk** [iomad/iomad#1232]
Hi, we have created a theme with iomadboost as its parent, however we can't see the company appearence options such as companylogo and companycss in the company edit form.

Pull request is here: #1231

**Comment by turf212** [comment]
If you use the word iomad somewhere in the theme name it will pick it up automatically.

**Comment by moxxuk** [comment]
For various reasons, we'd rather not have to rename the theme. Any chance the pull request can be merged?
________________________________

**Comment by turf212** [comment]
I've reviewed and added the code.  Thanks for supplying!

**Comment by turf212** [comment]
closed under #1321

**Comment by moxxuk** [comment]
Thanks for the merge!
