### ISSUE TITLE
Creating Departments via API Webservices

### ISSUE THREAD

**Issue by williamwithin** [iomad/iomad#1234]
I'm importing a company/department structure from an existing mysql database (using a custom PHP script), and I'm looking for a way to create departments via the API webservices. Is there a way to do this, or am I missing something?

It seems like there should be a webservice like "block_iomad_company_admin_create_departments" but I'm not seeing it. Is there another way to accomplish this with the existing Iomad webservices?

I see that I can 'Import department structure' under 'Manage departments', but I would prefer to do it with the API. 

Looking forward to your response. Thanks

**Comment by turf212** [comment]
We don't have that Webservice call yet as it wasn't one which was specified by the sponsoring company.   You can import company departments from within the manage departments pages but only when there are not any yet for that company.

**Comment by williamwithin** [comment]
I'm going to need the create_departments API, so I'm writing it now. I've got one that works, I just need to clean it up a bit before I share it.
