### ISSUE TITLE
Able to access other company courses

### ISSUE THREAD

**Issue by nielsharma** [iomad/iomad#1235]
User from Company A is able to access courses from Company B even if course is not shared. Users can navigate to other courses by changing the course ID at the end of the URL.
If self-enrolment is enabled on a course then a user from any company can enrol themselves into that course.

Tested with both sharing options – Not shared and Closed sharing. (Course was not assigned to the other company in the Closed sharing option)

![1](https://user-images.githubusercontent.com/47655776/69299090-c6832300-0c63-11ea-80f6-a71306712ea8.JPG)

Logged in as a user from a different company

![2](https://user-images.githubusercontent.com/47655776/69298862-27f6c200-0c63-11ea-9d68-e64cadf3d647.JPG)

**Comment by turf212** [comment]
There is code within course/view.php on 3.7 which disables the course id should the one passed not belong to the current company.  Can you give me a sample URL (the bit after the hostname is fine) for each of those instances so I can check why that's not working correctly.

Thanks!

**Comment by nielsharma** [comment]
These two courses belong to Company A:
https://demo.iomad.org/enrol/index.php?id=5
https://demo.iomad.org/enrol/index.php?id=6
Both are not shared with other companies.

If a user from Company B tries to navigate to either course via the URL, they will get redirect to the Self Enrolment page for the course- https://demo.iomad.org/enrol/index.php?id=5 or https://demo.iomad.org/enrol/index.php?id=6
They can then self enrol by clicking on the Enrol me button.

Maybe the code within course/view.php also needs to apply to enrol/index.php

Thanks,
Niel

**Comment by turf212** [comment]
Turned out the check course wasn't working as expected at all.
