### ISSUE TITLE
Auto enrollment to Companies

### ISSUE THREAD

**Issue by Chelsy29** [iomad/iomad#1236]
Hi,

In IOMAD, is there any way to assign users into the company according to their institution field?
For example,
If a user has "Company A" in the institution field, then assign that user to "Company A" on user creation automatically
If a user has "Company B" in the institution field, then assign that user to "Company B" on user creation automatically.
Is there anything like auto-enrol cohort and cohort sync plugin?

Also, what are the required fields in the spreadsheet to assign users into the company?
Appreciate your help.

Thanks.
Chelsy

**Comment by turf212** [comment]
Yes there is, but it doesn't use the institution field, it uses the email address domain.  If you have self sign up enabled and you have the appropriate email domain within the company definition and you have set up the options for the local iomad signup plugin then it will put users into companies when they are created outside of the company.

You can also use the hostname (assuming it's been set up on the webserver) which will bring the user to a branded signup/login page or you can pass the parameters directly to that page.

**Comment by Chelsy29** [comment]
Hi Derick,

Thanks for your reply. I have one more question about how local iomad signup plugin works?

What I understood is, Suppose a user with abc@gmail.com is created in iomad and if we set Company A domain as gmail, then the user abc@gmail.com will add to Company A when he logged in on iomad. Is this right?
