### ISSUE TITLE
how to hide course and Reports from the dashboard?

### ISSUE THREAD

**Issue by RTewolde** [iomad/iomad#1238]
Is it possible to hide the "Courses", "Competencies", "Reports" icons from the manager role? I want the manager to be able to create a "Companies" and "users" but not to create a course and view a report.

**Comment by turf212** [comment]
What the manager see's is all based on the capabilities for their role.  You can set these for the site under the site admin -> users-> permissions define roles page or you can further remove them for a company using the company role restrictions within the Iomad dashboard.

**Comment by RTewolde** [comment]
Thank you. that was very useful.  i now managed to hide the  "Courses", "Competencies", "Reports" icons from the manager role  by dashboard->Companies→Restrict capabilities→ Company manager→ edit Untick:
-Assign a course educator
block/iomad_company_admin:assign_educator, 
-Enrol/unenrol users on company courses
block/iomad_company_admin:company_course_users, 
-Assign competency frameworks to a company
block/iomad_company_admin:company_framework
-View competency management tab in dashboard
block/iomad_company_admin:competencymanagement_view
-View competencies from dashboard
block/iomad_company_admin:competencyview
-View the course management tab
block/iomad_company_admin:coursemanagement_view
-Edit company course groups
block/iomad_company_admin:edit_groups
-Manage Iomad competency framework settings
block/iomad_company_admin:manageframeworks
-Access to Iomad Reports
block/iomad_reports:view
-View course iomad attendance report
local/report_attendance:view
-View course iomad progress report
local/report_completion:view
-View the license allocations report
local/report_license_usage:view
-View the user license allocations report
local/report_user_license_allocations:view
-View the Iomad user login report
local/report_user_logins:view
-View the users report
local/report_users:view
![hide course and Reports from the dashboard](https://user-images.githubusercontent.com/17621577/70427926-83032400-1a6d-11ea-8d35-9d8a24250fe5.PNG)



But i am unable to hide it from the Site administrator  the  "Courses", "Competencies", "Reports" icons from the dashboard.
I navigated to dashboard->Companies→Restrict capabilities→ client administrator and then untick the same parameters as above but i was unable to hide the  "Courses", "Competencies", "Reports" icons from the dashboard.

Thank you very much for your help

**Comment by Areej-akhtar** [comment]
Iomad Reports - Completion report by users how to hide decimal points in reports like 3.735325506937%
Completed courses
