### ISSUE TITLE
Same Course under different Category

### ISSUE THREAD

**Issue by Chelsy29** [iomad/iomad#1239]
Hi,
Can we have the same courses under a different category and assign a different company to each course in IOMAD.
For Example, I have Course A under Category A and assigned Company A to that course. And I want the same Course A under Category B and assign Company B.
Is it possible in IOMAD?

Thanks,

**Comment by turf212** [comment]
Sharing courses doesn't work in this way under Iomad.  If you go to the Iomad dashboard and click on Iomad course settings under the courses tab you can mark a course as being shared or not.  There are two types of sharing (it's explained under the ? icon)  and from there you can either access the course fromt he other company (open shared) or you can assign the course to the other company (closed shared).
