### ISSUE TITLE
Usage of Iomad

### ISSUE THREAD

**Issue by MissyMel** [iomad/iomad#1240]
This may not be an issue, however i can't find anywhere anything on how the multitenancy feature works in iomad. 
i am a user for the last 3 years on moodle and are now transitioning to iomad. But this multi tenant feature just to ensure i get the full understanding and use of it would be fantastic. 
Also i can see that the reports are somewhat a little different also. Can anyone assist in providing an overview for me please?  Happy to pay someone some time to ensure i get my head around it correctly.. 
Also can we use all template plugins that moodle uses for Iomad? I am aware iomad is built on top of the core moodle just wanted to make sure i had my information correct.

**Comment by Blacksheeprules** [comment]
markiannone@gmail.com

I might be able to give you a run down on how to set a basic Company up.
