### ISSUE TITLE
can user able to  self register to company?

### ISSUE THREAD

**Issue by RTewolde** [iomad/iomad#1241]
I created four company names using IOMAD, and now I want a user to self-register and select the company they want to be registered.

This will allow the user  to be automatically be assigned to an IOMAD company.

Thank you

**Comment by turf212** [comment]
The user can be put onto the correct company through a number of methods.  If you look at the local iomad_signup plugin settings you can choose what type of enrolment it will listen for an you can either use email domain matching to put a user into the correct company or you can use a URL link with appropriate parameters to local/iomad_signup/signup.php which will automatically select the correct company, and theme, for the user to sign into.  If you have multiple hostnames pointing toyour site installation, you can also match those to a company which will set the URL out correctly for the user.

**Comment by RTewolde** [comment]
Thank you for your reply. Do you have an example of updated signup.php file?

**Comment by nielsharma** [comment]
Hi Derick,

Do you have any instructions on how i can assign users to different companies automatically when they sign up. I can see an option to select a company in iomad signup setting, but not too sure how to assign user to different companies.

Thanks,
Niel

**Comment by nielsharma** [comment]
Hi Derick,
I've been able to successfully register to a company using the 'List of company domains' field.
Are you able to guide me on how i can achieve the same using 'Webserver hostname' field?

Thanks,
Niel

**Comment by bavdalimbaev** [comment]
Hello. Сan you help me with create list domain? @nielsharma

**Comment by shadyshrif** [comment]
Why not have the company names in a drop-down box in the self-registration form so users can pick their companies then the admin can approve or reject them?
I believe this feature is missing from Iomad

**Comment by turf212** [comment]
not everyone wants their clients to know who their other clients are

In any case - superseded with per tenant URLs
