### ISSUE TITLE
Auto enroll to courses

### ISSUE THREAD

**Issue by Chelsy29** [iomad/iomad#1242]
Hi,

I have created Company A and assign user A into Company A manually. And choose Course A as Autoenrolment courses in advanced company settings. But user logged in and when he opened that course, it shows as you cannot enrol yourself into this course. How can I assign users assigned in the company automatically to the courses that they have access?

Thanks

**Comment by turf212** [comment]
The user is enrolled on the courses at point of creation.  So if you created the user first and then set this up, they would not be enrolled on the course.
