### ISSUE TITLE
Assigning users/managers to multiple departments

### ISSUE THREAD

**Issue by williamwithin** [iomad/iomad#1244]
Is there a way to assign users/managers to multiple departments? When I assign a user to a department, they are removed from the current one and placed in the new one only.

If it's not currently possible, can you point me in a general direction to where in the code I might look into modifying to enable this?

This is a core functionality I would require in implementing Iomad, I'm not sure I can continue without it.

**Comment by turf212** [comment]
At the moment, users can only be in one department.  Managers can manage users in their department and below, so you should be able to look at your department structure to get this to work.  If it is an absolute requirement, we would be happy to look at this further and provide a quote for developing this functionality.  If you contact info 'at' e-learndesign.co.uk we can pick this up there.

**Comment by manuel-garcia-sn** [comment]
@turf212 now this is possible right?

**Comment by turf212** [comment]
this was added a while back.  User can even be in multiple companies with different roles now.
