### ISSUE TITLE
IOMAD sign up

### ISSUE THREAD

**Issue by Chelsy29** [iomad/iomad#1248]
I am not able to figure out how iomad sign up is working. This is what I am doing.
1. I have added a new user from site admin->users->add a new user (ex. abc@gmail.com)
2. Created a company called " Company A" and entered"@gmail.com" in the list of company domains under the company A
3. When I logged in as abc@gmail.com, that user hasn't added to that company.

Am I doing something wrong? Can you please elaborate on how iomad signup is working?

**Comment by turf212** [comment]
If you are creating users, then use the Iomad dashboard to create them with the appropriate company selected.  If you use the Moodle tools, it doesn't understand about companies so the user will be created in limbo.  To bring this user into a company, you can use the assign users in the Iomad dashboard.

The Iomad dashboard allows for single users to be created from a manaement screen and multiple user to be created via CSV upload.  By using the Iomad screen's and having a company selected all of the bits which tie the user to a company happen automatically.

**Comment by bavdalimbaev** [comment]
Hi, can you help me. how to indicate the company in the registration? how to add select company in page signup? @turf212
