### ISSUE TITLE
Can company manage  send message to all users within the company

### ISSUE THREAD

**Issue by RTewolde** [iomad/iomad#1249]
Can company manage send a message to all the users within the company?

A. Can the company manage
 1.    Click on name in the top right-hand corner of the screen and click on Messages.
2.    Type a group name (e.g company name ) and then send the message?
or

B. Can the company manage use the IOMAD dashboard to send message to all the user from the company

Many thanks for your  help

**Comment by turf212** [comment]
The internal messaging isn't company aware at the moment.  We could definitely loo at this as an enhancement, if that is something you would want.

Similarly, there isn't anything in the Dashboard for the company manager to do the same.

One work around would be for the company to have a dedicated course which is to be used as a "Common Room" for their staff.  It can be set to be autoenrolled on user creation (you would need to enrol the other company users who already exist).  The company manager, who would be given the client course editor role, can then set up a forum with forced subscriptions to be used for announcements.  All their users would get any posts made in the forum.
