### ISSUE TITLE
Bulk user upload from iomad block not imported

### ISSUE THREAD

**Issue by deva199** [iomad/iomad#1251]
Hi,
I been using iomad application, when I try to use bulk upload option in iomad_company_admin block,
on csv validation, it sends error message 
![image](https://user-images.githubusercontent.com/42734131/71142777-65d50f00-223e-11ea-918e-ddee10f354fb.png)

needed guidance to overcome this issue, plz

**Comment by turf212** [comment]
You have an issue in your CSV file.  Either the headers dont match what is expected or there is something broken in the data.  If you open it up in a text editor like notepad, then you can look for spaces where there shouldn't be.  Also have a look at the Moodle docs for the Moodle tol this was built from - https://docs.moodle.org/38/en/Upload_users

**Comment by deva199** [comment]
thanks, i managed to solve this issue

**Comment by vivek-hashroot** [comment]
> thanks, i managed to solve this issue

Hi Bro, could you please help me in resolving this same issue for me? I could bulk upload users via admin login > site admin > users > upload users, but not from iomad section. I created a company manager also and tried from iomad section but from there also I could not upload bulk users and enrol them to the desired course. Thank in advance.

**Comment by iberactiv** [comment]
This thread is a little bit old, but I had the same problem with IOMAD 4.0.3 on Moodle 4.0. In my case it was not exactly a bug. IOMAD don't validate all Moodle available fields, and I was trying to add the field "maildisplay" in the spreadsheet. So, I modified the file **blocks/iomad_company_admin/uploaduser.php** around the line 149 to add the fields I needed to be validated:

`$stdfields = array('id', 'firstname', 'lastname', 'username', 'email',
        'city', 'country', 'lang', 'auth', 'timezone', 'mailformat',
        'maildisplay', 'maildigest', 'htmleditor', 'ajax', 'autosubscribe',
        'mnethostid', 'institution', 'department', 'idnumber', 'skype',
        'msn', 'aim', 'yahoo', 'icq', 'phone1', 'phone2', 'address',
        'url', 'description', 'descriptionformat', 'oldusername', 'deleted',
        'password', 'temppassword', 'suspended', 'alternatename','maildisplay');`

But I also had issues before with the CSV file. Make sure it is well-formated, and that you choose the right charset encoding and field separator during the import.
