### ISSUE TITLE
Ecommerce

### ISSUE THREAD

**Issue by Blacksheeprules** [iomad/iomad#1255]
I am using Iomad Moodle 3.7.3+ (Build: 20191205)

I added the course to Ecommerce and made it visible in shop. 
I first allowed single purchases. 
I put in a Paypal Sandbox that works in the Block Ecommerce. 
I logged in as a Manager and I was able to make a single purchase with the payment going through Paypal perfectly. 

I allowed license blocks for 10 and  a  unit price of $2 CAD. 
I logged in as a Manager and made a purchase of a block of 10. When I submitted the order from the checkout I got the attached error. 

Error |  
-- | --
Detailed Error Message: | The totals of the cart item amounts do not match order amounts.
Short Error Message: | Transaction refused because of an invalid argument. See additional error messages for details.
Error Code: | 10413
Error Severity Code: | Error

I choose 10 licenses and $2 per for $20

Thank-you for any help you can provide.

**Comment by turf212** [comment]
The error form paypal is stating that "The totals of the cart item amounts do not match order amounts. "

When you look at the order in the Sandpit, what was it trying to do?

**Comment by Blacksheeprules** [comment]
The orders for the single purchase are there and not for the batch. They look like:


Hello test buyer,You sent a payment of $1.00 CAD to test facilitator's Test Store(miannone-facilitator@shaw.ca)It may take a few moments for this transaction to appear in your account.Merchanttest facilitator's Test Storemiannone-facilitator@shaw.caInstructions to merchantYou haven't entered any instructions.Shipping address - confirmedMan AgerA8045 159 A StSurreyBRITISH COLUMBIA V4N 0K1CanadaShipping detailsThe seller hasn’t provided any shipping details yet.DescriptionUnit priceQtyAmount$1.00 CAD1$1.00 CADSubtotal$1.00 CADTotal$1.00 CADPayment$1.00 CADPayment sent to miannone-facilitator@shaw.ca |   |   | Merchanttest facilitator's Test Storemiannone-facilitator@shaw.ca | Instructions to merchantYou haven't entered any instructions. | Shipping address - confirmedMan AgerA8045 159 A StSurreyBRITISH COLUMBIA V4N 0K1Canada | Shipping detailsThe seller hasn’t provided any shipping details yet. | Description | Unit price | Qty | Amount |   | $1.00 CAD | 1 | $1.00 CAD | Subtotal$1.00 CADTotal$1.00 CADPayment$1.00 CADPayment sent to miannone-facilitator@shaw.ca | Subtotal | $1.00 CAD | Total | $1.00 CAD | Payment | $1.00 CAD | Payment sent to miannone-facilitator@shaw.ca
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
  |  
Merchanttest facilitator's Test Storemiannone-facilitator@shaw.ca | Instructions to merchantYou haven't entered any instructions.
Shipping address - confirmedMan AgerA8045 159 A StSurreyBRITISH COLUMBIA V4N 0K1Canada | Shipping detailsThe seller hasn’t provided any shipping details yet.
Description | Unit price | Qty | Amount
  | $1.00 CAD | 1 | $1.00 CAD
Subtotal$1.00 CADTotal$1.00 CADPayment$1.00 CADPayment sent to miannone-facilitator@shaw.ca | Subtotal | $1.00 CAD | Total | $1.00 CAD | Payment | $1.00 CAD | Payment sent to miannone-facilitator@shaw.ca
Subtotal | $1.00 CAD
Total | $1.00 CAD
Payment | $1.00 CAD
Payment sent to miannone-facilitator@shaw.ca
