### ISSUE TITLE
Not able to add users as Department Manager

### ISSUE THREAD

**Issue by Chelsy29** [iomad/iomad#1258]
Hi,
We restored the moodle 3.5+ database into IOMAD 3.6 version.
Getting the below error when I tried to add users as a department training manager/company manager.
![image](https://user-images.githubusercontent.com/56966301/72131318-e3092500-33a1-11ea-89d8-30689c682cef.png)
I am able to add users into the company and one more issue is the user is not removing from the company when I clicked on the user and clicked on Remove.

Appreciate your help.
Thanks!

**Comment by turf212** [comment]
Is this the latest 3.6 code?

**Comment by Chelsy29** [comment]
yes, it is the latest 3.6 code.

**Comment by turf212** [comment]
I've just tested this on my dev site and I'm not able to get the error (FYI this is Moodle complaining that we are removing more than one role from the user and should be using a different method).

I've tried:
Promote user to Company manager
Demote user from Company manager
Promote user to Department manager
Demote user from Department manager
Promote user from Department manager to Company manager
Demote user from Company manager to Department manager

Does the user you are trying to demote promote have any other system roles?

**Comment by Chelsy29** [comment]
No, they are not in any other system roles. I deleted the user from IOMAD and tried to add, then also it's showing the same error. Is this because of any database issue while restoring the moodle database into IOMAD?

**Comment by kirupalaksh** [comment]
Hi turf212,
I am also facing same issue on add or remove users in department page. Can't remove a user from a department?
I can able to add or remove to company manager or department training manager or educator.
Ii don't get any error on screen.
