### ISSUE TITLE
Sychronization of new users added to Active Directory to be added to Company in IOMAD 

### ISSUE THREAD

**Issue by Chelsy29** [iomad/iomad#1259]
We use the active directory for our Authentication and Cohort Sync & auto-enrol cohort to add users to a cohort. We would like to implement the same kind of functionality to sync users from active directory to a specific company created on IOMAD Moodle 

So here's the requirement what we are looking for:
Initially, I would import existing users into IOMAD and this would ensure they have access to the specific company.
Going forward, when a new user is added to the AD list, I would like to use either the department field or any other field on AD list and set up a rule to add the user to a default company.
Can you please tell me how to go about this?

Thanks!!!

**Comment by turf212** [comment]
If you have company specific email domains then you can use these to tie users to a company.  There is a company setting in advanced company settings for the list of company domains.  These match any email domains being supplied.  If you have self sign up allowed and you have the AD authentication plugin selected under the local iomad settings plugin then it will carry out what you are looking for.

At the moment there is nothing to sync a user's profile department to an existing company department.  You can, however, sync it the other way.
