### ISSUE TITLE
How can a company manager create a student or teacher role after creating a course?

### ISSUE THREAD

**Issue by RTewolde** [iomad/iomad#1262]
1. To create a course: 
I navigated into IOMAD dashboard -> courses -> create course -> I then filled in the course details-

2. to enrole user
I navigated into IOMAD dashboard -> courses ->user enrolments-> search for the course name -> enrol user

How do I now assign student or teacher role  to the user?

![image](https://user-images.githubusercontent.com/17621577/72998645-1b731f00-3df6-11ea-9dd5-1050d515aec6.png)

**Comment by RTewolde** [comment]
And how can i get access to the "Users" access
![image](https://user-images.githubusercontent.com/17621577/72998782-4e1d1780-3df6-11ea-9865-1b9923272b74.png)


![image](https://user-images.githubusercontent.com/17621577/72998822-5aa17000-3df6-11ea-88fc-2dbd53a38369.png)

**Comment by RTewolde** [comment]
Could you please help me with the above request. Thank you

**Comment by dvillareal22** [comment]
Can anyone please answer this question as we also need to enrol educators on the courses...

**Comment by turf212** [comment]
Local IOMAD settings - enrol managers as none students - untick this and then you can assign users as educators within the company and not just company/department managers.
