### ISSUE TITLE
Iomad cron not mail notfifcation not sent

### ISSUE THREAD

**Issue by deva199** [iomad/iomad#1263]
Hi,
For new creation under company, signup notification not sent to users.
when I checked mdl_email table "sent" column seems to be null, where as if create user under "site administration" and run cron nor specific task, it seems to be working.

mailing via cron at core level seems to be working, but in iomad aspect no work
Any suggestions ?

**Comment by turf212** [comment]
The schedule task which sends out the Iomad emails is local_iomad.  Check what this task is throwing as an error when you run it with debugging on.  (You will need to put your path to php in the server system paths admin page and then you can run that task from the browser).  It's either disabled, or something has happened to the data causing it to fail.

**Comment by deva199** [comment]
yes turf you are right, at email templates some them been disabled
but the weird, we have multilingual website
in English seems to be enabled
but in French seems to be disabled
you have any suggestion for it ?

**Comment by turf212** [comment]
Iomad treats each of the languages with their own settings.  So the language strings can be completely different along with the rest of the template settings.  You will need to enable the same templates for each of the languages.  I suppose some more sophisticated controls should be added but unfortunately there aren't any there at the moment.

You can create a template set which has the settings for all the languages and then apply these to each of the companies.  It works like a one time stamp replacing what the company has with the template.  This means you can then edit the company and or the template independently from each other.  You apply the template in the edit company screen.

**Comment by dsquare58** [comment]
iomad email issue!! User created email are created but never sent please help!
![Screenshot (211)](https://user-images.githubusercontent.com/44236940/77825582-19815100-7102-11ea-9ee2-3108be161afc.png)

**Comment by dsquare58** [comment]
> 
> 
> iomad email issue!! User created email are created but never sent please help!
> ![Screenshot (211)](https://user-images.githubusercontent.com/44236940/77825582-19815100-7102-11ea-9ee2-3108be161afc.png)

@iomad

**Comment by turf212** [comment]
hi @dsquare58 is the scheduled task local email running without error?  This is the one which processes the email queue you can see in this report.

**Comment by dsquare58** [comment]
Yes it gives me error

**Comment by turf212** [comment]
If you turn on full developer debug and display error messages  (Site admin -> development -> debug) and re-run the task, what error do you get?  Typically this is something which is stuck elsewhere in your email queue and it's blocking all of the other emails from going.

**Comment by turf212** [comment]
closing as no further response.
