### ISSUE TITLE
Common groups not displayed for open shared course

### ISSUE THREAD

**Issue by deva199** [iomad/iomad#1266]
Hi,
Considering the below scenario,
For the course that been assigned to 4 companies in a closed sharing, i see the common groups for the 4 companies available under course groups.
Same thing doesn't work for open shared course ?
Am I missing any step ?

**Comment by turf212** [comment]
No.  It shouldn't matter between closed or open shared.  The groups should appear the same in both.

Where are you looking at the groups?  In the course itself or when managing groups in the Iomad dashboard?

**Comment by deva199** [comment]
"In the course itself" I'm looking for the common groups to appear, whether course is open or closely shared it need to show all groups
isn't it ?

So far what I understood is based on course assignment to company (common group gets created)

**Comment by turf212** [comment]
I suspect what has happened is that the groups get created when someone from that company is enrolled on the open shared courses.  Closed shared courses the groups are implicitly added.
