### ISSUE TITLE
block_iomad_company_admin_unassign_users parameter error

### ISSUE THREAD

**Issue by francoisjacquet** [iomad/iomad#1274]
Hello,

I am trying to unassign a user from a company using the Webservice function `block_iomad_company_admin_unassign_users parameter`.
The following error occurs:
```
Moodle: 29039061 - Invalid parameter value detected (users => Invalid parameter value detected (Unexpected keys (usertype) detected in parameter array.): Unexpected keys (usertype) detected in parameter array.)
```
It states `usertype` parameter is invalid. However it is mentioned in the API documentation:
![image](https://user-images.githubusercontent.com/4723501/74591254-aa024700-5016-11ea-8120-ec39c78bc70b.png)

If the call is made without the `usertype` parameter, the error is exactly the same.

Please note I am able to successfully assign a user to a company via the API.

I have tried to tweak the `blocks/iomad_company_admin/externallib.php` file wit no luck, especially this line which looks wrong:
https://github.com/iomad/iomad/blob/IOMAD_36_STABLE/blocks/iomad_company_admin/externallib.php#L851

**Comment by turf212** [comment]
That line is definitely wrong.  Thanks for reporting.  It's the event call which is failing.

**Comment by francoisjacquet** [comment]
Thank you @turf212 I confirm this is now working as expected.
