### ISSUE TITLE
block_iomad_company_admin_unenrol_users function

### ISSUE THREAD

**Issue by francoisjacquet** [iomad/iomad#1275]
Hello,

Do you have any plan on implementing a `block_iomad_company_admin_unenrol_users` Webservice function?

**Comment by turf212** [comment]
Does the core function for unenrolling a user not work?  FYI license user may not be able to be unenrolled depending on their license definition.

**Comment by francoisjacquet** [comment]
Hello @turf212 

The core Moodle function for removing the "Student" role used by RosarioSIS was: `core_role_unassign_roles`

But student was still enrolled in the course for Iomad company:
![image](https://user-images.githubusercontent.com/4723501/75547205-b4670c80-5a2a-11ea-8637-e37d57ffcc1c.png)

The solution was to use this WS function instead: **`enrol_manual_unenrol_users`**.

Thanks!
