### ISSUE TITLE
create a user that works for two different companies 

### ISSUE THREAD

**Issue by RTewolde** [iomad/iomad#1276]
This issue was created previously, I am wondering if the feature below available.
Is there a way that I can create a user that works for two different companies and have the same user assigned to both companies without them having to have a separate user account within each company?

If the feature is not available, is it a major work for someone to make a change in the code. As my project higher requirement is to assign a user into more than  two different companies but have only one profile information in the system

**Comment by turf212** [comment]
This is not currently possible.  It's a fairly major bit of work to achieve this but, if it's something which is required, I'd be happy to work out a spec and a quote for you.  Please send an email to info@iomad.org and we can pick it up from there.

To give you an idea of the scope, some questions to consider
If a user is allocated to more than one company, which company theme do they get
What happens with shared courses when a user is assigned the same course from multiple companies
Similarly with licenses

**Comment by turf212** [comment]
Possible as of IOMAD 4.3
