### ISSUE TITLE
How to configure shop?

### ISSUE THREAD

**Issue by VOOM108** [iomad/iomad#1277]
I have been trying to configure the shop all day on my IOMAD testsite, so courses can be bought via the block. I have had a look at the demo.iomad.org as well to see how the block is configured. I have two courses in two companies, licence enrolment is set. I created licences. No matter what I do, the block only shows the message "The eCommerce block has not been configured. Check the settings page for the block". 

In the settings there is mentioned that "the shop can be turned on for companies" or "you will then need to turn on the shop for the companies who require it". (tried both settings) - but where and how do I "turn on the shop for a company"? 

I feel completely lost (and I have been Moodle admin since Moodle 1.4)... I wonder if we can dare to use IOMAD without any documentation to be found anywhere at all. I understand the need to sell support etc., but at least the basic functions specific for IOMAD over Moodle need to be openly documented in my opinion.

**Comment by turf212** [comment]
Documentation for this is on the https://www.iomad.org website
