### ISSUE TITLE
Educator - Edit Licensed Closed Courses - Not working

### ISSUE THREAD

**Issue by Scott-Rogers2020** [iomad/iomad#1285]
Hi, I have assigned the Educator Role to the Company Manager with the idea that the Company Manger can then edit the courses within the Company. When I log in as the Company Manager the edit option does not show. I then assigned the educator role in Core Moodle and the Company Manager could edit, however, the course edits were visible for all Companys.

Is there a way to assign course edit role to a user so they can edit "closed licenced courses" that only change courses for their company and not all companies?

**Comment by turf212** [comment]
Standard Iomad users should not be allowed to edit shared courses as this will allow them to see all of the other company groups and users in the course.   If you are trying to create a user who belongs to your company (and you are providing the training to all of the company users or they are allowed to see the whole picture) then you can provide them with the editing teacher role once they have a valid license for the course.

If this is to allow someone in your company to have near admin capabilities then you can use the Client administrator role (check it works for your use cases) which will allow them further access to the Iomad dashboard to do all of the things the site admin can but not within Moodle.
