### ISSUE TITLE
Compatibility with Configurable Reports plugin

### ISSUE THREAD

**Issue by moxxuk** [iomad/iomad#1286]
Is there a way to make IOMAD compatible with the Configurable Reports plugin? We don't want company admins to be able to see data from other companies, but can't work out how to achieve this.

**Comment by turf212** [comment]
The only way I have thougt about this (without making an Iomad version of the plugin, which would be the better solution) is to create the report and allow the company managers access to view them only.  Don't allow them to have access to configurable reports block but, instead, use the Iomad HTML block and paste in links to the appropriate reports which are only visible to users within that company.
