### ISSUE TITLE
Create company sub-categories

### ISSUE THREAD

**Issue by nielsharma** [iomad/iomad#1289]
Hi,

Is it possible to create sub-categories for a company via IOMAD? A parent category is created at the same time the company is created. If I create a sub-category via Moodle (Site administrator -> Courses -> Manage courses and categories -> Create new category) then the sub-category is visible to all other companies. I need to be able to create sub-categories and add courses to the sub-categories.

What might work is, when a Department is created then a sub-category is also created inside the Parent category. (just a thought)

Thanks,
Niel

**Comment by turf212** [comment]
Hi Niel,

The other option would be to ignore all of the subcategories of the company course category.  .  This is only really created as a convenience to allow somewhere for courses to be stored when they are created within the Iomad dashboard under that company.  I'll check but I think this would be the simplest way.

**Comment by turf212** [comment]
we went with this option a while back
