### ISSUE TITLE
Iomad Cron Error on scheduled task

### ISSUE THREAD

**Issue by amirtq** [iomad/iomad#1294]
Hi there
I have installed Iomad 3.8 a few hours ago
and I have error on a cron scheduled task with below details:

"""
Iomad Cron

Execute scheduled task: Iomad Cron (local_iomad\task\cron_task)
!!! Exception - Class 'local_iomad\task\company' not found !!!

I am using site in multilingual environment with additional calendar plugin installed.
"""

Any idea?

**Comment by amirtq** [comment]
if it helps, below is the debug info with manual task run:
Iomad Cron

Execute scheduled task: Iomad Cron (local_iomad\task\cron_task)
!!! Exception - Class 'local_iomad\task\company' not found !!!
!! 
Error code: generalexceptionmessage !!
!! Stack trace: * line 73 of /local/iomad/classes/task/cron_task.php: Error thrown
* line 157 of /admin/tool/task/cli/schedule_task.php: call to local_iomad\task\cron_task->execute()
 !!

Fatal error: Uncaught coding_exception: Coding error detected, it must be fixed by a programmer: A lock was created but not released at:
/var/www/app.aflms.ir/admin/tool/task/cli/schedule_task.php on line 142

 Code should look like:

 $factory = \core\lock\lock_config::get_lock_factory('type');
 $lock = $factory->get_lock(Resource id #677);
 $lock->release();  // Locks must ALWAYS be released like this.

 in /var/www/app.aflms.ir/lib/classes/lock/lock.php:117
Stack trace:
#0 [internal function]: core\lock\lock->__destruct()
#1 {main}
  thrown in /var/www/app.aflms.ir/lib/classes/lock/lock.php on line 117

**Comment by amirtq** [comment]
I found some more details, 
It is happening when a company reaches the contract end date.
before that, everything looks fine but at the time of a company's contract end date, instead of suspending the company, the "local_iomad\task\cron_task" scheduled task starts being failed.
Is it a bug or a misconfiguration  at somewhere ?

**Comment by amirtq** [comment]
something strange that may be related to this issue
on new user mail that is sending user details, which is being triggered by "block_iomad_company_admin\task\emailpasswords"
the task log shows success from server cronjob, but it does not that email to the user
but if I run the task manually from web GUI, it will send the email to the users immediately
I was thinking maybe there is something problematic on the linux cronjob level that is causing above mentioned issue about  "local_iomad\task\cron_task"m :-?

**Comment by turf212** [comment]
Looks like it's not picking up the company class when running.  I've added a require once to the routine which will address this.

**Comment by turf212** [comment]
thanks for reporting!

**Comment by amirtq** [comment]
Okay lemme replace, test and feedback

**Comment by amirtq** [comment]
It is still failing with below error in task log:
Execute scheduled task: Iomad Cron (local_iomad\task\cron_task)
... started 20:26:02. Current memory use 19.9MB.
!!! Exception - Call to undefined function local_iomad\task\once() !!!

**Comment by amirtq** [comment]
however, even after disabling contract end date, the task is failing som Im replacing the cron_task.php with the old one

**Comment by turf212** [comment]
I have a typo in that file.  I've fixed and pushed.

**Comment by amirtq** [comment]
its still failing :)

**Comment by amirtq** [comment]
do you need debug info?

**Comment by amirtq** [comment]
Execute scheduled task: Iomad Cron (local_iomad\task\cron_task)
!!! Exception - Class 'local_iomad\task\company' not found !!!
!! 
Error code: generalexceptionmessage !!
!! Stack trace: * line 76 of /local/iomad/classes/task/cron_task.php: Error thrown
* line 157 of /admin/tool/task/cli/schedule_task.php: call to local_iomad\task\cron_task->execute()
 !!

**Comment by turf212** [comment]
Missed that the file declared a different namespace for the class.  Needed to be escaped. Doh!

**Comment by amirtq** [comment]
looks this one is really wanted to be un-fixed :-?
Execute scheduled task: Iomad Cron (local_iomad\task\cron_task)
... started 21:04:03. Current memory use 31.4MB.
!!! Exception - Class 'local_iomad\task\company' not found !!!
!! 
Error code: generalexceptionmessage !!
!! Stack trace: * line 88 of /local/iomad/classes/task/cron_task.php: Error thrown
* line 201 of /lib/cronlib.php: call to local_iomad\task\cron_task-&gt;execute()
* line 119 of /lib/cronlib.php: call to cron_run_inner_scheduled_task()
* line 73 of /lib/cronlib.php: call to cron_run_scheduled_tasks()
* line 61 of /admin/cli/cron.php: call to cron_run()
 !!

**Comment by amirtq** [comment]
It just worked with manual task run
lets wait few mins to see if it also works for cron run

**Comment by turf212** [comment]
There were two.  Missed the second one.

**Comment by amirtq** [comment]
Yup its finally fixed
Thanks for effort!
