### ISSUE TITLE
Unit tests fatal error "Cannot declare class core_accesslib_testcase"

### ISSUE THREAD

**Issue by ni-ght** [iomad/iomad#1295]
IOMAD 3.6

When running unit tests:

`$ php vendor/bin/phpunit`

I get:

`Fatal error: Cannot declare class core_accesslib_testcase, because the name is already in use in ./local/iomad/tests/accesslib_test.php on line 3140`

The problem seems to originate with declarations in the files:
./lib/tests/accesslib_test.php
./local/iomad/tests/accesslib_test.php

(this might be the same issue: https://github.com/iomad/iomad/issues/1111)

Many thanks

**Comment by turf212** [comment]
file no longer exists - fixed a while back
