### ISSUE TITLE
Disable Auto Enrol for other IOMAD roles

### ISSUE THREAD

**Issue by amirtq** [iomad/iomad#1297]
Hi there
Im going to rename and use "Company Department training Manager" as Teacher role for companies.
Challenge is that when we setup a user as "Company Department Manager" and/or "Company report only", then, when we create a new course, it will automatically enroll that user to the new course.
To remove access to that course, every time that we create a new course, we have to unroll all users with mentioned role from new course. its a very huge work if we have many teachers. 
How can we disable this behavior?
This way (disabling mentioned behavior), we can create a course, and enroll a user with mentioned roles to that course, and make him/her easily as the teacher for specific course.

**Comment by turf212** [comment]
If you untick the option for "Enrol managers as non students" in the local plugin Iomad settings settings page it will allow you to assign any user within the companies to be an educator.  This takes over the company course access and company course editor roles where appropriate within your courses instead of the company and department managers.  You assign educators using the assign department managers and users tool.

**Comment by turf212** [comment]
FYI - This also unlocks the educator license types which can be used to allow these teacher type roles access to license access courses too.

**Comment by amirtq** [comment]
I have unchecked that option, but educator role has two new challenges:
1- an educator user will have access to all courses in all departments across the company
2- there is no role for educator in "Moodle Define Roles" so actually we can not limit or change the access level of an educator.
Also for giving better perspective, we are going to use a flat company modeling for all of our customers "Means no Departments" at all for this moment. because we found that a user with "Department training Manager" role will have access to all courses cross the company.

Its very important for us to not let a teacher to have access to courses of other teachers.

**Comment by amirtq** [comment]
I think still the best way can be renaming two existed roles "Department Manager" and "Reporter" to use as teacher and another possible need
and my biggest challenge is that the system is enrolling a department manager, and reporter, to new courses automatically

**Comment by amirtq** [comment]
I have checked again, and this auto enroll is happening only for "Company Department training manager"
if we set a user as "Company report only" IOMAD will not enrol the user for newly created courses
but how to create same behavior for "Company Department training Manager"?

**Comment by turf212** [comment]
The roles which they get are not an educator role rather the client course access and client course editor.

If you are trying to keep teachers from one course out of courses belonging to other teachers within the same company, then you would wither have to do this by hand or convert your courses to ones which are licensed.  By default the only people who have access to the licensed courses are those who have been given a license for them.  The educators do not have access automatically.  They have to be given a license for the course which they then can access.  If one educator is given an educator license for course a and another educator is given a different license for course b then these users will not see the other course.  Only if they have explicitly been given a license for it.

You, as site admin, can set up a license to cover all of the courses and the company manager can then assign them to whichever "teacher" they want.  You, as site admin, can define a very controlled set of data on how those courses can be access.

To give you some insight into the thinking - Manual access courses are for those courses which an institution has full access to (e.g. they paid you $10,000 for a bespoke course).  They can enrol any number of their users onto it without any restriction.  License based courses are where you, as the site admin, want to place restrictions on how many users that institution can enrol in the course and for how long.  (e.g. they are paying you $100 per user they put through the course).

**Comment by turf212** [comment]
As for the company manager and reporting roles, these are meant to be used to give a user access to some part of the Iomad dashboard and some kind of control over their users.  The roles are assigned at site level.  Depending on the config setting I mentioned, the manager type users get course level roles too or users who are tagged as an educator type do.  The educator types do not get any access to the Iomad dashboard unless they have another Iomad role.

**Comment by amirtq** [comment]
First,  keep it in mind, we have removed all License options from dashboard of company manager because we was not able to imagine the logic.
So, you mean,
if we re-enable that licensing options, and again check "Enrol managers as non students",
A company manager can create licenses by himself, and
can create for example 20 users.
create two courses A and B
create licenses for his academy
give user 1 educator license to course A
give users 2 to 10 student license to course A
give user 11 educator license to course B
give users 12 to 20 student license to course B
and non of educator/students of course A will not have any access to course B and vice/versa ?

**Comment by amirtq** [comment]
Im now investigating over licenses,
It look, license must be provisioned by Site-Admin on specific course
so it will disables the full self service access of a company admin to the system?

**Comment by turf212** [comment]
You are the supplier.
The company are your clients
The company want to purchase 24 cans of various sodas
You package them up and give them to the company
The company hands the cans of soda to their users

This is licensing.  The company is paying for access to courses you are providing.
You package up the courses within a license
The company manager then assigns the licenses to the courses to their users.
Licenses have many options for control of access.  They can either be for users or educators.
Having the company creating their own licenses and then allocate them to their users would be giving their users access to the courses for free.  When they should be paying for them.

It may well be that the use case you are trying to achieve (I'm assuming standard Moodle for educational institutions where they have full control over their own courses and teachers and so on) is not one which is currently catered for.  We would be happy to help you work through this for a specification and provide a cost to incorporate this type of useage.  If you send an email to info@iomad.org we can take this off line.

**Comment by amirtq** [comment]
I got it now :)
so Im switching to license based model
The thing we need to know is what system role is inheriting for users we are allocating license for?
as I know, a user with no license is inheriting permissions from Moodle authenticated users
and after giving license to a course, which one is it inheriting?
also after unchecking "Enrol managers as non students", which Moodle role the educator user of IOMAD is inheriting?
We want to remove or add some permission.
