### ISSUE TITLE
Unable to assign educator license while creating new user

### ISSUE THREAD

**Issue by amirtq** [iomad/iomad#1299]
Hi there,
There is an error when we attempt to assign educator license while we are creating a new user,
it gives back invalidresponse error in a popup with below details:
invalidresponse
Invalid response value detected
File: /lib/externallib.php
Line: 442
error content:

license => Invalid response value detected: type => Invalid response value detected: Invalid external api response: the value is "3" of PHP type "string", the server was expecting "bool" type
Error code: invalidresponse
* line 442 of /lib/externallib.php: invalid_response_exception thrown
* line 250 of /lib/externallib.php: call to external_api::clean_returnvalue()
* line 79 of /lib/ajax/service.php: call to external_api::call_external_function()

![IOMAD-NewUser-AssignLicense-Error](https://user-images.githubusercontent.com/46824284/78063709-e101a180-73a5-11ea-9585-28f4ffdbede3.jpg)

**Comment by amirtq** [comment]
@turf212

**Comment by turf212** [comment]
I can confirm I'm getting the same error. Will provide a fix

**Comment by turf212** [comment]
The external WS API was expecting the found value for license type to be a Boolean.  It no longer is just that.
