### ISSUE TITLE
Unassign license from educator or user will not remove them from course

### ISSUE THREAD

**Issue by amirtq** [iomad/iomad#1300]
Hi there
When we assign license to a educator or user, it will add them to the course, but when we unassign that  license from educator or user, they will still have the course in their list, and also they will have the permissions on the course.
license is an usable license.
is it a misconfiguration or a BUG ?

**Comment by amirtq** [comment]
we are using IOMAD 3.8

**Comment by amirtq** [comment]
@turf212

**Comment by turf212** [comment]
Is the license type normal or re-usable?  You should only be able to remove a re-usable license from a user who has already used the license.  Otherwise the enrolment and license can't be removed.

**Comment by amirtq** [comment]
the license type is re-usable, the issue is same for Students and Educators

**Comment by amirtq** [comment]
@turf212 do you have any idea?

**Comment by turf212** [comment]
I've tested this on a couple of test systems without issue.

What were your exact steps to get the error in case I'm missing something?

**Comment by turf212** [comment]
FYI I did the following:

- Created 2 courses which were license types
- Created a user
- Created an Educator user
- Created a reusable instant license for both courses
- Created a reusable instant educator license for both courses
- Went to the iomad dashboard -> Licenses -> user license allocations page
- Selected the user reusable license and allocated the courses to the user (observerd user was enrolled as student on the course)
- Removed all of the license allocations (observed user was removed from course)
- Allocated one license to a single course (observed user was enrolled on the course as a student)
- Removed license from that course (observed user was unenrolled from the course)
- Allocated license for all courses to user (observed user was enrolled as a student on all courses)
- Removed license allocation for one course (observed user was a student in the other course only)
- Removed remaining license from user (observed all enrolments were removed)
- Repeated allocation and unallocation tests with educator license and user with the same observed results except this time the user was given a client course role and not student.

Result - As expected.

**Comment by amirtq** [comment]
What I did was exactly same as you did but with different result

- Created multiple courses
- Created a reusable license ad attached all courses to the license
- Went to the iomad dashboard -> Licenses -> user license allocations page
- Selected the user reusable license and allocated one of the courses to the user (observerd user was enrolled as student on the course)
- Removed the reusable license from the user using iomad dashboard -> Licenses -> user license allocations page, **HERE IS THE DIFFERENT:**
(observed user was not unenrolled from the course)
-

**Comment by turf212** [comment]
What other licenses do these users have for the same course?  In case this is what is causing the issue?

**Comment by amirtq** [comment]
in our scenario there is only one reusable license to handle all courses so actually, there is only one license assignment to a user to a course.
so I believe we dont have multiple licenses on single course for a user
