### ISSUE TITLE
Editing courses as a company manager

### ISSUE THREAD

**Issue by moxxuk** [iomad/iomad#1301]
Hi, I understand how to enable course creation for course managers (by adding the block/iomad_company_admin:createcourse capability to the company manager role) - the only thing is, it only creates the course, there's no way to edit it.

Assigning them as course educator (I've switched off the 'Enrol managers as non students' option to allow this) doesn't seem to make a difference?

We are offering companies a (sub)set of predefined courses from our catalog, which are spread across multiple categories. (i.e. one company gets 2 courses from Health and Safety category, 3 courses from Personal Development category; another company has just one course from each category). This is working OK. We don't want course managers to be able to edit these courses, but we want to allow them to add their own courses and categories, and potentially even their own courses to our categories, obviously without other companies seeing their courses/categories.

Is this possible?

**Comment by amirtq** [comment]
An easy way is to grant "moodle/course:update" to the "Company Manager" role so they can edit all courses across the company.

**Comment by amirtq** [comment]
However, Im not sure with this permission, Comapny manager will have access to courses from other ocmpanies or not, I will test it and feedback

**Comment by moxxuk** [comment]
Thanks for the response - I was just wondering the same thing. I'd be interested to know what you find out!

**Comment by amirtq** [comment]
I will update you in a couple of hours, its easy to test

**Comment by amirtq** [comment]
Okay it looks its safe to grant "moodle/course:update" to "Company Admin" then he can edit only courses in his own company.
In addition, to make him able to edit courses without being enrolled to a course, you should grant him another permission which is "moodle/course:view" so if company admin goes to Home Page, he can see all courses including those are without any participant and he can start editing the course without enrolling himself as student or educator.

**Comment by amirtq** [comment]
It looks because IOMAD is managing access levels using Moodle categories, in any way, "Company Admin" has access only to courses under his Category (Which is logical container of his Company)

**Comment by moxxuk** [comment]
Wow, thanks for your investigation @amirtq . Looks like this could be an option.

Am I right however in thinking a company manager cannot create their own categories? This is an essential part of our offering so we need to make sure that that could also work, without them being able to access anybody else's categories.

**Comment by amirtq** [comment]
I think there is another option which is departments in a company but I really dont know the logic behind departments so maybe its better to close this ticket and open another one, and ask @turf212 to help as he is the GOD of IOMAD!

**Comment by moxxuk** [comment]
Thanks for all your help @amirtq, I shall try another ticket and see if I get a response there.

**Comment by turf212** [comment]
The only thing which you will need to check/be careful of when changing this capability (as it really means across the whole site the user can view or edit a course) can they gain access to courses outside of their company bu changing the id number in the URL.  It's why they were just given the editing role within the company itself.  Of course, that model may not work for you so it will be interesting to see what we would need to fix this.

Regarding creating categories, the company users should be able to see all categories and child categories which belong to the company (or no company, so be careful!) There is a manage categories capability but we don't want them being able to create a course (as it wouldn't belong to the company under the hood) so you would need to test and make sure that it didn't allow that.

Thinking about this some more, we would probably want this to be in an Iomad page and then the category selectable when you create the course.  That may be the correct solution.

**Comment by petergaiello** [comment]
@turf212 in reading along this forum I have been able to put this in place for our instance, however I have a wrinkle I am having trouble solving. I need to make editing available and used moodle/course:update to do so, however we have courses that we do not want them to be able to edit that they have access to. Companies have the option to create their own courses, or use ours within our intended environment. 

Any help/guidance is so greatly appreciated.

**Comment by dallenk** [comment]
Apologies, I hate bumping up old threads but wanted to add some information here that could be a security/permissions bug or problem.

for "company manager" role I can add the following permissions:
    "block/iomad_company_admin:createcourse"
    "moodle/course:update"
    "moodle/course:view"

and indeed the company manager can create courses in the company and appears only viewable within the company.   However the Company Manager cannot really edit the course as there are no available activities or resources when trying to add one.

Additionally an existing activity or resource is missing the edit options (screenshots)
![image](https://user-images.githubusercontent.com/2725066/101114135-b0f24a00-3595-11eb-971c-d6529b775a38.png)

![image](https://user-images.githubusercontent.com/2725066/101114159-bbacdf00-3595-11eb-833c-36fec4c28ce9.png)

Another issue is a closed shared course from another company is allowed to be edited by another company manager.  

@turf212, Derek, can you confirm if this is the intended action? or should a company manager be allowed to edit a course from another company when it is shared?

I have 'nested' companies within IOMAD.  Two companies, and each has three child companies under them without departments.

Thanks!

(If you would like to me to create a new thread I will)

**Comment by turf212** [comment]
The issue with company manager role being given capabilities to edit courses is that this is applied at a site level and they will have that access on any course they are enrolled in.

When a company manager creates a course (assuming you have not changed the default setting for local/iomad settings/enrol managers as non student in which case for company manager read educator) then they are given the client course editor role within that course.  This is the equivalent of the editing teacher role (but without access to anything which could be outside of their own users).  Any course which they have not created, they are instead given the client course access role (which is the equivalent of the non editing teacher role).  As company mangers are promoted/demoted these are automatically given to them.  Department managers only get the access role.

You can obviously change the capabilities of these roles at a site level (and further change them within a company using the restrict roles page) to get them to where they need to be.

Shared courses do not get the editor roles either as this would allow someone to see outside of their bubble.

**Comment by turf212** [comment]
Should have said, the switch as to whether a course is editable or not is currently within the mdl_company_created_courses table which has companyid/courseid only in it.

**Comment by dallenk** [comment]
Thanks Derek, I will double check my settings.  I do believe I modified the company manager as student default so I will change it back and recheck this.  Allowing a person within a company to be able to create and edit company courses is a major requirement for my project so I hope I can get this configuration nailed down.   I may contact you directly for custom work (compensated of course) and released in the code for everyone to benefit from if this is an option available.

**Comment by dallenk** [comment]
OK.. I could not make this work the way I think you described it so I installed a completely fresh 39 and set it up companies like so:  (in case I changed something else and didn't notice)
![image](https://user-images.githubusercontent.com/2725066/101268197-4ec05300-3715-11eb-8d68-d11b2a7c09d1.png)



Each child company has three users, one Company Manager, one Training Manager, and one user following this format
![image](https://user-images.githubusercontent.com/2725066/101268272-02294780-3716-11eb-8983-2384228a494c.png)



dev.domain.ca has one course, closed shared, and assigned to each of the 2nd level child companies

Each "Training Manager" enrolls the "user" of their company into the shared course


"Out of the box"
-- Company Managers cannot create courses in their own companies.
-- Training Managers cannot create courses in their own companies
-- All users can see the course shared to each company
-- No user can edit any course
-- Company Manager cannot edit roles for participants of the course
-- Company Training Manager cannot edit roles for participants of the course
-- Only the user shows with a role, Company Manager and Training Manager have no roles 
![image](https://user-images.githubusercontent.com/2725066/101268521-9c8a8a80-3718-11eb-8434-4d2cdc3d32a7.png)

**Dashboard / Site administration / Users / Permissions / Define roles**
Enabling  "block/iomad_company_admin:createcourse" for Client Course Editor:
-- Company Managers cannot create courses in their own companies.
-- Training Managers cannot create courses in their own companies
-- All users can see the course shared to each company
-- No user can edit any course
-- Company Manager cannot edit roles for participants of the course
-- Company Training Manager cannot edit roles for participants of the course

**Dashboard / Site administration / Users / Permissions / Define roles**
Enabling  "block/iomad_company_admin:createcourse" for Company Manager:
-- Company Managers can create courses in their own companies.
-- Training Managers cannot create courses in their own companies
-- All users can see the course shared to each company
-- No user can edit any course
-- No roles show for the "company Manager" user viewing course participants


But, If I view the Moodle Dashboard / Courses / Participants list.. here I see all the roles as the site admin user
![image](https://user-images.githubusercontent.com/2725066/101269058-3c4b1700-371f-11eb-98a5-05446bdcaba9.png)


which leaves me very confused now.  I can see no way to assign the "teacher" role, aside from the site admin account adding the "teacher" role manually.   Can you clarify if this is the intended way?  A manager of a company should be able to create/edit courses by default, and there should be a method for the Company Manager to assign the teacher/course editing role to any member of the company for courses created within the company.   Or an additional option to assign a user to a permissions to create/edit courses within the company here:
![image](https://user-images.githubusercontent.com/2725066/101269265-15421480-3722-11eb-8cd4-046ed2639828.png)


I can give you access to my site if you can find something I've done wrong, I don't even mind paying for an hour of your time to configure it and tell me how it should be done, but I do think by default these capabilities should be pre-configured with permissions.

Thanks so much, this really is a great addition to Moodle!

**Comment by ghost** [comment]
Company manager unable to create course.. How do I fix this?
In https://demo.iomad.org/ link, company manager can able to create, edit course. 
What I've to do for this issue? I am stuck here for a long time, and could not to find a proper documentation.
please help...
