### ISSUE TITLE
Iomad integration with WordPress

### ISSUE THREAD

**Issue by LucasOliveiraS** [iomad/iomad#1306]
Hello, I am trying to integrate Iomad with Wordpress and I would like to know if it is possible to integrate only one company and list these courses on Wordpress. I'm using the Edwiser Bridge plugin. It works well with standard Moodle, but since Iomad has Multi-Tenancy functionality, I don't know if it is possible to just list courses from a single company.

**Comment by turf212** [comment]
The issue with Course Merchant is that it only works with manual enrolment courses and does not understand about the company groups when using shared courses.

Iomad has a suite of plugins which are currently in Beta that allow for WooCommerce to be synced up with Iomad using the additional groups plugin.  This allows you to leverage the WooCommerce eCommerce plugin (and all of it's additional plugins/payment gateways) whilst using groups to keep products (and prices) separate between companies.  There is also the option within Iomad to point the shop to a different instance of the WordPress/WooCommerce site per company too.  The plugins will enrol a user straight into a manual enrolment course and will provide the user a license for licensed courses.  It also, through groups, can be set up so a manager can purchase a set of courses which can then be allocated at a later date.

We have a couple of clients who are already using these plugins and they require licenses to be enabled (so will not be free).  Please let me know if you would like to be part of this trial by sending an email to info@iomad.org.

**Comment by nielsharma** [comment]
Hi Derick,
I'm interested in your IOMAD/WooCommerce plugins. I've tried send an email to info@iomad.org but got a bounce back.

**Comment by turf212** [comment]
Answered your query there.

**Comment by actXc** [comment]
**how to buy the plugins or become part of the trial?** 

email sends: 

  info@iomad.org
    SMTP error from remote mail server after RCPT TO:<info@iomad.org>:
    host mailx.e-learndesign.co.uk [54.247.101.217]:
    550 5.1.1 <info@iomad.org>: Recipient address rejected:

**Comment by turf212** [comment]
Ah.  My apologies.  The one I got through must have been direct from the website.  Please try again.

**Comment by michalludynia** [comment]
I’m interested in WooCommerce integration with my instance of IOMAD. I've sent an email to info@iomad.org, got a new ticket on ElearnDesign platform, but I've got no reply for over a week. 
@turf212  Can you share me more details about plugins?

**Comment by actXc** [comment]
Based on the service API of moodle, we have implemented Woo/Moodle plug-ins for our customers. 
For IOMAD we have a WOO module for selling IOMAD licenses for a course and give the buyer the department manager role.
This can upload students and distribute the bought licenses to the companies students.

**Comment by michalludynia** [comment]
How can we get that plug-ins? How much it costs?

**Comment by actXc** [comment]
I work at lern.link, Moodle partner in Germany, if our Moodle-customers use IOMAD, we offer the plugins. But you seem to be already in contact with ElearnDesign @turf212 and have a platform up and running.

**Comment by LeCutus1024** [comment]
As we are still waiting for a reply from ElearnDesign, I would be interested in hearing more about your plugin and its functionality.

**Comment by michalludynia** [comment]
I'm still waiting for response too.. Can't get information how to make woocommerce work with IOMAD.
