### ISSUE TITLE
After Upgrade - Missing IOMAD Plugins

### ISSUE THREAD

**Issue by demontech** [iomad/iomad#1307]
Hi Derick,

I just recently upgraded from version 3.4 to 3.6 , and it resulted of missing local iomad plugins:

![image](https://user-images.githubusercontent.com/8148238/79184761-f0331700-7dc9-11ea-8ded-16692dc7a829.png)

Are those needed and do they need to be copied from the backup (version 3.4) that I have?

Thank you!

**Comment by turf212** [comment]
These are no longer needed and you can remove them from your site.  The reports were replaced as part of the reports overhaul and the dashboard was moved to the user's dashboard so no longer required it's own block.
