### ISSUE TITLE
Error while uneroll from Courses tab - User enrolments

### ISSUE THREAD

**Issue by diokast** [iomad/iomad#1308]
While trying to unenroll a user from a course through Courses tab - User enrolments, the error "block_iomad_company_management/invaliduserdepartment" is thrown

If we try from User tab - Edit user - User controls - Change user enrolments works fine

We are using IOMAD 3.6 latest version

**Comment by turf212** [comment]
I've just tested this with the latest 3.6 code and it was working fine.  There was a fix for this under #1304 which was pushed on the 8th of April.  Can you please check that you have the latest 3.6 code and try again.

**Comment by diokast** [comment]
Thanks, I 'll give it a try with latest release
