### ISSUE TITLE
iomad / bigbluebutton plugin installation

### ISSUE THREAD

**Issue by systemcon** [iomad/iomad#1309]
Hello, i have installed bigbluebuttonBN plugin from site administration and used my endpoint bbb server. When i create a bigbluebutton activity i got this message bigbluebuttonbn/general_error_not_allowed_to_create_instances

Any idea why? Also some other plugins I have installed are not working. The default activities/plugins works fine. 

I have installed the plugins from site administration/plugins with my main account (that one created during the first time installation of IOMAD)

**Comment by actXc** [comment]
have you checked the rights for using this plugin by the specific role?

**Comment by systemcon** [comment]
> 
> 
> have you checked the rights for using this plugin by the specific role?

Can you guide my how to do that? It's my first time with IOMAD and i haven't found any documentation except from installation. Is there any specific place where i can grant permissions for plugins?

**Comment by actXc** [comment]
https://docs.moodle.org/38/en/Override_permissions
