### ISSUE TITLE
Icons Doesn't Display in Adaptable Theme for 3.6 

### ISSUE THREAD

**Issue by demontech** [iomad/iomad#1310]
Hi Derick,

I upgraded recently to IOMAD 3.6 I've been using the Adaptable theme. This theme is the most popular for its customization. Icons on the new block dashboard are not there

![image](https://user-images.githubusercontent.com/8148238/79299800-d103ba80-7e99-11ea-9449-0677052b36aa.png)

This block works with another theme.

Thanks

**Comment by turf212** [comment]
There is a CSS fix for this in #1108  It's because the theme is Bootstrap 3.
