### ISSUE TITLE
Make course available on the homepage

### ISSUE THREAD

**Issue by LucasOliveiraS** [iomad/iomad#1311]
Hello,

I have a problem regarding the availability of courses on the home page. I have a company that has a course, and I would like that when the user (not logged in) saw the home page, that course would be visible. When I create the course through the site administration: **Courses > Manage courses and categories**. I create the course in the category of the company and the course is available for everyone to see (ie, on the home page). However, a user who is linked to this company cannot see this course, even though the course is within the category of the company. The user will only be able to see this course if I go to the **Iomad dashboard and assign this course to the company**. I would like to know if there is a way to make the course visible on the home page and still the user of this company can enroll in it.

**Comment by turf212** [comment]
Creating courses using the Moodle Site admin menus and putting them into the company course category does not assign the course to the company.  If a course is not assigned to a company, then it is visible to everyone.  Which is what is happening here.  To fix this, you can use the Assign to company menu item under the courses tab with the appropriate company selected, search for and then assign the course.  Please note, this is also how you assign closed shared courses to other companies, so you will see a list of all unassigned courses and closed shared courses.  In future use the create course menu item under the courses tab in the Iomad dashboard and this will perform all of the company assignation tasks too.

The company course category is simply a convenient place to put courses which have been created within a company.

For your question of making courses for one company available on the front page without the user being logged in, this is only possible if you are identifying the company in question in another way.  The guest user (which is the account that sees this information) does not belong to any company.  In 3.8 and later you can use the company hostname value and use the URL to specify the company.  This will require work done on your webserver to ensure that the company hostname will be served by the same directory as your main Iomad URL.

**Comment by LucasOliveiraS** [comment]
Thanks for answering @turf212. I'm trying another approach, as you suggested, I'm creating these courses outside of Iomad, so everyone can see, I changed the Iomad registration settings, so every user who signs up on the site is not directed to a company. However, those users who register on the site, when they click on the panel in the left corner, can see a company from Iomad, is there a way to leave them isolated? For example, users who register on the site see only public courses?

**Comment by turf212** [comment]
Yes.  Put them in their own company.  I.e. create a company where all of the users who are not actual company employees will go.  This can then be used for drive-by access or purchasing for individuals rather than the typical company employee.  This is what you would set the default company to be when setting up the per company domain matching.  Where it dumps people when they don't match a real company.
