### ISSUE TITLE
block_iomad_company_admin_assign_users does not assign capabilities

### ISSUE THREAD

**Issue by fryeguy63** [iomad/iomad#1325]
We have an internal workflow from our CRM system that makes four API calls to our Iomad site. 1) create company, 2) create user, 3) assign user to company and 4) create license.

All the calls are performed and complete successfully. The result is a new company with a new user who is assigned as the Department Training Manager. When this user signs in, they should be able to go to the Iomad dashboard, add users and assign licenses to them. But the Iomad Dashboard is missing.

An administrator must login, go to the company, go to 'assign department users/managers', select the user and unassign them, then reassign them as the Department Training Manager. The next time they sign in everything works as expected.

So it appears that the block_iomad_company_admin_assign_users function does not actually assign the proper capabilities to the user when they are assigned as the manager. This behavior is in 3.8 and was also the same in 3.3 (my production environment). I would be happy to edit the code to solve this, I am struggling to understand where the problem might be.

**Comment by turf212** [comment]
The code is in blocks/iomad_company_admin/externallib.php here - 
https://github.com/iomad/iomad/blob/e6929a750031087175ba0d7232001746f892bbf7/blocks/iomad_company_admin/externallib.php#L685-L688 

This fires off the $company->assign_user_to_company() call with the userid, departmentid, and managertype variables.  All of which get passed through the webservice call.  Are you definitely passing a mangertype value?

0 = user
1 = Company Manager
2 = Department Manager
3 = Educator (if you have this turned on within the Iomad settings).
4 = Company report only

**Comment by fryeguy63** [comment]
Yes, I pass managertype = 2 and when I login and view that company, the user is listed as a department manager but when they login the Iomad Dashboard is missing.

So I go to their company and unassign them and then reassign them as a department manager and everything works normally.

I followed the logic today and it looks like the $company->assign_user_to_company function calls the upsert_company_user() function which should make the call to - 
https://github.com/iomad/iomad/blob/e6929a750031087175ba0d7232001746f892bbf7/local/iomad/lib/company.php#L1143-L1147

When I check the db, the company_users record is updated and shows the managertype = 2.
![image](https://user-images.githubusercontent.com/2111499/80436774-263dc400-88bd-11ea-9dec-b3f5a3c2c0ca.png)

But the record never gets added to role_assignments until I unassign/reassign the user. Then it works fine.

**Comment by fryeguy63** [comment]
I added this hack in the blocks/iomad_company_admin/externallib.php file that makes it work for me.

![image](https://user-images.githubusercontent.com/2111499/80514035-2f6e7580-893d-11ea-984b-b2cb77a643cc.png)

Not sure why the role_assignment doesn't fire otherwise...

**Comment by turf212** [comment]
We don't use system roles any more.  Roles are assigned at Company context
