### ISSUE TITLE
Re-send user details does not re-send email

### ISSUE THREAD

**Issue by nielsharma** [iomad/iomad#1326]
Hi, 
I've tried to re-send user details via the IOMAD Dashboard: Users tab -> Edit users -> User controls -> Re-send user details.

I've tested this a few times using different accounts and the users never received their logon details.

![re-send user details](https://user-images.githubusercontent.com/47655776/80329915-0db2b700-8887-11ea-80e0-df7f90094b93.png)

**Comment by turf212** [comment]
Check that the email template is enabled.  the template in question is user_reset / User account reset.  If it is check if the email is being created in the email report.  If it is, and it's been sent, you need to check your email server logs.

**Comment by nielsharma** [comment]
Thanks Derick,

The email template was disabled. Sorry, i should have checked that first. All working now.

Thanks for your help!
