### ISSUE TITLE
How to bring Moodle optional profile field to new user form

### ISSUE THREAD

**Issue by amirtq** [iomad/iomad#1330]
Hi there,
how can we bring an optional user filed (in example Skype ID) to the default create user form and make it required field?

**Comment by turf212** [comment]
You would need to edit the form and add in the field and make it required.  The forms in Iomad are meant to be as simple as possible so the only "extra" fields which get added automatically are optional ones for the site or company.  You could add one of those instead of the standard Moodle one.

**Comment by amirtq** [comment]
by editing the form, you mean to do some hard coded changes?
it will impact further system updates, we are trying to do not apply hard codes on the system.
and I did not get your meaning by:
_**You could add one of those instead of the standard Moodle one.**_
would you please explain a bit more?

**Comment by shadyshrif** [comment]
I faced the same challenge and I fixed it by adding a rule to make the field required if the required option is set when the field was created 

Go to:
blocks/iomad_company_admin/classes/forms/user_edit_form.php

find the section that shows the profile fields
```
            // Display the header and the fields.
            foreach ($fields as $field) {
```

add this code before the end of the loop

```
                // add rule to make the field required if the required option is set when the field was created
                if ($field->required) 
                    $mform->addRule($formfield->inputname, $strrequired, 'required', null, 'client');
```

So your code would look like

```
        // Optional profile fields.
        $mform->addElement('header', 'profile_id', get_string('profilefields', 'mnet'));
        // Get global fields.
        if ($fields = $DB->get_records_sql("SELECT * FROM {user_info_field}
                                            WHERE categoryid NOT IN (
                                             SELECT profileid FROM {company})")) {
            // Display the header and the fields.
            foreach ($fields as $field) {
                require_once($CFG->dirroot.'/user/profile/field/'.$field->datatype.'/field.class.php');
                $newfield = 'profile_field_'.$field->datatype;
                $formfield = new $newfield($field->id);
                $formfield->edit_field($mform);
                $mform->setDefault($formfield->inputname, $formfield->field->defaultdata);

                // add rule to make the field required if the required option is set when the field was created
                if ($field->required) 
                    $mform->addRule($formfield->inputname, $strrequired, 'required', null, 'client');
            }
        }
```
