### ISSUE TITLE
h5p with IOMAD theme only 300px wide settings

### ISSUE THREAD

**Issue by enrarelloem** [iomad/iomad#1332]
When using H5P with an IOMAD theme, the h5p section in the settings of the activity is only approx. 300 pixels wide i.e. completely unusable.
When I switch to a non-IOMAD theme, the settings for h5p appear to be responsive and adapted to screen width.
This behaviour is consistent from IOMAD 3.6. to 3.8.2+.
Any ideas to get around this problem would be much appreciated!
Thanks!

**Comment by turf212** [comment]
adding the CSS:

.form-inline {
    display: inline;
}

appears to fix it for the H5P settings page but I@m not sure what other issues that would cause.  The CSS between the Iomad Boost and Boost themes for moodle.css dont have any differences around that.
I've checked a couple of other activity settings pages after that change and it appears to be OK.  I'll need to dig further to see what the difference would be, though.

**Comment by turf212** [comment]
checked this on Moodle 3.6 under Moodle boost and the settings page is thin too.

**Comment by turf212** [comment]
Also Iomad 3.8 Boost theme has the display settings narrow too.  Exactly the same as for Iomad Boost.

**Comment by enrarelloem** [comment]
> adding the CSS:
> 
> .form-inline {
> display: inline;
> }

Sorry, for not replying earlier!
That piece of CSS fixed the issue.
Thanks a lot. The fix makes my life much easier!
Just for the record: In Moodle 3.8 the behaviour of the activity exported from IOMAD is normal.
