### ISSUE TITLE
How to purge Moodle/IOMAD database?

### ISSUE THREAD

**Issue by amirtq** [iomad/iomad#1340]
Hi there
we have a production IOMAD that has many changes from original empty installation and now we want to mirror it to our dev environment but we dont want the production data to be there
is there any way to purge all data after importing from production to dev?
by all data, I mean every company, user, course, activity, etc.

**Comment by turf212** [comment]
If you are removing all of the data including all courses and users then the simplest thing to do would be to install a fresh version using the same code base and plugins you have and then backup and restore the mdl_config and mdl_config_plugins tables from live to your dev site.  You will need to go back in and change the site name and so on in the dev site but this will bring over all of the configuration settings from one to the other.  Be aware, this will not bring over any files you have uploaded and you will need to re-do them.

**Comment by amirtq** [comment]
Thanks for reply
the challenge is that we have a lot of config changes in Moodle and its somehow impossible to re-install with same code.
so the best option is to purge data and delete all records including company, users, courses etc.

**Comment by amirtq** [comment]
What we finally did,
Deleted all Users from Moodle
Deleted all courses and categories from Moodle
Suspended all companies in IOMAD
Deleted all IOMAD companies from the MySQL table
I dont know the negative impact if there is any but it seems to be a workaround
