### ISSUE TITLE
Error on IOMAD login page

### ISSUE THREAD

**Issue by shakum** [iomad/iomad#1341]
![error](https://user-images.githubusercontent.com/356407/81082565-15223200-8f11-11ea-9247-9da05622bc59.PNG)

Hi,

Can someone tell me what i am doing wrong. I want to have a seperate branding login page with LOGO for each tenant.  Is that possible. I get this in Dashboard page when switching/selecting the comapany in the dropdown. Please let me know, Thanks in advance

Regards,
Sankar Kumar

**Comment by turf212** [comment]
Can you please turn on full site debug and list what the message is showing?

Also, what version of Iomad are you using?

**Comment by shakum** [comment]
hi,
if i try with localhost it is working. if i try with the dns name it shows this error. attached the debug message.

![image](https://user-images.githubusercontent.com/356407/81703676-88382500-948a-11ea-8293-ddf35ad25b09.png)

**Comment by turf212** [comment]
I'd pushed something which had a typo on it which has since been fixed..  Pull the code again and it will be fine.

**Comment by turf212** [comment]
There have been some changes since you pulled your code which should address this.

If they haven't what does your config.php have for the wwwroot?

**Comment by shakum** [comment]
ok thank you.
