### ISSUE TITLE
"User promoted to manager" email does not work 

### ISSUE THREAD

**Issue by michalludynia** [iomad/iomad#1342]
Hi @turf212 
I've got a problem with "User promoted to manager". When I promote normal user to company manager, email does not appear in outgoing email report and it doesn't sent out.
I use "Assign department users/managers" tab in IOMAD panel.

My version of IOMAD: 3.8 patched today (6.05.2020).
What I've already checked:
- email scheduled tasks are running without delay on it
- installed complete new instance of IOMAD without any additional plugins
 
Can you check if that scenario works for you? I'm using completely raw instance.

**Comment by turf212** [comment]
Yeah, that doesn't look right to me either.
