### ISSUE TITLE
Error while opening API documentation

### ISSUE THREAD

**Issue by UCN0** [iomad/iomad#1346]
Exception - Argument 1 passed to external_multiple_structure::__construct() must be an instance of external_description, array given, called in [dirroot]/blocks/iomad_company_admin/externallib.php on line 315

**Comment by turf212** [comment]
which version is this for?  Tested and working with latest 3.6, 3.7 and 3.8 versions.

**Comment by UCN0** [comment]
I was using an old branch I corrected, thanks for the answer. But I found this error while trying to add functions to a service.

Can't find data record in database table external_functions.

**Comment by turf212** [comment]
I've had some issues with API calls where the Moodle mobile app WS calls were enabled.  The calls no longer exist but are listed in the database and this is causing the error.

If you edit /lib/externallib.php and change lines 86 on from 
```
            if (!file_exists($function->classpath)) {
                throw new coding_exception('Cannot find file with external function implementation');
            }
```
to
```
echo "<pre>";print_r($function);echo "</pre>";
            if (!file_exists($function->classpath)) {
                die;
                throw new coding_exception('Cannot find file with external function implementation');
            }

```
and reload the page it will tell you which function it's trying to find that doesn't have a relevent externallibphp file.  The last one listed will be the broken one.  So if the last output which is displayed before the page stops loading is 
```
stdClass Object
(
    [id] => 620
    [name] => block_dashboard_get_data
    [classname] => block_dashboard_external
    [methodname] => get_data
    [classpath] => /var/www/dev.training.tafensw.edu.au/installers/iomad-IOMAD_37_STABLE/blocks/dashboard/externallib.php
    [component] => block_dashboard
    [capabilities] => block/dashboard:export
    [services] =>
)

```
You can then remove that from the database table using:

`delete from mdl_external_functions where component='block_dashboard';`
