### ISSUE TITLE
Department and Company Short names not updating in Moodle database

### ISSUE THREAD

**Issue by lukebond68** [iomad/iomad#1348]
If a short name for the department or the company is changed after first being saved, the name isn't updated in the Moodle database, only in the Iomad database. This then creates issues like the department search function not working when searching for users in a specific department if a client changes any of their department names. It also creates issues if searching for a company in Moodle reports.

**Comment by turf212** [comment]
Hi Luke,
the Iomad change of company or department only changes the Iomad tables for these.  There are a couple of reasons for this, 1 - Institution and department were not part of the Moodle profile when Iomad was first coded so this wasn't available to re-use for Iomad, and 2 - People use the uer profile information for other things by renaming them in the language pack.

You can turn on a sync between the Iomad company and department and the Profile Institution and department within the local Iomad settings plugin settings which keeps these the same for things like restricted access and so on.  If you are coding searches the you should be using the mdl_company_users table joined to the mdl_company and mdl_department tables.   There are also plenty examples in the code which filter for the current department or the current department and child departments.  The search functions in the reports, for example, all share classes in local/iomad/lib/user.php.
