### ISSUE TITLE
Recreate stored certificates errors due to RAM requirements for php script

### ISSUE THREAD

**Issue by lukebond68** [iomad/iomad#1349]
Recreate stored certificates creates errors when recreating hundreds of certificates (after a client migration onto the portal) and does not recreate all the required certificates as it requires a massive amount of RAM assigned to php scripts (eg around 4Gb needed to recreate 6000 certificates).

**Comment by turf212** [comment]
When you run the script it spits out the ID number of all of the local_iomad_track ID's its processed.  One of the variables the form or CLI script can take is an ID number which it will use as a starting place.  If you re-run the script/form from the next to last ID number it will resume from where it failed.
