### ISSUE TITLE
How to create activity plugin in iomad which has diffent plugin settings for each company

### ISSUE THREAD

**Issue by zuheb123** [iomad/iomad#1350]
Hi

i have created one activity plugin for moodle which had admin settings. but i install the same plugin in iomad only super admin is able to do that setting of the plugin. I want to give settings for each company manager so that company level company managers can provide settings to create activity at company level courses.

regards
Zuheb

**Comment by turf212** [comment]
If you look at how the auth/iomadoidc plugin works you could follow the same method.  Specifically, if you get the current company the user is working with (tied to the company the user is in when they are a company manager and only in one company or the selected company for the site admin) then you can append the company ID tot he config settings.

E.g. 
$CFG->myplugin_setting_a
becomes 
$CFG->myplugin_setting_a_1
for company ID 1.

In this case I had to set the whole setting name as a variable to allow it to work but you could probably escape it.

**Comment by turf212** [comment]
Another plugin to look at is the latest block/iomad_commerce which has a default external shop URL and the capability of having a company specific external shop URL.
