### ISSUE TITLE
New Feature 3.8 Implementation

### ISSUE THREAD

**Issue by nadjavon** [iomad/iomad#1353]
Sorry but need help please. How do I implement step by step, the following new features. I have been desperate for this for a while now. Installed 3.8 but not certain how to implement both below. Thanks.
1. "Branded login, logout and signup pages
The default Moodle login, signup and logout pages now will accept company id and shortname parameters (?code=&code=) which will pass the company branding to these pages.
Distinct URLs per company across the whole site
2. Following the previous change, Iomad 3.8 can now use the hostname value in the company definition to define the company $CFG->wwwroot setting. This means that your Iomad site will look like it is different sites using different URLs throughout while still remaining a single multi-tenant site."

**Comment by turf212** [comment]
So for the URL per company

- set up a hostname for the company in a DNS record with the same IP address for your webserver.
- set up the webserver to listen to this hostname and to use the same document root as your Iomad site
- edit the company in the iomad site and change the hostname to be the hostname you set up in the DNS record.

E.g.  demo.iomad.org, testcompany.iomad.org and anothercompany.iomad.org all have the same IP address.  The webserver they are on will direct all of these virtual hosts to the same document root /home/iomaddemo/public_html.  The company definition for Test Company has a hostname of testcompany.iomad.org and the company definition for Another Company has a hostname definition of anothercompany.iomad.org.   Visiting the company URLs will give the branding for the company on the front page and the login pages.

**Comment by nadjavon** [comment]
> So for the URL per company
> 
> * set up a hostname for the company in a DNS record with the same IP address for your webserver.
> * set up the webserver to listen to this hostname and to use the same document root as your Iomad site
> * edit the company in the iomad site and change the hostname to be the hostname you set up in the DNS record.
> 
> E.g. demo.iomad.org, testcompany.iomad.org and anothercompany.iomad.org all have the same IP address. The webserver they are on will direct all of these virtual hosts to the same document root /home/iomaddemo/public_html. The company definition for Test Company has a hostname of testcompany.iomad.org and the company definition for Another Company has a hostname definition of anothercompany.iomad.org. Visiting the company URLs will give the branding for the company on the front page and the login pages.

Thanks, will let you know of the outcome, regards
Noel

**Comment by turf212** [comment]
If you look at the demo.iomad.org site you can see the setting within there for the companies I've mentioned.

**Comment by turf212** [comment]
Oh and for other companies, where you you want to use passed URL parameters, see #1354
