### ISSUE TITLE
SIGN-UP

### ISSUE THREAD

**Issue by nadjavon** [iomad/iomad#1354]
Hi All, How do I activate or use "local/iomad_signup/login.php" for New Users.Sign UP instead of the default moodle sign -up page?, Thanks

**Comment by evaristorivi** [comment]
Hi, I have that question. It's activated in local plugins.
But then I go to mysite.com/local/iomad_signup/signup_form.php and the blank page comes out.

**Comment by evaristorivi** [comment]
It may not work in PHP 7.4 on Ubuntu 20 ?

**Comment by nadjavon** [comment]
> Hi, I have that question. It's activated in local plugins.
> But then I go to mysite.com/local/iomad_signup/signup_form.php and the blank page comes out.

I did but unfortunately I put the URL in the alternate URL space on the "Manage Authentications" page and it logged me out with no way to get back in because the iomad sign up form was blank.

**Comment by turf212** [comment]
PHP 7.4 is only just supported in Moodle 8.3.3 + so it's quite likely that any issues on that page haven't been picked up yet.  You can, instead, use the standard Moodle signup form either by using the per compayy URL (see #1353) or by passing the same parameters as you would have to local/iomad_signup/signup.php to login/signup.php which are _?id=<companyid>&code=<companyshortname>_  So if you have a company record which is 
id = 1, name=Test Company, shortname = tc
then the resulting URL would be

_/login/signup.php?id=1&code=tc_

You can use the same on the login page too

_/login/index.php?id=1&code=tc_

and the signup page on the login page will retain the desired company.

**Comment by turf212** [comment]
For the blank page, if you are using 7.4, can you run the php against it from the command line and post the error output?

**Comment by evaristorivi** [comment]
> PHP 7.4 solo es compatible con Moodle 8.3.3+, por lo que es muy probable que todavía no se hayan solucionado los problemas de esa página. En su lugar, puede usar el formulario de registro estándar de Moodle, ya sea mediante el uso de la URL por empresa (consulte [# 1353](https://github.com/iomad/iomad/issues/1353) ) o pasando los mismos parámetros que tendría a local / iomad_signup / signup.php para iniciar sesión / signup.php, ¿cuáles son _? id = & code =_ Entonces, si tiene un registro de empresa que es
> id = 1, name = Test Company, shortname = tc
> , la URL resultante sería
> 
> _/login/signup.php?id=1&code=tc_
> 
> También puede usar lo mismo en la página de inicio de sesión
> 
> _/login/index.php?id=1&code=tc_
> 
> y la página de registro en la página de inicio de sesión retendrá la empresa deseada.

I'm using the last  IOMAD_38_STABLE

**Comment by turf212** [comment]
Soory, I possibly should have been clearer :)

I've not tested the Iomad code with PHP 7.4 as this was not supported within Moodle (which Iomad is based on) until the release on 18th of May.  The weekely release has not been added to the current IOMAD_38_STABLE branch so is still not supported for Iomad.

If you are using PHP 7.4 and you are getting an error, then please raise this as a bug so I can look at those pages.  If the page is simply showing a white screen, then you need to run PHP against that page in the command line as it's failing before it starts to get rendered (usually caused by a syntax error in the code).

**Comment by evaristorivi** [comment]
Oh! Thank you so much!
Sorry, it's my fault, I'm a php novice.
Then it would be advisable to go back to 7.3.

Ok I'll do as you say.

**Comment by evaristorivi** [comment]
![image](https://user-images.githubusercontent.com/34553420/82739007-8862db00-9d3c-11ea-99a3-2fdaedd835c9.png)
The answer is nothing. :S

**Comment by turf212** [comment]
which suggests there are no errors with that file., so the issue is not with that but is with one of the files which it also uses.   These are:
signup_form.php
and ../../user/editlib.php
If you could do the same please?

**Comment by evaristorivi** [comment]
ok! :)

![image](https://user-images.githubusercontent.com/34553420/82754779-aaf20400-9dcf-11ea-8e80-58c8cdac7602.png)

**Comment by evaristorivi** [comment]
line 25:
![image](https://user-images.githubusercontent.com/34553420/82754834-f4425380-9dcf-11ea-921a-29675d28f49e.png)
![image](https://user-images.githubusercontent.com/34553420/82754895-5307cd00-9dd0-11ea-97f3-47bcbcb9b8d0.png)

**Comment by turf212** [comment]
Again, thse are OK as the $CFG variable will get defined elsewhere.  It's more syntax errors which I'm looking for.

Does the page load eventually (such as when you refresh the cache with a Boost theme and it takes a minute or so to load up)?  Is there anything in the webserver error logs?

**Comment by evaristorivi** [comment]
https://moodle2.evaristorivieccio.es/local/iomad_signup/signup_form.php
The page loads quickly, and it looks blank.
From private tab, different browsers, cleaning cache, etc...


No errors in /var/log/apache2/error.log

**Comment by turf212** [comment]
FYI we have moved over to use the login/signup.php pages instead of this one in more recent versions of Iomad which now handles all of the same parameters/setup as the original /local/iomad_signup/signup.php page.
