### ISSUE TITLE
Iomad "User Login report" and "Users report" pulling too much data and timing out 

### ISSUE THREAD

**Issue by lukebond68** [iomad/iomad#1355]
The reports are returning 30Mb+ of data for even just one user and the reports are timing out.

**Comment by tomster1969** [comment]
The pages are having a large amount of empty data returned to them in the form of empty table data. The CSS class .emptyrow is then not displaying them as they are set to display:none.

![image](https://user-images.githubusercontent.com/65608802/82336526-9d5d0880-99e2-11ea-971c-8d19ec281148.png)

**Comment by turf212** [comment]
Which version is this?  The reports were completely rewritten in 3.6 onward and are significantly faster.

**Comment by lukebond68** [comment]
We’re using v3.6.6

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by turf212** [comment]
what kind of numbers do you have for that company?

I've just run this on my test 3.6.10 site and 90 pages of 30 rows for user login report and the page was rendered in 1.76 seconds.  This was for 1 company out of 270 and 55k company users.

There are no empty empty row classes on the page

![image](https://user-images.githubusercontent.com/1685229/82377178-360f7a80-9a1b-11ea-8d0b-d4de9c635f93.png)

There have been some changes to the local/user_login code since that version but nothing which would make changes to the way the table is classed.

There have been more changes to local/report_users since 4c74bd45ca1a560df7cc3e1376362f5045e1d423 (the 3.6.6 Iomad version tag) but more around ensuring that courses from other companies are not shown to company managers where the user has been moved and the clear/delete buttons.  FYI the Users report for 91 pages of 30 users took 2.12 seconds to render.  Again there are no emptyrow table classes.

**Comment by tomster69** [comment]
Would you be able to advise why we might be getting empty rows returned?

Thanks

**Comment by turf212** [comment]
I'm honestly not sure.  The reports are built on the new Moodle table APIs which allow for the user to customise how the table is being displayed so you can change the ordering, hide columns and so on.  These are kept in a preference so you get the same view the next time you log in.  If you have changed the table defaults you get a piece of text which says - "Reset table preferences".  Have you done anything here which may have caused the table to not be standard?

If you want to debug the code you can turn on the DB debugging (and back off again) by putting these lines around the $table->out() function.
e.g. local/report_user_logins/index.php line 360

`$DB->set_debug(true);
$table->out($CFG->iomad_max_list_users, true);
$DB->set_debug(false);`

You can run the SQL in your database (though you will need to change the ? marks to the passed values.  These are in order at least) which will give you the raw rows which are being returned and then processed by the table.

**Comment by tomster69** [comment]
OK, so the queries run very quickly when run directly on the database and when DB mode set, so the SQL seems to be fine.

The php renders the html to the output buffer in about 2 seconds. I am coming to this conclusion by putting some echo statements around where the data is being echo'd to the table output of date("h:i:sa"); and the time difference is about 2 seconds consistently, which seems fair.

However, the whole page takes a long time to render. The footer takes ages to appear as the table is still downloading the 36MB (approx) total including many lines of 'empty data' as I posted above. If I echo the time after the table in here:

if (!$table->is_downloading()) {
    echo $output->footer();
    echo '</br>Right after the footer '. date("h:i:sa");
}

2 seconds have 'elapsed' in the processing time, but it's over 12 seconds until the browser stops downloading and the footer appears and then the time appears following the footer. That's obviously on my internet connection, which is a fibre connection. Anyone on an ADSL it will take an age. 

Are you testing this yourself on a local server on your LAN or development server on your local machine?  That will likely not show this lag, it is a real world internet situation where it manifests.

Here's a screenshot of the html that's being generated by the php which shows the scale of the issue:

![image](https://user-images.githubusercontent.com/7557403/82808564-201e1180-9e82-11ea-9680-7a8a5d207f13.png)

**Comment by turf212** [comment]
I've tested this on a local instance and also on a number of live clients.  E.g. login report for one company which has 516 pages loaded in 1.41 seconds.  This is also fibre but, as there are no "emptyrow" table entries I don't believe that will make much difference to the page load times as it's just 30 rows and not 49530 rows.

Have you made any changes to the Iomad code?  Specifically /lib/tableib.php  Have you changed any unusual options in your config file?  Are you using a non-standard theme which has overwritten the table classes?  It looks like the table is producing the number of rows on the page (so is not using pagination)

**Comment by tomster69** [comment]
As far as I am aware there have not been any modifications to /lib/tableib.php

I  checked that file and found this starting around line 1160:

function finish_html() {
        global $OUTPUT;
        if (!$this->started_output) {
            //no data has been added to the table.
            $this->print_nothing_to_display();

        } else {
            // Print empty rows to fill the table to the current pagesize.
            // This is done so the header aria-controls attributes do not point to
            // non existant elements.
            $emptyrow = array_fill(0, count($this->columns), '');
            while ($this->currentrow < $this->pagesize) {
                $this->print_row($emptyrow, 'emptyrow');
            }

If I comment out these lines:

 $emptyrow = array_fill(0, count($this->columns), '');
            while ($this->currentrow < $this->pagesize) {
                $this->print_row($emptyrow, 'emptyrow');
            }

The reports now loads and render very quickly.

This code is also in the most current Moodle version 3.8.3
