### ISSUE TITLE
Connections to scorm multiply every 50 minutes

### ISSUE THREAD

**Issue by soporteipeditorial** [iomad/iomad#1356]
We have detected that every 50th minute of every hour, the students' connections to the scorm (specifically to the datamodel.php files) are multiplied by 50.
We have ruled out that it is a cron job, but we have not been able to detect the reason.
The platform is IOMAD 3.5

![Captura1](https://user-images.githubusercontent.com/65596044/82342065-78bc5d00-99f1-11ea-9bb7-8e8616673178.PNG)

**Comment by turf212** [comment]
The activities within a course with the exception of the trainingevent module are all core Moodle.  There are keepalives in the Moodle SCORM player to prevent disconnections and also to ensure that data is consistently being written to the Moodle DB.  Could this be the issue?
