### ISSUE TITLE
Companies can see all users not assigned to a company

### ISSUE THREAD

**Issue by davidpesce** [iomad/iomad#1358]
When in Companies > Assign Users, a company admin can see all users not assigned to a company. There doesn't appear to be a way to disable this in "Restrict capabilities".

IOMAD_38_STABLE (latest).
PHP 7.3

**Comment by turf212** [comment]
This is how the selection is designed to work.  You can only add users who are not assigned to another company to a company (unless we are talking as an external company manager but this is not from this page).  The capability to turn it on/off is block/iomad_company_admin:company_user

**Comment by davidpesce** [comment]
Perfect! That did it. Thank you!!
