### ISSUE TITLE
Iomad not loading Adaptable Theme after logging out

### ISSUE THREAD

**Issue by cathac** [iomad/iomad#1359]
Hi! Thanks in advance for your attention. 
I've installed today a fresh  IOMAD_38_STABLE on ubuntu linux, and I installed the plugin theme Adaptable (previously downloaded from moodle site) uploading the .zip, and I chose the theme as default. 
After I log out, right in the login page the adaptable theme is not loaded. Once I log in again, I go to themes selections and it's already chosen as default but not working.

Thanks again,

Cath.

**Comment by turf212** [comment]
Hi Cath,
if the company you were editing had a different theme then this is the theme which will be seen when you log out.  This is to allow users to have a branded logout page.  If you just want to use the adaptable theme throughout the site (which will mean you can't have per company logos etc) then you can just set all of the companies to use that theme as well as making it the selected site theme.
