### ISSUE TITLE
Maximum active users at Company edit menu

### ISSUE THREAD

**Issue by systemcon** [iomad/iomad#1362]
Hello, i found the option maximum active users at company advanced settings. I set the limit at 1 but when i try to login with 2 accounts concurrent, they are able to login succesfully. Is it something different that setting? 

I need to limit the available users that can login concurent at the moodle.

Do i have to setup anything else, firstly?

thanks

**Comment by turf212** [comment]
This limit is for the maximum number of users which that company can have allocated to it at any time.  It does not restrict concurrent logins.

**Comment by systemcon** [comment]
Is there any way for concurrent login restriction?
________________________________

**Comment by slapnik** [comment]
Check this out: Dashboard / Site administration / Plugins / Authentication / Manage authentication and find the Limit Concurrent Logins option
