### ISSUE TITLE
Iomad reports: glitches due to user setup

### ISSUE THREAD

**Issue by moheyd** [iomad/iomad#1365]
Any user that is set up via the Moodle site admin panel is not pulled into the Iomad reports. Iomad reports only include users that have been created via Iomad specifically. Iomard reports should take all users into account regardless of where they have been set up.

**Comment by turf212** [comment]
That is correct.  Any user who is created via the Moodle admin panels will not be allocated to a company as the Moodle admin panels do not understand about companies as they are core Moodle code.  Please use the Iomad dashboard functions where possible to manage creation of users or courses as this does understand about companies and will assign the users/courses appropriately.

**Comment by turf212** [comment]
FYI any user who has been created via Moodle admin panels can be added to a company using the assign users option at which point they will be available to the reports within that company.
