### ISSUE TITLE
Can't Search for Certificate ID

### ISSUE THREAD

**Issue by slapnik** [iomad/iomad#1369]
The IOMAD Certificate plugin is great.  I have it working fine and displaying a Certificate ID.

Only problem is, how do I search for this Certificate ID to validate it?  I tried turning on Global search setting, and adding that block, but I couldn't get the certs to show up.

**Comment by enrarelloem** [comment]
Being just a user and not a developer, I reckon the option "Print Code" with the help text, "A unique 10-digit code of random letters and numbers can be printed on the certificate. This number can then be verified by comparing it to the code number displayed in the certificates report." , is just a forgotten left-over from the original Moodle plugin.
There is another plugin for that plugin: Verify Certificate https://moodle.org/plugins/block_verify_certificate
However, when you install this plugin/block in Iomad, it will NOT recognise the Iomad-Certificate plugin as the old Moodle certificate plugin...
As far as I can see, there is no Certificate Report.

Workaround: Search user in User Report --> view Profile My Certificates --> compare code

**Comment by turf212** [comment]
The certificate ID is stored in the iomadcertificate activity within the course.  You can see certificates for current users (so currenty enrolled and certificates for latest resits).  As described by enrarelloem, you can also compare the certificate for that user /course by using the company course completion reports.
