### ISSUE TITLE
Toggle message drawer appears as a block

### ISSUE THREAD

**Issue by nielsharma** [iomad/iomad#1372]
Hi, 

The Message drawer appears as a block on the very bottom of the page when toggled (Iomad 3.7). It took me a while to find it.. Is this how it's meant to appear in the Iomad boost theme? It toggles fine in the default Moodle Boost theme. 

<img width="500" alt="iomad-message-1" src="https://user-images.githubusercontent.com/47655776/84567344-6d274080-adbb-11ea-8515-47a4f1bc332c.PNG">
<img width="500" alt="iomad-message-2" src="https://user-images.githubusercontent.com/47655776/84567345-6ef10400-adbb-11ea-988f-871295fb9f29.PNG">

Default Moodle Boost theme:
<img width="500" alt="iomad-message-3" src="https://user-images.githubusercontent.com/47655776/84567346-6f899a80-adbb-11ea-9f48-41f2aa2a454f.PNG">

**Comment by turf212** [comment]
Which theme is this happening in?  If it's Iomad Boost then we may need to update this using the latest Moodle boost theme.

**Comment by nielsharma** [comment]
Hi Derick,
It's happening on the Iomad Boost theme.

**Comment by turf212** [comment]
I've updated the Iomad themes to use the latest versions of Boost/Classic in #1386
