### ISSUE TITLE
IOMAD SSO login with WordPress

### ISSUE THREAD

**Issue by ken4ward** [iomad/iomad#1374]
How to integrate IOMAD login with WordPress. I'll like every used in WordPress to have direct access to their IOMAD companies. Are there any development in this direction? 

I'm a developer as well, please how do I get involved in IOMAD development?

**Comment by turf212** [comment]
There is a plugin which we sell which allows for SSO to Wordpress from Iomad (so Iomad is the authority here) but doesn't work the other way around.  This allows for WooCommerce (needs this and groups) to be used to purchase courses.  The issue with going from Wordpress to Iomad is tying the user to the correct company and avoiding extra companies being created when the user makes a typo.

If you have any ideas around how this could work then I'd be happy to her them so we can improve this plugin.

**Comment by ken4ward** [comment]
I'll be glad to be part of this. Just need a direction on how to get started. I'll appreciate if you give me the hand. Hoping to hear from you. Thanks @turf212 .

**Comment by turf212** [comment]
Plugin was updated to allow for user to be created on WP and added to IOMAD company using the auto assign rules in local IOMAD signup.
