### ISSUE TITLE
When I am logging in with different account credentials, showing error as ”Error reading from database”.

### ISSUE THREAD

**Issue by Annesha-maker** [iomad/iomad#1375]
![Error](https://user-images.githubusercontent.com/55189363/84640763-c1473780-af17-11ea-9726-1fd9e8fb211e.png)

When I am logging in with different account credentials, showing error as ”Error reading from database”.
Steps to Reproduce:-
1)	Login as main Admin, navigate to other pages then logout.
2)	Login as Student or any other account, not able to see dashboard page .

Workaround  
Logged in with different browser or guest or incognito window which works fine.

**Comment by turf212** [comment]
What version of Iomad are you using?

Can you turn on full developer debug on your site (Site administration -> development -> debugging and set to full developer and display to the browser) and capture the message it shows?

I'm not having any issues with this and I use this method within testing.

**Comment by Annesha-maker** [comment]
![image](https://user-images.githubusercontent.com/55189363/87792166-210b6800-c861-11ea-9f9a-2013331d76f0.png)
Hi,
Thank you for replying.
Moodle 3.8.2

**Comment by Annesha-maker** [comment]
Iomad
![image](https://user-images.githubusercontent.com/55189363/87793969-9710ce80-c863-11ea-83cd-4313576949d3.png)
Iomad- 3.8.2

**Comment by turf212** [comment]
There were fixes for this to prevent someone logging in in the wrong company URL in later versions of 3.8.  can you please update to the latest version and try again.

**Comment by Annesha-maker** [comment]
ok thank you
