### ISSUE TITLE
Upgrade to bootstrap 4.5 in iomadboost

### ISSUE THREAD

**Issue by jamiechapmanbrn** [iomad/iomad#1377]
Iomadboost uses bootstrap 4.0.0 which has xss vulnerabilities we would like to quash. Upstream has moved to v4.3.1 (https://tracker.moodle.org/browse/MDL-64887) and recently to v4.5.0 https://tracker.moodle.org/browse/MDL-67386.

I'm creating a pr for this, but could use some details on how iomadboost is related to moodle boost and what testing is appropriate.

I've been attempting to use the builtin tests in theme/iomadboost/tests/behat but they don't appear to work as is before completing the upgrade.

I managed to get it to run w/ these changes
theme/iomadboost/tests/behat/behat_theme_iomadboost_behat_files.php:
```
-require_once(__DIR__ . '/../../../../lib/behat/behat_files.php');
+require_once(__DIR__ . '/../../../../lib/behat/core_behat_file_helper.php');
-class behat_theme_iomadboost_behat_files extends behat_files {
+class behat_theme_iomadboost_behat_files extends behat_base {
+    use core_behat_file_helper;
```

But now I'm running into duplicate context definition w/ the context blacklist doesn't seem to help.
```
Scenario: Student cannot use all options in the region main settings menu       # /var/www/html/theme/iomadboost/tests/behat/regionmainsettingsmenu.feature:35
      And "#region-main-settings-menu [role=button]" "css_element" should not exist # /var/www/html/theme/iomadboost/tests/behat/regionmainsettingsmenu.feature:40
        Step "/^I create "(?P<foldername_string>(?:[^"]|\\")*)" folder in "(?P<filemanager_field_string>(?:[^"]|\\")*)" filemanager$/" is already defined in behat_filepicker::i_create_folder_in_filemanager()
       
        behat_filepicker::i_create_folder_in_filemanager()
        behat_theme_iomadboost_behat_filepicker::i_create_folder_in_filemanager()
```

**Comment by turf212** [comment]
Which branches is this for as it may just be better to clone the core themes again and re-do the company work.  I took the boost theme and cloned it to iomadboost and iomad where I added in code to make it company aware (CSS, menu items, logos etc).  I also did the same with the classic theme.  If they have moved on then we should be updating all of them.

**Comment by jamiechapmanbrn** [comment]
bootstrap 4.3.1 made it into moodle 3.8, whereas bootstrap 4.5.0 is in 3.9. 

4.5.0 is a better choice because  they've made changed to improve the compatibility with future bootstrap versions, but neither has known xss vulnerabilities at this time. It might be wise to take try and find a more robust strategy as unfortunately this is probably going to keep coming up. Is there a way to subclass boost that would make upgrades easier?

Unfortunately looking at the changes required it's a bit larger in scope than I can chew off at the moment.

**Comment by turf212** [comment]
I've updated the 3.8 and 3.7 boost based theme (iomad, iomadboost and iomadbootstrap) to use the latest version of their theme.  Change is in #1386

**Comment by jamiechapmanbrn** [comment]
Awesome thanks!
