### ISSUE TITLE
Delete Department training managers account throwing an error   

### ISSUE THREAD

**Issue by jaysoncleofas** [iomad/iomad#1380]
![Screenshot_60](https://user-images.githubusercontent.com/42472405/84968597-7876c500-b149-11ea-959f-b4f248c946e8.png)
![Screenshot_59](https://user-images.githubusercontent.com/42472405/84968599-79a7f200-b149-11ea-89d1-37b6b2ed0247.png)

**Comment by turf212** [comment]
Thanks for reporting I'll get this checked and fixed.

**Comment by turf212** [comment]
Functionality for this has been completely overhauled.
