### ISSUE TITLE
Role Company Reporter Only - Cannot access reports

### ISSUE THREAD

**Issue by enrarelloem** [iomad/iomad#1381]
Hi there
The role Company Reporter Only should be able to access the reports through the dashboard.
I tried three different installations of Iomad 3.8 (latest was 3.8.3 (Build: 20200511)) on two different machines with themes Iomad boost, boost, classic, iomad and Iomad bootstrap.
Users with this role have a tab "Reports", however, there are no icons for the different types of reports and a click on the tab leads to no action.
Any help would be very much appreciated. Thanks!

**Comment by turf212** [comment]
If you look at the definition for that role under site administration -> Users -> Permissions -> define roles, and search for local/report you will see the list of capabilities which can be given to that role.  To view the reports it should have a :view at the end of the cap.  You can check the reports which you want them to have access to.  The defaults must be missing for this role.  I'll check and fix.

**Comment by enrarelloem** [comment]
Hello Derick
Thanks, for the swift reply!
I checked the permissions, unfortunately, they are set correctly, but no reports are displayed.
However, the Role Archetyp is set to Company Reporter which is a role that -as far as I can see - does not exist.

**Comment by enrarelloem** [comment]
WORKAROUND
I withdrew permissions from the role Company Manager bit by bit. Turned out that withdrawal of "View the license management tab" block/iomad_company_admin:licensemanagement_view took away access to the reports. If this permission is set to "allow" in the role Company Reporter Only, there is an empty tab "licences" in the dashboard, but all reports are visible.
This is definitely a glitch in the permissions.

**Comment by turf212** [comment]
OK.  Thanks for the detail.   There was some logic wrong in the block_iomad_company_admin.php file which I've changed as it wasn't setting the panel up if it got passed the ecommerce tab.  Checked with the default capabilities and the reports show up for this role.

**Comment by enrarelloem** [comment]
Thanks, Derick!
Updated and checked with two installations. Seems to work like a charm with no bad side effects.
