### ISSUE TITLE
Critical Security issue with IOMAD

### ISSUE THREAD

**Issue by amirtq** [iomad/iomad#1383]
Hi there
to reproduce the issue create two company, named A with hostname a.domain.com another named B with hostname b.domain.com
now, open b.company.com URL in browser, and login with company manager of company A
then from dashboard, go to courses IOMAD course settings, you will see all courses of company B while you logged in with company manager of company A
I believe  it should prevent any user of company A to login to IOMAD when the URL is host name of another company.

**Comment by rmeske** [comment]
I was just reviewing the current state of Iomad prior to installing and saw this which I agree is a critical security issue.

Which version of IOMAD are you running?

**Comment by amirtq** [comment]
it is the latest stable version 38

**Comment by turf212** [comment]
3.8 has been patched to fix this.  As we don't know what company the user is in until they log in they get redirected to the correct URL (either the users company URL or the default $CFG->wwwroot) login page.
