### ISSUE TITLE
Users can not edit their courses

### ISSUE THREAD

**Issue by justinhunt** [iomad/iomad#1384]
I want to create an IOMAD site where users are each given one or more of their own courses which they can edit. However I can not seem to give anyone access to do that. I know I am doing something wrong. But what?

I have a plain IOMAD_38_STABLE site.
As admin I add a company.
I create a user for the company, in the advanced list I see:

- user
- department training manager
- company manager
- company report only

I choose company manager. I create a course for the company and I login as the manager user.
But as that user,  I can not edit the course. And I can not create a new course either.

In Site admin -> user -> define roles (and from various references here), I know there is a "client course editor" role. But it does not appear available anywhere. In fact, none of the custom roles appear in any of the locations where I might assign it usually in Moodle. I can make them teacher but thats not correct is it?

How can I grant a user access to edit their own course?

**Comment by turf212** [comment]
you need to allow a capability for company managers to allow for this.  There are a couple of people asking the same question in the rasied questions/issues.
