### ISSUE TITLE
License expiry date warning email - when is being sent?

### ISSUE THREAD

**Issue by michalludynia** [iomad/iomad#1385]
Hi
As it is said in topic.
When License expiry date warning email is being sent? 
I need to know exact time period. Is it days, or at the moment of expiration?
Thanks

**Comment by michalludynia** [comment]
@turf212 can you help me or point a file where that action is triggered? Can't find it with github file search.

**Comment by turf212** [comment]
Task didn't exist till dca57e2510434d9c4f07221920cea2b5760e6ff8
