### ISSUE TITLE
Error in Manage Iomad course settings

### ISSUE THREAD

**Issue by williamwithin** [iomad/iomad#1387]
When I go to Dashboard - Manage Iomad course settings and change a setting in one of the courses, I get the error page which says:

`Exception - Class 'block_iomad_company_admin\event\company_course_updated' not found`

When I click "Continue" I get back to the Dashboard page

It looks like the 'block_iomad_company_admin\event\' namespace does not exist?

I have found a function with the same name here:

`./local/iomad_track/classes/observer.php:    public static function company_course_updated($event)`

**Comment by turf212** [comment]
Which version of Iomad is this?  The file was missed initially but was added back in #1324

commit 7f5073afbb194d022a5000e4d5fa6f4392328c26
Author: Derick Turner <derick@e-learndesign.co.uk>
Date:   Thu Apr 30 23:08:31 2020 +0100

    IOMAD: missed an event file from #1324

**Comment by turf212** [comment]
Just checked and this file was added to the 3.6/7/8 branches all on that date.  I'd suggest pulling the latest branch to your site.

**Comment by williamwithin** [comment]
Thanks. This error does not occur on the latest code.
