### ISSUE TITLE
Limit storage space per company

### ISSUE THREAD

**Issue by rijulsudhir** [iomad/iomad#1388]
There is already an option to limit active users per company. Just like that, is there any way to limit the total storage used by the company. Limit should be on a per company basis. If currently there is no way. Can you suggest any modification that can be done to iomad source code to enforce such a limit. Thank you.

**Comment by turf212** [comment]
There currently isn't a way of doing this.  I'm not even sure there is a way of achieving this.  Moodle stores the used data under either a course context or a user context in private files.  What is it you are trying to prevent here?  Companies from creating too many courses with too much data?

**Comment by rijulsudhir** [comment]
Yes, to prevent companies from creating too many courses with too much data(like many video files). Any idea how https://moodlecloud.com/app/en/ implemented this. I don't know if it includes courses. But they definitely limits Max file storage.

**Comment by turf212** [comment]
I actually don't but I would guess that this would be a user quota on the moodledata directory with a hard limit, which obvoiusly wouldn't work on a per tenant basis but would on a whole site.  This kind of approach can cause massive disruptions to the site if not set up properly as, for example, if the session information is kept on the filesystem and not in the database, no-one would be able to log in.

**Comment by rijulsudhir** [comment]
Thank you for the valuable guidance
