### ISSUE TITLE
Upload Courses to multiple companies using csv

### ISSUE THREAD

**Issue by anirudh74** [iomad/iomad#1392]

**Comment by turf212** [comment]
If you are asking if thta is a thing in Iomad, then no it's not.  If you are providing the same course to multiple companies then you want to have a single course which you share to the companies.  Courses can either be open shared (every company sees them) or closed shared (you have to add the course to a company).  One of the underlying precis is that you only have the number of courses you require to cut down on site administration.

**Comment by anirudh74** [comment]
Thank you, turf212
But my question here is that in moodle we have an option to upload courses using csv format, using this csv format we can upload courses (Unique Courses, not a shared one) to multiple categories at once.
So is there any such to do same thing in IOMAD?
or
Even I will very glad if there is any work around for this

**Comment by turf212** [comment]
The course categories don't matter much other than they are there are a space to put courses which have been created by a company manager. The point of Iomad is to have the same course shared across multiple companies to reduce the course management overhead.

Please note, you can still always use the Moodle tools (Iomad is Moodle afterall) but you would need to do something about registering the course to the company afterwards. (Iomad dashboard, select company, assign course to company, or create an entry in the mdl_company_courses table with the companyid and course id).

The current course upload tool could also definitely be re-purposed for this. As you would want to choose which company then we would need to have a column that has the company shortname to match on and then, if that exists in the row, assign the course to the company.  Unfortunately it would be a rewrite of that form and not something which you could capture an event for.
