### ISSUE TITLE
Users are able to login from any company url

### ISSUE THREAD

**Issue by rijulsudhir** [iomad/iomad#1397]
If i create user1 in Company A and user2 in Company B, then user1 is able to login in Company B's  Host Name. Logged in account is of Company A. How to restrict from logging in from other companies Host Name. This doesn't occur in demo.iomad.org.

This is how i set it up
iomad : http://iomad.mydomain.com (in config.php at $CFG->wwwroot)
company A host name: a.mydomain.com (during company creation)
company B host name: b.mydomain.com (during company creation)

DNS is set with wildcard *.mydomain.com as A record

Iomad files are in a apache server at /var/www/html/

Where did i go wrong? or did i miss anything?

**Comment by turf212** [comment]
There was a fix for this added to the 3.8 branch under #1383 4 days ago.  What version of Iomad are you using?

**Comment by rijulsudhir** [comment]
Thanks a lot, it worked. My version is IOMAD_38_STABLE. But was downloaded on june 15th.

**Comment by rijulsudhir** [comment]
Looks like there is still an issue. Now login fails for user1(user in Company A) in Company B's url. But after failure it get redirected to Company A's url.

**Comment by rijulsudhir** [comment]
@turf212 changing
`$companyurl = $_SERVER['REQUEST_SCHEME'] . "://" . $mycompanyrec->hostname;`
to
`$companyurl = $_SERVER['REQUEST_SCHEME'] . "://" . $currentcompany->hostname;`
in `/login/index.php` should fix it

**Comment by turf212** [comment]
Yes, this is designed behaviour.  If the user is valid and from another company then they are re-directed to the correct company URL so that they can log in.  If the company they are from does not have company URL then it directs them to the default wwwroot as defined in the config file.  Feel free to change the identified file on your site.

**Comment by rijulsudhir** [comment]
Thank you
