### ISSUE TITLE
Course custom fields not working for iomad course

### ISSUE THREAD

**Issue by nileshnpathade** [iomad/iomad#1398]
Hi 

Course custom fields not able to see in create course form.  

I have added custom course fields by Site Administration => Courses => Course custom fields

Then 

I trying to create course by IOMAD Dashboard this custom fields not display..

**Comment by turf212** [comment]
These fields were added in after the create course screens were first created (back in Moodle 2.0).  You should be able to get to them in the edit course settings page?

Would you consider these to be site level or would you expect them to be like the profile fields where they are configurable per company?  Where else would you expect these fields to appear?

**Comment by nileshnpathade** [comment]
Thanks for reply, 

But When company Manager going to create course ( I have given permission to him to create course).

then He can not see custom fields at course create form ( From IOMAD Dashboard => Courses tab => Create Courses link).

If course custom fields is required parameters then it make take issue.

It should not make site level features, You should make this features as it is Moodle provides. i. e. Create course form should provide custom fields block. where any role can create course by with custom fields.

is it makes scene ?

Please correct me if I am wrong.

Thanks again
