### ISSUE TITLE
 assign a course to two companies or more

### ISSUE THREAD

**Issue by davidramos010** [iomad/iomad#1399]
For a specific need I need to assign a course to two companies or more, is this possible? ,how to do it?

**Comment by nileshnpathade** [comment]
Hi Davidramos010,

If you want to share your course in multiple companies, then you can use

Manage Iomad course settings

Where you need to course as open sharing for all companies or If you want to selected company then you can use Close sharing option.

So, You can assign it in selected company for a course.

**Comment by davidramos010** [comment]
Great!!, thanks
