### ISSUE TITLE
Company list : pagination is not working in IOMAD 3.8.3

### ISSUE THREAD

**Issue by nileshnpathade** [iomad/iomad#1400]
When I am going to add more than 30-35 company its not display pagination and company list.

![err](https://user-images.githubusercontent.com/13468332/86367425-8ecc6700-bc99-11ea-8ec9-1022d9170384.png)

**Comment by turf212** [comment]
Can confirm.  Thanks for reporting.

**Comment by nileshnpathade** [comment]
Hi, 

Issue still is there..

![image](https://user-images.githubusercontent.com/13468332/87776478-746fbd00-c845-11ea-874b-9a7156c3cd7c.png)



When I have added more than 60+ this issue looks mee..

I am very worried about this.

Please look into this.

**Comment by nileshnpathade** [comment]
I have check code, and code having issue. order_companies_by_parent() function

My Case:

Compamy Structures : 

**> TOP company **
> A = Child of TOP company
>     A.a = Child of A Company
>     A.b
>     A.c
>     A.d
> B = Child of TOP company
>     B.a = Child of B Company
>     B.b
>     B.c
>     B.d
> C = Child of TOP company
>     C.a = Child of A Company
>     C.b
>     C.c
>     C.d

Assume that B.b company is listed at 30th Number So, On the First Page(0) B.b is last company
and Should B.c will First of 2nd Page. (31st Number in list).

And 

C.b company is listed at 60th Number So, On the First Page(2) C.b is last company
and Should C.c will First of 4th Page. 

**In this case Pagination and sorting of column not working............** 

Hope I can explain well.

Waiting for help. Please.
