### ISSUE TITLE
Facing issue while creating child company

### ISSUE THREAD

**Issue by nileshnpathade** [iomad/iomad#1402]
I don't know what is issue with this.

I am using IOMAD 3.8.3

Some time when I am creating child company then it showing same form.

and URL showing me 

http://localhost/iomad/blocks/iomad_company_admin/company_edit_form.php?returnurl&companyid=0&parentid=4&createnew=1

there is companyid = 0;

???

**Comment by turf212** [comment]
Are you using the Create new company page directly from the dashboard or are you clicking through from the manage companies page?   If you are going directly from the create company page and then selecting a parent company, then the page needs to reload (I'm open to ideas of fixing that UI) as it needs to pick up the available email templates and role templates which can be applied to that company or are available to be applied to that company.  Some of the options are also set to inherit.  So the page get's reloaded.  The company ID is 0 as it's not created yet and causes the URL.

Does the child company get created properly when you save it?

**Comment by nileshnpathade** [comment]
I am used 2nd option :  **clicking through from the manage companies page**

When I am trying to create 1st time it's reloading same page and child company not creating. a big issue here....

I need to click again to save.  then its works fine.  BUT issue is reloading form...


**SUGGESTION ONLY**
Yes, You should make user friendly UI for this form. it means Drop down should be take Up After Country fields. It will very useful to know where I am going to create company or who will parent of company

**Comment by turf212** [comment]
I agree.  The form is reloading because there is a number of fields which are populated when the parent company changes.  Specifically the role and email templates.  Moving the filed for parent company makes sense if you are always creating child companies but the majority of users are only creating simple companies so that is not important to them.  I'm open to something new which would work for this if you have any ideas?

**Comment by nileshnpathade** [comment]
Child companies creation has issue. need to solved it.

make some limitation for structures of company and management of company. Make as easy as we can do.

I think this is programming and database structures issue which we need to look into this.

**Comment by turf212** [comment]
Fixed in 28c40b001ef76226bd57c16e73963e8169c45c18
