### ISSUE TITLE
How to update multiple courses and users from another moodle

### ISSUE THREAD

**Issue by pedrolois** [iomad/iomad#1403]
I need  backup  courses (around 556) and users from another moodle into Iomad. How could be the easier way?

**Comment by turf212** [comment]
The quickest/easiest way is to clone the whole Moodle site and replace the Moodle code with the exact same version or higher Iomad code and run an upgrade against it.  This will then allow you to sort the users, courses etc into companies.

The broad idea of this would be
Create all of your companies
Identify which company each user goes into (something from the profile field info probably.  e.g. institution).
Add each user to the correct company/department (mdl_company_users is the swing table)
Add each course to the correct company. (mdl_company_courses is the swing table)
Populate the local_iomad_track and other reporting tables.  (pull info from mdl_course_completions and mdl_grade_grade for each user and populate the mdl_local_iomad_track table.)
Convert any mod_certficate certificates to mod_iomadcertificate (tables are a match just need to have the data copied over)
Recreate user certificates.
