### ISSUE TITLE
Recently accessed courses & Timeline block appears two times but second just shows loading

### ISSUE THREAD

**Issue by santoshndev** [iomad/iomad#1405]
I am using 3.8.3+
Whenever any user logins account.. Recently accessed courses & Timeline block appears two times but second just shows loading.. I have to delete these blocks manually.
![Screenshot from 2020-07-04 01-13-58](https://user-images.githubusercontent.com/25514423/86494687-d0413d00-bd93-11ea-9b30-a69f9c32ab74.png)

**Comment by nileshnpathade** [comment]
Hi Santosh,

Just try will remove this block from "Site administrator => Appearances => Default Dashboard page" and reset for all users.

Hope this will works.

**Comment by santoshndev** [comment]
I tried..its not working Nilesh

**Comment by turf212** [comment]
The other option is to disable this block in site administration -> plugins -> Blocks -> Manage blocks and close the eye next to that plugin.
