### ISSUE TITLE
How to stop redirection to iomad main domain on visiting any subdomain that is not a company

### ISSUE THREAD

**Issue by rijulsudhir** [iomad/iomad#1406]
When invalid company subdomains are visited, it gets redirected to main iomad domain. How to stop this redirection?

**Comment by turf212** [comment]
Is this on login? or just Moodle converting the URL to the main wwwroot when it's not matching a company URL?

**Comment by rijulsudhir** [comment]
Its the second, "Moodle converting the URL to the main wwwroot when it's not matching a company URL". Which code should i modify to change this behavior?

**Comment by turf212** [comment]
Unfortunately you can't.  Moodle is switching any unknown URLs to the wwwroot in the config file as it doesn't match any URL it knows about.
