### ISSUE TITLE
"The file imported does not match the company structure." error when I tried to Import Company structure .json file

### ISSUE THREAD

**Issue by likhith-ch** [iomad/iomad#1407]
I tried to import department structure. But when I used .json file it gave me error "The file imported does not match the school structure." can anyone tell me the how .json file structure should be.
Thank you

**Comment by turf212** [comment]
The attached file will create a set of departments under the company My Company (with the shortname mycompany) which looks like this:

My Company - Department AA - Department AA 1
                       |                           - Department AA 2
                       |                           - Department AA 3
                       - Department AB - Department AB 1
                       |                           - Department AB 2
                       - Department AC - Department AC 1

So 1 company department, 3 child departments (AA, AB and AC) each of which has 3, 2 and one child department respectively.

[mycompany.json.txt](https://github.com/iomad/iomad/files/4908703/mycompany.json.txt)

You need to change the file type to just .json as I can't upload that type of file here :)
