### ISSUE TITLE
Not able to assign course and role through Company dashboard->Users->Upload Users csv file

### ISSUE THREAD

**Issue by santoshndev** [iomad/iomad#1408]
I have been trying to upload users through Company Dashboard-->Users-->Upload Users , using csv file with column username, firstname, lastname, email, course1, role1 but whenever i upload the csv file it assigns student rule to all users.

So kindly guide me as i want to upload users and enroll them into course and assign them the role as well.

I am currently using 3.8.3+

**Comment by turf212** [comment]
The role is being defined by the dropdown in the upload CSV form and not coming from the file itself.  Once the users are created, you can use the standard Moodle CSV upload should you want to chose a different role for the users.

Please be aware that, depending on your site and course enrolment settings, managers will be given certain roles within courses too as part of being a manager.  You can also change the course groups a user is in within the groups menus in the Iomad dashboard (which ensures that the groups are separate between companies).
