### ISSUE TITLE
Is there any way to keep a clone of master course in IOMAD?

### ISSUE THREAD

**Issue by anirudh74** [iomad/iomad#1409]
We have a scenario where a master course will be a clone for multiple companies and if I update any  activity in that master then that should be also added to the clones.

This can be done in Moodle by updating the existing cources using upload courses in site administration.

**Comment by turf212** [comment]
Yes.  You share the master course to all of the companies which require it (either closed sharing where you can specify which companies get it or open sharing where it is available to all companies).  Every company that has access then sees the exact same course, so you only have to update the one course.

**Comment by anirudh74** [comment]
Thank You
