### ISSUE TITLE
Start and end date of course fields not display in course create form in IOMAD

### ISSUE THREAD

**Issue by nileshnpathade** [iomad/iomad#1410]
Hi 

I want to set start and end date of course fields while creating course by IOMAD Dashboard => Courses Tabs => Create course form.

Its only display course full name, short name, and enroll type, summary. I want to set Start and end date as well.

Because My company manager should not go to edit after course create.

Why this fields not in create course form?

**Comment by turf212** [comment]
Simply because the create course form was created in Moodle 2.0 and these fields were not part of Moodle then :) (and there has not been any request to add them in).

I'll get the form updated for these fields too.

**Comment by nileshnpathade** [comment]
Yes, please.

There should some setting/Configuration page so user can add this fields as per there requirements. Now I need course start and end date, Course Short name, Courses custom fields when company manager Or Course creator use IOMAD Dashboard to create course.

Is it makes sense ??

**Comment by turf212** [comment]
I've added the start/end date to the page.  The custom fields are available in the 3.7 + branches.
