### ISSUE TITLE
iomad_courses_form table not display

### ISSUE THREAD

**Issue by nileshnpathade** [iomad/iomad#1411]
This page not working

blocks/iomad_company_admin/iomad_courses_form.php?companyid=all

its showing same ID issue..

![image](https://user-images.githubusercontent.com/13468332/86626082-d0377c00-bfe3-11ea-8899-7be87819d19a.png)

![image](https://user-images.githubusercontent.com/13468332/86626199-feb55700-bfe3-11ea-9886-6e7ca3af15ed.png)

![image](https://user-images.githubusercontent.com/13468332/86626249-0ecd3680-bfe4-11ea-9fbd-79fd53a2a9e5.png)

**Comment by turf212** [comment]
The way the form works is that it will append the id in the iomad_courses table to each of the courses which are being displayed.  Have you added a load of courses to the site and not assigned them to any companies?  For any of this processing to work the course must belong to a company where where it can be shared to one, many or all other companies.
