### ISSUE TITLE
when does 3.9 release?

### ISSUE THREAD

**Issue by moossaab** [iomad/iomad#1412]
Thanks for your valuable product
I would like to ask about release date of 3.9 stable version

**Comment by turf212** [comment]
As soon as I can finish testing it.  Specific parts which need checked are around the course categories and listing functions (got changed in 3.9) and the addition for the H5P functionality for course cleardown (as this has moved more into core).  There is a bunch of automated testing I'd like to get implemented too.

We typically say 3 months after the Moodle release which gives us to 15th September.
