### ISSUE TITLE
 Could not Restrict Latest announcements to Company level

### ISSUE THREAD

**Issue by likhith-ch** [iomad/iomad#1413]
When a company manager post any message in 'Latest announcements' block it is getting displayed even to other company users.
May I know how can we restrict this

**Comment by turf212** [comment]
Correct.  Te latest announcement block is a sitewide block which goes to all users.  There are no groups on the front page so there is no filtering.

If you want to have some company announcements only then I would suggest setting up a common room type course for each of the companies which then means the company manager (or educator roles if you have split them) can post to a forum for all of the company users.   You can also tie this with the company course autoenrolment features which means that everyone added or created in that company is enrolled on that course automatically.
