### ISSUE TITLE
some code is displaying on Assign users to course Page

### ISSUE THREAD

**Issue by santoshndev** [iomad/iomad#1414]
I am trying to enroll users into a course using Assign Users to Course Page but there it shows some code like as follows:

Array
(
    [0] => -1
)

A

Kindly help to remove this code from the page.

**Comment by turf212** [comment]
Woops.  Thanks for reporting this.  I've removed that debug code.

**Comment by santoshndev** [comment]
Thank you.. it helps me a lot...
