### ISSUE TITLE
cannot install from git.

### ISSUE THREAD

**Issue by dallenk** [iomad/iomad#1415]
I've installed from the downloaded zip several times, and wanted to try the git source for easier updating.  I have never been able to make this work.  I followed the directions to the letter at least 5 times and only see this:

[Mon Jul 13 18:39:57.758736 2020] [php7:notice] [pid 22795] [client 75.155.xxx.xxx:57569] PHP Stack trace:
[Mon Jul 13 18:39:57.758750 2020] [php7:notice] [pid 22795] [client 75.155.xxx.xxx:57569] PHP   1. {main}() /var/www/vhosts/iomad.domain.com/iomad/index.php:0
[Mon Jul 13 18:39:57.758759 2020] [php7:notice] [pid 22795] [client 75.155.xxx.xxx:57569] PHP   2. require_once() /var/www/vhosts/iomad.domain.com/iomad/index.php:30
[Mon Jul 13 18:39:57.758767 2020] [php7:notice] [pid 22795] [client 75.155.xxx.xxx:57569] PHP   3. require_once() /var/www/vhosts/iomad.domain.com/iomad/config.php:851

is there something simple I have overlooked??

I downloaded the zip and i can have it running in 30 seconds now.

**Comment by turf212** [comment]
That looks like a permissions issue.  The index.php cannot read the config.php file which should live in the root of the webroot directory, /var/www/vhosts/iomad.domain.com/iomad in this case.  Check that the webserver has read access to that file.

**Comment by dallenk** [comment]
that was one of the first things I checked.

drwxr-xr-x  5 www-data www-data 4096 Jul 13 18:31 .
drwxr-xr-x 14 root     root     4096 Jul  8 23:10 ..
drwxr-xr-x 50 www-data www-data 4096 Jul 13 18:37 iomad
drwxr-xr-x  2 www-data www-data 4096 Jul  8 23:14 logs
drwxrwxrwx  2 www-data www-data 4096 Jul 13 18:29 moodledata

root@smoothbore:/var/www/vhosts/iomad.domain.com/iomad# ll config.php
-rw-r--r-- 1 www-data www-data 43886 Jul 13 18:37 config.php

even went as as far to chmod 777 config.php

**Comment by turf212** [comment]
As a work-around, if you download the zip file and also git checkout the branch to another directory you can move the .git directory from there to the directory you unzipped to and, as long as you did both these things at the same time using the same version, you should have git control over the downloaded zip.

**Comment by dallenk** [comment]
this appears to be resolved with the newest version.. not sure why it happened in the first place.
