### ISSUE TITLE
Self Enrol by License Permissions?

### ISSUE THREAD

**Issue by slapnik** [iomad/iomad#1418]
I'm trying to add a Self Enrol by License option to one of my courses.  Unfortunately I keep getting a permissions error of:

Sorry, but you do not currently have permissions to do that ([[iomadlicenseself:config]]).

I have scoured the permissions to allow this and can't seem to find the one that unlocks this.  I'm also using the Moodle Administrator account which normally has all options enabled.  Where is this permission and under what role should I edit?

**Comment by turf212** [comment]
I've checked the code for the string iomadlicenseself and I cannot see it anywhere.  I've tested this by adding a license enrolment method to a new course and it added without any issue.  Can you please confirm what version of Iomad you are using?

**Comment by slapnik** [comment]
Using Version 37. I was able to by-pass this message by edting /enrol/editinstance.php, commenting out line 47 which calls the require_capability() function.

I know that's a bad idea, but it at least got me to the next screen.  Unfortunately that screen has no options to speak of :(. It did at least add the Enrollment Option to my settings, but it still doesn't allow anyone to Enroll in the course with a license.

![image](https://user-images.githubusercontent.com/52262392/87806500-fb606d80-c824-11ea-8963-1435ac89f02b.png)

**Comment by turf212** [comment]
not an IOMAD plugin.  However - the license type "Blanket" will allow users to access licenses courses as though they were self enrolment by taking an available license slot themselves rather than being provided one by the company managers.
