### ISSUE TITLE
Special Character not displaying properly.

### ISSUE THREAD

**Issue by Annesha-maker** [iomad/iomad#1419]
Special Character not displaying properly.May be encoding issue.
If we Give Input as sed 's/\([^:]*\).*/\1/' /etc/passwd.
It display as  sed 's/[:]∗.*/\1/' /etc/passwd.
I am using 3.8.1+ version.

**Comment by turf212** [comment]
Is this text within a course/activity?  If so, Iomad is Moodle at this point.  It would be worth having a look through the Moodle forums (https://moodle.org/course/)  to see if there is any answers for this.  It could be encoding.  The preferred DB encoding is now utf8mb4/utf8mb4_unicode_ci to allow for the extended emojis.
