### ISSUE TITLE
Hi Course manager list pagination  not working. 

### ISSUE THREAD

**Issue by nileshnpathade** [iomad/iomad#1420]
Hi, 

Issue still is there..

![image](https://user-images.githubusercontent.com/13468332/87776478-746fbd00-c845-11ea-874b-9a7156c3cd7c.png)

When I have added more than 60+ this issue looks mee..

I am very worried about this.

Please look into this.

_Originally posted by @nileshnpathade in https://github.com/iomad/iomad/issues/1400#issuecomment-660022914_

**Comment by turf212** [comment]
Is this the view the company manager sees?  Can you please turn on full developer error display (Site administration -> debugging -> set the level to full developer and display messages and tell me if it has any error messages.

**Comment by turf212** [comment]
Sorry - Just noticed the text in the other issue which is now closed.  Copying here for convenience:

I have check code, and code having issue. order_companies_by_parent() function

My Case:

Compamy Structures :

**> TOP company **

A = Child of TOP company
A.a = Child of A Company
A.b
A.c
A.d
B = Child of TOP company
B.a = Child of B Company
B.b
B.c
B.d
C = Child of TOP company
C.a = Child of A Company
C.b
C.c
C.d

Assume that B.b company is listed at 30th Number So, On the First Page(0) B.b is last company
and Should B.c will First of 2nd Page. (31st Number in list).

And

C.b company is listed at 60th Number So, On the First Page(2) C.b is last company
and Should C.c will First of 4th Page.

In this case Pagination and sorting of column not working............

Hope I can explain well.

Waiting for help. Please.

**Comment by turf212** [comment]
The list of companies with children is built up differently than just a straight list and I'll need to check.  It's likely because the next page doesn't find the parent company, so the child companies are never found to be cycled through in the renderers.

**Comment by nileshnpathade** [comment]
Yes, Please let me know this is big issue for this list.

**Comment by nileshnpathade** [comment]
Hi Team,

As I can see same issue with same code too.

I am facing again pagination issue with newer version too. Unable to see all company when I use

Parent company A (L1)
=> A child company (L2)
=> L2 child company (L3)
=> L3 child company (L4)
=> L4 child company (L5)
=> L5 child company (L5)
=> L5 child company (L5)
=> L3 child company (L4)
=> L4 child company (L5)

This is structure I am using that time it's not working

**Comment by nileshnpathade** [comment]
> Sorry - Just noticed the text in the other issue which is now closed. Copying here for convenience:
> 
> I have check code, and code having issue. order_companies_by_parent() function
> 
> My Case:
> 
> Compamy Structures :
> 
> **> TOP company **
> 
> A = Child of TOP company
> A.a = Child of A Company
> A.b
> A.c
> A.d
> B = Child of TOP company
> B.a = Child of B Company
> B.b
> B.c
> B.d
> C = Child of TOP company
> C.a = Child of A Company
> C.b
> C.c
> C.d
> 
> Assume that B.b company is listed at 30th Number So, On the First Page(0) B.b is last company
> and Should B.c will First of 2nd Page. (31st Number in list).
> 
> And
> 
> C.b company is listed at 60th Number So, On the First Page(2) C.b is last company
> and Should C.c will First of 4th Page.
> 
> In this case Pagination and sorting of column not working............
> 
> Hope I can explain well.
> 
> Waiting for help. Please.

SAME ISSUE FACING AGAIN WITH NEW CODE.
