### ISSUE TITLE
how can I assign teacher to a course

### ISSUE THREAD

**Issue by moossaab** [iomad/iomad#1422]
As a company manager I can create a course but I can not add participants as a course creators, I can't find this option when I click enroll users from inside the course
and when I try to assign teacher role to manager from the main system he can enroll all system users not only company users
please help

**Comment by moossaab** [comment]
I think the whole problem in the database query when pressing the drop down list of users after adding new participants. It selects all users in the system when it should select only company users

**Comment by actXc** [comment]
This is not the intended use of iomad, but in some way you can configure it.

Important first step:
unselect the setting: 
Enrol managers as non students
 _iomad_autoenrol_managers_
(3.8.3)
  
then you will find options to add a role 
"Client Course Editor (role name: _companycourseeditor_ (very confusing, not consistent with company and client elsewhere) )

set the role e.g. in 
creating new users or 
blocks/iomad_company_admin/company_managers_form.php    "**Course educator**"

also a license type will be available after unselect _iomad_autoenrol_managers_
**Couse educator**

But the role assignment is not consistent and users created before changing the setting will react diffrent copmpared to users created after. And assigning this role gives diffrent results depending where you try. E.G. during create user : the option does diffrent compared to the comany_manager_form in my experiance. (3.8.3)

The idea behind seems to be that editing a course can be sold as license (good!) 
Needs a lot of testing.

But all this does not help, if you do not change the capabilities of   _companycourseeditor_
Add any capability to this role you need for the project you are working on. 
double check if this will allow to see data of other companies.

Please share your experiance.

**Comment by moossaab** [comment]
Thanks for your help
I know where to (unselect Enrol managers as non students) from system administrsation -> plugin -> local -> iomad setting
 but please provide more explanation on this
(then you will find options to add a role
"Client Course Editor (role name: companycourseeditor (very confusing, not consistent with company and client elsewhere) )
set the role e.g. in
creating new users or
blocks/iomad_company_admin/company_managers_form.php "Course educator"
also a license type will be available after unselect iomad_autoenrol_managers
Couse educator)

I will appreciate if you explain by steps
how can I add the role? I found it in system administration -> define roles. But how can I can I make it appears in my course?
And please more explanation about the next step (set the role eg. creating new user)  where to find it?

**Comment by actXc** [comment]
After unselect "Enrol managers as non students"
create a new user and take a look at the new options on the 
blocks/iomad_company_admin/company_user_create_form.php
in Advanced, you will find:
**Assign as educator**

**Comment by moossaab** [comment]
Thank you very much I could see this new option for the first time because of your assistance, and I have assign course educator license  too
now I miss one setting of your instruction:
(
 then you will find options to add a role
"Client Course Editor (role name: companycourseeditor (very confusing, not consistent with company and client elsewhere) ) "
)
sorry for asking more questions but I need more explanation on how to do it

**Comment by actXc** [comment]
may be step 2 is to set the necessary capabilities.

 if you do not change the capabilities of companycourseeditor, the role can not edit courses like a trainer. 
Compare the roles trainer and companycourseeditor with the moodle function 
User -> Permissions  -> Capability Overview (admin/tool/capability/index.php)

Add any capability to the companycourseeditor  role you need for the project you are working on.
double check if this will allow to see data of other companies.
