### ISSUE TITLE
How to create new  custom role in IOMAD like Company Manager 

### ISSUE THREAD

**Issue by nileshnpathade** [iomad/iomad#1424]
Hi All, 

Can this possible to create new custom role like company Manager in iomad ? If Yes, Explain how should I do this?

**Comment by nileshnpathade** [comment]
Any reply ??

**Comment by amirtq** [comment]
Hi there
would you please explain more about your scenario?
what are you expecting from the new mentioned role?
it is absolutely possible but it depends on scenario because each of them may have different workaround

**Comment by nileshnpathade** [comment]
I want new custom role which can have access IOMAD Dashboard like Company Manager having.

I have added new custom role by Site administration => Users => Define role =>Add new role
And selecting role archetype as Company Manager.

But in the screen of IOMAD Dashboard I can not see my custom role in drop down of Assign department users manager.

Is it possible to create custom role which having similar access like Company Manager having.???

**Comment by nileshnpathade** [comment]
Any reply ???

**Comment by nileshnpathade** [comment]
Any Reply ???

**Comment by turf212** [comment]
It's not.
