### ISSUE TITLE
change a user role in IOMAD

### ISSUE THREAD

**Issue by ken4ward** [iomad/iomad#1429]
I created a user in IOMAD and assigned it a User role, now, I intend upgrading the role to Company manager role, when I tried editing the user, I am taken to the Moodle user editing interface, not of IOMAD, so I could not upgrade the user. Is there anything I'm missing? Please, help out.

**Comment by turf212** [comment]
IOMAD dashboard - Edit users -> turn editing on - use the drop down to change their role.  Or use the Assign department users/managers page.
