### ISSUE TITLE
Direction and Some instruction on wordpress/woocommerce/iomad plugin use

### ISSUE THREAD

**Issue by Melly78** [iomad/iomad#1432]
Hi there,

I have purchased from you guys the woocommerce / iomad plugin. Have had extensive liason with Derick who has also provided us with significant training on iomad platform as we develop and release to market. 
i can't seem to find any instructions on how woocommerce and iomad communicate, what information comes over from iomad into woocommerce and where information is displayed in woocommerce, i have sent derick a few emails on providing a 1 hour training session so i can further understand. I haven't heard from him? 
Is anyone able to assist us with this instruction and guidance, so i get it right?

**Comment by Melly78** [comment]
Hi All 
Just following up on the above request, is there anyway i can organise this URGENTLY! i am wanting to send our site live, but am struggling on how to do this?

**Comment by Melly78** [comment]
Is anyone able to assist with this please?

**Comment by mrmuehle** [comment]
We have developed  for Woo <-> Moodle/iomad , may be we can help with our software, but you should first ask the people you paid for this.

**Comment by Melly78** [comment]
as per the above comments and initial call.... i have sent numerous emails and am getting nothing in response. As this post was sent as per above, i had emailed 3 times before lodging on here.

**Comment by Melly78** [comment]
Oh Derick is from iomad. we have had numerous training sessions with him on using iomad as we were transitioning from original moodle.

**Comment by turf212** [comment]
Hi Mel!  Let me check tickets.  I think there was something on contracts outstanding which I'd asked you about previously.

**Comment by turf212** [comment]
closing this to take it off-line.
