### ISSUE TITLE
How can a Teacher be enrolled by a Company Manager ?

### ISSUE THREAD

**Issue by GustavBouwer** [iomad/iomad#1434]
Currently it appears that a Teacher can only be enrolled in a course by the system administrator. This becomes a responsibility of the system administrator, regardless of the Company that a teacher would be assigned to. 

How would a Company Manager be able to enroll a teachers to a course, once Users are assigned to a Company? This allows the Company Manager to control the Teacher enrolments for each specific company only. 

I'd appreciate your assistance to configure the role correctly if it is possible.

**Comment by anirudh74** [comment]
You can specify that in the "Define roles" in Site Administration
Site Administration --> Users --> Define Roles --> Allow role assignments --> Check "Teacher" role for the Role you want to define in the left side

**Comment by turf212** [comment]
We try not to use teacher roles as they have abilities like enrol participants - which means they can see everyone in the site.

If the company manager has created the course (or the company has been given control of the course - which is brand new functionality) and you have turned off assign managers as non students in local IOMAD settings, then the company manager can designate someone as an educator which get editing teacher rights without the ability to add participants. (client course editor role)
