### ISSUE TITLE
Unable to assign user as Educator when creating their account.

### ISSUE THREAD

**Issue by nielsharma** [iomad/iomad#1435]
In Iomad 3.7.4 (20200113) you had the option to assign as Educator when creating a user account via the Iomad dashboard. The functionality is missing in Iomad 3.7.7 (20200713). Unless there is a new way to assign the user as an Educator?

Iomad 3.7.4 (20200113):

![1](https://user-images.githubusercontent.com/47655776/88762967-965a2f80-d1b5-11ea-8b52-8dbca289b451.PNG)

Iomad 3.7.4 (20200113):

![2](https://user-images.githubusercontent.com/47655776/88762920-788cca80-d1b5-11ea-9e04-cda7576b945b.PNG)

**Comment by turf212** [comment]
This is definitely showing on Iomad 3.7.7 for me.  The option disappears if you change the setting in site admin -> plugins -> local plugins -> iomad settings for Enrol managers as non students

![image](https://user-images.githubusercontent.com/1685229/92532631-958ed180-f228-11ea-9699-c1db502f1a16.png)
