### ISSUE TITLE
Maximum Active Users not enforced on Email-based Self Registration

### ISSUE THREAD

**Issue by slapnik** [iomad/iomad#1437]
Maximum Active Users restricts a Manager's ability to create more accounts after the Max Users limit is reached, but this is not enforced on the user registration form.

I would expect that if the limit has been reached that the signup form would simply display a message saying the Company has reached it's limit, and to contact a supervisor for more info.

**Comment by turf212** [comment]
Good point.  I'll add a check in the signup page.

**Comment by slapnik** [comment]
I added your change to signup.php and tested. Your change works perfectly on my installation!

However. the error message does not display, and instead I get the following. I also tested a bad company ID and found that the appropriate 'unknown_company' error message also does not display.  It seems none of these messages are displaying despite the fact they do exist in the language pack.  What could be causing this?

![image](https://user-images.githubusercontent.com/52262392/92599441-42dd0600-f278-11ea-947e-f364128a2987.png)

**Comment by slapnik** [comment]
Update: If I modify the string in the language pack the text will display but it's in an odd format.  Is this the expected format for this message?

![image](https://user-images.githubusercontent.com/52262392/92600908-2772fa80-f27a-11ea-93f9-7d4b8ff0aa1a.png)

**Comment by turf212** [comment]
The string was added in but if you haven't refreshed the Moodle language cache it wont display yet.  Typically when the site is upgraded it refreshed the cache, but in this case it was simply added without a version bump.

**Comment by slapnik** [comment]
I cleared my cache manually and then added these strings to local_iomad_signup, which must be why they now appear.  Would you happen to know where I can change the standard Moodle error format?

**Comment by slapnik** [comment]
Hey no worries on that last question. I figured out the error formatting.
