### ISSUE TITLE
Frontpage not available

### ISSUE THREAD

**Issue by FahadKhanChughtai** [iomad/iomad#1439]
I have installed iomad (latest) and setup a company. 
I am facing 2 issues:
1) Whenever I open my iomad site, it is relocated to the login page instead of front page. How can I access the front page? 
2) The company has a Webserver hostname alloted to it. When I open that link (Webserver hostname) it opens its login page instead of its front page. Can I setup its front page? Also in address bar it show link to iomad site not that Webserver hostname link. 
How to make it show the Webserver hostname link?

**Comment by turf212** [comment]
There is a setting, which you may have turned on, under site administration -> security -> site security settings to force users to log in.  This redirects everyone to the login page when they hit the site.

When a company has a webserver hostname it will still follow this directive.

Using a company hostname in the URL was introduced in Iomad 3.6/7/8 from March of this year.  Please ensure you are patched to a suitable version
