### ISSUE TITLE
Course category inside a company

### ISSUE THREAD

**Issue by rijulsudhir** [iomad/iomad#1443]
Does iomad support course category? So that i can assign a user/deparment to a course category. (instead of  assigning users for individual courses)

**Comment by turf212** [comment]
You can still use category enrolment with Iomad but there will be nothing to automatically segregate users in shared courses to their own company groups (which the Iomad dashboard and license functions will sort out), so you would need to be careful as to what the users can see inside of the courses.

If this is to save on effort, then the company manager can be responsible for enrolling their users and the upload users via CSV withing the Iomad dashboard can handle course assignation and will properly manage the course groups where required.
