### ISSUE TITLE
I am new to IOMAD. I do have experience. anybody please confirm is it possible to create a separate home page for the companies

### ISSUE THREAD

**Issue by dhascruz** [iomad/iomad#1444]

**Comment by turf212** [comment]
You can have some custom content depending on the default dashboard using conditional access tied to a user's institution (you need to ensure syncing the company to institution is on under site administration -> plugins -> local plugins -> iomad settings).

There is also the Iomad Company HTML block which allows for different companies to see the content within it.  Other than that, there isn't much per company custom content on the dashboard.

**Comment by turf212** [comment]
The Company availability restriction can also be used for things like this too.
