### ISSUE TITLE
API Creation for assigning company manager role.

### ISSUE THREAD

**Issue by nileshnpathade** [iomad/iomad#1445]
Hi Support team,

I need help, I would like to develop API for assigning user as Company Manager role. Is there available API for this ??
Or Can you please explain me database structures to do this.

Please help me.

Thanks and Regards,
Nilesh P

**Comment by nileshnpathade** [comment]
I find out API 

block_iomad_company_admin_assign_users 

but this is not work for me to assign user to company as Company Manger. ???

Please help me. Waiting for reply !

**Comment by turf212** [comment]
This API call is the one you should be using.  You can pass a manager type as part of the payload.  The values are:
0 - Normal User
1 - Company Manager
2 - Department manager

What version of Iomad are you using?

**Comment by nileshnpathade** [comment]
I am using IOMAD 3.8+
I want to create new role like company manager and want to assign user for this new role.

https://github.com/iomad/iomad/issues/1424
