### ISSUE TITLE
Assign (block_iomad_company_admin_assign_users) API having issue

### ISSUE THREAD

**Issue by nileshnpathade** [iomad/iomad#1447]
Hi 

I am trying use IOMAD API 

wsfunction : **block_iomad_company_admin_assign_users**
Assigning company Manager user 
After login with same user which assign as company users it showing on dashboard page. please check in screen shot.

![image](https://user-images.githubusercontent.com/13468332/91440275-fc58d600-e88b-11ea-894d-1ef03fd324bf.png)

checked code 

\iomad\blocks\iomad_approve_access\lib.php

Line no 49 ( near by)

 // What type of manager am I?
        if ($manageruser = $DB->get_record('company_users', array('userid' => $USER->id))) {
            if ($manageruser->managertype == 2) {
                $approvaltype = 'manager';
            } else if ($manageruser->managertype == 1) {
                $approvaltype = 'company';
            } else {
                return false;
            }
        }

there is get_record function having issue when I have assign parent company manager and that case there multiple records with same userid in company_users table.
Please check and revert me.

**Comment by turf212** [comment]
I'm going to assume that the user is a user in one company and a manager in the other?  If so, that's not a supported mode of operation as the company manager role is assigned at site level to the user so they would get elevated access to any other company they were assigned to.  I.e. not just user level access.

I can tighten up that get_record call in any case to the companyid being used which should help but wont fix the issue if the data is wrong. :)
