### ISSUE TITLE
Custom Field Filters not working properly

### ISSUE THREAD

**Issue by santoshndev** [iomad/iomad#1450]
I am trying to use custom profile fields for filtering the user's list. But the filters not showing correct result.
I am using IOMAD 3.5

**Comment by turf212** [comment]
I would upgrade to a newer version of Iomad.  There has been a lot of work done since 3.5 which is available on 3.6/7/8.  Of these I would suggest going to 3.8 as it is still currently supported for Moodle security patches with a eye to upgrading to 3.9 when it drops.
