### ISSUE TITLE
Iomad Cron error

### ISSUE THREAD

**Issue by tbeachy** [iomad/iomad#1451]
I just cloned the most recent version of IOMAD_38_STABLE and upgraded my db.  
I am now getting this error in cron:

Execute scheduled task: Iomad Cron (local_iomad\task\cron_task)
Copying company shortnames to user institution fields

Copying company department name to user department fields

suspending any companies which need it
Terminating any companies which need it
Clear users from courses where the license has expired and the option is chosen
... used 7 dbqueries
... used 0.020184993743896 seconds
Scheduled task failed: Iomad Cron (local_iomad\task\cron_task),Error reading from database (Unknown column 'cl.clearonexpire' in 'where clause'
SELECT clu.* FROM mdl_companylicense_users clu
                                                  JOIN mdl_companylicense cl on (clu.licenseid = cl.id)
                                                  WHERE cl.clearonexpire = 1
                                                  AND cl.cutoffdate < ?
                                                  AND clu.timecompleted IS NULL
[array (
  0 => 1599532948,
)])
Debug info:
Unknown column 'cl.clearonexpire' in 'where clause'
SELECT clu.* FROM mdl_companylicense_users clu
                                                  JOIN mdl_companylicense cl on (clu.licenseid = cl.id)
                                                  WHERE cl.clearonexpire = 1
                                                  AND cl.cutoffdate < ?
                                                  AND clu.timecompleted IS NULL
[array (
  0 => 1599532948,
)]
Backtrace:
* line 1247 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()
* line 100 of /local/iomad/classes/task/cron_task.php: call to mysqli_native_moodle_database->get_records_sql()
* line 157 of /admin/tool/task/cli/schedule_task.php: call to local_iomad\task\cron_task->execute()

**Comment by tbeachy** [comment]
I added the column to mdl_companylicense as TINYINT and it runs now, but it be missing from the db install.

**Comment by turf212** [comment]
Thanks for reporting this.  The updated files didn't make it onto the 3.8 branch (for some reason).  I've updated the code and fixed for 3.6/7/8
