### ISSUE TITLE
Display issues with Multilang filter

### ISSUE THREAD

**Issue by slapnik** [iomad/iomad#1453]
I'm using the Multilang filter for the title of a course and it works great in most places on the site.

However, I noticed a few issues with Emails and Reports.

If I include the {Course_FullName} variable in an email template, BOTH English and Spanish items display in the email message. Also, if this is used in the Email Subject all of the HTML tags are displayed as well.

In Reports, if you select the Show All Users option both titles are again displayed. This also occurs if you Download a report.

How can I correct this?

`<span lang="en_us" class="multilang">English Text</span><span lang="es" class="multilang">Spanish Text</span>`

**Comment by turf212** [comment]
Ah, thanks for reporting.  A couple of the reports were missing a format_string() call on the course name.

Good point about the email templates.  I'll pass them through format_string before saving/sending.

**Comment by slapnik** [comment]
Report looks good now.

As for Email templates, you have fixed the display of the filtered data but now all of my HTML tags have been stripped out of my formatted messages, leaving me a long paragraph of un-formatted text. How do we compensate for this?

**Comment by slapnik** [comment]
One more item for the Course Completion email.  The filename of the PDF completion certificate sent to the user needs to be filtered as well.  See what was sent to me during testing:

![image](https://user-images.githubusercontent.com/52262392/93113671-7ad4b680-f687-11ea-962f-370f500119f0.png)

**Comment by turf212** [comment]
I've rolled back the original change and provided an alternative.  

What PDF name does it record the certificate under in mdl_local_iomad_track_certs ??  That's the filename it should be using.

**Comment by slapnik** [comment]
It's using the full un-filtered Course title which is:

![image](https://user-images.githubusercontent.com/52262392/93132954-78348a00-f6a4-11ea-8191-ab96c5c1a471.png)

**Comment by slapnik** [comment]
Excuse me, not Course Title, but the title of the Completion Certificate activity, which I am also translating.

**Comment by turf212** [comment]
Sorry, I wasn't being clear.  The name for the file which is being saved (and then added to the email) is stored in the mdl_local_iomad_track_certs table. This is populated when the user course completed event is fired.  From what you are saying, I think if you were to download the certificate file from the reports it would also be the full/non lang filtered filename.  Could you please confirm as it decides where the filtering needs to be done :)

**Comment by slapnik** [comment]
No worries.  Here is what is in that table for that certificate:

![image](https://user-images.githubusercontent.com/52262392/93211407-3270d380-f72f-11ea-806f-6818ba1a74f5.png)

**Comment by turf212** [comment]
OK.  So the issue is that the filename for the certificate is not being passed through the language filter as it's being saved as the whole thing.  I'll sort this in the local_iomad_track event consumer.

**Comment by slapnik** [comment]
Were you able to resolve this? I didn't see a commit yet.
