### ISSUE TITLE
In page Manage company groups I am not able to see all the courses in this company. 

### ISSUE THREAD

**Issue by Annesha-maker** [iomad/iomad#1454]
In Page Manage company groups I am not able to see all the courses in this company.
Iomad 3.8.2+.
Is this bug or I need to provide some extra roles to my company manager.

![Not visible](https://user-images.githubusercontent.com/55189363/92626107-1d3b1580-f2e7-11ea-89b1-411f84468d9f.png)

**Comment by turf212** [comment]
It doesn't bring back courses which do not have groups enabled (as the feature wouldn't work).  Is that what you are seeing?
