### ISSUE TITLE
IOMAD Completion Report grade

### ISSUE THREAD

**Issue by fesaner** [iomad/iomad#1455]
The IOMAD Completion Report shows a course grade as a percentage, when the number reported is actually the course raw score. This is confusing and misleading. I believe the IOMAD report pulls the 'finalgrade' value from the mdl_grade_grades and/or mdl_grade_items tables. The value of 'finalgrade' is a raw score. It equals 'rawgrade' unless the grade item has been overridden, but even if overridden it is still a raw score. The Grade column in the IOMAD Completion Report should be calculated as finalgrade/rawgrademax*100 to get the percentage grade. It makes sense to keep the grade as a percentage in this report because the rawgrademax value is not given. Just reporting a raw grade does not make sense without knowing rawgrademax. The value reported in the IOMAD Completion Report does not seem to be affected by the Moodle grade book aggregation settings.

**Comment by turf212** [comment]
The grade is being saved before then in the mdl_local_iomad_track table.  I'l change the code to work out the percentage as suggested but this will be for future saved grades.
