### ISSUE TITLE
IOMAD API for get enrolled users list of course and company wise..? 

### ISSUE THREAD

**Issue by nileshnpathade** [iomad/iomad#1459]
IOMAD API for get enrolled users list of course and company wise..? 

Is there such API ??

**Comment by turf212** [comment]
All of the Iomad API calls are in blocks/iomad_company_admin/externallib.php.  There isn't one specifically for this but you can use get_companies() and get_department_users to get a list of all of the users within the company.  The Moodle APIs will tell you what courses a user is enrolled onto (core_enrol_get_users_courses).
