### ISSUE TITLE
User deleted from mdl_user_enrolments before access period ends

### ISSUE THREAD

**Issue by enrarelloem** [iomad/iomad#1460]
Scenario:
Users are enrolled by license to a course:
  License type : Standard
  Program of courses : no
  Instant access : Yes
  License startdate 1.1.2020
  License expires after : 1.4.2020
  Course cut off date : NOT enabled
  **License is valid for (days) : 30**

Expected behaviour:
  User who logs on for the first time 1 Feb should be able to access the course until beginning of March.

Actual behaviour:
  timeend in table mdl_user_enrolment is set to 1 Jan + 30 days and user is kicked out of the list of participants in the course end of Jan and cannot access the course. The entry in the table is deleted. Strangely: The course was originally built on Moodle with the plugin Completion Progress. In this, the participant is still listed...

Workround:
 Creating a new entry in the table and fiddling with the time stamp in mdl_user_enrolments "timeend" brings back the user to the list of participants. Same applies to users who are kicked out in the middle of the course. They are back as if nothing has happened.

**Comment by turf212** [comment]
Instant access licenses enrol the user onto the course immediately that they are given the license.  So, if you gave the user the license on the 1st of January, the enrolment to the course would start from there.  Not when the user first logs into the system.  If you want the user to have control of when they start the course then don't use instant access license type and the user has control of when they start the course (like a self enrolment type) giving them the full 30 days to access it.

**Comment by enrarelloem** [comment]
Hello Derick
Thanks for the swift reply!

Could this behaviour be clarified in the help text? E.g.:

License is valid for (days) 
This is how long a user can access the course for after they start it. -->
This is how long a user can access the course for after they start it or after they are enrolled via "instant access" in their license.

But anyway: When I don't use instant access, the users have to find their way around the system to get into the right course (assuming they start with the mail for access first, ignoring the one with the direct link to the course...).

That might be ok, when users are acquainted with the system or will need to get acquainted with the system anyway. However, if you typically just sell one course per user, it is another hurdle into the course.
