### ISSUE TITLE
System-level role assignment for Iomad Create Course gives too much access

### ISSUE THREAD

**Issue by AdvChaAP** [iomad/iomad#1462]
We are using the Client Course Editor role (Iomad for Moodle 3.6.5) for clients to administer their own courses, including creating courses. The permissions we have enabled to achieve this seem to give excessive permissions to Iomad/other companies' data.

In order to allow a Client Course Editor to create a course we have had to assign users the Client Course Editor role at System level.

(If we do not assign the role at System level - e.g. if we assign at Company category level only - then users cannot access the Iomad Create Course page to create a new course: **/blocks/iomad_company_admin/company_course_create_form.php**)

However when assigning this role at System level, users can also access information about other companies e.g. by loading the "Iomad Course Settings" page: **/blocks/iomad_company_admin/iomad_courses_form.php** (We don't given them a navigation link to this page but...)

The page is "read-only" but offers a (functioning) company selector - and users can view and delete courses outside of their own company - even though the role does not have access to view all companies etc:

**Block: Iomad Company / User Admin**
_View list of companies
block/iomad_company_admin:company_view_

_View all companies
block/iomad_company_admin:company_view_all_

The page is still visible even if we disable the following permission:

**Block: Iomad Company / User Admin**
_Mage Iomad course settings
block/iomad_company_admin:managecourses_

Is the view-other-companies capability on Iomad Course Settings intentional or should the above settings be making this page restricted to own-company-only?

Should we be able to give clients access to Iomad Create Course without making them Client Course Editors at System level?

**Comment by turf212** [comment]
What you are trying to do will break the system as those users will have editing access within all courses on the site.  If you instead allow the company manager the capability block/iomad_company_admin:createcourse any course which they create themselves will provide the company managers (or educators if you have chosen that option in local iomad_settings plugin) the client course editor role automatically.

**Comment by AdvChaAP** [comment]
Thanks Derick, I'll take another look using Company Manager as suggested.
