### ISSUE TITLE
The user's password information will be empty

### ISSUE THREAD

**Issue by syusanjun** [iomad/iomad#1463]
I updated the user information using Upload Users on the Iomad dashboard.
I selected No changes for the existing user password and uploaded it.
The user's password information will be empty and you will not be able to log in.

IOMAD3.8.4　IOMAD3.8.5

**Comment by turf212** [comment]
To confirm:
You used a CSV which had an empty password column and a list of existing users.
You uploaded the CSV and selected update existing users only and over write from files and no changes for existing user passwords.
Upload ignored that option and all of the existing users passwords were set to ''

**Comment by syusanjun** [comment]
I made a source fix and solved the problem.
/blocks/iomad_company_admin/uploaduser.php

                    $temppasswordhandler = '';
                    foreach ($allowed as $column) {
                        //$temppasswordhandler = '';
                        if ($column == 'username') {
                            continue;
                        }
