### ISSUE TITLE
missing icons in child companies

### ISSUE THREAD

**Issue by okellog** [iomad/iomad#1466]
I am having problems with companies. They don't display Icon properly
and sometimes the file pickers too disappear. 
Anybody with a solution. For example in Adaptable theme, fa-fa icons appear as small boxes. 

![fa-fa icons](https://user-images.githubusercontent.com/48151244/93794800-dc24f880-fc38-11ea-95f7-1ca7f3d9a013.PNG)

**Comment by turf212** [comment]
Is this just in child companies or is it when you are using the site under Adaptable as a whole?

**Comment by turf212** [comment]
(should have said I've checked with the site and it looks OK but in case i'm missing a step).

**Comment by okellog** [comment]
I had to purge cache and all got back. Thank you for the response. This is common with Adaptable especially with child companies. Otherwise the main site is not affected.
