### ISSUE TITLE
How to remove "Users can enroll themselves onto course" from course create form.

### ISSUE THREAD

**Issue by nileshnpathade** [iomad/iomad#1469]
![image](https://user-images.githubusercontent.com/13468332/94263887-6334e200-ff53-11ea-84fb-012793b7369c.png)

I am unable to remove this option from setting or configuration of permission. please help me.
How to remove "Users can enroll themselves onto course". I only want to kept 2nd option "............ by manager"

Please let me know setting or configuration of permission. 

Thank you in advance

**Comment by turf212** [comment]
There is no option to remove this although it also doesn't check to see if the self enrolment plugin is enabled so It could check that first.

**Comment by turf212** [comment]
Added a check to see if self enrolment is enabled and, if not, don't show it as an option in the drop down.

**Comment by nileshnpathade** [comment]
Have you update this request in IOMAD 3.8 ??

**Comment by turf212** [comment]
3.7 and 3.8, yes.
