### ISSUE TITLE
How to make a configuration for each company?

### ISSUE THREAD

**Issue by bavdalimbaev** [iomad/iomad#1472]
Hello, help please. who know?

i created 3 subdomains    A.example.com   |    B.example.com   |    C.example.com
How can I make a configuration {config.php} for each company?
i must all files {moodle/iomad} copy to each subdomain? or How?

**Comment by amirtq** [comment]
you dont need to do any change on you config.php
its all about the web server host files, the easiest way is to add a wildcard on web server to accept traffic on *.exmaple.com and use Moodle root dirrectory as document folder. the rest will be handled by IOMAD

**Comment by bavdalimbaev** [comment]
Thank you for answer. 

example. i create 3 company a, b, c and official we.
example.com   has moodle files.
after i make web server  A.example.com | B.example.com and C.example.com  on moodle root.
how iomad/moodle understand what user signup on company B on page B.example.com?

**Comment by bavdalimbaev** [comment]
in my local server. i create 3 company and 3 web server.  {**localhost** - it is official |  A.localhost | B.localhost | C.localhost in total i have 4 webserver). }
but when i signup in **localhost**. i follow to a _company B_.
when i signup in **B.localhost**.  i follow to a _company A._  

why? how i can change this problem?

**Comment by amirtq** [comment]
we are not using self registration so I have no experience for this part and @turf212 should come to help
by the way, I think it has to be handled by e-mail domain names which is configurable on company edit page under advanced settings.

**Comment by amirtq** [comment]
however, you dont need to have multiple host files for *.domain.com on a single server, its possible to use *.domain.com in Apache virtual host file

**Comment by bavdalimbaev** [comment]
thank you very much @amirtq .
i added domain in under advanced setting and all work. thank you

**Comment by turf212** [comment]
To complete the answer about self signup/login:

When you are using the webserver and company definitions for different wwwroot values, the user is immediately placed into that companies "world" at point of access.  So the login page and the signup page will be themed as though they are a logged in member of that company.  Using the self signup pages will also then assign that user to the company being identified by the URL in question.  To them it just seems like they are accessing theirs company specific Iomad site.
