### ISSUE TITLE
Assign Student Parent with company manager panel

### ISSUE THREAD

**Issue by mohgh** [iomad/iomad#1473]
As stated in [moodle documentation](https://docs.moodle.org/39/en/Parent_role) we can create a parent role and assign a parent to a student. To do this a client administrator will go to  Site administration ► Users ► Accounts ► Browse list of users, click on student's name and go to preferences and do the assigning via "Assign roles relative to this user" section. As company managers do not have access to the Site administrator section, how they can perform this action for their companies students? Are there any permissions to be set to the company manager role to provide access to that section? Thanks in advance.

**Comment by bavdalimbaev** [comment]
maybe, for manager role on iomad/moodle. need to paste role manager moodle on admin settings.
{
  iomad/moodle company
       user has role manager from iomad
           and
      this user has role student on moodle.  you must give for this user role manager) 
}

) sorry for my English

**Comment by turf212** [comment]
The roles which can be assigned by the Iomad dashboard are set in code.  These are also, for the most part, assigned at system level (company managers and reporter roles) or computed within the code (client course access, client course editor).  Parent roles would be assigned at student (user) level which makes this outside of the current functionality.  It would be possible to add something to assign a role to a user in a company (would need filtered to then show only potential users within the company) but this wouldn't be that efficient as you would have to go through each user in turn.

How would you like to see this work?

**Comment by mohgh** [comment]
I think for the first step it would be ok if we have an option for "Assign roles relative to this user" in company users page for each user. The next steps would be the same as the system context functionality but as you said the list of relative users should be filtered based on the user's company.

**Comment by TheArkaTek** [comment]
Did anyone find or create a solution to this? This is something my company would also benefit from.

**Comment by SolutionsDEV** [comment]
@turf212 
> The roles which can be assigned by the Iomad dashboard are set in code. These are also, for the most part, assigned at system level (company managers and reporter roles) or computed within the code (client course access, client course editor). Parent roles would be assigned at student (user) level which makes this outside of the current functionality. It would be possible to add something to assign a role to a user in a company (would need filtered to then show only potential users within the company) but this wouldn't be that efficient as you would have to go through each user in turn.
> 
> How would you like to see this work?

I strongly recommend adding this feature as it would be a main help in managing schools wherever they are used.

Thanks,
