### ISSUE TITLE
New install fails

### ISSUE THREAD

**Issue by alexmorrisnz** [iomad/iomad#1474]
`local/report_user_license_allocations/db/install.php` causes install to fail because it tries to query the database before all the tables have been created.  
There should probably be a check in there for if the site is new, or to move it into the upgrade script.

**Comment by turf212** [comment]
Which version of Iomad is this? 3.9?  I can see there is code in the 3.8 branch there is code in there to check to see if a table exists before doing anything.  I can't see that in 3.9 (so I've added that commit 67a7d1ac7bda07a74bde716fd023ede58d200483).  Must have been missed of the list of cherry-picks keeping the two branches the same.  Testing also did not throw up this issue when installing clean.

**Comment by alexmorrisnz** [comment]
This was 3.9 however that commit is also missing from 3.7 and 3.6. I haven't checked if the log table is created before the plugin on those two versions versions though.
