### ISSUE TITLE
PHPUnit test and phplint fails

### ISSUE THREAD

**Issue by alexmorrisnz** [iomad/iomad#1475]
Trying to run phpunit tests and before it starts to actually run tests you get this error:
```
PHP Fatal error:  Cannot declare class core_accesslib_testcase, because the name is already in use in local/iomad/tests/accesslib_test.php on line 3140

Fatal error: Cannot declare class core_accesslib_testcase, because the name is already in use in local/iomad/tests/accesslib_test.php on line 3140
```

The class needs to be renamed or removed.

**Comment by alexmorrisnz** [comment]
Removed the file and now I'm getting the same error on `local/iomad/tests/dml_test.php`, and based on what else is in the `local/iomad/tests/` folder it looks like you duplicated core tests and then modified them for the iomad customisations.  
I just read the PHPUnit iomad readme file which fixes the issue, but why not modify the core tests to suit your customisations?

**Comment by alexmorrisnz** [comment]
phplint is also failing because of an extra comma in `/mod/trainingevent/view.php` on line 772.

**Comment by turf212** [comment]
fixed at some point in the past as those lib files no longer exist in current versions.
