### ISSUE TITLE
How to update Iomad from 3.8 to 3.9 with out loosing data 

### ISSUE THREAD

**Issue by anantha-ravipati** [iomad/iomad#1478]
We are using Iomad 3.8(multi tenancy) with moodle 3.8 .As there is update of Iomad we want to use it with in our moodle site .
Please give us guidance on how to update Iomad with our moodle site with out loosing Existing data

**Comment by bavdalimbaev** [comment]
the update is the same as in a regular moodle. just make a backup before updating
