### ISSUE TITLE
Department level course educator role

### ISSUE THREAD

**Issue by izharmail** [iomad/iomad#1479]
Is it possible that department manager can edit courses within his department only and can not edit other department courses?

**Comment by turf212** [comment]
Not at the moment or, at least, not without intervention from the site admin.  Courses are assigned at the company level so there is no concept of a course at a company department level.

If you want to have courses which are only for certain parts of a company structure, then you may, instead, want to look at parent child companies where a company manager of the parent company is also a company manager of the child company but a company manager of the child company has no rights outside of their own company.  They can, however, perform all of the same company manager tasks as any other such as creating/editing courses.

**Comment by izharmail** [comment]
Thanks, I will consider child company option for this purpose.
