### ISSUE TITLE
How can I add existing users to an Iomad company?

### ISSUE THREAD

**Issue by totoromaum** [iomad/iomad#1481]
Hi, I am having trouble in adding users to Iomad companies with the latest IOMAD version. I have two questions.

1. Is there any way of adding already existing users to an Iomad company?

2. Can I add an existing user to multiple Iomad companies?

Thank you.

**Comment by turf212** [comment]
You are not able to add users to more than one company at this point in time (other than company managers which you can add into another company via the department managers / users page and selecting company manager type and allow external company managers).

To add unassigned users to the company use the Assign users page.

**Comment by turf212** [comment]
Users can be in multiple companies as of IOMAD 4.3
