### ISSUE TITLE
Manage role inheritance of a child company from the parent company

### ISSUE THREAD

**Issue by totoromaum** [iomad/iomad#1482]
Hi, I expected that a manager in a parent company inherit the manager of its child company with the latest IOMAD version. However, this did not happen when I created the child company of a parent company which has a company manager. I think I am missing something. Could you let me know how I can solve this problem. Thank  you in advance.

**Comment by turf212** [comment]
Company managers of parent companies become company managers of child companies (they have rights over everything below them)
Company managers of child companies only have rights over their own company and any child companies.

It's the same logic as a department manager can only see the departments they are assigned to and below.  No-one can see up the tree.
