### ISSUE TITLE
Creating a license is not possible

### ISSUE THREAD

**Issue by totoromaum** [iomad/iomad#1483]
Hi, I have been trying to creating licenses in a company to no avail with the latest IOMAD version. The problem is that there is no button called 'save' or 'create.'  Even though I filled all the required fields up, there are no ways to create licenses. Please let me know what I am missing. Thank you in advance.

**Comment by turf212** [comment]
It's the button which says "Update license allocation".  I get your point that the language should possibly be better.  I'll make a change so that its "Create" when it's a new license.
