### ISSUE TITLE
'Users Report' -> Filter by custom fields not working (other reports do)

### ISSUE THREAD

**Issue by jlizen** [iomad/iomad#1484]
The Users report area is behaving differently than the other reports, when using company-specific custom fields as a filter. (I haven't tested with non-company-specific).

It ignores the custom field input rather than filtering properly. If no field terms are included for default (non-custom) fields, it just displays the full user list.

Other areas using the same form filter, such as users->edit users, reports->user login report, completion report by course->all users, etc, do not share this behavior. They properly filter based on terms included in the custom field filter.

Glad to provide any additional information needed.

Thank you,
Jess Izen

**Comment by turf212** [comment]
I'd made some changes to that report recently.  It's possibly something to due with that. Will check.

**Comment by turf212** [comment]
Site wide ones work.  Company specific don't.  (tested latest 3.9 code).  Thanks for reporting.  Will fix ASAP.

**Comment by turf212** [comment]
Wasn't the changes made previously just looks like it wasn't working properly.  I'm about to upload a fix.

**Comment by jlizen** [comment]
@turf212  Thanks for the fix!
