### ISSUE TITLE
 Restrict capabilities edit button is not appearing.

### ISSUE THREAD

**Issue by izharmail** [iomad/iomad#1487]
![image](https://user-images.githubusercontent.com/49977312/98840248-9d046e00-2457-11eb-87e4-ac1b72c7387e.png)

Edit button disappeared in restrict capabilities page.

**Comment by turf212** [comment]
Which version?  It's appearing for me on latest 3.6/7/8/9.

Have you done something with your theme which has prevented them from showing?

**Comment by izharmail** [comment]
This issue is with Rebel theme for 3.9. 
Edit button is appearing on all other themes.
