### ISSUE TITLE
Occurs when sslproxy is set true in config file

### ISSUE THREAD

**Issue by rijulsudhir** [iomad/iomad#1489]
![screen](https://user-images.githubusercontent.com/42400713/99032346-5ae64400-259f-11eb-9e0b-1b76d8de9f10.jpg)
* iomad apache server runs behind a load balancer
* Load balancer terminates ssl. 
* wwwroot in config file is a https url.
* Error occurs for company host names, when sslproxy is enabled in config file. 

In moodle when ssl is terminated externally sslproxy needs to be enabled, otherwise browser would say too many redirections. When same done in iomad the main hostname (url at wwwroot in config file) works. But company hostnames fails as shown in the screenshot.

**Comment by rijulsudhir** [comment]
Was able to fix it by adding `$CFG->overridetossl = true` in config file. But is it the right way to do it? afterall `overridetossl` is not mentioned in the default config file.

**Comment by turf212** [comment]
Looks to be correct and thanks for the investigation.  Looking at /lib/setup.php this setting is used to force the URL protocol to be https if it is not already.

```
    if (!empty($CFG->overridetossl)) {
        if (strpos($CFG->wwwroot, 'http://') === 0) {
            $CFG->wwwroot = str_replace('http:', 'https:', $CFG->wwwroot);
        } else {
            unset_config('overridetossl');
        }
    }
```
The code which is changing the wwwroot should be picking up the same protocol as the one which is passed from the webserver.  If the proxy wasn't using this to connect the the webserver then this would cause the confusion and this setting is exactly what you are looking for.

**Comment by rijulsudhir** [comment]
Thanks a lot for checking it out and confirming it.
