### ISSUE TITLE
Exception - Call to a member function get_theme() on null

### ISSUE THREAD

**Issue by dallenk** [iomad/iomad#1492]
Hello, i'm trying to use IOMAD to create a multi-tenant system for moodle.   I'm having some issues with users self-creating accounts with a custom field that currently assigns them to a cohort using plugins (Profile field based cohort membership)

a user is given a "key" that will add them to a cohort and automatically assigns them to a group, which enables access to any course configured with cohort sync enrollment methods.

I'm trying to duplicate this in IOMAD but see the following error when creating a new account.   The account is actually created, but the error shows and a confirmation email is never sent out. 

Any ideas what could be causing this?   I see nothing in the apache error log.  Is there another log location that would give more info to provide?  

Thanks

**Comment by turf212** [comment]
Can you please turn on full developer debug which will allow for the whole error message including which line of which file is throwing it.

Site admin -> Developer -> debugging

Set to full developer debug level, check to show output and save.

**Comment by dallenk** [comment]
Good morning Derek, I ended up dropping the database and re-installing fresh.. the error has cleared now.  I'll close this issue.
