### ISSUE TITLE
change role of existing user (self signup)

### ISSUE THREAD

**Issue by dallenk** [iomad/iomad#1493]
Good morning.. I cannot seem to find a way on the IOMAD dashboard to change the role of a user to a Company Manager.   I see that if I manually add a user I can choose the roles, but my users are all self-registered  with email confirmation and added into a cohort, where the company manager can assign courses.

does this option exist to change a company user role?

**Comment by turf212** [comment]
You want the Department users/managers menu item which is on the Company tab ( > 3.9) or the Users tab (3.9+)

**Comment by dallenk** [comment]
oh man, i can't believe I missed that.. I looked all over and completely looked over that section.
