### ISSUE TITLE
Spelling Mistake - Iomad dashboard

### ISSUE THREAD

**Issue by abhujbal** [iomad/iomad#1494]
In the Iomad dashboard > Course section > **User Enrolment**

Enrollment spelling is wrong its a "Enrolment" please let me know how to change this,

**Comment by dallenk** [comment]
This can be changed by updating the language pack
Home -> Site administration -> Language -> Language customisation

Open the pack, choose the block_iomad_company_admin

![image](https://user-images.githubusercontent.com/2725066/100048122-eeeab380-2dc8-11eb-8445-10a40052bc0b.png)

mine is spelled "User enrolments"

**Comment by turf212** [comment]
strings have been sanitised and changed since this.
