### ISSUE TITLE
Company Certificate logo/border/signature are not applied

### ISSUE THREAD

**Issue by dallenk** [iomad/iomad#1495]
I've been fighting with getting a company certificate for a course to use the customizations in "edit company" with a logo, border and signature but nothing I set is applied to a certificate.

I thought it was due to a "open share" from the root company, to a sub company but creating a course specifically for the sub company also does not apply the settings.

If I specify a logo/border/signature in the certificate activity of the course, it is displayed but every company now has the same certificate.. am I missing something??

**Comment by turf212** [comment]
Are you using the company certificate type in the design options for the iomadcertificate activity within the course?  This only works with the company or company kanji design options.

**Comment by dallenk** [comment]
Hello, yes I have tried both company and companykanji in the course, using the iomadcertificate activity.
![image](https://user-images.githubusercontent.com/2725066/100395407-a532e080-2ff5-11eb-974c-034cac0d1057.png)

In each company I have uploaded a different logo, border and signature but all certificates only contain the text. no borders, logo nor seal/logo.
![image](https://user-images.githubusercontent.com/2725066/100395518-1d010b00-2ff6-11eb-9b9e-7af7bda3e6a0.png)

![image](https://user-images.githubusercontent.com/2725066/100395489-fba01f00-2ff5-11eb-9751-b01830185954.png)

I tried every option in the iomadcertificate activity (i'm sure of it)  selected 'no' except for the cert type, tried picked borders, line and anything else I could think of.

If it makes a difference, i'm using iomadBoost theme.

**Comment by turf212** [comment]
Theme shouldn't matter.  The certificate file in /mod/iomad/certificate/type/company/certificate.php should be picking up the company settings. Can you please confirm which version you are using and I'll test it here?

**Comment by dallenk** [comment]
I'm using the latest git pull from IOMAD_39_STABLE

**Comment by turf212** [comment]
Thanks for confirming.  I have just done the following:

Created a new iomad certificate within a course using the company type and no design options other than this.
Edited a company to have a logo and signature
Clicked to get my certificate and the design is there with the company specific details.

Questions:
- Have you chosen to save the certificate within the mod options? (this shouldn't be set as you never get a new one and we save them in the Iomad reports in any case when someone completes a course).
- When you are getting the certificate, is the user definitely in that company?
- What happens if you select that company from the dashboard and then download the certificate?

**Comment by dallenk** [comment]
i will try again this evening and report back as soon as I can.  Thanks for checking, that would seem it is something on my end, i'll clear caches, unconfigure everything and try it again.

**Comment by dallenk** [comment]
sonofa... i'm an idiot.

I was trying to refresh the page and see the changes, it looks like iomad needs the "get your certificate" button clicked to regenerate it each time I made a change?    It appears to be working now.  I"m assuming any further customization needs to be done in  ./iomad/mod/iomadcertificate/type/company/certificate.php for positioning of each line and logo placements??  

Is there an easy way to make a new "companymylayout" and use in the iomadcertificate activity ??

**Comment by turf212** [comment]
Yep.  That would do it :)

If you cp -rp /mod/iomadcertificate/type/company to /mod/iomadcertificate/type/mycompany you can then edit the certificate.php file under the new directory and change the placement for everything.  The activity we used for this was the old Moodle certificate mod and all of the same tricks with that work with this.  The only difference being the company and companykanji types will handle the per company certificate settings.

**Comment by dallenk** [comment]
perfect, will work off that!   Thank you very much.
