### ISSUE TITLE
Duplicate course completion entries in course completed tab & Course Completion report.

### ISSUE THREAD

**Issue by abhujbal** [iomad/iomad#1496]
Hello, 
I have course completed with the successfully and received 100 marks.
But to test it when i delete the attempt and take the new attempt then there are two entries of the same course attempts in the completed course tab in My Courses section.  

Same thing when i unenroll the user from the course and again enroll him then take the course again then same thing happen.

So normally it should be only one entry of successfully completed attempt of the course. 

Can you please help.

Abhijeet

**Comment by turf212** [comment]
What version are you using?  Newer versions (3.6+) have code which checks to ensure that a course completion event which is fired for an existing enrolment is not re-recorded into the local_iomad_track table when the enrolment date exists.

There are a number of things which will cause the course completion event to fire more than once for a user in a course.  Typically this is when you clear down the lock on the completion criteria to edit it, though there are a number of other scenarios.

In the latest 3.6+ code you can go into the user report for a specific user and edit the recorded information for them in the Iomad record store.  You can change the dates, clear out the user from the course, add new entries without the need for the user to have completed the course, and completely remove the recorded entry.

**Comment by abhujbal** [comment]
Hi Turf, 

Thanks for reply. I have used 3.7 Iomad version. 
But i am not able to find out the "Iomad record store" as you mentioned.

So can you please tell me from where i can access this area to update the report record.

Really thanks for your help.

Abhijeet

**Comment by turf212** [comment]
If you have the latest 3.7 code You can go into the user report for the impacted users and can click on the turn editing on button to gain editing access to the data.  Commit was 5a9db87a34896f702a8a90d7dc82c5c249b9cf79 from the 4th November for that functionality.

**Comment by abhujbal** [comment]
Hi Turf,

If I update the user course grade from the Grade report (turn edit on) and updated the course the grades are not getting reflected on the Iomad>report > section > Completion report by course.

What could be the reason for this. Once added course grades with the course completion report course wise are not getting updated with any of the options, even by retaking the course also. 

How to update or delete the course grade entry from the Iomad > report > course completion report course wise 

Also most importantly, when user takes the second attempt with the course and get the highest grade with the course. Then the second attempt is not get listed with the course completion report and the dashboard course completed tab also not showing the highest grade received with second attempts.

**Comment by turf212** [comment]
Once Iomad has captured the course grade on completion, then any subsequent update to the course grade will be ignored (as the certificate will have been created and the course completion date set at the same time).  If you go into the Iomad reports and open the User's completion report, find the user, open their course completion reports, click on editing, you will get the screen I was talking about.  It's not the grade report within the course.  Sorry I should have been more explicit.

**Comment by abhujbal** [comment]
Hi Turf,
Thank you so much for your help.

But the screen which you have mentioned, on that I am not able to find the **edit option** to edit the grade. Please check the below screenshot.

![image](https://user-images.githubusercontent.com/42462024/102967078-29a25180-4517-11eb-80f5-1edff2627d55.png)

**Comment by turf212** [comment]
"_If you have the latest 3.7 code You can go into the user report for the impacted users and can click on the turn editing on button to gain editing access to the data. Commit was 5a9db87 from the 4th November for that functionality._"

If you pull the latest version of 3.7 you will get this feature :)

**Comment by abhujbal** [comment]
Hi Turf,

I have checked and I am using 3.7.8 (Build: 20200914) which is the latest one. :) 
Do I need to enable it from somewhere?

AB

**Comment by turf212** [comment]
Latest 3.7 version is 3.7.9 ;)

**Comment by abhujbal** [comment]
I may be wrong but instead of updating complete Moodle can I update those 14 files which were changed for this report edit functionality. 

![image](https://user-images.githubusercontent.com/42462024/103087491-ae6f9700-460d-11eb-9d92-b2360a1ec530.png)

**Comment by turf212** [comment]
There are a number of security patches for Moodle wrapped up in that release too.  If you aren't using the git commands to manage the code, I would highly recommend it.  Saves you having to download and then remember to copy over all of the optional packages you have.  Instead it becomes (in your case) :

git pull origin IOMAD_37_STABLE
php admin/cli/upgrade.php --non-interactive

which just merges in the 3.7 branch changes and upgrades the site.

**Comment by abhujbal** [comment]
Ok.
But by updating the LMS with the git commands is our changes remains with the updated LMS which we did with the current LMS.
The change like,
1) Language pack changes
2) custom email templates
3) compaies/users which we have created..
4) UI level changes

**Comment by abhujbal** [comment]
Hi Derick,

Can you please update on my above question.

Also if I want to update the grade which gets display with the Course completion report then can i do it directly from the DB?
In which table i need to update the grade.

Please update.

**Comment by abhujbal** [comment]
Hi Derick,

Can you please update on my above question.

Also if I want to update the grade which gets display with the Course completion report then can i do it directly from the DB?
In which table i need to update the grade.

Please update.

**Comment by turf212** [comment]
Anything which is saved within the database or within moodledata will not be overwritten by a pull/merge from github of the code.  This will only change files which are already under git control (so not any extra plugins you may have downloaded or installed) as long as you haven't made any uncommited local changes to them.  I.e. just the core Iomad and Moodle files.

Language packs are stored in moodledata and local language changes are stored in the database.  All companies, courses and other data are held in the database or the moodledata directories (where any files you have uploaded are kept).

I would always suggest taking a full backup of the site first (database, code and moodledata).  After this it should just be a _git pull origin_ from the public_html directory to get the latest code and run a Moodle upgrade (either by command line _php admin/cli/upgrade.php_ or by going to Site administration -> Notification when logged on.

To answer your question about scores - These are held in the mdl_local_iomad_track table with userid and courseid and timecompleted to identify them.  You would need to re-generate any stored certificates by going to Site administration -> users -> recreate stored certificates and selecting the course / user.  FYI - If you update the code all of this is done for you when you edit within the reports page.
