### ISSUE TITLE
Exception - Argument 1 passed to enrol_plugin::enrol_user() must be an instance of stdClass, bool given

### ISSUE THREAD

**Issue by rijulsudhir** [iomad/iomad#1497]
![screenshot-c0b03217](https://user-images.githubusercontent.com/42400713/100514346-e06e1480-3199-11eb-8463-06f1d50187a4.jpg)
Above is the error occurring. This occurs when upload user csv has shortcode of department and multiple courses. Also it doesn't occur all the time, I still haven't figured out the case in which the error is occurring. But it occurs from time to time. Any idea why this is happening?

**Comment by rijulsudhir** [comment]
it seems that in line 317 of /local/iomad/lib/user.php is setting  `$manualcache[$courseid] = false` that is where the boolean is coming from.
```
            if (!isset($manualcache[$courseid])) {
                if ($instance = $DB->get_record('enrol', array('courseid'=>$courseid, 'enrol'=>'manual'))) {
                    $manualcache[$courseid] = $instance;
                } else {
                    $manualcache[$courseid] = false;
                }
            }
```
and in line 333 that boolean is given as argument as seen below. But enrol_user function doesn't seem to accept boolean
```
$manual->enrol_user($manualcache[$courseid], $user->id, $rid, $today, $timeend, ENROL_USER_ACTIVE);
```
to check why  `$instance = $DB->get_record('enrol', array('courseid'=>$courseid, 'enrol'=>'manual'))` is becoming false, I checked the mdl_enrol table in db and found that my test course has an entry in it with enrol as manual, but its status is set to 0, does enrol status have anything to do with this? When new course is created it is set to 0 by default. I checked the enrolment plugin found that it is already enabled there and also i can enrol through the iomad panel. I tried changing the enrol status in db to 1 directly. But still the error is occurring. So what am i missing here?

**Comment by turf212** [comment]
If manual enrol is set to 0 then the plugin is disabled (which is likely why you are getting the error). Check if it has it's eye open in the enrolment methods under course admin for that course.

 I'd need to go back through that code to see why I was setting it to false.  I was likely trying to do something about the course not being available to that company so could instead set it to a new stdclass() instead of just false.

If you can confirm the set up for the enrolment options in the course I can test what a better solution would be.

**Comment by rijulsudhir** [comment]
**Dashboard--> Site administration--> Plugins--> Enrolments--> Manage enrol plugins**
![screen1](https://user-images.githubusercontent.com/42400713/101106881-1b87a200-35f7-11eb-8a9c-134e0d6589c2.jpg)
**mdl_enrol table in db**
![screen](https://user-images.githubusercontent.com/42400713/101106907-2a6e5480-35f7-11eb-9e01-ef6e0c24af7d.jpg)
**enrolment methods for the course with courseid 72 in above db table**
![screen3](https://user-images.githubusercontent.com/42400713/101107513-74a40580-35f8-11eb-934a-86ec9634d21e.jpg)

**Comment by turf212** [comment]
So from the data I can see the SQL:

select * from mdl_enrol where courseid=72 and enrol =' manual';

should be returning a row.  The logic is, get the enrolment from the cache if it's there.  If it's not, get it from the mdl_enrol table for the manual enrolment type (could be an issue if multiple manual enrolments here) and use that to populate the cache.

That select seems to be failing for some reason.

FYI the status is only used when people are trying to access the course or look at users.  0 == active, 1 == inactive.  (Confusing I know).

**Comment by rijulsudhir** [comment]
Thank you for taking the time to check it out. So what do think is the issue? Any solutions? Sorry, i don't get what you meant by 'could be an issue if multiple manual enrolments here', You meant multiple manual enrolments in cache or in mdl_enrol table?
Is there anything i can do, to find why the select is failing?

**Comment by 2w3nn3r** [comment]
I'm stuck with the same error while working at the demo page. Unfortunately, the error makes it impossible to assign courses via bulk/ CSV-Upload.
