### ISSUE TITLE
move course to another company?

### ISSUE THREAD

**Issue by dallenk** [iomad/iomad#1498]
It appears that a course cannot be moved from one company to another.  I understand that when a course has results from members this could be an issue and cause problems, but if a course is reset it would be a good feature to be able to move a course. 

in the moodle options, I can reassign the group, but in the IOMAD dashboard, the course remains under the previous 'company'

curious if there is a way to do it?  or must it be deleted, then restored to the new company?

**Comment by turf212** [comment]
If there are no users on the course then you should be able to remove it from within the dashboard - courses tab - assign to company page.  You can use the un-assign arrow to remove it from the original company and then select the new company and assign it.

**Comment by dallenk** [comment]
As always, your help was on-point.  I was looking at it differently but you straightened me out on the process.
