### ISSUE TITLE
Company Manager has access to Competency Framework of other companies

### ISSUE THREAD

**Issue by dallenk** [iomad/iomad#1499]
I've noticed that any company manager can view and edit all other competency frameworks across the entire site.    If this isn't intentional, I believe this is a bug as they should only be able to manage their own company?

**Comment by turf212** [comment]
The competency frameworks should be tied to a company and filtered in the same way as courses with the same options for sharing across companies.  What version are using and I'll check.

**Comment by dallenk** [comment]
good morning, latest git pull for 39
i have two companies, several sub-companies under each..

if the competency framework permission is enabled in the roles, all companies show in the dropdown list for competency frameworks, and can view frameworks created by another company.   I'll gather screenshots for you shortly

**Comment by turf212** [comment]
The caps which you need is block/iomad_company_admin:templateview, block/iomad_company_admin:managetemplates and block/iomad_company_admin:managetemplates. The first two allow access from the dashboard to the framewords editing pages and the last is for the tab in the dashboard.  If you give the user more than this they will get access to see all of the frameworks not just in their own company.

**Comment by turf212** [comment]
Tested this on latest 3.9 with two companies.  Created frame work and learning plan template for each.  Logged in as company manager for one of the companies and could only see their own.

Should also say that you can manage these like courses where they can be shared and assigned to other companies.
