### ISSUE TITLE
Company Managers not able to edit courses

### ISSUE THREAD

**Issue by petergaiello** [iomad/iomad#1504]
I had a follow up question in #1301 but I believe it may have been overlooked due to another persons questions.

I am following along with settings recommendations but am have some trouble. 

My overall goal is to have company managers be able to create and edit courses in their own tenancy but not edit any courses that are shared or outside their tenancy.
 
I added settings for editing activities and plenty of other course creation options.

I added these 3 capabilities
"block/iomad_company_admin:createcourse"
"moodle/course:update"
"moodle/course:view"

One thing I did notice is that it still is blank where the list of teachers would be.
![image](https://user-images.githubusercontent.com/69163578/101377150-77645c00-387f-11eb-82ac-93b4b48485c1.png)

with these options set, I can edit but cannot delete. I think I am still missing quite a bit in the ways of allowing Company Managers Edit. Possibly because they are not being assigned as Teachers. 

@turf212 I originally tagged you when I asked my question but anyone that can help would be amazing.

Thank you to any responses.

**Comment by turf212** [comment]
Don't add the "moodle/course:update", "moodle/course:view" capabilities as this would be site wide.

As the company manager, when you create a course you should be given the client course editor role within that course.  If the course is added by a non company manager (say you, as an admin) they don't get that.  The logic around this is probably a little fuzzy now and there should be a more explicit management within the iomad courses page (probably).  A manual work around would be to put the course id /company id pairing into mdl_company_created_courses and give the company manager the client course editor role within it.

To delete courses you need to give the company manager role "block/iomad_company_admin:deletecourses"

**Comment by petergaiello** [comment]
First of all @turf212 thank you for your response.

I removed those two settings, but it still is not granting access to a Company Manager who creates a course. The course is created, but I does not enroll the creator in the course (had to do that manually) and then I still don't have the permissions I need to make changes to the course. I don't even see the Grades, Badges, or Competencies or the Teachers section in the Course Dashboard. Just the Activities section only.

**Comment by turf212** [comment]
Which version are you using so I can test here too?

The client company editor is cut down so it's quite possible that some new capabilities have been added since it was initially set up.

**Comment by 2w3nn3r** [comment]
@turf212 Could you explain how to give  a company manager "client course editor role within" as you described in:
["A manual work around would be to put the course id /company id pairing into mdl_company_created_courses and give the company manager the client course editor role within it."]
I found that, one can change role assignments in mdl_role_assignments. Is there a possibility to do this with the IOMAD interface?

**Comment by 2w3nn3r** [comment]
Ok, I think I got it. The assignments are written into mdl_role_assignments by assigning the course educator role in ("Department users & managers)) AFTER  course id/ company id pairing into mdl_company_created_courses.
