### ISSUE TITLE
How to disable the Notification copy to the company manager for course enrollment and user creation. 

### ISSUE THREAD

**Issue by abhujbal** [iomad/iomad#1505]
1) I want to disable the notification copy to the company manager sent while the user enrolled in the course or while the new user create. 

2) With the company manager's login, I am getting an "invalid department" error when I am uploading bulk users using CSV file.
(username,password,lastname,email)

Please update me with these issues.

Thanks & Regards,
Abhijeet.

**Comment by turf212** [comment]
To disable the email templates for a company go to the company tab and select email templates.  The 2nd column is the manager copy (where appropriate).  Sliding the switch disables this.

Can you give me a sample of the CSV including headers?  Is it just the ones you've mentioned?

**Comment by abhujbal** [comment]
Yes, it is the same I have mentioned in a mail.
(username,password,lastname,email)

But when I upload it with the super admin it works properly but when uploading with the company manager it gives me the error "invalid department"

**Comment by turf212** [comment]
I've just tested this on latest 3.9 code with a CSV which looks like this:

username | password | firstname | lastname | email
wateruser1 | P@55w0rd | wateruser | 1 | water1@example.com
wateruser2 | P@55w0rd | wateruser | 2 | water2@example.com
wateruser3 | P@55w0rd | wateruser | 3 | water3@example.com
wateruser4 | P@55w0rd | wateruser | 4 | water4@example.com

No errors were thrown up.

Can you please check the department your company manager is within that company?  The company manager should be at the top level department for the company.

Select * from mdl_department where companyid = <companyid>
Select * from mdl_company_users where userid = <userid>

**Comment by abhujbal** [comment]
Hi,

Thanks for the update.

Yes, this template also works for me with the super admin access but not with the Company manager access.
I have not created any department within the company as there is no requirement.
So is it mandatory to have a department with the company?

**Comment by turf212** [comment]
You don't need to create a department in the company.  There is a default one which is the top level department for that company created when you create the company, which is what I mean by the top level department.  So if you look at:

SELECT * FROM mdl_department where company = <companyid>;

There should be one which has the same name as the company and which has a parent = 0;

If you then look at :

SELECT * FROM mdl_company_users WHERE userid = <companymanageruserid> AND companyid = <companyid>;

The row should have the departmentid = the the id value in the mdl_department table.

**Comment by abhujbal** [comment]
Hi,

Thank you so much for your help.
