### ISSUE TITLE
No group assigned to user with autoenrolment while self-signup

### ISSUE THREAD

**Issue by michalludynia** [iomad/iomad#1509]
Hi! 
I've created a no-licensed, closed sharing course and assigned it to company. Next I added that course as "autoenrolment courses" in company settings. After self registration of user iomad assigned him to that company by domain and assigned him to the course correctly, but he's not added to any of course groups. 
Company group exists in course and were created automatically, but it seems like users are not assigned to them while auto enrolment.

Is that bug or do I need to configure something more?

IOMAD 3.8

**Comment by turf212** [comment]
That sounds like a bug.  Thanks for reporting.  I'll look ASAP.

**Comment by turf212** [comment]
The $company->autoenrol()  function calls the company_user::enrol() function and checks if the course is shared or not.  If it is (or the course has groups turned on) then it will call company::add_user_to_shared_course().  It looks like the group id may not be getting set, however, so they don't get put into a group when they should.  Testing now.

**Comment by turf212** [comment]
I've added a check in the enrol function which, if the course is shared or in group mode, and the group id is empty, call company::get_company_group() to get or create the default company group.

**Comment by michalludynia** [comment]
@turf212 Thanks for quick response. I've updated user.php file and unfortunately it looks like an additional check did not help and the bug still exists. 
I'm using 3.8 version and when I enrol user using dashboard everything works great and user is assigned to proper group. The situation is different using "autoenrolment courses" and self registration - users are still out of the groups.

**Comment by turf212** [comment]
Tested this again in 3.8 and self signup account is being assigned to company, course and company group in both an open and closed shared course.  I have made some chnges to the signup page as nothing was happening if there as a default company and company wasn't chosen in any other way, but this wouldn't have affected the outcome.  Maybe bring in a full merge?

**Comment by michalludynia** [comment]
Full merge helped me. It works great on my IOMAD 3.8. 
Thanks @turf212 for your help.
