### ISSUE TITLE
Administrator created user in a company - welcome email not using company subdomain

### ISSUE THREAD

**Issue by dallenk** [iomad/iomad#1510]
As the site administrator, I create a Company Manager in a company, the welcome email with temporary password contains the root domain of the site, and not the company subdomain.

As a Company Manager, creating a new user in the company the email contains the correct subdomain

structure:

**As the Site Admin**
```
dev.domain.com  _<--email contains this domain_
   |
   |-----c1.dev.domain.com
   |            |---c1s1.dev.domain.com  _<-- creating a user here_
   |
   |-----c2.dev.domain.com
               |---c2s1.dev.domain.com
```

**As a Company Manager**
```
dev.domain.com  
   |
   |-----c1.dev.domain.com
   |            |---c1s1.dev.domain.com  _<-- creating a user here, welcome email contains this domain_
   |
   |-----c2.dev.domain.com
               |---c2s1.dev.domain.com
```

**Comment by turf212** [comment]
That sounds like a bug.  The processing of the email should be conscious of any company hostname.

**Comment by turf212** [comment]
I've added a function $company->get_wwwroot() which will bring back the appropriate wwwroot for the company using the hostname (if set) or the default $CFG->wwwroot.  I've switched the routing in /lib/setuplib.php to use this too which means that Iomad will work with multiple domains as well as using <domain>/<directory> style wwwroot.  This can now be <domain1>/<directory> <domain2>/<directory>  and so on.

I've also updated the LinuURL and CourseURL variables to ensure that the correct wwwroot is being used in the emails for that company.

**Comment by dallenk** [comment]
Fantastic! I will update now and test.

**Comment by dallenk** [comment]
odd...  every company gives a 500 error when clicking "edit user" using the Admin User.
nothing in the virtualhost error log.. will look more.
are you able to test ?

**Comment by dallenk** [comment]
i see this in the error log with development/debug set when the "edit users" page.


[ Sat Dec 12 09:28:43.915620 2020] [php7:notice] [pid 14377] [client 172.218.212.184:63314] PHP Stack trace:, referer: https://sub.domain.ca/my/
[Sat Dec 12 09:28:43.915630 2020] [php7:notice] [pid 14377] [client 172.218.212.184:63314] PHP   1. {main}() /var/www/vhosts/domain.ca/iomad/blocks/iomad_company_admin/editusers.php:0, referer: https://sub.domain.ca/my/
[Sat Dec 12 09:28:43.915635 2020] [php7:notice] [pid 14377] [client 172.218.212.184:63314] PHP   2. require_once() /var/www/vhosts/domain.ca/iomad/blocks/iomad_company_admin/editusers.php:17, referer: https://sub.domain.ca/my/
[Sat Dec 12 09:28:43.915640 2020] [php7:notice] [pid 14377] [client 172.218.212.184:63314] PHP   3. require_once() /var/www/vhosts/domain.ca/iomad/config.php:27, referer: https://sub.domain.ca/my/
[Sat Dec 12 09:28:43.915645 2020] [php7:notice] [pid 14377] [client 172.218.212.184:63314] PHP   4. initialise_fullme() /var/www/vhosts/domain.ca/iomad/lib/setup.php:747, referer: https://sub.domain.ca/my/
[Sat Dec 12 09:28:43.915650 2020] [php7:notice] [pid 14377] [client 172.218.212.184:63314] PHP   5. company->get_wwwroot() /var/www/vhosts/domain.ca/iomad/lib/setuplib.php:837, referer: https://sub.domain.ca/my/
[Sat Dec 12 09:28:43.918385 2020] [php7:notice] [pid 14377] [client 172.218.212.184:63314] PHP Warning:  require_once(/var/www/vhosts/domain.ca/iomad/blocks/iomad_company_admin/editusers_table.php): failed to open stream: No such file or directory in /var/www/vhosts/domain.ca/iomad/blocks/iomad_company_admin/editusers.php on line 20, referer: https://sub.domain.ca/my/
[Sat Dec 12 09:28:43.918449 2020] [php7:notice] [pid 14377] [client 172.218.212.184:63314] PHP Stack trace:, referer: https://sub.domain.ca/my/
[Sat Dec 12 09:28:43.918485 2020] [php7:notice] [pid 14377] [client 172.218.212.184:63314] PHP   1. {main}() /var/www/vhosts/domain.ca/iomad/blocks/iomad_company_admin/editusers.php:0, referer: https://sub.domain.ca/my/
[Sat Dec 12 09:28:43.918525 2020] [php7:notice] [pid 14377] [client 172.218.212.184:63314] PHP Fatal error:  require_once(): Failed opening required '/var/www/vhosts/domain.ca/iomad/blocks/iomad_company_admin/editusers_table.php' (include_path='/var/www/vhosts/domain.ca/iomad/lib/pear:.:/usr/share/php') in /var/www/vhosts/domain.ca/iomad/blocks/iomad_company_admin/editusers.php on line 20, referer: https://sub.domain.ca/my/
[Sat Dec 12 09:28:43.918554 2020] [php7:notice] [pid 14377] [client 172.218.212.184:63314] PHP Stack trace:, referer: https://sub.domain.ca/my/
[Sat Dec 12 09:28:43.918576 2020] [php7:notice] [pid 14377] [client 172.218.212.184:63314] PHP   1. {main}() /var/www/vhosts/domain.ca/iomad/blocks/iomad_company_admin/editusers.php:0, referer: https://sub.domain.ca/my/

**Comment by dallenk** [comment]
git reset --hard 8ec24d5  resolves the 500 error.

troubleshooting:
[Sat Dec 12 09:28:43.918385 2020] [php7:notice] [pid 14377] [client 172.218.212.184:63314] PHP Warning: require_once(/var/www/vhosts/domain.ca/iomad/blocks/iomad_company_admin/editusers_table.php): **failed to open stream: No such file or directory** in /var/www/vhosts/domain.ca/iomad/blocks/iomad_company_admin/editusers.php on line 20, referer: https://sub.domain.ca/my/

seems like a file is missing on the commit.

commit c7b91ca9830d9769641f9b71c1371b32f7878477
blocks/iomad_company_admin/editusers.php 
```
require_once(dirname(__FILE__) . '/../../config.php'); // Creates $PAGE.
require_once($CFG->libdir.'/adminlib.php');
require_once($CFG->dirroot.'/user/filters/lib.php');
require_once($CFG->dirroot.'/blocks/iomad_company_admin/editusers_table.php');
require_once('lib.php');
```

editusers_table.php doesn't exist.

**Comment by turf212** [comment]
There was.  That's what I get for doing three things at once.  Commit was under #1512 I'd missed the table file.

**Comment by turf212** [comment]
It's now in the codebase and pushed under 86044464de8f8e344db31fba5ec548739e988914

**Comment by dallenk** [comment]
Thank you.

**Comment by cescc1978** [comment]
Hi, I'm facing the same problem with IOMAD Moodle 3.9.3, I need to update??
