### ISSUE TITLE
Fresh 'git clone' installation of MOODLE_39_STABLE - error loading home page - Table "company" does not exist

### ISSUE THREAD

**Issue by ni-ght** [iomad/iomad#1513]
When loading home page, on a fresh 'git clone' installation of MOODLE_39_STABLE:
    
    Table "company" does not exist
    Debug info: 
    Error code: ddltablenotexist
    Stack trace:
    line 665 of /lib/dml/moodle_database.php: dml_exception thrown
    line 1574 of /lib/dml/moodle_database.php: call to moodle_database->where_clause()
    line 1704 of /local/iomad/lib/iomad.php: call to moodle_database->get_record()
    line 886 of /lib/setuplib.php: call to iomad::check_redirect()
    line 747 of /lib/setup.php: call to initialise_fullme()
    line 1068 of /config.php: call to require_once()
    line 30 of /index.php: call to require_once()

**Comment by turf212** [comment]
Thanks for reporting.  I've added a check in the redirect code which then does nothing when installing.
