### ISSUE TITLE
How can I check the email log sent from Moodle as a notificaitons

### ISSUE THREAD

**Issue by abhujbal** [iomad/iomad#1514]
Hi,

Is there any area or option through which i can check the log of the outgoing mails (notifications) send by moodle?

--
Abhijeet

**Comment by michalludynia** [comment]
I'm not sure if that's yours case but you can check some send emails in the iomad dashboard. When you go to reports tab you can open "Outgoing email report".

**Comment by turf212** [comment]
Unfortunately Moodle doesn't keep a log of any emails sent.  If the emails are ones which are through the Iomad dashboard or are to do with Iomad functionality, then these are kept  and you can view them in the report which @Wazowski11 mentioned.  Your only other option is checking your SMTP logs to see if something matches up timewise with an email being sent to a user.

**Comment by abhujbal** [comment]
Hi Wazowski/Turf

Thank you so much for your help with this.

AB
