### ISSUE TITLE
possible z-index CSS bug - Edit company users - Edit item is hidden behind

### ISSUE THREAD

**Issue by dallenk** [iomad/iomad#1515]
![image](https://user-images.githubusercontent.com/2725066/102703722-6cb6a900-4227-11eb-96d9-c23d819151d3.png)

I can use the arrow key to navigate to the edit user item, but it is not visible.

**Comment by turf212** [comment]
I added a fix for this in a12ecf708605af135ee45c924d7842dff53a1d99 which made the main section min height 50% for the page.  It was pushed on 16th Dec.  Do you have the latest pull?

**Comment by dallenk** [comment]
good morning,   yes I'm using the latest pull.
"git log --pretty=format:'%h' -n 1"
fda7699
"git pull"
Already up-to-date.

**Comment by turf212** [comment]
Which theme are you using (in case the CSS is different).  This was the CSS which was added in the commit:

```
#page-blocks-iomad_company_admin-editusers .main, #page-blocks-iomad_company_admin-editusers #region-main, #page-blocks-iomad_company_admin-editusers #region-main > div {
    height: 100%;
}

#page-blocks-iomad_company_admin-editusers .no-overflow {
    min-height: 50%;
}
```

**Comment by dallenk** [comment]
Hello, I am only using iomadBoost themes across the entire site for all companies..  However, this morning I attempted to change a theme for a single company to compare and see if it is a theme related problem for me, and now the entire site is inaccessible and I have no idea what to look for .. I have many virtual hosts running under apache and iomad is the only one affected.   Accessing any of the companies causing apache2 to use 100% of CPU and my load averages are building up.. it was 4.36 when I restarted the apache service.

How can I change the theme used for a company in the database back to iomadBoost and see if that is what is causing this new problem?   I've tried clearing all caches via cli, and browsers already.

top - 07:56:03 up 5 days,  9:37,  2 users,  load average: 1.93, 1.57, 1.45
Tasks: 161 total,   3 running, 158 sleeping,   0 stopped,   0 zombie
%Cpu(s): 56.3 us,  5.5 sy,  0.0 ni, 37.5 id,  0.5 wa,  0.0 hi,  0.2 si,  0.0 st
KiB Mem :  8174788 total,   596780 free,   917500 used,  6660508 buff/cache
KiB Swap:        0 total,        0 free,        0 used.  6741504 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 6534 www-data  20   0  719224 184332  77120 R 100.0  2.3   6:21.81 apache2
 6622 www-data  20   0  730308 184280  77704 R 100.0  2.3   1:30.78 apache2


This is after approx 2 minutes of attempting to view two companies.  Browser is just sitting and spinning the icon in the tab.. nothing displays.. after a few more minutes the page shows with no styling applied, just plain text.   This is the first time I've seen this happen with iomad, but I've also never changed the theme that I can remember.

**Comment by turf212** [comment]
The tables in the DB to define the themes are mdl_company and mdl_user.

update mdl_company set theme='iomadboost' where id = #companyid#;
Update mdl_user set theme=;iomadboost' where id in (select userid from mdl_company_users where companyid = #companyid#);

Then clear the cache.

**Comment by turf212** [comment]
from what you've described, the CSS is broken somewhere.  Likely in the new theme files.

**Comment by dallenk** [comment]
OK.. all companies are using the same iomadboost theme in the database (i never assigned a user a theme)   clear cache using the cli script and cleared browser cache and the problem still persists.   all other vhosts are working without issue but for some reason as soon as I changed one company theme to iomad (from iomadboost) all companies can't be accessed with the browser.    This is a development site with only testing users created, so if I have to reinstall clean I don't mind rebuilding it if I have too...   Can all courses and companies/users be restored from the database alone? or do i need to copy moodledata as well?

do you have any other suggestions I can attempt?

**Comment by dallenk** [comment]
quick question..  i just noticed that a few users do not have a theme in the database, I don't know if they ever did before the theme change but could this cause a problem ??
mysql> select id,theme from mdl_user;
+----+------------+
| id | theme      |
+----+------------+
|  1 |            |
|  2 | iomadboost |
|  3 | iomadboost |
|  4 | iomadboost |
|  5 | iomadboost |
|  6 | iomadboost |
|  7 |            |
|  8 | iomadboost |
|  9 |            |
| 10 | iomadboost |
| 11 | iomadboost |
| 12 | iomadboost |
| 13 | iomadboost |
| 14 | iomadboost |
| 15 | iomadboost |
| 16 | iomadboost |
| 17 | iomadboost |
| 18 | iomadboost |
| 19 | iomadboost |
| 20 | iomadboost |
| 21 | iomadboost |
| 22 | iomadboost |
| 23 | iomadboost |
| 24 | iomadboost |
| 25 | iomadboost |
| 26 | iomadboost |
| 27 | iomadboost |
| 28 | iomadboost |
| 29 | iomadboost |
| 30 | iomadboost |
| 31 | iomadboost |
| 32 | iomadboost |
| 33 | iomadboost |
| 34 | iomadboost |
| 35 | iomadboost |
+----+------------+

I did update all users to have the iomadboost theme in the db, cleared cache again and still having the same problem.
cache was cleared in cli, apache restarted.. even put into maintenance mode and the maintenance page does show (but can't access anything anyway)

**Comment by dallenk** [comment]
not sure if this helps, but running the dev tools console shows:
![image](https://user-images.githubusercontent.com/2725066/102805556-3f294700-4370-11eb-9ab0-197aea2a0d20.png)

If i stop the page loading, the CSS shows as cancelled.
![image](https://user-images.githubusercontent.com/2725066/102805615-56683480-4370-11eb-8ba3-c6cf53437c27.png)

**Comment by dallenk** [comment]
after 5 mins of waiting for the page load.
![image](https://user-images.githubusercontent.com/2725066/102807467-8d8c1500-4373-11eb-972d-5b603d6ee065.png)

**Comment by turf212** [comment]
if a user doesn't have a theme it's because they are not in a company.  When the user is added to a company they get given the company theme.  We are really just using core Moodle's allow user theme and giving the theme to the user without them choosing it, so it's not really anything special in the Iomad code.

It does sound like something else is going on, however.  What is the site theme?  Is it iomadboost too?  (select * from mdl_config where name = 'theme';)

**Comment by dallenk** [comment]
mysql> select * from mdl_config where name = 'theme';
+----+-------+------------+
| id | name  | value      |
+----+-------+------------+
|  5 | theme | iomadboost |
+----+-------+------------+
1 row in set (0.01 sec)

**Comment by turf212** [comment]
Something else which may be impacting load time is if you have themedesigner mode switched on.  (Site admin -> appearance -> theme settings, theme designer mode).  When this is enabled the site doesn't cache anything, which means that every page will take at least ~ 1 minute to load due to the boost theme.

FYI - I've checked the Iomad theme in my test 3.8 and 3.9 sites and nothing untoward is happening with the Iomad theme.

**Comment by dallenk** [comment]
I've manually deleted cache and localcache in moodledata and see they are recreated when trying to load the pages.  I also tried git reset --hard HEAD, and a git pull.  no change.
odd that everything worked great until trying to change a theme for a company though.. is it safe to assign the default moodle boost or classic theme in the db for mdl_user, mdl_company and mdl_config? and see if this allows me login?   I don't believe I have ever changed theme designer mode (and I can't access it anyway at the moment to check)

**Comment by turf212** [comment]
You can use any Moodle theme you like for anything (it's a Moodle site after all :) You just lose the per company configuration fro CSS/Logos/Menus.

**Comment by dallenk** [comment]
I've gone ahead with the following:
update mdl_config set value='classic' where name='theme';
update mdl_user set theme='classic';
update mdl_company set theme='classic';

php admin/cli/kill_all_sessions.php
php admin/cli/purge_caches.php

sudo -u www-data /usr/bin/php admin/cli/maintenance.php --disable
== Maintenance mode (https://mydomain.ca) ==
Maintenance mode has been disabled and the site is running normally again

Results are the same, looks like CSS is never loaded.

**Comment by turf212** [comment]
I'm assuming you have full debug on? 

$CFG->debug = (E_ALL | E_STRICT);   // === DEBUG_DEVELOPER - NOT FOR PRODUCTION SERVERS!
$CFG->debugdisplay = 1;             // NOT FOR PRODUCTION SERVERS!

In your config.php file

If will throw if there are any other syntax errors which could be causing this.

Another thought, are you using a different URL than in the config file?

**Comment by dallenk** [comment]
sorry for the delay, call for work..
I will enable full debug, I am using the correct URL in the config.php file.. nothing else changed until I tried to assign a different theme to one company.

**Comment by dallenk** [comment]
( ! ) Notice: Undefined index: path in /var/www/vhosts/mydomain.ca/iomad/local/iomad/lib/company.php on line 171
--


1 | 0.0001 | 369984 | {main}( ) | .../index.php:0
2 | 0.0002 | 375072 | require( '/var/www/vhosts/mydomain.ca/iomad/config.php ) | .../index.php:27
3 | 0.0002 | 389888 | require_once( '/var/www/vhosts/mydomain.ca/iomad/lib/setup.php ) | .../config.php:28
4 | 0.0765 | 2543208 | initialise_fullme( ) | .../setup.php:747
5 | 0.0789 | 2601048 | company->get_wwwroot( ) | .../setuplib.php:837


then the spinner waiting for CSS.


line 171:              $url = "$u[scheme]://".$this->companyrecord->hostname."$u[path]" . (isset($u["query"]) ? "?$u[query]" : "");

**Comment by dallenk** [comment]
just for a test.. I disabled http redirect to https.. updated the wwwroot in config.php to use http:

no change, was wondering if that was maybe the cause..

**Comment by dallenk** [comment]
OK.. so I went and removed the iomad directory and tried a fresh install from git.
rm -rf iomad/
git clone https://github.com/iomad/iomad.git
cd iomad
git checkout -b myiomad39 origin/IOMAD_39_STABLE
git pull origin IOMAD_39_STABLE
cp ../iomad.old/config.php ./
chown -R www-data:www-data *
sudo -u www-data /usr/bin/php admin/cli/maintenance.php --disable


same issue.. stalls while getting CSS.


```
( ! ) Notice: Undefined index: path in /var/www/vhosts/mydomain.ca/iomad/local/iomad/lib/company.php on line 171
--
1 | 0.0001 | 360032 | {main}( ) | .../index.php:0
2 | 0.0001 | 360704 | require_once( '/var/www/vhosts/mydomain.ca/iomad/config.php ) | .../index.php:30
3 | 0.0001 | 369888 | require_once( '/var/www/vhosts/mydomain.ca/iomad/lib/setup.php ) | .../config.php:28
4 | 0.3620 | 3670488 | initialise_fullme( ) | .../setup.php:747
5 | 0.3633 | 3728744 | company->get_wwwroot( ) | .../setuplib.php:837
```

**Comment by dallenk** [comment]
also manually removed some of the moodledata folders, and verified they are all recreated when I take it out of maint mode with cli.
rm -rf cache/
rm -rf sessions/
rm -rf temp/
rm -rf trashdir/
rm -rf localcache/
rm -rf filedir/

All recreated again.. unfortunatly the issue still remained.

next I created a new db and updated config.php
mysql> CREATE DATABASE db_mydomain_ca DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
Query OK, 1 row affected (0.00 sec)

mysql> grant all privileges on db_mydomain_ca.* to 'usr_training'@'localhost' identified by 'usr_training';
Query OK, 0 rows affected, 1 warning (0.01 sec)

mysql> flush privileges;
Query OK, 0 rows affected (0.01 sec)

(edit:  I should have noted I attempted to restore the database after the new once was created)

Result is the same, however, the title does change the tab to show "Installation Moodle 3.9.3 (Build 20201109)"

**Comment by dallenk** [comment]
OK.. this is interesting...  I had a second instance dev.mydomain.ca running with multiple companies... I changed the theme of one of the sub companies and the exact same thing happened.. i can no longer access any of the sites under the dev.mydomain.ca instance..

beforehand, I did a git pull to the most recent code, backed up database and made a full copy of the vhost directory structure.
 
I will run a compare on the DB and look for anything odd.

**Comment by dallenk** [comment]
there is something in the database for sure.. restoring to the db backup taken before changing the theme setting for one subcompany restores the site.. unfortunately I do not have a recent db backup of my other site.   I'll run through a diff and see if I can narrow it down.. nothing jumped out right way.

**Comment by dallenk** [comment]
update
Brand new git clone/checkout/pull
brand new empty database
once config.php is generated by the install and added to iomad/   the same result..

**Comment by turf212** [comment]
What were the steps to produce (and I'll do the same here)?

**Comment by dallenk** [comment]
I'll get a detailed list of steps, with OS/php versions ect..

**Comment by dallenk** [comment]
I'd like to send you some credentials you can see for yourself, with the most current code from git.   Is there a private messaging feature here or an email I can send too ?

**Comment by turf212** [comment]
I don't think there is.  If you send to helpdesk at e-learndesign dot co dot uk (with the correct syntax) I can get it there.

**Comment by dallenk** [comment]
email sent with notes...  If you wait 5 mins for the request to time out after the refresh, you'll see it does load without CSS (eventually)

**Comment by turf212** [comment]
SO I created a site to mimic yours.  2 parent companies each with 3 child companies.  All have 1 user and 1 manager.  Each company has a hostname associated to it and one has the same as the wwwroot for the site (in case it was something to do with caching).  Once set up, I changed one of the companies to use iomadbootstrap theme.  All worked and no issues.

Did I miss any steps?

**Comment by dallenk** [comment]
I will restore the DB backup on the dev site so I can see it.  I'll post back shortly

**Comment by dallenk** [comment]
Here is the company layout (hostnames match the company names)

![image](https://user-images.githubusercontent.com/2725066/103022263-7dee0700-4500-11eb-90e3-8a75e892144d.png)
Each has 3 users.. one manager, one department training manager, and a user. (some have more users)

I changed the theme to iomad, from iomadboot in one of the sub companies  (c1s1.dev.mydomain.ca)

Both of these sites were fresh installations and configured from the ground up, nothing was imported from each other.


the db has been restored on the dev site.  Something is changing in the database if I restore it after the theme change and it works again, I just can't figure out what the heck it is.

**Comment by dallenk** [comment]
I will add, there are a number of permission changes for the Company Managers to view other certificates, create / edit own courses ect..

**Comment by dallenk** [comment]
I just performed a fresh installation following the git installation and kept detailed notes and logs from the server, with screenshots of each step taken during the web setup.. I will post links to direct downloads in the ticket #6884
