### ISSUE TITLE
How can I move users from one company to another?

### ISSUE THREAD

**Issue by cerpusoddarne** [iomad/iomad#1516]
I have a situation where a lot of users have been created in the wrong company. 

Is there any way for me to move them to the correct company? No courses or anything else is involved.

**Comment by dallenk** [comment]
I had the same question a while ago.. if you go into the company, use the "assign to company" feature.   remove the users so they appear in the potential users side.. Then go to the company you want them in and assign them from the potential users window..  

I believe that will work.

**Comment by gregosullivan** [comment]
I did this and it did work but caused some issues with the licencing. 

All records/certificates for the courses completed on the previous company's licence didn't show in the reports for the new company.

The only way to access the old course records was to open the user report, then (in a new tab) change my company back to the original company, and then refresh the user report.

**Comment by gregosullivan** [comment]
Licencing aside, would this be the recommended way to move users between companies?

**Comment by turf212** [comment]
As this had been fairly manual previously - option added in 4.3
