### ISSUE TITLE
What is the PHP compatible version for the current Iomad stable software?

### ISSUE THREAD

**Issue by ab-drame** [iomad/iomad#1517]
Hello,
According to the Iomad installation guide the “PHP 5.6. PHP 7 and 7.1 will work”
But at the other hand the moodle official site is stating from the link below https://docs.moodle.org/dev/Moodle_and_PHP
“PHP 7.0 can be used with Moodle 3.0.1, Moodle 3.1”
“PHP 7.1 can be used with Moodle 3.2 and later releases. It is also the minimum supported version for Moodle 3.7.”
also 
The last moodle stable release (3.10) Requires: PHP 7.2, MariaDB 10.2.29 or MySQL 5.7 or Postgres 9.6 or MSSQL 2012 or Oracle 11.2 etc..
Considering these facts, I need to know what moodle version correspond to the last Iomad stable version?
What is the PHP version we should use when installing Iomad ?
The reason I am asking because I tried installing Iomad with PHP 7.0 , it never worked for me; I also tried PHP 7.1 and get stocked on the web interface when trying to finalize the install; I could not set the main Administrator password it was grayed out 
Thanks,

**Comment by turf212** [comment]
The install document is a little out of date (something I'm working on).  Iomad requires the same versions of PHP and so on as Moodle for the same branch.  I.e. Iomad 39 is Moodle 3.9 and so on.

**Comment by ab-drame** [comment]
Hi,
Thanks for you response;
With php 7.4 installed In a new server install when try testing the configuration in doing
/var/www/html/moodle/admin/cli$ php install.php --help,   I get the following error message
"PHP Fatal error:  Cannot use 'object' as class name as it is reserved in /var/www/html/moodle/lib/setuplib.php on line 66
Is there any thing i can do to fix it ?

Thanks.
