### ISSUE TITLE
Looking for support

### ISSUE THREAD

**Issue by petergaiello** [iomad/iomad#1518]
We have installed IOMAD as our LMS platform and have some specific needs that we may be looking to have someone develop for us if necessary. 

We are looking to develop a progress dashboard to create gamification of our certification program. 

We are also looking to be able to connect with an outside company via api/sso with a badging and digital credentialing company. (from my project lead for the certification program "Need to integrate with external provider where we send the external provider the user and completion of specific courses.")

Are these things possible within the current IOMAD environment or would we need to further develop our current system?

**Comment by turf212** [comment]
If you send an email into info (at) iomad (dot) org then we can pick this up there.
