### ISSUE TITLE
Filter categories to only show 'company' categories for the current user

### ISSUE THREAD

**Issue by zchermit** [iomad/iomad#1519]
This issue relates to Iomad plugin (local/iomad/lib/iomad.php:410 iomad_filter_categories function) at IOMAD_39_STABLE branch.
PHP function strpos never return 'true' as a boolean value. 
This condition:
`if (true === strpos($categoryrec->path, "/".$user->company->category."/")) {`
should be changed to:
`if (false !== strpos($categoryrec->path, "/".$user->company->category."/")) {`

**Comment by turf212** [comment]
Thank you for this.  When I was coding this it did pass a true but there were issues if the result was at the first (0) position.  This is better in any case so have changed it.

**Comment by zchermit** [comment]
Thank you for such a quick response and fix!
