### ISSUE TITLE
User data not found.

### ISSUE THREAD

**Issue by abhujbal** [iomad/iomad#1521]
Hi Derick 

I am facing some weird situation with our client LMS (Iomad). 

With client production environment. we have created one user who has not even access (Last access never) his account with the LMS. Also, he has not self-enrolled in any of the courses available with the LMS. But still, he has received the Course completion notification from the LMS for one of the courses. which is again not showing in the outgoing email report for that user.

But when I have checked the SMTP outgoing mail log there I can able to see that the course completion email notification has been sent to this user. 

So what could be the possibilities for this kind of issue with the LMS?

I really appreciate your help on the same.

Thanks,
AB

**Comment by turf212** [comment]
If the email is not in the outgoing email report and there isn't another user with the same email address, or the affected user is not a manager and you also haven't set up the supervisor email field with any other user having their email address set, or you haven't updated any of the email templates to CC to that email address, then the email is not coming through the Iomad code and must be coming from the course enrolments or any other plugin within the course.

Check you don't have any duplicate email addresses for users and check the CC's in the email templates.
