### ISSUE TITLE
PHP 7.4 and error "PHP Fatal error: Cannot use 'object' as class name as it is reserved in /var/www/html/moodle/lib/setuplib.php on line 66"

### ISSUE THREAD

**Issue by ab-drame** [iomad/iomad#1522]
Hi,
Thanks for you response to the previous post.
With php 7.4 installed In a new server install when try testing the configuration in doing
/var/www/html/moodle/admin/cli$ php install.php --help, I get the following error message
"PHP Fatal error: Cannot use 'object' as class name as it is reserved in /var/www/html/moodle/lib/setuplib.php on line 66
Is there any thing i can do to fix it ?

Thanks.

**Comment by turf212** [comment]
Which Iomad code are you installing?  Both 3.8 and 3.9 have a blank line for that line number in that file.  https://github.com/iomad/iomad/blob/e81c92a3f141895ccf5b9c64e10500ac5a5f3ce5/lib/setuplib.php#L66

It may be one of the older plugins or it could be an optional plugin you have installed?

FYI I've tested via the CLI upgrade.php and purge_caches.php via PHP7.4 on the latest 3.8/9 code and didn't get any errors.

**Comment by ghost** [comment]
Got the same error.
The only non standard plugins I use are grouptool and organizer

**Comment by caljp** [comment]
Hi, are you following the install doc? I did this and pulled IOMAD_32_STABLE and then got the php error, if you run the below instead and re-apply the db settings it should work:

`checkout -b myiomad39 origin/IOMAD_39_STABLE`

**Comment by ghost** [comment]
Found the issue for some reason an old moodle version was linked in the update docs of version 3.10

**Comment by boboche** [comment]
Install doc mentions iomad32.  Landed here because of the same error in xampp.
