### ISSUE TITLE
Diffrent language Course display as per language preferance of the user

### ISSUE THREAD

**Issue by abhujbal** [iomad/iomad#1529]
Hi Derick,

Wish you A Very Happy New Year!!!

I have a different language courses uploaded with LMS.
So is there any option available though which I can achieve the functionality like if the user preferred the language option with Spanish then only courses develop in Spanish language will get display. 

Thanks
AB

**Comment by turf212** [comment]
There isn't anything to filter courses by language.  You could put the courses into categories based on language but that wouldn't do anything for the user's dashboard.  We do make use of the multi-lang filters, so, depending on how you've set your site up, you could have a single course which displays in different languages depending on what the user has selected.  You can also make content within the course dependent on current language using the conditional access portion of the course activity/resource.

More info on this is here - https://docs.moodle.org/310/en/Multi-language_content_filter and https://docs.moodle.org/310/en/Restrict_access_settings

**Comment by abhujbal** [comment]
Hi,

Can I add the preferred language filed (if i installed the language pack) into the new user account creation form? and if user login to the LMS can the preferred language will automatically get set with the LMS.

--
AB
