### ISSUE TITLE
Bulk upload users fails in update

### ISSUE THREAD

**Issue by pozor** [iomad/iomad#1531]
Hello

**Affected branches**: IOMAD 35_STABLE and IOMAD_39_STABLE (these are the one I tested)
**Component**: iomad_company_admin
**File**: blocks/iomad_company_admin/uploaduser.php

**Description**: if I upload a well formatted CSV to update one or more users, the password of the updated user changes (to an unknown one) even if I select to not change the password.

**Reprodution steps**:
1. Upload a csv with a new user, ie:
```
username;password;firstname;lastname;email;department;
test1;Qwerty12;Test1;Test1;test1@test.com;DEP;
```
2. Login with that user just to check that everything works good
3. Upload a csv with the same user with a field changed (ie: firstname, lastname or department)
```
username;firstname;lastname;email;department;
test1;Test1New;Test1New;test1@test.com;DEP;
```
4. On field "Upload type" select "Update existing users only" or "Add new and update existing users"
5. On next step, select "Override with file" in the "Existing user details" field (i want to update the profiles with the new CSV)
6. Select "No changes" for "Existing user password" field (i want to maintain old user password)
7. Try to login with username: test1 and password: Qwerty12 and the user won't log in

I tried even leaving the same password in the second file and still doesn't work:
```
username;password;firstname;lastname;email;department;
test1;Qwerty12;Test1New;Test1New;test1@test.com;DEP;
```

If you try the original moodle bulk upload, it work in the right way (but of course without department and license stuff).

I fixed this in IOMAD_35_STABLE (the variable $temppasswordhandler must be outside the foreach and few other changes), now I'll try to fix for IOMAD_39_STABLE

If you confirm the issue, is there any chance to fix it? If I fix it by my own, let me know if I can share the fix in some way.

Thx for the effort.

**Comment by turf212** [comment]
Thanks for reporting this.  The issue is due to when we are stashing the existing users password and the logic around what the default of this would be.

**Comment by pozor** [comment]
Thanks! It's working for me.
There is just a debug line (805) in the code:
echo "Got a new user - stopping";die;

**Comment by turf212** [comment]
Whoops!  Thought I'd got them all :O

removed and pushed.
