### ISSUE TITLE
3.5 ->3.9 Upgrade - local_report_user_logins duplicate values

### ISSUE THREAD

**Issue by tbeachy** [iomad/iomad#1535]
I was able to upgrade from Moodle 3.2 to Iomad 3.5 successfully.  Now working on upgrading 3.5 to 3.9 using Iomad.
DB is on AWS.  Using 'auroramysql' db driver and have converted all tables to dynamic row format.  All upgrade pre-checks are ok.
I had other index-related issues the first few times I ran the upgrade, but those have been dealt with and fixed.  So, the upgrade has partially been completed.  But currently, I still have 238 plugins left that need to be upgraded.
When the upgrade (takes a loong time to run) finally gets to the local_report_user_logins upgrade it says:
```
Dealing with 144542 users 10% 20% 30% 40% 50% 60% 70% 80% 90%
Did you remember to make the first column something unique in your call to get_records? Duplicate value '276346' found in column 'id'.

    line 1282 of /lib/dml/mysqli_native_moodle_database.php: call to debugging()
    line 123 of /local/report_user_logins/db/upgrade.php: call to mysqli_native_moodle_database->get_records_sql()
    line 692 of /lib/upgradelib.php: call to xmldb_local_report_user_logins_upgrade()
    line 1917 of /lib/upgradelib.php: call to upgrade_plugins()
    line 713 of /admin/index.php: call to upgrade_noncore() 
```

...and then I get a ton of those messages repeated down the page - one for each record.

I've tried deleting the index, and once I found a duplicated local_report_user_logins table that I deleted, but I am unable to figure out why this is happening and what to do to fix it.
Thanks for any help.

**Comment by tbeachy** [comment]
Just checked the table in the db -- there are currently 600k+ records there.  Assuming that there should only be 1 per user, this is 4x times too many.

**Comment by turf212** [comment]
You are right in that the table should simply be a list of all of the users without any duplicates.  It just stores the userid, when they were created, when they first logged in, when they last logged in and the current login count.  The index should have kept that uniqueness on userid.

I've not tested anything with Aurora (MySQL and PostgreSQL) so unsure why this would be.  You could remove the local/report_user_logins and re-install it?  It should go through the eventlog for all of the users and populate itself again.

**Comment by tbeachy** [comment]
Sounds good, thanks.
I was able to eventually get through the upgrade (not quite sure how unfortunately), and of course the table is empty now, but I will remove/re-install as you suggest to get it to run again.

**Comment by tbeachy** [comment]
Closing for now.

**Comment by tbeachy** [comment]
Well, this is strange...
I uninstalled the report/plugin, and in the process, the db went to the upgrade page, which is normal.  But in the process of upgrading the db, I noticed it was taking a long time, so I checked  and noticed that the local_report_user_logins is still there and is actually in the process of filling up again.  How could this happen on an uninstall action?

**Comment by turf212** [comment]
If you uninstall a plugin in Moodle and do not remove the plugin directory, Moodle (and therefor Iomad) will re-install the plugin from scratch.

**Comment by tbeachy** [comment]
Ah yes, I did know that.  Sorry and thanks.
