### ISSUE TITLE
Suspended my Admin account.

### ISSUE THREAD

**Issue by Annesha-maker** [iomad/iomad#1536]
hii ,
I have suspended my Admin account by mistake can u please help me to find any solution to it.
I wanted to revert it to a normal account. Or I wanna Active it.

**Comment by turf212** [comment]
Do you have access to the database?  If so you should be able to change the suspended value for your user record within the mdl_user table to 0.  This reactivates the user account.

What were the steps you took to suspend in the first place?  Was it suspension of a company that the admin was a member of?  Or something else?

**Comment by Annesha-maker** [comment]
Thank you for replying!
Actually my Iomad setup is used by 4 people only I do not who did this.But after my research I came to know that my admin account was suspended.

**Comment by Annesha-maker** [comment]
Thank you so much it has worked for me.
