### ISSUE TITLE
Again bulk upload user

### ISSUE THREAD

**Issue by pozor** [iomad/iomad#1537]
Sorry, I'm experiencing another issue in bulk users upload

Affected branch: IOMAD_39_STABLE
Component: iomad_company_admin
File: blocks/iomad_company_admin/uploaduser.php

Description: if I upload a well formatted CSV to insert or update one or more users, with a custom field in it (ie: CF), I get the error "Incorrect column:profile_field_CF". During the insert the custom field is not set, during the update is set but with the error message.

This is the stack trace:
Incorrect column:profile_field_CF
line 1443 of /blocks/iomad_company_admin/uploaduser.php: call to debugging()
line 690 of /blocks/iomad_company_admin/uploaduser.php: call to uu_progress_tracker->track()

Looking into the code, if there is a custom field, it necessary goes inside line 690:

```
if ($column != 'suspended') {
        $upt->track($column, '', 'normal', false); // Clear previous.
}
```

and in row 1443 the condition 

`if (!in_array($col, $this->columns))`
is always true because $this->columns does not include custom columns:

```
public $columns = array('status',
                            'line',
                            'id',
                            'username',
                            'firstname',
                            'lastname',
                            'email',
                            'password',
                            'auth',
                            'enrolments',
                            'deleted',
                            'department');
```

Thanks!

**Comment by turf212** [comment]
I've tested this on 3.9 and the CSV upload went through fine.  If the profile field is a company one then the profile field name will have the company shortname prepended to the shortname of the profile field.  I.e. if the company is Derick Company and the short name is DC and I create a company profile field with a shortname of mymanager the field for the CSV upload will be profile_field_DCmymanager.  Is this how the profile field is set up?

**Comment by turf212** [comment]
Fixed and pushed issue where profile field not getting populated on new user.  I suspect your original issue is that the actual short name of the profile field doesn't match what is in the CSV.

**Comment by pozor** [comment]
Thx, after the fix the custom fields are saved in the right way. Btw I've still the warning but after your hint I think that is due to my categories configuration.
I've a custom field category for each company and I've created one more category for custom fields shared between all companies (https://github.com/iomad/iomad/issues/998). Is it possible that uploadusers.php allows custom fields only from company categories and not from shared ones?
I'll try to explain with an example:
Company1 (shortname C1)
Company2 (shortname C2)
So we'll have C1 and C2 categories for custom fields.
Then I create a new custom field category, lets say OTHER, with a custom field in it with shortname CF1
If in CSV I call the field profile_field_OTHERCF1, I get an error in the file parsing:
line 498 of /lib/setuplib.php: moodle_exception thrown
line 176 of /blocks/iomad_company_admin/uploaduser.php: call to print_error()
If in CSV I call the field with in the moodle way (profile_field_CF1) it works but I get the error Incorrect column:profile_field_CF1.

Hope it helps and thanks again for effort!

**Comment by turf212** [comment]
custom profile field fields which are in their own category will be available to everyone. The ones in the company category will be available to the company.  In all cases the column for the CSV upload will be the shortname which is under Site administration -> Users -> User profile fields when you edit the custom field (as this doesn't strip of the company short name).
