### ISSUE TITLE
New Course from existing course 

### ISSUE THREAD

**Issue by izharmail** [iomad/iomad#1539]
Is there any way to create an IOMAD course using existing course as template?

**Comment by michalludynia** [comment]
As far as I'm concerned you can do it just like in pure moodle. 
You can create a new course based on existing one as a template and decide which resources should be migrated. 
Just go to administration->courses and you should be able to find that stuff there . I found that option on some moodle forum sometime ago. 
Then you will be able to assign that course to proper companies. 

I'm not sure if that is exactly your case, but just in case I replied :)

**Comment by michalludynia** [comment]
@izharmail you should check it out: https://docs.moodle.org/310/en/Upload_courses

The "templatecourse" field is what you need.

**Comment by izharmail** [comment]
Thanks @Wazowski11

**Comment by turf212** [comment]
ability for company manager to clone the courses they have editing rights to added under 30afcba9d21a9e25c8c58bf78eea3e9eeaca25e4
