### ISSUE TITLE
Show to users only courses they are enrolled in

### ISSUE THREAD

**Issue by michalludynia** [iomad/iomad#1540]
Hi!

I want to prevent my users from displaying all courses in my IOMAD instance. 
Perfectly I want to show them only courses they are enrolled in or they have assigned license.

To keep it simple I just want to that site:
/course/index.php?mycourses=1
would have the same result as that site:
/course/index.php

Is there any possibility to achieve this? I think it's crucial feature in IOMAD concept to fully separate tenants.

**Comment by abhujbal** [comment]
Hi,

You can set below setting on the front page setting option.
front page setting > Front page items when logged in > (from drop down select) Enrolled Courses

**Comment by michalludynia** [comment]
> Hi,
> 
> You can set below setting on the front page setting option.
> front page setting > Front page items when logged in > (from drop down select) Enrolled Courses
> 

@abhujbal Thanks for your reply but that is not my case. I want to control which courses are visible under /course/index.php URL.

**Comment by turf212** [comment]
my courses block does this.  fa53f570a76ebda407d047ac1fdb81ee5507e5a1  Front page course listing will show all courses - showing only enrolled courses on the home page is not even supported by Moodle.
