### ISSUE TITLE
When unenroll educator from a course and enroll him again he will be a student!

### ISSUE THREAD

**Issue by moossaab** [iomad/iomad#1541]
When I assigned user as an educator he will enroll in all courses by default
If I unenrolled him from the course and try to enroll him again he will join the course as a student
Is there any way to enroll him as an educator again?
Note: the course is unlicensed

**Comment by turf212** [comment]
Yes, that is correct.  Using the manual enrol method through the dashboard will assign anyone as a student.  The educator type users are automatically assigned to any appropriate course as the relevant teacher type role when the course is created or assigned to the company.  If you have removed them within the course participants, then you've gone around the Iomad methods and would need to re-add them in the same way.  Company managers can't un-enrol educators, Site admins can.

**Comment by moossaab** [comment]
What is the best way to make company manager responsible for assigning teachers without giving him a sitewide role enable him to see other companies teachers ?

**Comment by turf212** [comment]
Teachers are in the company - there isn't a way to have one teacher in one course and one in another all company educators are all this in all qualifying company courses.
