### ISSUE TITLE
Educator can not create quiz or interactive content

### ISSUE THREAD

**Issue by moossaab** [iomad/iomad#1542]
If I assigned him as an educator from the first place with unlicensed courses he can not create neither a quiz nor interactive content while he can create and edit other activities normally
And if I assigned him using educator license he can create them but can not edit to add a questions or content
any help?

**Comment by turf212** [comment]
The educator should have been given the role client course editor for the course.  Was this the case or were they given the client course access role?

**Comment by moossaab** [comment]
sorry I will appreciate more details
I didn't give company manager course creator role because it is sitewide 
I let company manager add members from his dashboard -> courses -> user enrolments
And assign teacher as educators when creating them
