### ISSUE TITLE
Email notifications in selected preferred language by the user

### ISSUE THREAD

**Issue by abhujbal** [iomad/iomad#1544]
Hi,

If user selected the preferred language as French (I will install the french language pack) then can the system email notification from the LMS will get send in the French language? or what setting i have to do with the Iomad.

What is the use of language option available in front of each email template from the email template section?

**Comment by turf212** [comment]
Once you have installed he French language pack you can go into the email templates for a company and then edit each of the templates for the new language pack (there is a drop down to allow you to choose).  Once you have this, you can save this as a template set which you can then use to overwrite the email texts for all languages to what you have just set for that company.  PLEASE NOTE - This will overwrite for any and all languages, so if you have already customised the English text for one company, this will also be overwritten with what is in the template, so only change those which you haven't already altered.  For those, you need to go back and change the text for the new language pack by hand.

If you click on Manage template sets there is an option to apply a template set to one or more companies.  This saves you from needing to edit each company in turn and selecting the email template set.
