### ISSUE TITLE
How to create a course to be shared by multiple companies?

### ISSUE THREAD

**Issue by ratishsaini** [iomad/iomad#1545]
I am new to IOMAD.

I have a course that should be assigned to all the companies we will create. Each company will have its own separate users.

I created the course through Moodle Dashboard. But when I assign that course to one company then it becomes invisible when I try to assign the same course to another company.

What is the correct way to create a course, so that it can be used by multiple companies with their own managed users?

**Comment by actXc** [comment]
1) go to (your url)/blocks/iomad_company_admin/iomad_courses_form.php?companyid=all
2) in column "is shared" select "open sharing"

now it can be used in all companies.

**Comment by ratishsaini** [comment]
I changed the settings as above but I still have the same issue in 'Manage Iomad Settings'  under "Courses" tab and changed "is shared" to open sharing. But I can only assign this course to one company only. When  I assign same course to another company I still can't see that course to assign.

However, if I create a User through 'Create User' through the 'Users' tab in each company then the course is visible in 'Assign Courses' option in the user creation form.

I am a bit confused. Do I still need to assign the course in each company even though the course is visible in 'Create User' form in each company to assign to users without assigning the course? Then what is the purpose of 'Assign To Company' Tab in 'Courses' tab.

**Comment by shadyshrif** [comment]
I found an option called closed sharing, this exactly does what I wanted. you can assign the course to multiple companies 
<img width="379" alt="Screenshot 2024-05-21 at 15 40 10" src="https://github.com/iomad/iomad/assets/10328735/04a4f146-1d29-48c0-90c9-feec44dd655d">

But my question is, how to make this default for any future course?
