### ISSUE TITLE
After Installation Issues

### ISSUE THREAD

**Issue by FahadKhanChughtai** [iomad/iomad#1547]
I have installed Iomad, with PHP 7.4 Nginx on my local machine.
It gets installed, but when its time to create a company, I put the related information, and this error occurs:
```
`This page should automatically redirect. If nothing is happening please use the continue link below.1
Continue`
```
I have tried all possible documentation and moodle documentation. There is no Iomad documentation available. I am so tired.

**Comment by turf212** [comment]
If you click on continue does anything happen?  The message only appears if you have debug turned on (either via the site or un-commented in your config file) when there is another notice appearing.  This other notice will appear directly above that message.

If the company is not created, what version of Iomad did you install?
