### ISSUE TITLE
Maybe error in provider file in two plugins

### ISSUE THREAD

**Issue by pozor** [iomad/iomad#1549]
In /class/privacy/provider.php for both local_report_user_license_allocations and local_iomad_track there are issues in function export_user_data:

`if (empty($contextlist->count())) {
            return;
        }`
is duplicated

`foreach ($tracks as $ctrack) {
                writer::with_context($context)->export_data($context, $track);`
The foreach has $ctrack as value but inside the loop the var is $track

**Comment by turf212** [comment]
Thank you for this.  They are indeed incorrect.
