### ISSUE TITLE
Edit Users - Search filters for custom fields get wiped when going to next page

### ISSUE THREAD

**Issue by jlizen** [iomad/iomad#1550]
On dashboard -> users tab -> edit users page, we can filter the search results by custom fields. 

This applies to the first page's results, but all custom filters disappear when you click to further pages. 
- If you check the search filter drop down, the input is cleared out. 
- The page count is reset to the unfiltered results' count, though we do load the second (or whichever) page of results that we had clicked on.

Screenshots attached showing an example.

Thanks for your time!
![unnamed](https://user-images.githubusercontent.com/44884346/108603133-263f1100-7374-11eb-81b0-04e8cd6c1e95.jpg)

![unnamed2](https://user-images.githubusercontent.com/44884346/108603135-28a16b00-7374-11eb-832c-362ea7390c3d.jpg)

**Comment by turf212** [comment]
There is a fix for this already pushed to github (unless you are using 3.5 version).  The table for edit users has been completely revamped to use the SQL Table class and it has the standard firstname/lastname first letter filtering too.

**Comment by jlizen** [comment]
@turf212 Sorry about that - I'll get us up to version and double check before raising other issues.

**Comment by turf212** [comment]
No worries at all :)  It's easy done!
