### ISSUE TITLE
Heading color not being displayed

### ISSUE THREAD

**Issue by ThomE2** [iomad/iomad#1551]
Selecting a heading color from the 'Edit company' view doesn't change anything (the header remains white).
I believe the 'bg-white' class is at stake, in 

`<nav class="fixed-top navbar navbar-light bg-white navbar-expand moodle-has-zindex" aria-label="{{#str}}sitemenubar, admin{{/str}}">`

(line 20 within the file iomad/theme/iomadboost/templates/navbar.mustache) 
When I remove this class, the header color changes with the parameters set for each companies.

Am I right to consider it as a issue or is it the normal behaviour ? Is this is normal, how should I change the heading color ?

Thanks

**Comment by turf212** [comment]
Looks like the default header identifier changed in the core Moodle theme.  Can you please confirm which version you are experiencing this on?  3.8/9?

**Comment by ThomE2** [comment]
I am using Moodle 3.9.4 (Build: 20210118)
I am checked out on the commit 7eea12e967c52a582ba84711d6290156eb71d8e0 on IOMAD_39_STABLE

**Comment by turf212** [comment]
The core Moodle themes had made a CSS for a colour to be !important before we added our company changes.  I've made our changes !important too, which will then override the defaults.
