### ISSUE TITLE
Exception - Class 'iomad_approve_access' not found 

### ISSUE THREAD

**Issue by jlb224** [iomad/iomad#1552]
I'm trying to install the latest 3.8 code but I am getting this error when visiting /my. I have deleted the code and DB (its just a local copy) and setup twice but both times same error.

**Comment by turf212** [comment]
Thanks for letting me know.   This was from a merge back from new 3.9 code.  The block lib got a little scrambled.

**Comment by turf212** [comment]
The missing classlib has been added in.  If you download the latest version, you should be good to install again.

**Comment by jlb224** [comment]
Thanks Derick. It has worked. I was just setting up some stuff and noticed a similar error: 

Exception - Class 'block_iomad_approve_access\forms\iomad_approve_access' not found

when I go to Dashboard > User > Approve training events. 

I have no special config here - its a mostly empty install just with one company, one course, and just added one user (other than admin).

**Comment by turf212** [comment]
AH, yes, the form had the old \block_iomad_approve_access class in it's use list and wasn't updated.  Fixed and pushed.

**Comment by jlb224** [comment]
Fixed.
