### ISSUE TITLE
iomad 3.9 user management issues

### ISSUE THREAD

**Issue by hetcxp** [iomad/iomad#1553]
I have found a few problems, as you can see attached, there's no assing department user/manager option inside the companies dashboard.
![image](https://user-images.githubusercontent.com/19639688/109248825-5435b280-77c5-11eb-8234-4c2a7bc2c1f0.png)

then if i try to upload users with a company manager account i get this error:
![image](https://user-images.githubusercontent.com/19639688/109249210-053c4d00-77c6-11eb-8d38-304c765a4ca0.png)

then if i use a department trainer account i get this error: (and the department does exist is the company itself)
![image](https://user-images.githubusercontent.com/19639688/109249756-1d609c00-77c7-11eb-8a0c-55909ef6df86.png)

finally this section is also not working, i think is not showing all roles and is also not allowing me to move people from one side to the other.
![image](https://user-images.githubusercontent.com/19639688/109249915-67e21880-77c7-11eb-84cb-996b7363b6f8.png)

**Comment by turf212** [comment]
We changed the dashboard menu items around slightly in 3.9  The "Assign department users/managers" item is now in the Users tab (as it's a user function)

**Comment by hetcxp** [comment]
thanks for your reply, any recommendation regarding the other two problems (not able to upload users or to assing roles) that i'm also describing?

**Comment by turf212** [comment]
When you are uploading the users, are you selecting a department or are you leaving it as is?  The unknown operand, again, is this just selecting the company manager role with one user?

I'll test with the latest 3.9 code.  There was some recent work around this and it's possible a couple of scenarios were missed in testing.

**Comment by turf212** [comment]
How are you saying they should have a role?  There is no dropdown selector for this on the page and you can't assign a role on upload?  Ignore me - You are doing this as a company manager.

**Comment by turf212** [comment]
Found the underlying error.  WIll fix and come back to you.

**Comment by turf212** [comment]
I've pushed a fix for the underlying issues on the bulk upload and the department users/managers form.

**Comment by hetcxp** [comment]
Great job Derick! I've pulled the update, tested and now is working as expected.
