### ISSUE TITLE
Self-enroll and Completions in Learning Paths

### ISSUE THREAD

**Issue by tbeachy** [iomad/iomad#1555]
Is there any mechanism or trigger that could used to auto-enrol or auto-assign users into Learning Paths without having to be assigned manually by a manager or administrator?

Also, for Learning Paths that are 100% completed, is there a way to generate a certificate of completion?

**Comment by turf212** [comment]
For the enrolment, not at the moment.  If you could describe how that may work I'd be happy to look at how we could achieve this.

Certificates, as an activity, need to live in a course in Moodle (and so therefore Iomad).   You could have the final LP certificate as a certificate within the last course in the LP but it would need to be a dedicated course for the last one and course completion requirements could be tricky (There is a course completion conditional plugin for Moodle module access which could be used as well).  Another possibility is awarding a badge, though that doesn't have the same gravitas as being awarded a certificate.  If we can have somewhere to associate the certificate then we would be most of the way to solving the requirement.

**Comment by tbeachy** [comment]
Thanks.

Enrolment - being able to add an enrolment method an LP maybe?  Could work the same way as course enrolment.  I can't see why the patterns for enrolling, accessing and completing an LP couldn't be just the same as a course.  In other words, you'd just be creating a course with the LP metadata attached to it, but it would essentially function as a course.
Certificate - if the LP became an entity like a course, then creating a landing page and adding a certificate would be trivial.

In the meantime, I've just used the Subcourse plugin, and the coursemeta enrolment method to essentially accomplish what I want.  I can point you to an example if you would like to take a look.  Seems like that would give you the concept as well as provide code that you could re-use.  When I see the way LP course sequencing is added/set up, it looks very similar to the course meta linking mechanism.

**Comment by turf212** [comment]
Auto enrolment is how we have implemented this for clients. Or keep it as self.
