### ISSUE TITLE
Create a default learning path group

### ISSUE THREAD

**Issue by zchermit** [iomad/iomad#1556]
For now, the default learning path group is created only if the user starts managing learning path courses.
local/iomad_learningpath/courselist.php:55
```
$categories = $companypaths->get_categories($id);
$companypaths->check_group($id);
$groups = $companypaths->get_display_courselist($id);
```
Therefore, the system may have an issue when the path exists, and the group doesn't. Maybe the system should check the default group right after the path is created? Maybe here:
local/iomad_learningpath/editpath.php:55
```
// Attempt to locate path
$path = $companypaths->get_path($id);
// Check for default group
$companypaths->check_group($id);
```

**Comment by turf212** [comment]
Don't see why we couldn't have it in both places as it's just a check and create if nothing exists. :)

**Comment by zchermit** [comment]
> Don't see why we couldn't have it in both places as it's just a check and create if nothing exists. :)

Thank you!

In our project we create courses under the learning path programatically. If the path exists without a group, we get an exception: "No groups for learning path id = NN".
