### ISSUE TITLE
Issue using fa icons with an inheriting theme

### ISSUE THREAD

**Issue by ThomE2** [iomad/iomad#1557]
/blocks/iomad_company_admin/block_iomad_company_admin.php
line 282 : 
```
// Get topic image icon
            if (((empty($USER->theme) && (strpos($CFG->theme, 'iomad') !== false)) || (strpos($USER->theme, 'iomad') !== false))  && !empty($menu['icon'])) {
                $icon = $menu['icon'];
            } 
```

This check prevents me from using the fa icons with my theme inheriting from IomadBoost, if my theme name doesn't contains 'iomad'. Isn't it possible to also check parent theme ?

**Comment by turf212** [comment]
It should be by checking what the $PAGE->theme->parents[] array values are as well.  Something like:

`if (((empty($USER->theme) && (strpos($CFG->theme, 'iomad') !== false)) || (strpos($USER->theme, 'iomad') !== false) || in_array('iomad', $PAGE->theme->parents))  && !empty($menu['icon'])) {`

should work?  If you can confirm I'll make the changes to the code.

**Comment by ThomE2** [comment]
I believe in_array checks if the value is contained, so if the theme inherit from 'iomadboost' or 'iomadbootstrap' instead of 'iomad' it shouldn't work

**Comment by jlb224** [comment]
I'm not sure if it helps but we use Lambda and have this:
![image](https://user-images.githubusercontent.com/26649166/110026425-847ed300-7d28-11eb-9540-811c3ffc8de7.png)

**Comment by turf212** [comment]
We decoupled the icons from the theme as an option under 482b1f86f6260b3f13b56575af4c6bfdf5d78b1f
