### ISSUE TITLE
3.9 Iomad Certificate shows Date Issued, even when Completed Date is selected

### ISSUE THREAD

**Issue by tbeachy** [iomad/iomad#1560]
Tried testing this with multiple different certificate options selected, but always the same issue.

I have a test user in a course completed in 2012.  I have a traditional Certificate plugin cert activity and an Iomad certificate activity side-by-side.  Traditional shows 2012 completed date, Iomad shows issued date (incorrect).  local_iomad_track table shows 2012 date for that record.

I would like to use Iomad certificate for certain courses because it shows up in the Dashboard, but I can't use it like this.  Sometimes people come back years after their completion to reprint their certificate, and is HAS to show the date they completed the course, not the date they printed the certificate.

**Comment by tbeachy** [comment]
Never mind, this was my mistake.  Not an issue after all.  It is working correctly.

**Comment by tbeachy** [comment]
Closing.

**Comment by tbeachy** [comment]
I take this back, I believe there is a flaw in iomadcertificate_get_date logic.
The first IF statement deals with timecreated, but ELSE then deals with timecompleted, so it's never reached because $certrecord -> timecreated is not empty. 
If I comment out the ELSE branch, Iomad certs then start printing the correct course_completions date.

```
// Set iomadcertificate date to current time, can be overwritten later
    if (!empty($certrecord->timecreated)) {
        $date = $certrecord->timecreated;
    } //else {
        if ($iomadcertificate->printdate == '2') {
            // Get the enrolment end date
            $sql = "SELECT MAX(c.timecompleted) as timecompleted
                      FROM {course_completions} c
                     WHERE c.userid = :userid
                       AND c.course = :courseid";
                if ($timecompleted = $DB->get_record_sql($sql, array('userid' => $userid, 'courseid' => $course->id))) {
                if (!empty($timecompleted->timecompleted) && $date > $timecompleted->timecompleted) {
                    $date = $timecompleted->timecompleted;
                }
            }
        }
    //}
```

**Comment by ni-ght** [comment]
I came to suggest the same thing. Hope to see this integrated into the code.
Thanks.
