### ISSUE TITLE
disabledmanager / managerdisabled in /local/email/template_list.php

### ISSUE THREAD

**Issue by jlb224** [iomad/iomad#1567]
Hello

Somebody reported some strange behaviour to me in the the /local/email/template_list.php page (some emails not being received when they thought they should). I had a quick look at the code and can see, 
$newtemplate->disabledmanager = 0;
$newtemplate->disabledsupervisor = 0

but the code that updates it to 1 is using
$newtemplate->managerdisabled = 1;
$newtemplate->supervisordisabled = 1;

Later in the sql it uses 
SET disabledmanager = :ajaxvalue

**Comment by turf212** [comment]
Ah.  Yes.  That should all be disabled-thing-.  I've fixed in the code and pushed to the repo.
