### ISSUE TITLE
User Reports give incorrect grade

### ISSUE THREAD

**Issue by fesaner** [iomad/iomad#1568]
Running IOMAD Moodle 3.6.6 (Build: 20190909)
User Reports give an incorrect grade when Natural aggregation is used. The raw grade (points) is reported as a % resulting in an incorrect value. We found that changing the aggregation method to Simple Weighted Mean of Grades then shows the correct grade percent. However, if a user has already completed the course, then changing the aggregation method does not change what is in the report.

Has this been corrected in the most recent version of IOMAD?
How does IOMAD calculate the grade that is shown in the User Report?

Thanks,
Floyd Saner

**Comment by turf212** [comment]
This was fixed in newer versions of the code.  We were storing the raw grade and was changed to store the course grade.  If you update to the newest patch versions it will be sorted.

**Comment by fesaner** [comment]
Thanks! I will have the client upgrade to the most recent version of IOMAD.
