### ISSUE TITLE
Feature request / usability enhancment

### ISSUE THREAD

**Issue by dallenk** [iomad/iomad#1570]
I've been struggling with the way the select / option box displays the company list when there are many companies and sub-companies.. I really like the way the layout looks nested when clicking "Manage Companies" under any company.  I have had to change the long names of each company to make it somewhat nested and sorted in an order that makes it easier to manage.

Is it possible to use OPTGROUP to nest companies in the select/option dropdown on the pages for manage companies, and courses for each company ?

here are a couple screenshots of what I'm trying to explain.
here is the default layout
![image](https://user-images.githubusercontent.com/2725066/111847712-9df65200-88c6-11eb-84c6-c50a1301bf82.png)

Companies and sub companies get lost once you have many of them.

Here is something that would make it so much easier.
![image](https://user-images.githubusercontent.com/2725066/111847895-0d6c4180-88c7-11eb-9689-68c79bbf7315.png)

I can make a really weak attempt to accomplish this, but I am not a php coder by any stretch...  The sub companies could be alphabetical, if they are all nested it really doesn't matter how they are sorted, the grouping is the important part.

**Comment by turf212** [comment]
Is this the dropdown in the dashboard page?  I'll check if that's possible.  It's using the standard Moodle autocomplete form element, which then allows for searching.  Not sure if you can pass an optgroup to it (though logically should be able to).

**Comment by dallenk** [comment]
This is the "Select a company" dropdown on the dashboard, and the same dropdown for the companies on /blocks/iomad_company_admin/iomad_courses_form.php

**Comment by dallenk** [comment]
bump.

**Comment by dallenk** [comment]
bump again?   @turf212

**Comment by dallenk** [comment]
Hi @turf212   is this something you could look at?   I think it would be a really good enhancement if it's possible to do.

**Comment by turf212** [comment]
I've added it to the functions which set up the company selector options.  The only issue is that if it's a child company the selected option has the prepended "--"(s) showing.
