### ISSUE TITLE
possible path bug after self-enrollment into shared courses?

### ISSUE THREAD

**Issue by dallenk** [iomad/iomad#1571]
I have recently noticed a shared course with self-enrolment (i have not tested other methods)  seems to have a path bug.  screenshots and description below

Viewing a course from the available courses shows:
![image](https://user-images.githubusercontent.com/2725066/111939286-1efd4700-8a89-11eb-9d00-da1c75788679.png)

Clicking the link bring to this page, showing this path:
![image](https://user-images.githubusercontent.com/2725066/111939458-9501ae00-8a89-11eb-827e-80234d9ad5e5.png)

once enrolled in the course the path changes:
![image](https://user-images.githubusercontent.com/2725066/111939611-f45fbe00-8a89-11eb-9884-c62eb6ee4dd8.png)

Which brings an error to the user when the company name is clicked on:
![image](https://user-images.githubusercontent.com/2725066/111939656-0fcac900-8a8a-11eb-954b-d0d76c3948a5.png)

**Comment by dallenk** [comment]
for the time being, I've disabled breadcrumbs using css on the theme

**Comment by turf212** [comment]
So the course is within it's own category rather than within the company named category?  Does the company named category still exist on the site?

**Comment by dallenk** [comment]
hi Derek.. I'm not sure what you mean, each company is a category to Moodle isn't it?  I didn't create any additional categories (although I would love to have sub-categories for courses under a company if that's possible)   I didn't specify any additional categories.  Is there something I can screenshot for you?

**Comment by turf212** [comment]
No it was more checking if it wasn't something like that.  It's will be the breadcrumb path somewhere in the navigation lib. I'll have a look.  Thanks for reporting :)

**Comment by turf212** [comment]
This did get fixed.  I cannot find the commit but have tested using classic theme on recent branches.
