### ISSUE TITLE
How to create a company course creator?

### ISSUE THREAD

**Issue by eYinka** [iomad/iomad#1572]
Hello, I can't seem to find a way to allow a company manager create a course.
I would not expect the site admin to be the one creating courses for all the tenants (or is that so?).

I see a role called 'Client Course Editor' but it's not among the list of roles when creating a new company user. I only see the following roles on that form:

User
Department Training manager
Company manager
Company report only

Is there a documentation for this? Or how do I simply create a course creator role under a company.

Quite urgent :(

**Comment by turf212** [comment]
If you add the capability block/iomad_company_admin:createcourse to the company manager role, they will be able to create courses.  Any courses which a company manager creates, they will have gain the company course editor role on, rather than the client course access role.
