### ISSUE TITLE
Persistent error after creating config.php file.

### ISSUE THREAD

**Issue by dosciati** [iomad/iomad#1573]
Persistent error after creating config.php file.
It is not possible to proceed with the installation.
What should I do?
Warning: Unexpected character in input: '\' (ASCII=92) state=1 in /home1/cortex55/modle.cortex6b.com.br/index.php on line 79

**Comment by turf212** [comment]
Sounds like there is hidden special character within your config.php file which is causing your issue.

**Comment by dosciati** [comment]
Thanks.
There were two CFG lines with wrong parameters.
Partially resolved, now we need to set up details of the database.
