### ISSUE TITLE
Lambda theme Iomad menu tab navigation

### ISSUE THREAD

**Issue by izharmail** [iomad/iomad#1576]
Iomad menu tab navigation not working properly with Lambda theme and sometimes no rendering of tab menu items on tab click.
- Is Lambda theme is not compatible with Iomad?
- or there is known solution for the issue of Iomad menu tab navigation with Lambda.

![image](https://user-images.githubusercontent.com/49977312/113058992-8fa61100-91b7-11eb-97a6-967601afe194.png)

**Comment by turf212** [comment]
The block is using Bootstrap 4 opacity fade in and out commands when switching between them.  Lambda still uses Bootstrap 3.  please see #1108 and #1119 for the CSS you need to add to the theme to allow the blocks to display properly.
