### ISSUE TITLE
Language pack development for non listed language in the Language pack list available

### ISSUE THREAD

**Issue by abhujbal** [iomad/iomad#1577]
Hi,

I want to create a language pack for the "Cantonese" language. This language is not listed with the currently available languages with Moodle. 

But in the initial stage, I just want to develop a pack for student UI and not for all the admin side screens. So can you please tell me which PHP files from the (existing English language pack) I need to translate in terms of translating the user side screens in "Cantonese" with the new language pack?

So which PHP files (existing English language pack) should I refer to translate the only student UI (not the admin section) in my language?

Also, how can I add this new language pack "Cantonese" listing with the list where we select the new language, at the time of language pack installation?

Please update.
--
AB

**Comment by turf212** [comment]
The best place to start is with the AMOS system in Moodle where you can create the main Moodle language pack which you can then download.  Once you have the bokes of that you can start adding in lang files for the Iomad plugins.  block/mycourses and block/iomad_company_admin shoudl cover a lot of the strings.
