### ISSUE TITLE
Changing username creation settings when creating a new user via /blocks/iomad_company_admin/company_user_create_form.php

### ISSUE THREAD

**Issue by arryola** [iomad/iomad#1579]
When 'manually' creating users, Iomad always default to selecting the email address as the username, even after disabling this on the page and in enrolment settings for both iomad and stock moodle manual enrolments.

Is there a way to change it so it defaults to first name and lastname + a number? for example:
User: Bart Simpson.
email address used: springfield@show.com
currently generated username: springfield1
preferred username: barsimp1

We are running Moodle 3.9.4 (Build: 20210118)

Thanks in advance

**Comment by turf212** [comment]
Yes.  If you go to site administration -> plugins -> local -> Iomad settings there is an option where you can specify the username rather than using the email address.
