### ISSUE TITLE
Merge with Moodle 3.9.6 planned?

### ISSUE THREAD

**Issue by enrarelloem** [iomad/iomad#1580]
Hi Derick
According to the version.php in the repo Iomad is still on version 3.9.4 of Moodle.
Do you plan to merge with the code of 3.9.6 to fix security issues?

**Comment by turf212** [comment]
There were issues with the 3.9.5 Moodle branch and plugins which talked directly to the calendar.  Latest weeklies fro 3.8, 3.9 and 3.10 have been pushed to repos now.

**Comment by enrarelloem** [comment]
Thanks Derick!
