### ISSUE TITLE
users bulk download produces empty file

### ISSUE THREAD

**Issue by dallenk** [iomad/iomad#1582]
Title says it all, when trying a bulk download from a company, the resulting text or Excel file contains only the header titles, but no user data.

**Comment by turf212** [comment]
Which version are you using (so I can test)?

**Comment by dallenk** [comment]
Latest git version.

**Comment by dallenk** [comment]
just upgraded to the latest. same result.  is there logging that might be useful?

**Comment by turf212** [comment]
It was an issue from allowing users and department managers in multiple departments.  Pushed a fix for it.

**Comment by dallenk** [comment]
tested and working, thank you!
