### ISSUE TITLE
Error on edit users (when A-Z filters set if no user has those firstname + lastname initials)

### ISSUE THREAD

**Issue by jlb224** [iomad/iomad#1587]
Hello, 
I just received this error on the user report on 3.8.7. It appears to be happening when the A-Z filters are set if there is no user present with those initials.

![image](https://user-images.githubusercontent.com/26649166/115776324-e57f6a80-a3ab-11eb-96cd-bfdcba2ecf16.png)

**Comment by turf212** [comment]
Tested the edit users page under 3.8.9 and this isn't showing the issue.

![image](https://user-images.githubusercontent.com/1685229/118662968-5453b600-b7e8-11eb-83f3-df500cc09188.png)

Can you pull the latest version and test again?

**Comment by jlb224** [comment]
Tested and working on 3.8.9. Closing issue.
