### ISSUE TITLE
When to use the iomad OIDC?

### ISSUE THREAD

**Issue by fishfree** [iomad/iomad#1588]
On the page admin/settings.php?section=authsettingiomadoidc. But I don't know when to use this feature? Could someone give me an example please?

**Comment by turf212** [comment]
If company wants to be using Office 365 for their authentication then you want to use the Iomad OIDC plugin.  It's a company aware version of the Moodle OIDC plugin (https://moodle.org/plugins/auth_oidc) and you configure it in exactly the same way except you need to have the company selected from the Iomad dashboard before you can configure for that company.  I.e. to configure for another company - select that company and then configure the plugin.

**Comment by fishfree** [comment]
@turf212 Thank you! I see now.

**Comment by skillableapp** [comment]
Hi !
I'm trying to connect using OIDC to our Azure Portal. The token is indeed returned by Microsoft to the application but this leads to a 500 Inetrnal server error. 
Also, is the "local_o365" plugin required to connect to the Azure portal?
Thanks in advance for your help ! :)
![oidc-iomad-500-error](https://user-images.githubusercontent.com/28006937/193913186-55d21636-5fff-4b8d-8d03-17a3c7acac35.jpg)
