### ISSUE TITLE
Re-allocate a license after enrolment expiry for automatic re-certification?

### ISSUE THREAD

**Issue by 2w3nn3r** [iomad/iomad#1589]
I wonder if it would be possible to provide an option for re-allocating a license after enrolment has expired (according to the setting in the iomad course settings) – i. e. not just after clearing userdata in the user report (for this, you need to have marked the iomad_autoreallocate_licenses). Thus, one could keep re-certifications in cycle without having to clear userdata manually.

I found that kind of an automatic cycle can be managed by combining enrolment expiry and self-enrolments. But I really don’t find a way for licensed courses (which I depend on, as I need to make use of licensed course educator roles too). Perhaps one of you comes up with another solution. Thx in advance.

**Comment by turf212** [comment]
added under #1282 There is a setting in local IOMAD settings which handles this.
