### ISSUE TITLE
Prevent managers from editing user details

### ISSUE THREAD

**Issue by gregosullivan** [iomad/iomad#1591]
Can we prevent managers from accessing the 'edit' function and editing user details (Users > Edit Users > User controls) without restricting access to the entire Edit Users page and the User Report?

**Comment by ghost** [comment]
Currently it seems you can not do this. Access to both the Edit users page and to the Edit option on the User controls menu are controlled by the same capability check for block/iomad_company_admin:editusers. 

However, there is a note under the User control > Edit (/blocks/iomad_company_admin/editusers.php) that says " // TODO: this should be under a separate capability." So, hopefully this may be updated to make that possible.
