### ISSUE TITLE
Lambda theme / iomad dashboard tabs 

### ISSUE THREAD

**Issue by jlb224** [iomad/iomad#1595]
I am using the latest Lambda theme for 3.8, and upgraded locally to iomad 3.8.8 (5th May), and seem to be getting display issues with the iomad dashboard tabs. I have in place (from previous use) what is suggested here (https://github.com/iomad/iomad/issues/1576). I do not recall this being an issue with a download of iomad 3.8 on 27th Feb this year. Do you have any thoughts on what might help to fix?

![iomad388 3](https://user-images.githubusercontent.com/26649166/117531060-84c17600-afd8-11eb-9dd9-4a39cec91501.gif)

**Comment by turf212** [comment]
This is a known issue with the CSS for the older Bootstrap 3 theme and the opacity settings in the CSS not being changed on fade.  See here https://github.com/iomad/iomad/issues/1119 for the lates tlinks to the previous issues which have the fixes.

**Comment by jlb224** [comment]
Hi Derick, 
The above video is what is happening with the following fixes in place already: 

#iomadDashboardTabContent .fade.tab-pane {
	opacity: 1;
}

div.block_iomad_company_admin div.iomadlink_container {
	top: 0px;
	opacity: 1;
}

#mycourses_available_view,
#mycourses_inprogress_view,
#mycourses_completed_view {
	opacity: 1;
}

**Comment by turf212** [comment]
Ah.  Sorry - Should have read the issue!   So it's the icon for manage iomad template settings which is broken/missing. Fixed and pushed.

**Comment by jlb224** [comment]
Yes it is that icon. But its also the juddery flickers when moving between tabs. I have recently upgraded the Lambda theme to the latest release for 3.8 (v: 2021012738). It seems to be since then. I also upgraded at same time to iomad 3.8.8 (around 05 May: v: 20210324)
