### ISSUE TITLE
Suspend / Unsuspend companies issue

### ISSUE THREAD

**Issue by jlb224** [iomad/iomad#1596]
If a company reaches their _Contract end date_ as set in _Companies > Edit company > Advanced company settings_, and is suspended by the system, it adds a completion date, 100% course progress, and a 0% grade (no certificate) to their record in Users > Edit users > [user name] > User report for any unfinished courses including those not started. If the company is then reinstated by unsuspending the company via _Companies > Manage Companies_ increasing the Contract end date to some future date, these values persist.
![image](https://user-images.githubusercontent.com/26649166/117538877-ae41c800-afff-11eb-9205-afa6700da3fa.png)
If the company is manually suspended via _Companies > Manage Companies_ and unsuspended, the user report displays as expected.
![image](https://user-images.githubusercontent.com/26649166/117538742-7fc3ed00-afff-11eb-8d42-b60b94822e7e.png)
This has caused us some issues for users in the production environment for a company who came to end of contract and then asked to be reinstated.

**Comment by turf212** [comment]
These are 2 separate functions.  The first one, $company->suspend() simply suspends the company.  The second one $company->terminate() happens after a period of time of the contract end date and the "Suspend after" value (which probably should be changed to terminate after - as that is a little misleading).

So if the contract end date is 1st September 2022, at that date the company and all of the users are suspended (same as if you suspended the company in the manage companies page).  If you set the Suspend (terminate) after to be 6 months then in 6 months time the company licenses and everything will be set to expire and users cleared from all of the courses and so on.  If that is set to 0 minutes (default) then the company will be terminated immediately.

I'll change the default language to "Terminate after" as that is definitely misleading.

**Comment by turf212** [comment]
Turns out the flow wasn't quite right either.  It would terminate the company first and then suspend the company.  Should suspend the company first and then, if there is terminate after value, terminate all of the company licenses and course interactions.  Updated code pushed to 3.9, 3.10 and 4.0
