### ISSUE TITLE
Role template change not updating in DB

### ISSUE THREAD

**Issue by jlb224** [iomad/iomad#1599]
We have two role templates that are being used across the site. We would like to remove two capabilities from the templates. If I go into role templates > edit and then uncheck these capabilities from each role to which they are assigned within the template, they are not updated within company_role_templates_caps DB table. 
I then removed the capability from site administration > users > define roles. This has removed the capability from being visible on the edit role template page, but the capability is still present in the company_role_templates_caps DB table and assigned to those roles.  
Is this a bug? I think I will need to go into the DB and manually remove these capabilities from company_role_templates_caps unless you suggest otherwise?

**Comment by turf212** [comment]
Which version are you using?  I have a memory of this being fixed and just tested in latest 3.8 and this is working fine.  If you can let me know I can check against that version.

**Comment by jlb224** [comment]
I am using version 20210324 downloaded around 5th May I believe.

**Comment by turf212** [comment]
Can you pull the latest version and try again please?

**Comment by turf212** [comment]
closing as no further comment == already fixed
