### ISSUE TITLE
Created departments do not show up  in 3.10

### ISSUE THREAD

**Issue by 2w3nn3r** [iomad/iomad#1600]
This was working fine in 3.9.  But now, after I created departments for a company, I cannot access them, as they do not show up when clicking on the company in the grey box (in "Manage Departments"). I only see the company name. The little "Drop-Out-Triangle" is missing as well. Although it says there are no departments defined I am not able to create the same department again as "This department shortnme is already in use". 

![Screenshot_2021-05-19 Manage departments](https://user-images.githubusercontent.com/81077756/118844554-5478b200-b8cb-11eb-9bad-049cb56218e5.png)

**Comment by turf212** [comment]
For some reason some of the get_userlevel bts of code to allow for users to be in multiple departments didn't make it's way onto 3.10.  Thanks for reporting.  These have now been added.

FYI - if you go into the database and check the mdl_department table the new department you made will be there but will not have the right parentid for the company department.   If you update this, it will appear again.
