### ISSUE TITLE
3.10 Dashboard does not allow you to create a manager from a user. 

### ISSUE THREAD

**Issue by Blacksheeprules** [iomad/iomad#1601]
3.10 Dashboard does not allow you to create a manager from a user. It only has a department training manager and Company Report only.

**Comment by Blacksheeprules** [comment]
3.10.4

**Comment by 2w3nn3r** [comment]
If I click on the company's name in the grey box (in Department users & managers) the company manager role re-appears in the drop-down menu and can be assigned.

**Comment by Blacksheeprules** [comment]
Thank you very much! It worked!

**Comment by izharmail** [comment]
How to fix this issue. Do we need to press company grey button every time ?

**Comment by ghost** [comment]
This is a bug and is related to this issue: https://github.com/iomad/iomad/issues/1630. It will need to be fixed in the code but for now, the trick from @2w3nn3r works around it.

**Comment by turf212** [comment]
This has since been fixed. Tested in 3.9, 3.10 and 4.0 latest code.  (I'm unsure of the commit but is OK now)
