### ISSUE TITLE
IOMAD course settings.

### ISSUE THREAD

**Issue by pamaher** [iomad/iomad#1602]
I added a course through the site admin (using "restore" from a template course. Normally this works fine. But today, I did it and am not seeing the course in the list of unallocated courses in the IOMAD dashboard, so I can't share it. Not sure what to do. Just to see, I added another course and the same thing happened.

**Comment by ShawnWhy** [comment]
Hi, from what I found out, a course needed to be added to the table "mdl_iomad_courses" to appear in the iomad dashboard

**Comment by turf212** [comment]
If the course is hidden then it also wouldn't have appeared.  This was recently changed to allow users who could see hidden courses be able to see the hidden courses in the menus.
