### ISSUE TITLE
error: Your local changes to the following files would be overwritten by merge:

### ISSUE THREAD

**Issue by dallenk** [iomad/iomad#1603]
i sure hope this is a dumb question, but I can no longer perform a git pull without receiving errors updating.

I'm not very familiar with git and really don't want to screw up a production site by doing it wrong.. I am assuming this is due to the 39 -->  310 code change?

```
root@domain:/var/www/vhosts/domain.ca/iomad# git status
Refresh index: 100% (23076/23076), done.
On branch myiomad39
Your branch is behind 'origin/IOMAD_39_STABLE' by 231 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

```
```
root@domain:/var/www/vhosts/domain.ca/iomad# sudo -u www-data git pull
Updating 0689520ff13..54f8891be27
error: Your local changes to the following files would be overwritten by merge:
        .eslintignore
        .stylelintignore
        .travis.yml
        Gruntfile.js
        admin/cli/mysql_collation.php
        admin/cli/mysql_compressed_rows.php
        admin/environment.xml
        admin/tool/behat/cli/run.php
        admin/tool/cohortroles/classes/output/cohort_role_assignments_table.php
```

but I am unclear on the steps to take now.. I've been reading from google searches and it has been recommended to either commit my changes (I have made no changes)  or stash it for later.

any help is appreciated preferably step by step so I can learn for next time... this is on a production site.

**Comment by dallenk** [comment]
A little more information.. When I installed Iomad and followed the instructions, this may be what the issue is.  The commands I used were in the document:

_git clone https://github.com/iomad/iomad.git (this downloads the repository to a directory called iomad)
cd iomad
git checkout -b myiomad origin/<BRANCH VERSION> (this creates a local copy of the latest <BRANCH VERSION> branch and calls it myiomad e.g. IOMAD_39_STABLE. You don’t need to worry about what this actually means; it’s simply something so that git knows how to reference your code)._



Which leads me to believe I can't upgrade past IOMAD_39_STABLE..  so is it as simple as checking out the 310 branch over the current code?

sudo -u www-data git checkout -b myiomad310 origin/IOMAD_310_STABLE
sudo -u www-data git pull origin IOMAD_310_STABLE


```
root@mydomain:/var/www/vhosts/mydomain.ca/iomad/.git# cat HEAD
ref: refs/heads/myiomad39

root@mydomain:/var/www/vhosts/mydomain.ca/iomad/.git# cat FETCH_HEAD
54f8891be276fcaaa9c33f3881fa78dbd16c8c52                branch 'IOMAD_39_STABLE' of https://github.com/iomad/iomad
b6264c77f14ab75f3e5b642b49d4e18fedac3442        not-for-merge   branch 'IOMAD_25_STABLE' of https://github.com/iomad/iomad
355001dd0e42c0c5e0f24d084cf1f525e2970cfe        not-for-merge   branch 'IOMAD_26_STABLE' of https://github.com/iomad/iomad
a72e545f11f2c29c3abb24d7d8e3b730918974eb        not-for-merge   branch 'IOMAD_27_STABLE' of https://github.com/iomad/iomad
0084e0c0f1aee89fb0cdcdce80a4edd56af39609        not-for-merge   branch 'IOMAD_28_STABLE' of https://github.com/iomad/iomad
3d6206b733bfb9caf38ea6db8fc3f8d887d489b2        not-for-merge   branch 'IOMAD_29_STABLE' of https://github.com/iomad/iomad
b340dbac25bc806e91e2ee7336b8665bece6ad90        not-for-merge   branch 'IOMAD_30_STABLE' of https://github.com/iomad/iomad
2b39a29adaf6c0bfefc262b27021011f2455c4a3        not-for-merge   branch 'IOMAD_310_STABLE' of https://github.com/iomad/iomad
abf96f6a8d58cdbc43604c160a04c841c96107ee        not-for-merge   branch 'IOMAD_31_STABLE' of https://github.com/iomad/iomad
1e35e7ba8e5106ed5484aad12a7f86cfdd2d6beb        not-for-merge   branch 'IOMAD_32_STABLE' of https://github.com/iomad/iomad
d01dd6fbc41618aec4162bc4a4899280c38090c0        not-for-merge   branch 'IOMAD_33_STABLE' of https://github.com/iomad/iomad
e3be589ac3837e853bae7fa75b5ced3d918c858a        not-for-merge   branch 'IOMAD_34_STABLE' of https://github.com/iomad/iomad
b87bf72715e998aedf99568a9f3ec3b4280e9ea0        not-for-merge   branch 'IOMAD_35_STABLE' of https://github.com/iomad/iomad
8dc1e123e2462dfab3f2730e1a2141652058f069        not-for-merge   branch 'IOMAD_36_STABLE' of https://github.com/iomad/iomad
92ba7f40b8436ea2bf9ade274c4b7c15d3c42366        not-for-merge   branch 'IOMAD_37_STABLE' of https://github.com/iomad/iomad
9edada84b34e950497d9e38b7ddd06a085ce1824        not-for-merge   branch 'IOMAD_38_STABLE' of https://github.com/iomad/iomad
ffb2b63ef5c209fbc42310b02a24d618fe9e3a06        not-for-merge   branch 'IOMAD_MASTER' of https://github.com/iomad/iomad
c79de3ad955def86bdb10f071d3ca2eaacc074ce        not-for-merge   branch 'dependabot/npm_and_yarn/grunt-1.3.0' of https://github.com/iomad/iomad
370e89c08ceb3989cb1957f8c7f9e40cccdc43bb        not-for-merge   branch 'dependabot/npm_and_yarn/xmldom-0.5.0' of https://github.com/iomad/iomad
de6898dbe92a4496e7bbb19b1a7237e5b111737a        not-for-merge   branch 'iomad35_nodashboard' of https://github.com/iomad/iomad

root@mydomain:/var/www/vhosts/mydomain.ca/iomad/.git# cat ORIG_HEAD
0689520ff13931c1f4ccb2d15b9ad18402723a60
root@mydomain:/var/www/vhosts/mydomain.ca/iomad/.git#

```

**Comment by turf212** [comment]
If you've changed a file, either contents of the permissions, and you haven't committed them then you get this message when you try to merge in another change which impacts on the same file.  If you haven't changed any files at all then you can set the check for permissions changes to be off.  (I cheat this by editing the .git/config file and changing the value for filemode to be false.  There are proper ways of doing it but I never remember as I do this so rarely).

You can see what you local changes are by running a _git status_ command within your code.  I suspect that it will be permissions and making that change will allow you to checkout the other branches/upgrade.

**Comment by turf212** [comment]
Oh and if you are upgrading rather than patching you need to create a new local branch for the new version :

git pull origin
git checkout -b myiomad310 origin/IOMAD_310_STABLE
php admin/cli/upgrade.php

**Comment by dallenk** [comment]
the filemode didn't help.. i ended up taking a backup moodledata and the sql from my production site and on a separate server
```
sudo git clone https://github.com/iomad/iomad.git
sudo git pull
```
do I "have" to specify the checkout line?  it seems to work fine..  can you see any issues with this in the future?

should it be safe just to treat this as a fresh installation and restoral of the moodledata and sql database and start fresh with:
```
sudo git clone https://github.com/iomad/iomad.git
sudo -u www-data git checkout -b myiomad310 origin/IOMAD_310_STABLE
sudo -u www-data git pull origin IOMAD_310_STABLE
```

If i do this, will i run into the issue again when 311 or anything further than 310 is available?    if I stick to just the clone and pull, will that automagically take the newest branch ??

sorry for the dumb questions, git is very new to me.

**Comment by dallenk** [comment]
After extensive testing I ended up just deleting the iomad directory and re-installing from git.  performed a database upgrade and everything appears stable and up-to-date now.
