### ISSUE TITLE
Disappearing user after role assignment (3.10.4)

### ISSUE THREAD

**Issue by 2w3nn3r** [iomad/iomad#1604]
- Going to Department users & managers,
- choosing "course educator" fom drop down
- trying to assign user
--> user disappears from both lists

Looking in the database in mdl_company_users I see that a new user was created with the same user ID but with wrong department ID.

![grafik](https://user-images.githubusercontent.com/81077756/120066613-91853700-c077-11eb-89ce-99f3978000c7.png)

If I want the user to reappear, I need to delete the doubled record from the db table an set the educator value to 1.
BTW, trying to assign "department training manager" role the same way also creates doubled entry.

However, the whole process works fine, when I click on the company name in the grey box beforehand (company name turns bold)!
The issue might be related to #1601

**Comment by 2w3nn3r** [comment]
I can see the mistake in the url of the form. Without clicking the company's name and having chosen a role it shows deptid=0:
https://..../blocks/iomad_company_admin/company_managers_form.php?deptid=0&managertype=0&showothermanagers=&managertype=3
After clicking company's name it adds deptid=1, which is correct:
https://...../blocks/iomad_company_admin/company_managers_form.php?deptid=0&managertype=3&showothermanagers=&deptid=1

**Comment by turf212** [comment]
Code was added to update all of the records when a user was given a new role for all of the departments they were in.  This wasn't happening and was causing confusion like this.
