### ISSUE TITLE
Exception : Call to a member function rarrow() on null when trying to assign groups

### ISSUE THREAD

**Issue by ThomE2** [iomad/iomad#1605]
Hi, 

Using Iomad 3.9.4, I have this error when trying to select a group different from the standard 'Group for MyCompany' after creating two other groups within a course for this company. It looks like I can't select one of the groups i created, and thus can't assign users to it.

**Comment by ThomE2** [comment]
![Capture d’écran du 2021-06-08 09-17-38](https://user-images.githubusercontent.com/67593304/121140690-6ef2db00-c83a-11eb-8bc9-162616b8c835.png)

**Comment by ThomE2** [comment]
The standard Group for MyCompany is OK
![Capture d’écran du 2021-06-08 09-18-47](https://user-images.githubusercontent.com/67593304/121140839-99449880-c83a-11eb-8d26-9f3baf0b42ee.png)

**Comment by ThomE2** [comment]
The created Group A is not
![Capture d’écran du 2021-06-08 09-19-45](https://user-images.githubusercontent.com/67593304/121140913-b11c1c80-c83a-11eb-9fe9-1257f53bda0e.png)

**Comment by ThomE2** [comment]
Hi Iomad team, since you weren't responding, I took the liberty to investigate myself :)
It was very easy, in file ``blocks/iomad_company_admin/classes/forms/course_group_users_form.php`` on line 175, we find 
``$ouput->rarrow()`` instead of ``$output->rarrow()``

I would be grateful if you could commit a fix for this one ;)

**Comment by turf212** [comment]
fixed in a54639885da1
