### ISSUE TITLE
Company manager able to see all users (including from other companies) !!

### ISSUE THREAD

**Issue by ThomE2** [iomad/iomad#1609]
Hi, 

With Iomad 3.9.4, I am currently trying to use the learning plans. When logged as a company manager, I go into the Learning plan templates tab and click on Modify, then on Add learning plans, in order to assign users to the learning plan template. Then on the page, I am able to see every users on the site, not only the one in the company under which I am logged. 

![Capture d’écran du 2021-06-08 15-47-38](https://user-images.githubusercontent.com/67593304/121196915-286ca300-c871-11eb-8270-4e652286f3b8.png)

Also, I understand that learning plans in Moodle are supposed to work with cohort sync. If there is no cohort in Iomad, how can we use this functionnality (do we have to add manually each user to the learning plan ?) 

I suggest to add a department selection section to the page above, so as to be able to filter users.

**Comment by turf212** [comment]
Tested in current versions - Company manager can only see their own company users.

You can use Learning paths as a feeder for Learning paths now.
