### ISSUE TITLE
User losing access to licensed course when unallocating Course Educator role (3.10.4)

### ISSUE THREAD

**Issue by 2w3nn3r** [iomad/iomad#1610]
Whenever I remove the Course Educator role from a user, a licensed course is no longer accessible by the user - though the user still appears in the license-allocation list. License needs to be reallocated to the user in order to regain access.
Course Enrolments seem to be lost as well.

**Comment by turf212** [comment]
Educators use a different license type from standard users (so we can ensure they get the correct role and so paid for license slots go to actual learners) as well as different course roles on manual and self enrol courses.  So, to ensure that the user is no longer a teacher type in the course and can access it as a learner, roles are completely removed.
