### ISSUE TITLE
Unable to edit course list and assign students in learning path

### ISSUE THREAD

**Issue by sarathp06** [iomad/iomad#1611]
Hi,
As Client administrator, I am unable to edit course list and assign students in the learning path. I am getting the following error:
Error code: nopermissions
* line 1693 of \local\iomad\lib\iomad.php: required_capability_exception thrown
* line 148 of \local\iomad_learningpath\externallib.php: call to iomad::require_capability()
* line 261 of \lib\externallib.php: call to local_iomad_learningpath_external::getprospectivecourses()
* line 81 of \lib\ajax\service.php: call to external_api::call_external_function()

Could you please tell me which permission should be enabled in order to view those pages?
![iomad_issue](https://user-images.githubusercontent.com/54504917/122268928-4c2b8b00-cefa-11eb-9e0b-e1dd3676803d.PNG)

**Comment by davidpesce** [comment]
Confirmed. This is an issue in the latest version of IOMAD.

**Comment by turf212** [comment]
We overhauled the way the IOMAD roles were given permissions.  The one which is causing the above error is iomad_learningpath:manage and the client admin role wouldn't have had it.  We added in role archytypes for all of the IOMAD roles and updated the various files which set up the permissions.  So, if you are having issues like this - you can reset the role and it will likely then work.
