### ISSUE TITLE
Can I change "company" to "school" ?

### ISSUE THREAD

**Issue by moossaab** [iomad/iomad#1614]
and  "company manager" to "school admin" ?

**Comment by ThomE2** [comment]
Hi mosaab, https://docs.moodle.org/311/en/Language_customisation this should be helpful ! :)

**Comment by moossaab** [comment]
Thanks thomaseudes , It works
but what about upgrade? does upgrade affect language customization?

**Comment by ghost** [comment]
No, upgrades do not affect the language customisations. Those are saved locally in the moodledata/lang directory in files.
