### ISSUE TITLE
Custom profile field is not getting uploaded with bulk user upload template 

### ISSUE THREAD

**Issue by abhujbal** [iomad/iomad#1615]
Hi,

Using 3.7 setup. 

Below is my bulk user upload template -
username,password,firstname,lastname,email,lang,profile_field_userposition
Abhijeet,Test@123,abhitatya7,Surname5,aaaa@email51.com,fr_ca,Officer

My custom profile field name is "userposition" and its a menu with the value Officer, Staff, Member 

The user gets created successfully with upload user functionality but the user position field not get set with the dropdown. 
So i have also checked the database but it is not updated with db also. Please suggest what will be the issue.

AB

**Comment by turf212** [comment]
Company custom profile fields have the company shortname as part of them. If you look at Site administration -> Users -> accounts profile fields you will see what the real shortname of this field is and you can use this on the CSV header.
