### ISSUE TITLE
Error Bug in a Select

### ISSUE THREAD

**Issue by pedrolois** [iomad/iomad#1619]
Someone forgot a dot in a Select query: .mn.sectionid

This is the path:
/app/iomad/blocks/iomad_microlearning/block_iomad_microlearning.php

        // Get any nuggets assigned and not completed.
        $mynuggets = $DB->get_records_sql("SELECT mtu.*,mn.name AS nuggetname,mn.cmid,.mn.sectionid,mt.name AS threadname 
                                           FROM {microlearning_thread_user} mtu
                                           JOIN {microlearning_nugget} mn ON (mtu.nuggetid = mn.id)
                                           JOIN {microlearning_thread} mt ON (mtu.threadid = mt.id)
                                           WHERE mtu.userid = :userid
                                           AND mtu.timecompleted IS NULL
                                           ORDER BY mn.name,mtu.schedule_date",
                                           array('userid' => $USER->id));

**Comment by pedrolois** [comment]
It is in version 3.9 and 3.10

**Comment by dmsanchez80** [comment]
#1636 Haaa.. I re-reported this error

**Comment by peterhuppertz** [comment]
Furthermore, the url of the nugget is not returned by the statement, so I changed the select statement to
`SELECT mtu.*,mn.name AS nuggetname,mn.url AS url,mn.cmid,mn.sectionid,mt.name AS threadname`

**Comment by turf212** [comment]
Thanks for this.  Fixing now.

**Comment by turf212** [comment]
Fixed in 3.9/3.10 and 4.0
