### ISSUE TITLE
How can we add Preferred Language filed with New account creation form and New user creation form

### ISSUE THREAD

**Issue by abhujbal** [iomad/iomad#1620]
Hi,

How can I add the "Preferred language" field to Create New Account form from the Login page and the Create New User form from the Iomad Dashboard?  

Can you please update me on the same?

--
AB

**Comment by abhujbal** [comment]
Hi 

Can you please update me on this?

AB

**Comment by turf212** [comment]
The default language for a user is tied to the default language for the user's company. The user can then update their preferred language field in their profile.
