### ISSUE TITLE
Manager/ Reporters disappear from list on course assignment/ enrolment (3.10.4)

### ISSUE THREAD

**Issue by 2w3nn3r** [iomad/iomad#1621]
If I try to assing a  user to a course ("Assign users to course"), who has been given a Company Manager/ Department Manager/ Company Reporter role, the user is no longer listed, neither as "Enrolled student" nor as "potential student" in the company_course_users_form.php.
Yet, looking into the user administration of the course, I see that the enrolment was successful.
If I delete the role, making him an ordinary user, the user reappears in the list as enrolled student.

**Comment by turf212** [comment]
Managers get Client course access roles on courses which are not licensed to allow them to run reports on their users within the course.  If you untick the option _Enrol managers as non students_ under site administration -> plugins -> local plugins -> local IOMAD settings it will allow you to have managers as ordinary users and assign users as Educators who take over this functionality.
