### ISSUE TITLE
How to show moodle iomad company name as sub-domain in url?

### ISSUE THREAD

**Issue by rafaelg21** [iomad/iomad#1622]
Hello, do I need the company to have a subdomain?  

how can iomad do this examples please?

_There are two companies set up to use their own distinct URLs.  **https://testcompany.iomad.org** and **https://anothercompany.iomad.org** Visiting thee links will provide the branding for those companies for login pages and keep the URL throughout for their own users._

Thank

**Comment by ghost** [comment]
You do not have to use this feature. You can have all companies use one url, which is the default.

To set up subdomains for companies, you need to:

1) Create the two subdomains as usual in your webserver
2) In the Iomad Dashboard, Edit a company and set the "Webserver hostname" with the domain name that company should use.


That's it. Users of the company can now log is using that subdomain name. 

Optionally, you can also set a theme for each company in the Appearance settings for the company and if you do, it should show up on the login page for that company.
