### ISSUE TITLE
Deletion task for outgoing email?

### ISSUE THREAD

**Issue by 2w3nn3r** [iomad/iomad#1623]
Is there any deletion task for outgoing iomad mails that are stored in mdl_mails? Just like moodle offers a setting (messagingdeleteallnotificationsdelay) to automatically delete notifications from mdl_notifications...

Just wondering, cause the database could be bloated up and it's privacy issue as the messages contain names and email addresses.

**Comment by turf212** [comment]
Yes - the local email cron task deletes anything which has been sent and is older than 6 months (ish)
