### ISSUE TITLE
Unable to create new entry in user reports (blank page, fatal error) (3.10.4)

### ISSUE THREAD

**Issue by 2w3nn3r** [iomad/iomad#1624]
If I try to add a new entry in the user reports ("Add new entry"-button), a new tab opens, but it is blank.
My local installation shows the following error:

Warning: require_once(C:\xampp\htdocs\eclipse\iomad\local\report_users/lib.php): failed to open stream: No such file or directory in C:\xampp\htdocs\eclipse\iomad\local\report_users\newentry.php on line 27

Fatal error: require_once(): Failed opening required 'C:\xampp\htdocs\eclipse\iomad\local\report_users/lib.php' (include_path='C:\xampp\htdocs\eclipse\iomad/lib/pear;C:\xampp\php\PEAR') in C:\xampp\htdocs\eclipse\iomad\local\report_users\newentry.php on line 27

Seems as if some files are missing.

**Comment by turf212** [comment]
This was fixed in 317a162dff33267477c3a9a9a111bf596ef4fe8f
