### ISSUE TITLE
Clean-up Task

### ISSUE THREAD

**Issue by gregosullivan** [iomad/iomad#1625]
We have fixed an issue where users were not being automatically unenrolled from courses after the enrolment expiry date passed. However, this has created a backlog of users who are still enrolled on expired licenced courses, but there is no clear button in the user report which we can use to unenroll them manually.

Is there a clean-up task built-in that we can trigger which will go back and unenroll all of these users?

![image](https://user-images.githubusercontent.com/71894991/123950700-de706c00-d99b-11eb-81c7-7721e137d280.png)
![image](https://user-images.githubusercontent.com/71894991/123951288-8ab25280-d99c-11eb-9f43-f72f6085a474.png)

**Comment by turf212** [comment]
There isn't a clean up task for this.  If you set the expired licenses to clear on expire:

`update mdl_companylicense set clearonexpire = 1 where expirydate < unix_timestamp();`

then the system will automatically clear down all of the expired user enrolments and course interactions.
