### ISSUE TITLE
Jus ask,  isn't a issue - Create a new group using Upload of users CSV file to company

### ISSUE THREAD

**Issue by claytonccs** [iomad/iomad#1627]
Hello guys,

I'm trying to use a CSV file to import some users and I need to create different groups (by department), the field group<number> doesn't work in the CSV file. How can I do this?

Someone could help me? 

I'm using IOMAD version 3.8.9
Fields in the CSV file: username;password;firstname;lastname;email;institution;phone1;city;group1;course1

Thanks in advanced

.

**Comment by turf212** [comment]
This was fixed in commit 5280439fd651
