### ISSUE TITLE
Completion report

### ISSUE THREAD

**Issue by Werrie09** [iomad/iomad#1628]
Hi there

In my course completion report the progress bar display 100% towards in progress and nothing towards completed or not yest started even though I have learners who have completed the course by doing all the checked activities. The status of all of my users is still only displaying an empty grey bar.

Can someone please assist? 

![image](https://user-images.githubusercontent.com/87529046/125943918-14fc08a0-ec35-4d15-b14f-162a4848814c.png)
![image](https://user-images.githubusercontent.com/87529046/125944506-b541efa1-92f4-4f26-b8fd-b1c6442d48cf.png)

**Comment by turf212** [comment]
Typically this is due to there not being any requirements set for the course completion itself - or the user not matching what these are.  Activity completion does not necessarily equal course completion unless you have set that up.
