### ISSUE TITLE
iomad dashboard icons

### ISSUE THREAD

**Issue by hetcxp** [iomad/iomad#1629]
i'm using the edumy premium theme and the **assign to company** icon from the **users** tab is missing:
![image](https://user-images.githubusercontent.com/19639688/126368656-1317177a-43ec-4f8d-a5e4-5fa0350d9090.png)

also is there a way to **display the iomadboost icons** (shown below) instead of the boost icons?
![image](https://user-images.githubusercontent.com/19639688/126369249-ba8a8d63-d300-484e-84a7-66323c854675.png)

**Comment by brianatkin** [comment]
I was just about to report this same issue. I look forward to when it is fixed as it prevents the use of Boost and themes that use it as a base, in my case New Learning.

**Comment by brianatkin** [comment]
After the latest upgrade (3.10.6), this issue remains:
![image assigntocompany (png) missing on Boost theme](https://user-images.githubusercontent.com/88057289/131898106-6c24f5dc-7460-424f-8441-856dcac93e9c.jpg)

**Comment by izharmail** [comment]
Fix missing icon issue for”assign to company” in following file
/blocks/iomad_company_admin/db/iomadmenu.php 
the **'icondefault' => '',** which is blank to be corrected to **'icondefault' => 'assigntocompany',** 

'assignusertocompany' => array(
                'category' => 'UserAdmin',
                'tab' => 2,
                'name' => get_string('assigntocompany', 'block_iomad_company_admin'),
                'url' => 'company_users_form.php',
                'cap' => 'block/iomad_company_admin:company_user',
                _**'icondefault' => 'assigntocompany',**_
                'style' => 'user',
                'icon' => 'fa-building',
                'iconsmall' => 'fa-chevron-circle-left',
            ),

**Comment by brianatkin** [comment]
Perfect!! Many thanks for the fix.

**Comment by turf212** [comment]
Added fix to 3.9, 3.10 and 4.0 branches.  Again - thanks for the fix!

**Comment by brianatkin** [comment]
Hi Derrick

 

Many thanks.

 

Regards

 

Brian
