### ISSUE TITLE
Issue with Department users & managers after upgrade from 38 to 310

### ISSUE THREAD

**Issue by amirtq** [iomad/iomad#1630]
Hi @turf212 

A couple of days ago, we upgraded from 3.8 to 3.10 and now, we found that in the "/blocks/iomad_company_admin/company_managers_form.php" there is no Company Manager in dropdown menu
Is there any issue in 3.10 ? because it looks the company_managers_form.php is completely changed in IOMAD 3.10

Regards
Amir

**Comment by amirtq** [comment]
I have checked it on a fresh IOMAD 3.10 and same issue is there so it is not related to upgrade
in other hand, rollback is not an option for us because upgrade was 3 days ago and we have around 50K users so a lot of data changes happened in last 3 years make us unable to restore everything from the backup we have made before upgrade :-?

**Comment by amirtq** [comment]
and it looks this is related to this par of code:
if ($departmentid != $parentlevel->id) {
    _**unset($managertypes[1]);**_
    if ($roleid ==1) {
        $urlparams['managertype'] = '';
        $urlparams['deptid'] = $departmentid;
        redirect(new moodle_url($linkurl, $urlparams));
    }
}

**Comment by amirtq** [comment]
I think this part:
if ($departmentid != $parentlevel->id) {

is getting back wrong '$departmentid ' or $parentlevel->id) so it will hit unset($managertypes[1]); then removes Company Manager from dropdown menu

**Comment by amirtq** [comment]
By the way, changing 
if ($departmentid != $parentlevel->id) {
to:
if ($departmentid = $parentlevel->id) {
makes it working


also, commenting entire :
if ($departmentid != $parentlevel->id) {
unset($managertypes[1]);
if ($roleid ==1) {
$urlparams['managertype'] = '';
$urlparams['deptid'] = $departmentid;
redirect(new moodle_url($linkurl, $urlparams));
}
}

makes it working.

**Comment by amirtq** [comment]
however, mentioned change will only add 'Company Manager' option in the dropdown menu but the function of add user as company manager still not works

**Comment by amirtq** [comment]
Hi @turf212 would you please take a look at this issue? I believe its a critical one and needs to be fixed asap.

**Comment by ghost** [comment]
I see this issue too. It seems to be present in latest git pull from today with Moodle build 20210902. This is a really important issue since it means it is not possible in the interface to assign or change company managers atm. 

I was hoping that upload users was a workaround but it seems companymanager is not a system level role so not assignable that way.

When trying to assign a Department training manger I see this in the debugging:

```
Notice: Undefined property: stdClass::$courseid in /srv/www/iomad310a/local/iomad/lib/user.php on line 445

Deprecated: array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in /srv/www/iomad310a/local/email/lib/vars.php on line 157
```

**Comment by ghost** [comment]
See also this issue which is the same, with a trick workaround for the time being: https://github.com/iomad/iomad/issues/1601

**Comment by amirtq** [comment]
> See also this issue which is the same, with a trick workaround for the time being: #1601

Hi there, I confirm that clocking on mentioned gray area works.

**Comment by turf212** [comment]
This has since been fixed. Tested in 3.9, 3.10 and 4.0 latest code.  (I'm unsure of the commit but is OK now)
