### ISSUE TITLE
Issue with IOMAD API in 3.10

### ISSUE THREAD

**Issue by amirtq** [iomad/iomad#1631]
Hi @turf212 

It looks in the 3.10 you added a new field named 'Code' into the company details
the problem is, in the GUI it is optional but in the API "wsfunction=block_iomad_company_admin_create_companies" this value is required and API fails if we dont send the 'code', please make it optional for API or make it required for GUI, any of them will work.
By the way, we have changed our customers portal to send the code in API for new customers.

Regards
Amir

**Comment by turf212** [comment]
Thanks for reporting - fixed in 3.9, 3.10 and 4.0

**Comment by turf212** [comment]
Sorted that too!
