### ISSUE TITLE
Bulk user upload from iomad block is not working from Admin/Company Manager login

### ISSUE THREAD

**Issue by vivek-hashroot** [iomad/iomad#1634]
Hello there,

I'm using Moodle LMS iomad application, when I try to use bulk upload option in iomad_company_admin block,
on csv validation, it sends error message like this. I could upload through Site Admin > Users but cannot do the same from iomad_company_admin block either from Admin login or from Company Manager login. Can someone help me in resolving this issue? Thanks in advance!

![iomad-error](https://user-images.githubusercontent.com/75065375/128493781-47143119-af3e-425b-99ec-a0c3ffe938fa.PNG)

**Comment by amirtq** [comment]
Hi there,
did you test with with Company Manager only or even with site administrator?

**Comment by vivek-hashroot** [comment]
Hi Amir,

I tested with both logins and couldn't upload it via iomad_company_admin block.

**Comment by amirtq** [comment]
is it an upgrade or fresh install ?
what is your current version?
and what is the .php page you are trying to upload CSV?
and consider that you have to do it with a CSV UTF8

**Comment by amirtq** [comment]
also, what columns do you have in your CSV file?

**Comment by vivek-hashroot** [comment]
Hi,
Its an already running moodle project. Version is 3.6.6. I'm using CSV UTF-8 format with username,firstname,lastname,email,sysrole1,course1 columns.

**Comment by ghost** [comment]
You can not use the sysrole column in an Iomad user upload file, since system roles are outside the context of Iomad companies. You will need to use the usual Moodle upload in Site admin > Accounts > Users to assign those roles.
