### ISSUE TITLE
Database error on "manager" role

### ISSUE THREAD

**Issue by moossaab** [iomad/iomad#1637]
At the beginning I thought is Postgresql error, but I try it on MySQL and I had the same issue
It looks like 3.10 version issue

When (manager) role try to "Brows list of users" or "Mange courses and categories" it shows runtime error "Error reading from database"

Debug info: ERROR: column "/" does not exist
LINE 4: ... WHERE cc.path like '' || "/" || ''...
^
SELECT DISTINCT cc.id
FROM mdl_course_categories cc,
mdl_company c
WHERE cc.path like '' || "/" || '' || c.category || "%"
[array (
)]
Error code: dmlreadexception

================

Stack trace:
line 486 of /lib/dml/moodle_database.php: dml_read_exception thrown
line 329 of /lib/dml/pgsql_native_moodle_database.php: call to moodle_database->query_end()
line 920 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
line 403 of /local/iomad/lib/iomad.php: call to pgsql_native_moodle_database->get_records_sql()
line 2750 of /course/classes/category.php: call to iomad::iomad_filter_categories()
line 69 of /user/filters/courserole.php: call to core_course_category::make_categories_list()
line 80 of /user/filters/courserole.php: call to user_filter_courserole->get_course_categories()
line 46 of /user/filters/user_filter_forms.php: call to user_filter_courserole->setupForm()
line 214 of /lib/formslib.php: call to user_add_filter_form->definition()
line 102 of /user/filters/lib.php: call to moodleform->__construct()
line 178 of /admin/user.php: call to user_filtering->__construct()

**Comment by ghost** [comment]
I receive this error too for Moodle system level Managers who are no in any Company in Iomad. This is with MySQL so I think this is not a db specific error but something else.

**Comment by turf212** [comment]
There was a fix for this in commit 02349ff70ca5 Can you please pull the latest patch versions and check again?
