### ISSUE TITLE
Missing code since refactor. No longer shows $fullname .= " (S)" in editusers.php table

### ISSUE THREAD

**Issue by jlb224** [iomad/iomad#1639]
Hello, 
It seems that the code in `iomad/blocks/iomad_company_admin/editusers.php` has been refactored at some point and the below code is now missing. This means that in editusers.php if select 'show suspended users' the suspended users no longer have the (S) after their name. 

It was present in 3.8.5. Missing in 3.8.9.

Missing code: 
`// Is this a suspended user?
        if (!empty($user->suspended)) {
            $fullname .= " (S)";
        }`

Please can this be added back in?

**Comment by turf212** [comment]
Was added back in to 3.9 and 3.10 a while back.  Refactored again as was missing from 4.0 so new commit with change for all branches added.
