### ISSUE TITLE
Error returned in block_iomad_company_admin_assign_users educator cannot be null

### ISSUE THREAD

**Issue by VickiW-nightowl2** [iomad/iomad#1641]
When calling  block_iomad_company_admin_assign_users for a new user regardless of values sent the following error is returned
{
    "exception": "dml_write_exception",
    "errorcode": "dmlwriteexception",
    "message": "Error writing to database (Column 'educator' cannot be null\nINSERT INTO mdl_company_users (companyid,userid,departmentid,educator,managertype) VALUES(?,?,?,?,?)\n[array (\n  0 => 1,\n  1 => 21,\n  2 => 1,\n  3 => NULL,\n  4 => 0,\n)])",
    "debuginfo": "Column 'educator' cannot be null\nINSERT INTO mdl_company_users (companyid,userid,departmentid,educator,managertype) VALUES(?,?,?,?,?)\n[array (\n  0 => 1,\n  1 => 21,\n  2 => 1,\n  3 => NULL,\n  4 => 0,\n)]"
}

Bug is in upsert_company_user

Searching github shows this same issue across different versions. 
 
Our version
$version  = 2020110904.00;              // 20201109      = branching date YYYYMMDD - do not modify!
                                        //         RR    = release increments - 00 in DEV branches.
                                        //           .XX = incremental changes.
$release  = '3.10.4 (Build: 20210510)';// Human-friendly version name
$branch   = '310';                      // This version's branch.
$maturity = MATURITY_STABLE;             // This version's maturity level.

**Comment by LarsDreier** [comment]
blocks/iomad_company_admin/externallib.php
Line 740

Change hardcoded null to false.

if (!company::upsert_company_user($userrecord['userid'],
                                              $company->id,
                                               $userrecord['departmentid'],
                                               $userrecord['managertype'],
                                               false,
                                               true)) {
                 $succeeded = false;
                 $errormessage = "Unable to assign user";
            }

**Comment by francoisjacquet** [comment]
Related issue #1635

**Comment by turf212** [comment]
Thank you for reporting and the fix.  Pushed to 3.9, 3.10 and 4.0 branches
