### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by pedrolois** [iomad/iomad#1642]
Hello Iomad team,

I came across with this message bug when the user is not assigned to a company, I think it would be better control it and display it in a more friendly way.

![imagen](https://user-images.githubusercontent.com/9946406/131961747-6cd3434c-53bb-4705-bfaf-4938dbd54c44.png)

**Comment by turf212** [comment]
Default Moodle debugging looks like this.  This error was fixed in a7fedc96e5b1
