### ISSUE TITLE
Email templates: not all emails sending + other queries

### ISSUE THREAD

**Issue by jlb224** [iomad/iomad#1643]
Hello, I wondered if anybody could help with the use of email templates. I found the following:

1) Not all emails send. E.g. no email is generated for user account created, but an email is generated for user enrolled on course. Only tested on User so far. User created via dashboard > users > create user, and also via admin/user.php. No emails generated. I still need to test the other emails / roles.
2) What do the Toggls mean? E.g. If the template is to notify User they are enrolled on course, what does Enable for Manager mean in that context? Does it mean they will get a cc on that email? 
3) The Toggl 'Enable for Supervisor' - where is the supervisor role? I cannot see it in the Roles to be assigned dropdown. Is it the Department Manager?

For 2, I assume Manager means Company Manager as applied in dashboard > companies > assign company managers / department managers.

The reason I am testing is because on prod these emails do not seem to be sending, so I am investigating locally on a fresh install. 

Any help appreciated.  (Version 3.8.9)

**Comment by jlb224** [comment]
On our staging site we see on the task log,

```
Notice: Trying to get property 'lang' of non-object in /var/www/staging.name.org/public_html/local/email_reports/lib.php on line 512
Sending expiry warning email to namechangeme.co.uk
Sending supervisor warning email for namechangeme.co.uk

email reporting cron completed at Tue Sep 2021 04:09:04
```
But this email is not showing in our diverted email inbox.

**Comment by turf212** [comment]
The toggles for the templates are (from left to right)

First = Template is enabled and will be sent out
Second = Where this is a user email then the manager will be sent out a copy
Third = When a company has a Supervisor profile file set, and this is not empty for the user, then send to this profile field email address.

If you have the first toggle switched off - nothing will be sent out.

**Comment by turf212** [comment]
Sorry - should add - Manager here = any manager above the user within the department structure of the company.  So any company and/or department manager.
