### ISSUE TITLE
editusers.php 14 second page load time

### ISSUE THREAD

**Issue by gregosullivan** [iomad/iomad#1644]
I have found this to be the case on the desktop versions of Chrome and Edge, but not Firefox.

We have replicated this issue on two different servers, so I don't think the issue is server-related.

I'm also unable to search using Ctrl+F on this page.

**Comment by jlb224** [comment]
Any update on this? I can replicate this on Chrome (same site but local version)
![image](https://user-images.githubusercontent.com/26649166/134951026-37bc05cd-da23-41f3-8007-f5de2f86d0f8.png)
on FireFox is less (for same users/page)
![image](https://user-images.githubusercontent.com/26649166/134951088-d1cc4757-57d6-4609-bad8-1c520aab8759.png)
