### ISSUE TITLE
"Department Managers" hidden until company name is clicked.

### ISSUE THREAD

**Issue by dallenk** [iomad/iomad#1645]
Steps.
1.) select a company from Dashboard
![image](https://user-images.githubusercontent.com/2725066/134440420-4f61905e-6789-43dc-9bee-fbd4d6456e6d.png)
-------------------------------------------------------

2.) Users Tab,  Department managers and users
![image](https://user-images.githubusercontent.com/2725066/134440441-efec8bad-ea5c-4308-92d7-10fb3cadaf70.png)
-------------------------------------------------------

3.) "Company Managers" is missing from dropdown
![image](https://user-images.githubusercontent.com/2725066/134440454-d6a38a8b-17a9-4ef7-9c7d-777c06dfec80.png)
-------------------------------------------------------

4.) Click the company name.
![image](https://user-images.githubusercontent.com/2725066/134440479-e1afe4c4-00e4-45c8-aa89-0a4200919ec0.png)
-------------------------------------------------------

5.) "Company Managers" now shows in the dropdown
![image](https://user-images.githubusercontent.com/2725066/134440494-077d7e67-2cca-4da5-b399-72db8ec1483f.png)
-------------------------------------------------------

Unsure when this appeared, I recently updated to the newest code, but have not looked at this section in a while.

Thanks

**Comment by turf212** [comment]
Just checked this on 3.9 , 3.10 and 4.0 latest and this issue is not showing for me. Likely fixed since raised.

**Comment by dallenk** [comment]
Confirmed on my install as well, this has been fixed.
