### ISSUE TITLE
Can't assign open shared courses with all companies. 

### ISSUE THREAD

**Issue by Blacksheeprules** [iomad/iomad#1646]
3.10.7 (Build: 20210913)

I have courses set at open sharing. Some companies are sharing the course, but I cannot assign new companies from dashboard: courses > assign to company. The course is not in the list. This used to work for I have assigned many other companies. When I remove the course from a company that had it then it doesn't show up in the selector to add again. I also have 120 companies. Have I exceeded the limit? Any help with this would greatly be appreciated. Thanks!

**Comment by Blacksheeprules** [comment]
I found the solution. I changed the course to closed sharing.

**Comment by turf212** [comment]
Yes - open sharing means all of the companies automatically get the course, so you don't need to do anything more.  If you want to allocate the course to specific companies you need to set it to closed sharing and then assign it.
