### ISSUE TITLE
Bulk Upload user by General Manager IOMAD3.10

### ISSUE THREAD

**Issue by sheol77** [iomad/iomad#1649]
Hi,
when a "general manager" tries to upload users with a csv file, get an "Invalid Department" error. The problem does not occur when the upload is performed by the administrator. 
Sometimes appears error "Exception - Unsupported operand types".
![Upload-users](https://user-images.githubusercontent.com/29025120/137314182-5af467ee-408d-46d5-9fda-44d07792573a.png)

**Comment by alexlau811** [comment]
Hi I have encountered the same error. I found that it is caused by a typo in the company.php and have made a pull request to fix it.

**Comment by sheol77** [comment]
Thanks for the reply. I also changed the permissions for the general manager role and it worked.
Site administration -> Users -> Permissions -> Define roles -> Company Manager -> block/iomad_company_admin:edit_all_departments -> Allow
