### ISSUE TITLE
Ecommerce/shop error.

### ISSUE THREAD

**Issue by dallenk** [iomad/iomad#1652]
Unsure if this is a Moodle core problem or related to iomad.   using ecomm / shop for a course and choosing invoice presents this error, the invoice is created and emailed.

![image](https://user-images.githubusercontent.com/2725066/140432158-2c638afc-3239-48fb-8ae8-e6d27ecc2e74.png)

**Comment by turf212** [comment]
mark_context_dirty() had been deprecated.  I've pushed a fix for 3.9, 3.10 and 4.0
