### ISSUE TITLE
Additional capabilities granted to parent and child company managers

### ISSUE THREAD

**Issue by esevillo1** [iomad/iomad#1653]
Hi! I'm new to using IOMAD. It seems like the parent or the child company manager cannot do the following:
1) Create a course
2) Create a license
Does the future roadmap include these? Thank you.

**Comment by turf212** [comment]
These are turned off by default for company managers. I would suggest creating a new site role which you can give to your reseller company managers that have the capabilities to do this. For licenses you don't want them to create a license, you want them to split an already allocated license (_Split a license to a child company_). to allow them to create a child company it's _Add a child company_, and for courses it's _block/iomad_company_admin:createcourse_
