### ISSUE TITLE
Setting up o365 SSO - Moodle OIDC vs IOMAD OIDC

### ISSUE THREAD

**Issue by rmeske** [iomad/iomad#1655]
I am using IOMAD 3.9.11.

I understand the IOMAD OIDC plugin is a company aware version of the Moodle OIDC plugin, but I am unable to install the Microsoft 365 Integration Plugin without also install the Moodle OIDC plugin.  Once I install I enabled only the IOMAD OIDC plugin and configured it, but the button for the login does not appear on the login page.  I had to also enable the Moodle OIDC plugin and configure it to get the button.

Is that correct or did the latest version of the Microsoft plugin break it?

**Comment by turf212** [comment]
The other Microsoft integration plugin only works with the standard OIDC plugin and not the IOMAD one.  There is not an IOMAD version of the Microsoft Integration plugin.
