### ISSUE TITLE
possible security issue, able to view other company users.

### ISSUE THREAD

**Issue by dallenk** [iomad/iomad#1656]
hello @turf212   I don't want to post exactly how I did it but would like to see if you can duplicate it.

**Comment by dallenk** [comment]
bump ?

**Comment by turf212** [comment]
If you've allowed site access to user profiles so that they can be seen then it's possible that you did it on the URL by adding the id number.  It's highly likely to be be a role based issue.

**Comment by turf212** [comment]
Added checks to user's profile pages etc to make sure the user accessing the page has the rights to see that users even if they have the capability.  added in cf840db00504
