### ISSUE TITLE
when saving a mail template set, only the first 30 mail settings are stored in the database, 15 are lost

### ISSUE THREAD

**Issue by actXc** [iomad/iomad#1657]
When I try to save the mail templates, only the first page (30) of mail settings is saved.
How to save all 45 mail settings?

Version 3.9.x

**Comment by actXc** [comment]
Even if the perpage value is set to a higher value, it is not used for display.
Workaround: manipulate the "perpage" in the browser url:
`local/email/template_list.php?sort=name&dir=ASC&perpage=45&lang=de&page=0`
 would work

**Comment by turf212** [comment]
It's not quite this (looking at the code) it's only pulling in the templates which already have been already been changed for the company.  This is the code which is doing the lifting here -

```
    // Save the template.
    $templatesetid = $DB->insert_record('email_templateset', array('templatesetname' => $data->templatesetname));
    $emailtemplates = $DB->get_records('email_template', array('companyid' => $companyid));
    foreach ($emailtemplates as $emailtemplate) {
        $emailtemplate->templateset = $templatesetid;
        $DB->insert_record('email_templateset_templates', $emailtemplate);
    }

```
It get's all of the templates which are saved for the company and then stashes them in a different set of tables with the associated template set ID.  If you've only updated the first 30 templates in some way then it will only save those ones.

As a test I created a new company and updated the email templates so there were switched off.

```
mysql> select count(*) from mdl_email_template where companyid=771;
+----------+
| count(*) |
+----------+
|       92 |
+----------+
```

I then saved this as a new templateset and checked how many were saved

```
mysql> select count(*) from mdl_email_templateset_templates where templateset=6;
+----------+
| count(*) |
+----------+
|       92 |
+----------+

```

Which is exactly what I would expect.  This was in IOMAD 3.9.

I do think the templates could be better as with the vagaries of default language (where they are assembled on the fly) and updated language (where they are stored in the DB) doesn't lend itself to searching and new table APIs.  Does need thought.

**Comment by actXc** [comment]
I could not find more than 30 from one company in the database, not depending on the change status. But may be I have some other problem. 

I would love to have a $CFG for the number of mail templates displayed on the first page. This can be set to 45 and it would make it much more useable. Users could faster search for the wanted template in the browser. 
The paging might be something for very slow bandwidth or thousands of templates, but I can not imagine a usecase for paging if the max count is  45 instead of 30.

**Comment by turf212** [comment]
Email templates were completely overhauled in 4.1 away from the wooliness of if template isn't in the list then use default settings - which was causing issues like this
