### ISSUE TITLE
Department Manager cannot upload users by CSV - Invalid department

### ISSUE THREAD

**Issue by skillsetltd** [iomad/iomad#1658]
I'm hitting a problem with an Iomad deployment that I thought would have been core functionality. If you set up a company with one department, assign a user to be the department training manager for that department, and then have that user attempt to upload a user CSV, the upload is permitted from the Iomad dashboard but will fail with "Invalid department". This is even though the user is the DTM for that department and only has that department available to them on the upload, and even though there is no other department being specified in the CSV.  If you do this upload as an administrator, with the department selected, it works fine.

I have played around with the role definitions a bit to see if there was anything missing but there don't appear to be any capabilities on the Moodle side or on the Iomad side for Company Department Manager that are obviously wrongly unset or prevented.

I have tracked the path it's going through in the code down to the if-then-else in `blocks/iomad_company_admin/uploaduser.php` lines 894-937.

In my case I'm dropping into the else clause (despite the fact that the user's department is set in the Moodle user record). The department is found in the IF statement on line 917 and as a result I end up calling `can_manage_department()`.  That function is defined in `/local/iomad/lib/company.php` from line 2418. There seem to be at least two sets of problems to my untrained Iomad eye in this function definition.  

Firstly an array `$subhierarchytree` is defined but the loop appears to add items to a variable called `$subhierarchies` instead. Outside the loop, it reverts to checking `$subhierarchytree` as an array, but we've not added anything to it inside the loop, so it's empty, and so the function always returns false.

Secondly, inside the loop, the current element is assigned to `$userhierarchylevl` which seems to be a typo, as inside the loop it's referring to `$userhierarchylevel`. With developer logging on, there is quite a lot of "trying to get property 'id' of non-object" noise in the error logs, some of which may be attributable to this.

So I'm a bit confused really as to what's going on, I could try to fix some of these issues which I think are typos or what have you, but I don't know why I'm ending up in this part of the code anyway, and whether that's expected. I've tried what I think are the obvious fixes but I'm still getting a `false` out of this function in this code branch which is causing the "Invalid department" message.

It is entirely possible I am just configuring something wrong, but I don't think that's the case. Happy to work through this with someone if that is helpful.

**Comment by turf212** [comment]
This was fixed in commit ccafe75a657e back in  Feb 26 15:22:19 2021  in 3.9 but looks like it didn't get pushed to 3.10.  It's now been pushed to 3.10 and 4.0
