### ISSUE TITLE
IOMAD 3.10+

### ISSUE THREAD

**Issue by Blacksheeprules** [iomad/iomad#1659]
Hi,

I create an IOMAD group from the dashboard for a The Main Company and Course 1 called Group A. Then when I assign course groups and pick Course 1 and Group A, I get an error. 

Exception - Call to a member function rarrow() on null[](url

![Capture](https://user-images.githubusercontent.com/33699631/145938233-e79e5c44-e979-472e-9fe3-c9507c640f95.PNG)

**Comment by turf212** [comment]
Thanks for reporting fixed and pushed to latest code.  Sorry for the delay.
