### ISSUE TITLE
Unable to assign grade reports capability to company manager

### ISSUE THREAD

**Issue by nileshnpathade** [iomad/iomad#1663]
I am using IOMAD 3.8, I am trying to assign capability to company manager role following capability
gradereport/grader:view 
gradereport/history:view
gradereport/outcomes:view
gradereport/overview:view
gradereport/singleview:view
gradereport/user:view
moodle/grade:view
moodle/grade:viewall
moodle/grade:viewhidden
mod/assign:viewgrades

STILL not any report accessible to company manager role.
please suggest if anything is missing 

Thank you 

Regards,

**Comment by nileshnpathade** [comment]
Please help me for this issues.

**Comment by turf212** [comment]
The company manager role isn't the place to be assigning those capabilites as the company manager role is in the System context and these need to be assigned in the Course context.  If you have not unticked the option "Enrol managers as non students" under Site administration -> plugins -> local -> local IOMAD settings then you company managers will be given the Client course access role on any non licensed course available to the company and the Client course editor role on any course they have created themselves.

Please note - giving access to things like moodle/grade:viewall will allow the company manager to see all of the grades on that course for all of the users.  Including across groups, which will break the shared courses separation of users.  So - please keep this in mind when changing roles.
