### ISSUE TITLE
Sort order in course select box on Iomad Create User form

### ISSUE THREAD

**Issue by bschantz** [iomad/iomad#1664]
The select form element on the create user page at /blocks/iomad_company_admin/company_user_create_form.php has unpredictable sorting behavior.

Initially, it's *almost* sorted alphabetically by course name.
![image](https://user-images.githubusercontent.com/2325253/147282416-53d7975f-e271-4ddc-b925-bc0215c5a5d6.png)

Entering some search text results in what seems to be an unsorted state. Clearing the search text leaves it unsorted.

The latter behavior can be seen on the Iomad demo site.

**Comment by turf212** [comment]
Would be better to use the newer form fields for this (e.g. auto complete) - for a start it would make the form nicer.

**Comment by turf212** [comment]
Updated this to the Autocomplete form type as is already being used on the Enrol users page for 3.9, 3.10 and 4.0
