### ISSUE TITLE
Need help in creating a company from API

### ISSUE THREAD

**Issue by anirudh74** [iomad/iomad#1665]
I have tried to create a company from API but I am getting 
{
    "exception": "invalid_parameter_exception",
    "errorcode": "invalidparameter",
    "message": "Invalid parameter value detected"
}
error
Following is the api request I have used

&wsfunction=block_iomad_company_admin_create_companies&moodlewsrestformat=json&companies[0][name]=Name&companies[0][shortname]=short&companies[0][code]=api&companies[0][city]=hyd&companies[0][country]=IN

**Comment by turf212** [comment]
You were missing the customcss field.  I've updated the code to make this optional.
