### ISSUE TITLE
departmentid in event company_user_assigned::create

### ISSUE THREAD

**Issue by pozor** [iomad/iomad#1667]
Hello

Affected branches: IOMAD_39_STABLE (this is the one I tested)
File: local/iomad/lib/company.php
Function: upsert_company_user
Row: 1418

Description: the event company_user_assigned::create doesn't have the information about the departmentid that is going to be assigned. After the feature I39_Multi_depts (users can be assigned to multiple departments) the departmentid isn't anymore unique so it isn't possibile to retrieve it from event. Is it possible to add the departmentid information in the array $eventother?

Ie
From this:
`// Create an event for this.
        $eventother = array('companyname' => $company->get_name(),
                            'companyid' => $company->id,
                            'usertype' => $managertype,
                            'usertypename' => $managertypes[$managertype]);
        $event = \block_iomad_company_admin\event\company_user_assigned::create(array('context' => $systemcontext,
                                                                                      'objectid' => $company->id,
                                                                                      'userid' => $userid,
                                                                                      'other' => $eventother));`

To this:
`// Create an event for this.
        $eventother = array('companyname' => $company->get_name(),
                            'companyid' => $company->id,
                            'departmentid' => $departmentid,
                            'usertype' => $managertype,
                            'usertypename' => $managertypes[$managertype]);
        $event = \block_iomad_company_admin\event\company_user_assigned::create(array('context' => $systemcontext,
                                                                                      'objectid' => $company->id,
                                                                                      'userid' => $userid,
                                                                                      'other' => $eventother));`
                                                                                      
Thanks in advance

**Comment by turf212** [comment]
Yes.  Done - sorry for the wait on this.
