### ISSUE TITLE
Getting Error while assigning a user to a company

### ISSUE THREAD

**Issue by anirudh74** [iomad/iomad#1668]
Hi,
I am able to see the following error
_**"error/an error occurred whilst communicating with the server"**_
I was trying to assign a user to a company, below is the debug info

Debug info:
Error code: An error occurred whilst communicating with the server
$a contents:
Stack trace:
line 92 of /lib/classes/session/manager.php: core\session\exception thrown
line 793 of /lib/setup.php: call to core\session\manager::start()
line 27 of /config.php: call to require_once()
line 24 of /blocks/iomad_company_admin/company_users_form.php: call to require_once()

**Comment by turf212** [comment]
I've tested this with latest versions of 3.9/3.10 and 4.0 without issue.  Can you please upgrade and check?
