### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by sotoco** [iomad/iomad#1669]
Unable to find how to add course categories in IOMAD? I went to IOMAD dashboard, it has how to add courses but does not include categories. Maybe I miss something. Is there something I could do to fix this?

**Comment by turf212** [comment]
Courses are automatically put into the company course category when they are created via the dashboard.  You can create sub categories in the manage courses and categories section of the site administration menu.  IOMAD will treat any sub category as belonging to the company for checking if users should see the courses or not (as long as the course is assigned and visible to the company too.  Simply adding a course to a category doesn't add it to a company).
