### ISSUE TITLE
Delete a company throw an error

### ISSUE THREAD

**Issue by malekdev97** [iomad/iomad#1670]
In the iomad on this URL, you can delete a company
**/blocks/iomad_company_admin/company_list.php**
but it throws an error 

Debug info:
Error code: invalidcategoryid
×Stack trace:
line 494 of \lib\setuplib.php: moodle_exception thrown
line 282 of \user\profile\definelib.php: call to print_error()
line 89 of \blocks\iomad_company_admin\company_list.php: call to profile_delete_category()
×Output buffer: NULL

**Comment by VFXpro** [comment]
Any luck? I badly need to delete numerous IOMAD companies created in batch via API...

**Comment by VFXpro** [comment]
What is the API method you are using?  I don't see anything about "delete"...
![image](https://user-images.githubusercontent.com/44643864/150392360-acaeb9b5-21ff-4de9-99c0-463d92d73ab2.png)

**Comment by malekdev97** [comment]
My apologies for the late response,

Have look at these lines of code which are responsible for showing and deleting a company.

navigate to this blocks/iomad_company_admin/company_list.php.
to see it in action.

I faced some issues when I tried to delete a company.

If anyone has faced the same issue, please let me know. so I can close this Issue. 

happy coding.

**Comment by VFXpro** [comment]
Thanks.   Is there an API to do it versus using the UI. I'm talking about **_thousands_** of companies...

**Comment by VFXpro** [comment]
Also, the link you provided works... but where is the icon to navigate to such page?  In other words, how can someone navigate to such page without a hyperlink?

![image](https://user-images.githubusercontent.com/44643864/171696629-f5296b65-51b6-41b2-9e1d-bab783ee7203.png)

**Comment by malekdev97** [comment]
unfortunately, there is no hyperlink to navigate to this page, I have just found this page while surfing the code. 
I'm not sure how to use the API for deleting a company. As you said in API documentation there's no API for deleting a company.

I'm not suggesting deleting a company from Database, unless that company does not has any users or category on it.

**Comment by turf212** [comment]
This was very old functionality which never really worked - so has been left off. Much like "deleting" users in a Moodle site - there could be too much interlinked data so the best you can do at the moment is suspend (or repurpose by renaming it) a company.

**Comment by malekdev97** [comment]
I really appreciate your response.
