### ISSUE TITLE
Client administrators can't edit course completion settings due to a fatal error

### ISSUE THREAD

**Issue by abias** [iomad/iomad#1671]
Steps to reproduce:
* Login as admin
* Create a new user U
* Go to site administration roles -> Users -> Define roles and allow the 'Client Course Editor' role to be assigned in the system context
* Go to site administration roles -> Users -> Define roles, edit the 'Client Administrator' role and add the 'moodle/course:view' capability so that Client Admins can view courses without being enrolled
* Assign the global role 'Client Administrator' to the user U
* Assign the global role 'Client Course Editor' to the user U
* Logout

* Login as user U
* Create a new company with standard settings
* Select this company on the Dashboard
* Create a new course C within the organization
* Go to course C
* Open the course cog icon
* Open the course completion settings page
* Save the page without changing anything

Expected result:
* The course completion settings are saved

Actual result:
* A fatal error is thrown and the user is redirected to the Dashboard.
* The user can't change the course completion settings of the course at all
* The error says:
Exception - Argument 1 passed to core_course_list_element::__construct() must be an instance of stdClass, null given, called in [dirroot]/course/classes/category.php on line 1641
Stack trace:

    line 97 of /course/classes/list_element.php: TypeError thrown
    line 1641 of /course/classes/category.php: call to core_course_list_element->__construct()
    line 131 of /course/completion_form.php: call to core_course_category::search_courses()
    line 214 of /lib/formslib.php: call to course_completion_form->definition()
    line 80 of /course/completion.php: call to moodleform->__construct()

The error can be traced back to a strange comment in https://github.com/iomad/iomad/blame/IOMAD_39_STABLE/course/classes/category.php#L1639-L1642 which is specific to IOMAD and does not exist in Moodle upstream. 
Removing these four lines makes the course completion settings page functional again. However, we are unsure if this will break something else.

This is especially strange as the affected function search_courses() is about course search and does not do anything with course completion. Thus, I suspect that the above error is a side effect of another, unrelated modification in IOMAD.

**Comment by turf212** [comment]
This will be linked to an earlier bug where if the array of courses after filtering for the company returned an empty list it threw an error.  The commit it was fixed in was f09b8bc16168195ac8e8fcc16488b40a35de6b08
