### ISSUE TITLE
Cannot delete an IOMAD empty company...

### ISSUE THREAD

**Issue by VFXpro** [iomad/iomad#1672]
There is no UI to delete a company and no API.  Can we simply delete the records in the DB?
I fail to understand why we can't delete mistakes or empty companies with no users, courses or content related to it.

**Comment by malekdev97** [comment]
Please have look at this issue which is near to yours. 
https://github.com/iomad/iomad/issues/1670

**Comment by turf212** [comment]
This was very old functionality which never really worked - so has been left off.  Much like "deleting" users in a Moodle site - there could be too much interlinked data so the best you can do at the moment is suspend (or repurpose by renaming it) a company.
