### ISSUE TITLE
Iomadboost CSS regression with Atto and the content bank

### ISSUE THREAD

**Issue by abias** [iomad/iomad#1673]
I encountered an Iomadboost CSS regression in IOMAD 3.9.11+ and probably some earlier minor versions and later major releases which affects Atto and the content bank. It is related to issue #1491 and commit 62678a330613c05049946101bb2c85f896855b1c, but it is basically caused by theme_iomadboost being an somehow outdated fork of theme_boost.

There are two fundamental problems:

1a. https://github.com/iomad/iomad/blob/IOMAD_39_STABLE/theme/iomadboost/scss/moodle.scss is not in sync with https://github.com/iomad/iomad/blob/IOMAD_39_STABLE/theme/boost/scss/moodle.scss, but it must be. The imports for atto and the content bank are missing.

1b. https://github.com/iomad/iomad/tree/IOMAD_39_STABLE/theme/iomadboost/scss/moodle is missing contentbank.scss which is in place upstream on https://github.com/iomad/iomad/tree/IOMAD_39_STABLE/theme/boost/scss/moodle.

2. As a result, atto styles were not shipped to the browser. To overcome this issue, the style/moodle.css sheet was added on https://github.com/iomad/iomad/blob/IOMAD_39_STABLE/theme/iomadboost/config.php#L29. But this is wrong. style/moodle.css is a fallback CSS file which containes a shipped version of the whole, unmodified Moodle Core CSS. I think this solution was integrated in Moodle Core in MDL-59261. You must not include that CSS sheet as a theme sheet. Besides many other side effects, it may overwrite some of your theme's RAW SCSS and will especially turn the theme brand color unusable.

For everyone who is affected, this is a quick fix to overcome the regression:

Apply this patch:
```
diff --git a/theme/iomadboost/config.php b/theme/iomadboost/config.php
index e4b3117091c..917d69816f0 100644
--- a/theme/iomadboost/config.php
+++ b/theme/iomadboost/config.php
@@ -26,7 +26,7 @@ defined('MOODLE_INTERNAL') || die();
 require_once(__DIR__ . '/lib.php');
 
 $THEME->name = 'iomadboost';
-$THEME->sheets = ['iomad', 'moodle'];
+$THEME->sheets = ['iomad'];
 $THEME->editor_sheets = [];
 $THEME->editor_scss = ['editor'];
 $THEME->usefallback = true;
```

And this patch:
```
diff --git a/theme/iomadboost/scss/moodle.scss b/theme/iomadboost/scss/moodle.scss
index d79cd5a2e2d..df180754ade 100644
--- a/theme/iomadboost/scss/moodle.scss
+++ b/theme/iomadboost/scss/moodle.scss
@@ -14,6 +14,7 @@ $breadcrumb-divider-rtl: "◀" !default;
 @import "moodle/blocks";
 @import "moodle/bootswatch";
 @import "moodle/calendar";
+@import "moodle/contentbank";
 @import "moodle/course";
 @import "moodle/drawer";
 @import "moodle/dashboard";
@@ -34,7 +35,6 @@ $breadcrumb-divider-rtl: "◀" !default;
 @import "moodle/templates";
 @import "moodle/undo";
 @import "moodle/debug";
-@import "moodle/expendable";
 @import "moodle/sticky-footer";
 @import "moodle/popover-region";
 @import "moodle/tool_usertours";
@@ -42,3 +42,4 @@ $breadcrumb-divider-rtl: "◀" !default;
 @import "moodle/print";
 @import "moodle/modal";
 @import "moodle/layout";
+@import "moodle/atto";
```

And run this command:
cp -p theme/boost/scss/moodle/contentbank.scss theme/iomadboost/scss/moodle/

As this regression affects multiple release branches, I won't create a pull request and will leave it up to the maintainers to fix all supported branches.

**Comment by jgdk** [comment]
Hello,

Does your additions also likely resolve the missing icons in the Atto Editor like this picture shows (Lambda theme in Iomad 3.10):

https://www.screencast.com/t/MeV6l5fH

And patching with git only works if I have used it from when I initially installed the Iomad site, is that correct?

**Comment by abias** [comment]
> Does your additions also likely resolve the missing icons in the Atto Editor like this picture shows (Lambda theme in Iomad 3.10):

I have to admit that I do not know.

> And patching with git only works if I have used it from when I initially installed the Iomad site, is that correct?

You do not necessarily apply the patch which I have listed above with Git.

**Comment by turf212** [comment]
Fork is old indeed.  It was from original 3.9 build.  Thanks for the patches I've applied them to the current themes.
