### ISSUE TITLE
Cannot add company managers from users

### ISSUE THREAD

**Issue by BLFN21** [iomad/iomad#1675]
In the **Department users & managers** menu, when clicking the Add button to add users to the company managers tab it does nothing.

Please help for fixing this.

**Comment by turf212** [comment]
Company managers can only be added when the uer is in the top level (company) department only.  You need to select the company manager role and then add the user to the department.  This page got more confusing when users could be in multiple departments.  We've added functionality in 4.0 which alows you to change the user's role and departments within the edit users page instead.

FYI if you select different departments and add the user to them you are not removing them from the old departments you are adding them to the new department _as well as_ the old department.
