### ISSUE TITLE
security issues in code - 

### ISSUE THREAD

**Issue by dallenk** [iomad/iomad#1676]
@turf212  - can you please contact me? I've found two security issues i would like to send for you to look into please.

**Comment by Fydon** [comment]
Hi @sgvfr. According to the [security policy](https://github.com/iomad/iomad/security/policy), it would be best to submit them via [this form](https://moodle.org/security/report/), unless they are iomad specific I guess.

**Comment by dallenk** [comment]
> Hi @sgvfr. According to the [security policy](https://github.com/iomad/iomad/security/policy), it would be best to submit them via [this form](https://moodle.org/security/report/), unless they are iomad specific I guess.

correct, they are iomad specific

**Comment by turf212** [comment]
Sorry I missed this - day job has been mental of late. Can you please send them to derick [at] e-learndesign [dot] co [dot] uk ?

**Comment by dallenk** [comment]
> Sorry I missed this - day job has been mental of late. Can you please send them to derick [at] e-learndesign [dot] co [dot] uk ?

no problem.. I will dig out my notes and re-create them.   I have since disabled access to other iomad managers to the sections.  It might take me a couple days to remember what they are.

**Comment by turf212** [comment]
Any news on this??

**Comment by dallenk** [comment]
> 

Hey Derek sorry.   Yes I will replicate it and send steps.  I've disabled the options on my production site but my dev server should show the same.

**Comment by turf212** [comment]
Issues identified and fixed.
