### ISSUE TITLE
demo.iomad.org/ returns "Error reading from database"

### ISSUE THREAD

**Issue by ryukochan** [iomad/iomad#1679]
I clicked on the demo site link on this page at approximately 12:25PM today: https://www.iomad.org/demo-site/ 

And saw the following error:

<img width="978" alt="Screen Shot 2022-02-16 at 12 28 51 PM" src="https://user-images.githubusercontent.com/19441341/154332338-6aa598ce-4873-4021-812d-c5ecac327bea.png">

**Comment by turf212** [comment]
Was sorted a while back.  Thank you for reporting.
