### ISSUE TITLE
unable to upload users as company manager nor as training manager

### ISSUE THREAD

**Issue by hetcxp** [iomad/iomad#1680]
Hi there,

i'm trying to upload users with a company manager account and i keep getting this error:

![imagen](https://user-images.githubusercontent.com/19639688/156637631-8f1f4ee3-fa77-47ed-a4c6-12ac2659154b.png)

then if i change the role to traning department manager i get this error

![imagen](https://user-images.githubusercontent.com/19639688/156637824-519e690e-cf02-4f56-b13b-864f234d4b25.png)

**Comment by transang1981dhv** [comment]
you may turn on the debug mode in moodle, there are some mistype of variables. If you need the PHP file, send me an email via  sangtx@vinhuni.edu.vn

**Comment by turf212** [comment]
Assigning the role at the site level for company managers and other IOMAD roles will not work.  They will get the capabilities but they will not be marked as a company manager in the IOMAD tables, which means that many other things will break.

Upload the users first and then assign them the roles within the IOMAD dashboard.  If you are using pre 4.0 code you need to use the Department users & managers page.  If you are using 4.0 you can do this within the edit users page as well (and it's a much more intuitive way too).
