### ISSUE TITLE
Upload Users with Enroltimestart and Enrolperiod

### ISSUE THREAD

**Issue by imlask** [iomad/iomad#1681]
Hi,

I have tried to upload users as a company manager using csv with enroltimestart1 and enrolperiod1 columns (as per [Moodle documentation](https://docs.moodle.org/310/en/Upload_users#Enrolment_fields) but the attempt fails with error reading temporary file.
![image](https://user-images.githubusercontent.com/45632627/156774519-879a4cc7-e5a7-4e21-bafd-fdd2e85e5e44.png)

Here is the csv I used:
`username,firstname,lastname,password,email,course1,enroltimestart1,enrolperiod1
ales.valenta,Ales,Valenta,pwd123,ales.valenta@example.com,Minecraft Modding,2022-04-01,28`

**Comment by peterhuppertz** [comment]
I think the problem is `enroltimestart1` which is not a valid field for the upload and therefore the upload throws an error. It's also not mentioned in the document link you sent.

**Comment by imlask** [comment]
Thank you for checking the issue. The [link](https://docs.moodle.org/310/en/Upload_users#Enrolment_fields) navigates to the "Enrolment fields" section of Moodle's "Upload users" documentation v. 3.10. The section lists the `enroltimestart1` field in available fields:

![image](https://user-images.githubusercontent.com/45632627/157431754-44bef81f-75b5-42aa-8bbd-a536513f1001.png)

Description says:
**enroltimestart#** may be used to set the enrolment start time, for each course. If not explicitly set here, the enrolment start time is set to be today. To set a date: "2021-02-15" and to set a date and time "2021-02-15 15:30"

Is it not a valid field for iomad?

**Comment by iberactiv** [comment]
Check this answer, it might help: https://github.com/iomad/iomad/issues/1251#issuecomment-1252534646

**Comment by turf212** [comment]
The upload here is meant to be a more simplified one for Company managers and not for site admins (who know how Moodle works - so will miss some of the functionality).  If you know the consequences - you can still use the Moodle tools.
