### ISSUE TITLE
Reset scorm attempt

### ISSUE THREAD

**Issue by natas123** [iomad/iomad#1685]
Hello
We are working with iomad 3.5.4 and we have a somewhat strange behavior that occurs only in certain students, it is random and we cannot find what the problem may be, let's see if someone can give us a clue.

When a student makes a scorm unit and completes it by setting the status to passed when she re-enters it, she resets the status and sets it to incomplete and starts from the beginning. We have seen in the moodle event log that these logs are fired:

When it does it right the sequence is this:

**Event name**			**Description**

**2nd launch**	
Sco launched			        The user with id '3' launched the sco with id '2801' for the scorm with course module id '185'.
Course module viewed		The user with id '3' viewed the 'scorm' activity with course module id '185'.

**1st launch**
Course viewed			        The user with id '3' viewed the course with id '27'.
Submitted SCORM status	The user with the id '3' submitted the element 'cmi.core.lesson_status' with the value of 'passed' for 
                                                the attempt with the id '1' for a scorm activity with the course module id '185'.

But when he does it wrong, the sequence is this one:

**Event name**			**Description**	

2nd launch
Sco launched			        The user with id '3' launched the sco with id '2801' for the scorm with course module id '185'.

1st launch
Submitted SCORM status	The user with the id '3' submitted the element 'cmi.core.lesson_status' with the value of 'passed' for 
                                                the attempt with the id '1' for a scorm activity with the course module id '185'.

As I have told you, this happens randomly and we are going crazy to find out what the problem is.

Regards, and thank you very much

**Comment by turf212** [comment]
This sounds like a bug with the Moodle SCORM activity itself.  Moodle 3.5 is no longer supported (supported versions are 3.9, 3.11 and 4.0) 3.9 is the LTS version and I would suggest that this would be where to go next.  4.1 will also be LTS but not due out till November for Moodle and January for IOMAD.
