### ISSUE TITLE
Required Moodle version [2021051700] 

### ISSUE THREAD

**Issue by vivomeetings** [iomad/iomad#1686]
I cannot install several themes. 
Error message

Install plugin from ZIP file
Validating theme_xxxx ... Error
[Error] Required Moodle version [2021051700] 
Installation aborted due to validation failure

**Comment by malekdev97** [comment]
you need to change the date2021051700 in the theme version.php file. 
try to put 2022060900 or increase the date number. 
I hope it will work with you.
