### ISSUE TITLE
MissingParam when sorting by last accessed in Edit Students.

### ISSUE THREAD

**Issue by AC-Education** [iomad/iomad#169]
![error](https://cloud.githubusercontent.com/assets/10127152/5937453/a68546c8-a6e7-11e4-9627-ef347d147e83.png)
Received MissingParam error when sorting by Last Accessed after suspending user.

Please refer to image below for full error details.

http://i.imgur.com/TQr437M.png

**Comment by turf212** [comment]
Will get this looked at.

**Comment by turf212** [comment]
This is a duplicate of #178.  Fixed in that one.
