### ISSUE TITLE
iomadcertificate report - PDF download link for saved certificate is broken when course shortname is prefixed by white space - MOODLE_39_STABLE 

### ISSUE THREAD

**Issue by ni-ght** [iomad/iomad#1690]
Hello,

To reproduce the problem:

1) Create a new course, set short-name as having a leading white-space, e.g. " demo";
2) Add an iomadcertificate activity, set "Issue Options > Save Certificates" => "Yes";
3) Open the iomadcertificate activity as a student, obtain the certificate;
4) Open the iomadcertificate activity as an admin, view the issued certificate report;
5) The link for downloading the certificate PDF file is broken.

I enclose a screen-shot.

<img width="512" alt="err" src="https://user-images.githubusercontent.com/26959486/168335463-e8d9a0dc-5607-4101-984a-4746a2faa2a1.png">

Many thanks.

**Comment by enrarelloem** [comment]
Are you sure it is only with a leading space?
I also have broken links to PDFs. However, I can't find a pattern.
[https://github.com/iomad/iomad/issues/1682]
Something is rotten in the certificate plugin.
@turf212 Could you help, please?

**Comment by ni-ght** [comment]
> Are you sure it is only with a leading space?
> I also have broken links to PDFs. However, I can't find a pattern.
> [https://github.com/[/issues/1682](https://github.com/iomad/iomad/issues/1682)]
> Something is rotten in the certificate plugin.
> @turf212 Could you help, please?

Hello,

leading whitespaces in the course shortname is definitely an issue, as the shortname is used in constructing the certificate's file name. Of course there could be other issues.

I pulled records from the "mdl_files" table in order to inspect the filename. You could try the same.

The certificate issue id in this query can be seen in the download link URL.

```
select
    *
from
    mdl_files
where
        component = 'mod_iomadcertificate'
    and filearea='issue'
    and itemid = (certificate issue id)
```

Hope this helps.

**Comment by enrarelloem** [comment]
> I pulled records from the "mdl_files" table in order to inspect the filename. You could try the same.

>The certificate issue id in this query can be seen in the download link URL.

Thanks for the hint! I'll check that out.

**Comment by turf212** [comment]
This is tied to a Moodle bug - (https://tracker.moodle.org/browse/MDL-71250) as you should not be able to save a course shortname with a leading (or trailing space).
