### ISSUE TITLE
typo in report_user_license_allocations/index.php

### ISSUE THREAD

**Issue by dallenk** [iomad/iomad#1692]
error:  Exception - Call to undefined function get_sring()

line 278:  $table->is_downloading($download, format_string($company->get('name')) . ' ' . get_sring('pluginname', 'local_report_user_license_allocations'), 'user_report_license_allocations123');

should be "get_string"

**Comment by turf212** [comment]
fixed in commit 80f72ee9856ae0ff5c6330b74b83bb2d5fa561c7
