### ISSUE TITLE
Small bug in Reports - User license allocations report (Iomad 310) 

### ISSUE THREAD

**Issue by atljohnsen** [iomad/iomad#1696]
Error thrown - Exception - Call to undefined function get_sring()
In line 278 of /local/report_user_license_allocations/index.php
There is a missing t - it should read function get_string()

Tnx for a great-great job with Iomad

**Comment by atljohnsen** [comment]
Sorry - this one has been reported earlier.

**Comment by turf212** [comment]
fixed in commit 80f72ee9856ae0ff5c6330b74b83bb2d5fa561c7
