### ISSUE TITLE
Misplaced string 'trainingevent_not_selected' in local/email/lang/en/local_email.php

### ISSUE THREAD

**Issue by abias** [iomad/iomad#1699]
In local/email/lang/en/local_email.php, the very first line is saying:

```
//trainingevent_not_selected<?php
```

This line was introduced in https://github.com/iomad/iomad/commit/500dfe299632bf02eeaaacb79e216ffb848e459d, most probably due to a copy & paste error.

As this string is _before_ the opening PHP tag, the string is shown in the browser every now and then when the page loads.

**Comment by turf212** [comment]
fixed in commit 8f368ba960db1d3b4110de57c8c94c6508915fa6
