### ISSUE TITLE
Mislabeled Drop Down Box

### ISSUE THREAD

**Issue by AC-Education** [iomad/iomad#170]
![dwxmmhh](https://cloud.githubusercontent.com/assets/10127152/5937485/f0dc4370-a6e7-11e4-95de-91ab4930d178.png)

Within Manage user enrolments the drop down box on the left hand side is labeled as "Potential Courses" instead of "Enrolled Courses"

http://prntscr.com/5y2sn4

**Comment by turf212** [comment]
Good spot.  I'll get this sorted and push a fix.

**Comment by turf212** [comment]
fixed in 2.8
