### ISSUE TITLE
An apology

### ISSUE THREAD

**Issue by turf212** [iomad/iomad#1700]
I just want to apologise for not being on top of issues being raised here as much over the last few months.  IOMAD development has never stopped, but for various reasons, we needed to focus on issues which had been raised by our clients rather than the community at large.  Thankfully, circumstances have now changed for the better, and we've been able to get back up to speed.  We've released IOMAD 4.0 (ahead of Workplace) and I will be keeping a close eye on any issues and questions raised over the next few days to address anything which might be outstanding.

I would also like to take this opportunity to thank all of you for your patience and support.  The project has changed a lot since Moodle 2.0 and I aim to continue to build on this and the IOMAD community as a whole.  Some insight to the future:

1. Building a documentation wiki/knowledge base has been on my radar for a long time but I now have access to content authors (who can take my bad writing and make it easily understandable);
2. Use cases will be created for functionality, and freely available (of course) on the e-Learn Design website; and
3. We'll be finding another forum for issues as Git does not lend itself to the answering of questions as well it does the reporting of bugs.

All in all, we feel very positive for IOMAD's future, and we hope you'll stick with us, wherever it may end up :)

**Comment by dallenk** [comment]
Thank you for all your hard work on this project.  If I knew a fraction of what you did.. I would help..

**Comment by dallenk** [comment]
Sorry @turf212 I hate to have to ask this but can you include some directions on how to upgrade from a previous stable, to a new stable?   I'm up-to-date on IOMAD_310_STABLE but every time a major upgrade comes out I spend at least 3-4 hours reading the install guide, then screwing up twice before wiping it all out and managing to restore from a backup iomad/moodledata to a fresh git install then upgrade

I'm not super familiar with how git works and how to checkout over an existing clone.  Can I suggest some instructions in a readme that can be put somewhere for us idiots :)   ?

for example. Here is where I am now:
```
# git log
commit 75fd8b95eb1745ac476c724752fbc6d063183d13 (HEAD -> myiomad310, origin/IOMAD_310_STABLE)
Author: Derick Turner <derick@e-learndesign.co.uk>
Date:   Tue Jul 19 12:41:36 2022 +0100

```
is it as easy as 'cd iomad', then "git checkout -b myiomad310 origin/IOMAD_400_STABLE"  ?? 
I should have used a more generic id such as just 'myiomad' perhaps

will future "git pull" continue to use IOMAD_400_STABLE until a new checkout is done??

Thanks, and sorry if the questions are basic I'm not dumb I swear!! hahah

**Comment by turf212** [comment]
The step we use for this kind of work is as follows:

INITIAL install

git clone https://github.com/iomad/iomad.git
mv iomad public_html
cd public_html
git checkout -b IOMAD_400_STABLE origin/IOMAD_400_STABLE

This gets you an IOMAD 4.0 branch which follows the main IOMAD_400_STABLE branch so going back into the public_html directory and running git pull origin will bring down all of the fixes since you last did this.  (You may need to run the Moodle upgrade command php admin/cli/upgrade.php if there have been code changes - best to run in case anyway)

To get a newer version of the code to upgrade your site with (e.g. when 4.1 is released) you then just need to do this:

cd public_html
git pull origin   (The new branches will be shown as being available)
git checkout -b IOMAD_410_STABLE origin/IOMAD_410_STABLE
php admin/cli/upgrade.php 

The checkout -b will change the current branch to the new branch keeping any additional plugins you may have installed in place.  I.e. anything which git status shows in the Untracked list.  You can then run the Site administration -> Plugins -> plugins overview and check for available updates and then install available updates.

Obviously you want to back up your site before you upgrade it.

Hope this helps!
