### ISSUE TITLE
Company Managers cannot edit users from Iomad dashboard.

### ISSUE THREAD

**Issue by encodecreate** [iomad/iomad#1704]
When a user with the company manager role goes to /blocks/iomad_company_admin/editusers.php , instead of a list of users, they receive the error "Exception - Call to a member function get_userlevel() on null."

This issue does not apply to site admins, and does not seem to apply on other pages that call this function.

**Comment by turf212** [comment]
Thanks for reporting. Needed some global variables added the the column.
