### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by madizongo** [iomad/iomad#1707]
Hello, 
I get this error  : 
Screenshot : https://www.screenpresso.com/=38dsd
Iomad version : 402
Moodle : 402
DB : MariaDB
PHP : 7.4
Site url : https://m.oalms.net/

**Comment by turf212** [comment]
Just installed a clean site with latest IOMAD 4.0, MariaDB, PHP 7.3 and that worked without issue.

I've switched over to PHP 7.4 and tried again and it also worked.

Did you clone the whole IOMAD repository and use the IOMAD_40_STABLE branch for the install?  Or have you taken the plugins and put them on top of Moodle?  The IOMAD release contains all of the Moodle code as we need to make some core code changes for the multi-tennacy parts to work.  You don't need to do anything with Moodle code at all.

**Comment by madizongo** [comment]
Ok. Thanks you very much. Le 12 août 2022 15:40, Derick Turner ***@***.***> a écrit :
Just installed a clean site with latest IOMAD 4.0, MariaDB, PHP 7.3 and that worked without issue.
I've switched over to PHP 7.4 and tried again and it also worked.
Did you clone the whole IOMAD repository and use the IOMAD_40_STABLE branch for the install?  Or have you taken the plugins and put them on top of Moodle?  The IOMAD release contains all of the Moodle code as we need to make some core code changes for the multi-tennacy parts to work.  You don't need to do anything with Moodle code at all.

**Comment by madizongo** [comment]
It works fine. Thanks you for this solution. 
https://www.screenpresso.com/=udoee
