### ISSUE TITLE
Course Completion Report shows 0 users as not started even though there are some uses that have not started. 

### ISSUE THREAD

**Issue by Blacksheeprules** [iomad/iomad#1709]
I the IOMAD dashboard under Reports, Course Completion Report shows 0 users as not started even though there are some uses that have not started. In the Course Summary there are users that have no percentage in their status and have clearly not started or completed any of the course. Is there some way to get the course summary to show the number of users that have not started. Right now it shows the completed and still in progress correctly but not started is always 0. 

We are using [3.9.2 (Build: 20200914)]

Thank-you for any help on this issue.

Regards,

Mark

**Comment by turf212** [comment]
Moodle "course started" is not necessarily as intuitive as you think.  The IOMAD reports take the course to be started from enrolment (much of corporate training is 15 minutes, single activity for completion type training so this makes more sens in that regard).  Moodle requires a users to complete one of the course completion requirements before they are marked as started.  In the single activity type courses this would have people enrolled on the course with potentially several failed attempts at the activity being marked as not started.  Hence Started = Enrolled.

**Comment by Blacksheeprules** [comment]
Thank-you for the response. I appreciate the power and usefulness of your
software. Keep up the great work!

Mark
