### ISSUE TITLE
 Iomadboost CSS regression with the content bank

### ISSUE THREAD

**Issue by abias** [iomad/iomad#1711]
Unfortunately, #1673 was solved improperly.

You oversaw one important step in my issue description in #1673 which said:

> And run this command:
> cp -p theme/boost/scss/moodle/contentbank.scss theme/iomadboost/scss/moodle/

Your commit in ec7dbe88e91981a8b26ff46abf328a2e599b44bb did not copy this file.

That's why the content back layout is currently broken on theme_iomadboost:

![grafik](https://user-images.githubusercontent.com/1092118/187452897-df366841-c65a-424f-b633-5226bb5e82f2.png)

(The screenshot is from IOMAD 3.9.16 and I would like to ask you to fix this regression from 3.9.x upwards).

Thanks!

**Comment by turf212** [comment]
Ah - It was only added for the 4.0 branch.  I've added these from the current boost themes in each of the 3.9 and 3.10 branches.

**Comment by turf212** [comment]
commits were 6a134504191384ca41ecc85fdb7966637f1dd91a and 7348dd84581eacf438de702ef23bce7114c0c8b7
