### ISSUE TITLE
Subdomain for different companies not working

### ISSUE THREAD

**Issue by Maaqt** [iomad/iomad#1714]
Hello, 

I'm trying to use the multi-tenancy of iomad for having a different url for each company. like company1.domain.com and company2.domain.com. However so far i have no succes in this. i filled in the different urls in the hostname & domain field for each company. and tried to place a wildcard on the dns server( A : *.domain.com : Ip-adres). however nothing seems to work. does anybody maybe have some suggestions. ? it's build on a hostinger server

Thanks in advance

**Comment by turf212** [comment]
We have an article on that here - https://www.iomad.org/documentation/administration/how-to-set-up-different-urls-per-tenant/

You only need to set up the hostname (the company domains is for something else) and it's not the URL it's just the hostanme part.

**Comment by Maaqt** [comment]
Hi, Thanks for helping out!

The link you send opens on iomad.org unfortanetly. I also tried it just with the hostname company1.domain.com > also without succes. Do you know another place where to find more information or steps to follow.   If a client fills in on the browser company1.domain.com the page doesn't exist. if a client of company1 logs in on domain.com he will be redirected tot to company1.domain.com but gets a 404 error.  so i think it is something with the dns server settings. do you you mayeb have some info on that?

again thanks,

**Comment by dallenk** [comment]
I have 30 subdomains working flawlessly on my installation.  most current 4.x code.
each company must use a valid subdomain in the "Webserver Hostname" field of the Advanced Company Settings.

![image](https://user-images.githubusercontent.com/2725066/189741650-9f83f08f-31f3-424d-a5f0-c376845eab94.png)

Your DNS must be pointing to the IP of your server (or a CNAME works fine as well)  wildcard records also work.   Stripped down example below

```
sgadmin@ns:/var/lib/bind$ cat domain.com.INTERNAL.hosts
$ttl 3600
domain.com.   IN      SOA     ns.domain.com. admin.domain.com. (
                        2022090901
                        3600
                        600
                        1209600
                        3600 )
domain.com.			IN      NS      ns.domain.com.
domain.com.			IN      A       111.222.333.444
www.domain.com.		IN		CNAME	domain.com.
sub1.domain.com.	IN		CNAME	domain.com.
sub2.domain.com.	IN		CNAME   domain.com.
sub3.domain.com.	IN		CNAME   domain.com.
sub4.domain.com.	IN		CNAME   domain.com.

```

**Comment by turf212** [comment]
Sorry - we were just sorting out the knowledge base and I'd linked to it before it was live. 
 Document is up and available here - https://www.iomad.org/documentation/documentation/administration/how-to-set-up-different-urls-per-tenant/

**Comment by Maaqt** [comment]
Thanks. It finally worked on a different server. The server i was working on didn't support ssl certificates on wildcard records.  I still have one more question.  If you look @ the example @turf212 send me. you will see that the url will be company1.domain.com on the branded login page and when you are logged in. However when i type in the url https://company1.domain.com my installation reroutes it to https://domain.com/login/index.php?id=2&code=company1 

Anyone an idea why this is?

Thanks in advance!
