### ISSUE TITLE
Manager unable to Create & Edit course issue.

### ISSUE THREAD

**Issue by ghost** [iomad/iomad#1715]
Create and Edit course option is not available in manager profile.

**Comment by turf212** [comment]
This is not switched on by default.  If you add the capability -

[Create a course]
block/iomad_company_admin:createcourse

to the company manager role at the site level then all of the company managers will be able to create courses. (Remember you can disable that at a company level using the restrict capabilities menu item in the IOMAD Dashboard)

Any courses which are created by company managers they are then given the role Client course editor (which is based on the teacher role) at a course level which allows them to edit these courses.
