### ISSUE TITLE
not a bug / question:   Calendar event problem

### ISSUE THREAD

**Issue by dallenk** [iomad/iomad#1718]
This might be a Moodle design, not an IOMAD issue, but is there a way to create an event on a company calendar that all users can see but NOT attached to a course?   I like to post upcoming external training opportunities on the calendar, but it is not a course we are presenting.  It seems events can be created only if they are assigned/attached to a course.

**Comment by turf212** [comment]
Moodle requires that calendar events are tied to a user or a course.  A work around for this is to have a course for the company that everyone is enrolled on (you can make it one of the auto-enrol course) which is used for company announcements and other information.   You could then use an announcement forum to publish or you can put an event into the course calendar.
