### ISSUE TITLE
Is it possible to have one student in two different companies?

### ISSUE THREAD

**Issue by jmartin-pukkas** [iomad/iomad#1719]
Hello,

We'd like to know if there is a way to have one user in two companies, so he/she can be on both at the same time.

It is realistic that a student having been enrolled on a course from one company ant then goes enrolled in a course from a second company.

If it isn't possible currently, it is there any workaround? Is it a future enhacement?

Thanks and regards

**Comment by turf212** [comment]
As of IOMAD 4.3 - yes.
