### ISSUE TITLE
Organisation logo not showing in Iomad theme

### ISSUE THREAD

**Issue by nick69g** [iomad/iomad#172]
When adding/editing an organisation in "Appearance" you have the option of adding in a Company Logo. In v2.7 this worked fine with the chosen logo being displayed. In 2.8, rather than the logo being displayed once uploaded, the filename of the logo graphic is displayed instead; and when Save changes is made;it does not show the logo in the top-right as expected.

**Comment by turf212** [comment]
Thanks for logging this Nick.  I can confirm that this is definitely a bug.  I will get this looked at ASAP.

**Comment by nick69g** [comment]
Hello

Thanks for coming back to me to clarify this - I was slightly concerned that the install had not gone quite right and although having tried it a couple of times, the logo issue remained.

Any ideas how soon this would get fixed? I assume I could continue with 2.7 and then upgrade to an updated version when fixed?

Regards.
Nick

[cid:4B4119FA-53D4-4AFD-9BB0-B2BA3FF9234B]
Nick Garrod MCIPD
eLearning Development Manager

nick.garrod@cloudsustainability.commailto:nick.garrod@cloudsustainability.com
T. 0845 287 3850 DD. 0203 102 6948
M. +44 (0)7712 331 789 Skype ID. nickg69
www.cloudsustainability.comhttp://www.cloudsustainability.com/

[cid:E2CF250B-8057-4745-918A-1F8E1A69CA70] @CloudPioneerhttp://twitter.com/cloudpioneer

[cid:F0C23E4F-9A25-486F-B1F6-3F54F4923868]
The information contained in this e-mail is for the exclusive use of the intended recipient(s), or person responsible for delivering this information to the intended recipient, and may be confidential, proprietary, and/or legally privileged. Inadvertent disclosure of this message does not constitute a waiver of any privilege. If you receive this message in error, please do not directly or indirectly use, print, copy, forward, or disclose any part of it. Please immediately delete the e-mail plus all copies and notify the sender or call 0845 287 3850.
Cloud Sustainability Limited makes reasonable attempts to exclude any virus, or any other defect which might affect any computer or IT system, from this e-mail and any attachments but it is the responsibility of the recipient to ensure that they are virus free and we accept no liability for any loss or damage arising in any way from their receipt or use.
Cloud Sustainability Limited is registered in England, company no. 06863577, registered address Leeds Innovation Centre, 103 Clarendon Road, Leeds, LS2 9DF.

Please think about the environment before printing this e-mail.

**Comment by turf212** [comment]
Hi Nick,

this has been fixed and pushed.

**Comment by nick69g** [comment]
Thanks. What do you mean by Pushed?

**Comment by nick69g** [comment]
Hello Derek

Is the updated version available to download please? I've downloaded 2.8 on GitHub and this version still has the bug.

Regards.
Nick

Nick Garrod MCIPD
eLearning Development Manager

nick.garrod@cloudsustainability.commailto:nick.garrod@cloudsustainability.com
T. 0845 287 3850 DD. 0203 102 6948
M. +44 (0)7712 331 789 Skype ID. nickg69
www.cloudsustainability.comhttp://www.cloudsustainability.com/

[cid:226F0B3F-A2A3-437D-BF02-8EC9BB4AB55D] @CloudPioneerhttp://twitter.com/cloudpioneer

[cid:2EF1F87D-DEC8-44C0-AEE3-93B7C96EE7F7]
The information contained in this e-mail is for the exclusive use of the intended recipient(s), or person responsible for delivering this information to the intended recipient, and may be confidential, proprietary, and/or legally privileged. Inadvertent disclosure of this message does not constitute a waiver of any privilege. If you receive this message in error, please do not directly or indirectly use, print, copy, forward, or disclose any part of it. Please immediately delete the e-mail plus all copies and notify the sender or call 0845 287 3850.
Revise Limited makes reasonable attempts to exclude any virus, or any other defect which might affect any computer or IT system, from this e-mail and any attachments but it is the responsibility of the recipient to ensure that they are virus free and we accept no liability for any loss or damage arising in any way from their receipt or use.
Revise Limited is registered in England, company no. 06863577, registered address Leeds Innovation Centre, 103 Clarendon Road, Leeds, LS2 9DF.

Please think about the environment before printing this e-mail.
