### ISSUE TITLE
API broken, not able to create companies by api request

### ISSUE THREAD

**Issue by LarsDreier** [iomad/iomad#1720]
#1665 solution broke the api in commit 5946276

You added a pre-tag to function create_companies in externallib.php, probably for testing purposes.
`echo "<pre>";print_r($params);die;`

With this line you're no longer able to create companies by api as every requests ends in a die;

**Comment by turf212** [comment]
Thanks for pointing that one out.  Fixed and pushed.

**Comment by LarsDreier** [comment]
Hey turf212, thank you for the repair.
5946276 references the 39_STABLE, your fix only applies to 400_STABLE.
As we're still using 3.9 it would be great if you could commit to the other affected branches as well.

**Comment by turf212** [comment]
Done (I thought it was only the 4.0 branch)
