### ISSUE TITLE
assignment submissions viewable by company managers in all companies

### ISSUE THREAD

**Issue by dallenk** [iomad/iomad#1722]
As the title suggests, It appears that any company manager is able to view assignment submissions from any user in any company when mod/assign:grade is set to allow.  There doesn't seem to be any isolation between companies.

**Comment by turf212** [comment]
This is a course set up issue.  Courses need to be using forced separate groups and all of the users put into separate groups (default is a group named after their company).  This is how the shared functionality works.

**Comment by dallenk** [comment]
oh man!  the only course I had not set to forced..  thank you and appologies!
