### ISSUE TITLE
Coding Error in edit mode of the company users

### ISSUE THREAD

**Issue by dallenk** [iomad/iomad#1724]
newest code
Company / Users / Edit Users:  User list is viewable, no delete or suspend options on user context menu

Turn edit mode on, and server error

Coding error detected, it must be fixed by a programmer: Options for select element must contain an option for the specified value

[More information about this error](http://docs.moodle.org/400/en/error/debug/codingerror)

Debug info:
Error code: codingerror×Dismiss this notification
Stack trace:
line 183 of /lib/classes/output/inplace_editable.php: coding_exception thrown
line 91 of /blocks/iomad_company_admin/classes/output/user_roles_editable.php: call to core\output\inplace_editable->set_type_select()
line 146 of /blocks/iomad_company_admin/classes/tables/editusers_table.php: call to block_iomad_company_admin\output\user_roles_editable->__construct()
line 832 of /lib/tablelib.php: call to block_iomad_company_admin\tables\editusers_table->col_managertype()
line 2009 of /lib/tablelib.php: call to flexible_table->format_row()
line 2133 of /lib/tablelib.php: call to table_sql->build_table()
line 655 of /blocks/iomad_company_admin/editusers.php: call to table_sql->out()
×Dismiss this notification

**Comment by turf212** [comment]
There was a commit for a similar error on the 12th of Sep - 5f8ae93eec30091ea1258cae0e95f7d12d59c690 - Do you have this on your site?  The error that this commit fixed was that the value being held for the user didn't appear in the available list of options.

**Comment by dallenk** [comment]
Hi @turf212 .  I am at this code now.
commit 25540645896d8ae2eadef46329cf05f6882d1b5e (HEAD -> IOMAD_400_STABLE_2, origin/IOMAD_400_STABLE)
Author: Derick Turner <derick@e-learndesign.co.uk>
Date:   Thu Sep 15 17:20:58 2022 +0100

The commit you mentioned on the 12th fixed the error in the reports section.  This looks like it was introduced recently (or I haven't tried it in a while)  it is in the "edit users" section any only appears when "edit mode" is enabled.

**Comment by dallenk** [comment]
@turf212 I just updated my sandbox to the newest commit and the error is still active.

Company Dashboard / Users / Edit Users
enable "edit mode"

commit 525c4b7262b5c4f49499b95d8c6d84e53ee421d5 (HEAD -> IOMAD_400_STABLE, tag: IOMAD_404, origin/IOMAD_400_STABLE)
Author: Derick Turner <derick@e-learndesign.co.uk>
Date:   Mon Sep 26 13:16:58 2022 +0100

    IOMAD: split licenses not showing up correctly

**Comment by turf212** [comment]
Thanks for confirming.  I'm not seeing the error on my site (though it could be to do with the options)  Can you turn on full debug for me and let me know the error?

**Comment by dallenk** [comment]
Coding error detected, it must be fixed by a programmer: Options for select element must contain an option for the specified value

[More information about this error](http://docs.moodle.org/400/en/error/debug/codingerror)

Debug info:
Error code: codingerror×Dismiss this notification
Stack trace:
line 183 of /lib/classes/output/inplace_editable.php: coding_exception thrown
line 91 of /blocks/iomad_company_admin/classes/output/user_roles_editable.php: call to core\output\inplace_editable->set_type_select()
line 146 of /blocks/iomad_company_admin/classes/tables/editusers_table.php: call to block_iomad_company_admin\output\user_roles_editable->__construct()
line 832 of /lib/tablelib.php: call to block_iomad_company_admin\tables\editusers_table->col_managertype()
line 2009 of /lib/tablelib.php: call to flexible_table->format_row()
line 2133 of /lib/tablelib.php: call to table_sql->build_table()
line 655 of /blocks/iomad_company_admin/editusers.php: call to table_sql->out()

**Comment by turf212** [comment]
OK - so the set_type_select() call is the one where the current value for the user's role is being selected from the available list of managertypes for the select.

If you edit the file blocks/iomad_company_admin/classes/tables/editusers_table.php and go down to the function col_managertype($row) there is some code which looks like 

`            $editable = new \block_iomad_company_admin\output\user_roles_editable($company,
                                                          \context_system::instance(),
                                                          $row,
                                                          $currentvalue,
                                                          $usertypeselect);
`

if you can put the following before this row:

`echo "usertypeselect  = <pre>"; print_r($usertypeselect);echo "</pre>";
echo "currentvalue = $currentvalue</br>";`

and then reload the page, hopefully the will give the line where it's failing.

**Comment by turf212** [comment]
Oh - actually add the following instead:

```
echo "usertypeselect = <pre>"; print_r($usertypeselect);echo "</pre>";
echo "currentvalue = $currentvalue</br>";
echo "user managertype = $row->managertype</br>";
```

**Comment by dallenk** [comment]
usertypeselect =
Array
(
    [0] => User
    [1] => Chief Training Officer
    [2] => Assistant Training Officer
    [4] => Department report only
)
currentvalue = 0
user managertype = 0
[Reset table preferences](http://dev.firetrain.ca/blocks/iomad_company_admin/editusers.php?sort=lastname&dir=ASC&perpage=30&usertype=a&treset=1)
First name
All

usertypeselect =
Array
(
    [0] => User
    [1] => Chief Training Officer
    [2] => Assistant Training Officer
    [4] => Department report only
)
currentvalue = 1
user managertype = 1

Coding error detected, it must be fixed by a programmer: Options for select element must contain an option for the specified value

[More information about this error](http://docs.moodle.org/400/en/error/debug/codingerror)

Debug info:
Error code: codingerror×Dismiss this notification
Stack trace:
line 183 of /lib/classes/output/inplace_editable.php: coding_exception thrown
line 91 of /blocks/iomad_company_admin/classes/output/user_roles_editable.php: call to core\output\inplace_editable->set_type_select()
line 148 of /blocks/iomad_company_admin/classes/tables/editusers_table.php: call to block_iomad_company_admin\output\user_roles_editable->__construct()
line 832 of /lib/tablelib.php: call to block_iomad_company_admin\tables\editusers_table->col_managertype()
line 2009 of /lib/tablelib.php: call to flexible_table->format_row()
line 2133 of /lib/tablelib.php: call to table_sql->build_table()
line 655 of /blocks/iomad_company_admin/editusers.php: call to table_sql->out()

**Comment by dallenk** [comment]
I removed all the sorting options, if you want those also.  
```

user managertype = 0
[Reset table preferences](http://dev.firetrain.ca/blocks/iomad_company_admin/editusers.php?sort=lastname&dir=ASC&perpage=30&usertype=a&treset=1)
First name
All
[A](http://dev.firetrain.ca/blocks/iomad_company_admin/editusers.php?sort=lastname&dir=ASC&perpage=30&usertype=a&tifirst=A)
[B](http://dev.firetrain.ca/blocks/iomad_company_admin/editusers.php?sort=lastname&dir=ASC&perpage=30&usertype=a&tifirst=B)
[C](http://dev.firetrain.ca/blocks/iomad_company_admin/editusers.php?sort=lastname&dir=ASC&perpage=30&usertype=a&tifirst=C)
[D](http://dev.firetrain.ca/blocks/iomad_company_admin/editusers.php?sort=lastname&dir=ASC&perpage=30&usertype=a&tifirst=D)
[E](http://dev.firetrain.ca/blocks/iomad_company_admin/editusers.php?sort=lastname&dir=ASC&perpage=30&usertype=a&tifirst=E)
[F](http://dev.firetrain.ca/blocks/iomad_company_admin/editusers.php?sort=lastname&dir=ASC&perpage=30&usertype=a&tifirst=F)
[G](http://dev.firetrain.ca/blocks/iomad_company_admin/editusers.php?sort=lastname&dir=ASC&perpage=30&usertype=a&tifirst=G)
[H](http://dev.firetrain.ca/blocks/iomad_company_admin/editusers.php?sort=lastname&dir=ASC&perpage=30&usertype=a&tifirst=H)
[I](http://dev.firetrain.ca/blocks/iomad_company_admin/editusers.php?sort=lastname&dir=ASC&perpage=30&usertype=a&tifirst=I)
[J](http://dev.firetrain.ca/blocks/iomad_company_admin/editusers.php?sort=lastname&dir=ASC&perpage=30&usertype=a&tifirst=J)
[K](http://dev.firetrain.ca/blocks/iomad_company_admin/editusers.php?sort=lastname&dir=ASC&perpage=30&usertype=a&tifirst=K)
[L](http://dev.firetrain.ca/blocks/iomad_company_admin/editusers.php?sort=lastname&dir=ASC&perpage=30&usertype=a&tifirst=L)
[M](http://dev.firetrain.ca/blocks/iomad_company_admin/editusers.php?sort=lastname&dir=ASC&perpage=30&usertype=a&tifirst=M)
[N](http://dev.firetrain.ca/blocks/iomad_company_admin/editusers.php?sort=lastname&dir=ASC&perpage=30&usertype=a&tifirst=N)
[O](http://dev.firetrain.ca/blocks/iomad_company_admin/editusers.php?sort=lastname&dir=ASC&perpage=30&usertype=a&tifirst=O)
[P](http://dev.firetrain.ca/blocks/iomad_company_admin/editusers.php?sort=lastname&dir=ASC&perpage=30&usertype=a&tifirst=P)
[Q](http://dev.firetrain.ca/blocks/iomad_company_admin/editusers.php?sort=lastname&dir=ASC&perpage=30&usertype=a&tifirst=Q)
[R](http://dev.firetrain.ca/blocks/iomad_company_admin/editusers.php?sort=lastname&dir=ASC&perpage=30&usertype=a&tifirst=R)
[S](http://dev.firetrain.ca/blocks/iomad_company_admin/editusers.php?sort=lastname&dir=ASC&perpage=30&usertype=a&tifirst=S)
[T](http://dev.firetrain.ca/blocks/iomad_company_admin/editusers.php?sort=lastname&dir=ASC&perpage=30&usertype=a&tifirst=T)
[U](http://dev.firetrain.ca/blocks/iomad_company_admin/editusers.php?sort=lastname&dir=ASC&perpage=30&usertype=a&tifirst=U)
[V](http://dev.firetrain.ca/blocks/iomad_company_admin/editusers.php?sort=lastname&dir=ASC&perpage=30&usertype=a&tifirst=V)
[W](http://dev.firetrain.ca/blocks/iomad_company_admin/editusers.php?sort=lastname&dir=ASC&perpage=30&usertype=a&tifirst=W)
[X](http://dev.firetrain.ca/blocks/iomad_company_admin/editusers.php?sort=lastname&dir=ASC&perpage=30&usertype=a&tifirst=X)
[Y](http://dev.firetrain.ca/blocks/iomad_company_admin/editusers.php?sort=lastname&dir=ASC&perpage=30&usertype=a&tifirst=Y)
[Z](http://dev.firetrain.ca/blocks/iomad_company_admin/editusers.php?sort=lastname&dir=ASC&perpage=30&usertype=a&tifirst=Z)
Surname
All
[A](http://dev.firetrain.ca/blocks/iomad_company_admin/editusers.php?sort=lastname&dir=ASC&perpage=30&usertype=a&tilast=A)
[B](http://dev.firetrain.ca/blocks/iomad_company_admin/editusers.php?sort=lastname&dir=ASC&perpage=30&usertype=a&tilast=B)
[C](http://dev.firetrain.ca/blocks/iomad_company_admin/editusers.php?sort=lastname&dir=ASC&perpage=30&usertype=a&tilast=C)
[D](http://dev.firetrain.ca/blocks/iomad_company_admin/editusers.php?sort=lastname&dir=ASC&perpage=30&usertype=a&tilast=D)
[E](http://dev.firetrain.ca/blocks/iomad_company_admin/editusers.php?sort=lastname&dir=ASC&perpage=30&usertype=a&tilast=E)
[F](http://dev.firetrain.ca/blocks/iomad_company_admin/editusers.php?sort=lastname&dir=ASC&perpage=30&usertype=a&tilast=F)
[G](http://dev.firetrain.ca/blocks/iomad_company_admin/editusers.php?sort=lastname&dir=ASC&perpage=30&usertype=a&tilast=G)
[H](http://dev.firetrain.ca/blocks/iomad_company_admin/editusers.php?sort=lastname&dir=ASC&perpage=30&usertype=a&tilast=H)
[I](http://dev.firetrain.ca/blocks/iomad_company_admin/editusers.php?sort=lastname&dir=ASC&perpage=30&usertype=a&tilast=I)
[J](http://dev.firetrain.ca/blocks/iomad_company_admin/editusers.php?sort=lastname&dir=ASC&perpage=30&usertype=a&tilast=J)
[K](http://dev.firetrain.ca/blocks/iomad_company_admin/editusers.php?sort=lastname&dir=ASC&perpage=30&usertype=a&tilast=K)
[L](http://dev.firetrain.ca/blocks/iomad_company_admin/editusers.php?sort=lastname&dir=ASC&perpage=30&usertype=a&tilast=L)
[M](http://dev.firetrain.ca/blocks/iomad_company_admin/editusers.php?sort=lastname&dir=ASC&perpage=30&usertype=a&tilast=M)
[N](http://dev.firetrain.ca/blocks/iomad_company_admin/editusers.php?sort=lastname&dir=ASC&perpage=30&usertype=a&tilast=N)
[O](http://dev.firetrain.ca/blocks/iomad_company_admin/editusers.php?sort=lastname&dir=ASC&perpage=30&usertype=a&tilast=O)
[P](http://dev.firetrain.ca/blocks/iomad_company_admin/editusers.php?sort=lastname&dir=ASC&perpage=30&usertype=a&tilast=P)
[Q](http://dev.firetrain.ca/blocks/iomad_company_admin/editusers.php?sort=lastname&dir=ASC&perpage=30&usertype=a&tilast=Q)
[R](http://dev.firetrain.ca/blocks/iomad_company_admin/editusers.php?sort=lastname&dir=ASC&perpage=30&usertype=a&tilast=R)
[S](http://dev.firetrain.ca/blocks/iomad_company_admin/editusers.php?sort=lastname&dir=ASC&perpage=30&usertype=a&tilast=S)
[T](http://dev.firetrain.ca/blocks/iomad_company_admin/editusers.php?sort=lastname&dir=ASC&perpage=30&usertype=a&tilast=T)
[U](http://dev.firetrain.ca/blocks/iomad_company_admin/editusers.php?sort=lastname&dir=ASC&perpage=30&usertype=a&tilast=U)
[V](http://dev.firetrain.ca/blocks/iomad_company_admin/editusers.php?sort=lastname&dir=ASC&perpage=30&usertype=a&tilast=V)
[W](http://dev.firetrain.ca/blocks/iomad_company_admin/editusers.php?sort=lastname&dir=ASC&perpage=30&usertype=a&tilast=W)
[X](http://dev.firetrain.ca/blocks/iomad_company_admin/editusers.php?sort=lastname&dir=ASC&perpage=30&usertype=a&tilast=X)
[Y](http://dev.firetrain.ca/blocks/iomad_company_admin/editusers.php?sort=lastname&dir=ASC&perpage=30&usertype=a&tilast=Y)
[Z](http://dev.firetrain.ca/blocks/iomad_company_admin/editusers.php?sort=lastname&dir=ASC&perpage=30&usertype=a&tilast=Z)
usertypeselect =

```

**Comment by turf212** [comment]
If those are the only two users then both of them have a valid value in the options.  Either 0 or 1, both of which are options in the select.  Are we missing one?  are there only 2 users?

**Comment by dallenk** [comment]
correct, there are only two users in that company.

**Comment by dallenk** [comment]
if I create a filter for Chief Training Officer (usertype 1) or All,  i see the error.. If i filter by User [0], or Assistant [2] the error does not show.  
in this company there are no Assistants, just a manager (chief training officer) and a User

**Comment by turf212** [comment]
This is the offending line in the core lib:

```
    public function set_type_select($options) {
        if (!array_key_exists($this->value, $options)) {
            throw new \coding_exception('Options for select element must contain an option for the specified value');
        }

```

All it's doing is checking that the key value exists somewhere in the list of options.  1 exists in the list of keys.  I wonder if this is a type error.

Can you please add this line where you put the debug?

`$currentvalue = (int) $currentvalue;
`

**Comment by dallenk** [comment]
![image](https://user-images.githubusercontent.com/2725066/193606876-e19c61a2-2080-42d1-9574-4421ac53a5cd.png)

here ?
if so, no change.

**Comment by turf212** [comment]
Yes there. 

OK - let's do the check there then.  Add in this below that new line

```
if (!array_key_exists($currentvalue, $usertypeselect)) {
    echo "DOESNT EXIST</br>";
}
```

**Comment by dallenk** [comment]
no change
![image](https://user-images.githubusercontent.com/2725066/193608162-b95edb93-25db-42c2-a49c-77a60f7a74fa.png)

**Comment by turf212** [comment]
So the test which is failing is passing here.  OK.  Let's check the next layer.

If you checkout that file so it's back to normal and edit the file blocks/iomad_company_admin/classes/output/user_roles_editable.php

Above line 91 put the following:

```
echo "this value = $this->value</br>";
echo "assignable roles = <pre>";print_r($assignableroles);echo "</pre>";
if (!array_key_exists($this->value, $assignableroles)) {
    echo "DOESNT EXIST</br>";
} else {
    echo $assignableroles[$this->value] . "</br>";
}
```

which is pretty much the same debug as before with the same testing.

**Comment by dallenk** [comment]
done.. code looks like this now

```
            if ($count > 5) {
				echo "this value = $this->value</br>";
				echo "assignable roles = <pre>";print_r($assignableroles);echo "</pre>";
				if (!array_key_exists($this->value, $assignableroles)) {
					echo "DOESNT EXIST</br>";
				} else {
					echo $assignableroles[$this->value] . "</br>";
				}
                $returnstr .= "</details>";
            }

```

**Comment by turf212** [comment]
That's not right??  line 91 should look like :

`        $this->set_type_select($assignableroles);
`
Do you have the right file?

**Comment by turf212** [comment]
file is blocks/iomad_company_admin/classes/output/user_roles_editable.php :)

**Comment by dallenk** [comment]
Whoops!  My mistake.  10 mins

**Comment by dallenk** [comment]
no change, no output on the screen either.


```
       parent::__construct('block_iomad_company_admin', 'user_roles', $itemid, $editable, $value, $value);

        $this->edithint = get_string('xrolesassignments', 'block_iomad_company_admin', fullname($user));
        $this->editlabel = get_string('xrolesassignments', 'block_iomad_company_admin', fullname($user));

		echo "this value = $this->value</br>";
		echo "assignable roles = <pre>";print_r($assignableroles);echo "</pre>";
		if (!array_key_exists($this->value, $assignableroles)) {
			echo "DOESNT EXIST</br>";
		} else {
			echo $assignableroles[$this->value] . "</br>";
		}
        $this->set_type_select($assignableroles);
    }
```

**Comment by dallenk** [comment]
sorry!! I had an SCP permissions error (different IP when i saved)
this is with your code in the correct file now


![image](https://user-images.githubusercontent.com/2725066/193629238-77c9c52a-eb35-453a-af6a-06f8878b79ac.png)

**Comment by dallenk** [comment]
filtering by "User"
```
1 Users
this value = 0
assignable roles =
Array
(
    [0] => User
    [1] => Chief Training Officer
    [2] => Assistant Training Officer
    [4] => Department report only
)
User
```

filtering by "Assistant Training Officer"  [4]  (no users)  - no errors, Nothing to display

filtering by "Chief Training Officer" [1] 
```
1 Users
this value = "1"
assignable roles =
Array
(
    [0] => User
    [1] => Chief Training Officer
    [2] => Assistant Training Officer
    [4] => Department report only
)
DOESNT EXIST
```

**Comment by turf212** [comment]
So it is a type issue.  The value = "1" and not 1.

if you change the line 

`$value = json_encode($currentvalue);`

to

`$value = $currentvalue;`

what happens?

**Comment by dallenk** [comment]
error is cleared and users are listed in "Edit mode" now.

![image](https://user-images.githubusercontent.com/2725066/193634940-690dc16a-6680-4736-b5bd-362073271769.png)

**Comment by turf212** [comment]
Fab - So it was a type issue.
