### ISSUE TITLE
cannot clear courses for users any longer

### ISSUE THREAD

**Issue by dallenk** [iomad/iomad#1725]
attempting to clear a course on both my sites production (commit 25540645896d8ae2eadef46329cf05f6882d1b5e) and sandbox (commit 5f8ae93eec30091ea1258cae0e95f7d12d59c690 ) returns message `User has been removed from the course successfully.`

but it not cleared - debug shows no errors and the landing url is:  http://domain.com/local/report_completion/index.php?userid=0

**Comment by turf212** [comment]
The userid from the $params variable wasn't being overwritten when we added the new set of params to the buttons.  Not sure why that would be as previously moodle_url() would just sort it out when you added the arrays together.

**Comment by dallenk** [comment]
seems I still cannot clear a course, or purge records as the site administrator.

I also don't see the edit mode slider for Company Managers in "reports / completion report by course / show all users"

**Comment by dallenk** [comment]
bump  Hi @turf212 this still appears to be a bug.  Clearing a course for a user has no effect.

**Comment by turf212** [comment]
reports were overhauled in 635f3c8eaa4a0b94811330471f4db271db84c8ad
