### ISSUE TITLE
"edit mode" disappeared from "edit users" for Company Managers

### ISSUE THREAD

**Issue by dallenk** [iomad/iomad#1727]
This is quite strange, one of the tenants messaged me today saying they can't find how to edit a user.. as the Admin I can see everything and edit the users correctly but when I try with a Company Manager account the "edit mode" switch is missing.  

A workaround is to enable edit mode from Home, or the Dashboard.. then go to the edit users link, the menu's show options to edit users but the slider is still missing.

I checked the demo site and it doesn't look like any user but the admin has the edit mode slider either..

**Comment by turf212** [comment]
Looks like the checks for capabilities for what page gets edit mode was made more secure.  I've updated the code to expicitly add the caps to the PAGE requirements.

**Comment by dallenk** [comment]
confirmed working now,

Thank you!
