### ISSUE TITLE
Users not being added into company groups when enrolling.

### ISSUE THREAD

**Issue by tcaronNAIT** [iomad/iomad#173]
Any enrollment into a courses that allow self enrollment in not adding the users into the company groups that were created.

**Comment by turf212** [comment]
The standard Moodle enrolment methods are not company aware (at the moment).  So self sign up on a course will not know which company group to put the user into.  You can work around this for the moment using group enrolment keys which would allow the user to be automatically put into the right company group.

If this is a specific need you have, you could sponsor this going into core.

**Comment by nick69g** [comment]
Hi

Thanks for your reply.

What I'm doing is creating a user within their company and then enrolling them onto a course via the license. This still allows them to see all the categories which in theory are companies? How do I prevent them listing "courses" in the Navigation block?

Thanks.
Nick

Nick Garrod MCIPD
eLearning Development Manager

nick.garrod@cloudsustainability.commailto:nick.garrod@cloudsustainability.com
T. 0845 287 3850 DD. 0203 102 6948
M. +44 (0)7712 331 789 Skype ID. nickg69
www.cloudsustainability.comhttp://www.cloudsustainability.com/

[cid:B71A5E66-26AF-4C60-A792-13DFB000C0C7] @CloudPioneerhttp://twitter.com/cloudpioneer

[cid:797E7365-7CD7-47BB-9226-AC039B2253D7]
The information contained in this e-mail is for the exclusive use of the intended recipient(s), or person responsible for delivering this information to the intended recipient, and may be confidential, proprietary, and/or legally privileged. Inadvertent disclosure of this message does not constitute a waiver of any privilege. If you receive this message in error, please do not directly or indirectly use, print, copy, forward, or disclose any part of it. Please immediately delete the e-mail plus all copies and notify the sender or call 0845 287 3850.
Revise Limited makes reasonable attempts to exclude any virus, or any other defect which might affect any computer or IT system, from this e-mail and any attachments but it is the responsibility of the recipient to ensure that they are virus free and we accept no liability for any loss or damage arising in any way from their receipt or use.
Revise Limited is registered in England, company no. 06863577, registered address Leeds Innovation Centre, 103 Clarendon Road, Leeds, LS2 9DF.

Please think about the environment before printing this e-mail.

**Comment by nick69g** [comment]
Hi

Are there any instructions or advice in getting the automated Iomad email to work? I'm creating new learners, adding learners etc to courses and licenses and no email is being sent/received?

What settings etc do I need to do please?

Thanks.
Nick

Nick Garrod MCIPD
eLearning Development Manager

nick.garrod@cloudsustainability.commailto:nick.garrod@cloudsustainability.com
T. 0845 287 3850 DD. 0203 102 6948
M. +44 (0)7712 331 789 Skype ID. nickg69
www.cloudsustainability.comhttp://www.cloudsustainability.com/

[cid:6321A05A-97C0-4C21-9375-86C1D3AFC08A] @CloudPioneerhttp://twitter.com/cloudpioneer

[cid:B89A0FE3-1B29-4D07-B7B6-4295A74832CB]
The information contained in this e-mail is for the exclusive use of the intended recipient(s), or person responsible for delivering this information to the intended recipient, and may be confidential, proprietary, and/or legally privileged. Inadvertent disclosure of this message does not constitute a waiver of any privilege. If you receive this message in error, please do not directly or indirectly use, print, copy, forward, or disclose any part of it. Please immediately delete the e-mail plus all copies and notify the sender or call 0845 287 3850.
Revise Limited makes reasonable attempts to exclude any virus, or any other defect which might affect any computer or IT system, from this e-mail and any attachments but it is the responsibility of the recipient to ensure that they are virus free and we accept no liability for any loss or damage arising in any way from their receipt or use.
Revise Limited is registered in England, company no. 06863577, registered address Leeds Innovation Centre, 103 Clarendon Road, Leeds, LS2 9DF.

Please think about the environment before printing this e-mail.

**Comment by BananaRama203** [comment]
@nick69g I had the same issue. IOMAD automated emails rely on CRON. It fills the mysql database with emails and it fires them out when CRON is run.

https://docs.moodle.org/28/en/Cron - How to set up CRON on your server.

**Comment by nick69g** [comment]
Hi

Thanks. I've just run the Cron from within Moodle/Notifications and no email has been sent! Any ideas please?

Nick

Nick Garrod MCIPD
eLearning Development Manager

nick.garrod@cloudsustainability.commailto:nick.garrod@cloudsustainability.com
T. 0845 287 3850 DD. 0203 102 6948
M. +44 (0)7712 331 789 Skype ID. nickg69
www.cloudsustainability.comhttp://www.cloudsustainability.com/

[cid:C487F06B-4816-4284-9B7B-9F29DE64BF61] @CloudPioneerhttp://twitter.com/cloudpioneer

[cid:2DE03049-AF28-4DE8-B82A-6D8138FEDB79]
The information contained in this e-mail is for the exclusive use of the intended recipient(s), or person responsible for delivering this information to the intended recipient, and may be confidential, proprietary, and/or legally privileged. Inadvertent disclosure of this message does not constitute a waiver of any privilege. If you receive this message in error, please do not directly or indirectly use, print, copy, forward, or disclose any part of it. Please immediately delete the e-mail plus all copies and notify the sender or call 0845 287 3850.
Revise Limited makes reasonable attempts to exclude any virus, or any other defect which might affect any computer or IT system, from this e-mail and any attachments but it is the responsibility of the recipient to ensure that they are virus free and we accept no liability for any loss or damage arising in any way from their receipt or use.
Revise Limited is registered in England, company no. 06863577, registered address Leeds Innovation Centre, 103 Clarendon Road, Leeds, LS2 9DF.

Please think about the environment before printing this e-mail.

**Comment by BananaRama203** [comment]
Have you checked mdl_email table within your database to see that the table is being filled?

If so look at the sent column (NULL) obviously means it hasn't sent and if it has a time stamp then you know it has been sent out.

Also there has recently been a patch to fix the automated emails in 2.8 are you on the latest version? If not check the recent commits for the email module

Lastly. I don't know if running the CRON from the notifications page is adequate enough for the system to fire out the emails (I might be completely wrong!) But as you will need to set up a automated CRON job anyway I would set up a automated CRON Job on your webserver just in case. Here is my cron job as an example...

`*    *   *   *   *   /usr/bin/php -q /home/ryanhaml/public_html/SOLA3System/admin/cli/cron.php >/dev/null`

Hope that helps!

**Comment by nick69g** [comment]
Hi

You have been most helpful. The database is showing a list of the queued email as NULL so at least I know they are being created and know they have not been sent.

I was using 2.8 but found a bug with the company not allowing a logo to be added. This has been fixed so I'me just updating to 2.8 to see if the latest version on GitHub has the company logo fix in it.

I will have a go at the CRON server - I'm using a dedicated Lynux UK Fast server - will have a play...

Nick

Nick Garrod MCIPD
eLearning Development Manager

nick.garrod@cloudsustainability.commailto:nick.garrod@cloudsustainability.com
T. 0845 287 3850 DD. 0203 102 6948
M. +44 (0)7712 331 789 Skype ID. nickg69
www.cloudsustainability.comhttp://www.cloudsustainability.com/

[cid:F1953060-21C2-4214-A4CD-DC221B643CAD] @CloudPioneerhttp://twitter.com/cloudpioneer

[cid:09CEF655-5EE2-4C45-B800-2A47C0DE8778]
The information contained in this e-mail is for the exclusive use of the intended recipient(s), or person responsible for delivering this information to the intended recipient, and may be confidential, proprietary, and/or legally privileged. Inadvertent disclosure of this message does not constitute a waiver of any privilege. If you receive this message in error, please do not directly or indirectly use, print, copy, forward, or disclose any part of it. Please immediately delete the e-mail plus all copies and notify the sender or call 0845 287 3850.
Revise Limited makes reasonable attempts to exclude any virus, or any other defect which might affect any computer or IT system, from this e-mail and any attachments but it is the responsibility of the recipient to ensure that they are virus free and we accept no liability for any loss or damage arising in any way from their receipt or use.
Revise Limited is registered in England, company no. 06863577, registered address Leeds Innovation Centre, 103 Clarendon Road, Leeds, LS2 9DF.

Please think about the environment before printing this e-mail.

**Comment by BananaRama203** [comment]
No worries. If you got cPanel you should see a option for "Cron Jobs" and the rest is relatively easy.

**Comment by nick69g** [comment]
I have - and was just going to look at that. I assume I get this to run the cron.php file?

Nick

Nick Garrod MCIPD
eLearning Development Manager

nick.garrod@cloudsustainability.commailto:nick.garrod@cloudsustainability.com
T. 0845 287 3850 DD. 0203 102 6948
M. +44 (0)7712 331 789 Skype ID. nickg69
www.cloudsustainability.comhttp://www.cloudsustainability.com/

[cid:7EFE3031-9803-4091-813D-A691987C8237] @CloudPioneerhttp://twitter.com/cloudpioneer

[cid:481C9B0E-00E2-40FD-BFF5-D85253A39E61]
The information contained in this e-mail is for the exclusive use of the intended recipient(s), or person responsible for delivering this information to the intended recipient, and may be confidential, proprietary, and/or legally privileged. Inadvertent disclosure of this message does not constitute a waiver of any privilege. If you receive this message in error, please do not directly or indirectly use, print, copy, forward, or disclose any part of it. Please immediately delete the e-mail plus all copies and notify the sender or call 0845 287 3850.
Revise Limited makes reasonable attempts to exclude any virus, or any other defect which might affect any computer or IT system, from this e-mail and any attachments but it is the responsibility of the recipient to ensure that they are virus free and we accept no liability for any loss or damage arising in any way from their receipt or use.
Revise Limited is registered in England, company no. 06863577, registered address Leeds Innovation Centre, 103 Clarendon Road, Leeds, LS2 9DF.

Please think about the environment before printing this e-mail.

**Comment by tcaronNAIT** [comment]
Hi,

Thank you for replying and the information, I was thinking I broke something.

**Comment by turf212** [comment]
Just to reiterate this, Iomad is effectively Moodle with a lot of additional plugins and some core Moodle changes to make it work with multi-tenancy.  You still need to have the cron set up to run for a lot of the processing to happen.

**Comment by pm-tatiana** [comment]
I am having a related issue.
Usually when I have a course that's closed shared, not licensed. I assign the course to the company I want and the company manager (CM):

1. Can see the course in the list of available courses or my courses
2. CM gets enrolled as Company manager and Client course access and linked to a specific group with same name as the company http://prntscr.com/eta2c0 - This is wonderful because it allows segregation of data and allows me to modify permissions on the company manager and client course access roles so that company manager can check the grades only for those users that belong to his own company (same group).

**When the course is closed shared and licensed,** however, doesn't work as I need it to work.
When I assign the licensed course to the company, my company manager is not able to see the course listed in the courses available to the company because all of the enrollments methods are disabled.
This causes my CM not being enrolled into the course as usual. Instead, I need to go and create a license for the company and allocate the course to the license. If I want the course to be visible to the CM, I have to allocate him a license. That's fine. I can live with that BUT, those brings me another issue.
My CM gets enrolled into the course "Student" and as "Company Manager".
I don't want my CM to be a student. I want him to have the roles he usually gets AND I want my CM to be allocated to the group he should be in.

Also, Company users under this licensed - closed shared/open shared course scheme. Are not segregated by company because they are not added in a group as usually they would if they were enrolled into the course via "user enrollment".

Do you have any suggestion regarding this?

**Comment by pm-tatiana** [comment]
@tcaron2 @turf212 @turf212 @swingflip Do you have any suggestion?
