### ISSUE TITLE
Email templates not working, still sending standard emails

### ISSUE THREAD

**Issue by Maaqt** [iomad/iomad#1731]
I made different email templates for a company, and turned them from left to right on. however when a user is created or enrolled on a course. They are still getting the standard email. Is there a function somewhere that i'm missing? or can anyone explain me the process

Thanks in advance,

**Comment by dallenk** [comment]
did you apply the template to your companies or edit the templates for the individual companies?    I missed that when I first started using different company templates.

**Comment by Maaqt** [comment]
Hi,  thanks for the reply.
if i'm correct. you edit different mail templates, then save the Template set, and then add it to a company.  After doing this it still sends the standard emails instead of the personalised ones.  Any other idea what it ccould be?

**Comment by Maaqt** [comment]
We got the emailtemplates working if we manualy add a user or assign a course to a user. But if a user uses self_enrolment Email_based_registration. the standard emails are send out instead of the company ones.  While debugging we find this:

[Tue Oct 11 13:42:23.000828 2022] [php7:notice] [pid 21467] [client 94.157.162.11:60036] PHP Notice:  Undefined index: path in /srv/iomad/local/iomad/lib/company.php on line 178,

any idea's?
