### ISSUE TITLE
regenerate certificate as Company Manager - Coding error

### ISSUE THREAD

**Issue by dallenk** [iomad/iomad#1733]
Coding error detected, it must be fixed by a programmer: Invalid state passed to moodle_page::set_state. We are in state 2 and state 1 was requested.

enabled permission:
[Regenerate stored user certificates for a course.]
local/report_users:redocertificates

**Comment by dallenk** [comment]
update:  this also occurs as the Administrator also, but under conditions.

Selecting the checkbox on the user, then clicking "Regenerate Selected Certificates"  does not produce the error.
Clicking on "Regenerate certificate" on any user produces the error, then lands on the following URL (which is also invalid)

https://sub.domain.ca/local/report_completion/index.php.php

**Comment by turf212** [comment]
fixed in ba81513d1be0bf551e36f7314a4af47c2392a2ff
