### ISSUE TITLE
Local Reports Fix/Improve install/upgrade speed

### ISSUE THREAD

**Issue by thundor** [iomad/iomad#1735]
Hi,
I'm currently attempting to install iomad over an a moodle 3.8 with much info and stumbled upon unnecesarily-long-running install/upgrade scripts. Also fixed some query offset - limit bug (they were inside the array, not outside)

Please find attached my resolve:

[iomad_local_reports_install_upgrade_fix.patch.1.txt](https://github.com/iomad/iomad/files/9910370/iomad_local_reports_install_upgrade_fix.patch.1.txt)

This fix is to prevent crash on upgrade because table "company" missing.
[fix-iomad-migration.patch.txt](https://github.com/iomad/iomad/files/9909708/fix-iomad-migration.patch.txt)

**Comment by turf212** [comment]
Were the changes for the IOMAD 3.8 code or were you using one of the newer branches?

**Comment by thundor** [comment]
> 

iomad_404_stable

**Comment by turf212** [comment]
Ah - Thanks for these. I've added 2 commits - one for the setuplib.php issue and one for the reports.  I've neatened up the code so that it's using spaces instead of tabs and for readability.  They've been pushed to 3.6 (as it;s where they were first introduced), 3.9, 4.0 and 4.1 branches.
