### ISSUE TITLE
Course Categories

### ISSUE THREAD

**Issue by Blacksheeprules** [iomad/iomad#1737]
Hi,

Is there a way to use course categories with IOMAD. It appears that course categories are being used for companies. I would like to have course categories for each company. 

Thank-you for any help on this issue. 

Mark

**Comment by Blacksheeprules** [comment]
Could I create a sub category in moodle and move the course created in Iomad into the sub category.

**Comment by mikeaveli007** [comment]
Yes, actually just did this with our instance.  You create subcategories in the companies
