### ISSUE TITLE
Exception - Class 'Iomad' not found.

### ISSUE THREAD

**Issue by sagar456-ops** [iomad/iomad#1738]
![Screenshot from 2022-11-12 21-10-44](https://user-images.githubusercontent.com/59444038/201482330-2490160d-7937-49ae-b0fc-c96d911c1fb7.png)

**Comment by sagar456-ops** [comment]
During moodle upgrade to latest version 4 this error arises

**Comment by turf212** [comment]
one of the upgrade functions was missing the library load.
