### ISSUE TITLE
Licence not working

### ISSUE THREAD

**Issue by nick69g** [iomad/iomad#174]
I've created a company with a test learner. A licence has been created and assigned to a course and all works OK when viewing the licence.

When trying to add a user to a licence nothing happens. You select the learner to move across to occupy one of the licence places, but nothing happens.

Is this a major bug?

**Comment by turf212** [comment]
Hi Nick,   Its certainly the first we have heard of this (and we have a number of clients who are using licenses in earnest.)  Can you please detail which version of Iomad (there were licensing changes in V2.8) and the exact steps you used to have this issue?

Thanks

**Comment by nick69g** [comment]
Hello  v2.8

Have a look at http://94.229.166.97/~cloudorgs
Username: admin
Password: Pa$$word1

There is a course/license set up - see if you can allocate the license and you will see what I mean by the bug.

Regards.
Nick

[cid:F844580D-2CEB-4D53-AFEA-51307FF22570]
Nick Garrod MCIPD
eLearning Development Manager

nick.garrod@cloudsustainability.commailto:nick.garrod@cloudsustainability.com
T. 0845 287 3850 DD. 0203 102 6948
M. +44 (0)7712 331 789 Skype ID. nickg69
www.cloudsustainability.comhttp://www.cloudsustainability.com/

[cid:880F9786-99B0-41DC-9666-A020E2EA5B03] @CloudPioneerhttp://twitter.com/cloudpioneer

[cid:16874E89-3282-46CA-A145-5C05687CFEE4]
The information contained in this e-mail is for the exclusive use of the intended recipient(s), or person responsible for delivering this information to the intended recipient, and may be confidential, proprietary, and/or legally privileged. Inadvertent disclosure of this message does not constitute a waiver of any privilege. If you receive this message in error, please do not directly or indirectly use, print, copy, forward, or disclose any part of it. Please immediately delete the e-mail plus all copies and notify the sender or call 0845 287 3850.
Cloud Sustainability Limited makes reasonable attempts to exclude any virus, or any other defect which might affect any computer or IT system, from this e-mail and any attachments but it is the responsibility of the recipient to ensure that they are virus free and we accept no liability for any loss or damage arising in any way from their receipt or use.
Cloud Sustainability Limited is registered in England, company no. 06863577, registered address Leeds Innovation Centre, 103 Clarendon Road, Leeds, LS2 9DF.

Please think about the environment before printing this e-mail.

**Comment by nick69g** [comment]
Hello

Were you ever able to look into this to see if it was a bug please?

Nick

Nick Garrod MCIPD
eLearning Development Manager

nick.garrod@cloudsustainability.commailto:nick.garrod@cloudsustainability.com
T. 0845 287 3850 DD. 0203 102 6948
M. +44 (0)7712 331 789 Skype ID. nickg69
www.cloudsustainability.comhttp://www.cloudsustainability.com/

[cid:7D32865C-4C50-4677-A2C2-04A6B506B494] @CloudPioneerhttp://twitter.com/cloudpioneer

[cid:2FBDE303-1044-4EF4-8B6A-9FF58C911462]
The information contained in this e-mail is for the exclusive use of the intended recipient(s), or person responsible for delivering this information to the intended recipient, and may be confidential, proprietary, and/or legally privileged. Inadvertent disclosure of this message does not constitute a waiver of any privilege. If you receive this message in error, please do not directly or indirectly use, print, copy, forward, or disclose any part of it. Please immediately delete the e-mail plus all copies and notify the sender or call 0845 287 3850.
Revise Limited makes reasonable attempts to exclude any virus, or any other defect which might affect any computer or IT system, from this e-mail and any attachments but it is the responsibility of the recipient to ensure that they are virus free and we accept no liability for any loss or damage arising in any way from their receipt or use.
Revise Limited is registered in England, company no. 06863577, registered address Leeds Innovation Centre, 103 Clarendon Road, Leeds, LS2 9DF.

Please think about the environment before printing this e-mail.

**Comment by BananaRama203** [comment]
Hi Nick, I took the time to log in as your Admin on your site to check if the licensing is working and it seems to be fine to me.

there are two ways the licensing system can work.

Change course enrolments and Change course licenses.

The first option you can select a group of courses to make available to a specific user. When the user logs in then they have a choice of what courses to enroll themselves on.

The latter option is a case of setting up a license for a company, making a selection of courses available to a license and when creating/editing a user you are able to allocate specific courses from the license to the students to participate. Each course you allocate through this method deducts a unit from the license for each course allocated to the learner.

I checked bth methods and they work fine for me.

I would suggest using course licenses. (It is what I use) and it works great for what we need it for. Just make sure you add courses to a master company and set them to open and shared. Also make sure they have license enrolment active on each course.

Once you got a select of open and shared courses you can then go create companies, licenses with courses on and then start allocating to students.

So in answer to your question... no, it's not a bug but I hope I cleared some stuff up for you :)

**Comment by nick69g** [comment]
Hello

Thanks for your reply, but I simply cannot get this to work.

I've got a course called "Test". There is a license called "Test Test" assigned to the course. When I attempt to allocate a learner/user to the license absolutely nothing happens.

I'm doing exactly the same on an earlier version of Iomad which works fine to what I am doing on this later version and it's driving me mad. I'm probably going to have to stop using it.

Please are you able to confirm what I'm doing wrong or recheck this for me please?

Have a look at http://94.229.166.97/~cloudorgs
Username: admin
Password: Pa$$word1

Regards.
Nick

**Comment by BananaRama203** [comment]
Ok I checked it out and set up the companies ok and allocated the licenses ok and all seems ok.

What I suggest is starting from the beginning and we can go through it step by step.
1. Do a fresh install of iomad2.8
2. Create a MASTER company
3. Create some test blank course called test course1 + test course2 + test course3
4. Go to course management and click assign courses...assign the 3 courses to the MASTER company
5. Once allocated click manage iomad course settings and set the courses to open shared and licensed
6. Create a company called test client company
7. Make sure you have test company selected in dashboard
8. Click on license management and click on license management.
9. Create test license1 and add the 3 courses to the license
10. Click on user management and create user.
11. When creating a user click on available licenses -> select the license and allocate the 3 courses and click save. (This will create a leaner allocated to 3 courses and you would use up 3 units of the license)
12. Create another test user but only allocated course1.
13. Click on edit user and change course licenses on the 2nd test user.
14. Select the license and allocate course2 to the user.

You would have just set up a master company, a test company, 2 learners, a company license and you would have 5 units deducted from the license you set up.

If you logged into the 2 users you would be able to access and start the two courses.

This is the best and easiest way of using iomad. There are two different methods however just follow these steps and you should grasp the concept

Good luck!

**Comment by nick69g** [comment]
Hi

Many thanks for the detailed response. Let me work through this and see if I can figure it out!

Nick

Nick Garrod MCIPD
eLearning Development Manager

nick.garrod@cloudsustainability.commailto:nick.garrod@cloudsustainability.com
T. 0845 287 3850 DD. 0203 102 6948
M. +44 (0)7712 331 789 Skype ID. nickg69
www.cloudsustainability.comhttp://www.cloudsustainability.com/

[cid:DC8830B2-CFA9-4F51-8429-FDCBF6F1D4D1] @CloudPioneerhttp://twitter.com/cloudpioneer

[cid:E9F925F8-BF5A-4DBF-82DE-5A9034DA4199]
The information contained in this e-mail is for the exclusive use of the intended recipient(s), or person responsible for delivering this information to the intended recipient, and may be confidential, proprietary, and/or legally privileged. Inadvertent disclosure of this message does not constitute a waiver of any privilege. If you receive this message in error, please do not directly or indirectly use, print, copy, forward, or disclose any part of it. Please immediately delete the e-mail plus all copies and notify the sender or call 0845 287 3850.
Revise Limited makes reasonable attempts to exclude any virus, or any other defect which might affect any computer or IT system, from this e-mail and any attachments but it is the responsibility of the recipient to ensure that they are virus free and we accept no liability for any loss or damage arising in any way from their receipt or use.
Revise Limited is registered in England, company no. 06863577, registered address Leeds Innovation Centre, 103 Clarendon Road, Leeds, LS2 9DF.

Please think about the environment before printing this e-mail.

**Comment by nick69g** [comment]
Hello

Thanks again for your detailed response, I can see how the license works following your instructions; but what I cannot get to work on 2.8, but working fine on 2.7 is the following:

On this screen in 2.7, I can select a learner on the right; click "Allocate license" and they will move to the section on the left and use up a license space. The reversal does work; when I select a learner on the left and click "Unallocate license", providing they are not using the license (showing with a *) then the move to the right side.

Please can you left me know if the above should work as I've outlined or not, as it does do so in 2.7.

Regards.
Nick

[cid:8249B043-7142-4E65-95FE-0E36BEFA45A9]

[cid:FD9CF925-99B5-4B69-86D4-8683062DDB35]
Nick Garrod MCIPD
eLearning Development Manager

nick.garrod@cloudsustainability.commailto:nick.garrod@cloudsustainability.com
T. 0845 287 3850 DD. 0203 102 6948
M. +44 (0)7712 331 789 Skype ID. nickg69
www.cloudsustainability.comhttp://www.cloudsustainability.com/

[cid:B2DC983B-05D4-47E2-8BBC-12E591D8158D] @CloudPioneerhttp://twitter.com/cloudpioneer

[cid:76525512-427A-42B0-BCB5-EF11DADFDF41]
The information contained in this e-mail is for the exclusive use of the intended recipient(s), or person responsible for delivering this information to the intended recipient, and may be confidential, proprietary, and/or legally privileged. Inadvertent disclosure of this message does not constitute a waiver of any privilege. If you receive this message in error, please do not directly or indirectly use, print, copy, forward, or disclose any part of it. Please immediately delete the e-mail plus all copies and notify the sender or call 0845 287 3850.
Cloud Sustainability Limited makes reasonable attempts to exclude any virus, or any other defect which might affect any computer or IT system, from this e-mail and any attachments but it is the responsibility of the recipient to ensure that they are virus free and we accept no liability for any loss or damage arising in any way from their receipt or use.
Cloud Sustainability Limited is registered in England, company no. 06863577, registered address Leeds Innovation Centre, 103 Clarendon Road, Leeds, LS2 9DF.

Please think about the environment before printing this e-mail.

**Comment by pm-tatiana** [comment]
Why licensing needs to work with open sharing? why not with closed sharing???

**Comment by ghost** [comment]
Created course is not available in 'Select a course to edit licenses for' this area IOMAD.

**Comment by turf212** [comment]
Licensing works with both open and closed shared courses.  There was a bug where some of the courses didn't show up but it was fixed a while back.  As long as the course is available to the company and the course is set to licensed then you can create a license with that course.
