### ISSUE TITLE
Auto Enrol All Company Managers/Department Training Managers/Users in Course

### ISSUE THREAD

**Issue by TheArkaTek** [iomad/iomad#1743]
I've created courses to train each role on how to use the platform and want to be able to automatically enrol each role it's intro course. I figure there has to be a way to do this. It may be a little harder since all the users are separated out into their own child companies.

**Comment by dallenk** [comment]
In each company dashboard, edit the company, advanced company settings.  Autoenrollment courses

is this what you are looking for?

![image](https://user-images.githubusercontent.com/2725066/205788334-53cdc2b6-0ff5-4674-b99a-0aa36949cdcc.png)

**Comment by TheArkaTek** [comment]
This could work, can I apply the autoenrol to a specific role? I would test it myself but that option only appears at the original company. If it applies to every role across companies that could still be useful in a different way.

**Comment by turf212** [comment]
Auto enrolment plugin with profile field and company matching would be the current solution.
