### ISSUE TITLE
Version 4.1

### ISSUE THREAD

**Issue by E-Learner-Foxx** [iomad/iomad#1744]
Thanks for the dedication and support.
Is there an expected date for the release of IOMAD 4.1?
Really looking forward to experimenting with the new Gradebook features.

**Comment by rmeske** [comment]
I am looking to create a new installation and would like to know when IOMAD 4.1 will be available to decide if I should just wait and avoid the need to do the update, or if I should proceed with 4.0 and know that I will need to do an update in the future.

**Comment by thundor** [comment]
This was my problem too. I created an upgrader (lastest Iomad with latest Moodle)
https://github.com/iomad/iomad/issues/1746
I'll attempt to create a fork to create this automatically.
I'll be back

**Comment by thundor** [comment]
(UNTESTED) https://github.com/thundor/iomad/tree/IOMAD_401_STABLE
Il'll try sometimes soon to keep histories in git. I failed

**Comment by turf212** [comment]
To answer the initial question - we are typically a couple months behind the Moodle release.  Two reasons for this:
1 - We've been caught out with last minute changes to the release which prompted a lot of rework of code so we now wait till the release is finalised
2 - Testing typically prompts a number of things which are broken in the multi-tenancy parts which need to be checked and fixed before we release.  (Also this is when we make sure all of the new features have fully been added in).

I keep a copy of the Moodle MASTER branch which has all of the IOMAD code merged to it. On the release of a new version I create a branch off of this just before the Moodle release and merge in the Moodle release branch.  That's our starting point.  It also means all of the git history is kept and we can apply fixes to multiple branches (if necessary)

If you want to test I can create a testing 4.1 branch and push here.  It would be subject to change as we found/fixed issues/added new functionality but would save a lot of this effort.

Let me know?

**Comment by DennieW** [comment]
Hi
Thanks for responding.
Yes I would really appreciate a copy of the 4.1 branch so I can perform some testing.

I definitely look forward to this.

**Comment by E-Learner-Foxx** [comment]
@turf212 Would really appreciate if you can create the 4.1 branch for testing.

**Comment by E-Learner-Foxx** [comment]
@thundor have you had chance to do some testing on this https://github.com/thundor/iomad/tree/IOMAD_401_STABLE ?
I noticed you wrote "I failed" can you clarify what you meant by this statement.

**Comment by thundor** [comment]
> @thundor have you had chance to do some testing on this https://github.com/thundor/iomad/tree/IOMAD_401_STABLE ? I noticed you wrote "I failed" can you clarify what you meant by this statement.

I haven't had the chance to test it.
By "I failed" i meant if you access https://github.com/thundor/iomad/tree/IOMAD_401_STABLE you'll see "Updated iomad 401". That should not have been there. I am not very proficient with git. I'll have to try again and preserve the history.
The upgrade was made via git, but i must have messed something up... 
The files should be good though. I'll try to test them this evening if i'm not too busy/tired

**Comment by thundor** [comment]
Disclaimer: I am not a developer of IOMAD, nor affiliated, using https://github.com/thundor/iomad/tree/IOMAD_401_STABLE just means that the following was done for you, nothing else. Iomad is not responsible if you detect errors using my fork. Nor I for that matter. 

I succeeded https://github.com/thundor/iomad/tree/IOMAD_401_STABLE
Tested on my server, installation was successful

What I did:
Initting directory:
> mkdir iomad401
> cd iomad401

Getting the desired branch of moodle
> git clone --branch MOODLE_401_STABLE https://github.com/moodle/moodle.git ./

Merging with the desired iomad branch, prefering the moodle
> git remote add iomad404 https://github.com/iomad/iomad.git
> git fetch iomad404
> git merge -X ours iomad404/IOMAD_400_STABLE --allow-unrelated-histories

Checking the status:
> git status

Then I dealt Unmerged paths (I don't really know how they came to be):

        both added:      course/tests/reportbuilder/datasource/courses_test.php
        added by them:   enrol/license/classes/task/cron_task.php
        added by us:     lib/classes/task/task_lock_cleanup_task.php
        both added:      lib/tests/task/manager_test.php
        both deleted:    mod/quiz/report/statistics/classes/task/quiz_statistics_cleanup.php

added by them: means added by iomad, so we do:
> git checkout iomad404/IOMAD_400_STABLE -- /path/to/file

added by us: added by moodle so we do:
> git checkout origin/MOODLE_401_STABLE -- /path/to/file

OR 
> git reset -- /path/to/file
> git checkout -- /path/to/file

For both added and both deleted, just:
> git reset -- /path/to/file

In this case, i did:
> git reset -- course/tests/reportbuilder/datasource/courses_test.php
> git checkout iomad404/IOMAD_400_STABLE -- enrol/license/classes/task/cron_task.php
> git reset -- lib/classes/task/task_lock_cleanup_task.php
> git checkout -- lib/classes/task/task_lock_cleanup_task.php
> git reset -- lib/tests/task/manager_test.php
> git reset -- mod/quiz/report/statistics/classes/task/quiz_statistics_cleanup.php

Then:
> git status

**Comment by DennieW** [comment]
> Disclaimer: I am not a developer of IOMAD, nor affiliated, using https://github.com/thundor/iomad/tree/IOMAD_401_STABLE just means that the following was done for you, nothing else. Iomad is not responsible if you detect errors using my fork. Nor I for that matter.
> 
> I succeeded https://github.com/thundor/iomad/tree/IOMAD_401_STABLE Tested on my server, installation was successful
> 
> What I did:
> 
> Getting the desired branch of moodle
> 
> > git clone --branch MOODLE_401_STABLE https://github.com/moodle/moodle.git ./
> 
> Merging with the desired iomad branch, prefering the moodle
> 
> > git remote add iomad404 https://github.com/iomad/iomad.git
> > git fetch iomad404
> > git merge -X ours iomad404/IOMAD_400_STABLE --allow-unrelated-histories
> 
> Checking the status:
> 
> > git status
> 
> Then I dealt Unmerged paths (I don't really know how they came to be):
> 
> ```
>     both added:      course/tests/reportbuilder/datasource/courses_test.php
>     added by them:   enrol/license/classes/task/cron_task.php
>     added by us:     lib/classes/task/task_lock_cleanup_task.php
>     both added:      lib/tests/task/manager_test.php
>     both deleted:    mod/quiz/report/statistics/classes/task/quiz_statistics_cleanup.php
> ```
> 
> added by them: means added by iomad, so we do:
> 
> > git checkout iomad404/IOMAD_400_STABLE -- /path/to/file
> 
> added by us: added by moodle so we do:
> 
> > git checkout origin/MOODLE_401_STABLE -- lib/classes/task/task_lock_cleanup_task.php
> 
> OR
> 
> > git reset -- /path/to/file
> > git checkout -- /path/to/file
> 
> For both added and both deleted, just:
> 
> > git reset -- /path/to/file
> 
> In this case, i did:
> 
> > git reset -- course/tests/reportbuilder/datasource/courses_test.php
> > git checkout iomad404/IOMAD_400_STABLE -- enrol/license/classes/task/cron_task.php
> > git reset -- lib/classes/task/task_lock_cleanup_task.php
> > git checkout -- lib/classes/task/task_lock_cleanup_task.php
> > git reset -- lib/tests/task/manager_test.php
> > git reset -- mod/quiz/report/statistics/classes/task/quiz_statistics_cleanup.php
> 
> Then:
> 
> > git status

Thanks, Understood.
Appreciate the efforts.
Will run on test server.

**Comment by rmeske** [comment]
@turf212,

Thank you Derick.  At one time I remember seeing a release cycle for IOMAD that showed the delay.  I was unable to find it on the website so thought I would ask.  Is there a targeted month yet?

**Comment by jlb224** [comment]
Hello, do you have an estimated release date for iomad 4.1?

**Comment by muthuswamywhbs** [comment]
Expecting tentative release date for iomad 4.1

**Comment by iomad** [comment]
Yes.  2 minutes ago. ;)
