### ISSUE TITLE
Script for moodle upgrade with iomad

### ISSUE THREAD

**Issue by thundor** [iomad/iomad#1746]
In an attempt to offer my contribution in thanks for iomad,
I attached a runnable php (index.php) with which i was able to upgrade moodle to the latest version while keeping the iomad changes.
it uses the xdiff_file_diff php function so requires xdiff to be installed on the server.
the second attached file is a blank githash.php used by index.php
these 2 files need to be put inside a folder, along with some other folders that represent 
- the latest version of moodle
- the latest version of iomad
- the current site
- the moodle of the same version as the latest version of iomad
- the moodle of the same version as current site
all are configurable in index.php

you can use this script to generate a iomad version of the latest moodle.

[index.php.txt](https://github.com/iomad/iomad/files/10185793/index.php.txt)
[githash.php.txt](https://github.com/iomad/iomad/files/10185862/githash.php.txt)

**Comment by dallenk** [comment]
very interesting.. what happens if you update with your script, then later use the standard method to upgdate IOMAD?  do conflicts prevent it from working?

**Comment by thundor** [comment]
> very interesting.. what happens if you update with your script, then later use the standard method to upgdate IOMAD? do conflicts prevent it from working?
Unfortunately there is no short answer to this question.

Standard-Upgrading IOMAD directly into the site means upgrading to Iomad latest version, but with a slightly older version of Moodle then the actual latest.
This script is to update both IOMAD and Moodle to latest (or any version, really) while keeping custom-made changes to core files.

So basically, the developers of iomad could create a cron job to run a modified version of this script automatically to keep iomad git repository at the latest of moodle version every few hours for example.
With few changes (elimnations really), the script can be used strictly for moodle migration, keeping custom changes intact.

Choosing to standard-upgrade iomad means you haven't made any core changes or are willing to migrate them manually. (very painful sometimes)
Opting for standard-upgrade after using this script makes as much sense as the sentence above.

**Comment by thundor** [comment]
I'll provide extra details if necessary

**Comment by turf212** [comment]
We already have an IOMAD MASTER branch which is kept up to date with Moodle's Master branch and tat has all of the latest IOMAD commits in.  Creating the new version isn't really the issue.  It's what gets broken by changes in the Moodle code with respect to the multi-tenancy.

**Comment by turf212** [comment]
Oh - and not to be ungrateful for the work at all :)

The IOMAD versions are kept purposefully to the minor point releases.  If you are using git (which you should be :) then you can always merge in the latest Moodle weekly to your local IOMAD branch if you wanted to be at the latest release.  For the most part that will just work.  Only if there are conflicts would there be any issues.
