### ISSUE TITLE
Course Upload

### ISSUE THREAD

**Issue by DennieW** [iomad/iomad#1747]
Is there anyway that courses can be bulk uploaded from the IOMAD dashboard as is the case with users?
The challenge I'm having is when the _Site Administration >> Courses >>Upload Courses_  option is used, the courses show up in all companies.
If we have a bulk import by company this will alow for company specific courses to be imported.

If anyone has a work around to this i would really appreciate some assistance.

Thanks in advance

**Comment by jlb224** [comment]
We are looking for similar - a bulk assign of courses to companies. So we can assign course to multiple companies at same time.
