### ISSUE TITLE
RESOLVED - IOMAD 4.0.5 - Functionality - IOMAD Dashboard (Edit User / Password Reset)

### ISSUE THREAD

**Issue by RedQon1** [iomad/iomad#1751]
Hey team,

I wanted to report missing functionality in **IOMAD 4.0.5** Previously in **IOMAD 3.7**, Company Managers were able to reset/edit learner details through the IOMAD dashboard block by navigating to "**Users > Edit Users**". 

Currently in **4.0.5**, the drop down only offers three (3) options:

- Change course enrolments
- Change course licenses
- User report

Where in **3.7**, there were seven (7) options:

- Edit
- Re-send user details
- Delete
- Suspend
- Change course enrolments
- Change course licenses
- User report

**Comparison**

**IOMAD 4.0.5** - Company Admin Edit Users (Taken from IOMAD Demo site)
https://p197.p4.n0.cdn.getcloudapp.com/items/GGuJprrQ/0bdddb85-e478-4e89-b957-e53556f606f0.png

**IOMAD 3.7** - Company Admin Edit Users (Taken from our DEV instance)
https://p197.p4.n0.cdn.getcloudapp.com/items/nOu1vnoB/d618b58b-79a4-4cfc-ae57-d6150987f674.png

Even though the "Edit" URL is not available on the 4.0.5 edit users page, if you navigate to that specfic user ID by adding this to the end of the URL, it will go through to the usual IOMAD Edit User page.

**_/blocks/iomad_company_admin/editadvanced.php?id=####_**

So it seems the functionality is still there but the option(s) have seemed to be removed/hidden?

**Comment by dallenk** [comment]
Did you enable the edit slider in the top right corner?  Many things changed with the upgrade

**Comment by RedQon1** [comment]
@sgvfr - Thank you! I was playing around with all the permissions and the answer was staring at me on the top right of the screen. Apologies for the time waste!
