### ISSUE TITLE
API function: lock_iomad_company_admin_enrol_users - dml_write_exception

### ISSUE THREAD

**Issue by rmeske** [iomad/iomad#1752]
IOMAD 4.0.5

I am using the External APIs to create users, assign them to a company & department, and enroll them into courses.  I am using the following functions in the order shown:

1. core_user_create_users
2. block_iomad_company_admin_assign_users
3. block_iomad_company_admin_enrol_users

The first two work perfectly, but the third is giving an error.  Based on the documentation "block_iomad_company_admin_enrol_users" accepts the following data:

- roleid int   //Role to assign to the user
- userid int   //The user that is going to be enrolled
- courseid int   //The course to enrol the user role in
- timestart int  Optional //Timestamp when the enrolment start
- timeend int  Optional //Timestamp when the enrolment end
- suspend int  Optional //set to 1 to suspend the enrolment
- quantity int  Optional //Number of items purchased

The error being returned is:
{
    "exception": "dml_write_exception",
    "errorcode": "dmlwriteexception",
    "message": "Error writing to database",
    "debuginfo": "Column 'allocation' cannot be null\nINSERT INTO mdl_companylicense (name,allocation,validlength,startdate,expirydate,companyid,instant) VALUES(?,?,?,?,?,?,?)\n[array (\n  0 => '6-2-1672438691',\n  1 => NULL,\n  2 => 1703974691,\n  3 => 1672438691,\n  4 => 1672438721,\n  5 => '2',\n  6 => 1,\n)]"
}

Is the documentation missing a parameter, or does the function have an error, or am I missing a step?

**Comment by rmeske** [comment]
Update

I located the function and found that "quantity" is a "Required" parameter as it is mapped to "allocation".  

What I would like to know is the appropriate value to pass.  Should it always be 1 for an active user?

**Comment by turf212** [comment]
Quantity should always be at least one.  The function you are calling will create a license for this user/course (because the course is a licensed based course).  If you don't pass the number of licenses slots which are to be created for that license it will fail.
