### ISSUE TITLE
Company suspended mail will be sent only after reactivation of the company

### ISSUE THREAD

**Issue by LarsDreier** [iomad/iomad#1753]
**Issue:**
The user receives the "Your company was suspended" mail only after the suspension is over.

**Steps to reproduce:**
1. Create a company
2. Create a user within the company and make it company manager
3. Suspend the company
4. Wait until the cronjob fired once. You will not have received any mail.
5. Unsuspend the company. You will receive 2 emails. One stating your company got reactivated, one saying your company got suspended.

**Why is this happening?**
With the suspension of the company the user will be suspended, too. The mails are added to a sending queue, but suspended users are not processed. But as there is no clearing mechanism for the queue it will wait until it is allowed to send again, firing both mails at this point.

**Comment by turf212** [comment]
Fixed in commit 94e81135c20c4d4f5d2c1a5b08267e4c350e1a7a

Thanks for the bug report.
