### ISSUE TITLE
Duplicate Course or add course from basic Moodle to Iomad

### ISSUE THREAD

**Issue by ShawnWhy** [iomad/iomad#1755]
Hi, may I ask if there is a way to duplicate a course in IOMAD? or may I ask if there is a way to manually migrate a course from moodle to appear in IOMAD?

thank you.

**Comment by turf212** [comment]
You can add any unassigned Moodle courses to a company or any closed shared courses which are already assigned to another company.  If you go to the IOMAD dashboard Courses tab and click on Assign to company.

**Comment by Coderra** [comment]
I am facing a similar issue whereby I have upgraded Moodle to Iomad. I have created a company and assigned the Moodle courses to that company, but when I create a new company, I cannot assign the same Moodle course to the new company. Is there a solution for this? Basically I am wanting to create multiple companies and assign to them a selection of courses from Moodle. But when I assign a course to one company, it cannot be assigned to another.

**Comment by ShawnWhy** [comment]
thanks so much!

**Comment by turf212** [comment]
@Coderra - Once you have assigned the courses to one company you can change how these are viewed within the IOMAD course settings page within the dashboard.  Here you can change the course sharing from None to Open (every company will see this course) or Closed (only companies which have been assigned the course can see it).  Once you've changed this to what you want you will be able to access the courses in the other tennant.
