### ISSUE TITLE
Company Managers cannot view certificates

### ISSUE THREAD

**Issue by Blacksheeprules** [iomad/iomad#1757]
Company managers when made also get client course access rights. I have a recent IOMAD using moodle 4.03. The managers are not able to view their own certificate or other users certificates. Is this by design? When I looked at the permissions of a client course access they should be able to view a certificate? Can you clarify this. What would I do if I had some managers that wanted to test the course and the certificate?

**Comment by enrarelloem** [comment]
Can admins see the certificates?
We have a similar problem where no one can see (some) certificates.
A workaround is to use Site administration --> Recreate stored certificates
After restoring, the certificates appear in e.g. Completion report by course in the Iomad dashboard.

**Comment by turf212** [comment]
If the certificates are not generated on course completion - e.g. the conditional access to the certificate happens after the course is marked as complete, then the certificate wont get stored so won't be available to the Managers.  If you check your conditional access for the certificate and ensure that it's available on course completion it will show up as expected.  This will absolutely be the case if you can go back and recreate the certificates without issue later.
