### ISSUE TITLE
Blank error pop-up & missing strings

### ISSUE THREAD

**Issue by rmeske** [iomad/iomad#1758]
Hello,

I am having the same issue on two separate installs on the same computer.
1. The original was installed at version 4.0.4, then upgraded to 4.0.5 and then 4.0.6
2. The second was installed at version 4.0.5, then upgraded to 4.0.6

I am using:
Apache 2.4.54
PHP 7.4.33 
MySQL 8.0.28

On the first visit to Site Administration - Browse list of users, I get a pop error message that has a heading of undefined with all the other fields blank.  I have turned on debugging - Developer mode, and Display debug messages but nothing is shown on screen or in the log.  After dismissing everything works and it does not come back during the same session unless I edit a user profile and when returning it comes back.
![image](https://user-images.githubusercontent.com/3299975/214613519-f0955b38-f923-42e4-bfc1-a43930553f35.png)

Though I doubt that it is related, when I turned on debugging I did find some occasionally errors with missing strings. For example, when viewing the definition of a role:
`Invalid get_string() identifier: 'trainingevent:resetattendees' or component 'mod_trainingevent'. Perhaps you are missing $string['trainingevent:resetattendees'] = ''; in mod/trainingevent/lang/en/trainingevent.php?`
`Invalid get_string() identifier: 'iomad_track:importfrommoodle' or component 'local_iomad_track'. Perhaps you are missing $string['iomad_track:importfrommoodle'] = ''; in  ******/local/iomad_track/lang/en/local_iomad_track.php?
`

I have manually run the upgrade from the command line but it says "No upgrade needed for..."

These seem to be annoying errors that do not have an obvious impact to the system.  

Any ideas on how to fix them would be appreciated.

**Comment by turf212** [comment]
Thanks for the note - the missing strings were all added in a2702e7651d985bf33167919177b0a2886c6d2df.
