### ISSUE TITLE
my/courses.php not using new block in iomad4

### ISSUE THREAD

**Issue by jlb224** [iomad/iomad#1759]
Hello, 
when visiting my/courses.php iomad4 loads the old 'My courses' block and a copy of the dashboard navtabs, and not the new 'My courses > Course overview' block present in Moodle 4. Is there a reason why we cannot use the new My courses block, and why those same blocks appear now on two separate screens?

![image](https://user-images.githubusercontent.com/26649166/215265627-9e9ba05d-e0a3-4f46-b400-8e2531151e18.png)

![image](https://user-images.githubusercontent.com/26649166/215265642-aa8e9bb1-3c65-41bf-a4bf-e8cd86b541fe.png)

Moodle block
![image](https://user-images.githubusercontent.com/26649166/215265716-6f03082c-5155-4338-a118-667bcbcdf674.png)

**Comment by jlb224** [comment]
Also, do we need the nav link to Iomad dashboard when it has the same block on Dashboard? It might be confusing to have two dashboards

![image](https://user-images.githubusercontent.com/26649166/215265874-9c3e6b58-b6e3-4875-afa6-bb06b0fde31e.png)

**Comment by turf212** [comment]
In 4.0  we moved the IOMAD dashboard to it's own page in the same style as the Site administration links/pages.  The block no longer needs to be on a users dashboard (as you say it could cause confusion) which tidies these up.  It wasn't removed automatically as this would have caused a UI change that many may not have expected.

IOMAD has it's own My Courses block - which is what it displays.  The main reason for this is that there is a third state for users other than enrolled and not enrolled where a user has been given a license for a course that they haven't yet used - so there is a potential enrolment.  I can see in 4.1 that the core Moodle block now supports plugins and this is something I'm considering for that release. (which is real soon now).

**Comment by jlb224** [comment]
@turf212 in relation to the above, the my courses block appears on both /my and my/courses pages. Because we do not want it repeated on two pages, I tried to delete it from /my but this results in it deleting it from /my/courses at the same time. I can re-add the block onto /my but 

- is this your modified version?
- it does not readd it back my/courses.

**Comment by turf212** [comment]
Moodle moved away from the dashboard being where the courses block is shown to the /courses page instead.  So it's been put on both places for now as it mimics their courseoverview block.
