### ISSUE TITLE
"Exception occurred while processing privacy data"

### ISSUE THREAD

**Issue by dallenk** [iomad/iomad#1760]
After completing the data removal of old users, i received this email several times (one for each user processed)  using the built-in Moodle feature:  Site Administration / users / Data requests.

As the administrator I authorized the requests for users who are no longer on the system.. some time later I received the emails.

Exception occurred while calling local_iomad_track\privacy\provider::delete_data_for_user.
This means that plugin local_iomad_track did not complete the processing of data. The following exception information may be passed on to the plugin developer:
Error reading from database

#0 /var/www/vhosts/domain.ca/iomad/lib/dml/moodle_read_slave_trait.php(291): moodle_database->query_end()
#1 /var/www/vhosts/domain.ca/iomad/lib/dml/mysqli_native_moodle_database.php(1273): mysqli_native_moodle_database->query_end()
#2 /var/www/vhosts/domain.ca/iomad/lib/dml/moodle_database.php(1500): mysqli_native_moodle_database->get_records_sql()
#3 /var/www/vhosts/domain.ca/iomad/lib/dml/moodle_database.php(1451): moodle_database->get_records_select()
#4 /var/www/vhosts/domain.ca/iomad/local/iomad_track/classes/privacy/provider.php(208): moodle_database->get_records()
#5 /var/www/vhosts/domain.ca/iomad/lib/moodlelib.php(8141): local_iomad_track\privacy\provider::delete_data_for_user()
#6 /var/www/vhosts/domain.ca/iomad/privacy/classes/manager.php(578): component_class_callback()
#7 /var/www/vhosts/domain.ca/iomad/privacy/classes/manager.php(611): core_privacy\manager::component_class_callback()
#8 /var/www/vhosts/domain.ca/iomad/privacy/classes/manager.php(415): core_privacy\manager->handled_component_class_callback()
#9 /var/www/vhosts/domain.ca/iomad/admin/tool/dataprivacy/classes/task/process_data_request_task.php(138): core_privacy\manager->delete_data_for_user()
#10 /var/www/vhosts/domain.ca/iomad/lib/cronlib.php(341): tool_dataprivacy\task\process_data_request_task->execute()
#11 /var/www/vhosts/domain.ca/iomad/lib/cronlib.php(198): cron_run_inner_adhoc_task()
#12 /var/www/vhosts/domain.ca/iomad/lib/cronlib.php(76): cron_run_adhoc_tasks()
#13 /var/www/vhosts/domain.ca/iomad/admin/cli/cron.php(178): cron_run()
#14 {main}

**Comment by turf212** [comment]
Table being checked here wasn't correct.  I've updated it so that the SQL will work as it should have.

**Comment by dallenk** [comment]
This seems to be back.

```
Exception occurred while calling local_iomad_track\privacy\provider::delete_data_for_user.
This means that plugin local_iomad_track did not complete the processing of data. The following exception information may be passed on to the plugin developer:
Error reading from database


#0 /var/www/vhosts/domain.ca/iomad/lib/dml/moodle_read_slave_trait.php(293): moodle_database->query_end()
#1 /var/www/vhosts/domain.ca/iomad/lib/dml/mysqli_native_moodle_database.php(1278): mysqli_native_moodle_database->query_end()
#2 /var/www/vhosts/domain.ca/iomad/local/iomad_track/classes/privacy/provider.php(211): mysqli_native_moodle_database->get_records_sql()
#3 /var/www/vhosts/domain.ca/iomad/lib/moodlelib.php(8152): local_iomad_track\privacy\provider::delete_data_for_user()
#4 /var/www/vhosts/domain.ca/iomad/privacy/classes/manager.php(578): component_class_callback()
#5 /var/www/vhosts/domain.ca/iomad/privacy/classes/manager.php(611): core_privacy\manager::component_class_callback()
#6 /var/www/vhosts/domain.ca/iomad/privacy/classes/manager.php(415): core_privacy\manager->handled_component_class_callback()
#7 /var/www/vhosts/domain.ca/iomad/admin/tool/dataprivacy/classes/task/process_data_request_task.php(138): core_privacy\manager->delete_data_for_user()
#8 /var/www/vhosts/domain.ca/iomad/lib/cronlib.php(367): tool_dataprivacy\task\process_data_request_task->execute()
#9 /var/www/vhosts/domain.ca/iomad/lib/cronlib.php(198): cron_run_inner_adhoc_task()
#10 /var/www/vhosts/domain.ca/iomad/lib/cronlib.php(76): cron_run_adhoc_tasks()
#11 /var/www/vhosts/domain.ca/iomad/admin/cli/cron.php(178): cron_run()
#12 {main}
```
