### ISSUE TITLE
Error reading from database

### ISSUE THREAD

**Issue by Fujimaru-Kun** [iomad/iomad#1761]
Version: iomad-IOMAD_37_STABLE

Debug info: Not unique table/alias: 'ic'
SELECT cc.id, cc.userid, cc.courseid as courseid, c.fullname as coursefullname, c.summary as coursesummary, c.visible, ic.hasgrade
FROM mdl_local_iomad_track cc
JOIN mdl_course c ON (c.id = cc.courseid)
JOIN mdl_iomad_courses ic ON (c.id = ic.courseid and cc.courseid = ic.courseid)
JOIN mdl_user_enrolments ue ON (ue.userid = cc.userid)
JOIN mdl_enrol e ON (e.id = ue.enrolid AND e.courseid = c.id)
LEFT JOIN mdl_iomad_courses ic ON (c.id = ic.courseid AND cc.courseid = ic.courseid)
WHERE cc.userid = ?
AND c.visible = 1
AND cc.timecompleted IS NULL
AND ue.timestart != 0
[array (
0 => '2',
)]
Error code: dmlreadexception
Stack trace:
line 486 of /lib/dml/moodle_database.php: dml_read_exception thrown
line 1247 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()
line 58 of /blocks/mycourses/locallib.php: call to mysqli_native_moodle_database->get_records_sql()
line 71 of /blocks/mycourses/classes/output/main.php: call to mycourses_get_my_completion()
line 46 of /blocks/mycourses/classes/output/renderer.php: call to block_mycourses\output\main->export_for_template()
line 504 of /lib/outputrenderers.php: call to block_mycourses\output\renderer->render_main()
line 57 of /blocks/mycourses/block_mycourses.php: call to plugin_renderer_base->render()
line 326 of /blocks/moodleblock.class.php: call to block_mycourses->get_content()
line 235 of /blocks/moodleblock.class.php: call to block_base->formatted_contents()
line 1181 of /lib/blocklib.php: call to block_base->get_content_for_output()
line 1239 of /lib/blocklib.php: call to block_manager->create_block_contents()
line 685 of /lib/outputrenderers.php: call to block_manager->ensure_content_created()
line 94 of /theme/iomad/classes/output/core_renderer.php: call to core_renderer->standard_head_html()
line 219 of /lib/mustache/src/Mustache/Context.php: call to theme_iomad\output\core_renderer->standard_head_html()
line 138 of /lib/mustache/src/Mustache/Context.php: call to Mustache_Context->findVariableInStack()
line 31 of /var/www/moodledata/localcache/mustache/1675135021/iomad/__Mustache_71b3f41fa2e3ab3d8e00a5d2c0bbecb1.php: call to Mustache_Context->findDot()
line 13 of /var/www/moodledata/localcache/mustache/1675135021/iomad/__Mustache_855b38ba8b271c88f7112d528adf78d9.php: call to __Mustache_71b3f41fa2e3ab3d8e00a5d2c0bbecb1->renderInternal()
line 67 of /lib/mustache/src/Mustache/Template.php: call to __Mustache_855b38ba8b271c88f7112d528adf78d9->renderInternal()
line 195 of /lib/outputrenderers.php: call to Mustache_Template->render()
line 56 of /theme/iomad/layout/columns2.php: call to renderer_base->render_from_template()
line 1416 of /lib/outputrenderers.php: call to include()
line 1346 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
line 164 of /my/index.php: call to core_renderer->header()

**Comment by Fujimaru-Kun** [comment]
Remove
 
LEFT JOIN {iomad_courses} ic ON (c.id = ic.courseid AND cc.courseid = ic.courseid)

iomad/blocks/mycourses/locallib.php

**Comment by turf212** [comment]
IOMAD 3.7 is no longer being actively supported.  We are supporting 3.9, 3.10 (kinda as it's not supported by Moodle HQ any more but if there are code fixes for our plugins they get pushed) and 4.0.
