### ISSUE TITLE
Upgrading 3.4 -> 3.6, iomad_tracks - PHP Fatal error:  Allowed memory size of 

### ISSUE THREAD

**Issue by rmeske** [iomad/iomad#1763]
Hello, I am in the process of upgrading an IOMAD 3.4.3+ site that has been running several years.  While updating to IOMAD 3.6, I am receiving a "PHP Fatal error:  Allowed memory size of  x bytes exhausted (tried to allocate 20480 bytes) in my domain/lib/dml/mysqli_native_moodle_database.php on line 1252."

I increased the memory_limit to 3000M and still received the error.  It gets to the point of "rest start" in the upgrade.

```
local_iomad_track
starting 1675722756 coursename end 1675722767 companies/departments start 1675722767 companies/departments end 1675722811 licenses start 1675722811 licenses end 1675722852
2018081900: Success (96.31 seconds)
starting 1675722853 current start 1675722854 current end 1675722862 rest start 1675722866
```

It takes about 45 minutes before it crashes.  

I don't know that this will fix the issue, but I am assuming that the following may be causing the memory issue.

```
$rest = $DB->get_records_sql("SELECT clu.*,cl.name AS licensename, cl.companyid, c.fullname AS coursename FROM {companylicense_users} clu
                                      JOIN {companylicense} cl ON (clu.licenseid = cl.id)
                                      JOIN {course} c ON (clu.licensecourseid = c.id)
                                      LEFT JOIN {local_iomad_track} lit ON (clu.licensecourseid = lit.courseid AND clu.userid = lit.userid AND clu.issuedate = lit.licenseallocated)
                                      WHERE lit.id IS NULL");
```

 Is there any possibility of breaking the upgrade process if I incorporate a limit/offest for the above and add an outer loop to read through all records?

**Comment by iomad** [comment]
The upgrade runs some routines to convert over to the new reporting structures.  You could simply skip that part of the upgrade and then populate the mdl_local_iomad_track table by hand.  The table was updated to hold everything the reports could need (in a BI style) to speed up display.  If you have a lot of data then that will be the issue.

**Comment by turf212** [comment]
I've also just added some code which significantly speeds this process up too.  Patches were provided in #1735
