### ISSUE TITLE
Edit users coding error for companydepartmentmanger role

### ISSUE THREAD

**Issue by dallenk** [iomad/iomad#1764]
I've believe I have given the role access to view/edit users profiles but I see this error when trying to Edit Users from the dashboard.
moodle/user:editprofile   Allow
moodle/user:viewalldetails   Allow
moodle/user:viewuseractivitiesreport   Allow
moodle/user:viewdetails   Allow

12 Users

Coding error detected, it must be fixed by a programmer: Options for select element must contain an option for the specified value

Am I missing a permission by chance?

Coding error detected, it must be fixed by a programmer: Options for select element must contain an option for the specified value
Debug info:
Error code: codingerror
Stack trace:

    line 183 of /lib/classes/output/inplace_editable.php: coding_exception thrown
    line 91 of /blocks/iomad_company_admin/classes/output/user_roles_editable.php: call to core\output\inplace_editable->set_type_select()
    line 147 of /blocks/iomad_company_admin/classes/tables/editusers_table.php: call to block_iomad_company_admin\output\user_roles_editable->__construct()
    line 832 of /lib/tablelib.php: call to block_iomad_company_admin\tables\editusers_table->col_managertype()
    line 2016 of /lib/tablelib.php: call to flexible_table->format_row()
    line 2140 of /lib/tablelib.php: call to table_sql->build_table()
    line 656 of /blocks/iomad_company_admin/editusers.php: call to table_sql->out()

**Comment by dallenk** [comment]
i think it will be a similar issue as https://github.com/iomad/iomad/issues/1724   i tried to follow that and fix myself but I fail at coding ha

This also seems to appear when edit mode is enabled.

**Comment by turf212** [comment]
This is the in place editable element for the roles which the manager can assign people as. Department managers should be able to assign other department managers so check if block/iomad_company_admin:assign_department_manager is allowed in their role?

**Comment by dallenk** [comment]
Hi Derek, Yes that user role has that permission.

**Comment by turf212** [comment]
Is this still an issue after you refreshed your code?

**Comment by dallenk** [comment]
Good morning, i'll be checking this today.  I have discovered doing a dist-upgrade from ubuntu 20.04.x to 22.xx, changing to mariadb 10.4.x and the seemingly automatic upgrade to php8.1 from 7.4 .. is a serious pain in my arse. haha.

**Comment by dallenk** [comment]
This appears to be fixed, updated to the latest git code now.
