### ISSUE TITLE
Everytime I go to home page after the new update it states "Unknown Category"

### ISSUE THREAD

**Issue by ludz007** [iomad/iomad#1765]
Hi there, 

Everytime I login as an authenticated user and go to home page, or dashboard to view the courses, i get the following error:

![image](https://user-images.githubusercontent.com/52195007/217915550-887d98e0-41e1-485b-9d2e-b41b2b1053eb.png)

I dont know what to do... this was after the latest update

**Comment by dallenk** [comment]
Curious, can you see if you have "open shared" courses to other companies?  Change temporarily to closed sharing and see if it clears the error. 

As an authenticated user change the url to domain.com/?redirect=0 and that should put you in the user's home tab??  Could be similar to my issue as well

**Comment by mikeaveli007** [comment]
I had this same issue even though I was on commit f4e5832 and it was strangely only on one user.  If I removed the user from a company the error went away.  If I re assigned the same user back to the company, error came back.  I noticed this particular user had their name and email in all CAPS so I changed to lower case and it resolved the issue in my case.

**Comment by ludz007** [comment]
Hi guys, thanks for the replies. Nothing worked... Had to restore a previous backup and pull changes once again... There is no error now. Thanks... Just want to avoid this in the future again
