### ISSUE TITLE
Fresh installation -  error with local_report_user_logins

### ISSUE THREAD

**Issue by dallenk** [iomad/iomad#1766]
Linux sandbox 5.15.0-60-generic #66-Ubuntu SMP Fri Jan 20 14:29:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
PHP 7.4.33 (cli) (built: Feb 14 2023 18:31:54) ( NTS )
mysql  Ver 15.1 Distrib 10.6.12-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper

all checks pass (except for ssl on the sandbox server)

**_local_report_user_logins_**
Dealing with 2 users
Error writing to database

[More information about this error](https://docs.moodle.org/401/en/error/moodle/dmlwriteexception)

It is usually not possible to recover from errors triggered during installation, you may need to create a new database or use a different database prefix if you want to retry the installation.

Debug info: Table 'sandbox_400_firetrain_ca.mdl_logstore_standard_log' doesn't exist
INSERT INTO mdl_local_report_user_logins (userid, created, firstlogin, lastlogin, logincount, modifiedtime)
SELECT id as userid,
timecreated,
NULLIF(firstaccess,0) AS firstaccess,
NULLIF(currentlogin,0) AS currentlogin,
IF (currentlogin = 0, 0, IFNULL((SELECT COUNT(id) FROM mdl_logstore_standard_log l WHERE u.id = l.userid AND eventname = ?),0)) AS totallogins,
1677210467 as modifiedtime
FROM mdl_user u
[array (
0 => '\\core\\event\\user_loggedin',
)]
Error code: dmlwriteexception×Dismiss this notification
Stack trace:
line 497 of /lib/dml/moodle_database.php: dml_write_exception thrown
line 293 of /lib/dml/moodle_read_slave_trait.php: call to moodle_database->query_end()
line 1172 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->query_end()
line 46 of /local/report_user_logins/db/install.php: call to mysqli_native_moodle_database->execute()
line 767 of /lib/upgradelib.php: call to xmldb_local_report_user_logins_install()
line 1953 of /lib/upgradelib.php: call to upgrade_plugins()
line 721 of /admin/index.php: call to upgrade_noncore()

**Comment by dallenk** [comment]
refreshing the screen, the installation does continue and seems to complete fine.

**Comment by turf212** [comment]
One of the speed fixes assumes that the table exists.  I've added code to check first.
