### ISSUE TITLE
background image / login page background doesn't seem to work on newest code

### ISSUE THREAD

**Issue by dallenk** [iomad/iomad#1767]
console shows 404 for the background image, and login page background image, working site shows a url like:

`url(//www.domain.ca/pluginfile.php/1/theme_iomadboost/backgroundimage/1676770489/bgimage.jpg)
`

Site that fails is a little different and a "-1" in the url. and the location in quotes.

`url("//sandbox.domain.ca/pluginfile.php/1/theme_iomadboost/backgroundimage/-1/bgimage.jpg")`

Direct access to the image url shows a stack trace, when a simple 404 should be shown.

Sorry, the requested file could not be found

Debug info:
Error code: filenotfound×Dismiss this notification
Stack trace:
line 2140 of /lib/filelib.php: moodle_exception thrown
line 95 of /theme/iomadboost/lib.php: call to send_file_not_found()
line 5267 of /lib/filelib.php: call to theme_iomadboost_pluginfile()
line 44 of /pluginfile.php: call to file_pluginfile()

**Comment by dallenk** [comment]
bump

**Comment by turf212** [comment]
Sorted now.
