### ISSUE TITLE
Suspended Companies display in Company Dropdown For System Admins

### ISSUE THREAD

**Issue by BananaRama203** [iomad/iomad#177]
Suspended Companies display in company select drop down box.

**Comment by turf212** [comment]
The suspended companies show a (s) next to them at the end of the name.  Otherwise how do you unsuspend a company?

I'll make this an enhancement so that there is a tick box to show suspended companies or not.

**Comment by BananaRama203** [comment]
The idea was to unsuspend companies within Manage companies.

That would be great though. Thanks :)

**Comment by turf212** [comment]
This was added to Iomad 2.8 (I should have closed it then... :)

**Comment by thepurpleblob** [comment]
Hi,

I've got some new pizza recipe for you, you should try it, more info here http://accept.assistnational.com/e4cctbz

Later, howard@e-learndesign.co.uk
