### ISSUE TITLE
Exception thrown while using iomad

### ISSUE THREAD

**Issue by xntstack** [iomad/iomad#1770]
This anomalous behavior has been reported to me. While using iomad this exception is raised: "Argument 1 passed to core_course_list_element::__construct() must be an instance of stdClass null given called in [dirroot]/course/classes/category.php on line 1649".
Looking at this line there are two versions to this call. The second seems to be more robust by actually checking if the value is not empty. The error then disappears by commenting out line 1649.

https://github.com/iomad/iomad/blob/68b74de3be80710c9d85e1b43865fad4c016d2b8/course/classes/category.php#L1649

I'm currently using the branch IOMAD_401_STABLE.

**Comment by turf212** [comment]
Weird - that code was from 2019 and was added in with the check commented out.  Thanks for reporting!
