### ISSUE TITLE
Theme Customization

### ISSUE THREAD

**Issue by anandbobby** [iomad/iomad#1771]
I have a Iomad site running perfectly but when I use a different theme (RemUI) my companies do not display their personalized logos. Is there a way to make this work? Any help is much appreciated

**Comment by turf212** [comment]
This depends on a couple of things:
1 - If your theme is using the core Moodle logos
2 - The version of IOMAD you are using.

If your theme doesn't use the core Moodle logos then it won't work with the company logos.  4.0 converts the core logos to be the company logos and 4.1+ use the core logo and favicons areas to have different ones per tenant.

The other option is to get that theme converted to one which works with IOMAD (which will also allow for the per tenant CSS and menus).  If you feel like doing this yourself then look at the difference between the Boost and IOMADBoost or the Classic and IOMAD Bootstrap themes (the IOMAD themes are copies of those with extra code for this).  If you don't then you can check in with us info (at) e-learndesign.co.uk and we can do this for you.  New versions of the theme would need the work re-applying - which is something to be aware of at time of upgrade.
