### ISSUE TITLE
Branch name and version mis-match?

### ISSUE THREAD

**Issue by rmeske** [iomad/iomad#1774]
Hello,

The latest branch name is IOMAD_401_STABLE but the version file is 4.1.  Is this branch truly in line with Moodle 4.1?

**Comment by turf212** [comment]
Moodle is using the branch name MOODLE_401_STABLE for Moodle 4.1,  We are using the same branch naming convention.

**Comment by rmeske** [comment]
Thank you.  I hadn't checked Moodle's branches.
