### ISSUE TITLE
error/An error occurred whilst communicating with the server

### ISSUE THREAD

**Issue by kameshfourbends** [iomad/iomad#1775]
My PHP version 8.1.0, Xampp V.3.3.0, MariaDB ,
10.4.25-MariaDB 

1) Clone the Git repo and switch to this branch IOMAD_401_STABLE
2) Installed Iomad
3) After complete the installation I got this issue "error/An error occurred whilst communicating with the server"
![image](https://user-images.githubusercontent.com/31654071/225237445-dcf77981-9c23-492b-b730-d785cf225d29.png)

Any one help me for fixing this issue.

**Comment by DakshKK** [comment]
Did you figure out how to fix this issue? I've got the same issue during my installation and it's stuck now.

**Comment by willianmano** [comment]
I have the same issue here. A solution was install via command line.

`php admin/cli/install.php`

The same error will appear if you want to install a new plugin. The solution was also use the command line.

`php admin/cli/upgrade.php`

**Comment by turf212** [comment]
The deprecated issues have been fixed a while ago - it's PHP8 and it needed the variables of functions to all have default values after one has a default value.  The specific error here is when the browser cannot start the session with the site. So if you are upgrading in another browser page - close it and open it in another browser it gets confused.

CLI upgrade will sort.
