### ISSUE TITLE
MissingParam when suspending.

### ISSUE THREAD

**Issue by BananaRama203** [iomad/iomad#178]
I had the following issue reported by a Company Manager

> I want to edit our list of students by archiving carers and staff who are no longer with us. The first page comes up no problem and I can archive a student, but when it returns to the list page, I can’t get to page 2 or page 3. The error code which comes up is “missingparam”

**Comment by turf212** [comment]
Error is - 

A required parameter (sesskey) was missing

Debug info: 
Error code: missingparam
Stack trace:
line 463 of /lib/setuplib.php: moodle_exception thrown
line 548 of /lib/moodlelib.php: call to print_error()
line 73 of /lib/sessionlib.php: call to required_param()
line 257 of /blocks/iomad_company_admin/editusers.php: call to confirm_sesskey()

Confirmed as a bug.

**Comment by turf212** [comment]
The suspend/unsuspend parameter wasn't getting cleared after the user was being suspended/unsuspended.

**Comment by turf212** [comment]
closed in 2.7 and 2.8
