### ISSUE TITLE
iomad 41 - Show chart data obscured in 'Completion report by course'

### ISSUE THREAD

**Issue by jlb224** [iomad/iomad#1782]
Hello, 
in iomad4.1 [root]/local/report_completion/index.php, 
1) the formatting is a bit off (simply fixed with a bit of margin: 0.25rem on the buttons, and some padding-bottom: 2rem on .path-local-report_completion .generaltable td.cell.c2 - or whatever spacing is preferred)
2) more importantly, after clicking Show chart data, the overlay is not visible because it sits behind the subsequent doughnut chart.
![image](https://user-images.githubusercontent.com/26649166/226560566-6b98a40e-88b5-4f51-aa2f-ff2840154a96.png)

**Comment by turf212** [comment]
Setting the max width/height for the chart image only fixes this.  Thanks for the update.  fix has been pushed.
