### ISSUE TITLE
version: 4.1 - $string['sectionidalreadyinuse'] is missing

### ISSUE THREAD

**Issue by sheetal071** [iomad/iomad#1785]
Invalid get_string() identifier: 'sectionidalreadyinuse' or component 'block_iomad_microlearning'. Perhaps you are missing $string['sectionidalreadyinuse'] = ''; in /path/to/iomad/blocks/iomad_microlearning/lang/en/block_iomad_microlearning.php?
line 356 of /lib/classes/string_manager_standard.php: call to debugging()
line 7422 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
line 117 of /blocks/iomad_microlearning/classes/forms/nugget_edit_form.php: call to get_string()
line 653 of /lib/formslib.php: call to block_iomad_microlearning\forms\nugget_edit_form->validation()
line 589 of /lib/formslib.php: call to moodleform->validate_defined_fields()
line 699 of /lib/formslib.php: call to moodleform->is_validated()
line 77 of /blocks/iomad_microlearning/nugget_edit.php: call to moodleform->get_data()

**Comment by turf212** [comment]
Fixed by pull request - thanks for supplying!
