### ISSUE TITLE
Attendance report by course: Headers of the report are in wrong format

### ISSUE THREAD

**Issue by sheetal071** [iomad/iomad#1787]
Iomad version: 4.1.2
PHP version: 7.4.33
Database: mysql (8.0.32)

Steps to regenerate the error:
1. Create the training event for the course
2. Book the users to the event
3. Go to the Iomad Dashboard > Reports > Attendance report by course
4. Then choose the course in which you have created the training event
5. Click on Download as CSV file

Now you may see Full name is correct but there is no Department header instead email header is there. 
![image](https://user-images.githubusercontent.com/108781673/227851781-6297dfb5-244f-4787-915e-beea679f5e6b.png)

**Comment by turf212** [comment]
Thanks for this. Fix pushed to 3.9, 4.0 and 4.1
