### ISSUE TITLE
Content Overflows from the container

### ISSUE THREAD

**Issue by sheetal071** [iomad/iomad#1789]
Iomad version: 4.1.2

If we set dark or cloured background then we can clearly see that content is overflowing. It can be fixed by setting the height from 100% to auto.
#region-main, #page-content, #region-main-box {
    height: auto;
}

Screenshot for the above error:

![image](https://user-images.githubusercontent.com/108781673/228161310-fe062f73-00d3-4f7b-bdd3-58e3e2fb6850.png)

We can see content overflows out of the container.

**Comment by turf212** [comment]
Which theme is this with?

**Comment by turf212** [comment]
Ignore me - boost theme.

**Comment by turf212** [comment]
fixed for 4.1 themes
