### ISSUE TITLE
Unable to see allocated courses within Course Allocations if license used up.

### ISSUE THREAD

**Issue by BananaRama203** [iomad/iomad#179]
If you have a learner with 2 courses allocated to them and you want to see what courses are allocated to that leaner via `edit users` - `edit course enrolments` but there is no active license for that company. Regardless if you are a system admin or company manager when you click on edit course enrolments 

you receive the message you have no licenses to allocate and nothing else.

This was a fix to a previous issue however it would be beneficial if this message shows in place of the license select dropdown box instead so you can still see the current allocations for that user or unallocate courses still without a active license/used up license

**Comment by turf212** [comment]
This is fixed in Iomad 3.0 version.
