### ISSUE TITLE
New Role created not viewing in iomad dashboard create user form

### ISSUE THREAD

**Issue by kirupalaksh** [iomad/iomad#1790]
Hi turf212,
I am facing the same issue, I have created a supervisor role and it is displayes in iomad-signup plugin role assignments.
But when i create a new user from iomad dashboard i cant able to get supervisor role. Please help me. Thanks in advance, Kirupa

**Comment by turf212** [comment]
The roles which are displayed to be assigned in the IOMAD dashboard are fixed to the IOMAD roles (company manager, department manager, company report only, educator) Other custom roles can on;y be assigned through the Moodle site admin pages.

**Comment by kirupalaksh** [comment]
Hi turf212,
Thanks for your response.
If we add a course educator role from child company , can this user enrolled as a Teacher role and manger reports / grades of a particular course.
Thanks, Kirupa

**Comment by kirupalaksh** [comment]
My requirement completed and new role created
