### ISSUE TITLE
Syntax error in LTI grade submission

### ISSUE THREAD

**Issue by kk122345** [iomad/iomad#1792]
https://github.com/iomad/iomad/blob/d20bf2107865526bd19a6670a2619e1ab137977c/enrol/lti/classes/local/ltiadvantage/task/sync_grades.php#L234

Found a syntax error in sync_grades.php.

**Comment by turf212** [comment]
This is a Moodle bug - The only course activities/resources which are part of IOMAD are the Training events and IOMAD certificate.
