### ISSUE TITLE
IOMAD 4.1 Error During Installation

### ISSUE THREAD

**Issue by DakshKK** [iomad/iomad#1793]
Was trying to install IOMAD 4.1 (branch - IOMAD_401_STABLE).

The installation fails after installing required modules, by saying that there was an error whilst communicating with the server. There are no other reports, or issues provided, and nothing seems to work.

Is there any way to understand what's wrong so I can continue.

**Comment by turf212** [comment]
This sounds like a PHP timeout on he browser.  If you rerun the installation (refresh the browser page and or rerun the command line upgrade then it) it should pick up from where you left it.

If this is a fresh install - I've just pushed a fix for one of the tables to do with the shop (#1779) so you would be best to pull that code before you try again.

**Comment by DakshKK** [comment]
Got it working. Did exactly as you suggested and worked better for me.
