### ISSUE TITLE
Error after approving data request after user deletion.

### ISSUE THREAD

**Issue by dallenk** [iomad/iomad#1794]
I believe this was corrected once, but seem to be back.
repeat of https://github.com/iomad/iomad/issues/1760

Exception occurred while calling local_iomad_track\privacy\provider::delete_data_for_user.
This means that plugin local_iomad_track did not complete the processing of data. The following exception information may be passed on to the plugin developer:
Error reading from database

#0 /var/www/vhosts/001-dev.domain.ca/iomad/lib/dml/moodle_read_slave_trait.php(293): moodle_database->query_end()
#1 /var/www/vhosts/001-dev.domain.ca/iomad/lib/dml/mysqli_native_moodle_database.php(1278): mysqli_native_moodle_database->query_end()
#2 /var/www/vhosts/001-dev.domain.ca/iomad/local/iomad_track/classes/privacy/provider.php(211): mysqli_native_moodle_database->get_records_sql()
#3 /var/www/vhosts/001-dev.domain.ca/iomad/lib/moodlelib.php(8152): local_iomad_track\privacy\provider::delete_data_for_user()
#4 /var/www/vhosts/001-dev.domain.ca/iomad/privacy/classes/manager.php(578): component_class_callback()
#5 /var/www/vhosts/001-dev.domain.ca/iomad/privacy/classes/manager.php(611): core_privacy\manager::component_class_callback()
#6 /var/www/vhosts/001-dev.domain.ca/iomad/privacy/classes/manager.php(415): core_privacy\manager->handled_component_class_callback()
#7 /var/www/vhosts/001-dev.domain.ca/iomad/admin/tool/dataprivacy/classes/task/process_data_request_task.php(138): core_privacy\manager->delete_data_for_user()
#8 /var/www/vhosts/001-dev.domain.ca/iomad/lib/cronlib.php(359): tool_dataprivacy\task\process_data_request_task->execute()
#9 /var/www/vhosts/001-dev.domain.ca/iomad/lib/cronlib.php(198): cron_run_inner_adhoc_task()
#10 /var/www/vhosts/001-dev.domain.ca/iomad/lib/cronlib.php(76): cron_run_adhoc_tasks()
#11 /var/www/vhosts/001-dev.domain.ca/iomad/admin/cli/cron.php(178): cron_run()
#12 {main}

**Comment by Fydon** [comment]
Getting the following with Iomad 4.3.3, which I received as an email.

```
Exception occurred while calling local_iomad_track\privacy\provider::delete_data_for_user.
This means that plugin local_iomad_track did not complete the processing of data. The following exception information may be passed on to the plugin developer:

Error reading from database (You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM mdl_local_iomad_track_certs
                                           JOIN' at line 1
SELECT litc* FROM mdl_local_iomad_track_certs
                                           JOIN mdl_local_iomad_track lit ON (litc.trackid = lit.id)
                                           WHERE lit.userid = ?
[array (
  0 => '5',
)])


#0 /bitnami/moodle/lib/dml/moodle_read_slave_trait.php(293): moodle_database->query_end()
#1 /bitnami/moodle/lib/dml/mysqli_native_moodle_database.php(1398): mysqli_native_moodle_database->query_end()
#2 /bitnami/moodle/local/iomad_track/classes/privacy/provider.php(211): mysqli_native_moodle_database->get_records_sql()
#3 /bitnami/moodle/lib/moodlelib.php(8339): local_iomad_track\privacy\provider::delete_data_for_user()
#4 /bitnami/moodle/privacy/classes/manager.php(578): component_class_callback()
#5 /bitnami/moodle/privacy/classes/manager.php(611): core_privacy\manager::component_class_callback()
#6 /bitnami/moodle/privacy/classes/manager.php(415): core_privacy\manager->handled_component_class_callback()
#7 /bitnami/moodle/admin/tool/dataprivacy/classes/task/process_data_request_task.php(151): core_privacy\manager->delete_data_for_user()
#8 /bitnami/moodle/lib/classes/cron.php(508): tool_dataprivacy\task\process_data_request_task->execute()
#9 /bitnami/moodle/lib/classes/cron.php(302): core\cron::run_inner_adhoc_task()
#10 /bitnami/moodle/lib/classes/cron.php(128): core\cron::run_adhoc_tasks()
#11 /bitnami/moodle/admin/cli/cron.php(186): core\cron::run_main_process()
#12 {main}
```

**Comment by Fydon** [comment]
This was [fixed recently](https://github.com/iomad/iomad/commit/c5e3460b72d5b0e6a17b8693e2f3854aa8f2b5b9#diff-cdfc9fa61db7003e6b72df318dcd44fc2d9528746a59ed39388cff15a4a32d17).
