### ISSUE TITLE
Duplicate Entry error when uploading users

### ISSUE THREAD

**Issue by mikeaveli007** [iomad/iomad#1795]
When uploading users to a company with a csv file, I am getting duplicate entry error.  When I check the users in the system only the first user in the list is added.  If I repeat the process the same thing happens where it will only add the first user and then give this error. 

Error writing to database

[More information about this error](https://docs.moodle.org/400/en/error/moodle/dmlwriteexception)
Debug info: Duplicate entry '4-383-11' for key 'mdl_compuser_comusedep_uix'
INSERT INTO mdl_company_users (userid,companyid,managertype,departmentid) VALUES(?,?,?,?)
[array (
0 => 383,
1 => 4,
2 => 0,
3 => '11',
)]
Error code: dmlwriteexception
Stack trace:

    line 489 of /lib/dml/moodle_database.php: dml_write_exception thrown
    line 291 of /lib/dml/moodle_read_slave_trait.php: call to moodle_database->query_end()
    line 1357 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->query_end()
    line 1403 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->insert_record_raw()
    line 178 of /local/iomad/lib/user.php: call to mysqli_native_moodle_database->insert_record()
    line 945 of /blocks/iomad_company_admin/uploaduser.php: call to company_user::create()

I am running v4.0.6

**Comment by turf212** [comment]
The upload is hitting the unique index for userid, companyid and department id which only allows a single entry for this. Do any of the users already exist on the system?

**Comment by mikeaveli007** [comment]
No, these are all new users.  Interestingly, it does create the user and assigns it to the company so it almost seems like it is trying to assign the newly created user to the company twice.  I can keep attempting to upload and create the users and it will add one at a time then error out.  

For the time being I added a Try/Catch block on line 175 in /local/iomad/lib/user.php where it is creating the user association and was able to upload my list and it created and assigned all the users to the company.

**Comment by turf212** [comment]
I think you are right.  If you have autoassignation then it may be explicitly called and then again on the user created event handler.

I've added some code to check if there is already a record and only if not add it.
