### ISSUE TITLE
Email templates missing (nothing to display) on fresh install of iomad 4.1

### ISSUE THREAD

**Issue by mikexis** [iomad/iomad#1798]
On fresh install of iomad 4.1.2, the email templates seems to be missing/not showing.   On the template_list.php page, it just says 'nothing to display'?

**Comment by turf212** [comment]
There is a scheduled task which should get set to run on cron after installation which populates the table for any company or when a company get's created. Is cron running on the site?

**Comment by xmontana** [comment]
I have the same problem, fresh install 4.1, the cron is running every minute. Could you tell me what the name of the task is so I can try to run it manually? Thanks in advance.

**Comment by mikexis** [comment]
Seemed to be an issue with a fresh install of 4.1.2,  when installed 4.0 and then immediately upgraded to 4.1.2 templates worked fine.

**Comment by turf212** [comment]
Issue is that we are expecting the tool custom lang table to be populated.  You can resolve this by going to site administration -> language -> language customisation and open the language for editing.  This then allows the company templates to appear.

The command to populate this was in the upgrade scripts but not installation.  Now there.

Thanks for reporting.

**Comment by slapnik** [comment]
> Issue is that we are expecting the tool custom lang table to be populated. You can resolve this by going to site administration -> language -> language customisation and open the language for editing. This then allows the company templates to appear.
> 
> The command to populate this was in the upgrade scripts but not installation. Now there.
> 
> Thanks for reporting.

I'm having the same issue on a fresh install of 4.3. No email templates. I've restricted the language options to en_us and es. Is there a specific lang I need to include to populate the default Email Templates? Do I need to trigger a system update for those to fill in?

**Comment by shadyshrif** [comment]
> Issue is that we are expecting the tool custom lang table to be populated. You can resolve this by going to site administration -> language -> language customisation and open the language for editing. This then allows the company templates to appear.
> 
> The command to populate this was in the upgrade scripts but not installation. Now there.
> 
> Thanks for reporting.

Thank you for the solution, this is an easy solution for IOMAD email templates page is empty and showing nothing to display.

I searched a lot and I think this solution needs to be documented somewhere
