### ISSUE TITLE
2 issues (1 Serious) Company Department Manager sets Activity Completion Restriction

### ISSUE THREAD

**Issue by dallenk** [iomad/iomad#1799]
When a Company Department Manager sets a restriction on activities, they can no longer access and edit the activity that has the restriction set - the site admin must change it

**1st issue:**
If a Company Department Manager with 'create course' permission allows self-enrollment on course creation, they cannot edit the activity settings once the restriction is saved

**2nd Issue - Serious**
Users can no longer access Dashboard or My Courses if the CDM sets "users are enrolled onto course by a Manager"
using SCORM activities as an example, "previous activity must be completed"

Once the restriction is saved, the following errors are shown
error 1: Course or activity not accessible. (click continue)
error 2: Invalid course module ID (click continue)
error 3: Invalid action parameter (click continue) - return to error 2 and loops

Now click - My Courses or Dashboard
 
Error
An internal error occurred in the completion system. (System administrators can enable debugging information to see more detail.)

Dashboard and My Courses are unavailable for the Company Department Manager.  Same error as above.

Site Administrator also cannot access the course to edit / remove the restriction - the course must be destroyed to restore the site.

(If you can't re-create this let me know and I'll open up the sandbox server for you to try)

**Comment by turf212** [comment]
Department mangers in all courses only get the client course access role (non-editing teacher) so they won't have the capability to  see hidden activities. That role would need to be updated to meet your requirements.
