### ISSUE TITLE
Blank page on 1st shibboleth login

### ISSUE THREAD

**Issue by matejzero** [iomad/iomad#180]
When user logs in for the 1st time via Shibboleth, it is redirected to a blank page right after authentication (when he enters username / password and clicks 'Login'). Firefox returns blank page (even if I view the source), but it looks like Chrome returns a page but it is not shown (also blank page). If I press F5 again, it is correctly redirected to moodle and user gets logged in.

![redirect](https://cloud.githubusercontent.com/assets/4689252/6392285/72715248-bdbf-11e4-957c-e1ba641766ae.png)

Matej

**Comment by turf212** [comment]
This sounds like it is related to the user not being allocated a company.  Can you please put your site into full debug mode and test again?  It should come back with a proper error message.

**Comment by matejzero** [comment]
I turned on debugging and got some, hopefully, useful informations:

Here is the error I get on 1st login:

```
(!) Fatal error: Call to undefined function expload() in /var/www/html/local/iomad_signup/lib.php on line 42
Call Stack
    Time    Memory  Function    Location
1   0.0000  249144  {main}( )   ../index.php:0
2   0.0145  3656416 authenticate_user_login( )  ../index.php:54
3   0.0184  3832240 create_user_record( )   ../moodlelib.php:4494
4   0.0622  4553344 core\event\base->trigger( ) ../moodlelib.php:4052
5   0.0649  4981704 events_trigger_legacy( )    ../base.php:726
6   0.0675  5004968 events_dispatch( )  ../eventslib.php:518
7   0.0676  5005688 call_user_func:{/var/www/html/lib/eventslib.php:299} ( )    ../eventslib.php:299
8   0.0676  5006096 local_iomad_signup_user_created( )  ../eventslib.php:299
```

It looks like a typo in lib.php, so I changed 'expload' to 'explode', which is probably what you meant, but now I get another error:

```
Comparisons of text column conditions are not allowed. Please use sql_compare_text() in your query.
More information about this error
Debug info: 
Error code: textconditionsnotallowed
Stack trace: 
line 597 of /lib/dml/moodle_database.php: dml_exception thrown
line 1426 of /lib/dml/moodle_database.php: call to moodle_database->where_clause()
line 43 of /local/iomad_signup/lib.php: call to moodle_database->get_record()
line ? of unknownfile: call to local_iomad_signup_user_created()
line 299 of /lib/eventslib.php: call to call_user_func()
line 518 of /lib/eventslib.php: call to events_dispatch()
line 726 of /lib/classes/event/base.php: call to events_trigger_legacy()
line 4052 of /lib/moodlelib.php: call to core\event\base->trigger()
line 4494 of /lib/moodlelib.php: call to create_user_record()
line 54 of /auth/shibboleth/index.php: call to authenticate_user_login()
```

There is also a link on the error page: https://docs.moodle.org/27/en/error/moodle/textconditionsnotallowed

Matej

**Comment by matejzero** [comment]
Since I turned on debug, I also see this error on every page:

```
Invalid get_string() identifier: 'authenticationtypes' or component 'local_iomad_signup'. Perhaps you are missing $string['authenticationtypes'] = ''; in /var/www/html/local/iomad_signup/lang/en/local_iomad_signup.php?

    line 293 of /lib/classes/string_manager_standard.php: call to debugging()
    line 6926 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
    line 39 of /local/iomad_signup/settings.php: call to get_string()
    line 67 of /lib/classes/plugininfo/local.php: call to include()
    line 492 of /admin/settings/plugins.php: call to core\plugininfo\local->load_settings()
    line 6649 of /lib/adminlib.php: call to require()
    line 6534 of /lib/adminlib.php: call to admin_get_root()
    line 23 of /admin/user.php: call to admin_externalpage_setup()
```

I'm not sure if this is a part of this problem or should I open another ticket?

Matej

**Comment by turf212** [comment]
That is a typo in the file.  I'll get that changed and uploaded. The 
get_string is the missing string values which I still need to add in..

On 27/02/15 13:54, Matej Zerovnik wrote:

> I turned on debugging and got some, hopefully, useful informations:
> 
> Here is the error I get:
> 
> |(!) Fatal error: Call to undefined function expload() in /var/www/html/local/iomad_signup/lib.php on line 42
> Call Stack
>      Time    Memory  Function    Location
> 1   0.0000  249144  {main}( )   ../index.php:0
> 2   0.0145  3656416 authenticate_user_login( )  ../index.php:54
> 3   0.0184  3832240 create_user_record( )   ../moodlelib.php:4494
> 4   0.0622  4553344 core\event\base->trigger( ) ../moodlelib.php:4052
> 5   0.0649  4981704 events_trigger_legacy( )    ../base.php:726
> 6   0.0675  5004968 events_dispatch( )  ../eventslib.php:518
> 7   0.0676  5005688 call_user_func:{/var/www/html/lib/eventslib.php:299} ( )    ../eventslib.php:299
> 8   0.0676  5006096 local_iomad_signup_user_created( )  ../eventslib.php:299
> |
> 
> I changed 'expload' to 'explode', which is probably what you meant, 
> but now I get another error:
> 
> |Comparisons of text column conditions are not allowed. Please use sql_compare_text() in your query.
> More information about this error
> Debug info:
> Error code: textconditionsnotallowed
> Stack trace:
> line 597 of /lib/dml/moodle_database.php: dml_exception thrown
> line 1426 of /lib/dml/moodle_database.php: call to moodle_database->where_clause()
> line 43 of /local/iomad_signup/lib.php: call to moodle_database->get_record()
> line ? of unknownfile: call to local_iomad_signup_user_created()
> line 299 of /lib/eventslib.php: call to call_user_func()
> line 518 of /lib/eventslib.php: call to events_dispatch()
> line 726 of /lib/classes/event/base.php: call to events_trigger_legacy()
> line 4052 of /lib/moodlelib.php: call to core\event\base->trigger()
> line 4494 of /lib/moodlelib.php: call to create_user_record()
> line 54 of /auth/shibboleth/index.php: call to authenticate_user_login()
> |
> 
> There is also a link to this page: 
> https://docs.moodle.org/27/en/error/moodle/textconditionsnotallowed
> 
> Matej
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/iomad/iomad/issues/180#issuecomment-76397347.

## 

E-Learn Design Ltd.
Scottish Moodle Partner
Official Mahara Partner
Website - http://www.e-learndesign.co.uk
Email - derick@e-learndesign.co.uk
Mobile - 07808068797

**Comment by bozicm** [comment]
Hello. Should this issue be considered resolved?

**Comment by BananaRama203** [comment]
I don't believe there has been a commit to action this yet. It appears there is a small logic fix and a missing Lang string to upload before this can be considered fixed

**Comment by turf212** [comment]
Hi Matej,  the fix was put onto your site a couple of weeks back.  (I'd emailed you outside of here)  If you are happy that is now all working (apart from the issue with the navigation block)  I'll push this now.

**Comment by matejzero** [comment]
As far as I tested, it looks like it's working...

Will do some more testing today and tomorrow.

**Comment by pexpert9** [comment]
How can i used shibboleth with moodle.
1. I need what are the primary tool or software required for shibboleth implementation 
2. what are the configuration (In context to local environment)
3. What is a role of shibboleth plugins like SP, IDP or DS.
4. How can i used shibboleth in our localhost.
5. Steps of Configuration of various files.

![shibboleth](https://user-images.githubusercontent.com/38654039/40547868-b1589750-6050-11e8-8d3e-396b9fa9ee60.png)
![1](https://user-images.githubusercontent.com/38654039/40547869-b15ebf86-6050-11e8-988c-cdcd017c99e5.png)
![2](https://user-images.githubusercontent.com/38654039/40547870-b1c30bd0-6050-11e8-8a4b-88ce65ef410e.png)
