### ISSUE TITLE
Database error dmlwriteexception in iomad

### ISSUE THREAD

**Issue by mariusz-mp** [iomad/iomad#1800]
Hello,
I installed IoMAD installations on the server with the following parameters:
Data base MariaDB 10.5.19
PHP 7.4.33
Website LiteSpeed
IoMAD 401

Moodle installed correctly, no errors were reported during the installation.
The database is in UTF8mb4_unicode_ci language encoding
Moodle is configured with translation into Polish.
I added the school correctly, it didn't return an error.
If it wants to add a new user, it returns me dmlwriteexception database error.
Similarly, when trying to correct the language string to Polish, it returns a database error.
When I set up a new course, it is assumed correctly.
When I play the course without users, the action is completed without error and the course is displayed correctly.
When I play copies of the course with users, the course is pinned to the selected school and correctly recreated.
Users are properly installed in the system, but they are not assigned to the declared school. Despite indicating it as the target.

Maybe you have any suggestions?
I considered the configuration of the database itself, it is rather not the source of the problem.

Regards
Mariusz Pulkowski

**Comment by turf212** [comment]
Can you please enable full developer debug (site administration - > development -> debugging and set tp full developer debug and show in the browser) and paste the error message you are getting?

**Comment by mariusz-mp** [comment]
Hello,
I did system updates, will test again and let you know if there are any surprises.

Is there a chance to import users to the selected company using a CSV file?
Regards
Mariusz Pulkowski

**Comment by mariusz-mp** [comment]
Hello,
getting language pack returns error:
Debug info: Incorrect string value: '\xF0\x9F\x91\x8B' for column `xxxxx_io41`.`mdl_tool_customlang`.`original` at row 1
INSERT INTO mdl_tool_customlang (lang,componentid,stringid,original,master,timemodified,outdated,local,timecustomized) VALUES(?,?,?,?,?,?,?,?,?)
[array (
0 => 'pl',
1 => '1',
2 => 'welcomeback',
3 => 'Welcome back, {$a->firstname}! 👋',
4 => 'Witaj ponownie, {$a->firstname}! 👋',
5 => 1685009597,
6 => 0,
7 => NULL,
8 => NULL,
)]
Error code: dmlwriteexception×Odrzuć te powiadomienie
Stack trace:
line 497 of /lib/dml/moodle_database.php: dml_write_exception thrown
line 293 of /lib/dml/moodle_read_slave_trait.php: call to moodle_database->query_end()
line 1362 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->query_end()
line 1408 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->insert_record_raw()
line 208 of /admin/tool/customlang/locallib.php: call to mysqli_native_moodle_database->insert_record()
line 63 of /admin/tool/customlang/index.php: call to tool_customlang_utils::checkout()

I have other test installations and this one works fine.
Do you have any suggestions?

Regards
Mariusz Pulkowski

**Comment by turf212** [comment]
The welcome back string is a core Moodle one.  The value for this is special characters - '\xF0\x9F\x91\x8B when it should be a string.  Likely local to your site.
