### ISSUE TITLE
Empty report charts - /local/report_license_usage

### ISSUE THREAD

**Issue by CesparRes** [iomad/iomad#1801]
When attempting to view license allocation graphs the chart is only rendering the axes.

![image](https://user-images.githubusercontent.com/113600501/230360012-767669fa-32d9-4353-bc3b-8be5cfaebb5b.png)

Upon inspecting the code:
![image](https://user-images.githubusercontent.com/113600501/230359331-912413fb-95ba-4c6d-88ff-b41c35bbdf8f.png)

Everything appears to be correct, however the issue is that there is no x-axis label.

Simply adding the set_labels() assignment for the chart applies the axis label and then displays the chart correctly:
`$chart->set_labels(['License Allocations']); // Charts *need* this code as we're only providing a single data point as index for labels`

![image](https://user-images.githubusercontent.com/113600501/230360059-45ebe0e0-0e73-4146-bafc-13e55e79fdab.png)

**Comment by turf212** [comment]
Thanks for this. Fix has been pushed.
