### ISSUE TITLE
divide by zero/infinity display on local/report_completion charts (Percentage of Course)

### ISSUE THREAD

**Issue by CesparRes** [iomad/iomad#1802]
When viewing course completion by percentage of course the charts are displayed incorrectly:
![image](https://user-images.githubusercontent.com/113600501/230406440-c6570eb7-7df2-4d44-9193-61e606e9ea91.png)

Checking the code we find not just a typo at line 1372 ("coursid") but it seems the wrong value assigned too:
`'courseid' => $row->coursid]);`

Correcting the code to:
`'courseid' => $row->id]);`
Appears to correct the display of the 2nd chart with the correct percentages:
![image](https://user-images.githubusercontent.com/113600501/230407525-ec6fe455-6775-49d3-aa56-80f651e719d3.png)

The same error can also be found at line 1208 too.

**Comment by turf212** [comment]
Thanks for this.  Fixed under #1820
