### ISSUE TITLE
IOMAD_400_STABLE-I cannot select an organization in the dashboard pull-down.

### ISSUE THREAD

**Issue by resonantstyle** [iomad/iomad#1804]
IOMAD_310_STABLE (Moodle release 3.10.11) was upgraded to IOMAD_400_STABLE (Moodle release 4.0.7).

Organization administrators in the middle hierarchy of parent and child organizations cannot select an organization in the dashboard pull-down.
IOMAD_310's iomad was able to select it.
Line 256 of the following file seems to be the cause.
local/iomad/lib/company.php

**Comment by turf212** [comment]
We are explicitly looking for top level companies (parentid = 0) so when a user is in the middle they are not being found.  I've updated the code to get the highest level company the user is in rather than explicitly looking for a top level company

**Comment by turf212** [comment]
I've pushed a fix for this to the 4.0/1 branches.
