### ISSUE TITLE
Hide empty sub categories?

### ISSUE THREAD

**Issue by mikeaveli007** [iomad/iomad#1806]
On our instance, we have all courses assigned to the main company and then into subcategories in the company category.  We assign out courses to other companies via "closed shared". When navigating to "/course/" as a user of another company to see the list of courses, I can see all the top level subcategories.  This includes categories with courses that are not assigned to this company and shows "0 Courses" and if you click on that category you will get an "unknown category" error.  Is it possible to hide those on this page?  The drop down selector on the page that allows you to change the category actually has the empty ones filtered out, but for some reason on the page itself it doesn't.

**Comment by turf212** [comment]
Categories are only shown to users if:

1 - The category or parent is tied to their company
2 - The category does not belong to any company

Additionally - if a user is enrolled in a course then they can see the category that course is in (but all of the courses should get removed by a filter).

Which version do you have installed?
