### ISSUE TITLE
"File: Open in Popup"  redirects to the log in page of the root url

### ISSUE THREAD

**Issue by dallenk** [iomad/iomad#1808]
When adding a file into a course and choosing:
![image](https://user-images.githubusercontent.com/2725066/231635001-0a2f942c-9110-4744-bc30-e7a8e88a123c.png)

the user is redirected to a login prompt on the root URL

**Comment by turf212** [comment]
Check the file URL which is being saved.  It will be a mismatch between the tenant hostname and the site hostname and the file will be using the site hostname.  If so then I need to check the code there as it's not setting the wwwroot correctly.
