### ISSUE TITLE
IOMAD 4.1. Important performance impact of is_company_user() calls

### ISSUE THREAD

**Issue by joseomedes** [iomad/iomad#1809]
We recently upgraded or installation to IOMAD 4.1.2 (2022112802.00). There were no issues during the upgrade and all the test after the upgrade were successful.

Once real traffic came into the LMS, we experience a huge increase in the number of requests coming into the database. The database got overloaded and we had to deploy one additional read replica to cope with the huge amount of queries coming in.

After our investigation, we discovered, that the queries had the following signature:

"SELECT `id` , `companyid` FROM `mdl_company_users` WHERE `userid` = ? ORDER BY `id` LIMIT ?, ..."

This query is part the is_company_user() function at local/iomad/lib/iomad.php.

This function gets called many times during the user navigation in IOMAD. Our performance probes, found out that in majority of the cases, 50% of the time required for loading a page is due to is_company_user() calls. For example, when loading /course/view.php this function can be called up to 51 times (50% of the page load).

In the case of teacher enrolled in several courses the performance impact was higher. 

![IOMAD_003](https://user-images.githubusercontent.com/98596064/231687391-0ffd9f02-380e-45a5-8efd-9fbb839e1d00.png)

The impact of all this calls was huge as it can be seen on the following graph (this graph shows just one of our read replicas). In total, we had more than 100 req/sec of this type.

![IOMAD_001](https://user-images.githubusercontent.com/98596064/231684337-b943cacd-4c1b-44a0-8021-d4bc9dad1560.png)

We believed this information should be cached and the number of queries to the database reduced. We suggest applying the following patch:

103,104d102
<         } else if (!empty($SESSION->usercompanyid)) {
<             return $SESSION->usercompanyid;
107d104
<             $SESSION->usercompanyid = $usercompany->companyid;
1838c1835
< }
---
> }

After we applied it to our system, the queries to the database lowered down to the same level as before the upgrade. See the graph below:

![IOMAD_002](https://user-images.githubusercontent.com/98596064/231686330-ae6a4da9-5ed3-4966-93f7-80862c69a180.png)

**Comment by turf212** [comment]
Thanks for this.  Only thing is that the function could be running the check against a different user and not necessarily the user who's SESSION value you are adding to.  If we add a check that the user in question is the same as $USER then we can stash it in $SESSION->currenteditingcompany and only check when it's not the current user.

**Comment by turf212** [comment]
I've pushed a fix for this to the 4.0/1 branches where if the user being passed is the USER variable and $SESSION->currenteditingcompany is not set - it sets it.  There is a check for this being set before the database call so it will have the same improvement on performance while still allowing for other users to be checked.
