### ISSUE TITLE
Shibboleth users don't get assigned to company

### ISSUE THREAD

**Issue by matejzero** [iomad/iomad#181]
When I login with a new user, it doesn't get assigned to a company/school. I can see the user under Administration->Users->Accounts->Browse all users, but I can't see it in any company under Administration->Iomad->Edit users. The user can also see all the courses and apply/enroll to it. It doesn't matter to which company a certain course belongs to.

**Comment by turf212** [comment]
Let me look at your test site.  That looks like a configuration issue as a user who doesn't belong to a company should not see any company courses at all (unless they are marked as open shared and then anyone can see them).

**Comment by matejzero** [comment]
I just checked the settings and courses are not set as open shared.

![courses1](https://cloud.githubusercontent.com/assets/4689252/6413629/ce4b5884-be91-11e4-879f-092729d7dc41.png)

**Comment by turf212** [comment]
This was an issue with the user not getting through the authentication properly.  Closed as part of #180

**Comment by bozicm** [comment]
The issue doesn't seem to be resolved yet - example(s):
- Case 1 (ps01.si):
  - I reinstalled the latest 2.7 branch and set up Shibboleth auth and companies with their respective domains
  - login as student ana@ps01.si
  - the user don't show up at https://ucilnice-dev.arnes.si/blocks/iomad_company_admin/editusers.php .
  - I have to manually assign her from https://ucilnice-dev.arnes.si/blocks/iomad_company_admin/company_users_form.php
- Case 2 (ps02.si):
  - manually assigning Peter as company admin
  - login as ana@ps02.si - can't see any company related information
  - Peter can't see any new users or any other user managing form (_There are no users. Create one now_) - he can't see/assign/enrol Ana.

There are no courses created yet in company categories. After I manually assigned ana@ps02.si, she could see the company category _Primary School 02_ in her [_Courses_ page](https://ucilnice-dev.arnes.si/course/index.php).
