### ISSUE TITLE
Can not open quiz or review attempt

### ISSUE THREAD

**Issue by DakshKK** [iomad/iomad#1811]
If the quiz is set with a close time and/or date, my users are unable to review attempts, or see scores. Neither does the page load completely. It loads part of the page, the rest is left with skeleton blocks.

Though moment I disable closing date and/or time, the page will load and attempts are available for review.

IOMAD Version: 4.1
IOMAD Branch: IOMAD_401_STABLE
PHP Version: 8.1.17
APACHE Version: 2.4.56

**Comment by turf212** [comment]
At this level the site is exactly the same as a Moodle site.  Documentation is here - https://docs.moodle.org/en/Quiz_activity

If you turn debug on it may tell you what is failing (if anything) (Site administration -> Development -> Debugging and switch to full developer and chose the show in browser option.
