### ISSUE TITLE
4.1 Company manager - editusers.php - red error when switch editing on

### ISSUE THREAD

**Issue by jlb224** [iomad/iomad#1812]
Hello, the following red error appears when company manager visits editusers.php and switches editing on. 
![image](https://user-images.githubusercontent.com/26649166/233964502-d2c6972e-0380-4a17-b754-29b5dc13f5d0.png)

**Comment by jlb224** [comment]
It is failing here 
public function set_type_select($options) {
        if (!array_key_exists($this->value, $options)) {
            throw new \coding_exception('Options for select element must contain an option for the specified value');
        }
$options just contains 0:"User" 
value = 1. 
But I am unsure what it should be, or why it is incorrect.

**Comment by jlb224** [comment]
The fix for this seems to be here: 
in /blocks/iomad_company_admin/classes/tables/editusers_table.php
line 138
changing
     $currentvalue = $row->managertype + 10 * $row->educator;
to 
     $currentvalue = ($row->managertype + 10) * $row->educator;
but I am unsure if this is correct? Seems to get rid of the red error though.

**Comment by turf212** [comment]
Thanks for this. Fix has been pushed.
