### ISSUE TITLE
Error in template_edit_form.php

### ISSUE THREAD

**Issue by CesparRes** [iomad/iomad#1813]
After noticing that email templates seem to have incorrect body text, we spotted that there was an error in the edit form php at line 90:

![image](https://user-images.githubusercontent.com/113600501/234024638-f3f7f6c2-bae6-4864-b05c-1d9dfcae4807.png)

The edit form is populating the template body data with the template subject.

Changing the line to:
`if (empty($templaterecord->body)) {
    $templaterecord->body = get_string($templatename . '_body', 'local_email', $lang);`
Fixes the issue and the template body text can correctly be viewed

**Comment by turf212** [comment]
Thanks for this.  Fix has been pushed.
