### ISSUE TITLE
after latest upgrade:  Capability "local/report_completion_overview:view" was not found!

### ISSUE THREAD

**Issue by dallenk** [iomad/iomad#1814]
Capability "local/report_completion_overview:view" was not found! This has to be fixed in code.
line 453 of /lib/accesslib.php: call to debugging()
line 1337 of /lib/adminlib.php: call to has_capability()
line 4606 of /lib/navigationlib.php: call to admin_externalpage->check_access()
line 4639 of /lib/navigationlib.php: call to settings_navigation->load_administration_settings()
line 4639 of /lib/navigationlib.php: call to settings_navigation->load_administration_settings()
line 4589 of /lib/navigationlib.php: call to settings_navigation->load_administration_settings()
line 4444 of /lib/navigationlib.php: call to settings_navigation->load_administration_settings()
line 833 of /lib/pagelib.php: call to settings_navigation->initialise()
line 962 of /lib/pagelib.php: call to moodle_page->magic_get_settingsnav()
line 8758 of /lib/adminlib.php: call to moodle_page->__get()
line 934 of /admin/index.php: call to admin_externalpage_setup()

**Comment by dallenk** [comment]
update:  manually removing, then adding ./local/report_completion_overview give an error on the installation and database upgrade:

Intersting part, user 59 is me, course ID 32 is an old course that was deleted, might have been licensed at one point, but isn't available anymore.

```
Upgrading to new version
local_report_completion_overview
Error writing to database

Debug info: Column 'licenseid' cannot be null
INSERT INTO mdl_local_report_user_lic_allocs (userid,licenseid,courseid,action,issuedate,modifiedtime) VALUES(?,?,?,?,?,?)
[array (
0 => '59',
1 => NULL,
2 => '32',
3 => 1,
4 => '1636001030',
5 => 1682396993,
)]
Error code: dmlwriteexception×Dismiss this notification
Stack trace:
line 489 of /lib/dml/moodle_database.php: dml_write_exception thrown
line 291 of /lib/dml/moodle_read_slave_trait.php: call to moodle_database->query_end()
line 1357 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->query_end()
line 1403 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->insert_record_raw()
line 114 of /local/report_completion_overview/db/install.php: call to mysqli_native_moodle_database->insert_record()
line 682 of /lib/upgradelib.php: call to xmldb_local_report_completion_overview_install()
line 1935 of /lib/upgradelib.php: call to upgrade_plugins()
line 719 of /admin/index.php: call to upgrade_noncore()

```

**Comment by turf212** [comment]
Capability is definitely there.  The install was a hangover from the report it was cloned from (and I've removed it in ca0abd7d23b206d8f4ea91dbf957289f2eabed3f

**Comment by dallenk** [comment]
perhaps something left over in my sandbox installation?  (clone of the production).  Pulled the commit and the error remains on:
Dashboard
My courses
Site administration
Department Dashboard (Iomad Dashboard)

**Comment by dallenk** [comment]
I just cloned the production to the sandbox and it seems to be working correctly now and upgraded from 400 to 401 branch.

closing.
