### ISSUE TITLE
"Show expired licenses" button does not correctly hide/show expired licenses

### ISSUE THREAD

**Issue by CesparRes** [iomad/iomad#1815]
Checking the code in: company_license_list.php

We can see on line 193:
![image](https://user-images.githubusercontent.com/113600501/234284495-71e451d1-3465-47c9-85d8-da3689888cdb.png)

This potentially is mysql/php version related, but on our platform certainly clicking the button does not actually change any of the displayed licenses.

However, after modifying the query on the above line to include brackets around the WHERE cl.companyid = :companyid $childsql clause we were able to fix things so the button is now functional.
![image](https://user-images.githubusercontent.com/113600501/234284973-ee15c516-14be-47ec-90a5-737a13eff667.png)

**Comment by turf212** [comment]
Thanks for this.  Fix has been pushed.
