### ISSUE TITLE
4.1 'are you sure you want to leave' when changing dropdown

### ISSUE THREAD

**Issue by jlb224** [iomad/iomad#1816]
Hello
On blocks/iomad_company_admin/company_license_users_form.php there is a 'Are you sure you want to leave' browser alert whenever the available courses dropdown is changed. 
Please can you add $mform->disable_form_change_checker(); to line 144 definition_after_data() on /blocks/iomad_company_admin/classes/forms/company_license_users_form.php to stop this?

**Comment by turf212** [comment]
Added as requested to 4.0 and 4.1 branches.
