### ISSUE TITLE
How to link Github Repo to a new installation

### ISSUE THREAD

**Issue by ludz007** [iomad/iomad#1818]
Hi There,

I had an old installation on www.oldinstallation.com, now i copied my whole installation to www.newinstallation.com, but i am struggling to link that installation to this iomad project in order to do a git pull. 
And when i do an update from remote on Git Version Control, it states that the repository is up to date, when in fact, it is not.

How do i link them via terminal?

Regards

**Comment by dallenk** [comment]
I've copied installs to new domains often and don't have a problem doing a git pull.
what is git log showing as your last commit?   `git log --oneline`   did you create a new branch and your site is working off an older one??

**Comment by turf212** [comment]
when you copy make sure you also copy the .git directory in the webserver root.
