### ISSUE TITLE
invoiceitem table does not get updated with license_validlength/shelflife for license block purchases

### ISSUE THREAD

**Issue by CesparRes** [iomad/iomad#1819]
The invoiceitem table pulls this data from the course_shopblockprice table. However, when creating a shop product, if you create a product that sells a block of licenses, the validlength and shelflife fields are not written to the course_shopblockprice table.

This can be fixed by adding the following lines of code in /blocks/iomad_commerce/edit_course_shopsettings_form.php:
`			$priceblock->validlength = $data->single_purchase_validlength;`
`			$priceblock->shelflife = $data->single_purchase_shelflife;`

![image](https://user-images.githubusercontent.com/113600501/234853693-d73f2836-5c84-4768-bb95-129d3677707c.png)

After this the course_shopblockprice and invoiceitem tables will be correctly populated with these 2 fields

**Comment by turf212** [comment]
Thanks for this.  fix has been pushed.
