### ISSUE TITLE
Companyid is not being assigned in the invoice table

### ISSUE THREAD

**Issue by CesparRes** [iomad/iomad#1822]
When viewing invoice table all invoices show that the companyid for the purchasing company is 0.

This can be resolved in several ways, but I went with simply updating the /blocks/iomad_commerce/checkout.php file.
![image](https://user-images.githubusercontent.com/113600501/235097907-268a9b04-8cf6-40de-b973-2e3d2d588b54.png)

Adding at Line 77:
`$data->companyid = $companyid`
![image](https://user-images.githubusercontent.com/113600501/235098181-0f17eef3-5848-46a1-8750-6e6f19a3accf.png)

Ensures that the companyid is correctly inserted to the invoice table when making a license purchase

**Comment by turf212** [comment]
Thanks for this.  Fix has been pushed.
