### ISSUE TITLE
local/iomad/lib/company.php has an incorrect variable causing cron to fail

### ISSUE THREAD

**Issue by CesparRes** [iomad/iomad#1823]
After receiving the following cron error mail:
![image](https://user-images.githubusercontent.com/113600501/235186535-0815082d-dd41-41c0-bb0c-76122e2c5720.png)

We checked into the code at line 3997:
![image](https://user-images.githubusercontent.com/113600501/235186812-c12a234d-6f46-4344-b885-a669ad677360.png)

It appears that there is a typo/misnaming of the variable $track as this is not referenced anywhere else in the code.
Changing this to $trackinfo seems to have resolved this.
`$licenses = $DB->get_records('companylicense_users', array('licenseid' => $trackinfo->licenseid));`

**Comment by turf212** [comment]
Thanks for this.  Fix is pushed
