### ISSUE TITLE
Stuck in the profilepage

### ISSUE THREAD

**Issue by janvanl** [iomad/iomad#1824]
Hi,

I installed the latest iomad on a server for testing-purposes. Made a few organisations.
All went well.

I then changed the userprofile and left the browser.

After i logged in new i get the userprofilepage and i cannot find a way to get out of that, i am stuck in the profilepage.
I looked in the database - did not find anything that could explain it.
I started install.php but again landed in the profile-page.

Any Idea how to cancel this page and get beck to the startpage?

To continu testing i installed a new instance but i would like to solve this issue.

Regards,
Jan

**Comment by turf212** [comment]
This was something the user did.  Not sure what but they installed a new version and couldn't repeat it.  Going to close the issue.
