### ISSUE TITLE
Completion Overview Report does not correctly populate course details for courses that have validlength of 0

### ISSUE THREAD

**Issue by CesparRes** [iomad/iomad#1826]
Looking at /blocks/iomad_company_admin/iomad_courses_form.php we see that the validlength field is intended to be used to represent whether a course needs to be retaken and if so, when it expires:
![image](https://user-images.githubusercontent.com/113600501/235719217-09d938a4-3aa1-4e84-8ca9-aa919bf1b808.png)

When set to 0, this simply means the course does not need to be retaken.
However, when viewing the completion overview report, the $rowclass and colouring that is added is based off validlength being >0. This means for courses that do not have to be retaken, the $rowclass is always ignored and no colouring added to the final report grid:

![image](https://user-images.githubusercontent.com/113600501/235720650-b19191c8-a140-4924-8b55-b67d13820fce.png)

Hovering over cells that appear "empty" still shows there is data in there though:
![image](https://user-images.githubusercontent.com/113600501/235720934-f1f24425-e759-4ae3-aad6-762b5a3b40ba.png)

This may be intended, but it seems like it would be better to always provide colouring regardless of whether a course needs to be retaken or not.

For our own "fix" I simply changed the initial SQL query on Line 192:
`$expirecourses = $DB->get_records_sql("SELECT courseid FROM {iomad_courses} WHERE validlength IS NOT NULL");`

Which produces a more visually pleasing grid (ignoring some formatting due to long course names!):
![image](https://user-images.githubusercontent.com/113600501/235721398-ef671096-2d42-49c7-b714-49efb4041d6c.png)

**Comment by turf212** [comment]
The spec for the report was that courses which didn't need to be retaken would simply show up as white. I'll add a setting for the report (there is already one there for the length of time for the course to be in a warning state) so that it switches between these two settings as, I agree, it works this way too for most people.

**Comment by turf212** [comment]
I've added a default setting and a button on the top right so you can switch between modes.
