### ISSUE TITLE
/blocks/iomad_commerce/orderslist is throwing errors when trying to filter by name

### ISSUE THREAD

**Issue by CesparRes** [iomad/iomad#1827]
With the recent fixes to include companyid in invoice table we are now able to view a list of recent orders, however, if we are to try and filter by the firstname/lastname we receive an error:

![image](https://user-images.githubusercontent.com/113600501/235893520-830bc8aa-b25b-4477-878a-642717bd1ba6.png)

I have tried to locate where the ambiguity for firstname or lastname arises but I have a suspicion the extra part of the query:
`(AND firstname LIKE ? ESCAPE '\\')`
is coming from a helper.php file somewhere? I've not been able to locate the code to update yet.

**Comment by turf212** [comment]
The default tablelib class doesn't allow for any prepending on the get_sql_where class.  Added a version of that function to the report tablesql class.
