### ISSUE TITLE
Company reports are showing values that are rather large/strange

### ISSUE THREAD

**Issue by CesparRes** [iomad/iomad#1828]
I've checked the math of how these are calculated, and the math checks out, but the logic of what they're showing is clearly not quite right.

![image](https://user-images.githubusercontent.com/113600501/235921033-7b6e0622-0b0b-40b5-8f16-5247249895b8.png)

I forget the exact figures on this, but essentially it was 405 courses, on 11 user company. 
I believe the math was:
`total courses (405) * 100 / total company users (11)`

This of course returns 3681%

However this doesnt really feel right for a company report haha - we will be providing license bundles of programs of courses so each user potentially will have up to 34 courses in one license bundle. Spread this over the company and it's easy to hit the 405 total courses. Seeing a report saying the 3681% of the company has started/completed courses is confusing :D

This is not the only report showing strange values:
![image](https://user-images.githubusercontent.com/113600501/235922209-3b58647e-87d1-4863-8808-a636a06d9981.png)
Again this is "% of company" and seems to suggest that more than 100% total of the company has completed or is in progress on individual courses.

For "% of course":
![image](https://user-images.githubusercontent.com/113600501/235922491-fb398265-90ad-41cf-a183-f19bd62c8ab6.png)

I'm unsure how many of these charts could be showing funky values due to licenses being unallocated and reallocated, but there clearly is some weird numbers flying around here!

**Comment by turf212** [comment]
If there are historic completions (e.g. I enrol on a course, complete it and then re-enrol on the course) then there could be multiple entries for every user.  If you click on "Remove expired course results" does the maths add up then?

**Comment by CesparRes** [comment]
I'm pretty sure it didn't change anything but will check once back to work.

**Comment by dallenk** [comment]
I also see odd results for Percentage of Company 

![image](https://user-images.githubusercontent.com/2725066/236661901-508b31e1-54b7-49b9-ba3b-5f7e53f9ed20.png)

**Comment by CesparRes** [comment]
Removing expired courses does change a little bit of the results, but still shows strange values:
![image](https://user-images.githubusercontent.com/113600501/237051507-f18dbfd2-8d4c-41fc-8834-677774e67407.png)
