### ISSUE TITLE
License related email templates do not appear to have tasks to send the email

### ISSUE THREAD

**Issue by CesparRes** [iomad/iomad#1829]
I've not checked all of these, but certainly the 'licensepoolexpiring' and 'license_reminder' email templates exist, but do not appear in a task that actually sends them.

We can see that 'expiry_warn_user' exists as a template, and is handled by /email_reports/classes/task/course_expiry_warn_task. But our test company manager accounts are not receiving any emails regarding license blocks expiring/unused etc..

**Comment by turf212** [comment]
This was added in commit 573a76cffaa5624159071e0d93bcd568ee4145ca - you were right it wasn't being handled anywhere
