### ISSUE TITLE
Deleted shibboleth users can't login again

### ISSUE THREAD

**Issue by matejzero** [iomad/iomad#183]
I'm not sure of the state of deleting users right now, but the last time we spoke, there was a bug, when a shibboleth user was deleted, it wasn't able to login back again. Error was:
"You seem to be Shibboleth authenticated but Moodle has no valid account for your username. Your account may not exist or it may have been suspended."

**Comment by turf212** [comment]
This appears to be a bug with the deleting of users within Iomad leaving the email address/username intact when it should be changing them.  Not Shibboleth related.

**Comment by turf212** [comment]
Fixed in 2.7 and 2.8

**Comment by matejzero** [comment]
Great!

It looks like deleting users under Administration->Users->Accounts is working.
I will test deleting from Iomad dashboard when issue #181 is fixed and users will get assigned to companies.

**Comment by pexpert9** [comment]
I have facing problem with Moodle shibboleth configurations
![shibboleth](https://user-images.githubusercontent.com/38654039/40547973-ffc8dc9c-6050-11e8-9a9f-2deee668fa0b.png)


now i want to know how can i configure the shibboleth configuration in a moodle
.
![1](https://user-images.githubusercontent.com/38654039/40548000-1459e3c2-6051-11e8-8ab0-464bfc8f8456.png)
![2](https://user-images.githubusercontent.com/38654039/40548004-1751d2a6-6051-11e8-88db-9d6f7d16095c.png)
