### ISSUE TITLE
local/email_reports/classes/task/manager_digest_task has an undefined variable

### ISSUE THREAD

**Issue by CesparRes** [iomad/iomad#1830]
Today we received the cron error:
![image](https://user-images.githubusercontent.com/113600501/236408884-6e03a2fc-ed46-4fa1-a214-5daa6802cc7c.png)

Checking line 155:
`array('weekago' => $timenow - (60 * 60 * 24 * 7)))) {`

This should be $runtime:
`array('weekago' => $runtime - (60 * 60 * 24 * 7)))) {`

It should be noted there is also an undefined departmentname in the cron email (referring to line 162), nor does the task appear to successfully send emails, returning warnings about duplicate values:
![image](https://user-images.githubusercontent.com/113600501/236427217-aa40c157-0aa9-4a62-8e48-d9aec312438f.png)
(these warnings are likely not a huge issue though)

**Comment by turf212** [comment]
thanks - updated the code.
