### ISSUE TITLE
various tasks are using incorrect date() formatting in mtrace

### ISSUE THREAD

**Issue by CesparRes** [iomad/iomad#1831]
example /local_email_reports/task/course_expiry_warning
`mtrace("Running email report course expiry warning task at ".date('D M Y h:m:s', $runtime));`
Which returns:
`Running email report course expiry warning task at Fri May 2023 11:05:53`

In php D is the day name (IE FRI) and m is month number (5 for may)

Changing the code to:
`mtrace("Running email report course expiry warning task at ".date('d M Y h:i:s', $runtime));`
Will correctly output:
`Running email report course expiry warning task at 05 May 2023 11:52:23`

Unsure how many tasks this formatting is used, but certainly in the /local_email_reports/task/manager_digest_task, /local_email_reports/task/course_not_started_task, /local_email_reports/task/course_not_completed_task and /local_email_reports/task/trainingevent_not_selected_task

I'm crossing my fingers this is an issue only in mtrace for tasks and not anywhere else where date() could be used :D

**Comment by turf212** [comment]
It's only the mtraces.  Every other date being displayed runs from the configured date format in settings.

**Comment by CesparRes** [comment]
Haha yeah I did a quick check on all files because it made me nervous 😅

All good :D

It needs to be `h:i:s` too though for the minutes

**Comment by turf212** [comment]
That will teach me for copy/pasting them all.... *facepalm"  Also updated.

**Comment by CesparRes** [comment]
Haha honestly I'm a python coder so to me h: m :s seemed right - easy thing to miss if you're switching between languages I guess.
