### ISSUE TITLE
Ecommerce Solution

### ISSUE THREAD

**Issue by ludz007** [iomad/iomad#1832]
Hi There,

I would like t know if someone can assist...

I have 2 x queries...

1st query

I want to give the option for all my companies to be able to sell their own courses ... at their chosen price etc. but then, if they sell we get a set amount of percentage? Is this possible with iomad?

2nd query

i would like to know if someone can assist me, is there an ability to enroll learners in a specific course, using a "custom" signup link that is sent to them via email? or lets say, someone purchases a course from my eCommerce store, there must be a unique link sent to that person to be able to enrol in that specific course? is this possible?

3rd query 

signup - How does the signup to a specific company work? I cannot get the iomad signup form to work...

Thanks in advance

**Comment by turf212** [comment]
1 - There isn't a way for you to get a cut of the money automatically.  You can use the reports to see the number of license allocations for that company and then you can recharge but nothing in-built.

2 - What's the use case for this?  When a user is allocated a license (either by a manager/admin or when they purchase a license) then they are granted access to the course (and an emails sent out to them if you haven't disabled it which has the link to the course). If the license isn't of the immediate type (where they are granted enrolment at time of allocation) then clicking on the course and then choosing to enrol activates the license. If it is an immediate type then clicking on the course takes them straight to the content as they are already enrolled.  There isn't any further "key" required for enrolment.  It's already there in potential from the license.

3 - See here for documentation for this - https://www.iomad.org/documentation/documentation/administration/how-to-automatically-assign-self-serve-users-to-companies/  There is also a link to how to set different URLs for tenants - which helps with automatic company assignation.

**Comment by ludz007** [comment]
Thanks Turf,

1 - So, there is a way for my clients to sell their own courses and the money will be redirected to them upon sale? Is this the ecommerce block?

2 - I understand, thank you, the use is, that i would like to sell access to my course on a third part y website that i have created... So the learner must browse through my shop, select a course, and purchase a course, after purchase create their account on my LMS, then have automated access?

3 - Thank you!

**Comment by groiso** [comment]
Hi, ludz007

I intend to use Wordpress eCommerce, I think it's easier to sell and distribute commissions, etc.
