### ISSUE TITLE
Shared course

### ISSUE THREAD

**Issue by levi19982** [iomad/iomad#1833]
I created a course for Company 1, and I want that this course to be visible to Company 2 as well. I logged in as administrator, chose Company 1 in IOMAD Dashboard, went to Courses and Manage IOMAD course settings where there is a list of the courses. I see that there is a column named "is shared" where it displays that this course is not shared but I cannot choose to be shared, I am unable to click on this text.

**Comment by dallenk** [comment]
Turn the edit option on
