### ISSUE TITLE
local_iomad - error during new installation on Krystal Web Server

### ISSUE THREAD

**Issue by logic-sense** [iomad/iomad#1837]
Not sure if it's because of my web server, can someone guide me?  
![Screenshot 2023-05-10 at 5 05 23 PM](https://github.com/iomad/iomad/assets/123898078/6f528c19-869d-4252-b3b2-03e9350f0152)

local_iomad
Exception - Attempt to assign property "roleid" on null

[More information about this error](https://docs.moodle.org/401/en/error/moodle/generalexceptionmessage)

Debug info: 
Error code: generalexceptionmessage × Dismiss this notification
Stack trace:
line 58 of /local/iomad/db/install.php: Error thrown
line 767 of /lib/upgradelib.php: call to xmldb_local_iomad_install()
line 1953 of /lib/upgradelib.php: call to upgrade_plugins()
line 721 of /admin/index.php: call to upgrade_noncore()

**Comment by turf212** [comment]
Which version of IOMAD is this and did you download the complete IOMAD code (which includes the Moodle code) or did you just bring over the plugins separately?

**Comment by logic-sense** [comment]
I downloaded iomad-IOMAD_401_STABLE.zip (entire code) on 8th May 2023. I think I found what the problem was, I had Moodle installed in a separate directory and this new one of IOMAD was running on the same database. So now I reinstalled and connected it to a separate database. This seems to have solved now.
