### ISSUE TITLE
Unable to create child departments

### ISSUE THREAD

**Issue by hippyhalfwit** [iomad/iomad#1846]
Have tried adding child departments to other departments it just keeps putting them in as departments under the company.

For example I am trying to create Company A>>Dept B>>sub dept C

but despite selecting Dept B as the parent department it sets up as 

Company A>>Dept B
                  >> Dept C

And then unable to delete Dept B or C

Whats really annoying is it worked on a demo I did and then hasnt worked since

**Comment by hippyhalfwit** [comment]
Also worth noting that selecting departments is really iffy, Have to click infront of the company/department name for the drop downs to remain open

**Comment by turf212** [comment]
this got refactored in 80f674a9d51d38e1a797034e1a447136657fee39
