### ISSUE TITLE
Unable to use AMOS to translate iomad modules once they are not at plugin database

### ISSUE THREAD

**Issue by andreyamin** [iomad/iomad#185]
I noticed that the iomad modules are not available for translating using AMOS translation tool, which makes the translation work much harder.
As far as I know, this is because the iomad modules are not in Moodle plugin database. I am not sure that make the iomad modules available at moodle plugin database is a good choice too. 
Anyway, this is an issue for those who would like to translate to iomad.

**Comment by turf212** [comment]
Unfortunately Iomad is more than just a collection of plugins as there are some core code changes in there to make it work.  Not many, admittedly, but enough that downloading and installing the plugins from the Moodle plugins directory wouldn't work.  Having never worked on the Moodle translation project, as there any other suggestions you may have to help with this?  What happens with the OU set of plugins, for example?

**Comment by andreyamin** [comment]
Hi Derick,
The best solution would be to make the iomad work without having to modify the core by incorporating the necessary patches into Moodle, as was done with Elis. I know this is not simple or fast, but is the best IMHO.
As a temporary workaround we could fork Iomad, add the other lang files into the plugin folder and make pull requests.
The OU modules are all available on Moodle plugin database so they are also available into AMOS translation tool. These modules are quite popular in Brazil (where I live) and almos all have Brazilian Portuguese translations.

**Comment by turf212** [comment]
Lang packs are being worked on - will be able to upload them via the import string from file option which is now available in Moodle.
