### ISSUE TITLE
License expiry date warning email template appears to be unused, or the warnings are not being sent out for expiry

### ISSUE THREAD

**Issue by CesparRes** [iomad/iomad#1851]
I thought I'd reported this before but I guess I forgot to.

It looks like there is no handling in place for licenses expiring, or indeed % usage:

**License expiry date warning**
Hi {User_FirstName} {User_LastName}

This message is to notify your company account {Company_Name} that that your program license {License_Name}, {License_ID} is expiring on {License_Expirydate}. You will not be able to allocate further licenses to users once you reach expiration date. Please contact your Program Manager if you have further questions

**License useage warning**
Hi {User_FirstName} {User_LastName}

This message is to notify your company account {Company_Name} has used 90% of the license pool {License_Name}, {License_ID} . You will not be able to allocate further licenses once you reach 100% usage.

Please contact your Program Manager for details

I *think* it was just these two that didnt even appear to have a task that checks and sends the mails for these events - however for sure in my email logs for IOMAD there have never been any templates sent out for these despite license bundles expiring and all licenses in a bundle being assigned to users

**Comment by turf212** [comment]
added in be62f3d76c316e9098d687b5011436551579a2b1
