### ISSUE TITLE
can not delete company 

### ISSUE THREAD

**Issue by egyptrise52** [iomad/iomad#1856]
Hello  
I try to  delete added company but I cannot find the delete button 
![Untitled](https://github.com/iomad/iomad/assets/137727931/caf5e3e6-cc15-43f9-b37f-cc6b5487db76)

**Comment by dallenk** [comment]
There is no delete option.. ( i wish there was )  you can only suspend the company which hides it from the list.

**Comment by malekdev97** [comment]
@egyptrise52 You can navigate to this URL, but make sure to login as administrator before you navigate: 
https://[Your_Domain_Name]/block/iomad_company_admin/company_list.php
