### ISSUE TITLE
Optimization for fixtracklicensetask 

### ISSUE THREAD

**Issue by rmeske** [iomad/iomad#1857]
I am in the process of updating an old IOMAD 3.4 site.  The latest version update I am working on is IOMAD 3.9.  With the update complete, there is an Adhoc task, fixtracklicensetask, currently running and based on what I can see  watching the MySQL connections this will take about 40 hours to complete.  It is currently 22 hours into it.  A few of the other Adhoc tasks 1-3 hours to complete.

For this particular task, the companylicense table has about 22,000 records.  In looking at the code it is performing several individual field updates for each licensed.  It seems like this could be optimized to do more of a batch of updates.  

Current  first part of the execute function:
`$found = false;

        // Fix any educator license allocations so that nag emails don't happen.
        if ($licenses =  $DB->get_records('companylicense')) {
            $found = true;
            foreach ($licenses as $license) {
                $DB->set_field('local_iomad_track', 'licensename', $license->name, array('licenseid' => $license->id));
                // Is this an educator license?
                if ($license->type == 2 || $license->type ==3) {
                    $DB->set_field('local_iomad_track', 'expirysent', time(), array('licenseid' => $license->id));
                    $DB->set_field('local_iomad_track', 'notstartedstop', 1, array('licenseid' => $license->id));
                    $DB->set_field('local_iomad_track', 'completedstop', 1, array('licenseid' => $license->id));
                    $DB->set_field('local_iomad_track', 'expiredstop', 1, array('licenseid' => $license->id));
                }
            }
        }`

Would combing the 4 set_field into one update_record, improve the performance enough to justify the change?  Perhaps use an if to create an object that included the license name as well so there is only 1 write to the database for each license instead of up to 5. 

Something like:
`//Change to write once per loop

  foreach ($licenses as $license) {  
    $updaterec = new \stdClass();
    if ($license->type == 2 || $license->type ==3) {
      $updaterec = new \stdClass();
                    $updaterec->id = $license->id;
                    $updaterec->licensename = $license->name;
                    $updaterec->expirysent = time();
                    $updaterec->notstartedstop = 1;
                    $updaterec->completedstop = 1;
                    $updaterec->expiredstop = 1;
                }else {
                    $updaterec->id = $license->id;
                    $updaterec->licensename = $license->name;
                }
                $DB->update_record('local_iomad_track', $updaterec);
            }`

The second part of the current execute function also loops through every license but the select does limit the number of records, so any optimization may not be a significant improvement.

PS: The second code block would not format properly for some reason.

**Comment by rmeske** [comment]
The log information from this task:
Time: 2 days, 4 hours

Execute adhoc task: local_iomad_track\task\fixtracklicensetask
... started 18:32:31. Current memory use 46MB.
... used 21625 dbqueries
... used 189216.52184606 seconds
Adhoc task complete: local_iomad_track\task\fixtracklicensetask

This is just a test of the update prior to the actual update.  I was able to disable other scheduled tasks until this one completed and there was no load from users.  I am concerned that when I do the actual update to the production system, this will likely run in the background for many more days impacting performance for possibly a week, so I am very interested in optimizing this task to run much faster.

I did create a SQL statement to do the update with one statement.  Testing on a copy of the database it took about 4 minutes.  The only downside is that it is most likely only compatible with MySQL server.  I would appreciate any input on the following.

```
UPDATE local_iomad_track lit
                  JOIN companylicense cl ON lit.licenseid = cl.id
                  SET lit.licensename = cl.name,
                      lit.expirysent = CASE WHEN cl.type = 2 OR cl.type = 3 THEN UNIX_TIMESTAMP() ELSE lit.expirysent END,
                      lit.notstartedstop = CASE WHEN cl.type = 2 OR cl.type = 3 THEN 1 ELSE lit.notstartedstop END,
                      lit.completedstop = CASE WHEN cl.type = 2 OR cl.type = 3 THEN 1 ELSE lit.completedstop END,
                      lit.expiredstop = CASE WHEN cl.type = 2 OR cl.type = 3 THEN 1 ELSE lit.expiredstop END
                      WHERE lit.id > 0
```

**Comment by turf212** [comment]
Your SQL seems sound.  If you prevent the task from firing in the upgrade.php file and then run that all should be good.  As you say, may only work with MySQL.
