### ISSUE TITLE
4.x uservisible check prevents regeneration of certificates from unenrolled courses

### ISSUE THREAD

**Issue by jlb224** [iomad/iomad#1861]
Hello, 

We have recently upgraded from 3.8 to 4.1 and the addition of the user->visible check for regeneration of certificates is preventing us from regenerating certs from unenrolled courses (required in the case of a name change, or just sometimes because client requests it).

Is there a way around this?

**Comment by turf212** [comment]
there were to commits around this to fix it 

ba81513d1be0bf551e36f7314a4af47c2392a2ff and f488af9df8bd4f79b55709575d25e713561bf1bd
