### ISSUE TITLE
Error: Download available H5P content types from h5p.org

### ISSUE THREAD

**Issue by DakshKK** [iomad/iomad#1869]
I switched on Debugging, and tried running H5P task to download available content types.

I get the following errors, and am unable to use H5P. Is there a way to fix this?

![image](https://github.com/iomad/iomad/assets/54723155/ddeaad55-d5c1-45c5-95a3-f2e9831a1175)

**Comment by turf212** [comment]
This will be a Moodle issue.  We do not make any changes to the Moodle H5P functions (or many other course functions)
