### ISSUE TITLE
Creating a course includes many users outside the department

### ISSUE THREAD

**Issue by craighamer** [iomad/iomad#187]
When I create a course that is part of a department, many users are enrolled and set up as managers and the like that are not managers in that department.  Growdly.com is our site.  I recently created a new course.  I haven't only enrolled 1 users manually, but when I got into the course and view the users, then I see many that perhaps are set up as a high level users, Client Course Access & Company Department Manager.  I spoke with one of the support people and he recommended I start this issue.  Thank you.

**Comment by turf212** [comment]
The code is not checking that the course is for a particular department and is blanket assigning everyone.

**Comment by craighamer** [comment]
Okay, so do I just wait or do you need more information from me.

Craig Hamer
M4Europe.com
Tartu, Estonia

**Comment by turf212** [comment]
closed.  This is not an issue.  The users being added are purposefully being added by the system as they are managers and get enrolled onto the course in either a non editing or editing role.
