### ISSUE TITLE
Autoenrol in company course(s) not working - 4.14

### ISSUE THREAD

**Issue by tbeachy** [iomad/iomad#1872]
I see that autoenrol has moved from Advanced Company Settings to the Iomad Course Settings page, which makes sense.  However, the autoenrol functionality doesn't seem to be working unless there's something wrong with my setup.
I am testing in a child company of the main parent company in a 4.14 installation.

- the child company uses a sub-domain for company assignment on signup
- the autoenrol courses are correctly assigned to the child company
- courses are non-licensed and using self-enrol (is that a problem?)
- users are being auto-assigned to the child company on signup correctly, but are not being enrolled in the autoenrol courses

Thanks for any help!

**Comment by turf212** [comment]
Within the child company - are the courses also set to auto enrol?  This is a per company setting so sounds like you are missing that step.
