### ISSUE TITLE
Incorrect category on course listing page

### ISSUE THREAD

**Issue by harshil8595** [iomad/iomad#1875]
I found issue in sql query in [iomad_filter_categories](https://github.com/iomad/iomad/blob/d0b7d2a35b0f58e591b50aebf45a105f89ba970a/local/iomad/lib/iomad.php#L447) function.
Query matches course categories that not belongs to company.

**Comment by harshil8595** [comment]
Hi @turf212

I've created pull request to fix issue #1876.

Please review.

**Comment by turf212** [comment]
Thank you for this.  I've added in a commit for it.

**Comment by harshil8595** [comment]
Hi @turf212

I have committed changes to fix this issue, then made a pull request is this the wrong way to contribute?

**Comment by turf212** [comment]
Not really - we don't add pull requests as they may/may not use the standard commit messages we use (IOMAD: <commit message>) and then become very easy to miss in the list of commits when trying to add stuff back into our main development branch.  So I typically review the change and then just add it.

**Comment by harshil8595** [comment]
Hi @turf212 

Thanks for having your time on this.

In the future, if i want to be an author of a commit, I need to commit standardized message starting with `IOMAD:` prefix right?
