### ISSUE TITLE
Issues uploading bulk users from CSV into multiple companies

### ISSUE THREAD

**Issue by Ahoja** [iomad/iomad#1877]
• Uploaded CSV user list in Iomad Dashboard fails with this DEBUG message:
` -- 'PHP message: Default exception handler: Error reading temporary file Debug: \nError code: cannotreadtmpfile\n* line 3665 of /lib/deprecatedlib.php: moodle_exception thrown\n* line 179 of /blocks/iomad_company_admin/uploaduser.php: call to print_error()\n', referer: https://servername/lms/blocks/iomad_company_admin/uploaduser.php
`
* Upload of users in MOODLE system admin screen works and users are correctly setup. Error only happens from IOMAD dashboard/users/upload users

**Comment by tbeachy** [comment]
I've seen some random errors like this is in my 4.14 installation as well, but I am not having this specific problem.  I have been using the Iomad upload users via csv extensively over the past few days and it's been working fine.  Are you trying to upload into multiple companies via the same upload file?  I've been just creating separate uploads per company.  Also are you sure that your .csv is UTF-8?  I've had issues in the past with Excel .csv files, so that may be something to check out too.
Good luck.

**Comment by Ahoja** [comment]
Thanks for the note. 
* Yes, UTF-8.
* Same CSV upload file works as planned from the main Site Admin/Users upload in Moodle.
* Attached is what debug gives back.
![iomaduploaddebug](https://github.com/iomad/iomad/assets/8656605/28a6a309-e532-44e9-bd9b-b72dcfde411f)
* It could be a repository issues or permissions item on our side -- as the Company/site upload user is different than the main Moodle admin.

**Comment by tbeachy** [comment]
What does the block/iomad_company_admin:user_upload permission say for the
user you're uploading with?

**Comment by Ahoja** [comment]
Interestingly a mix of permissions in the directory. This shows root:root. It's odd, as we run recursive chmod 755/644 on all files and directories in the folders. Note the mix in the attached png.
![permissions](https://github.com/iomad/iomad/assets/8656605/72206d98-4d2a-4e3a-8d85-25f522e93021)

**Comment by tbeachy** [comment]
That is odd...mine all show owner as root.
I am not a Linux permission expert, but I was actually referring to the
Moodle permissions in Site Administration > Users > (Permissions) Define
Roles.  Compare the *block/iomad_company_admin:user_upload* permission for
the two different user roles that you referred to earlier.  See if the
company-specific user doesn't have the permission set.

**Comment by Ahoja** [comment]
Thank you for your thoughtful help. The Client Administrator/Company Manager/Company Department Manager roles all show "Allow" in the Upload Users section. It is the Company Manager Role doing the upload. So next we will test resetting the Linux permissions in both directions (www-data:www-data and root:root) and report back.

**Comment by turf212** [comment]
The upload CSV is notoriously picky in Moodle.  Typically the issue is due to the file having incorrect column headers (should all be lower case) or having spaces in the text.  Check it in textpad/notepad and see if there is anything obvious.

**Comment by ericfalcon** [comment]
Hello.
For my csv files, I noticed that I needed at least the following fields:
id, username, firstname, lastname, email, institution (company name), department (company or department name).
