### ISSUE TITLE
Unassigning a user from one dept and assigning to another assigns to the old department

### ISSUE THREAD

**Issue by BananaRama203** [iomad/iomad#188]
Exactly what the title says...Unassigning a user from one dept and assigning to another assigns to the old department.

I.e. Assign a company manager to global dpt, unassign company manager from the global dpt, assign as company manager to a sub dpt...the company manager is assigned to the global dpt again.

**Comment by turf212** [comment]
Did you click on the "choose department" button again when you changed the department dropdown?   This is a horrible menu item and we are well aware that it has a lot of limitations/needs to be addressed.

**Comment by AC-Education** [comment]
Yeah definitely clicked on change department. Just verified and seems to be a bug

**Comment by turf212** [comment]
I've just tested this on a copy of your site.

NFA F company
selected department unknown from the drop down and clicked on choose department
Selected the only user in that and clicked on the remove arrow.
selected another department and clicked on choose department
in the right had search typed in that users name
selected the user and clicked the left hand assign arrow
went back to the original department and clicked on choose department
no one in it.

The list of potential users which is displayed when in a department is the list of all users who do not have the selected role in that department.  So you can simply select the department from the drop down and click on choose department, search for the user you want and click on the left hand assign arrow and they will be removed from whichever department they are in and added to the current one.

**Comment by RyanHamlin1234** [comment]
Confirm bug within Vanilla 2.8.

If you allocate a managertype or department to a user. Exit window, go back into edit department, un-assign a department then reallocate department/managertype it will put them back in to the old department which you unallocated them from instead of the new department.

**Comment by turf212** [comment]
Addressed in another bug for 3.0
