### ISSUE TITLE
Exception - Attempt to assign property "id" on null

### ISSUE THREAD

**Issue by navneetbhe** [iomad/iomad#1881]
Debug info:
Error code: generalexceptionmessage
Stack trace:
line 459 of /lib/accesslib.php: Error thrown
line 1737 of /local/iomad/lib/iomad.php: call to has_capability()
line 644 of /user/profile/lib.php: call to iomad::has_capability()
line 865 of /user/profile/lib.php: call to profile_get_user_fields_with_data()
line 613 of /lib/authlib.php: call to profile_get_custom_fields()
line 66 of /auth/oauth2/classes/auth.php: call to auth_plugin_base->get_custom_user_profile_fields()
line 3811 of /lib/moodlelib.php: call to auth_oauth2\auth->__construct()
line 456 of /lib/classes/session/manager.php: call to get_auth_plugin()
line 165 of /lib/classes/session/manager.php: call to core\session\manager::initialise_user_session()
line 139 of /lib/classes/session/manager.php: call to core\session\manager::start_session()
line 842 of /lib/setup.php: call to core\session\manager::start()
line 34 of /config.php: call to require_once()
line 30 of /index.php: call to require_once()

When, I opened the file

IOMAD_401_STABLE/lib/accesslib.php and on line number 459
if (!isset($USER->id)) {
        // should never happen
        $USER->id = 0;
        debugging('Capability check being performed on a user with no ID.', DEBUG_DEVELOPER);
    }
    
    Assigning $USER->id = 0; // while $USER object does not exist.

**Comment by turf212** [comment]
This was fixed in 12e20aa53377 - needed to make sure the company table was set up before we did anything further
