### ISSUE TITLE
"SCORM - LMSCommit failed" error on SCORM completion - IOMAD_401_STABLE

### ISSUE THREAD

**Issue by ni-ght** [iomad/iomad#1882]
Hello,

A "SCORM - LMSCommit failed" error is displayed with some SCORM engines on a SCORM’s completion.

This seems to be caused by the "iomad_track" course_completed event observer echoing a debug message. File “./local/iomad_track/classes/observer.php”, “public static function course_completed($event)”:
```
// Debug
if (!PHPUNIT_TEST) {
    mtrace('Iomad completion recorded for userid ' . $userid . ' in courseid ' . $courseid);
}
```

When "LMSCommit" function in "./mod/scorm/datamodels/scorm_12.js" is called by a SCORM engine, it calls "mod/scorm/datamodel.php". The script in this page has a well-defined output:
```
if ($result) {
    echo "true\n0";
} else {
    echo "false\n101";
}
…
```

Some SCORM engines rely on this output to determine a successful data commit.

The debug message echoed by the "iomad_track" course_completed event observer gets inserted into the output stream, just before the "true\n0" output string of "datamodel.php", which causes some SCORM engines to determine a false commit failure.

The solution might be to not issue an "mtrace" call in an event observer - it may end up wrecking the output of some web service.

Many thanks.

**Comment by turf212** [comment]
Thank you for this - I've commented that line out which should resolve the issue.
