### ISSUE TITLE
migratetemplates task issue in IOMAD_401_STABLE

### ISSUE THREAD

**Issue by anto-progetica** [iomad/iomad#1885]
Hi,
After upgrading to iomad at branch IOMAD_401_STABLE. the local_email\task\migratetemplates->execute() task raises an error:

```
Adhoc task failed: local_email\task\migratetemplates,Error writing to database
Debug info:
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE NOT EXISTS (
                                        SELECT * FROM mdl_...' at line 3
INSERT INTO mdl_email_template (companyid,name,lang)
                                      SELECT ?, ?, ?
                                      WHERE NOT EXISTS (
                                        SELECT * FROM mdl_email_template
                                        WHERE companyid = ?
                                        AND name = ?
                                        AND lang = ?)
-- line 110 of /local/email/classes/task/migratetemplates.php: call to mysqli_native_moodle_database->execute()
-- line 367 of /lib/cronlib.php: call to local_email\task\migratetemplates->execute()
-- line 198 of /lib/cronlib.php: call to cron_run_inner_adhoc_task()
-- line 76 of /lib/cronlib.php: call to cron_run_adhoc_tasks()
-- line 178 of /admin/cli/cron.php: call to cron_run()
[array (
  0 => '1',
  1 => 'admin_deleted',
  2 => 'en',
  3 => '1',
  4 => 'admin_deleted',
  5 => 'en',
)]
Backtrace:
* line 293 of /lib/dml/moodle_read_slave_trait.php: call to moodle_database->query_end()
* line 1176 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->query_end()
* line 110 of /local/email/classes/task/migratetemplates.php: call to mysqli_native_moodle_database->execute()
* line 367 of /lib/cronlib.php: call to local_email\task\migratetemplates->execute()
* line 198 of /lib/cronlib.php: call to cron_run_inner_adhoc_task()
* line 76 of /lib/cronlib.php: call to cron_run_adhoc_tasks()
* line 178 of /admin/cli/cron.php: call to cron_run()
```

From iomad on the email template page I then get the following error when I access it: "The email templates are not currently accessible
This is due to an adhoc migration task which is being run against them. Emails will still be sent out from the system as normal and access to the templates will return once the task has completed.".

It would appear that the FROM is missing from the query you are running.

**Comment by turf212** [comment]
The where not exists shouldn't need a FROM part of the statement.  What this bit of SQL is doing is trying to efficiently insert data in the email_template table if it doesn't already exist for that company/language/string.

I've tested this with an upgrade from 3.9 to 4.1 on MariaDB 10.11.5-MariaDB-1:10.11.5+maria~ubu2204 without any issues. It's also worked on MySQL 8.0.34-0ubuntu0.22.04.1 (which is my dev rig and why I also checked on MariaDB as MySQL can be too forgiving sometimes)

What happens in the DB when you run the following directly?

`INSERT INTO mdl_email_template (companyid,name,lang)
                                      SELECT 1, 'admin_deleted', 'en'
                                      WHERE NOT EXISTS (
                                        SELECT * FROM mdl_email_template
                                        WHERE companyid = 1
                                        AND name = 'admin_deleted'
                                        AND lang = 'en)`

**Comment by anto-progetica** [comment]
By entering this query the dbms returns the following error:
```
INSERT INTO mdl_email_template (companyid,name,lang) SELECT 1, 'admin_deleted', 'en' WHERE NOT EXISTS ( SELECT * FROM mdl_email_template WHERE companyid = 1 AND name = 'admin_deleted' AND lang = 'en');
/* Error SQL (1064): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE NOT EXISTS ( SELECT * FROM mdl_email_template WHERE companyid = 1 AND n...' at line 1 */
```
Keep in mind that we are using an instance of Mariadb managed as a service by
Microsoft Azure. Could it be a mariadb version issue?

I just checked in the control panel that the version in use is 10.3.

**Comment by turf212** [comment]
I've just tried - and got the same error.  Also MariaDB 10.3.  FYI that version isn't supported any more and the current supported versions of MariaDB are 10.6 and 10.11.  (10.10 is supported for the rest of the month but no point in upgrading to that for 3 weeks worth of support).

It may be worth upgrading your DB version?

What the script is doing is adding in a copy of each of the template names into mdl_email_template for each of the languages you have installed and for each of the companies on the site making sure not to duplicate any.  That way it keeps any of the customisations you may already have made/saved.  Once completed it unsets a config value ($CFG->local_email_templates_migrating) which unlocks the page.

**Comment by anto-progetica** [comment]
We will evaluate the database upgrade. OK for now we have solved the issue by implementing the queries manually. 
Thank you.
