### ISSUE TITLE
issue when I list the company users with edit option active. In IOMAD_402_STABLE

### ISSUE THREAD

**Issue by anto-progetica** [iomad/iomad#1886]
Hi,
An exception is generated when the users in the company are listed and the edit option is active.

Url: /blocks/iomad_company_admin/editusers.php

The user in the list is a company manager. (If the user in the list has a normal User role the bug does not occur.)

"Options for select element must contain an option for the specified value"
```
Stack trace: 
line 183 of /lib/classes/output/inplace_editable.php: coding_exception thrown
line 91 of /blocks/iomad_company_admin/classes/output/user_roles_editable.php: call to core\output\inplace_editable->set_type_select()
line 156 of /blocks/iomad_company_admin/classes/tables/editusers_table.php: call to block_iomad_company_admin\output\user_roles_editable->__construct()
line 842 of /lib/tablelib.php: call to block_iomad_company_admin\tables\editusers_table->col_managertype()
line 2068 of /lib/tablelib.php: call to flexible_table->format_row()
line 2192 of /lib/tablelib.php: call to table_sql->build_table()
line 664 of /blocks/iomad_company_admin/editusers.php: call to table_sql->out()
```

I got around the issue by editing: /blocks/iomad_company_admin/classes/tables/editusers_table.php at line 148
```
            // Set up the current value for the inplace form and display it.
            if (empty($CFG->iomad_autoenrol_managers)) {
                $currentvalue = ($row->managertype * 10) + $row->educator;
            } else {
                $currentvalue = $row->managertype * 10;
            }
```

changed to: 

```
            // Set up the current value for the inplace form and display it.
            $currentvalue = ($row->managertype * 10) + $row->educator;
```

It's not a complete fix. Just a starting point

**Comment by turf212** [comment]
There was an actual fix pushed for this the other week under commit 573845bd93084e19fac3a9c2c6fe97534e15bd4e (9th of September).  It was pushed to 4.1 and 4.2 branches,

**Comment by turf212** [comment]
Edit - sorry - should have checked if you had pulled that one in :)

**Comment by anto-progetica** [comment]
OK, thanks. For me this issue can also be closed.
