### ISSUE TITLE
Custom error pages

### ISSUE THREAD

**Issue by Ahoja** [iomad/iomad#1887]
**Not really an issue / more a "how to customise" request**

### Goal
**Is there any "easy way" to customise error pages in the Iomadboost theme?** For example, we want to redirect to a standard 404.php page.

The goal is to redirect to custom 401,403,404,500,503 error pages that would match our site CSS, then redirect the user back to the previous page.

We have the pages in a directory: /error*/custom/*404.php
Just need to connect them/add them into the theme. 

### Solutions that didn't work
Modifying our virtualhost conf files or hardcoding a redirect in .htaccess does not seem to work as planned.

### Comment
Just to add in here - Iomad is really great. Thanks for making it available for us to use.

**Comment by turf212** [comment]
Custom error pages should be set up within the webserver config - It's not something that you can set in Moodle either and I can't see any plugins which provide that.
