### ISSUE TITLE
Different pages use different 'last access' dates

### ISSUE THREAD

**Issue by jlb224** [iomad/iomad#1888]
Hello

We are getting reports from users confused about the 'last access' dates that appear across various pages. Looking at the various pages associated with this:
/local/report_users/index.php and /local/report_users/userdisplay.php use lastlogin
/blocks/iomad_company_admin/editusers.php uses currentlogin
userprofile uses lastaccess

Is it possible to standardise the iomad pages so that they use the same date?

**Comment by turf212** [comment]
Lastaccess was a late addition to the user table and should be the same as currentlogin.  I'll get these updated to use the new standard.
