### ISSUE TITLE
exception error after checkout to 402_STABLE

### ISSUE THREAD

**Issue by dallenk** [iomad/iomad#1889]
sudo -u www-data git checkout -b IOMAD_402_STABLE origin/IOMAD_402_STABLE
Updating files: 100% (9338/9338), done.
Branch 'IOMAD_402_STABLE' set up to track remote branch 'IOMAD_402_STABLE' from 'origin'.
Switched to a new branch 'IOMAD_402_STABLE'
domain@sandbox:/var/www/vhosts/sandbox.domain.ca/iomad$ sudo -u www-data git pull
Already up to date.
domain@sandbox:/var/www/vhosts/sandbox.domain.ca/iomad$ sudo -u www-data php ./admin/cli/upgrade.php
++ Invalid cache store in config. Not an available plugin. ++
* line 189 of /cache/classes/config.php: call to debugging()
* line 400 of /cache/disabledlib.php: call to cache_config->load()
* line 457 of /cache/classes/factory.php: call to cache_factory_disabled->create_config_instance()
* line 265 of /cache/disabledlib.php: call to cache_factory->create_definition()
* line 322 of /cache/disabledlib.php: call to cache_factory_disabled->create_definition()
* line 200 of /cache/classes/loaders.php: call to cache_factory_disabled->create_cache_from_definition()
* line 1551 of /lib/moodlelib.php: call to cache::make()
* line 773 of /lib/setuplib.php: call to get_config()
* line 695 of /lib/setup.php: call to initialise_cfg()
* line 30 of /config.php: call to require_once()
* line 41 of /admin/cli/upgrade.php: call to require()
++ A cache mode mapping exists for a mode or store that does not exist. ++
* line 268 of /cache/classes/config.php: call to debugging()
* line 400 of /cache/disabledlib.php: call to cache_config->load()
* line 457 of /cache/classes/factory.php: call to cache_factory_disabled->create_config_instance()
* line 265 of /cache/disabledlib.php: call to cache_factory->create_definition()
* line 322 of /cache/disabledlib.php: call to cache_factory_disabled->create_definition()
* line 200 of /cache/classes/loaders.php: call to cache_factory_disabled->create_cache_from_definition()
* line 1551 of /lib/moodlelib.php: call to cache::make()
* line 773 of /lib/setuplib.php: call to get_config()
* line 695 of /lib/setup.php: call to initialise_cfg()
* line 30 of /config.php: call to require_once()
* line 41 of /admin/cli/upgrade.php: call to require()
Default exception handler: Exception - syntax error, unexpected '|', expecting variable (T_VARIABLE) Debug:
Error code: generalexceptionmessage
* line 3899 of /lib/adminlib.php: ParseError thrown

!!! Exception - syntax error, unexpected '|', expecting variable (T_VARIABLE) !!!
!!
Error code: generalexceptionmessage !!
!! Stack trace: * line 3899 of /lib/adminlib.php: ParseError thrown
!!

**Comment by dallenk** [comment]
protected ?int $maxduration = null;

appears to fix the issue.. not sure if it's correct or not.

**Comment by turf212** [comment]
What version of PHP are you using?  Minimum version for Moodle 4.2 is now PHP 8.0.

**Comment by dallenk** [comment]
Hi, I installed php 8.0 once it prompted at the db update page.  Once viewing the site admin page is when I saw the error

**Comment by turf212** [comment]
Check what other optional plugins you have installed (in case one of them hasn't been updated to work with PHP 8.0) The error message for this tends to be exactly what you are seeing.

**Comment by dallenk** [comment]
I don't have any plugins showing any PHP errors.  The only plugin warning I see has been there for a long time.
![image](https://github.com/iomad/iomad/assets/2725066/dbaf5e2d-36af-4389-8981-a17bd921c114)

Should I see a warning in the plugins list for a compatibility issue?

**Comment by turf212** [comment]
OK Weird.  Which line/file did you make the code change??

**Comment by dallenk** [comment]
It was line 3899 on /lib/adminlib.php

**Comment by encodecreate** [comment]
I'm getting this same error, too. But unfortunately, @sgvfr 's fix isn't helping for me.

**Comment by turf212** [comment]
I suspect this is now fixed.  One thing which can cause this on the Webserver and not command line is if you haven't restarted your webserver or haven't switched it over to use the new PHP version. In any case that error is definitely a PHP version issue.
