### ISSUE TITLE
4.14 - IOMAD Edit Users (any company)  "Error reading from database"

### ISSUE THREAD

**Issue by tbeachy** [iomad/iomad#1890]
Here is full debugging:

Invalid get_string() identifier: 'organization' or component 'moodle'. Perhaps you are missing $string['organization'] = ''; in lang/en/moodle.php?
line 356 of /lib/classes/string_manager_standard.php: call to debugging()
line 7427 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
line 500 of /blocks/iomad_company_admin/editusers.php: call to get_string()
Invalid get_string() identifier: 'supervisor_name' or component 'moodle'. Perhaps you are missing $string['supervisor_name'] = ''; in lang/en/moodle.php?
line 356 of /lib/classes/string_manager_standard.php: call to debugging()
line 7427 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
line 500 of /blocks/iomad_company_admin/editusers.php: call to get_string()
Invalid get_string() identifier: 'supervisor_contact' or component 'moodle'. Perhaps you are missing $string['supervisor_contact'] = ''; in lang/en/moodle.php?
line 356 of /lib/classes/string_manager_standard.php: call to debugging()
line 7427 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
line 500 of /blocks/iomad_company_admin/editusers.php: call to get_string()
128 Users
Error reading from database

[More information about this error](https://docs.moodle.org/401/en_us_wp/error/moodle/dmlreadexception)

Debug info: Unknown column 'u.organization' in 'field list'
SELECT
DISTINCT CONCAT(u.id, CONCAT('-', c.id)) AS cindex, u.*, c.id AS companyid, c.name AS companyname, u.suspended, cu.managertype, cu.educator, u.organization, u.supervisor_name, u.supervisor_contact
FROM mdl_user u JOIN mdl_company_users cu ON (u.id = cu.userid) JOIN mdl_department d ON (cu.departmentid = d.id AND cu.companyid = d.company) JOIN mdl_company c ON (cu.companyid = c.id AND d.company = c.id)
WHERE u.id != '-1' and u.deleted = 0 AND u.id NOT IN (2) AND u.suspended = 0 AND u.id NOT IN (2) AND u.deleted = 0 AND u.suspended = 0 AND u.id IN (28,41,67,68,74,78,118,164,165,167,183,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,377,378,22,61,32) AND c.id = ? AND u.id NOT IN (
SELECT userid FROM mdl_company_users
WHERE companyid IN (3))
LIMIT 0, 30
[array (
0 => '1',
)]
Error code: dmlreadexception×Dismiss this notification
Stack trace:
line 494 of /lib/dml/moodle_database.php: dml_read_exception thrown
line 293 of /lib/dml/moodle_read_slave_trait.php: call to moodle_database->query_end()
line 1278 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->query_end()
line 2123 of /lib/tablelib.php: call to mysqli_native_moodle_database->get_records_sql()
line 2145 of /lib/tablelib.php: call to table_sql->query_db()
line 664 of /blocks/iomad_company_admin/editusers.php: call to table_sql->out()

**Comment by turf212** [comment]
The fields it's complaining about are extra fields you've asked for in the IOMAD reports and they don't exist in the database.  If you are trying to add optional profile fields then these would have the same name as if you were uploading them by CSV

**Comment by tbeachy** [comment]
Well, then this is somehow a secondary effect of https://github.com/iomad/iomad/issues/1852
These fields do exist in the database.  To get around the bug originally, I had to move the optional profile fields from the child companies they were in to the root company.  Maybe that has something to do with it, but I don't understand how to resolve this...

**Comment by tbeachy** [comment]
The optional profile field names are different in the database, they were renamed when moved to the root company.  But why wouldn't I be able to rename them without this happening?  Where are the old names coming from in this query?

**Comment by tbeachy** [comment]
I've renamed the fields (shortname) in the database to match what the strings are looking for exactly and it makes no difference.
I do notice that the record numbers in user_info_field start at 7.  I most likely deleted the original ones I set up on the child companies.  I will try to recreate them to see if that fixes this error for now, but it still seems like this is buggy behavior.

**Comment by turf212** [comment]
For optional profile fields you need to use the same format for the field as you would if you are uploading them via CSV.

From the help text below that setting field - 

_This is a list of profile fields separated by a comma. **If you want to use an optional profile field you need to use profile_field_ where is the shortname defined for the profile field.** The order given is the order they are displayed in._

So in this case if you use profile_field_organization, profile_field_supervisor_name, profile_field_supervisor_contact (assuming that is the same shortname as you've used for the optional profile fields) then it will work.

**Comment by tbeachy** [comment]
I'm not sure who is not understanding who...but are you thinking that I am wanting to upload users?  
My problem is I get this error when I try to Edit Users from the IOMAD dashboard (blocks/iomad_company_admin/editusers.php)  
It doesn't matter what I rename the shortname to, I cannot edit users.

**Comment by turf212** [comment]
I know you are not trying to upload users ;)  I'm talking about why simply putting organization,supervisor_name  and supervisor_contact in the settings will not work and has caused the error you are describing.

When you upload users via the CSV file the column names you need to use for optional profile fields needs to be _profile_field_<shortname>_.  So if you have an optional profile field which has the name Organization and the shortname organization then you need to use _profile_field_organization_.

The naming convention for the optional profile field extra fields in the reports uses the exact same naming convention.  So to add the extra reporting field for the optional profile field Organization, which has the shortname of organization, you need to add the value _profile_field_organization_ in the Local IOMAD settings plugin setting for reporting extra fields.  (as the help text immediately below states)

**Comment by tbeachy** [comment]
Ok, thank you for specifying.  I don't remember ever seeing the IOMAD settings page before and couldn't figure out what help text you were referring to.  I see it now and understand.
I still have questions, but will work with it first to see if I can't work them out myself before I bother you any further.
Thanks!
