### ISSUE TITLE
JSON errors when manually completing an activity for a user

### ISSUE THREAD

**Issue by dallenk** [iomad/iomad#1891]
Long story short..  I switched to a new application for SCORM creation (1.2).. combined that with the observer bug that was recently fixed and I find I have to change course completion criteria for every single course on the site, then needed to manually complete activities for users on some courses.

Previously when a user completed a SCORM activity the completion status looked like this:
**cmi.core.exit => suspend
cmi.core.lesson_location => 5324503
cmi.core.lesson_status => completed
cmi.core.total_time => 00:23:11.00
cmi.suspend_data => 5324474,5324475,[lots more]**

with the new software, activity completion looks like:
**cmi.core.lesson_location => 30
cmi.core.lesson_status => passed
cmi.core.score.raw => 100
cmi.core.total_time => 00:00:22.12**

I had to unlock each course's SCORM activity completion criteria to passed and completed, then manually compllete the actvity for students.. each time I see this error (but it does show completed after a page refresh)
 
![image](https://github.com/iomad/iomad/assets/2725066/109d2087-5836-466f-9dab-924c415eed2e)

**Comment by turf212** [comment]
There was a notification in the code in one of the completion observers.  fixed in 2e77b8c44c4d580a71bc001c7fcabf5d5812d9eb
