### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by sarathp06** [iomad/iomad#1897]
Hi everyone,

Users are experiencing errors while logging in. Please find the attached screenshot.

![iomad_login_error(2)](https://github.com/iomad/iomad/assets/54504917/7e8270ce-b213-4789-a1f2-a7e376b3edbc)

IOMAD Version 4.1.4 (Build: 20230612)

**Comment by turf212** [comment]
fixed in f59f27054799225a3e9ca20f87530f00209bcb6cfrom Date:   Fri Sep 8 12:50:30 2023 +0100
