### ISSUE TITLE
Custom menu item not highlighted after selection

### ISSUE THREAD

**Issue by kirck1984** [iomad/iomad#1898]
I am using the IOMAD Boost thema.

On the editing page of a company, when I add a link to the navigation bar (custom menu label) that points to one of my static pages, the link is not highlighted with the small blue bar as it is when I click on one of the other menu items.

I added the link via the custom menu items section in the company settings:
"MyPage||/local/staticpage/view.php?page=my_static_page".

In practice, when I click on the customised menu item, it is not highlighted, but the first item (the 'Home' button) is highlighted by the blue bar.

I know that on Moodle this bug has been fixed.

I would be grateful if you could provide me with a solution.

Thank you

**Comment by turf212** [comment]
This will be because the IOMAD boost theme hadn't been updated. New versions have been added as we move up the branches and some fixed have been applied where there were other issues found bu re-cloning the Moodle themes and re-creating the IOMAD ones from there.
