### ISSUE TITLE
has_capability issue

### ISSUE THREAD

**Issue by lagosgian** [iomad/iomad#1899]
Dear all,

When accessing the report builder we found the following bug.
In part of the code the function has_any_capability is called. This redirects to lib/accesslib.php which redirects to iomad:has_capability in local/iomad/lib/iomad.php.

In the accesslib you have this part of code 
` if (iomad::has_capability($capability, $context, $user, $doanything)) {`

while in iomad:has_capability you have 
`public static function has_capability($capability, context $context, $companyid = 0) {`

In this case the userid is send but received as $companyid resulting in line 1748 returning wrongfully false 
```
  // If companyid supplied then check the user is a member
        if ($companyid) {
            if (!$DB->record_exists('company_users', ['companyid' => $companyid, 'userid' => $USER->id])) {
                return false;
            }


```
In the above record_exists the $companyid and the $USER->id refers to the same value. userid.

**Comment by turf212** [comment]
Ah - thanks for that.  I've stripped the $user, $doanything from the call as it's not needed in the check.
