### ISSUE TITLE
Dpt Company Managers can see ALL users within company_managers_form.php

### ISSUE THREAD

**Issue by BananaRama203** [iomad/iomad#190]
If you have a Company Manager or a Dpt Company Manager for a sub Department in the right hand box the user can see all users within the company and not just the users within their own department.

**Comment by turf212** [comment]
That's because Company managers are designed to be managers for the whole company.  The Department manager role is what you should be using for managers at a department level.  There is no concept of a department company manager.

**Comment by AC-Education** [comment]
Sorry that's what I meant department manager. Is there a permission within define roles for seeing all users outside of their department?

**Comment by BananaRama203** [comment]
Confirmed as User Error not bug.
