### ISSUE TITLE
admin login aligned to wrong child tenant/company

### ISSUE THREAD

**Issue by iomadramk** [iomad/iomad#1900]
Hi,

I am using the latest version of IOMAD. Whilst I created a few child companies/tenants and as as admin I was trying use many features, for the past couple of weeks I can only login as admin from one of the child companies and not the main one. Anyone face the same issue? If I try to login, it gives me a 404 - not found error. But if I login from the child company, i am able to. 

Ram

**Comment by turf212** [comment]
closed in #1937
