### ISSUE TITLE
creating courses

### ISSUE THREAD

**Issue by kzpromo** [iomad/iomad#1901]
Good afternoon, I have a problem with creating courses, there is no option to create courses in any role, when creating a company user, only manager, training director, report viewer and user are offered. None of these roles have access to create courses or manage categories. 

The second problem is in license management, not a single course appears in the list.

What to do?

**Comment by calbasi** [comment]
Same here. Fresh install, 4.1 long term support

**Comment by turf212** [comment]
The capability to create a course within the IOMAD dashboard is block/iomad_company_admin:createcourse It's not added to the role by default but you can change this by editing the company manager role under site administration -> users -> permissions -> define roles, clicking the cog to edit the company manager role and then finding and allowing the capability.

Note - this will allow any company manager to create a course.  You take take it away on a company basis using the restrict roles menu in the IOMAD dashboard.
