### ISSUE TITLE
"SCORM - LMSCommit failed" error on SCORM completion where a certificate is issued - IOMAD_401_STABLE

### ISSUE THREAD

**Issue by ni-ght** [iomad/iomad#1903]
Hello,
This is very similar to the closed issue #1882, and can be traced back to the "mtrace" call in:
file: iomad_track/classes/observer.php
function: public static function record_certificates
line: 175
```
// Debugging
if ($showdebug) {
    mtrace('local_iomad_track: certificate recorded for ' . $user->username . ' in course ' . $courseid . ' filename "' . $filename . '"');
}
```

Many thanks.

**Comment by turf212** [comment]
This was fixed in commit e158a5bf58190dc0cbe1d45a84512dd840f54047 - the default was changed to not show the line that the certificate was created.
