### ISSUE TITLE
Exception : Class "theme_iomadbootstrap\output\custom_menu" not found

### ISSUE THREAD

**Issue by ericfalcon** [iomad/iomad#1904]
Hello i've a bug with iomad 4.02 STABLE.
I use php 8.0
when i install, i've the message "Exception : Class "theme_iomadbootstrap\output\custom_menu" not found"

Debug info:
Error code: generalexceptionmessage
Stack trace:
line 106 of /theme/iomadbootstrap/classes/output/core_renderer.php: Error thrown
line 219 of /lib/mustache/src/Mustache/Context.php: call to theme_iomadbootstrap\output\core_renderer->custom_menu_flat()
line 138 of /lib/mustache/src/Mustache/Context.php: call to Mustache_Context->findVariableInStack()
line 52 of /home/ericfalcon/iomaddata/localcache/mustache/1698418704/iomadbootstrap/__Mustache_265fa272c22a3008af0b64050130ad78.php: call to Mustache_Context->findDot()
line 144 of /home/ericfalcon/iomaddata/localcache/mustache/1698418704/iomadbootstrap/__Mustache_f888e64e13451a41f12b1b83cba5ca38.php: call to __Mustache_265fa272c22a3008af0b64050130ad78->renderInternal()
line 67 of /lib/mustache/src/Mustache/Template.php: call to __Mustache_f888e64e13451a41f12b1b83cba5ca38->renderInternal()
line 208 of /lib/outputrenderers.php: call to Mustache_Template->render()
line 51 of /theme/iomadbootstrap/layout/columns.php: call to renderer_base->render_from_template()
line 1508 of /lib/outputrenderers.php: call to include()
line 1434 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
line 578 of /lib/outputrenderers.php: call to core_renderer->header()
line 296 of /admin/renderer.php: call to plugin_renderer_base->__call()
line 945 of /admin/index.php: call to core_admin_renderer->admin_notifications_page()

**Comment by nayabbukhari** [comment]
It works!
file: theme/iomadbootstrap/output/core_renderer.php
Line # 28-50

use coding_exception;
use html_writer;
use tabobject;
use tabtree;
use custom_menu_item;
use custom_menu;
use block_contents;
use navigation_node;
use action_link;
use stdClass;
use moodle_url;
use preferences_groups;
use action_menu;
use help_icon;
use single_button;
use paging_bar;
use context_course;
use pix_icon;

defined('MOODLE_INTERNAL') || die;

require_once($CFG->dirroot.'/local/iomad/lib/user.php');
require_once($CFG->dirroot.'/local/iomad/lib/iomad.php');

**Comment by ericfalcon** [comment]
Thank you, it's done !
But i have two new problems
A box appear with "SyntaxError
Unexpected token '<', "<br /> <b>"... is not valid JSON"

And an error appear :
"user_picture::fields() is deprecated. Please use the \core_user\fields API instead.
line 255 of /lib/outputcomponents.php: call to debugging()
line 110 of /blocks/iomad_onlineusers/block_iomad_onlineusers.php: call to user_picture::fields()
line 337 of /blocks/moodleblock.class.php: call to block_iomad_onlineusers->get_content()
line 231 of /blocks/moodleblock.class.php: call to block_base->formatted_contents()
line 1231 of /lib/blocklib.php: call to block_base->get_content_for_output()
line 1289 of /lib/blocklib.php: call to block_manager->create_block_contents()
line 377 of /lib/blocklib.php: call to block_manager->ensure_content_created()
line 4193 of /lib/outputrenderers.php: call to block_manager->region_has_content()
line 30 of /theme/iomadbootstrap/layout/columns.php: call to core_renderer->blocks()
line 1508 of /lib/outputrenderers.php: call to include()
line 1434 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
line 179 of /my/index.php: call to core_renderer->header()"

**Comment by turf212** [comment]
Block online users has been updated to use the same code as the Moodle online users and filter the users accordingly.  This has been updated in 4.1 and 4.2 branches in 14fc3058962db584e4376b9f70d0991039a14395 d97224d1b639080c462d711d953fa25fe23e479b and 1aebe34a52b102b37cc566d7397583043bef021e 3290aa8c27e69b6439cc52950481c4bf4468711b
