### ISSUE TITLE
How to add course shortname after coursename on course selector

### ISSUE THREAD

**Issue by ajinursyamsi17** [iomad/iomad#1906]
Hi,
to identify the right course from many duplicate course name, I want to display course shortname also when select course from Assign to Company.

where is the file and line number the code that can I add?

Thank you in Advance

**Comment by turf212** [comment]
It's in the blocks/iomad_company_admin/lib/course_selectors.php file.  The class you want is specifically the potential_company_course_selector class and the class function find_courses().  It returns the list of courses ($course) so you could do something like

`$course->fullname .= " (" . $course->shortname . ")";`

in this section

```
        // Only show one list of courses
        $availablecourses = array();
        foreach ($allcourses as $course) {
            $availablecourses[$course->id] = $course;
        }

```
