### ISSUE TITLE
list of courses don't appear

### ISSUE THREAD

**Issue by ericfalcon** [iomad/iomad#1907]
IOMAD 4.1.6, PHP 8, MariaDB
the list of courses does not appear in:
- manage company groups
- assign course groups
- create a license
whereas when I want to assign a course to a company, the list of courses appears.

**Comment by NAUTH05** [comment]
i got the same problem. Have u sole this one?

**Comment by turf212** [comment]
Have you checked that the courses are set to show in their settings?

**Comment by turf212** [comment]
Updated those pages to show hidden courses and mark them as such to prevent this type of confusion - 8965584f91cb248d871a78539f497adeecd16ded
