### ISSUE TITLE
Can IOMAD work on Nginx with multiple domains?

### ISSUE THREAD

**Issue by afadillah98** [iomad/iomad#1909]

**Comment by turf212** [comment]
It should do.  We are using $_SERVER['SERVER_NAME'] to get the host part of the URL being requested. If this is not working directly as it could be returning __:8080_ as that is the default for the configuration you can get it to overwrite by adding a fastcgi_param.

See here - as an example - for more info https://serverfault.com/questions/924323/serverserver-name-returns-nginx-reverse-proxy-port-name
