### ISSUE TITLE
Migration from moodle to IOMAD 4.1.6

### ISSUE THREAD

**Issue by Raphael-Caudron** [iomad/iomad#1910]
Hello, I've tried to migrate my moodle from a personalised one to IOMAD (additional plugins, another theme ...) but i've encountered a few problems such as not being asked to create a Client administrator, and after checking the database, only the role "company manager" was created (https://github.com/iomad/iomad/assets/91120730/b7af768d-943b-4a59-9632-0034dc4b17cd). Another one is the "block_iomad_company_admin Incorrect legacy role definition for type: companymanager" (same as a previous issue which i saw) not only with block_iomad_company_admin but with other blocks as well. When i restarted it, it went further but stopped at other ones for the same reason so I continued on restarting it until It wasn't written anymore (I have a sql dump with a number in the prefix maybe that's why ?) The last two bugs were about "edit_department was not found (https://github.com/iomad/iomad/assets/91120730/27716b0f-b598-4563-aff8-a52573dd0ff6) and when debugging mode is on, when i try to go on dashboard or my course there is what is said : (https://github.com/iomad/iomad/assets/91120730/7a4ca4fb-fce9-42ab-937f-82b7699d7fd2). After these, I tried to do it with a classic moodle but there were the same problems. Sorry for the long message but I prefer to say everything from the beginning if you know a solution for each issue.

**Comment by turf212** [comment]
This sounds like only the IOMAD plugins were added and not the full code (which replaces the Moodle one).  The role archetypes are added to Moodle core in our code.
