### ISSUE TITLE
No courses shown in 'My Courses' block when using 'log in as'

### ISSUE THREAD

**Issue by gregmy** [iomad/iomad#1912]
Hi,

we have just upgraded to M4.1.6 and are on Iomad 401 Stable, branch 1460221. Now (and only since the upgrade) when I use 'log in as' as a site admin, the 'courses in progress' tab in the My Courses block displays no courses for any user, and shows the message "No courses in progress". 

The user may in fact have any number of courses in progress, and when they log in as themselves they can see this tab populated with their courses - it just doesn't work when using 'log in as'. This is not the case on a non-Iomad installation of the same Moodle version.

This is frustrating as it's one of the main ways we diagnose issues reported by users. Any help appreciated.

**Comment by turf212** [comment]
The very helpful message telling you that for security Javascript has been disabled when you log in as a user is explaining what is happening.  I had the same panic as you - that something had happened to the user's courses.  Moodle is being "helpful" here, unfortuantely.
