### ISSUE TITLE
user list shows a comma in the department, throwing exception error when editing

### ISSUE THREAD

**Issue by dallenk** [iomad/iomad#1913]
@turf212
I'm having a very odd problem with a company.. two users are showing a comma in the departments list and this throws an exception when trying to edit the list.   I found in mdl_company_users the userid was listed twice, one for the actual company, one for 0 (which didn't exist)

I can only guess it was saved with a blank entry on a previous edit?

I removed both entries on my sandbox server for the duplicated userid's in mdl_company_users but no change.

![image](https://github.com/iomad/iomad/assets/2725066/f6fdd94c-08ce-4150-b7af-5b884d724bb9)

As the admin, I can't edit this out, and I can't find in the database where the offending data is pulling from, 

Coding error detected, it must be fixed by a programmer: Options for select element must contain an option for the specified value

```
Debug info:
Error code: codingerror×Dismiss this notification
Stack trace:
line 183 of /lib/classes/output/inplace_editable.php: coding_exception thrown
line 91 of /blocks/iomad_company_admin/classes/output/user_roles_editable.php: call to core\output\inplace_editable->set_type_select()
line 155 of /blocks/iomad_company_admin/classes/tables/editusers_table.php: call to block_iomad_company_admin\output\user_roles_editable->__construct()
line 842 of /lib/tablelib.php: call to block_iomad_company_admin\tables\editusers_table->col_managertype()
line 2059 of /lib/tablelib.php: call to flexible_table->format_row()
line 2183 of /lib/tablelib.php: call to table_sql->build_table()
line 664 of /blocks/iomad_company_admin/editusers.php: call to table_sql->out()

Notice: Undefined offset: 0 in /var/www/vhosts/sandbox.domain.ca/iomad/blocks/iomad_company_admin/classes/tables/editusers_table.php on line 91
```

SQL looks like:
```
$users = $DB->get_records_sql("SELECT DISTINCT userid 
                                       FROM {company_users}
                                       WHERE companyid = :companyid",
                                       ['companyid' => $companyid]);
```

So i'm not sure where else it could be from?

Thanks.

**Comment by dallenk** [comment]
edit/update:   I was on the wrong sandbox after deleting the offending entries.. it did work after all.

Can you check to ensure a blank save can't be made by mistake?

**Comment by encodecreate** [comment]
Can we close this issue?

**Comment by dallenk** [comment]
I'll try to duplicate the problem on my sandbox and find how it happened in the first place.
