### ISSUE TITLE
Managers no longer receive copies of user course completion emails

### ISSUE THREAD

**Issue by dallenk** [iomad/iomad#1914]
I don't know when this happened, but since one of the upgrades, company managers are no longer receiving a copy of the emails.. the option is checked in the email configurations.

**Comment by dallenk** [comment]
@turf212 Hey Derek any chance to look at this one?   Thanks!

**Comment by dallenk** [comment]
Bump?   @turf212

**Comment by dallenk** [comment]
bump ?  @turf212

**Comment by dallenk** [comment]
Lots of testing over the weekend with different methods of getting a certificate to the company manager.. only the iomadcertificate "email teachers" and email others works.  

A different email template for when a quiz is completed works, but for some reason the IOMAD certificate plugin won't send emails to the company manager.

completed assessment email template to manager: works
iomadcertificate email teachers: works
iomadcertificate email others: works

external supervisor field: does not work
Send Manager emails (completion): does not work

Is there some debug code I can try to see where/why this isn't working?  Are there dependent permissions?   This worked for a long time, then stopped but I don't know which update broke it for me.

**Comment by LeonidasFRA** [comment]
I'll bump it, I have the same problem, some of the company manager emails won't be generated (didn't test them all, it could be a cool feature to be able to manually send them as a test). I still didn't figure out the reason. 
I was on the 4.2 with this problem, I thought I might have broke something.
I made a fresh install for the 4.3 (although reusing the DB), but I still have the same behavior : User Completion Email is being sent, but the Manager one doesn't.
The external supervisor worked with the 4.2 (not tested on the 4.3) but I had <p> and </p> tags around the text.

**Comment by dallenk** [comment]
oh good!  I'm not the only one, i've been changing everything I can change on a sandbox thinking I broke it somehow.   i'm glad someone else is seeing it also.   @turf212 , is there anything we can provide to test it further?

**Comment by turf212** [comment]
So - I had thought that this was that the managers were not getting cc'd into the user's course completion message - but it's the manager course completion message which is at fault - which could be a digest or a single email.  It looks like this got lost somewhere in a new version.  Will add it back in as it's own scheduled task.

**Comment by turf212** [comment]
So a bit of digging later. The dedicated email which is sent out to company managers when a user completes a course has not been part of the system since IOMAD 3.2. The manager is CC'd into the email the user gets which also includes their certificate.

I'm conscious of the system spamming the managers as they could get:
- CC'd into the user completion email
- Their own email sent directly

For a large company, the wealth of emails which a manager could get sent could be abusive.

I think this should be "direct" managers only, or company managers only (with a switch to define that). CC'd managers also set up the same way. This would allow CC'd managers to be direct managers and directly email managers to be company managers and would prevent the duplication of emails going to everyone.

Thoughts?

**Comment by turf212** [comment]
The other option is that it's the User's email which is being sent out and the manager is not being cc'd to that one - so check that this is the right one that is enabled for the manager.  This email template is "User course completion" for this.

**Comment by dallenk** [comment]
> I think this should be "direct" managers only, or company managers only (with a switch to define that). CC'd managers also set up the same way. This would allow CC'd managers to be direct managers and directly email managers to be company managers and would prevent the duplication of emails going to everyone.
> 
> Thoughts?

That would be great!

**Comment by dallenk** [comment]
Sorry to be a pain in the arse Derek :)   Any chance of a timeline for this one?   Lots of unhappy managers not getting updates for the last couple months.  @turf212

**Comment by dallenk** [comment]
Bumping up please.. Anything I can provide to help @turf212 ?

**Comment by dallenk** [comment]
Bumping again....  Derek, what can I do to help this one?  It is quite an important one for many of our managers.

**Comment by dallenk** [comment]
@turf212  bumping please.

**Comment by dallenk** [comment]
Hi Derek,  do you have any plans on fixing this one?  @turf212

**Comment by dallenk** [comment]
bumping again.. @turf212    ?

**Comment by dallenk** [comment]
Almost a year.   Any chance this being fixed??

**Comment by turf212** [comment]
all of the processing for the email reports was spilt out into their own separate tasks but this was back in 2022 - so unsure where it actually stopped working.

In any case - I've reworked that task to a new task and created 2 new tasks and digest emails for course completions in the last week and training expiring in the coming week. The email templates for these last two have been added as disabled to existing systems, so you will need to switch them on if you want them in the tenant (I did this to prevent emails going out on upgrade that you didn't know about and then all of your tenant complaining that they were getting them!).  Same for any template sets you may have saved - they are added disabled.

You can either do this by tenant in the GUI or in the database for everyone.  

```
update mdl_email_template set disabled=0 where name='expiring_digest_manager';
update mdl_email_template set disabled=0 where name='warning_digest_manager';

```
(can also add and companyid = or in (1,2,3,) )

and 

```
update mdl_email_templateset_templates set disabled=0 where name='expiring_digest_manager';
update mdl_email_templateset_templates set disabled=0 where name='warning_digest_manager';

```

This has been pushed to 4.1, 4.2 and 4.3 branches.

**Comment by turf212** [comment]
I've left #2048 open in case there are issues :)
