### ISSUE TITLE
Ecommerce Configuration issue

### ISSUE THREAD

**Issue by deepaksharma0311** [iomad/iomad#1915]
Hello 

I am using iomad 4.1 , Facing issue setup the ecommerce . 

I have done all the settings but still it show configration settings issue . Please check screenshots.

![image_2023_12_07T07_17_23_872Z](https://github.com/iomad/iomad/assets/43440608/1128fad9-ce46-453d-b787-064dbdcde95a)

![image_2023_12_07T07_18_27_477Z](https://github.com/iomad/iomad/assets/43440608/b5a5202f-b703-4991-a6d4-3659f48b1452)

**Comment by turf212** [comment]
Commerce admin email account isn't filled in.
