### ISSUE TITLE
Timeline block not working

### ISSUE THREAD

**Issue by sarathp06** [iomad/iomad#1917]
Hello everyone, I have installed IOMAD 4.1.6 (Build: 20231009). However, the timeline block is not working. When I logged in as a student, in the calendar I could see that the quiz was due but not on the timeline.

Initially, there was two timeline block and I removed both from the dashboard. Then when I tried to add there was only one timeline block.

**Comment by turf212** [comment]
we haven't made any changes to the timeline block and this remains as core Moodle code.  I can't see any changes in the block past Feb 2023. As standard there is a default timeline block added to the default dashboard.  You can add another one, which may explain why you had to and then on removal and re-adding you only got one.
