### ISSUE TITLE
double declaration of functions

### ISSUE THREAD

**Issue by CesparRes** [iomad/iomad#1918]
We just updated to 402, and ran into an issue when manually running any cron task.
It appears two functions are previously declared:

Fatal error:  Cannot redeclare tool_task_status_checks() (previously declared in /var/www/vhosts/<domain>
/httpdocs/admin/tool/task/lib.php:34) in /var/www/vhosts/<domain>/httpdocs/admin/tool/task/lib.php on line 34

Fatal error:  Cannot redeclare tool_task_mtrace_wrapper() (previously declared in /var/www/vhosts/<domain>/httpdocs/admin/tool/task/lib.php:48) in /var/www/vhosts/<domain>/httpdocs/admin/tool/task/lib.php on line 48

Im unsure why or where the 1st declaration of the function exists, but for now I've simply "if (!function_exists())" the two functions to fix this. However I'm concerned that one of the 2 declared functions may have extra features that may not be correctly loaded with this extra code.

*edit*

We've also just completely stood up a totally new website and fresh new install pulled directly from 402 stable branch, the same issue occurs on manual running cron tasks.

**Comment by turf212** [comment]
Weird - the only definition of that function is in the files which you've listed only.

I've installed latest 4.2 branch as a clean site with no additional plugins and I'm not getting this error message when I run cron.  Is it when you are using the "run now" option for the task?

**Comment by I123U** [comment]
Hello, that's correct. The error only occurs when running the cron manually with "run now" option, as I recall. It is the same issue on both instances of 4.2 we've installed.

**Comment by turf212** [comment]
is there a particular scheduled task that causes it or is it all of them?

I've tested with a number of core Moodle and IOMAD tasks and not getting this error.  This is a clean IOMAD 4.2 site with 1 user, 1 company and no optional plugins (other than IOMAD ones)

Do you have any optional plugins installed?
