### ISSUE TITLE
previous course history not deleted when un-enrolled.

### ISSUE THREAD

**Issue by dallenk** [iomad/iomad#1919]
So.. I have a course expiry set, which un-enrolls the student after 90 days.  I would assume that all the details and history would be removed when this happens but it isn't.  This is confusing to both the student and the teacher.

after a re-enrollment, students see this:
![image](https://github.com/iomad/iomad/assets/2725066/624fbd1a-010f-4e44-acaf-1fa56707ffde)

They have not viewed the activities since being un-enrolled.

Should this data be removed when un-enrolled on a course??

**Comment by turf212** [comment]
No - Moodle doesn't remove much when a user is removed.  If you want them cleared down then you can do this from the user reports.
