### ISSUE TITLE
Automailer sends email twice bug

### ISSUE THREAD

**Issue by BananaRama203** [iomad/iomad#192]
Hi, I can't seem to pinpoint exactly what is causing it but auto emails being fired out of IOMAD are getting sent twice for no apparent reason.

**Comment by turf212** [comment]
This is, again, because you have the main support email address as you.  The logic was that the site admin would get copied into every email and you were sending the email too.  You got two emails.  The user should only have received one.  I'll have a look at this logic.

**Comment by turf212** [comment]
I have updated this so that is the person creating the user account is a site admin then they will not be cc'd in.  If a company manager creates the user then they will get a copy of the email.

**Comment by BananaRama203** [comment]
This has been resolved in the latest batch of Commits (finally lol :+1: )
