### ISSUE TITLE
Learning Path Management

### ISSUE THREAD

**Issue by levi19982** [iomad/iomad#1923]
Hi, 

I created a new Learning Path in Learning Path Management in IOMAD's settings, make it active, added courses to it (sequential), and assigned students to it. Then I added Moodle's Learning Paths block but students unable to see that learning path, but they see the one I created with core Moodle. Is there anything else I need to set in IOMAD's learning path or that1s all? Or is there a cron job that needs to be run?

**Comment by mikeaveli007** [comment]
Did you ever figure this out?  I'm having a similar issue but only in my dev environment where I am testing this feature.  The only other thing I noticed is different is on the page where you assign students to the learning path.  

On the site that doesn't work, when you click to add a student they show on the left side as being in the learning path but still show up as potential students.  Meaning, they show in both areas. 

On the site that does work, when you click to add a student they move from potential to assigned.

**Comment by turf212** [comment]
The block which displays the learning paths for the user is the iomad_learningpath "Learning paths" block. This is IOMAD functionality and was there before Moodle, confusingly, added the Learning Plans as part of the competency subsystem.

We have recently added learning paths as feeders to the competency learning plans in 286da7a9ac55d1c8e7c69686d7b708f11884b259 and added it to the Courses page by default too in e07ccf48497e03212155c43a34a977c36edc5a02
