### ISSUE TITLE
WS function core_course_delete_courses REST call not returning valid JSON

### ISSUE THREAD

**Issue by francoisjacquet** [iomad/iomad#1926]
Hello,

I was testing the `core_course_delete_courses` web service function with IOMAD 4 from RosarioSIS.

The function does not return valid JSON when called from the REST API.

This is due to the IOMAD overhead adding HTML notifications to the event.

See the "errors" on this screenshot:

![image](https://github.com/iomad/iomad/assets/4723501/6c387c47-305b-40e8-a1a8-c55f66439461)

Note the var_dump is the array sent to the Moodle API from RosarioSIS.

**Comment by turf212** [comment]
The pre_course_delete hooks had echos in them when they shouldnt - originally added in 7e89cfd35a87108b638403803ae08fa1078c5eec
