### ISSUE TITLE
Security issue on admin block

### ISSUE THREAD

**Issue by jackkongjr** [iomad/iomad#1929]
Hello,
I have to report that there is a potential sql injection in the file /blocks/iomad_company_admin/iomad_courses_form.php

`$autofrom = " LEFT JOIN {company_course_autoenrol} cca ON (ic.courseid = cca.courseid AND cca.companyid = " . $companyid . ")";`

and in the immadiately after select:    `  '$companyid' AS companyid`

Since this vulnerability has lower impact and high complexity I think is not necessary to request a cve id, but you can decide differently.

**Comment by turf212** [comment]
This has been addressed in the following commits and branches

0d9f46e4179c4bd6663ad4b35f8cab29ec4b724f (HEAD -> IOMAD_400_STABLE, origin/IOMAD_400_STABLE, iomadgit/IOMAD_400_STABLE) IOMAD: wrong parameter type being used for companyid

4dd3bed4474b3b2c22813f9575e49b996b650839 (HEAD -> IOMAD_401_STABLE, origin/IOMAD_401_STABLE, iomadgit/IOMAD_401_STABLE) IOMAD: wrong parameter type being used for companyid

f2e6bb8c13a8e8119837663b4cf64228edc59d01 (HEAD -> IOMAD_402_STABLE, origin/IOMAD_402_STABLE, iomadgit/IOMAD_402_STABLE) IOMAD: wrong parameter type being used for companyid
