### ISSUE TITLE
None of the sort functions work in report_users/index.php

### ISSUE THREAD

**Issue by BananaRama203** [iomad/iomad#193]
When you try to sort by Firstname, Lastname, Email etc within the user report. It doesn't sort the results. However it does call it within the header.
i.e.

/local/report_users/index.php?sort=lastaccess&dir=DESC&page=1&perpage=30

**Comment by BananaRama203** [comment]
This issue is the same as #209 The fix is remove the actionlink and just change it to a plain string header. (Of course it would be better to retain the functionality and it work) But this will at least prevent errors in the meantime.

**Comment by RyanHamlin1234** [comment]
Confirmed as same issue as #218 and confirmed in vanilla 2.8 Iomad.

**Comment by turf212** [comment]
closed
