### ISSUE TITLE
Undefined variable $move when removing user from a role in Users/User Roles

### ISSUE THREAD

**Issue by dallenk** [iomad/iomad#1930]
Warning: Undefined variable $move in /var/www/vhosts/sandbox.domain.ca/iomad/local/iomad/lib/company.php on line 1079
Warning: Undefined variable $move in /var/www/vhosts/sandbox.domain.ca/iomad/local/iomad/lib/company.php on line 1446

**Comment by turf212** [comment]
missing the default.  Will add.
