### ISSUE TITLE
IOMAD Dashboard - Custom Reports

### ISSUE THREAD

**Issue by michaelbradley376** [iomad/iomad#1932]
I do not see any custom reporting options that can be added to the IOMAD dashboard.

Custom reports in the Site Administrator menu do not seem to be limited to company data, only the entire Moodle site.

Any ideas?

**Comment by turf212** [comment]
We've not added any data filters in for the company data structures to the custom reports yet.  I'd hoped to get it in for the 4.3 branch release but will be 4.4 now.

**Comment by michaelbradley376** [comment]
Thank you for the update. We are excited to see this feature. Do you have an estimated release date? Any need for beta testing?

Thank you,

Michael Bradley

Michael Bradley
________________________________

**Comment by turf212** [comment]
This was added to 4.1,4.2 and 4.3 branches in commits 77fad813b6d5bc6a3e9d9ab7f2268dd025fb5c2f d158fc93a9bb04542df4637471ad420a404b5792 and f993cac5eb6ef93994a04c0ac7658e26e9b12f43
