### ISSUE TITLE
user_picture::fields() is deprecated. Please use the \core_user\fields API instead.

### ISSUE THREAD

**Issue by dallenk** [iomad/iomad#1935]
When viewing a users profile, and debuging is enabled.

user_picture::fields() is deprecated. Please use the \core_user\fields API instead.
line 255 of /lib/outputcomponents.php: call to debugging()
line 110 of /blocks/iomad_onlineusers/block_iomad_onlineusers.php: call to user_picture::fields()
line 337 of /blocks/moodleblock.class.php: call to block_iomad_onlineusers->get_content()
line 231 of /blocks/moodleblock.class.php: call to block_base->formatted_contents()
line 1231 of /lib/blocklib.php: call to block_base->get_content_for_output()
line 1289 of /lib/blocklib.php: call to block_manager->create_block_contents()
line 377 of /lib/blocklib.php: call to block_manager->ensure_content_created()
line 4197 of /lib/outputrenderers.php: call to block_manager->region_has_content()
line 55 of /theme/iomadboost/layout/drawers.php: call to core_renderer->blocks()
line 1508 of /lib/outputrenderers.php: call to include()
line 1434 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
line 205 of /user/profile.php: call to core_renderer->header()

**Comment by turf212** [comment]
That block is very old code.  I've updated it to use the current online users code but I've also updated the core online_users code to filter by company too, so we can drop the IOMAD specific one at some point.

**Comment by turf212** [comment]
fixed in 18f3aa675ec624215e8cd33799461f36c0857981
