### ISSUE TITLE
Login As is broken

### ISSUE THREAD

**Issue by andrewhancox** [iomad/iomad#1937]
When a user is editing company A and then, without switching companies, uses login as to switch to a user from company B they will be logged in as the new user but retain the editing company of the initial user.

This is caused by the function \profile_get_user_fields_with_data calling \iomad::get_my_companyid without passing through a userid. This means the \iomad::get_my_companyid function uses the USER global which, at this point, has not yet been switched over.

As this is an API change to a couple of functions I'm just writing a quick hack to resolve it for my client but it's very confusing and has resulted in some very confusing issues while testing.

**Comment by andrewhancox** [comment]
Looking at the open issues, searching for login as, I can see several that relate to this problem, for example https://github.com/iomad/iomad/issues/1900

**Comment by turf212** [comment]
Doesn't look like the same issue.  However - we can unset the company from the users SESSION (which is what those functions are checking against) as part of the login as process.

If you change line 80 of course/loginas.php to be :

```
unset ($SESSION->currenteditingcompany);
unset ($SESSION->company);

// Login as this user and return to course home page.
\core\session\manager::loginas($userid, $context);
```

that should be sufficient.  Let me know and I'll add to core.

**Comment by turf212** [comment]
Added to 4.1 and 4.2 branches.
