### ISSUE TITLE
Issue with resource links

### ISSUE THREAD

**Issue by mikeaveli007** [iomad/iomad#1938]
After recent update our resource links no longer work.  It looks like the code was updated to make them relative urls instead of absolute in commit `1710f85` but in our case since we are serving the platform from a subfolder, this breaks all of those links and they no longer work.  I reverted these changes in our fork but putting it out there in case anyone else runs into this same issue when using a subfolder domain.

**Comment by turf212** [comment]
The fix you referenced was to ensure that links being sent out on activities got the right URL when there were more than one one the site.  It will be the pattern matching of that which is causing the issue.

**Comment by turf212** [comment]
I've changed the method in URL Page and resource which puts back the $CFG->wwwroot but runs a function to strip out the hostname only leaving the rest including the installation subdirectory.
