### ISSUE TITLE
Report "View pdf Certificate" returns NULL course grade in PDF

### ISSUE THREAD

**Issue by BananaRama203** [iomad/iomad#194]
When viewing a learner's certificate as a SA, CM, DCM etc within the reports it will return a null course completion grade 

FYI 
- Save certificate option does not effect the bug

**Comment by turf212** [comment]
the defaults for the standard certificates don't handle the user properly.  The "sample" certificate does.  I'll change the defaults to work.

**Comment by BananaRama203** [comment]
Confirmed as Fixed in commit 78e95ffd09d1fe3d50b535f4b496080b8365caf0
