### ISSUE TITLE
classroom_list.php error

### ISSUE THREAD

**Issue by jgdk** [iomad/iomad#1940]
On line 119 in the file: /clocks/iomad_company_admin/classroom_list.php it seems to call a redundant class?

$searchform = new iomad_company_search_form($baseurl, []);

Because when I comment it out, then it classroom_list.php works:

// $searchform = new iomad_company_search_form($baseurl, []);

// echo html_writer::start_tag('p');
// $searchform->display();
// echo html_writer::end_tag('p');

Cheers :-)

**Comment by turf212** [comment]
Looks like one of the new search classes wasn't merged back from 4.3 to 4.1 or 4.2 when the classroom changes were back-ported.  I've added these and pushed the fixes.  Thanks for letting me know.
