### ISSUE TITLE
403_STABLE: errors enrolling or unenrolling from course (debug enabled)

### ISSUE THREAD

**Issue by dallenk** [iomad/iomad#1941]
PHP 8.0.30 (cli) (built: Sep  2 2023 08:05:13) ( NTS )
46b2929eb0c (HEAD -> IOMAD_403_STABLE, tag: IOMAD_403_3, origin/IOMAD_403_STABLE) IOMAD: plugin name change on auth_iomadoidc for other lang packs

In LIT user_enrolment_created
This is a self enrolment course
Exception encountered in event observer '\local_iomad_track\observer::user_enrolment_created': Error reading from database (Table 'db_sandbox_domain_ca.mdl_company_courses' doesn't exist SELECT DISTINCT cu.companyid AS id FROM mdl_company_users cu JOIN mdl_company_courses cc ON (cu.companyid = cc.companyid) WHERE cu.userid = ? AND cc.courseid = ? [array ( 0 => '334', 1 => '2', )])

line 293 of /lib/dml/moodle_read_slave_trait.php: call to moodle_database->query_end()
line 1398 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->query_end()
line 548 of /local/iomad_track/classes/observer.php: call to mysqli_native_moodle_database->get_records_sql()
**line ? of unknownfile: call to local_iomad_track\observer::user_enrolment_created()**
line 155 of /lib/classes/event/manager.php: call to call_user_func()
line 75 of /lib/classes/event/manager.php: call to core\event\manager::process_buffers()
line 801 of /lib/classes/event/base.php: call to core\event\manager::dispatch()
line 2153 of /lib/enrollib.php: call to core\event\base->trigger()
line 158 of /enrol/self/lib.php: call to enrol_plugin->enrol_user()
line 203 of /enrol/self/lib.php: call to enrol_self_plugin->enrol_self()
line 79 of /enrol/index.php: call to enrol_self_plugin->enrol_page_hook()

IN company::user_enrolment_created
[Skip to main content](https://company12.sandbox.domain.ca/enrol/index.php#maincontent)
You are enrolled in the course.
This page should automatically redirect. If nothing is happening please use the continue link below.
([Continue](https://company12.sandbox.domain.ca/course/view.php?id=2))

Error output, so disabling automatic redirect.
Script /enrol/index.php mutated the session after it was closed: $SESSION->notifications

    line 791 of /lib/classes/session/manager.php: call to debugging()
    line 162 of /lib/classes/shutdown_manager.php: call to core\session\manager::check_mutated_closed_session()
    line ? of unknownfile: call to core_shutdown_manager::shutdown_handler()

The user is still enrolled/unenrolled and appears to be working

**Comment by turf212** [comment]
*sigh* typo in the observer table.  Fixed and thank you.
