### ISSUE TITLE
403_STABLE:  errors viewing IOMAD certificate after a course is completed

### ISSUE THREAD

**Issue by dallenk** [iomad/iomad#1942]
PHP 8.0.30 (cli) (built: Sep 2 2023 08:05:13) ( NTS )
46b2929 (HEAD -> IOMAD_403_STABLE, tag: IOMAD_403_3, origin/IOMAD_403_STABLE) IOMAD: plugin name change on auth_iomadoidc for other lang packs

I see this viewing any certificate on an already completed course, and a newly completed course.

```
Exception - core_user::get_fullname(): Argument #1 ($user) must be of type stdClass, string given, called in [dirroot]/lib/moodlelib.php on line 3636
Debug info:
Error code: generalexceptionmessage
Stack trace:

    line 1296 of /lib/classes/user.php: TypeError thrown
    line 3636 of /lib/moodlelib.php: call to core_user::get_fullname()
    line 244 of /mod/iomadcertificate/locallib.php: call to fullname()
    line 180 of /mod/iomadcertificate/view.php: call to iomadcertificate_email_student()
```

**Comment by turf212** [comment]
Thanks for this.  It looks like this sets the $teacher variable to get_fullname(get_admin()) which it then called a get_fullname() on.  I've removed the first get_fullname for this which should fix this.
