### ISSUE TITLE
Language Menu not displaying the Language Selector

### ISSUE THREAD

**Issue by LeonidasFRA** [iomad/iomad#1943]
The language menu is not displaying the language selector since the 4.3 update.
![image](https://github.com/iomad/iomad/assets/143517087/a0a1bcfd-9046-4976-8a67-8d43cc55601d)

I've uninstalled the extra language packs, switched few options, purged all the caches yet it's not displaying the language selector, it's simply closing the window.

**Comment by turf212** [comment]
Looks like it's the company switcher causing it.

**Comment by turf212** [comment]
Yep - clash on the div IDs being used.  Will push a fix ASAP.
