### ISSUE TITLE
403_STABLE:  error searching for string in Site Administration

### ISSUE THREAD

**Issue by dallenk** [iomad/iomad#1944]
Searching for any string in the Site Administration" section shows these errors:

Warning: Undefined array key "" in /var/www/vhosts/sandbox.domain.ca/iomad/lib/adminlib.php on line 1967

Warning: Undefined array key "" in /var/www/vhosts/sandbox.domain.ca/iomad/lib/adminlib.php on line 1967

Warning: Undefined array key "" in /var/www/vhosts/sandbox.domain.ca/iomad/lib/adminlib.php on line 1967

**Comment by turf212** [comment]
this is being thrown when the value is an array but the array is empty.

**Comment by dallenk** [comment]
errors are gone now
