### ISSUE TITLE
403_STABLE:  "use IOMAD icons" seems partially broken in 403

### ISSUE THREAD

**Issue by dallenk** [iomad/iomad#1945]
it looks like the CSS is broken since the 402/403 upgrade for me.  tried clearing local browser cache, and Moodle caches, toggling the use icon settings.

402_STABLE
![image](https://github.com/iomad/iomad/assets/2725066/55b404fc-5f2f-40f7-abc0-b92bfc55b7ec)

403_STABLE
![image](https://github.com/iomad/iomad/assets/2725066/e298d473-6560-4a35-a42f-0a695aee3b44)

**Comment by turf212** [comment]
The action icon shouldn't be showing up when it's the icons.

**Comment by dallenk** [comment]
hrm..  no change on my end.. will try another clone and upgrade.

**Comment by turf212** [comment]
You will need to purge the Moodle cache to clear the cached templates.

**Comment by dallenk** [comment]
cleared moodle cache several times, and browser cache and tried a fresh VM client with the same result.   
edit:  enabling Theme Designer mode had no effect either.

**Comment by turf212** [comment]
So this is what I see in the demo site - test company with use icons set to no (default)

![image](https://github.com/iomad/iomad/assets/1685229/3f5ea0e4-2e9b-4d56-bc3f-d9f08db64bfe)

Change ti use icons = yes

![image](https://github.com/iomad/iomad/assets/1685229/ac6fbd72-fac5-401f-8661-97c089f69ee4)

Looks like it's in the block one though 

![image](https://github.com/iomad/iomad/assets/1685229/a742e0d6-c7c8-40b4-b12d-5f89811ad360)

Will sort now

**Comment by dallenk** [comment]
hrm. interesting.   I think I was focusing on the font change that the icon itself.
