### ISSUE TITLE
403_STABLE : License allocations showing lines of code and an error for the user

### ISSUE THREAD

**Issue by LeonidasFRA** [iomad/iomad#1947]
Hello, new issue, whenever I add or remove licenses I've got lines of code printed on the page : 
![Capture d'écran 2024-03-21 175654](https://github.com/iomad/iomad/assets/143517087/75c17466-f96a-4e65-b839-fd3dd02a9fa6)

It also happened on your demo platform.

Also the user I allocated the license ended up having an error when trying to connect (and I could not remove the license anymore) : 
![Capture d'écran 2024-03-21 180752](https://github.com/iomad/iomad/assets/143517087/2fadb289-ea8f-45ef-84d6-13056a26e1da)

**Comment by turf212** [comment]
Debug was already removed in commit 86c12ee6376ed869220e5fbaf7541a509d4b29d3 pushed on the 18th March.  Demo site hasn't been updated yet (though should have been)

As for the other error - can you please turn on debug and let me know what the full error code was?
