### ISSUE TITLE
403_STABLE : Error when deleting a user

### ISSUE THREAD

**Issue by LeonidasFRA** [iomad/iomad#1948]
Hello,

When I delete any user from the Users / Browse list of users tab i've got an error showing (it doesn't stop the delete process, but I wonder what is the impact) : 
![image](https://github.com/iomad/iomad/assets/143517087/ae0525d7-e3b2-4349-b141-076d724d8ac6)

**Comment by turf212** [comment]
The user get's deleted but the check to clear any licenses and other company cleardown isn't working due to this.  Will push a fix now.
