### ISSUE TITLE
When clicking on "Manage Company" in the Manage Organizations, the system doesn't automatically switch to selected org.

### ISSUE THREAD

**Issue by VFXpro** [iomad/iomad#1949]
When clicking "Manage company" from this page https://dev.learninghub.pro/blocks/iomad_company_admin/editcompanies.php

![image](https://github.com/iomad/iomad/assets/44643864/211aa80b-4648-40b2-b735-3179f47953bf)

- The user doesn't get redirected to the Multi-tenant dashboard with the correct company selected.
- The current company managed in the Multi-tenant dashboard doesn't get changed to the company clicked to be managed forcing the user to constantly search again, and the select. 

![image](https://github.com/iomad/iomad/assets/44643864/3ff59078-d97d-4053-b6ba-02bf00251a99)

**Comment by turf212** [comment]
The link from manage company page is using the blocks/iomad_company_admin/index.php URL and is passing the company ID as a parameter.  It's the same route as when you use the company department selector - which again goes to that page and passes the company id as a URL parameter.

If you hover over the manage button it will tell you the URL it's using.  If you put that directly into the browser - does it work?

**Comment by VFXpro** [comment]
As you suggested, I copied the URL and pasted directly into the browser (https://xxxxxxxxxxxxx/my?company=4450)
and it opens on the "**Dashboard**" page vs opening on the "**Multi-Tenant Dashboard**" page with the company selected. (expected behavior).

Please note, I do have the default home page settings set to "Dashboard" instead of "Home", perhaps there is something related to that?

Furthermore, when I click on the Multi-Tenant Dashboard, the URL doesn't show a company ID, maybe there is a clue in there...?

https://xxxxxxxxxxxxxx/blocks/iomad_company_admin/index.php
![image](https://github.com/iomad/iomad/assets/44643864/ed82d9a6-5acd-4932-9852-1656862f912c)

**Comment by VFXpro** [comment]
@turf212 You may close this issue.  This was caused by the IOMAD Company User Block not being added (was removed a long time ago) from the dashboard.
