### ISSUE TITLE
User's Grade appears as 0% within reports

### ISSUE THREAD

**Issue by BananaRama203** [iomad/iomad#195]
Originally I thought this issue was down to just uploaded course history however I recently received reports that it is happening to people who are completing courses within IOMAD.

These user's for example have achieved 100% in the Quiz and have a Course Grade 100%. Printed off a certificate within the IOMADcertificate module however viewing the user in reports give a grade of 0%.
(Can't confirm grade with the PDF certificate as the pdf is currently broken within reporting)

Learner who has been allocated within and completed within Iomad/moodle
![Error1](http://i.imgur.com/V0UqJua.png) 

Learner who has had course history uploaded and completed within Iomad/moodle
![Error2](http://i.imgur.com/F4aW2nC.png)

**Comment by BananaRama203** [comment]
Just to confirm the Course by Course CSV is also affected by this and is displaying as 0 however running:

select count(*) from mdl_grade_grades where itemid=X and finalgrade is null and userid not in (select userid from mdl_course_completions where course=X);

yields no results so it would appear all the information is on the database.

**Comment by turf212** [comment]
The Final scores being 0% is a data issue.  This should now be OK on your site.

**Comment by BananaRama203** [comment]
Will check and confirm

**Comment by BananaRama203** [comment]
Confirmed as Data issue.
