### ISSUE TITLE
IOMAD 4.1 - User Report fails to load if any search fields are used

### ISSUE THREAD

**Issue by VFXpro** [iomad/iomad#1953]
**Repro Steps**
1. Go to https://dev.learninghub.pro/local/report_users/index.php
2. Type anything in any search fields
3. Click Filters
4.  Results: Coding error detected, it must be fixed by a programmer: Url parameters values can not be arrays!

![image](https://github.com/iomad/iomad/assets/44643864/0a4f1c69-d22c-46a7-a01f-fb45f568723a)

![image](https://github.com/iomad/iomad/assets/44643864/8a614f30-e29f-4d50-9f34-e2b6ac4ccd8e)

Ben G

**Comment by turf212** [comment]
This is being caused by one of the optional profile fields you've added.  What type is it as it's not listed in the initial image you've attached?

**Comment by VFXpro** [comment]
You are correct. There are custom fields in the search.  All of them are text types except one that is the data. Is there a way for me to hide/remove certain fields from the report? Maybe that is the quick workaround?   Here are the fields.

![image](https://github.com/iomad/iomad/assets/44643864/b440595b-ab01-4df5-bbee-d37110310b36)

**Comment by VFXpro** [comment]
We discovered the root cause...  The custom date field is "automatically" enabled, thus causing the failed search and error message.  The date custom field above is NOT a required field, which makes it hard to explain why it would be enabled automatically.  If there is way to force date fields to default as disabled, that would be great so customers don't report this issue as a bug.   Perhaps, the latest version of IOMAD will not have this issue.

**Comment by turf212** [comment]
There were two search forms for some reason. The main one had any datetime field force set to disabled - the other must not have.

We've consolidated these into one form and pulled them into their own local/iomad/classes/form file (as well as changing what this form looks like) This was from commit fdf0e13cff0ad46d49f01c9579c5eec60139b821
