### ISSUE TITLE
IOMAD 4.1: self sign up form department feild does not map 

### ISSUE THREAD

**Issue by Marklaps** [iomad/iomad#1954]
Hi 

i have added a Department profile field in the option profile field for a company  (they have the same name as the department field)  but when i  self register it does not update the department field or add then to the correct department

i made sure i map the field in  Advanced Company Settings. 

it just ads them to the parent company and not the correct department 

Thanks

Mark

**Comment by turf212** [comment]
Can you confirm if you have the IOMAD signup settings configured and it is listening to the email (if that's the authentication type you are using for sign up) auth plugin? If it's not set up to listen to that then it won't try and match on the department field.

**Comment by Marklaps** [comment]
Thnaks cahcked that and can confirm that email is ticked in the   the authentication type you are using for sign up in the  IOMAD signup settings
![Screenshot 2024-04-29 173936](https://github.com/iomad/iomad/assets/40467458/90d5f5bd-a2eb-483a-89bb-634a308ff68c)

 it does not map to the departments from the dropdown  i have checked that i have mapped in the comapny settings as well

many thnaks

**Comment by turf212** [comment]
The issue here is if the user has already been assigned to a company by the time it hits this bit of code it wasn't doing anythign.  This was fixed in d66fcd76be06f39a9da007a6eae15cdefeb7cdce
