### ISSUE TITLE
IOMAD 4.1 - Small Typo

### ISSUE THREAD

**Issue by VFXpro** [iomad/iomad#1957]
When looking at a company's courses reports, there is a backslash at the end of the string.

![image](https://github.com/iomad/iomad/assets/44643864/a1de63fa-d128-4f1c-970d-f1210b3e45f7)

**Comment by turf212** [comment]
That looks to be something in the name of the company. It shoudl look like :

![image](https://github.com/iomad/iomad/assets/1685229/30ef5939-2747-4f02-af7c-d4a8362ee116)

Check the name in the database - it looks like you may have extraneous characters at the end of it.

**Comment by VFXpro** [comment]
I've tripled checked the company name, and there is no "backslash" in it, see image below... it looks like something is converting the single quote into a backslash perhaps, since the last single quote is not showing.

Page shown https://{moodleURL}/blocks/iomad_company_admin/company_courses_form.php

![image](https://github.com/iomad/iomad/assets/44643864/a10d61ef-d5e8-43c5-adcd-bbfb0239ec4d)

**Comment by turf212** [comment]
This was an issue with the local language customisation.
