### ISSUE TITLE
new user email company url link is broken

### ISSUE THREAD

**Issue by dallenk** [iomad/iomad#1960]
When creating a new user, the welcome email has the correct text, but the url is incorrect.

link text:  https://companyname.domain.ca/user/profile.php?id=421

url link:  https://www.domain.ca/local/email/%7BLinkURL%7D

**Comment by turf212** [comment]
There was some checking around if the site allowed theme changes in the URL.  If it didn't, it skipped out on changing the links.  Similarly the LinkURL wasn't working as expected.  These have been reworked in 95ec69130813aff9da19b19ac186574610a6ea40
