### ISSUE TITLE
When course deletion is executed by giving course deletion authority to the organization administrator, the confirmation screen lang is not displayed.

### ISSUE THREAD

**Issue by reso-nitta** [iomad/iomad#1961]
Environment
iomad:4.1.9
We changed settings so that CompanyManager can delete courses.
The following three Capability were set up for the CompanyManager.

```
View company courses
block/iomad_company_admin:viewcourses

Delete a non-shared company course
block/iomad_company_admin:deletecourses

Manage IOMAD course settings for all companies and courses
block/iomad_company_admin:manageallcourses
```

Log in as the organization administrator and perform the course deletion from the "Manage IOMAD course settings" screen.
A confirmation screen appears but no lang is displayed.

CompanyManager confirmation screen
![CompanyManager](https://github.com/iomad/iomad/assets/83208825/80c18404-eace-469a-adfa-df365bc412f1)

The site administrator's confirmation screen will show lang.
Administrator's confirmation screen
![admin](https://github.com/iomad/iomad/assets/83208825/603b28a5-5af8-493d-a90e-fbe4f5c0db15)

After checking, I believe the following source may be the cause.
```
iomad/blocks/iomad_company_admin/iomad_courses_form.php
Line 157.
$message = get_string('deleteacoursesfull', 'block_iomad_company_admin', $course->fullname);
```

The following lang file says 'deletecoursesfull'.
```
iomad/blocks/iomad_company_admin/lang/en/block_iomad_company_admin.php
Line 251.
$string['deletecoursesfull'] = 'Are you sure you want to delete course {$a}? Clicking continue will remove all current user enrolments, any license allocations and the course from the company. <b>There is no recovery from this without backup</b>';
```

**Comment by reso-nitta** [comment]
Is there any problem with the above modification method?

Are there any plans for future modifications?

**Comment by turf212** [comment]
Typos will be the death of me.
