### ISSUE TITLE
Recommended upgrade path from 3.x to 4.x

### ISSUE THREAD

**Issue by Fydon** [iomad/iomad#1966]
As [Moodle claims to require upgrading to 3.11.8](https://docs.moodle.org/404/en/Upgrading) before upgrading to 4.x and Iomad [doesn't have a 3.11](https://github.com/iomad/iomad/issues/1688), what is the recommended upgrade path from Iomad 3.x? Do we need to revert to Moodle 3.11 or is it safe to go from Iomad 3.x to 3.10 to Iomad 4.x?

**Comment by turf212** [comment]
You can upgrade from 3.9 to 4.1 as they are both LTS versions (or any > 3.9 to 4.1)
