### ISSUE TITLE
SAML2-SSO error on logout

### ISSUE THREAD

**Issue by tom5850** [iomad/iomad#1968]
When loggin out from a SSO-SAML2 account, we get the following error:

![image](https://github.com/iomad/iomad/assets/166646600/5d19b650-dff3-4732-b03a-15b2ae43c0ca)

Problem seems to be in auth/iomadsaml2/classes/auth.php, line 1155:

$auth = new \SimpleSAML\Auth\Simple($this->spname);

The idp seems to be identified by the hash value, not the spname. So, changing the code this way fixes the problem for us:

$auth = new \SimpleSAML\Auth\Simple($idp);

**Comment by turf212** [comment]
Thanks for this.  Looks to be a bug in the underlying plugin.  They are setting $idp to be $this->spname a few lines earlier, just before checking if the $SESSION one already exists and setting $idp to that instead.  So your fix makes more sense than what they have hard coded it to be.
