### ISSUE TITLE
403_stable:  error enroling user to a course

### ISSUE THREAD

**Issue by sibjac** [iomad/iomad#1970]
I am getting below error when enrolling a user to course
![error enrolling user to course-roleid](https://github.com/iomad/iomad/assets/37014257/7422df92-b08d-41e7-bccb-8bbc58217e57)
this is a new installation, eariler was using 402 without any issues

**Comment by turf212** [comment]
Does the Manual enrolment class exist on the course?

**Comment by huy-nm** [comment]
I got the same issue with all three types of course
![image](https://github.com/iomad/iomad/assets/68839382/5554a5ce-4b2b-402b-9428-12a002785858)

**Comment by turf212** [comment]
If you go to the course and click on Participants and then choose enrolment methods from the drop down, are there any listed for the course?

**Comment by huy-nm** [comment]
> If you go to the course and click on Participants and then choose enrolment methods from the drop down, are there any listed for the course?

Dropdown is disabled (for all 3 types of course)
![image](https://github.com/iomad/iomad/assets/68839382/b149ecb9-1e54-4ec1-bbc4-8dc944628dae)

**Comment by turf212** [comment]
That's frustrating.  Looks like Moodle core has removed the enrolment methods when you create a course. Or at least when creating a course in 4.3 it's not adding them in from the IOMAD dashboard.

If you add a Manual or License enrolment method to the course it will work for now. I'll check why it's failing in the code. and fix ASAP.

**Comment by turf212** [comment]
More curiously, if I create the course directly in the Site admin -> Courses -> create course that still doesn't have any enrolment plugins set up.  I've tested this on the latest 4.3 code from today and that is showing this behaviour.

**Comment by turf212** [comment]
So the issue is that the default setting for manual,guest,license, and self enrolments to be added by default to a new course hasn't been saved in the database, even though it looks like it has when you check the settings for that plugin.  You can fix it for new courses by going to Site administration -> plugins -> enrolments and editing the settings for each of those plugins - first unticking the option saving, and then ticking the option and then saving again.

For courses you have created you can manually add in those enrolment types to each course from the enrolments option from the drop down.

This is only happening on new 4.3 sites, so I'm going to check a core Moodle 4.3 site and see if that issue is still there. If so I'll raise a bug with the Moodle devs, if not I'll work out why it's happening with our code and sort.

**Comment by shadyshrif** [comment]
> So the issue is that the default setting for manual,guest,license, and self enrolments to be added by default to a new course hasn't been saved in the database, even though it looks like it has when you check the settings for that plugin. You can fix it for new courses by going to Site administration -> plugins -> enrolments and editing the settings for each of those plugins - first unticking the option saving, and then ticking the option and then saving again.
> 
> For courses you have created you can manually add in those enrolment types to each course from the enrolments option from the drop down.
> 
> This is only happening on new 4.3 sites, so I'm going to check a core Moodle 4.3 site and see if that issue is still there. If so I'll raise a bug with the Moodle devs, if not I'll work out why it's happening with our code and sort.

Thank you this worked for me, both solutions worked for me.
I would like to help with exploring the root cause of the issue, I will install a fresh core Moodle 4.3 site and let you know

**Comment by shadyshrif** [comment]
Hi @turf212 I tried a fresh version of Version 4.3.1 (Build: 20231211)
Simply I created a user, and a course, and then I enrolled the user to the course. it worked without any issue. So this seems to be iomad issue not core Moodle issue.
I have this fresh install, tell me if you want me to check anything in the DB, I'm happy to help

**Comment by turf212** [comment]
Found the underlying issue for this. If you open the enrolment plugin settings and save them (for manual, guest, and self) it will save the default settings - including whether it should be added to a course on creation - which is what is missing in the database.
