### ISSUE TITLE
SAML2-SSO using autocreate is not tenant aware

### ISSUE THREAD

**Issue by tom5850** [iomad/iomad#1978]
Using SAML2-SSO with activated autocreate, creates a new user always without tenant information.

That's because in iomadsaml2/classes/auth.php, line 748 the moodle core function is called, which is not aware of tenants:

$user->id = \user_create_user($user, true, true);

I suggest to replace this line with:
$companyid = iomad::get_my_companyid(context_system::instance(), false);
$user->companyid = $companyid;
$user->id = \company_user::create($user);

**Comment by turf212** [comment]
There is already functionality in the local/iomad_signup plugin which listens for the user created event and will capture this and then handle the user assignation.  You do need to enable that plugin to listen to the auth modules and it wasn't doing the same code check as you suggest (which will handle from custom URLs so should be in there).

Using this gives more flexibility as you can add in more auth types and you can add them to the list of things being checked.

**Comment by tom5850** [comment]
Thank you @turf212 .
