### ISSUE TITLE
Unassign courses does not unenroll users if "OK to unenroll" is selected

### ISSUE THREAD

**Issue by tom5850** [iomad/iomad#1981]
We have removed some course assignments from a company. In doing so, we activated the "OK to unenroll" switch, but noticed that the enrolled users were not unenrolled, even though the course assignments have now been removed.
Did we miss something?

**Comment by turf212** [comment]
The functions to remove and delete courses in the company have been added/updated since this page was last touched.  I'll refactor this as there are a few things which don't seem quite right.

**Comment by turf212** [comment]
Closing this as referenced issue is now fixed in 4.3 and 4.4
