### ISSUE TITLE
email template missing - course completion to managers

### ISSUE THREAD

**Issue by dallenk** [iomad/iomad#1982]
Hate to keep bumping this one, but I think it got lost down the list maybe..

https://github.com/iomad/iomad/issues/1914

Is there anything I can do to help or provide to get this one fixed?   i don't even mind paying for some coding time as it's a really important one for the instructors for us.

**Comment by dallenk** [comment]
Bump???

**Comment by dallenk** [comment]
@turf212 are you still developing this project?

**Comment by turf212** [comment]
all of the processing for the email reports was spilt out into their own separate tasks but this was back in 2022 - so unsure where it actually stopped working.

In any case - I've reworked that task to a new task and created 2 new tasks and digest emails for course completions in the last week and training expiring in the coming week. The email templates for these last two have been added as disabled to existing systems, so you will need to switch them on if you want them in the tenant (I did this to prevent emails going out on upgrade that you didn't know about and then all of your tenant complaining that they were getting them!).  Same for any template sets you may have saved - they are added disabled.

You can either do this by tenant in the GUI or in the database for everyone.  

```
update mdl_email_template set disabled=0 where name='expiring_digest_manager';
update mdl_email_template set disabled=0 where name='warning_digest_manager';

```
(can also add and companyid = or in (1,2,3,) )

and 

```
update mdl_email_templateset_templates set disabled=0 where name='expiring_digest_manager';
update mdl_email_templateset_templates set disabled=0 where name='warning_digest_manager';

```

This has been pushed to 4.1, 4.2 and 4.3 branches.

**Comment by turf212** [comment]
I've left #2048 open in case there are issues :)
