### ISSUE TITLE
How to define different outgoing email configuration settings for different tenant?

### ISSUE THREAD

**Issue by sarathp06** [iomad/iomad#1984]
As per IOMAD 4.2 release notes, Added per tenant SMTP settings: This allows the site administrator to define different outgoing email configuration settings for different tenants while retaining the default site settings for everyone else.

I went to Site administration-> Server -> Outgoing mail configuration, and I can see the Company SMTP hosts where we can add one or more local SMTP servers with a colon as a separator (mail.a.com;mail.b.com), however, how can I add respective username and password for each Company SMTP hosts?

In addition to that where should I mention that a specific SMTP host should be used for a particular tenant?

My current IOMAD version is 4.3.4 (Build: 20240422)

**Comment by BlockAIx** [comment]
The UI isn't that clear about it but, when you see "company" fields, it means the company you selected in the dropdown. So in order to add a company specific configuration, just select your company, go into server -> outgoing mail and then configure the "company" fields.
