### ISSUE TITLE
IOMAD 4.3 Default settings (Themes)

### ISSUE THREAD

**Issue by mczaja** [iomad/iomad#1985]
In IOMAD 4.3 default theme settings don't work until you click Save. (After theme installation, only the first time).

I noticed that in **lib/adminlib.php in line 1964** has been added a code (not present in previous versions)

<img width="1870" alt="adminlib" src="https://github.com/iomad/iomad/assets/29889738/b7d9c808-07ad-40d9-8867-0c6b372e0596">

**Comment by turf212** [comment]
There were a number of issues with the system creating a cached set of default values for plugins which was causing it to then not get saved to the database.  This was eventually addressed in fb9f292b233d6fd012a65c6abcbb1301c7fcc93e for both 4.2 and 4.3.
