### ISSUE TITLE
Company code / short name with special characters causing issues

### ISSUE THREAD

**Issue by shadyshrif** [iomad/iomad#1986]
I added a company with code and short name that contains the & character for example B&Q and added users to this company.
This caused an issue when any user belongs to this company logs out, then is forwarded back the the login page: /login/index.php?id=1&code=B&Q

which causes an error:

Debug info:
Error code: [[unknown_company]]
$a contents:×Dismiss this notification
Stack trace:
line 68 of /login/index.php: moodle_exception thrown

The simple solution was to change the company's short name and code to BQ rather than B&Q

I believe a check has to be made on the IOMAD company_edit_form.php to restrict the special characters causing this issue

**Comment by turf212** [comment]
You are correct - this has been addressed in 8f9d51f8502ea5e9348d03cc60c4c891eafbbb2d
