### ISSUE TITLE
Cannot view users using Company Manager

### ISSUE THREAD

**Issue by huy-nm** [iomad/iomad#1987]
I create a user with Company Manager role. Then I add permission/capability to viewdetails, so I can click on user name to edit their profile.
- When I add viewdetails permission, it won't work.
- But when I add this user to Company Manager role in Site Admin [Assign system roles], it works.

Does anyone know how to fix this issue?

**Comment by turf212** [comment]
The company manager shouldn't be using the Moodle capabilities to edit their users roles.  There is an edit option in the Edit user's page which will allow them to edit the user's profile within the IOMAD boundaries.  They will need to turn editing on on that page to see it in the drop down.

What you have done is allow that company manager the capabilities of editing any user on the site - regardless of if they are in the same company or not.
