### ISSUE TITLE
Error reading from database: dmlreadexception

### ISSUE THREAD

**Issue by Fujimaru-Kun** [iomad/iomad#1988]
I have successfully installed IOMAD 4.3.  The test user can log in and only the admin user cannot. 

Debug info: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 3
SELECT id FROM mdl_company_users
WHERE userid = ?
and companyid IN ()
[array (
0 => '2',
)]
Error code: dmlreadexception×Dismiss this notification
Stack trace:
line 494 of /lib/dml/moodle_database.php: dml_read_exception thrown
line 293 of /lib/dml/moodle_read_slave_trait.php: call to moodle_database->query_end()
line 1398 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->query_end()
line 3592 of /local/iomad/lib/company.php: call to mysqli_native_moodle_database->get_records_sql()
line 269 of /login/index.php: call

**Comment by Fujimaru-Kun** [comment]
Hi,

Is there any update sorry but we badly needed a resolution about this issue.

**Comment by huy-nm** [comment]
You should use MySQL instead. Looks like the query in IOMAD use MySQL, so it may not work for MariaDB.

**Comment by dallenk** [comment]
I'm currently running 4.3 with MariaDB in a test environment

Server version: 10.6.16-MariaDB-0ubuntu0.22.04.1 Ubuntu 22.04
b67647c3209 (HEAD -> IOMAD_403_STABLE, origin/IOMAD_403_STABLE) IOMAD: IOMAD link block throws error is no company id returned

edit:  Looks like this is a new bug


interesting.. if I log in as the site admin user a the root url I have no error.
eg:   sandbox.domain.com  - no error

If I use a subdomain and log in as the site admin, then I see the error.
sub1.sandbox.domain.com  - Fails

**Comment by dallenk** [comment]
additional:

logging in as a user into a different sub domain, or to the root url of IOMAD produces the same errors:
**user1: member of sub1.sandbox.domain.com**
NO error logging into sub1.sandbox.domain.com

**attempting login to sandbox.domain.com**
```
Error reading from database

Debug info: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 3
SELECT id FROM mdl_company_users
WHERE userid = ?
and companyid IN ()
[array (
0 => '59',
)]
Error code: dmlreadexception×Dismiss this notification
Stack trace:
line 494 of /lib/dml/moodle_database.php: dml_read_exception thrown
line 293 of /lib/dml/moodle_read_slave_trait.php: call to moodle_database->query_end()
line 1398 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->query_end()
line 3597 of /local/iomad/lib/company.php: call to mysqli_native_moodle_database->get_records_sql()
line 269 of /login/index.php: call to company::check_valid_user()
```

**Comment by misog** [comment]
@turf212 Hi, this bug is critical because login functionality does not work even for admin users when using MariaDB (supported by IOMAD).

This bug is present if `$CFG->dbtype    = 'mariadb';` is present in config.php and MariaDB is used as the DB.

**Comment by misog** [comment]
Here are the problem lines, in `local/iomad/lib/company.php`

https://github.com/iomad/iomad/blob/22a5385f241ea1bf688c669c2d150241f152f8af/local/iomad/lib/company.php#L3590-L3602

When `$children` is empty array then it will cause the error because `and companyid IN ()` is not valid SQL syntax.

Here is fixed code:

```php
        } else {
            // is the user in a child company?
            $company = new company($companyid);
            $children = $company->get_child_companies_recursive();
            if (empty($children)) {
                return false;
            }
            if ($DB->get_records_sql("SELECT id FROM {company_users}
                                      WHERE userid = :userid
                                      and companyid IN (" . join(',', array_keys($children)) . ")",
                                      ['userid' => $userid])) {
                return true;
            } else {
                return false;
            }
        }
```
