### ISSUE TITLE
Handle possible invalid SQL "IN ()" query occurences

### ISSUE THREAD

**Issue by misog** [iomad/iomad#1990]
Hi, here is a bug where invalid `IN ()` query is constructed which leads to error https://github.com/iomad/iomad/issues/1988#issuecomment-2149257183

In IOMAD there are more than 20 places in code where "IN" query is constructed manually, in some there is check for empty array and in others there is not any check for empty array.
https://github.com/iomad/iomad/blob/22a5385f241ea1bf688c669c2d150241f152f8af/auth/mnet/auth.php#L385-L393
https://github.com/iomad/iomad/blob/22a5385f241ea1bf688c669c2d150241f152f8af/local/report_completion/index.php#L672-L678

Maybe this should be handled with SQL binding or with some string helper function.

**Comment by turf212** [comment]
Agree - thanks for reporting.
