### ISSUE TITLE
Company Manager can't edit the course

### ISSUE THREAD

**Issue by abdullahqu1** [iomad/iomad#1994]
I just installed the latest IOMAD and created a company and company manager. Now I want company manager to create new courses and able to update it and add new topics etc.

I can see on IOMAD demo site, company manager is able to do that. But I am not able to do this with IOMAD latest install. I did grant block/iomad_company_admin:createcourse permission to Company Manager but manager can only create a course and not able to edit it or assign himself to course.

Please help

**Comment by abdullahqu1** [comment]
And I am not even able to enroll users to courses from company manager account as I am able to do on demo site

**Comment by hamza-fc** [comment]
I faced the same issue with the latest version of IOMAD [4.3.3] where company manger was unable to create/update courses by default.

I downgraded and installed the last release **[IOMAD 4.2.6]** and it worked fine there - Looks like there has been some issue in the latest version.
- In the "Company Manager" role, allowed the permission for "block/iomad_company_admin:createcourse"
- Login as Company Manager
- In IOMAD Dashboard, under courses, create course
- Goto Course, turn on Edit mode, and now able to add activity/resource
- Now able to create and update the course

**Comment by jasonJamEther** [comment]
I hate to downgrade. Are there any other solutions to fix this? I see the `block/iomad_company_admin:createcourse` option is not even available under company manager anymore. I even just pulled the latest 4.3.7 and the issue still persists. I just need someone at the company level to be able to create courses. Currently it appears that only the entire iomad admin can do it.

**Comment by turf212** [comment]
That capability isn't given by default to company managers. You can add it to the company manager role at the site level by editing the role in Site administration -> Users -> Permissions -> Define roles.  This will then allow them to create courses.

Some other ones which you may also want to add for this in 4.3 are:

block/iomad_company_admin:viewcourses - Will give them access to the Manage IOMAD courses page
block/iomad_company_admin:managecourses - Will allow them to access the actions column on that page (with editing turned on)
block/iomad_company_admin:deletecourses - Will allow them to delete a course they have created
block/iomad_company_admin:hideshowcourses - Will allow them to make courses which they have created hidden or visible to their users

There is new functionality in 4.3 as of 30afcba9d21a9e25c8c58bf78eea3e9eeaca25e4 which will also allow Company managers who have the block/iomad_company_manager:createcourse capability the option to clone a course that they have created.  There is also the ability for an Admin to give control of a course to the Company managers so they can edit them and manage them with these settings. You can also take this away from the company too.

Any role you have given site wide can then be taken away at an individual company level by using the restrict roles options.
