### ISSUE TITLE
/local/report_users/userdisplay.php error

### ISSUE THREAD

**Issue by BananaRama203** [iomad/iomad#200]
When clicking on a user within the license user report this is generated as the link

/local/report_users/userdisplay.php?userid=2455994&courseid=1

Which is wrong as the userID for this user is 55994 not 2455994.

Even correcting the userID returns no worthwhile information.

I assume 24 is mean to be dptID or LicenseID

**Comment by turf212** [comment]
Same issue as for completion report.  sorted.
