### ISSUE TITLE
Error on a fresh installation

### ISSUE THREAD

**Issue by robertillyes** [iomad/iomad#2000]
Encountered this error while updating IOMAD_403_STABLE (SHA 5d4e0dea114860ba8e1109402674f161d7e183f6 commit)

I refreshed the page when it gave me the first error (image 1.), it seemed to work, all the plugins were installed, but then I couldn't continue (image 2).

I traced it back to iomad/admin/settings/plugins.php line 31 where it also set -1 for the postfix (image 3.). If I added the check for -1 - flag for the fresh installation (see image 4) - then everything worked. Could continue the installation without any issues.   

![Screenshot 2024-06-13 at 10 59 04](https://github.com/iomad/iomad/assets/148238166/62715fdc-fb0a-4676-8ad7-ec5cf2a0cd71)
![Screenshot 2024-06-13 at 11 36 24](https://github.com/iomad/iomad/assets/148238166/5346f69e-caed-46c0-8365-9f64f8f053b7)
<img width="1136" alt="Screenshot 2024-06-13 at 11 36 49" src="https://github.com/iomad/iomad/assets/148238166/e2b116b2-a1f8-4fbc-866d-45c934ec097e">
<img width="1136" alt="Screenshot 2024-06-13 at 11 37 06" src="https://github.com/iomad/iomad/assets/148238166/de06e359-199c-4a13-9650-9b35f94aff51">

**Comment by turf212** [comment]
#2004 is a duplicate.  The code to get the current users company ID was returning -1 if there wasn't one.  Fixed under 5b0701d97bc493df143f412717d83ed7d374313e on 21st June.
