### ISSUE TITLE
Competencies Error

### ISSUE THREAD

**Issue by VeNoMZiTo** [iomad/iomad#2002]
We have several errors in the competencies module of IOMAD. Before modifying anything in the code, we prefer to share it here to see if it is a general error.

![captura2](https://github.com/iomad/iomad/assets/1822968/123b53ab-d50a-4c9b-bdbf-fe0e479affd5)
![captura1](https://github.com/iomad/iomad/assets/1822968/bf829306-00f2-4c07-a6b3-f73b31993e75)

**Comment by turf212** [comment]
These were addressed under commit d928c5ac929d4874b97dcb8116c606baa198062a
