### ISSUE TITLE
IOMAD 4.3 - Selecting a child company returns the incorrect data when looking at user reports

### ISSUE THREAD

**Issue by VFXpro** [iomad/iomad#2003]
Hi Derick,

Repro Steps
1. Select a child company.
2. Click on Users/User Report
3. Reports shows incorrect company and data.

Ben G.

![image](https://github.com/iomad/iomad/assets/44643864/23b8e0d3-e814-4c3a-90ce-62f7709342fb)

![image](https://github.com/iomad/iomad/assets/44643864/913759f5-7a80-4701-9de6-886a09da96c6)

The org hiearchy is showing as correct
![image](https://github.com/iomad/iomad/assets/44643864/ce466a14-8c51-4c20-841b-51eb41886e32)

**Comment by turf212** [comment]
Seems to be working as expected after re-work done as part of #1828
