### ISSUE TITLE
E-Mail template prefilled "Manual from name" looks like Phishing

### ISSUE THREAD

**Issue by tom5850** [iomad/iomad#2005]
Hi Derick

In all email templates, the "Manual from name" field is filled with {Company_Name} by default. While this may be useful if the {Company_Name} matches the sender domain, it looks like a phishing email if it does not (which is probably the case for most IOMAD users).
For example, if the company name is "Microsoft" and the sending domain is iomad.org, then users would receive an email from "Microsoft <iomad.org>". We teach our users how to spot phishing emails, and a mismatch of domain and name is an important indicator.
Yes, we can remove {Company_Name} from this field. But if you edit the mail, it will be pre-filled again. There is a very high risk that if a company manager edits the email, they will overlook this field and have a phishy sender name again.
Since more and more people are aware of such phishing indicators, I suggest to remove lines 92-94 in local/email/template_edit_form.php

if (empty($templaterecord->emailfromthename)) {
    $templaterecord->emailfromothername = '{company_name}';
}

Happy to discuss.

**Comment by turf212** [comment]
Fair point.  Updated all the recent branches.
