### ISSUE TITLE
Enrolling via blanket license sends welcome email even when those are disabled.

### ISSUE THREAD

**Issue by leshlush** [iomad/iomad#2006]
If a user enrolls in a course by using a blanket license, that user will receive a welcome email from Moodle, even if the welcome emails are disabled.

Course welcome emails are sent via Moodle core (not Iomad) and do not show up in the outgoing emails report. They are disbabled via "Site Administration -> Plugins -> Self-Enrollment -> Welcome email"

Under normal self-enrollment circumstances (not using a blanket license, but standard Moodle self-enrollment), these welcome emails are not sent if disabled via the site administration settings.

EDIT:

Hunting around in the language packs, I see the language string "enrol_license" is identical to "enrol_self". It's possible that this is email is actually coming from Iomad, but that the email isn't listed under the Iomad Email Templates (it is a different email than user_enrolled_on_course). If that is the case, that template should be configurable using a company's email templates.

**Comment by mikeaveli007** [comment]
Looks like there is a setting for it in a similar place as the Self-Enrollment plugin.  Plugins -> Enrollment -> License Enrollment -> Send course welcome message.

**Comment by turf212** [comment]
As mentioned the license enrolment also has the option to create a course welcome message as it was built from the self enrolment plugin and by passes the IOMAD emails.  You can enable or disable per course should you want.
