### ISSUE TITLE
CI / CD for iomad plugin

### ISSUE THREAD

**Issue by khairu-aqsara** [iomad/iomad#2008]
Mostly we will use Moodle plugin with iomad, but sometimes we need to build our own plugin that use specific feature from iomad, when using Moodle CI/CD it's not gonna work since Moodle doesn't have company related table and other table specific to iomad.

My question is, is there any IOMAD CI/CD that we can use to run unit test, code quality or similar to it? Since Moodle has their own Moodle plugin CI tools to check the quality standard of the plugin.

**Comment by turf212** [comment]
We don't have anything however as IOMAD is Moodle with the IOMAD plugins and follows the Moodle coding standards - you can just use the Moodle ones.
