### ISSUE TITLE
IOMAD 4.3 Company managers cannot modify users.

### ISSUE THREAD

**Issue by ericfalcon** [iomad/iomad#2009]
While in edit mode, company managers get this error when they go to edit users

Exception: array_key_exists(): argument #2 ($array) must be of type array, given null

More information about this error

Debug info
Error code: generalexceptionmessage×Dismiss this notification
Stack trace
line 114 of /blocks/iomad_company_admin/classes/output/user_departments_editable.php: TypeError thrown
line 114 of /blocks/iomad_company_admin/classes/output/user_departments_editable.php: call to array_key_exists()
line 115 of /blocks/iomad_company_admin/classes/tables/editusers_table.php: call to block_iomad_company_admin\output\user_departments_editable->export_for_template()
line 861 of /lib/tablelib.php: call to block_iomad_company_admin\tables\editusers_table->col_department()
line 2085 of /lib/tablelib.php: call to flexible_table->format_row()
line 2208 of /lib/tablelib.php: call to table_sql->build_table()
line 669 of /blocks/iomad_company_admin/editusers.php: call to table_sql->out()

**Comment by chris-lav** [comment]
+1 We are also experiencing this issue on our site too.

**Comment by NorbertasL** [comment]
+1 Facing the same issue. It seems to work if we assign the same role via Moodle Admin Panel (at a system levels)

**Comment by tom5850** [comment]
+1 We are facing the same issue (IOMAD 4.3.8).

**Comment by khelmalin** [comment]
I found that the code inside this file incorrect typo: `blocks/iomad_company_admin/classes/forms/user_edit_form.php` line 67

Before:
`        if (\iomad::has_capability('block/iomad_company_admin:edit_all_departments', $this->companycontext)) {
            $userhierarchylevel = $parentlevel->id;
            $userlevels = array($parentlevel->id => $parentlevel->id);
        } else {
            $userlevels = $company->get_userlevel($USER);
            $userhierarchylevel = key($userlevel);
        }
`
After:

`        if (\iomad::has_capability('block/iomad_company_admin:edit_all_departments', $this->companycontext)) {
            $userhierarchylevel = $parentlevel->id;
            $userlevels = array($parentlevel->id => $parentlevel->id);
        } else {
            $userlevels = $company->get_userlevel($USER);
            $userhierarchylevel = key($userlevels);
        }
`

Hope that could help. thank you.
