### ISSUE TITLE
Manage IOMAD Framework/Template Settings - Pages don't load

### ISSUE THREAD

**Issue by nictau** [iomad/iomad#2011]
Running the latest IOMAD_403_STABLE, attempting to open either:

IOMAD Dashboard > Competencies tab:
- Manage IOMAD Framework Settings
- Manage IOMAD Template Settings

Results in an error:

Exception - Object of class company could not be converted to string

Stack trace:

    line 1289 of /lib/outputcomponents.php: Error thrown
    line 2323 of /lib/outputrenderers.php: call to single_select->export_for_template()
    line 245 of /lib/outputrenderers.php: call to core_renderer->render_single_select()
    line 157 of /blocks/iomad_company_admin/iomad_frameworks_form.php: call to renderer_base->render()

I believe this originates from commit https://github.com/iomad/iomad/commit/13f5c430172cbc10691b843617aded16571f8a16
in file [blocks/iomad_company_admin/iomad_frameworks_form.php](https://github.com/iomad/iomad/blob/c813d4f53cc54fc53fb680a1f4e97d327a6f9635/blocks/iomad_company_admin/iomad_frameworks_form.php#L157) (for the first example)

Where https://github.com/iomad/iomad/blob/c813d4f53cc54fc53fb680a1f4e97d327a6f9635/blocks/iomad_company_admin/iomad_frameworks_form.php#L73 is now making $company an instance of company instead of just the company id

This breaks down during rendering of the company select box here https://github.com/iomad/iomad/blob/c813d4f53cc54fc53fb680a1f4e97d327a6f9635/blocks/iomad_company_admin/iomad_frameworks_form.php#L150-L157 as the object is being passed in to `single_select` and subsequently cannot be converted to a string

Further, it appears this may break the functionality of this conditional here:
https://github.com/iomad/iomad/blob/c813d4f53cc54fc53fb680a1f4e97d327a6f9635/blocks/iomad_company_admin/iomad_frameworks_form.php#L90-L95

**Comment by turf212** [comment]
This was fixed in d928c5ac929d4874b97dcb8116c606baa198062a on the 25th July
