### ISSUE TITLE
When reassigning courses, unwanted "Company Manager" role change occurs

### ISSUE THREAD

**Issue by jalapatas** [iomad/iomad#2012]
In the Company Dashboard, when assigning a first batch of courses, a new Company Manager role is added: "Client Course Access", and when assigning a second batch of courses, the role assigned to the Company Manager changes to "Client Course Editor".
This is a potential security breach because the "Client course Editor" role gives access to ALL tenants data (users, company names, etc.) on the entire platform, and not just for the current tenant.

**Comment by turf212** [comment]
Cannot replicate in latest code.
