### ISSUE TITLE
4.3_stable - error downloadcerts

### ISSUE THREAD

**Issue by sibjac** [iomad/iomad#2013]
This is a new installation, and  mycourses page shows download certificates link, when clicked on it, it gets a 401 error
"local/report_completion/index.php?certusers=4&action=downloadcerts&sesskey=c1VCt5SEM6 might be having issues, or it may have moved permanently to a new web address."

![31 07 2024_08 50 04_REC](https://github.com/user-attachments/assets/6009b1cf-d8ae-49d8-a43b-8fef2600f6d5)

is there any workaround for this?

**Comment by turf212** [comment]
401 errors are due to the access not being authorized by the web server.  I suspect you have put the site under account access and when it's calling to it's own URLs it won't be passing a username/password so throws that error.
