### ISSUE TITLE
The recent company pulldown menu in the header has drastic negative performance impact, need a setting to turn it off.

### ISSUE THREAD

**Issue by VFXpro** [iomad/iomad#2015]
Hi Derick,

When we upgrade to the latest IOMAD, we were suffering of a massive slowdown (5 sec load) on every page where the new company pulldown was showing since we have thousands of parent/child companies.  We tried to use a theme to turn it off, but the code lives inside of a library, thus cannot be overridden. Thus, we had to modify the core code to turn it off which is not best practice for sure. 

**Request**
Can you please add a toggle switch in the IOMAD settings to allow this feature to be turned off?

Thanks,
Ben

**Comment by turf212** [comment]
added in commit 5acec5cdef88ee30b2dbb5bc4519539ec66edc3d
