### ISSUE TITLE
4.3 critical security issue

### ISSUE THREAD

**Issue by sibjac** [iomad/iomad#2018]
has any one of you come across this?  tried with two different versions of 4.3 stable, both face the same issue, also most of the folders can still be browsed even if a webpage opens which gives an error with a continue button, when you click on it, it dies letting us to browse those folders too.  Folders inside tools are also same, anybody without a login can browse them.  
/admin/tool/log/ (all folders in this can also be browsed)
/admin/tool/lp/ (all folders in this also)
/admin/tool/task/(all folders in this also)
 These are a few of the examples, have not checked other folder trees .  Though it can be rectified in the apache config, I think it is still a critical security issue.
 ![iomad](https://github.com/user-attachments/assets/f5d08c57-cc05-4296-8aae-5f23e7cc50a2)

**Comment by encodecreate** [comment]
Just checked this on our installation and can confirm the existence of this error. Tried with multiple user accounts/roles.

**Comment by encodecreate** [comment]
Have you tested this on Moodle to see if it's a Moodle issue, or specific to Iomad? I can try to find some time to spin up a moodle box, if not.

**Comment by turf212** [comment]
This is controlled by your webserver settings as will also happen with Moodle.  Plenty articles to describe this on Google - e.g. for Apache https://stackoverflow.com/questions/2530372/how-do-i-disable-directory-browsing
