### ISSUE TITLE
API function: block_iomad_company_admin_enrol_users - dml_write_exception

### ISSUE THREAD

**Issue by EdwinEspi18** [iomad/iomad#2024]
I am using the External APIs to enroll them into courses. I am using the following functions in the order shown:

block_iomad_company_admin_enrol_users
The first two work perfectly, but the third is giving an error. Based on the documentation "block_iomad_company_admin_enrol_users" accepts the following data:

roleid int //Role to assign to the user
userid int //The user that is going to be enrolled
courseid int //The course to enrol the user role in
timestart int Optional //Timestamp when the enrolment start
timeend int Optional //Timestamp when the enrolment end
suspend int Optional //set to 1 to suspend the enrolment
quantity int Optional //Number of items purchased
The error being returned is:
{
  exception: 'dml_write_exception',
  errorcode: 'dmlwriteexception',
  message: 'Error escribiendo a la base de datos',
  debuginfo: "Column 'validlength' cannot be null\n" +
    'INSERT INTO mdl_companylicense (name,allocation,validlength,startdate,expirydate,companyid,instant) VALUES(?,?,?,?,?,?,?)\n' +
    '[array (\n' +
    "  0 => '4-14-1724804004',\n" +
    '  1 => 1,\n' +
    '  2 => NULL,\n' +
    '  3 => 1724804004,\n' +
    '  4 => 1756340004,\n' +
    "  5 => '1',\n" +
    '  6 => 1,\n' +
    ')]'
}

**Comment by turf212** [comment]
It's not using a standard enrolment but creating a license for the user but you haven't set the default license parameters in the block iomad_ecommerce plugin. If you go to Site administration -> plugins -> blocks -> IOMAD eCommerce and scroll down and set the default license access length and the default license shelf life.

I've updated the code to use a default of 30 where this isn't set but best practice to change it there.
Commits c82c203da8b3cd6d475207f5a254c7f28acc4d95 3e5dfaccd41874d7e2faf78f223423baa346ac97 and 9ddd23706f31dc34ceeab38bedfc7a78f72148a6 in the 4.1/2/3 branches
