### ISSUE TITLE
Seems like IOMAD is not compatible with PostgreSQL?

### ISSUE THREAD

**Issue by keithkhl** [iomad/iomad#2026]
Right after the first installation, I couldn't see any pages but admin ones. I then turned on debug, and could see following.

`Debug info: ERROR: function if(boolean, character varying, text) does not exist
LINE 1: SELECT id, IF (suspended=0, name, concat(name, ' (S)')) AS n...
^
HINT: No function matches the given name and argument types. You might need to add explicit type casts.
SELECT id, IF (suspended=0, name, concat(name, ' (S)')) AS name FROM mdl_company
WHERE 1 = 1
AND parentid = $1 AND suspended = $2
ORDER BY name
[array (
0 => 0,
1 => 0,
)]
Error code: dmlreadexception`

I believe 'IF' is not supported to PostgreSQL, but IOMAD somehow uses MySQL/MariaDB commands to Postgre.
I strictly disprefer to rely on MySQL (or MariaDB), and wonder if you guys have any urgent fix for this.

I could see that it was reported a few months ago, and kinda surprising that this much of dire bug has not been fixed.
Just in case, I fetched git version for fresh installation.

Plz let me (and all PostgreSQL users) know if there is no urgent roadmap for this fix. Then, I think I should compromise with multiple Moodle installations, instead of jumping to MySQL / MariaDB.

**Comment by keithkhl** [comment]
https://github.com/iomad/iomad/issues/2001

Shared fix, but I think IOMAD should make it general case for both PostgreSQL and MySQL.

**Comment by turf212** [comment]
I've added the patch to the code as it was a better solution that the one I'd put in place to fix MS SQL Server that unfortunately broke PostgreSQL.
