### ISSUE TITLE
License not allowing user in to course. 

### ISSUE THREAD

**Issue by Blacksheeprules** [iomad/iomad#2027]
A standard license was working before upgrade to IOMAD [4.3.5 (Build: 20240610)]

When we allocate the license to a user, they get the statement below after clicking on the course.

Ther are 97 licensed available. 
![Capture](https://github.com/user-attachments/assets/af198b1d-5d26-4e2b-8a0e-e64d2af8092e)
![Capture1](https://github.com/user-attachments/assets/c6e1c5c3-3ba3-49b4-b384-c1fba201f616)

Your account does not have a valid license to access this course. If you require access contact your company manager to arrange a license.

Thanks in advance for any help you can give us.

**Comment by Blacksheeprules** [comment]
Mark Iannone was the user allocated the license.

![Capture3](https://github.com/user-attachments/assets/be5160b3-b5ee-4dd3-acbb-a83c7a531827)

**Comment by Blacksheeprules** [comment]
The email was sent to the user after the user was created and given the license. 

![Capture4](https://github.com/user-attachments/assets/98c3316e-2041-4b34-93c8-89b387ba53d8)

**Comment by turf212** [comment]
Check that the license enrolment type is enabled and has been added to the course.  It's likely either not there in the course enrolment methods themselves or it's turned off.
