### ISSUE TITLE
How does permission select input in page department user & manager?

### ISSUE THREAD

**Issue by BlackKhm** [iomad/iomad#2029]
Why user teacher by role teacher see role school manager?

![Screenshot 2024-09-10 111811](https://github.com/user-attachments/assets/39da97ad-79d1-4ca8-88e0-c3eb088bdc40)

**Comment by turf212** [comment]
I'm assuming these are renamed roles?  Company managers can create other company managers and department managers. Department managers cannot assign company managers. 

As a department training manager I can only see this:

![image](https://github.com/user-attachments/assets/482bdf16-34fb-4165-a4ff-808d2ba03daa)

Check which role you are renaming to what as it's not what you are expecting.
