### ISSUE TITLE
Refactor 'completion report'

### ISSUE THREAD

**Issue by thepurpleblob** [iomad/iomad#203]
The completion report has grown organically and has become difficult to support and enhance when new features are requested. This now requires a ground-up refactor to modularise the code and make it more easily extended.

**Comment by BananaRama203** [comment]
To begin with can you add in the SORT by function to the headers of the table so users can order by course name for example as the headers for the table are just simple strings.

Also the report displays any open/shared courses and not courses just allocated the company.

Ideally. the table would just display courses that have been allocated to the company. These enhancements would also be beneficial for the license report also.

**Comment by BananaRama203** [comment]
The Language file needs to be set to be consistent across the reports too.

I.e. Lastname is Surname in certain aspects of IOMAD and Lastname in others.

IMHO it should be Surname and only recorded as Lastname within the db.

**Comment by BananaRama203** [comment]
The header for the Mforms on the reports should be made to be the collapsible headers if possible. 

Also any instances of PChart2 graphs should display at the top of the page instead of below of the content.

**Comment by BananaRama203** [comment]
The below check is also redundant as it prevents creating users with report only permissions and needs to be gutted/re-purposed. 

It should be replaced with local/report_companies:view instead

```
if (!(iomad::has_capability('block/iomad_company_admin:editusers', $context) or
      iomad::has_capability('block/iomad_company_admin:editallusers', $context))) {
    print_error('nopermissions', 'error', '', 'report on users');
}
```

**Comment by thepurpleblob** [comment]
Most of the comments here are things I was thinking of doing. The UI should be a lot more presentable.

**Comment by BananaRama203** [comment]
Agreed, I also wanted to look at manipulating the Mform on the IOMAD reports in a non intrusive 'hacky' way to reposition form elements in a more 'pleasing to the eye' responsive layout.

Do you think it would be possible to set up some Plugin Settings page for IOMAD so we can incorporate some layout/theme changes within the settings page?

I.e.  I personally I like to just have the Firstname header instead of Firstname / Lastname and it would be good to introduce a setting in an IOMAD plugin settings page instead of _hacking_ it out of my instance of IOMAD.

**Comment by thepurpleblob** [comment]
I don't think this is a good use for mform as it takes up far too much space when used in this way. I was intending to 'hand code' the forms. 

I'm struggling to see how your second point relates to the report?

**Comment by BananaRama203** [comment]
Hand coding would definitely be a better option.

On the reports and other parts of IOMAD there are features/functionality that I would like to make toggable within settings. For example...

This is my Name Header within my IOMAD reports with the LASTNAME sort disabled (personal preference)

```
$fullnamedisplay = $OUTPUT->action_link($firstnameurl, $firstname); // ." / ". $OUTPUT->action_link($lastnameurl, $lastname);
```

In an ideal world I would be able to code in a IF statement:

If setting = x then $bleh = blehbleh elseif setting = xx then $bleh = bleh

Then any functionality changes within the reports/dashboard I can code in with a toggable setting.

There are other places within Moodle i.e. Edit users where I have removed certain parts of the page and replaced it with our own functionality so a setting page for IOMAD in this instance would be very handy.
