### ISSUE TITLE
Normal user not able to login after current commit https://github.com/iomad/iomad/commit/36b940671640d36ea69003b52d57eaf781ceeaf3

### ISSUE THREAD

**Issue by support-accellier** [iomad/iomad#2032]
This change is creating a **CRITICAL ISSUE** as it is stopping normal user to login into the system as there is code around line 253 and 263 in function get_companies_select of file local/iomad/lib/company.php which is still using $SQLIF

$companies = $DB->get_records_sql_menu("SELECT DISTINCT c.id, $SQLIF (c.suspended=0, c.name, concat(c.name, ' (S)')) AS name, cu.lastused

**Comment by jeroenhabets** [comment]
Thanks @turf212!
