### ISSUE TITLE
****Database Connection Error After Creating Company and User in IOMAD*****

### ISSUE THREAD

**Issue by eamon55** [iomad/iomad#2033]
**Description:**
After a fresh installation of IOMAD, I encountered a database connection issue when attempting to log in as a newly created user. The process I followed was:

1. Installed IOMAD on a Moodle platform.
2. Created a new company.
3. Added a new user under that company.
4. Tried to log in as the newly created user.

Upon login, I received the following error message:

```
Error: Cannot connect to the database
```

**Additional Information:**
- I verified the database credentials, which seem correct since the initial installation went smoothly, and I could create companies and users.
- No specific error logs were generated other than the database connection error upon login.

**Steps to Reproduce:**
1. Install IOMAD.
2. Create a new company.
3. Add a user to the company.
4. Attempt to log in as the new user.

**Expected Result:**
The user should be able to log in successfully without any database connection errors.

**Actual Result:**
The login attempt fails with a "cannot connect to the database" error message.

**System Information:**
-php 8
- IOMAD version: 4.3

**Comment by atljohnsen** [comment]
I got a similar situation after a resent git pull. I believe it is due syntax error in the last commit that done by turf212 last week, in response to issue 2032 reported earlier. I found that the code lacked and END keyword in the CASE statement in /local/iomad/lib/company.php. To fix that I replaced line 352-370 with the following:

$companies = $DB->get_records_sql_menu("SELECT DISTINCT c.id, CASE WHEN c.suspended=0 THEN c.name ELSE concat(c.name, ' (S)') END AS name, cu.lastused
                                                        FROM {company} c
                                                        JOIN {company_users} cu ON (c.id = cu.companyid)
                                                        WHERE cu.userid = :userid
                                                        AND cu.suspended = 0
                                                        $searchsql
                                                        $suspendedsql
                                                        ORDER BY $sort",
                                                        $companiesparams);
            } else {
                $companies = $DB->get_records_sql_menu("SELECT DISTINCT c.id, CASE WHEN c.suspended=0 THEN c.name ELSE concat(c.name, ' (S)') END AS name, cu.lastused
                                                        FROM {company} c
                                                        JOIN {company_users} cu ON (c.id = cu.companyid)
                                                        WHERE cu.userid = :userid
                                                        AND cu.suspended = 0
                                                        $searchsql
                                                        $suspendedsql
                                                        ORDER BY $sort",
                                                        $companiesparams);

**Comment by turf212** [comment]
Fixed in commit 211865e28065a20eb3698cb71c2bc2f0ead74064 from 4th November
