### ISSUE TITLE
Problem updating IOMAD_402_STABLE

### ISSUE THREAD

**Issue by oscc-es** [iomad/iomad#2034]
It seems that local/iomad cannot update properly because at this commit https://github.com/iomad/iomad/commit/8ca53442bd560310d2ec8a4a1717a99728eaca03#diff-f75a3af5435dc9f30d34a8b148de7bee7273cff5181ef5319abce9c2df7371a3R27 **the date version of the plugin changes to a previous date**. (from 2023072901 to 2023042702).

Is it that right?

**Comment by turf212** [comment]
closed in a112aa42c007f536f786fb9ade27ff340326525d on 21st October.  local_iomad versions from 4.1/2/3 all got out of step.
