### ISSUE TITLE
Error Accessing User Profiles and Editing Problem in IOMAD 4.3

### ISSUE THREAD

**Issue by mussaratawais55** [iomad/iomad#2035]
Hello!

I've recently installed IOMAD 4.3, but I'm encountering an issue where users are unable to access or edit their profiles. Whenever someone clicks on the profile link, an error message appears, even for the admin.

Server Error
403
Forbidden

![Screenshot_2](https://github.com/user-attachments/assets/75231b84-5de4-4e96-830e-fbf5b6a787f3)

**Comment by mussaratawais55** [comment]
The URL is when this issue is encountered.
/user/profile.php

**Comment by eamon55** [comment]
Disable Web Application Firewall//plesk 
rules 242994

**Comment by mussaratawais55** [comment]
Thanks.
You have solved my issue.

**Comment by mussaratawais55** [comment]
> Disable Web Application Firewall//plesk rules 242994

Thanks.
You have solved my issue.

**Comment by mussaratawais55** [comment]
Thanks.
You have solved my issue.
