### ISSUE TITLE
Issue with Home Page Redirecting to Dashboard in IOMAD 4.3 for Non-Admin Users

### ISSUE THREAD

**Issue by mussaratawais55** [iomad/iomad#2036]
Hello!

I've recently installed IOMAD 4.3, but I'm encountering an issue. Whenever I navigate to the home page, it only stays there for a few seconds before redirecting me back to the dashboard. This issue doesn’t occur when I log in as an admin, but it happens with other user accounts, including the manager account.

Could you please advise?

**Comment by turf212** [comment]
There were a couple of issues with the company select code in #2042 #2033 #2026 which was causing issues on the home page.  Can you please pull the latest version of 4.3 and check if this is now resolved for you?
