### ISSUE TITLE
 Error in Editing Company Maximum Active Users in IOMAD 4.1 and 4.3

### ISSUE THREAD

**Issue by eamon55** [iomad/iomad#2039]
Dear IOMAD Support Team,

I'm experiencing an issue in IOMAD versions 4.1 and 4.3. When a Company Manager attempts to edit the **Maximum Active Users** for a company, the following error occurs:

### Steps to Reproduce:
1. Navigate to **Edit Company** as a Company Manager.
2. Change the **Maximum Active Users** field (e.g., from 2 to 4).
3. Attempt to save the changes.
4.Then when try to create a new user I see error below : 

### Error Message:
```
Exception - key(): Argument #1 ($array) must be of type array, null given
```
It appears that a `null` value is being passed where an array is expected, likely in the function call to `key()`.

Could you please provide insights on a potential fix or workaround? Additionally, if there are any further steps needed to troubleshoot, please let me know.

Thank you for your attention to this matter.

**Comment by turf212** [comment]
There was a typo on 4.1 and 4.2 and the wrong variable was being passed.  Fix added and pushed.  For 4.3 there was a push already for this under commit d2b7267230a9 from the 6th November.
