### ISSUE TITLE
Assistance Needed for Role Permissions in IOMAD v4.3

### ISSUE THREAD

**Issue by syedaawais** [iomad/iomad#2040]
Hi there,

I am using IOMAD v4.3 and need to create a role with permissions to manage all courses across the IOMAD site. I've created a custom role by replicating the teacher role and adding the following permissions:

1. moodle/category:manage
2. moodle/category:viewcourselist
3. moodle/category:viewhiddencategories
4. moodle/course:create
5. repository/contentbank:accessgeneralcontent
6. repository/contentbank:accesscoursecategorycontent
7. moodle/site:approvecourse
8. tool/brickfield:viewsystemtools
9. moodle/course:view

I’ve set this role to be system-wide. While it can now create and manage courses, it still lacks access to view all courses across different IOMAD companies. 

Could anyone advise on which permissions are required to enable this role to view all courses across the site?

Regards,  
Awais

**Comment by turf212** [comment]
You might want to instead look at the Client administrator role - which can manage all of the companies, users, enrolments and so on but won't have Site admin rights.  If you add capabilities to that the edit courses then it will better provide what you want.
