### ISSUE TITLE
Fresh install DB error

### ISSUE THREAD

**Issue by MTS-Simon** [iomad/iomad#2042]
Installed fresh IOMAD_403_STABLE, using PHP 8.2.25, PostgreSQL 17 - On Ubuntu Server 24.04.1 LTS.

Green across the board during install, and system status, except for one task:

IOMAD microlearning cron - Failing

<img width="643" alt="image" src="https://github.com/user-attachments/assets/850c02fc-e3e1-4d0f-8994-658678dd130c">

**Comment by MTS-Simon** [comment]
Also getting a DB error when attempting to log in as a newly created user:

Debug info: ERROR: syntax error at or near ")"
LINE 1: ...uspended=0 THEN c.name ELSE concat(c.name, ' (S)')) AS name,...
^
SELECT DISTINCT c.id, CASE WHEN c.suspended=0 THEN c.name ELSE concat(c.name, ' (S)')) AS name, cu.lastused
FROM mdl_company c
JOIN mdl_company_users cu ON (c.id = cu.companyid)
WHERE cu.userid = $1
AND cu.suspended = 0

AND c.suspended = 0
ORDER BY cu.lastused DESC, name ASC
[array (
0 => '3',
)]
Error code: dmlreadexception
Stack trace:
line 494 of /lib/dml/moodle_database.php: dml_read_exception thrown
line 293 of /lib/dml/moodle_read_slave_trait.php: call to moodle_database->query_end()
line 358 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->read_slave_query_end()
line 1044 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
line 1607 of /lib/dml/moodle_database.php: call to pgsql_native_moodle_database->get_records_sql()
line 352 of /local/iomad/lib/company.php: call to moodle_database->get_records_sql_menu()
line 1193 of /local/iomad/lib/user.php: call to company::get_companies_select()
line 303 of /blocks/iomad_company_admin/lib.php: call to company_user::add_user_popup_selector()
line 3528 of /lib/outputrenderers.php: call to block_iomad_company_admin_render_navbar_output()
line 219 of /lib/mustache/src/Mustache/Context.php: call to core_renderer->navbar_plugin_output()
line 138 of /lib/mustache/src/Mustache/Context.php: call to Mustache_Context->findVariableInStack()
line 78 of /var/www/moodledata/localcache/mustache/1731510652/iomadboost/__Mustache_1c8d50e68bea0590742b493934c3d42b.php: call to Mustache_Context->findDot()
line 37 of /var/www/moodledata/localcache/mustache/1731510652/iomadboost/__Mustache_371e7f4e880679b78f825636ca415e3f.php: call to __Mustache_1c8d50e68bea0590742b493934c3d42b->renderInternal()
line 66 of /lib/mustache/src/Mustache/Template.php: call to __Mustache_371e7f4e880679b78f825636ca415e3f->renderInternal()
line 208 of /lib/outputrenderers.php: call to Mustache_Template->render()
line 107 of /theme/iomadboost/layout/drawers.php: call to renderer_base->render_from_template()
line 1519 of /lib/outputrenderers.php: call to include()
line 1445 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
line 131 of /index.php: call to core_renderer->header()

**Comment by turf212** [comment]
Hi @MTS-Simon, Odd.  On the DB error - the code pushed to the git repo was updated on the 4th November under 211865e28065 to fix this. Line in the code is https://github.com/iomad/iomad/blob/64b941eb7411f63fef96d2f6d482e7d55a91c2a0/local/iomad/lib/company.php#L352

The initial issue looks to be a a type mismatch.  What does the type of the send_message column in mdl_microlearning_thread in the database?

**Comment by MTS-Simon** [comment]
Ahhh.... ok, something is odd with my repository.... Running 'git branch' shows:
IOMAD_403_STABLE
* myiomad

This is as I'd expect after following the install instructions. But my company.php file is NOT the same as the one on github IOMAD_403_STABLE branch. Even though this is a completely fresh install on a new VM.

My query:
SELECT DISTINCT c.id, CASE WHEN c.suspended=0 THEN c.name ELSE concat(c.name, ' (S)')) AS name, cu.lastused

IOMAD_403_STABLE:
SELECT DISTINCT c.id, CASE WHEN c.suspended=0 THEN c.name ELSE concat(c.name, ' (S)') END AS name, cu.lastused

**Comment by MTS-Simon** [comment]
Looks like the DB type is: bytea

<img width="341" alt="image" src="https://github.com/user-attachments/assets/fe0f5324-e8de-406b-beb8-53deea25fdab">

**Comment by MTS-Simon** [comment]
Progress! Performed a git pull, which allowed the user login to now work. Trying to log in as admin informed me that the microlearning plugin needed to update the DB. Then I got the following:

<img width="860" alt="image" src="https://github.com/user-attachments/assets/064a3637-62ec-466c-94eb-f05390f37d9a">

**Comment by turf212** [comment]
OK - so that's the internal Moodle code which is causing an issue.  The type for that (and a couple of other columns on the microlearning tables) was incorrectly set to binary.  We are following the Moodle code to update the column definition to be SMALLINT with a length of 1 as it will be storing a true false value. All of the code for this is being generated by the Moodle XML DB Editor pages - so it is absolutely correct, just the underlying change functions in PostgreSQL aren't working.  Looking at the internal code it doesn't have anything to add the casting from binary/bytea to integer but there is for Char to integer or char or text to number.

see lib/ddl/postgres_sql_generator.php line 326 on:

```
            // Some castings must be performed explicitly (mainly from text|char to numeric|integer)
            if (($oldmetatype == 'C' || $oldmetatype == 'X') &&
                ($xmldb_field->getType() == XMLDB_TYPE_NUMBER || $xmldb_field->getType() == XMLDB_TYPE_FLOAT)) {
                $alterstmt .= ' USING CAST('.$fieldname.' AS NUMERIC)'; // from char or text to number or float
            } else if (($oldmetatype == 'C' || $oldmetatype == 'X') &&
                $xmldb_field->getType() == XMLDB_TYPE_INTEGER) {
                $alterstmt .= ' USING CAST(CAST('.$fieldname.' AS NUMERIC) AS INTEGER)'; // From char to integer
            }
```

As a quick workaround for where you are - if you remove the folder blocks/iomad_mircolearning and all its contents and reload the page it will skip the installation of that and bring you (eventually) to the notifications page.  You can then go to Site administration -> plugins -> blocks -> manage blocks and  uninstall the IOMAD Microlearning block (it's a new install so you wont have any issues with this) and, once that is complete, put back the blocks/iomad_microlearning folder and files and then re-run the upgrade it will install with the correct types for the tables.

I will raise an issue with Moodle so that this type change is supported in the DB code and hopefully that will get added before anyone on PostgreSQL has to upgrade that has data in this table.

If anyone does then you can run the SQL within the DB directly to convert the columns:
- send_message, send_reminder, halt_until_fulfilled and active on the table mdl_microlearning_thread
- halt_until_fulfilled on table mdl_microlearning_nugget
- message_delivered, reminder1_delivered and reminder2_delivered on table mdl_microlearning_thread_user

`ALTER TABLE <tablename> ALTER COLUMN <columnname> TYPE SMALLINT USING <columnname>::smallint;`

**Comment by turf212** [comment]
There was a similar bug for BINARY to TEXT but it's been closed as not fixed - https://tracker.moodle.org/browse/MDL-20469

**Comment by MTS-Simon** [comment]
Fantastic, thanks for the help! I'll give it a go tomorrow.

**Comment by MTS-Simon** [comment]
GREAT! Got the Microlearning plugin and User logins working! But I still have more DB errors... Sorry!


Scheduled task failed: [[company_license_expiring_task]] (local_email_reports\task\company_license_expiring_task),Error reading from database
Debug info:
ERROR:  column "allocated" does not exist
LINE 2: ...                                      WHERE used < allocated
                                                              ^
HINT:  Perhaps you meant to reference the column "mdl_companylicense.allocation".
SELECT * FROM mdl_companylicense
                                          WHERE used < allocated
                                          AND expirydate > $1
                                          AND expirydate < $2
[array (
  0 => 1731585726,
  1 => 1734177726,
)]
Backtrace:
* line 293 of /lib/dml/moodle_read_slave_trait.php: call to moodle_database->query_end()
* line 358 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->read_slave_query_end()
* line 1044 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
* line 57 of /local/email_reports/classes/task/company_license_expiring_task.php: call to pgsql_native_moodle_database->get_records_sql()
* line 405 of /lib/classes/cron.php: call to local_email_reports\task\company_license_expiring_task->execute()
* line 208 of /lib/classes/cron.php: call to core\cron::run_inner_scheduled_task()
* line 125 of /lib/classes/cron.php: call to core\cron::run_scheduled_tasks()
* line 186 of /admin/cli/cron.php: call to core\cron::run_main_process()

**Comment by turf212** [comment]
Yep - that is a typo.

**Comment by MTS-Simon** [comment]
Thanks for the fast turn around! Pulled the code and it's working. Next I have....


Execute scheduled task: Predict models (tool_analytics\task\predict_models)
... started 13:58:38. Current memory use 19.1 MB.
Debugging increased temporarily due to faildelay of 7680
Analysing id "1" with "From start to end" time splitting method...
-->Courses at risk of not starting results
Prediction results
!! No new elements to get predictions for. !!
Info
!! Analysable Site not used: No data to analyse !!
-->Students who have not accessed the course recently results
Prediction results
!! No new elements to get predictions for. !!
-->Students who have not accessed the course yet results
Prediction results
!! No new elements to get predictions for. !!
Analysing id "3" with "Upcoming week" time splitting method...
.... used 48 dbqueries
... used 0.10338497161865 seconds
Scheduled task failed: Predict models (tool_analytics\task\predict_models),Unsupported redirect detected, script execution terminated
Backtrace:
* line 77 of /local/iomad/lib/iomad.php: call to redirect()
* line 577 of /local/iomad/lib/iomad.php: call to iomad::get_my_companyid()
* line 2484 of /calendar/lib.php: call to iomad::add_calendar_trainingevent_courses()
* line 194 of /calendar/classes/local/event/strategies/raw_event_retrieval_strategy.php: call to calendar_get_default_courses()
* line 51 of /calendar/classes/local/event/strategies/raw_event_retrieval_strategy.php: call to core_calendar\local\event\strategies\raw_event_retrieval_strategy->get_raw_events_legacy_implementation()
* line 164 of /calendar/classes/local/event/data_access/event_vault.php: call to core_calendar\local\event\strategies\raw_event_retrieval_strategy->get_raw_events()
* line 223 of /calendar/classes/local/event/data_access/event_vault.php: call to core_calendar\local\event\data_access\event_vault->get_events()
* line 158 of /calendar/classes/local/api.php: call to core_calendar\local\event\data_access\event_vault->get_action_events_by_timesort()
* line 467 of /calendar/externallib.php: call to core_calendar\local\api::get_action_events_by_timesort()
* line 73 of /course/classes/analytics/indicator/activities_due.php: call to core_calendar_external::get_calendar_action_events_by_timesort()
* line 166 of /analytics/classes/local/indicator/base.php: call to core_course\analytics\indicator\activities_due->calculate_sample()
* line 478 of /analytics/classes/analysis.php: call to core_analytics\local\indicator\base->calculate()
* line 412 of /analytics/classes/analysis.php: call to core_analytics\analysis->calculate_indicators()
* line 330 of /analytics/classes/analysis.php: call to core_analytics\analysis->calculate()
* line 202 of /analytics/classes/analysis.php: call to core_analytics\analysis->process_time_splitting()
* line 105 of /analytics/classes/analysis.php: call to core_analytics\analysis->process_analysable()
* line 286 of /analytics/classes/local/analyser/base.php: call to core_analytics\analysis->run()
* line 824 of /analytics/classes/model.php: call to core_analytics\local\analyser\base->get_static_data()
* line 70 of /admin/tool/analytics/classes/task/predict_models.php: call to core_analytics\model->predict()
* line 405 of /lib/classes/cron.php: call to tool_analytics\task\predict_models->execute()
* line 198 of /admin/cli/scheduled_task.php: call to core\cron::run_inner_scheduled_task()

**Comment by turf212** [comment]
Yeah - the check to get the company ID probably shouldn't be forced here.  This path is to add courses the user isn't enrolled onto that has the Training event activity and has the potential to access (self enrol, unused license) to the user's calendar so they can use that to see upcoming events.  Fixed and pushed with thanks for the spot!

**Comment by MTS-Simon** [comment]
Awesome. Pulled and working!

Ok, final two! Both seem CURL related, so could be just my config...


<img width="664" alt="image" src="https://github.com/user-attachments/assets/ed809330-e3b6-419b-804b-e9a670349d10">

<img width="647" alt="image" src="https://github.com/user-attachments/assets/7d95f59c-6068-4de7-a30b-4ed5c4051c9d">

PHP v8.2.25 Info - showing CURL is enabled:

<img width="299" alt="image" src="https://github.com/user-attachments/assets/5f128c29-0581-40b8-a186-fca84fa23790">

**Comment by MTS-Simon** [comment]
Ignore the above! reinstalled php-curl again, and it's now working. No more failing tasks. THANKS FOR ALL THE HELP!
