### ISSUE TITLE
My courses block outdated on version 4.3

### ISSUE THREAD

**Issue by andresmrg** [iomad/iomad#2043]
Upgrading from 4.1.14 to 4.3 latest version shows 4.1 had mycourses block in 2024082700 and 4.3 has 2023092201
![Screenshot 2024-11-13 at 9 55 32 AM](https://github.com/user-attachments/assets/c6ea16f9-39db-4323-b88b-28208df41c42)

**Comment by turf212** [comment]
Thanks for letting me know.  One of the commits from the 4.1 branch didn't get added to the 4.3 code.  Now added and pushed.

**Comment by turf212** [comment]
commit 4916504f1b9c6f9da9ee84d3841fde6680b8a1df
