### ISSUE TITLE
IOMAD 4.3.8: creating child company is broken (2)

### ISSUE THREAD

**Issue by tom5850** [iomad/iomad#2047]
Thank you @turf212 for fixing #2044. The form is now behaving as expected. But we face some more issues. 

When a company manager creates a child company, he gets this error:

```
Coding error detected, it must be fixed by a programmer: The 'usertypename' value must be set in other.

More information about this error

Debug info:
Error code: codingerrorDismiss this notification
Stack trace:
line 111 of /blocks/iomad_company_admin/classes/event/company_user_assigned.php: coding_exception thrown
line 287 of /lib/classes/event/base.php: call to block_iomad_company_admin\event\company_user_assigned->validate_data()
line 1572 of /local/iomad/lib/company.php: call to core\event\base::create()
line 1085 of /local/iomad/lib/company.php: call to company::upsert_company_user()
line 1764 of /local/iomad/lib/company.php: call to company->assign_user_to_company()
line 407 of /blocks/iomad_company_admin/company_edit_form.php: call to company->assign_parent_managers()
Dismiss this notification
Output buffer: <br /> <b>Warning</b>: Undefined array key 1 in <b>/data/www/www58/www/iomad_bak/local/iomad/lib/company.php</b> on line <b>1567</b><br />
```

The child company is created. The company manager can select it in the company dropdown menu,  but no administration functions are available.

I found that in table mdl_company_role_restriction the capabilities for the newly created child company are missing (same happens btw when a sys admin creates the child company). When I add the missing records to this table, the administration functions are available.

When I now as a company manager select the child company in the company dropdown menu, it shows that my child company is selected. But this is not true. When I edit the company, I see the data of the parent company, not of the child. When I do the same as a Sys Admin, it works as expected.

**Comment by turf212** [comment]
The event needs to pass some information in other, which is there in the code, but it's pulling it from an array - 

This is the event it's firing in company.php
```
        // Create an event for this.
        $eventother = array('companyname' => $company->get_name(),
                            'companyid' => $company->id,
                            'departmentid' => $departmentid,
                            'usertype' => $managertype,
                            'usertypename' => $managertypes[$managertype],
                            'moved' => $move);
        $event = \block_iomad_company_admin\event\company_user_assigned::create(array('context' => $companycontext,
                                                                                      'objectid' => $company->id,
                                                                                      'userid' => $userid,
                                                                                      'other' => $eventother));
```
Can you please add the following before line 1569 (which is the $event = line) 

```
error_log(print_r($managertypes, true));
error_log(print_r($other,thrue));
```

Which will dump the manager types array neing used and the event other definition into your webserver logs.  You can cause this to this again by adding a new company manager to the parent company or promoting a user in the parent company to company manager.

**Comment by tom5850** [comment]
Thank you for your help Derick. When I create a new company manager as Sys Admin, I get this in the log
(Note: line 1570 is: error_log(print_r($other,true)); )

```
[18-Nov-2024 18:07:05] Array
(
    [0] => User
    [1] => Company manager
    [2] => Department training manager
    [3] => Course educator
    [4] => Company report only
)

[18-Nov-2024 18:07:05] PHP Warning:  Undefined variable $other in /local/iomad/lib/company.php on line 1570
[18-Nov-2024 18:07:05] 
[18-Nov-2024 18:07:05] Array
(
    [0] => User
    [1] => Company manager
    [2] => Department training manager
    [3] => Course educator
    [4] => Company report only
)

[18-Nov-2024 18:07:05] PHP Warning:  Undefined variable $other in /local/iomad/lib/company.php on line 1570
[18-Nov-2024 18:07:05] 
[18-Nov-2024 18:07:05] Array
(
    [0] => User
    [1] => Company manager
    [2] => Department training manager
    [3] => Course educator
    [4] => Company report only
)

[18-Nov-2024 18:07:05] PHP Warning:  Undefined variable $other in /local/iomad/lib/company.php on line 1570
[18-Nov-2024 18:07:05] 
[18-Nov-2024 18:07:05] Array
(
    [0] => User
    [1] => Company manager
    [2] => Department training manager
    [3] => Course educator
    [4] => Company report only
)

[18-Nov-2024 18:07:05] PHP Warning:  Undefined variable $other in /local/iomad/lib/company.php on line 1570
[18-Nov-2024 18:07:05] 
[18-Nov-2024 18:07:05] Array
(
    [0] => User
    [1] => Company manager
    [2] => Department training manager
    [3] => Course educator
    [4] => Company report only
)

[18-Nov-2024 18:07:05] PHP Warning:  Undefined variable $other in /local/iomad/lib/company.php on line 1570
[18-Nov-2024 18:07:05] 
[18-Nov-2024 18:07:16] Array
(
    [0] => User
    [1] => Company manager
    [2] => Department training manager
    [3] => Course educator
    [4] => Company report only
)

[18-Nov-2024 18:07:16] PHP Warning:  Undefined variable $other in /local/iomad/lib/company.php on line 1570
[18-Nov-2024 18:07:16] 
```

When I do the same as a company manager, I get the same error as when I create a child company:
```
[18-Nov-2024 18:06:15 Europe/Zurich] PHP Warning:  Undefined array key 1 in /data/www/www58/www/iomad_bak/local/iomad/lib/company.php on line 1567
[18-Nov-2024 18:06:15 Europe/Zurich] Array
(
    [0] => User
)

[18-Nov-2024 18:06:15 Europe/Zurich] PHP Warning:  Undefined variable $other in /data/www/www58/www/iomad_bak/local/iomad/lib/company.php on line 1570
[18-Nov-2024 18:06:15 Europe/Zurich] 
[18-Nov-2024 18:06:15 Europe/Zurich] Default exception handler: Coding error detected, it must be fixed by a programmer: The 'usertypename' value must be set in other. Debug: 
Error code: codingerror
* line 111 of /blocks/iomad_company_admin/classes/event/company_user_assigned.php: coding_exception thrown
* line 287 of /lib/classes/event/base.php: call to block_iomad_company_admin\event\company_user_assigned->validate_data()
* line 1574 of /local/iomad/lib/company.php: call to core\event\base::create()
* line 1445 of /local/iomad/lib/company.php: call to company::upsert_company_user()
* line 115 of /blocks/iomad_company_admin/company_user_create_form.php: call to company::upsert_company_user()
```

**Comment by turf212** [comment]
2 Questions
1-  Can you please let me know the version?  I think it's 4.3 but we have on-going work on 4.1, 4.2 and 4.3 (never mind final push on 4.4)
2 - Can you please give me the code or check your code around those lines in company.php - the variable $other doesn't exist anywhere near there in 4.1, 4.2 or 4.3.  The variable which should be there is $eventother around this bit -  https://github.com/iomad/iomad/blob/99de84b1004d5ca482ff8d0e35ef67afd9019f0b/local/iomad/lib/company.php#L1562

**Comment by tom5850** [comment]
1- We are using the lasted v4.3.8 (updated today, checked this issue again after latest updates and it is still there).
2- company.php is the same as on Github; I compared it extra to be absolutely sure

Maybe this is a configuration issue on our side. We have chosen a special setting for allowing certain users to create and manage child companies.
- a company manager does not have the required capabilities to add a child or suspend it (block/iomad_company_admin:company_add_child, block/iomad_company_admin:suspendcompanies)
- we have created a new system role which has those two capabilites
- when a company manager needs to use child companies, we just assign him this system role
- with v4.1 and v4.2 this approach worked well

Could this be the reason why we are facing this issue now?

**Comment by turf212** [comment]
What you have done for your reseller users is exactly how I would recommend it.  It wont be that.

It's weird that it's complaining about a variable that just isnt reference on that line in that file.  Can you get the lines around 1550 - 1580 in local/iomad/lib/company.php?

**Comment by tom5850** [comment]
[company.txt](https://github.com/user-attachments/files/17903539/company.txt)
I have attached our company.php.

Lines 1552-1579 contain:
```

            // Are we updating the user record?
            if(count($s)) {
                $s['id'] = $user->id;
                $success = $DB->update_record('company_users', array_merge($assign,$s));
            }
        }
        if(!$success) {
            throw new moodle_exception(get_string('cantassignusersdb', 'block_iomad_company_admin'));
        }

        // Create an event for this.
        $eventother = array('companyname' => $company->get_name(),
                            'companyid' => $company->id,
                            'departmentid' => $departmentid,
                            'usertype' => $managertype,
                            'usertypename' => $managertypes[$managertype],
                            'moved' => $move);
        $event = \block_iomad_company_admin\event\company_user_assigned::create(array('context' => $companycontext,
                                                                                      'objectid' => $company->id,
                                                                                      'userid' => $userid,
                                                                                      'other' => $eventother));
        // Fire the event.
        $event->trigger();

        if($ws) return $success;

        return true;
    }
```

With added debug lines before $event= it's this: 


```
            // Are we updating the user record?
            if(count($s)) {
                $s['id'] = $user->id;
                $success = $DB->update_record('company_users', array_merge($assign,$s));
            }
        }
        if(!$success) {
            throw new moodle_exception(get_string('cantassignusersdb', 'block_iomad_company_admin'));
        }

        // Create an event for this.
        $eventother = array('companyname' => $company->get_name(),
                            'companyid' => $company->id,
                            'departmentid' => $departmentid,
                            'usertype' => $managertype,
                            'usertypename' => $managertypes[$managertype],
                            'moved' => $move);
error_log(print_r($managertypes, true));
error_log(print_r($other,true));
        $event = \block_iomad_company_admin\event\company_user_assigned::create(array('context' => $companycontext,
                                                                                      'objectid' => $company->id,
                                                                                      'userid' => $userid,
                                                                                      'other' => $eventother));
        // Fire the event.
        $event->trigger();

        if($ws) return $success;

        return true;
    }
```

**Comment by turf212** [comment]
its the error_log line you put in.  Should have been 

`error_log(print_r($eventother,true));
`

**Comment by tom5850** [comment]
Okay, this mistery is solved. I have updated to latest source files today and I have added at line 1646

```
error_log(print_r($managertypes, true));
error_log(print_r($eventother,true));
```

Source file [company.txt](https://github.com/user-attachments/files/17907765/company.txt)

When creating a child company with a partner manager (reseller), I get this error

```
Coding error detected, it must be fixed by a programmer: The 'usertypename' value must be set in other.

[More information about this error](https://docs.moodle.org/403/en/error/debug/codingerror)

Debug info:
Error code: codingerrorDismiss this notification
Stack trace:
line 111 of /blocks/iomad_company_admin/classes/event/company_user_assigned.php: coding_exception thrown
line 287 of /lib/classes/event/base.php: call to block_iomad_company_admin\event\company_user_assigned->validate_data()
line 1651 of /local/iomad/lib/company.php: call to core\event\base::create()
line 1162 of /local/iomad/lib/company.php: call to company::upsert_company_user()
line 1843 of /local/iomad/lib/company.php: call to company->assign_user_to_company()
line 423 of /blocks/iomad_company_admin/company_edit_form.php: call to company->assign_parent_managers()
Dismiss this notification
Output buffer: <br /> <b>Warning</b>: Undefined array key 1 in <b>/data/www/www58/www/iomad_bak/local/iomad/lib/company.php</b> on line <b>1644</b><br />
```

Log file:
```
[25-Nov-2024 20:15:25] PHP Warning:  Undefined array key 1 in /data/www/www58/www/iomad_bak/local/iomad/lib/company.php on line 1644
[25-Nov-2024 20:15:25] Array
(
    [0] => User
)

[25-Nov-2024 20:15:25] Array
(
    [companyname] => Created by Partner Manager 3
    [companyid] => 100
    [departmentid] => 148
    [usertype] => 1
    [usertypename] => 
    [moved] => 
)

[25-Nov-2024 20:15:25] Default exception handler: Coding error detected, it must be fixed by a programmer: The 'usertypename' value must be set in other. Debug: 
Error code: codingerror
* line 111 of /blocks/iomad_company_admin/classes/event/company_user_assigned.php: coding_exception thrown
* line 287 of /lib/classes/event/base.php: call to block_iomad_company_admin\event\company_user_assigned->validate_data()
* line 1651 of /local/iomad/lib/company.php: call to core\event\base::create()
* line 1162 of /local/iomad/lib/company.php: call to company::upsert_company_user()
* line 1843 of /local/iomad/lib/company.php: call to company->assign_user_to_company()
* line 423 of /blocks/iomad_company_admin/company_edit_form.php: call to company->assign_parent_managers()
```

**Comment by tom5850** [comment]
And I just realized that with the latest source code, the company short name is allowed to contain only small alphanumerics and underscore. In the previous versions upper case letter and blanks were allowed.
It's not an issue, we can migrate the short names. Just want to ask if this intentional.

**Comment by turf212** [comment]
Thanks for the data - The usertype of 1 should be in the list and it's not. ID 1 should be Company manager (in your case).  Let me check why that's not getting set up in the $usertypes array in this case.  Currently what is happening is that the child company is being created but the reseller account is not being added as a manager to it - so they can see it but can't do anything in it - which is what you are seeing.

As for the company shortname - yes - this and department shortname were both changed to match the Moodle requirements for shortname data (lowercase alphanumerics and underscore).  Special characters in the shortname were breaking the URLS for company checking on log out.  I didn't want to update the database values as there wasn't really any way to do this and ensure the data was valid/didn't clash - so it's enforced on the forms and users will need to update as they edit the companies.

**Comment by turf212** [comment]
Found the issue.  The function call company::get_manager_types() is used to filter out what someone can or cannot see in the dropdowns, so it has a number of capability checks and returns an array with lesser or more values depending on what you should be able to see.

When we are creating the child company - it checks the current user's right on that new company and, since in your case the current user is not yet a company manger in that company, it fails to bring enough back and causes the error.

I've added a parameter to the get_manager_types() where we can pass that we want the full list instead, skipping the checks, which can be used inside other functions which have already been appropriately checked. This will solve this issue.

**Comment by tom5850** [comment]
Thank you @turf212 . We don't see any error anymore with this latest fix. However, the partner manager cannot manage the child company. He sees it in the dropdown, he can suspend it, but he cannot manage it. All the admin functions are not shown.

**Comment by turf212** [comment]
Was this with company they had previously created or a new company?  It wont fix a precious company but, for those, you will be able to promote them within the company to Company manager to fix.

**Comment by tom5850** [comment]
It was with a new company. The partner manager can create the child without error. It is also visible in the company selector dropdown. But when selected, the partner manager has no admin fucntions available.

I have check the database table mdl_company_users and see that a new record for the child was created where the partner manager has managertype=1. This new record looks excatly the same as for the childs we have created before.

mdl_company_role_restriction shows no entries for the new child. But it shows also not entry for the childs created before. Only the root company has records.

What else can I check to debug this?

**Comment by turf212** [comment]
Found the issue - the company manager was tagged as not being in the company tree when they created the child company, so they were never given the company manager role at the child company context.  I've fixed this in the code.  I've also tidied up what the user will see in case they are company manger in one company and not in another but have the rights to create child companies too.

**Comment by tom5850** [comment]
Thank you very much @turf212. It's working perfectly now! I close this issue.

**Comment by tom5850** [comment]
Apologies, @turf212 , but I have to reopen this issue.
Problem is now, that the company manager of the child company has no admin rights on the child.
I did:

- log in as partner manager and created a child company: works perfectly
- created a new user with role company manager and educator: works perfectly
- log out
- log in with the newly created child company manager: log in works, but I have no access to the admin functions

It looks like if the child company manager does not get any company manager capabilities.

When I check the role assignments of the child company manager, I only see: _System: Company Manager_. It doesn't get _Client Course Access_ to the course categories, usually a company manager and educator gets.

**Comment by turf212** [comment]
Does the partner manager create the new manager in the child company?

**Comment by turf212** [comment]
Just tested this on the same site I was using (4.4 but shouldn't make a difference here)

Log in as reseller user
Go to IOMAD Dashboard
Select Child company
Users -> Edit users = no users found -> Create user
Create new account and select company manager
== Account created and listed as Company manager

Log out and log in as this new account - User has access to the IOMAD dashboard for the Child company

Is this what you are doing - or are you creating another company manager in the parent company?

Actually - that might be what you are saying.  Just tried this by creating a company manager in the parent company and it wasn't added to the child company (and should be).

**Comment by turf212** [comment]
Ignore me - I thought it was broken as it wasn't listing the user in the child company - but it shoudln't as they are from the parent company.

**Comment by tom5850** [comment]
Yes, that's exactly what I did. 

But sorry, I think I misunderstood something. 
I logged in with the child company manager using the parent company URL. I was able to log in, but did not have access to any of my child's admin functions.
When I used the correct URL for the child, I was able to access the admin functions.

Could you please give me some quick advice?

- the parent company has the url: parent.iomad.com
- the child does not have a specific domain
- A child user can use the parent company's url parent.iomad.com to log in (this is what this partner wants) and access his courses, no problem.
- if the company manager logs in with the parent company url parent.iomad.com, he can log in but he will be considered as a normal user and not as a company manager. I have also tested parent.iomad.com/login/index.php?id=123&code=child_company with the same result.

Is this by design? And if so, would you recommend not using the parent url, but creating a specific subdomain for the child (or using the base url plus the id & code)?

**Comment by turf212** [comment]
In the parent company context - which is selected by default when you log in via their URL - the child company admin is just a user.  Which is why they wont see it.  If the child company managers logs into the main URL of the site they will get their company.  

The company switcher would trigger if they were in more than one company, but I could update it so that it would create a drop down if they were only in one company and the current SESSION company wasn't it.  Then the manager could pick up their company and go from there (this is assuming they are logging in on the reseller URL).

**Comment by tom5850** [comment]
That's a nice idea, thanks.

**Comment by turf212** [comment]
Updated the code to allow this.

**Comment by tom5850** [comment]
Thanks, it's working perfectly.
