### ISSUE TITLE
IOMAD 4.3.8: company manager cannot edit user anymore

### ISSUE THREAD

**Issue by tom5850** [iomad/iomad#2052]
Since upgrade from 4.2 to 4.3.8,  a company manager cannot edit a user anymore.

```
Error:
The system administrator has not given you permission to do this.

Debug-Info: 
Error code: nopermissions
Stack trace: 
line 1883 of /local/iomad/lib/iomad.php: required_capability_exception thrown
line 76 of /blocks/iomad_company_admin/editadvanced.php: call to iomad::require_capability()
```

editadvanced.php checks the capability
`76 iomad::require_capability('block/iomad_company_admin:editusers', $systemcontext);`

The company manager role has this capability:
block/iomad_company_admin:editusers = allow

So, the company manager has the required capability. Are we missing something or is this a bug?

**Comment by turf212** [comment]
This is a bug - those capability checks should have been on the company context not the system context.  Pushed a fix.

**Comment by tom5850** [comment]
Thank you very much. It's working now.
