### ISSUE TITLE
Email Templates Not Showing in IOMAD 4.1 and 4.2 

### ISSUE THREAD

**Issue by eamon55** [iomad/iomad#2053]
Dear Derick

I am experiencing an issue where the Email Templates feature is not appearing in IOMAD. This occurs both when installing IOMAD directly and when upgrading from Moodle 4 to IOMAD 4.1. or IOMAD 4.2

Could you please assist in resolving this issue? 

Best regards,
Eamon

**Comment by turf212** [comment]
Is cron running?

If so - then if you go to Site administration -> General -> Language customisation and open the language pack for editing it will prompt the system to update all of the strings in the DB (which the templates moved over to using)

An Adhoc task should also have been created to do this - but if you are still in maintenance after the upgrade then cron will be disabled so it won't run.
