### ISSUE TITLE
Warning notice after removing a course from manual enrollment page

### ISSUE THREAD

**Issue by dallenk** [iomad/iomad#2057]
As the site admin I Navigate too: Company Dashboard-> Courses -> User Enrollments

Choose a course from the Search box - the user list is shown (in my case, no users are registered)

click the X to remove the course from the "Select course to enrol into" view.

Error shown, the course is removed from the view.
```
optional_param_array() expects array parameters only: selectedcourses
line 740 of /lib/moodlelib.php: call to debugging()
line 33 of /blocks/iomad_company_admin/company_course_users_form.php: call to optional_param_array()
```

**Comment by turf212** [comment]
We are at the mercy of Moodle here.  The Auto select type we are using will pass back an array of courses - so we need to use optional_param_array() to capture this.  When you clear that select, it instead passes back a string - which is causing this warning.

In the code for optional_param it _does_ check whether the param being passed is an array and calls the optional_param_array() function instead.  The only issue is that it _also_ displays a warning that this has happened in debug.

This means we get a warning both ways.

I can add a check on the $_POST variable directly, which I'd prefer not to do, but seems to be the only option to not get any debug warnings.
