### ISSUE TITLE
error viewing another users profile

### ISSUE THREAD

**Issue by dallenk** [iomad/iomad#2058]
b04ab1663e9 (HEAD -> IOMAD_403_STABLE, origin/IOMAD_403_STABLE) IOMAD: added date selected for emails on uploaduser pages

This is an odd one, and possibly an issue with users able to see too much of another users profile.

as a regular user, navigate to a course and view participants.   I only see participants that are in my own company, which is OK.. but should users even see this?

Anyway, clicking on a user takes to the view.php.

click on "Full Profile" and the errors shown:

```
Coding problem: $PAGE->context was not set. You may have forgotten to call require_login() or $PAGE->set_context(). The page may not display correctly as a result
line 572 of /lib/pagelib.php: call to debugging()
line 967 of /lib/pagelib.php: call to moodle_page->magic_get_context()
line 1594 of /lib/weblib.php: call to moodle_page->__get()
line 2343 of /local/iomad/lib/company.php: call to format_string()
line 2377 of /local/iomad/lib/company.php: call to company::get_all_subdepartments()
line 2414 of /local/iomad/lib/company.php: call to company::get_recursive_department_users()
line 3846 of /local/iomad/lib/company.php: call to company::get_my_users()
line 80 of /user/profile.php: call to company::check_can_manage()

```

**Comment by turf212** [comment]
There is a capability for the student role which you can take away that prevents them from seeing who  else is in the course - Its a core Moodle one and it's View participants (moodle/course:viewparticipants)

We have a check in the users profile view page for security in case someone just changes the id= number to a different one and it's not someone in their tenant.  This is the company::check_can_manager()

The bit of code after that check fails does set the PAGE context but it looks like the code format string function we are using to get the filtered names of the list of companies references that and it doesn't yet exist.

They also shouldn't be able to view or look at the preferences of users either - so will update that.
