### ISSUE TITLE
not sure if a bug, but lowercase forced for short name?

### ISSUE THREAD

**Issue by dallenk** [iomad/iomad#2059]
![image](https://github.com/user-attachments/assets/3d5035ee-411f-41bf-a2e0-1ecbad893f2a)

this is new, first time it's restricted to lowercase letters.  is this intentional?  or a Moodle issue and not IOMAD ?

**Comment by turf212** [comment]
It's to bring it in line with the core Moodle checking for shortnames used in optional fields, courses, etc.  It was updated as it was allowing special characters before and that was breaking the log out URL changes.  Commit was this one - 706b2c94d17caab4e466b585b49b0f7c9fdcd961 and there were a couple of bugs which referenced it on Github too.
