### ISSUE TITLE
Question:  Certificate is emailed every time a user clicks on the IOMAD certificate link in a course

### ISSUE THREAD

**Issue by dallenk** [iomad/iomad#2070]
i just noticed a change in the way the certificate is handled and the email.

When a user completes a course and is issued a certificate, it isn't actually sent until a user clicks on the IOMAD certificate module in the course.

but, if a user goes back to the course, and clicks the link to view the certificate again, it is emailed again, and each time it is visited.

I'm guessing the certificate isn't actually created until the user clicks the link, but would it be better to have the system create it automatically when the requirements are met for course completion?  I do see the text above the button:  "Click the button below, and your certificate will be sent to you as an email attachment."  but I don't remember this occurring before.

**Comment by turf212** [comment]
This is the settings you have for the IOMAD Certificate.  User gets one when they open it - send to user on new certificate. 

This could also be tied to why the certificate isn't being sent in the other issue.  If the certificate activityisn't available to the user at the point in time they complete the course - then it won't get saved.  This could be down to things like - availability restriction == course completion.  Course completed - system records everything - then certificate is made available.

If you change it to have the same restrictions as the triggers for the course then it should fix this and the isse you were having at the end of #2048
