### ISSUE TITLE
IOMAD 4.3.8: Course images are not tenant aware when using subdomains

### ISSUE THREAD

**Issue by tom5850** [iomad/iomad#2089]
We are using subdomains for each tenant.
With the latest update (migration from 4.2 to 4.3.8), users are complaining that the course images are not displaying anymore in the "My courses" block. In the course itself the course image is displayed correctly.
When checking the html code of the "My courses" page, we see that some images have the url client1.domain.com, others client2.domain.com and so on. It looks like the client who has loaded the image as first after cache purge, defines the url of the image.
Any ideas of how we could fix that?

**Comment by turf212** [comment]
You are right - the URL for the course image is being cached with the full URL.  It's the requirement to force_login in the config, which is causing the course_image get from filelib.php to fire a require_login() call.  The only way I can see to stop that is to turn that check and response off.

**Comment by turf212** [comment]
Commented out this code.

**Comment by tom5850** [comment]
@turf212 , Thanks for fixing this. However, I'm not 100% convinced by this approach. While it certainly fixes the problem of not displaying images, it also opens up a small data leak. Anyone analysing the source code of the page will see other tenants' subdomains, which is not recommended.
I've taken a different approach and replaced the image url with the correct subdomain url.
I.e. in blocks/mycourses/classes/output/inprogress_view.php on line 102 I added the following code:
```
// 1. Find out the current URL of the web server.
$currenturl = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? "https" : "http")
    . "://$_SERVER[HTTP_HOST]";
// 2. replace the URL up to pluginfile.php with the current URL.
$imageurl = preg_replace('#^https?://[^/]+/pluginfile\.php#', $currenturl . '/pluginfile.php', $imageurl);
```
This way the URL and image are always correct.
It requires further modification of core Moodle elements, so I understand if this approach is not the best in terms of maintenance. We have developed our own dashboard anyway and are independent of this block. However, I wanted to share my thoughts with you.

**Comment by turf212** [comment]
Actually - with that approach - there are a couple of options (and yes, agree, it's better)

$CFG->wwwroot will be the right webserver root for the current user - with their tenant URL.

$SESSION->company->hostname will be the hostname to use in the company URL (probably more useful).

so could replace the hostname in $imageurl with the company hostname.

Need to think of the best way.

**Comment by turf212** [comment]
Other thoughts - changing it only in the MyCourses block wont fix this in the enrol externallib, completion information and so on.

What would be best is changing the cache value before it's sent back.  Checking on what is currently being cached that could be causing an issue - it's just this.  So perhaps not.

What will sort it is changing the code in the original exporter to have the right URL for the user.

**Comment by tom5850** [comment]
Indeed, that would be the very best solution.
