### ISSUE TITLE
/local/report_completion/index.php?sort=finalscore&dir=ASC&perpage=X&courseid=X&departmentid=X error

### ISSUE THREAD

**Issue by BananaRama203** [iomad/iomad#209]
when clicking on final grade % header in the all users part of completion_report

you receive the error "cannot read from database"

I have noticed on the other reports for different headers also.

/local/report_completion/index.php?sort=finalscore&dir=ASC&perpage=X&courseid=X&departmentid=X

**Comment by turf212** [comment]
scores are being added after the data is being brought back so shouldn't be able to sort on it.  Will change the header.

**Comment by BananaRama203** [comment]
OK I will find out which other headers are having the same issues and replace them as strings.

**Comment by BananaRama203** [comment]
Solved in commit a1a8e2e2ac84d39c3e6ff2a3f98d42e1d4b143f5
