### ISSUE TITLE
URL: Open in Popup external pdf redirects to the log in page of the main site 

### ISSUE THREAD

**Issue by kirupalaksh** [iomad/iomad#2092]
URL: Open in Popup external pdf redirects to the log in page of the main site if click on sub domain 
and redirects to login page of sub domain if click on main site.  Let me know what to do ?

**Comment by turf212** [comment]
Looks like the same kind of issue as #2089.  Can you please confirm which version of IOMAD you are using?

**Comment by turf212** [comment]
Just tested this on 4.3:

Course shared across 2 tenants
each tenant has a different URL
one user from each tenant enrolled into this course
Added a file resource with a PDF set to open in a popup
Logged in as first user on their company URL and went into the course - PDF opened as expected
In a different browser - logged in as the second user on their company URL and went into the course - PDF opened as expected.

So - definitely not related and it all seems to work. Again - what version of IOMAD are you using?

**Comment by kirupalaks** [comment]
My Moodle version 4.0.

**Comment by turf212** [comment]
We have stopped support for that version - the last push to it was in February of this year.   Moodle also have stopped all security fixes for it.

You can upgrade to 4.1 (which is the last LTS version) - which will supported by Moodle till December next year for security fixes and is being actively maintained by us.  If you are already on PHP 7.4 then you are at the minimum version required for IOMAD 4.1,  so there would be no need to update your server set-up.  IOMAD 4.1 will also support PHP 8.1 - which is the minimum version for 4.3+, so you can future proof it too.

Usual recommendations for upgrade apply.  Test it on a UAT to check none of your plugins are broken or need changes (e.g. theme) then backup live fully before upgrading.

**Comment by kirupalaksh** [comment]
sry for that wroing verson. We are using moodle 4.1. Thank you so much for detailed clarification. That is our next plan to upgrade. Without upgrade Pop Up will not work properly right ?

**Comment by turf212** [comment]
We've tested these same steps on 4.1 latest and everything works as it does for 4.3.  If you patch to the latest 4.1 code (4.1.15) and check if it's resolved.
