### ISSUE TITLE
4.3.8: Change course enrolments for a user gives error

### ISSUE THREAD

**Issue by tom5850** [iomad/iomad#2098]
Go to Users > Edit users. Click on "User controls" of a user and select "Change course enrolments" returns this error:

```
Exception - Class "context_company" not found

[More information about this error](https://docs.moodle.org/403/en/error/moodle/generalexceptionmessage)

Debug info:
Error code: generalexceptionmessageDismiss this notification
Stack trace:
line 474 of /local/course_selector/lib.php: Error thrown
line 834 of /blocks/iomad_company_admin/lib/course_selectors.php: call to course_selector_base->search_sql()
line 208 of /local/course_selector/lib.php: call to potential_user_course_selector->find_courses()
line 148 of /blocks/iomad_company_admin/classes/forms/company_users_course_form.php: call to course_selector_base->display()
line 1045 of /lib/formslib.php: call to block_iomad_company_admin\forms\company_users_course_form->definition_after_data()
line 99 of /blocks/iomad_company_admin/company_users_course_form.php: call to moodleform->display()
```

Simply replacing ‘context_company’ with ‘context_system’ fixes this error and allows me to change the user's registrations. However, the debug output still indicates another error:

```
context_system::instance(): invalid $id parameter detected, should be 0
line 142 of /lib/classes/context/system.php: call to debugging()
line 474 of /local/course_selector/lib.php: call to core\context\system::instance()
line 834 of /blocks/iomad_company_admin/lib/course_selectors.php: call to course_selector_base->search_sql()
line 208 of /local/course_selector/lib.php: call to potential_user_course_selector->find_courses()
line 148 of /blocks/iomad_company_admin/classes/forms/company_users_course_form.php: call to course_selector_base->display()
line 1045 of /lib/formslib.php: call to block_iomad_company_admin\forms\company_users_course_form->definition_after_data()
line 99 of /blocks/iomad_company_admin/company_users_course_form.php: call to moodleform->display()
```

**Comment by turf212** [comment]
Mis-use of the function should be \core\context\company::instance()

**Comment by tom5850** [comment]
@turf212 I still get an error, when I click on "Change enrolments" in the edit user form:

Exception - Too few arguments to function core\context\company::instance(), 0 passed in [dirroot]/local/course_selector/lib.php on line 473 and at least 1 expected

[More information about this error](https://docs.moodle.org/403/en/error/moodle/generalexceptionmessage)

Debug info:
Error code: generalexceptionmessageDismiss this notification
Stack trace:
line 148 of /lib/classes/context/company.php: ArgumentCountError thrown
line 473 of /local/course_selector/lib.php: call to core\context\company::instance()
line 834 of /blocks/iomad_company_admin/lib/course_selectors.php: call to course_selector_base->search_sql()
line 208 of /local/course_selector/lib.php: call to potential_user_course_selector->find_courses()
line 148 of /blocks/iomad_company_admin/classes/forms/company_users_course_form.php: call to course_selector_base->display()
line 1045 of /lib/formslib.php: call to block_iomad_company_admin\forms\company_users_course_form->definition_after_data()
line 99 of /blocks/iomad_company_admin/company_users_course_form.php: call to moodleform->display()

**Comment by turf212** [comment]
Definitely not getting an error here  - code around those lines should be:

```
        // Add some additional sensible conditions.
        $companyid = iomad::get_my_companyid(context_system::instance());
        if (!iomad::has_capability('moodle/course:viewhiddencourses', \core\context\company::instance($companyid)) &&
            !iomad::has_capability('moodle/course:viewhiddencourses', \core\context\company::instance($companyid))) {
```

(which is the same check so I'll going to have to remember what my thinking was - probably at site level)

In any case the call to set the companyid will redirect to the IOMAD dashboard if you don't have one - so it has to exist as a variable definition to be passed

**Comment by tom5850** [comment]
I agree, now it works. Don't know why my previous test was failing.
