### ISSUE TITLE
403: unable to disable maintenance mode after upgrade

### ISSUE THREAD

**Issue by dallenk** [iomad/iomad#2102]
on my sandbox, I attempted an upgrade from d14059c4217 to 9cc7e7a2a59

`domain@sandbox:/var/www/vhosts/sandbox.domain.ca/iomad$ sudo -u www-data git pull
[sudo] password for domain:
remote: Enumerating objects: 48043, done.
remote: Counting objects: 100% (24127/24127), done.
remote: Compressing objects: 100% (125/125), done.
remote: Total 48043 (delta 24001), reused 24117 (delta 23995), pack-reused 23916 (from 1)
Receiving objects: 100% (48043/48043), 21.41 MiB | 10.66 MiB/s, done.
Resolving deltas: 100% (34117/34117), completed with 5556 local objects.
From https://github.com/iomad/iomad
   d14059c4217..9cc7e7a2a59  IOMAD_403_STABLE -> origin/IOMAD_403_STABLE
   853d706d9dd..a56d8d371b3  IOMAD_401_STABLE -> origin/IOMAD_401_STABLE
   2be0d12a9b3..c704b8d1a50  IOMAD_402_STABLE -> origin/IOMAD_402_STABLE
 * [new branch]              IOMAD_404_STABLE -> origin/IOMAD_404_STABLE
Updating d14059c4217..9cc7e7a2a59
Fast-forward
 admin/tool/lp/classes/external.php                                 |  36 +++++-
 auth/iomadoidc/classes/iomadoidcclient.php                         |   2 +-
 auth/iomadoidc/classes/loginflow/base.php                          |  33 ++++--
 blocks/iomad_approve_access/approve.php                            |   6 +-
 blocks/iomad_approve_access/lang/en/block_iomad_approve_access.php |   4 +
 blocks/iomad_company_admin/block_iomad_company_admin.php           |   6 +-
 blocks/iomad_company_admin/classes/forms/company_courses_form.php  |  93 +++-------------
 blocks/iomad_company_admin/classes/forms/company_edit_form.php     |   2 +-
 blocks/iomad_company_admin/classes/forms/company_managers_form.php |   4 +
 blocks/iomad_company_admin/classes/forms/department_edit_form.php  |   2 +-
 blocks/iomad_company_admin/classes/forms/user_edit_form.php        |  12 ++
 blocks/iomad_company_admin/classes/tables/editusers_table.php      |   4 +-
 blocks/iomad_company_admin/classes/tables/iomad_courses_table.php  | 155 +++++++++++++++++++++-----
 blocks/iomad_company_admin/company_user_create_form.php            |  38 ++++---
 blocks/iomad_company_admin/db/access.php                           |  11 +-
 blocks/iomad_company_admin/db/iomadmenu.php                        |   2 +-
 blocks/iomad_company_admin/db/upgrade.php                          |  57 ++++++++++
 blocks/iomad_company_admin/editcompanies.php                       |  39 ++++---
 blocks/iomad_company_admin/editusers.php                           |  22 ++--
 blocks/iomad_company_admin/iomad_courses_form.php                  |   2 +-
 blocks/iomad_company_admin/lang/en/block_iomad_company_admin.php   |   9 +-
 blocks/iomad_company_admin/lib/course_selectors.php                |   4 +-
 blocks/iomad_company_admin/version.php                             |   2 +-
 blocks/iomad_microlearning/groups.php                              |  10 +-
 blocks/iomad_microlearning/lang/en/block_iomad_microlearning.php   |   2 +
 enrol/index.php                                                    |   5 +
 lib/filelib.php                                                    |   5 +-
 local/course_selector/lib.php                                      |   5 +-
 local/email_reports/classes/task/company_license_expiring_task.php |   2 +-
 local/email_reports/classes/task/course_expiry_warning_task.php    |   1 +
 local/iomad/classes/task/cron_task.php                             |   6 +-
 local/iomad/lib/company.php                                        | 160 +++++++++++++++++++-------
 local/iomad/lib/iomad.php                                          |  31 +++---
 local/iomad/lib/user.php                                           |  36 ++++--
 local/iomad_track/classes/privacy/provider.php                     |   2 +-
 local/iomad_track/import.php                                       |   4 +-
 local/report_completion/classes/tables/course_table.php            | 407 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-------
 local/report_completion/classes/tables/user_table.php              |   4 -
 local/report_completion/index.php                                  | 104 +++++++++++------
 local/report_completion/lang/en/local_report_completion.php        |   2 +
 local/report_completion/styles.css                                 |   7 ++
 local/report_users/classes/forms/add_entry_form.php                |   4 +-
 local/report_users/classes/tables/completion_table.php             |   4 -
 local/report_users/userdisplay.php                                 |   9 +-
 login/index.php                                                    |  35 ++++--
 mod/trainingevent/view.php                                         |   9 +-
 search/classes/manager.php                                         |  19 ++++
 47 files changed, 1068 insertions(+), 350 deletions(-)
domain@sandbox:/var/www/vhosts/sandbox.domain.ca/iomad$ sudo -u www-data php admin/cli/maintenance.php --disable
== Maintenance mode (https://sandbox.domain.ca) ==
Maintenance mode has been disabled and the site is running normally again
`

After the maint disable on the cli, i was able to complete the database upgrade, but it looks like the flag didn't get cleared?  This was trying to view the root url after the upgrade completed on the web-interface

```
Error
Site is being upgraded, please retry later.
Debug info:
Error code: upgraderunning
Stack trace:
line 744 of /lib/setup.php: moodle_exception thrown
line 29 of /config.php: call to require_once()
line 6 of /admin/upgradesettings.php: call to require_once()
```

I tried a reset --hard and enable/disable on the cli in case the git pull missed something.

`sudo -u www-data git reset --hard 9cc7e7a2a5906e414ae2e164d96e35dbbf98d0e8
HEAD is now at 9cc7e7a2a59 IOMAD: messed up the vars again. #2097
domain@sandbox:/var/www/vhosts/sandbox.domain.ca/iomad$ sudo -u www-data php admin/cli/maintenance.php --enable
!!! Site is being upgraded, please retry later. !!!

Debug info:
Error code: upgraderunning
Stack trace: * line 744 of /lib/setup.php: moodle_exception thrown
* line 29 of /config.php: call to require_once()
* line 28 of /admin/cli/maintenance.php: call to require()
domain@sandbox:/var/www/vhosts/sandbox.domain.ca/iomad$ sudo -u www-data php admin/cli/maintenance.php --disable
!!! Site is being upgraded, please retry later. !!!

Debug info:
Error code: upgraderunning
Stack trace: * line 744 of /lib/setup.php: moodle_exception thrown
* line 29 of /config.php: call to require_once()
* line 28 of /admin/cli/maintenance.php: call to require()
domain@sandbox:/var/www/vhosts/sandbox.domain.ca/iomad$
`

Seems to be stuck.  not a showstopper for me now since it's a sandbox and I can restore from a backup, but could affect other users on a production system upgrade?

**Comment by turf212** [comment]
What happens when you run
php admin/cli/upgrade.php

??

**Comment by dallenk** [comment]
update:  i waited 10-15 mins doing some extra trouble shooting, then refreshed the page while watching the Apache logs, it re-ran the database upgrade on the webpage and then completed without issue.  will try again from a 402 backup, and upgrade to 403.

perhaps it needed a cron to complete first?

**Comment by turf212** [comment]
Definitely weird - all of the steps in that worked without issue in my local 4.3 branch.  I'll try a 4.1 ->4.3 upgrade too tomorrow.

**Comment by turf212** [comment]
Tested this with an upgrade from 4.1.15 to 4.3.9 and all went through without issue.
