### ISSUE TITLE
4.4.5 stable - Throwing deprecated errors

### ISSUE THREAD

**Issue by IamRobinJoseph** [iomad/iomad#2107]
This shows in all course pages

Deprecated: Creation of dynamic property block_iomad_company_admin\forms\course_edit_form::$editoroptions is deprecated in /var/www/html/iomad/blocks/iomad_company_admin/classes/forms/course_edit_form.php on line 48

Deprecated: Creation of dynamic property block_iomad_company_admin\forms\course_edit_form::$companyrec is deprecated in /var/www/html/iomad/blocks/iomad_company_admin/classes/forms/course_edit_form.php on line 49

Deprecated: Creation of dynamic property block_iomad_company_admin\form is\course_edit_form::$companycontext is deprecated in /var/www/html/iomad/blocks/iomad_company_admin/classes/forms/course_edit_form.php on line 50

**Comment by turf212** [comment]
Can I check what version of PHP you are using?  I'm not seeing those errors on 8.1.
