### ISSUE TITLE
Missing fields on Company creation

### ISSUE THREAD

**Issue by jalapatas** [iomad/iomad#2112]
Since the installation of IOMAD_403 by editing a company, the option "Contract end date" & "Treminate after" are no longer available.

![image](https://github.com/user-attachments/assets/0b1fa075-5874-4bcf-939e-7e971ede6636)

However, these fields can still be found in the database: "validto" & "suspendafter".
Is this an error or was it done on purpose? Thanks in advance.

**Comment by turf212** [comment]
These fields shouldn't be getting changed by the company manager so were put behind a new capability.  Looks like some test logic was left in that check.
