### ISSUE TITLE
Deleting Users does not unallocate courses (if appliciable) before deleting.

### ISSUE THREAD

**Issue by BananaRama203** [iomad/iomad#217]
Not really a issue but more a logic issue and related to issue #216. When deleting a user which has courses with a isuing of 0 still on account. The units should be added back to company's active license. 

OR

Add a check. If User has courses WHERE isusing = 0 then ALERT("This user still has unused courses. If you do not unallocate these courses before you delete this user these units will be lost") OK Cancel etc.

**Comment by turf212** [comment]
I'm going to merge this one with #216 as it should be getting picked up in the same code.

**Comment by thepurpleblob** [comment]
Hi,
I know you were looking for this, I found this stuff for you, take a look at http://advantage.jonpoulter.com/e4tryeyp

Bests, howard@e-learndesign.co.uk
