### ISSUE TITLE
Sorting by column only works for page 1. When you using paging bar sorting disappears.

### ISSUE THREAD

**Issue by BananaRama203** [iomad/iomad#218]
Sorting by column only works for page 1. It will sort acceding or descending for the whole data capture just on page 1, when you click on a different page using the paging bar the sort is lost.

**Comment by BananaRama203** [comment]
Apologises, forgot to mention this is a global IOMAD bug.

**Comment by turf212** [comment]
I've checked this on the course_completion report and the license report.  Can you please tell me which pages you are seeing this on (as it's not a global function but distinct on each page)

**Comment by BananaRama203** [comment]
Edit Users
