### ISSUE TITLE
Sortorder displays when adding new user

### ISSUE THREAD

**Issue by markward** [iomad/iomad#219]
When adding a new user to an organisation via the IOMAD company administration block it is possible to select courses which the new user should be enrolled onto.

![Available Courses when adding new user](http://i.imgur.com/2klVxau.png)

Since the course selector __construct method is setting "sortorder" as an extra field to be sorted by the sortorder column is returned as part of the data and displayed to the user.

**Comment by turf212** [comment]
Thanks for this it was merged in to core.
