### ISSUE TITLE
New shibboleth user gets created in moodle, but not assigned to company

### ISSUE THREAD

**Issue by matejzero** [iomad/iomad#221]
Hello!

As Martin already wrote yesterday, we are having troubles with the latest 2.7 version from git. We did a fresh reinstall of IOMAD, set up Shibboleth and login with shibboleth user.

Upon pressing login, error page pops up saying:

```
Sorry, but you do not currently have permissions to do that (Change site configuration)

More information about this error(http://docs.moodle.org/27/en/error/moodle/nopermissions)

Debug info: 
Error code: nopermissions
Stack trace:
line 786 of /lib/accesslib.php: required_capability_exception thrown
line 517 of /admin/index.php: call to require_capability()
```

I can see user gets created in moodle (I can see user under Site administration -> Users), but it isn't assigned to a company.

To test, you can use the same users/passwords as the last time. You can also login with your own user/pass as the site admin.

Matej

**Comment by turf212** [comment]
This was addressed in the clients code and brought into core.
