### ISSUE TITLE
V 28 simply will not install

### ISSUE THREAD

**Issue by nick69g** [iomad/iomad#222]
Today I have set up server space to instal a fresh version of 28.

I've tried it twice and it shows the Moodle files to install and then does absolutely nothing. Check out http://94.229.166.97/~portal/admin/index.php to see what I mean.

I've done exactly the same instal with 27 and it works absolutely fine. I've installed 27 twice without any problems and tries 28 twice and it just delivers a blank screen.

We really want to use IOMAD but it appears to be plagued with bugs.

**Comment by nick69g** [comment]
http://94.229.166.97/~portal/admin/index.php
Click Continue to get the first screen, Continue to the next screen and then try Continue again - does Moodle install or do you get a blank screen?

**Comment by turf212** [comment]
looks like there were a couple of typos merged in.  I'm just checking a fix for it now.

**Comment by nick69g** [comment]
Thanks - much appreciate the update.

Nick

[cid:F1DEACBF-81E7-4069-ADDE-0C6CBF886064]
Nick Garrod MCIPD
eLearning Development Manager

nick.garrod@cloudsustainability.commailto:nick.garrod@cloudsustainability.com
T. 0845 287 3850 DD. 0203 102 6948
M. +44 (0)7712 331 789 Skype ID. nickg69
www.cloudsustainability.comhttp://www.cloudsustainability.com/

[cid:76C0EB5E-A2DD-4B91-9F36-035CB3EE5C5B] @CloudPioneerhttp://twitter.com/cloudpioneer

[cid:6F153531-DC7D-4334-91CA-24CF232733F2]
The information contained in this e-mail is for the exclusive use of the intended recipient(s), or person responsible for delivering this information to the intended recipient, and may be confidential, proprietary, and/or legally privileged. Inadvertent disclosure of this message does not constitute a waiver of any privilege. If you receive this message in error, please do not directly or indirectly use, print, copy, forward, or disclose any part of it. Please immediately delete the e-mail plus all copies and notify the sender or call 0845 287 3850.
Cloud Sustainability Limited makes reasonable attempts to exclude any virus, or any other defect which might affect any computer or IT system, from this e-mail and any attachments but it is the responsibility of the recipient to ensure that they are virus free and we accept no liability for any loss or damage arising in any way from their receipt or use.
Cloud Sustainability Limited is registered in England, company no. 06863577, registered address Leeds Innovation Centre, 103 Clarendon Road, Leeds, LS2 9DF.

Please think about the environment before printing this e-mail.

**Comment by turf212** [comment]
I've fixed and tested this and pushed to the Git repository.  This also includes the latest Moodle 2.x patches for each branch.

**Comment by nick69g** [comment]
Excellent - thanks.

Nick

[cid:E02031B4-FEFA-458A-8B6D-0FBE09779DCE]
Nick Garrod MCIPD
eLearning Development Manager

nick.garrod@cloudsustainability.commailto:nick.garrod@cloudsustainability.com
T. 0845 287 3850 DD. 0203 102 6948
M. +44 (0)7712 331 789 Skype ID. nickg69
www.cloudsustainability.comhttp://www.cloudsustainability.com/

[cid:BFC60C65-A7E8-40F3-BC2A-9C5D3145F68A] @CloudPioneerhttp://twitter.com/cloudpioneer

[cid:44B5A27A-E5B4-415A-B577-438941B90414]
The information contained in this e-mail is for the exclusive use of the intended recipient(s), or person responsible for delivering this information to the intended recipient, and may be confidential, proprietary, and/or legally privileged. Inadvertent disclosure of this message does not constitute a waiver of any privilege. If you receive this message in error, please do not directly or indirectly use, print, copy, forward, or disclose any part of it. Please immediately delete the e-mail plus all copies and notify the sender or call 0845 287 3850.
Cloud Sustainability Limited makes reasonable attempts to exclude any virus, or any other defect which might affect any computer or IT system, from this e-mail and any attachments but it is the responsibility of the recipient to ensure that they are virus free and we accept no liability for any loss or damage arising in any way from their receipt or use.
Cloud Sustainability Limited is registered in England, company no. 06863577, registered address Leeds Innovation Centre, 103 Clarendon Road, Leeds, LS2 9DF.

Please think about the environment before printing this e-mail.
