### ISSUE TITLE
typo in license_report CSV export

### ISSUE THREAD

**Issue by BananaRama203** [iomad/iomad#227]
Last access shows blank space code in the csv:

Sunday, 15 June 2014, 12:00 AM&nbsp; (317 days 12 hours)

However I changed the last allocation date to:

format_time(time() - $user->issuedate)." ago");

which solves this issue and looks less cluttered.

**Comment by turf212** [comment]
Which line/file did you change?  Also, best to use the get_string() functions for displayed words.  Ago may make sense in English but not in other languages.

**Comment by turf212** [comment]
This was addressed in the clients code and brought into core.
