### ISSUE TITLE
Report Completion In Progress not working

### ISSUE THREAD

**Issue by BananaRama203** [iomad/iomad#228]
When using the completion report the tables and csv show 0 for in progress even though there should be people in progress.

I.e. the chart displays approx 20 users in progress however the table or the csv displays 0 in progress.

Basically the report isn't echo'ing IN PROGRESS

**Comment by turf212** [comment]
Can you give me an example for this?  Has been a data issue and is now fixed?

**Comment by RyanHamlin1234** [comment]
I will get some evidence and collate

**Comment by turf212** [comment]
This has been addressed in the clients code and brought into core.
