### ISSUE TITLE
Change userdate()  and date('d M Y') to date('jS M Y') 

### ISSUE THREAD

**Issue by BananaRama203** [iomad/iomad#230]
At the moment there is an inconsistent method of echo'ing dates in IOMAD. Some places use the Moodles API userdate() or date('d M Y') for consistency sakes can we find and replace and use date('jS M Y') 

i.e. 

8th May 2013

**Comment by turf212** [comment]
I would actually prefer to use one of the standard time stamps such as UTC.   I believe the reason for asking this is to allow for sorts on the date column of the CSV export.  This would make more sense.

**Comment by turf212** [comment]
Dates have been changed to be of the format 2015-05-28

**Comment by thepurpleblob** [comment]
Hello,

Here are some very important news for you,  please read that information http://aim.photoshopforkids.com/e4axqyfy

Wishes, howard@e-learndesign.co.uk
