### ISSUE TITLE
License Report Permission Issue

### ISSUE THREAD

**Issue by BananaRama203** [iomad/iomad#231]
// Get the appropriate list of departments.
if (!(iomad::has_capability('block/iomad_company_admin:editusers', $context) or
      iomad::has_capability('block/iomad_company_admin:editallusers', $context))) {
    print_error('nopermissions', 'error', '', 'report on users');
}

The following statement causes the report to error out if you are using a user with View Only Access. As I can tell I don't believe you need this statement but with this statement in the code it will prevent VOA users from using this report.

**Comment by turf212** [comment]
The view only capability is something you added?  I can't see any other code for this in core.

**Comment by RyanHamlin1234** [comment]
Yeah but essentially it is just a repurposed Company Department Manager with View only permissions with no Edit permissions.

Across Iomad there are various REQUIRE BLAH EDIT. Which is a issue if you want view only accounts as you want them to view but not edit.

One can only assume this was to save time as there was no real point making two permissions i.e. (edit blah and view blah) but moving forward permissions should be coded in the sense of two permissions when checking if the user can view it or if they can edit data

**Comment by turf212** [comment]
This has been addressed in previous versions.
