### ISSUE TITLE
Cannot assign license to user for single course licenses

### ISSUE THREAD

**Issue by ehuggett** [iomad/iomad#235]
Hi,

When a license only has a single course managers cannot assign users to this course using "User license allocations" ("/blocks/iomad_company_admin/company_license_users_form.php")

The error (when attempting to use a license) is

```
optional_param_array() expects array parameters only: courses
line 679 of /lib/moodlelib.php: call to debugging()
line 296 of /blocks/iomad_company_admin/company_license_users_form.php: call to optional_param_array()
```

In company_license_users_form.php I would suggest removing the conditional around line 142. This will change

```
if (count($this->courseselect) > 1 ) {
        $courseselector->setMultiple(true);
}
```

to

```
$courseselector->setMultiple(true);
```

So that the "Available Courses" option will always use a multi-select list (and as such, always return an array) instead of a drop-down single option select list.

Changing the server-side validation to accept an integer or an array may also be an option.

**Comment by turf212** [comment]
Fixed in commit commit d86be484ec82f832788ad2c4495ae1fec0471b9d
