### ISSUE TITLE
Add Company Image In Email Template

### ISSUE THREAD

**Issue by nishantpandya** [iomad/iomad#247]
There is a nice facility in IOMAD that as per company we can update the email templates from IOMAD -> Course Management -> Email Templates.

If we want to send the email from one company manager of one company so they can change content as per there requirement.

Now I want to add the Image on the email template. So when admin / company manager create there employee then they will get there company logo on email.

How can I do this. Please help.
Thanks
Nishant

**Comment by nishantpandya** [comment]
I am not getting any reply yet. This is very slow forum. I know IOMAD is new but I dont think that no one can active in this forum. Anybody is there who can solve the issues. There are lots of issues are there in IOMAD.

**Comment by turf212** [comment]
This isn't a help forum, it's a bug forum for issues.  At the moment Iomad only handles plain text emails so this isn't possible.  If you would like to develop this yourself and filter back to us, or would like to pay for this new feature then we would be happy to discuss.

**Comment by nishantpandya** [comment]
Thanks for reply turf. I have implement this by custom coding.
Thanks
