### ISSUE TITLE
How to create Course of type Lesson on IOMAD 2.5 ?

### ISSUE THREAD

**Issue by nishantpandya** [iomad/iomad#248]
I am using IOMAD 2.5.
I want to create a course of type Lesson (moodle have option to select Single Activity & then got option to create Lesson). I know that we can create Lesson using Add Activity but I want to create a course of type Lesson.
How can I create course of type Lesson ? Please help. Thanks.

**Comment by turf212** [comment]
Hi.  You would do this in exactly the same way as you would create a single activity course in Moodle.  The iomad dashboard will not handle it directly, but you can change the course layout to be whatever you want by editing the course settings once it's created.  This part of the system is Moodle.  Iomad is the multi-tenancy part on top.
