### ISSUE TITLE
open shared courses

### ISSUE THREAD

**Issue by alexbls** [iomad/iomad#249]
Hi,
I've recently installed iomad 2.8 for evaluation, to see if it can help with the following use case:
We need our customers to be able to do one of 2 things: 1) a customer student can enroll to one of the courses we provide, after paying for it themselves using a credit card, or 2) a customer manager can purchase a group of licenses for a set of courses that they can later allocate to their student to join. In either flow, all users should be able to see all course descriptions listed on the frontpage but the course content should obviously be seen by then only after they pay. And we ideally want our customers to be as self-sufficient as possible in handling their own payments and enrollments.

I may not be familiar enough with iomad and I couldn't find much documentation on how to set up things, but is the above possible? 

What I've done so far, which doesn't seem to produce the expected results, is setting up a company called 'general', under it setting up 3 sub-categories (analyst, admin and developer - these are the categories for our courses), and under each sub-category I have the courses themselves. Then each of these courses is set as 'open shared' and 'licensed', and I also have under 'e-commerce' the licenses for these courses. I was expecting that all users (those assigned to company 'general' and those assigned to other companies) would see the courses listed on the frontpage, and be able to shop for them - but that's not what I see. Users from other companies only see the 'miscellaneous' category showing, but none of the open shared courses.

Also not clear to me how to set it up so that students can purchase their own courses (the first flow above). I think by design a student cannot do any shopping, it needs to be a company manager role?

Thanks
Alex

**Comment by turf212** [comment]
Hi Alex, yes, its designed that licenses be bought by company managers.  Courses are hidden in general as, for the most part, you only want the courses available to the company to be seen by the company and not outside of that.  In saying that, open shared courses should be visible to every company user.  Work was done on this in he 3.0 version which allows for users to search courses and this view of the course catalog being more appropriate.

It may be that what you are looking for is better served by hooking an eCommerce system (such as Woo Commerce) to a standard Moodle site.  If you don't need the actual companies for something else, it's likely over kill.
