### ISSUE TITLE
Training event always shows "This training event is no longer available"

### ISSUE THREAD

**Issue by thepurpleblob** [iomad/iomad#25]
A training event activity always says "This training event is no longer available" regardless of the settings of the start and end time.

**Comment by turf212** [comment]
How did you generate this?  I haven't been able to reproduce it.

**Comment by thepurpleblob** [comment]
I couldn't get it to do anything else. Knowing me it's because I was missing some data. I'd just sparked up the site, added a company, added a course and added an event. Displaying the event only showed this 'error'. I did look at the logic for the buttons but struggled to follow it.

**Comment by turf212** [comment]
Wonder if its down to not having any users in the company.  I'll have a play and see.  Will be an edge condition knowing me....

**Comment by turf212** [comment]
I've just tested that with no users.  May have been something to do with another bug which has fixed it.  Could you please pull the latest code and check?

**Comment by thepurpleblob** [comment]
Just tried again and exactly the same.
