### ISSUE TITLE
Iomad user create form fails when licenses are available but not selected

### ISSUE THREAD

**Issue by thepurpleblob** [iomad/iomad#251]
When creating a user for a company with licenses the form produces a Fatal error if no license is accepted. There should be no requirement to select a license. The user appears to be created anyway

 Notice: Undefined property: stdClass::$licensecourses in /Library/WebServer/Documents/iomad28/blocks/iomad_company_admin/company_user_create_form.php on line 323

**Comment by turf212** [comment]
Fixed in 3.0
