### ISSUE TITLE
Should be easier to change course enrolment option

### ISSUE THREAD

**Issue by thepurpleblob** [iomad/iomad#252]
When creating an Iomad course you have the option to select 'How do users enrol on the course'. However, once the course is created it is not (easily) possible to change this setting. Ideally, this setting should be properly reflected on the 'Manage Iomad course settings page'

**Comment by turf212** [comment]
It already covers the license and manual options, just not the self enrolment.  (setting the course to license will turn on the license option and all the other options off.  Setting the course back to manual will turn on Manual only and turn off license enrolment).

The course management page should like all be ajaxed up anyway.
