### ISSUE TITLE
License enrolment plugin throws notice for edit form

### ISSUE THREAD

**Issue by thepurpleblob** [iomad/iomad#255]
When viewing the edit setting form for a License enrolment plugin (via Enrolment methods in a course), the following notice is thrown...

Did you remember to call setType() for 'name'? Defaulting to PARAM_RAW cleaning.
line 1312 of /lib/formslib.php: call to debugging()
line 284 of /lib/formslib.php: call to moodleform->detectMissingSetType()
line 202 of /lib/formslib.php: call to moodleform->_process_submission()
line 62 of /enrol/license/edit.php: call to moodleform->moodleform()

It also shows the wrong edit icon (a pen rather than a gear) and the breadcrumb trail is incomplete.

**Comment by turf212** [comment]
Fixed in 3.0
