### ISSUE TITLE
Notice when creating new user

### ISSUE THREAD

**Issue by thepurpleblob** [iomad/iomad#258]
Created new user for new course for new company. Assigned to the course when creating the user. No licenses involved with this company...

Notice: Undefined variable: shared in /var/www/iomad28/local/iomad/lib/user.php on line 298

Analysis: In the function enrol() in the above file, the variable $shared is set to true or false with the depths of a loop. It possibly should be initialised outside the loop. However, a cursory glance would indicate that the code that sets it probably should be run so this may be surfacing some other problem.

**Comment by turf212** [comment]
Fixed in 3.0
