### ISSUE TITLE
User License Allocations does not show important information for company managers

### ISSUE THREAD

**Issue by ehuggett** [iomad/iomad#260]
Compare the two screen shots of the "User license allocations" tool below

This screen shot is taken from a Administrator account
![Image from site admin perspective](https://i.imgur.com/dTUk6EM.png)

This screen shot is taken from a Company Manager account
![Image from company manager perspective](https://i.imgur.com/rOls8TU.png)

The Company manager cannot see a number of important details, including
- The company department the user belongs to
- the email address of the user
- the name of the course the license has been allocated to (if the license is for multiple courses, without it its impossible to distinguish between licenses allocated to the same user for different courses)
- and the asterisk (*) which indicated if a license has been used

The last two are essential for a company manager to be able to use the tool.

All of the missing details seem to be appended/prepended into the "email" array element which does not seem to be used/present when viewed as a company admin (its not in the fields returned by $this->required_fields_sql anyway).

For example, these 4 lines append the course name to "email" (stored in "fullname") and the prepend the email with an asterisk if the license is in use.
https://github.com/iomad/iomad/blob/IOMAD_28_STABLE/blocks/iomad_company_admin/lib/user_selectors.php#L977-L980

I did put some effort into understanding why requied_fields_sql returns different fields for an Administrator vs Company Admin but had to move onto other tasks. for the time being I have chosen to append the course name to "lastname" and prepend "firstaname" with an asterisk if the license is in use.

**Comment by ehuggett** [comment]
@turf212 my changes still seem to work on 3.0

```
diff --git a/blocks/iomad_company_admin/lib/user_selectors.php b/blocks/iomad_company_admin/lib/user_selectors.php
index 4491851..bd9937a 100644
--- a/blocks/iomad_company_admin/lib/user_selectors.php
+++ b/blocks/iomad_company_admin/lib/user_selectors.php
@@ -974,9 +974,9 @@ class current_license_user_selector extends user_selector_base {
         }

         foreach ($availableusers as $id => $rawuser) {
-            $availableusers[$id]->email .= ' (' . $rawuser->fullname . ')';
+            $availableusers[$id]->lastname .= ' (' . $rawuser->fullname . ')';
             if (!empty($rawuser->isusing)) {
-                $availableusers[$id]->email = ' *' . $availableusers[$id]->email;
+                $availableusers[$id]->firstname = ' *' . $availableusers[$id]->email;
             }
         }
 //        $this->process_license_allocations($availableusers);
```

**Comment by turf212** [comment]
Added to 3.0
