### ISSUE TITLE
Company manager can see the other companies' categories

### ISSUE THREAD

**Issue by pm-tatiana** [iomad/iomad#266]
I have an issue with IOMAD. As far as I understand when creating a new company, this will create a category with the company name in moodle and will put that company's courses in there. 
my problem is that I don't want any other user (belonging to a specific company) to see the list of companies' categories listed, that includes the company managers of other "tenants"/companies.

I thought I could restrict that in block/iomad_company_admin:company_view but it doesn't work when I disbale this. The company manager still can see the categories of companies created in the lms.
any thought?

**Comment by turf212** [comment]
This is addressed in 3.0
