### ISSUE TITLE
Company logo display with other themes

### ISSUE THREAD

**Issue by nishantpandya** [iomad/iomad#268]
I am working on IOMAD 2.7 version.
I have created some company with there logo. And when I am going to login using any of the company user, after login I have seen the company logo. One more thing I have seen that while uploading company logo image there is a note i.e. NOTE: The options below will only work with the "Iomad" theme.
So my question is that is is possible to do same with any other themes. Actually IOMAD theme UI is not much better & when I try to use another theme, company logo is hidden from there & I need to use another theme.
Please help. Thanks.

**Comment by nishantpandya** [comment]
Please help me guys !!

**Comment by nick69g** [comment]
I think the logo option only works on the IOMAD theme - which is not the 
most attractive I know!

**Comment by nishantpandya** [comment]
Thanks for reply. I think I need to do it custom for new theme. Actually I have check but some functions are there & I have try to understand but facing problem in understanding code.

**Comment by ehuggett** [comment]
i was able to add the company logo to the iomad bootstrap theme by adding a _pluginfile function to the theme (copied & pasted out of the iomad theme, I'm only saying this works... not that its a good idea to do).

```
diff --git a/theme/iomadbootstrap/lib.php b/theme/iomadbootstrap/lib.php
index e77ac5e..3652e8b 100755
--- a/theme/iomadbootstrap/lib.php
+++ b/theme/iomadbootstrap/lib.php
@@ -188,3 +188,29 @@ function theme_iomadbootstrap_brand_font_link($settings) {
     return '<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family='
             .$fontname.':'.$fontweight.$fontitalic.'&amp;text='.$text.'">';
 }
+
+/**
+ * Serves any files associated with the theme settings.
+ *
+ * @param stdClass $course
+ * @param stdClass $cm
+ * @param context $context
+ * @param string $filearea  
+ * @param array $args
+ * @param bool $forcedownload
+ * @param array $options
+ * @return bool
+ */
+function theme_iomadbootstrap_pluginfile($course, $cm, $context, $filearea, $args, $forcedownload, array $options = array()) {
+    if ($context->contextlevel == CONTEXT_SYSTEM and $filearea === 'logo') {
+        $theme = theme_config::load('clean');
+        // By default, theme files must be cache-able by both browsers and proxies.
+        if (!array_key_exists('cacheability', $options)) {
+            $options['cacheability'] = 'public';
+        }
+        return $theme->setting_file_serve('logo', $args, $forcedownload, $options);
+    } else {
+        send_file_not_found();
+    }
+}
+
```

**Comment by turf212** [comment]
Adding this issue to the 3.0 testing.

`/**
- Serves any files associated with the theme settings.
  *
- @param stdClass $course
- @param stdClass $cm
- @param context $context
- @param string $filearea  
- @param array $args
- @param bool $forcedownload
- @param array $options
- @return bool
  */
  function theme_iomadbootstrap_pluginfile($course, $cm, $context, $filearea, $args, $forcedownload, array $options = array()) {
  
  $fs = get_file_storage();
  $relativepath = implode('/', $args);
  $filename = $args[1];
  $itemid = $args[0];
  if ($filearea == 'logo') {
      $itemid = 0;
  }
  
  if (!$file = $fs->get_file($context->id, 'theme_iomadbootstrap', $filearea, $itemid, '/', $filename) or $file->is_directory()) {
      send_file_not_found();
  }
  
  send_stored_file($file, 0, 0, $forcedownload);
  }`

**Comment by turf212** [comment]
closed.  Added to 3.0
