### ISSUE TITLE
completion report doesn't work (doesn't show users)

### ISSUE THREAD

**Issue by thepurpleblob** [iomad/iomad#270]
From new installation...
- create a company, create a course, create a user, make the user a student in the course
- set up completion in the course and put in something for the user to complete. 
- the user completes the activity and make sure cron runs a few times. Check the completion status in mdl_course_completions
- Run the completion report with default values. The single course is shown
- Ask for the list of users for that course, the one user who completed the course is NOT shown :(

I've had a very good look at the SQL that generates this list and I've honestly got no idea how it is (supposed to) work.

**Comment by nick69g** [comment]
Did you ever get this sorted - I have the same "issue"?

**Comment by turf212** [comment]
The issue was with the course not having any grade information.  The join for the temporary table wasn't returning anything when there was no course grade item.  It only happened on courses which had nothing in them.  Still, fixed.
