### ISSUE TITLE
Missing strings for some iomad capabilities

### ISSUE THREAD

**Issue by thepurpleblob** [iomad/iomad#271]
Missing strings for the following throw warnings...

'iomad_company_admin:companymanagement_view' in 'block_iomad_company_admin'
'iomad_company_admin:coursemanagement_view' in 'block_iomad_company_admin'
'iomad_company_admin:licensemanagement_view' in 'block_iomad_company_admin'
'iomad_company_admin:usermanagement_view' in 'block_iomad_company_admin'

**Comment by turf212** [comment]
Fixed in 3.0
