### ISSUE TITLE
Company Manager/Training Manager assigned to wrong department

### ISSUE THREAD

**Issue by ehuggett** [iomad/iomad#274]
Using [Assign department users/managers](https://github.com/iomad/iomad/blob/IOMAD_28_STABLE/blocks/iomad_company_admin/company_managers_form.php)
# Steps to Reproduce
1. Create a company with a sub-department
2. Create some users, they will have the Company as their department and the role of user by default
3. select the sub-department you created in the "Department" drop down & "company manager" as the "Role to assign" and then click "Choose Department"
4. Select the user you wish to make a manager of the sub-department from the "potential managers" list and click "Add"
5. The form will re-load, but the displayed information has not changed. However, if you select the company (not the sub-department) in the Department drop down and click show department you will find that the user has been assigned the company manager role of the parent company instead of the sub-department.
# Observations
- this also happens when you attempt to assign the department training manager role
- If you assign the the account the "user" role in the sub-department and then assign them the manager role it seems to work as expected (they become a manager of the sub-department)
- the only changes to department information seem to take place on Lines [288 and 292](https://github.com/iomad/iomad/blob/IOMAD_28_STABLE/blocks/iomad_company_admin/company_managers_form.php#L288), neither of which will be executed as they are in the 'else' sections of the the if statements checking to see if we are assigning manager/training manager roles

**Comment by turf212** [comment]
Thanks for this.  Will check this and incorporate any fixes in 3.0 version.

**Comment by ehuggett** [comment]
```
diff --git a/blocks/iomad_company_admin/company_managers_form.php b/blocks/iomad_company_admin/company_managers_form.php
index dc132c0..e252504 100644
--- a/blocks/iomad_company_admin/company_managers_form.php
+++ b/blocks/iomad_company_admin/company_managers_form.php
@@ -170,6 +170,9 @@ class company_managers_form extends moodleform {
                             if ($userrecord = $DB->get_record('company_users',
                                                                    array('companyid' => $this->selectedcompany,
                                                                          'userid' => $adduser->id))) {
+
+                                if ($departmentid != $userrecord->departmentid) $userrecord->departmentid = $departmentid;
+
                                 if ($roletype == 1 && $userrecord->managertype == 0) {
                                     // Give them the company manager role.
                                     role_assign($companymanagerrole->id, $adduser->id, $this->context->id);
```

**Comment by turf212** [comment]
Thanks.  Added to code or 3.0
