### ISSUE TITLE
Iomad 29 - Allocating a license to a user when there is only one course throws an error

### ISSUE THREAD

**Issue by turf212** [iomad/iomad#278]
optional_param_array() expects an array.

User is not then given a license for the course.

**Comment by ehuggett** [comment]
I think I reported this in #235 ?

**Comment by turf212** [comment]
You did indeed.  I'll link and close them. :)

**Comment by turf212** [comment]
duplicate of #235 fixed by commit d86be484ec82f832788ad2c4495ae1fec0471b9d
