### ISSUE TITLE
Getting email notification by student when they enrol by admin for any course

### ISSUE THREAD

**Issue by nishantpandya** [iomad/iomad#286]
Hi guys !!
I am using IOMAD 2.7 version. How to send email notification to users who are enrolled by admin. Means currently manually enrol course by admin to any user or student. Student will not get any email notification.
Please help. How can I do this ?
Thanks,
Nishant

**Comment by nishantpandya** [comment]
Please help me guys. How student can get the notification that he is enrolled for any course.

How can I do this. Please help.

Thanks,
Nishant

**Comment by f00k** [comment]
@nishantpandya - You may want to see: Site Administrations > Plugins > Message outputs > Default message outputs

**Comment by nishantpandya** [comment]
Hi @f00k - It's a bug of moodle. I have post this issue on http://www.moodle.org & I got solution from custom coding. I have apply those changes & got successful solution.
URL : https://moodle.org/mod/forum/discuss.php?d=108292#p1285689

Thanks,
Nishant

**Comment by turf212** [comment]
closing.  Not Iomad.

**Comment by nishantpandya** [comment]
Turf are you made... That query is not related to IOMAD ? If you are not able to help anyone then what are you doing here.
