### ISSUE TITLE
Iomad: licenses are not getting marked as completed on course completion

### ISSUE THREAD

**Issue by turf212** [iomad/iomad#287]
A license assigned to a user is not being marked as completed when a user completes a course.  Only on expiry of enrolment time.  This means that it becomes difficult to re-assign a license to a user to allow them to re-take a course.

**Comment by nick69g** [comment]
Linked to this - if a license expires in its duration, how can you reassign or extend the license to a learner so that they can continue to access the course?

**Comment by turf212** [comment]
The original issues is now fixed in 3.0.  The other question is answered in #305
