### ISSUE TITLE
Create roles on IOMAD ?

### ISSUE THREAD

**Issue by nishantpandya** [iomad/iomad#292]
Hi guys !
I have seen that at the time of user creation I have seen a drop down i.e. Role to assign. But I have seen only 3 roles i.e. User, Department Training Manager, Company Manager. I want to create some more roles. I have option to create more roles from "Administration -> Site administration -> User -> Permissions -> Define Roles -> Add new Role" but role created from this option not display on IOMAD i.e. Role to assign.
How can I do this.
Please help me guys !!
Thanks,
Nishant

**Comment by nishantpandya** [comment]
Help me guys !! Is this forum not active. I had post some issues also but I am not getting any solution yet.

**Comment by nishantpandya** [comment]
Hey turf212. Please help me to solve this.
Thanks,
Nishant

**Comment by turf212** [comment]
The Iomad roles are set in the system to the ones which are already defined. If you add a new role at a site level then you need to use the Moodle tools to assign those roles.  You need to be careful that this does not impact on the rest the site/multi-tenancy, however.

**Comment by kirupalaksh** [comment]
Hi turf212,
I am facing the same issue, I have created a supervisor role  and it is displayes in iomad-signup plugin role assignments.
But when i create a new user from iomad dashboard i cant able to get supervisor role. Please help me. Thanks in advance, Kirupa
