### ISSUE TITLE
Version 2.8+ - Create New Training Event

### ISSUE THREAD

**Issue by dn0616** [iomad/iomad#295]
Whenever we create a new Training Event activity after upgrading to 2.8+ and 2.9+ we get the following error when attempting to access the event - 

block_iomad_company_management/invaliduserdepartment

**Comment by morfjord** [comment]
I have the same problem

**Comment by turf212** [comment]
This is being addressed in Version 3.0 which will be getting release real soon now.

**Comment by turf212** [comment]
This has been fixed in 3.0.  There was a lot of work done with the training events and the approval system for them.  You may want to upgrade :)
