### ISSUE TITLE
After removing permissions for License, License tab still displays.

### ISSUE THREAD

**Issue by nishantpandya** [iomad/iomad#296]
Hi,

I have removed all the permissions from admin section, but yet License tab is displayed. What is the issue is this ?

![screenshot-183 182 87 221 2015-11-16 12-14-10](https://cloud.githubusercontent.com/assets/13360449/11175742/9a0c5012-8c5b-11e5-93f9-c27e23765373.png)

![firefox_screenshot_2015-11-16t06-37-16 710z](https://cloud.githubusercontent.com/assets/13360449/11175746/a3c1c452-8c5b-11e5-8a08-9936cb5eb708.png)

Please help.

Thanks,
Nishant Pandya

**Comment by ehuggett** [comment]
The Capability checks on lines 64-78 of /blocks/iomad_company_admin/block_iomad_company_admin.php control shown/hidden tabs.

If you want to hide the tab, try the "block/iomad_company_admin:licensemanagement_view" capability.

**Comment by turf212** [comment]
closed
