### ISSUE TITLE
Bug when trying to allocate course license to users

### ISSUE THREAD

**Issue by george-stratis** [iomad/iomad#297]
In **/blocks/iomad_company_admin/company_license_users_form.php** at line **306**

`$selectedcourses = optional_param_array('courses', array(), PARAM_INT);`

This works only when there are more than one courses. When a single course exists (which is many times the case when an admin is setting up a new set of courses for a new company) the **optional_param_array** function will always return an empty array and therefore no users can be allocated (or unallocated).

When a single course exists then it should use **optional_param** instead.

**Comment by george-stratis** [comment]
The following code seems to work for me

```
$selectedcourses = optional_param_array('courses', array(), PARAM_INT);
if( empty($selectedcourses) ){
    $selectedcourses = optional_param('courses', array(), PARAM_INT);
}
```

**Comment by turf212** [comment]
Thanks for reporting this.  I'm testing the patch at the moment.

**Comment by turf212** [comment]
This has been added to the 3.0 branch and fixed there.

**Comment by thepurpleblob** [comment]
Hey,

Are you still lookinf for that stuff? I think I've just seen someething you may like, look http://balance.magicguitarist.com/e4heax

Faithfully, howard@e-learndesign.co.uk
