### ISSUE TITLE
Company specific Optional field not working like company specific ?

### ISSUE THREAD

**Issue by nishantpandya** [iomad/iomad#298]
Hi guys !
I am using iomad & working on optional field. Is optional field be company specific ?
Actually, I have created a company & also create a company admin. First from admin create a profile field of type dropdown for default profile field. I have found 1 category created with company creation. When company admin login to the system then it will  get only default drop down fields not there company fields. If company admin try to create more fields then company admin have only permision to create field on default field not on there company named field which was created with company creation.
Please help me guys !!

Thanks,
Nishant Pandya

**Comment by turf212** [comment]
Company specifi optional profile fields need to be created through the dashboard.  Anything created through the "standard" Moodle admin menu will cause a field which is common to all companies.

**Comment by ndalpe** [comment]
Hey @turf212 ,
Sorry to reopen a closed ticket. I just installed a fresh copy of IOMAD_34_STABLE and created 1 optional profile field in each company. Unfortunately, both field are present on student profile. I also check in the database and couldn't find any association of either field with a company. 

I created 2 companies, added an optional profile field to each of them. I created 2 students, assign 1 of the students in each company. Very simple setup and yet both fields are visible on each students profile (/user/edit.php?id=3&returnto=profile). All this through IOMAD Dashboard.

Is this the intended result?

Thank you for your help

**Comment by geoffreyvanwyk** [comment]
We have the same problem as @ndalpe but with IOMAD_36_STABLE. Please reopen this issue.

**Comment by shariffmohamed** [comment]
I made a temporary fix for this by editing the function in the file moodlefolder/user/profile/lib.php

The fix does not show the optional fields to users in other companies but if the field is marked as required then a user in another company will not be able to leave the Edit Profile page.

Just before the 
`$sql .= 'ORDER BY uic.sortorder ASC, uif.sortorder ASC ';`
I've added
`$sql .= 'WHERE uif.categoryid = "'.$USER->company->id.'"';`

Full function code:
```
function profile_get_user_fields_with_data($userid) {
    global $DB, $CFG, $USER;

    // Join any user info data present with each user info field for the user object.
    $sql = 'SELECT uif.*, uic.name AS categoryname ';
    if ($userid > 0) {
        $sql .= ', uind.id AS hasuserdata, uind.data, uind.dataformat ';
    }
    $sql .= 'FROM {user_info_field} uif ';
    $sql .= 'LEFT JOIN {user_info_category} uic ON uif.categoryid = uic.id ';
    if ($userid > 0) {
        $sql .= 'LEFT JOIN {user_info_data} uind ON uif.id = uind.fieldid AND uind.userid = :userid ';
    }
    $params = array('userid' => $userid);
    // IOMAD - Filter the categories
    if (!iomad::has_capability('block/iomad_company_admin:company_view_all', context_system::instance())) {
        $sql .= " AND (uif.categoryid IN (
                  SELECT c.profileid FROM {company} c JOIN {company_users} cu ON (c.id = cu.companyid AND cu.userid = :companyuserid))
                  OR uif.categoryid IN (
                  SELECT id FROM {user_info_category} WHERE id NOT IN (SELECT profileid from {company}))) ";
        $params['companyuserid'] = $userid;
    }
    $sql .= 'WHERE uif.categoryid = "'.$USER->company->id.'"';
    $sql .= 'ORDER BY uic.sortorder ASC, uif.sortorder ASC ';
    $fields = $DB->get_records_sql($sql, $params);
    $data = [];
    foreach ($fields as $field) {
        require_once($CFG->dirroot . '/user/profile/field/' . $field->datatype . '/field.class.php');
        $classname = 'profile_field_' . $field->datatype;
        $field->hasuserdata = !empty($field->hasuserdata);
        /** @var profile_field_base $fieldobject */
        $fieldobject = new $classname($field->id, $userid, $field);
        $fieldobject->set_category_name($field->categoryname);
        unset($field->categoryname);
        $data[] = $fieldobject;
    }
    return $data;
}
```
