### ISSUE TITLE
No data in reports

### ISSUE THREAD

**Issue by nick69g** [iomad/iomad#302]
In image "one" you can see that the courses show that a learner has completed them; however when I click onto the User summary as shown in image "two", I'm not getting any information as to who has completed the course.

Do you know why this is please?
![one](https://cloud.githubusercontent.com/assets/10756954/11715529/91e9a1c2-9f3a-11e5-9952-8efe0039403a.jpg)
![two](https://cloud.githubusercontent.com/assets/10756954/11715530/91ef041e-9f3a-11e5-881f-bc2ff1db0cc2.jpg)

**Comment by turf212** [comment]
without knowing the data behind this I can't comment.  I would always check the report in the course first (there is a completion report within the course which is hidden from manager as it breaks the multi-tenancy as it reports on everyone in a course).  It should give you an idea of why the other reports are not working.
