### ISSUE TITLE
Download as CSV file - error page

### ISSUE THREAD

**Issue by canyasa** [iomad/iomad#303]
Hi,
When I try to download csv file under reports (all of them) I am having a "This webpage is not available - ERR_INVALID_RESPONSE" error. Do you have any idea why?

PS: my moodle installed under D; drive and Mysql is under C: Is this cause the error?

Thank you!

**Comment by canyasa** [comment]
Here is the error "Fatal error: Class 'report_completion' not found in...\local\report_completion\index.php on line 418"

**Comment by ehuggett** [comment]
```
diff --git a/local/report_completion/index.php b/local/report_completion/index.php
index 29bcecf..ef01790 100644
--- a/local/report_completion/index.php
+++ b/local/report_completion/index.php
@@ -407,6 +407,7 @@ if (empty($dodownload) && empty($showchart)) {

 if (empty($charttype)) {
     if (!empty($courseid)) {
+       require_once($CFG->dirroot.'/local/report_completion/locallib.php');
         // Get the course completion information.
         if (empty($dodownload)) {
             if (empty($idlist['0'])) {
```

Temporary workaround, apply the patch above or manually add 

```
require_once($CFG->dirroot.'/local/report_completion/locallib.php');
```

to local/report_completion/index.php after "if (!empty($courseid)) {" on line 409

**Comment by canyasa** [comment]
THANKS!! now I can get the users list but when I click download as csv now having this error "Fatal error:  Class 'local_report_completion' not found in C:\xampp\htdocs\iomad\local\report_completion\index.php on line 430"

**Comment by canyasa** [comment]
Ok I just updated the index.php in Report_completion and everything works FINE, THANK YOU!! The problem was my version has different codes such as local_report_completion, I have no idea how did it happen but finally it works.

**Comment by ehuggett** [comment]
@turf212 this may also relevant to 3.0 release

**Comment by turf212** [comment]
Will check this out in final testing. Thanks :)
