### ISSUE TITLE
What Teaching location does in iomad & how to provide group training for company specific users

### ISSUE THREAD

**Issue by nishantpandya** [iomad/iomad#304]
Hi guys !!

I want to create a company specific Instructor Role. This role can create users, create location for group training, assign courses, provide training to enrolled users, after completion of training provide certificate.

There is a option in iomad i.e. Teaching Location. But how to use this I don't know. I have create a teaching location. But how can I enroll some company users to some specific courses for group training.

Please help.

Thanks,
Nishant Pandya

**Comment by turf212** [comment]
The training locations are used by the training event activity.  These can be added to courses and can be set to be approved or self sign up or signed up by a manager.  These have been refactored in the 3.0 release which should be out this week.

**Comment by nishantpandya** [comment]
Hey turf, I am asking about how to use. Please provide helpful links.

**Comment by pm-tatiana** [comment]
You know I am wondering the same! @nishantpandya were you able to figure it out?

**Comment by nishantpandya** [comment]
Hi @pm-paradiso, I have done this by creating custom Classroom module. There is no option provided by iomad that's why I have created a custom module to figure out this functionality.

**Comment by ken4ward** [comment]
@turf212 Thanks for the good work. You mentioned here you have created a custom classroom module, I'll wish you link me to where the module can be found. JUst started using IOMAD about 3 days ago. Please, guide me.
