### ISSUE TITLE
Extending an expired license

### ISSUE THREAD

**Issue by nick69g** [iomad/iomad#305]
There appears no way to extend a license that has expired. How is this done please?

The license expires so I then attempt to create a new license and assign it to a course/learner, however when I enter the course as the learner it tells me there is no valid license.

Can someone please explain how to extend a license.

**Comment by ehuggett** [comment]
Just to clear up some potential confusion, what do you mean by License?

There is what I call 'license groups', created by the site administrator but there is also the act of a Company manager assigning a 'license' to a staff member so that they may enrol themselves onto a course.

Both types of license can expire and I’m not sure which one is causing you trouble.

**Comment by nick69g** [comment]
Hello

Thanks for your reply.

I can create a license linked to a course and assign a date to it, the 
number of user licenses and duration (e.g. 10 days).

When the license date expires I can no longer assin any unspent licenses 
and that works fine as I can increase the date and then assign any extra 
licenses - that is all OK.

Now assuming you have acces to Course X through a license for 10 days. 
When those 10 days have lapsed you are no longer able to access the 
course as the license has expired - this works as expected. But how do 
you then extend the license if the learner needs extra days? I've tried 
to create a new license fore the same course and added the learner, but 
it still tells me the license is not valid as the system is still 
looking at the old license and not the new one I assume.

if you delete the old license completely then the new one works - but 
that is not ideal to do.

Any help please much appreciated!

Nick

**Comment by nick69g** [comment]
Any chance I can get a reply please?

**Comment by ehuggett** [comment]
Sorry nick69g

I started looking into this a month ago as it seemed like the sort of issue that might eventually affect me, unfortunately I have (and have had) plenty of issues that are already affecting me now that are taking up most of my time.

I think normally you would alter user enrolments for a course through "Course Administration -> Users -> Enrolled Users", users on the course through the "manual" enrolment method can have their enrolment period and other options changed in this way but the license enrolment method does not seem to provide the option to edit the enrolment period, nor does it seem to provide the ability to manually unenrol a user.

At this point, I'm not sure what options are available to you other than deleting the license (as you mentioned) or manually editing the database to change the expiry time of the original  enrolment .

You might be able to get away with changing the value of enrolenddate on the mdl_enrol table for the original license, not sure if that would have any side effects.

**Comment by nick69g** [comment]
Hi

Thanks - I might look into the database and amend it there - thanks for 
your response and help.

Nick

**Comment by ehuggett** [comment]
Interestingly, but of little help here, the wording in issue #287 seems to suggest that you would be able to enrol a user to take the course again once the expiry time has passed... but for some reason this does not seem to be true in your case.

**Comment by nick69g** [comment]
Oh OK thanks. I'll have a look.

**Comment by turf212** [comment]
The length of time a user has access to the course when they are using a license is set at the point in time that the license is used.  There isn't any UI method for extending this at the moment however the time is set in the mdl_user_enrolments table and you can update it there.

**Comment by nick69g** [comment]
Thanks. That's a great help.

Nick

---

Nick Garrod

e: nick.garrod@cloudsustainability.commailto:nick.garrod@cloudsustainability.com
m: 07712 331789
s: nickg69

This email has been sent from my iPhone so please excuse any typos!

On 4 Mar 2016, at 17:18, Derick Turner <notifications@github.com<mailto:notifications@github.com>> wrote:

The length of time a user has access to the course when they are using a license is set at the point in time that the license is used. There isn't any UI method for extending this at the moment however the time is set in the mdl_user_enrolments table and you can update it there.

##
