### ISSUE TITLE
"Upload users" process cannot be cancelled on preview page

### ISSUE THREAD

**Issue by ehuggett** [iomad/iomad#308]
When using the "Upload users" tool after uploading a CSV you are taken to a preview page with 10 (by default) records from your CSV shown.

On this page, if the user clicks cancel instead of the expected action they are taken to a 'success' page confirming that the users from their CSV file have been imported (and they actually have been imported).

**Comment by ehuggett** [comment]
I've had another quick look at this, a few notes for when I do again.

The action buttons (submit/cancel) are added to the form in definition_after_data() don't work as intended.

If add_action_buttons() is moved from definition_after_data() to definition() then the cancel button does work as intended... with the obvious caveat that some form elements are inserted AFTER the action buttons, such as the course selector (which can't be used with insertElementBefore() easily).

**Comment by turf212** [comment]
I'm adding a fix for this in 3.0 version.

**Comment by ehuggett** [comment]
The cancel button does now cancel the upload!

Thanks
