### ISSUE TITLE
Add Company Address field & Company Contact No. field in Company creation form ?

### ISSUE THREAD

**Issue by nishantpandya** [iomad/iomad#309]
Hi guys,

At the time of Company creation, I want some extra fields to take input of Company Address & Company Contact No. How to create a custom fileld in iomad company creation form & db.

Thanks,
Nishant

**Comment by nishantpandya** [comment]
Hey guys, anybody have any suggestion. Everytime when I have post any query in this forum. I had never got any single reply. Guys please help. It's related to IOMAD.

**Comment by nishantpandya** [comment]
Hey guys, what is this. I have spend whole 1 day & yet not getting any single reply.

**Comment by nick69g** [comment]
IOMAD is free and unless you want to spend £ to get them to sort out the 
bugs and issues, then the support you receive will be very limited.

**Comment by nishantpandya** [comment]
Means if this forum is free, then no one can help if I will not pay. Is this a way of IOMAD forum ?

**Comment by nick69g** [comment]
IOMAD is a distribution of Moodle which is free. Using the support forum 
is free. However you get very little support unless you are prepared to 
pay for it - this is how the company makes its money. Been there, done 
that...

**Comment by nishantpandya** [comment]
First time I have listen that "how the company makes its money". Means company makes money from forum. Great nick69g. I had worked on drupal also. But I have never got any response like you. On drupal forum everyone is ready to help at every time. Great. 

Thanks for nice response.

**Comment by nick69g** [comment]
I don't work for the company. I am a user like you. We've had bugs and 
issues with IOMAD and whilst we got limited support via email, it really 
has to be paid for. Try and give them a ring and see what they offer you.

**Comment by nishantpandya** [comment]
Ok thanks. Sorry nick69g, actually I am totally frustrated using IOMAD. I got very less issues with moodle. But in IOMAD getting lots issues. Ok Ill try to use paid support.

Thanks & once again sorry for my bad language.

**Comment by nick69g** [comment]
No worries - I've had moments of frustrations ith it too (still do have!)
