### ISSUE TITLE
User report - temporary table already exists + workaround

### ISSUE THREAD

**Issue by ehuggett** [iomad/iomad#311]
N.B I'm full of the cold and cannot think straight!

The user report uses time() to make a temporary tables name 'unique' , however, time only has a resolution of one second so if it runs twice within one second the value will not be unique and causes the following error.

I ran into this while modifying the report to show courses for which the user has a license but has not yet enrolled (patch included for reference) but i'm pretty sure this error could occur without my modifications (ie on a really fast server or if two different managers run a report in the same second etc).

The error message from moodle

```
Report information for test user 3 (testing3@testing.local)

Table "tmp_ccomp_comp_1457616490" already exists

More information about this error

Debug info: 
Error code: ddltablealreadyexists

Stack trace: 

    line 448 of /lib/ddl/database_manager.php: ddl_exception thrown
    line 186 of /local/report_users/lib.php: call to database_manager->create_temp_table()
    line 46 of /local/report_users/lib.php: call to userrep::populate_temporary_completion()
    line 164 of /local/report_users/userdisplay.php: call to userrep::get_completion()
```

The change I made to work around the problem (uniqid has a resolution of microseconds, its doesn’t actually guarantee a unique value... ). I wouldn't call this a fix as all it does is (significantly) reduce the likelihood of non-unique temporary table names. There is probably a better way of handling the temporary table name, possibly some functions from moodle? 

```
diff --git a/local/report_users/lib.php b/local/report_users/lib.php
index 5d88ebd..29313ca 100644
--- a/local/report_users/lib.php
+++ b/local/report_users/lib.php
@@ -40,7 +40,7 @@ class userrep {
         $info = new completion_info( $course );

         // Set up the temporary table for all the completion information to go into.
-        $tempcomptablename = 'tmp_ccomp_comp_'.time();
+        $tempcomptablename = 'tmp_ccomp_comp_'.uniqid();

         // Populate the temporary completion table.
         list($compdbman, $comptable) = self::populate_temporary_completion($tempcomptablename, $userid, $courseid, $showhistoric);
```

there where also some missing language strings

```
diff --git a/local/report_users/lang/en/local_report_users.php b/local/report_users/lang/en/local_report_users.php
index fe97a41..8e94cfe 100644
--- a/local/report_users/lang/en/local_report_users.php
+++ b/local/report_users/lang/en/local_report_users.php
@@ -42,3 +42,5 @@ $string['user_detail_title'] = 'User reports';
 $string['usercoursedetails'] = 'User details';
 $string['userdetails'] = 'Report information for ';
 $string['viewfullcourse'] = 'View complete summary for course';
+$string['actions'] = 'Actions';
+$string['delete'] = 'Delete';
```

The changes I had made that reliably cause the error (the user was enrolled into 3 courses but licensed for 13).

```
diff --git a/local/report_users/userdisplay.php b/local/report_users/userdisplay.php
index 7667478..845a78a 100644
--- a/local/report_users/userdisplay.php
+++ b/local/report_users/userdisplay.php
@@ -69,6 +69,8 @@ if (empty($dodownload)) {
 $enrolcourses = enrol_get_users_courses($userid, true, null, 'visible DESC, sortorder ASC');
 $completioncourses = $DB->get_records_sql("SELECT courseid as id FROM {local_iomad_track} 
                                            WHERE userid = :userid", array('userid' => $userid));
+$licensecourses = $DB->get_records_sql("SELECT licensecourseid as id FROM {companylicense_users} WHERE userid = :userid", array('userid' => $userid));
+
 $usercourses = array();
 foreach ($enrolcourses as $enrolcourse) {
     $usercourses[$enrolcourse->id] = $enrolcourse;
@@ -77,6 +79,10 @@ foreach ($completioncourses as $completioncourse) {
     $usercourses[$completioncourse->id] = $completioncourse;
 }

+foreach ($licensecourses as $licensecourse) {
+       $usercourses[$licensecourse->id] = $licensecourse;
+}
+
 // Get the Users details.
 $userinfo = $DB->get_record('user', array('id' => $userid));
```

**Comment by turf212** [comment]
It is actually used in a number of places.  uniqid() is a much better solution than the one I was using so I've added it to the 3.0 branch.

For reference it's in these files :

./local/iomad/lib/iomad.php
./local/report_users/lib.php
./local/report_completion/locallib.php

**Comment by ehuggett** [comment]
I'm not sure if this is going to work for users running iomad on windows (I assume it runs under cygwin? I’ve never run php on windows!)

the [documentation](http://php.net/manual/en/function.uniqid.php) states

```
Under Cygwin, the more_entropy must be set to TRUE for this function to work. 
```

probably because of https://bugs.php.net/bug.php?id=65626
and

```
/* We can also activate the more_entropy parameter, which is 
 * required on some systems, like Cygwin. This makes uniqid()
 * produce a value like: 4b340550242239.64159797
 */
```

It looks like setting more_entropy will cause two further problems
1. full stops are not valid characters for table names
2. the table name will be too long

microtime() doesn't look to be much easier to deal with, perhaps mt_rand() instead?

NOTE: seems it will 'work', but will throw a E_WARNING? (based on the code snippet in https://dustri.org/b/uniqid-in-php-is-not-even-remotely-funny.html)

**Comment by turf212** [comment]
Never run in under cygwin.  There is a PHP for windows (32 and 64 bit from various places).  Lets leave it at uniqid() and see if anyone squeals. :)
