### ISSUE TITLE
User license allocations potential users search filter

### ISSUE THREAD

**Issue by ehuggett** [iomad/iomad#312]
EDIT: This affects IOMAD_30_STABLE and previous releases

The get_options function in the potential_license_user_selector class, used by, blocks/iomad_company_admin/company_license_users_form.php does not return the value of "multiple".

if false (not multiple) the find_users function will remove any user from the list of potential users if they have an allocation from the current license assigned to them, this makes sense if the license is only valid for a single course.

however, because the value of multiple is not returned by get_options is is not saved into the userselector used by the ajax search filter, which means users are excluded when the shouldn't be when using the search filter on potential users for a license valid for multiple courses.

To re-create the issue, 
1. create a license with multiple courses
2. assign half the users in a department an allocation from that license
3. use the search filter under the potential license users, the only results returned will for users who do NOT have any allocations from the current license. if you click the "clear" button after using the search all the users which have a licensed assigned will be missing.

The search filter works as expected when you have multiple courses in a license after adding multiple into get_options

```
diff --git a/blocks/iomad_company_admin/lib/user_selectors.php b/blocks/iomad_company_admin/lib/user_selectors.php
index 3bb7168..db5513a 100644
--- a/blocks/iomad_company_admin/lib/user_selectors.php
+++ b/blocks/iomad_company_admin/lib/user_selectors.php
@@ -666,6 +666,7 @@ class potential_license_user_selector extends user_selector_base {
         $options['subdepartments'] = $this->subdepartments;
         $options['parentdepartmentid'] = $this->parentdepartmentid;
         $options['file']    = 'blocks/iomad_company_admin/lib.php';
+        $options['multiple'] = $this->multiple;
         return $options;
     }
```

**Comment by turf212** [comment]
thanks.  Adding this to 3.0 branch
