### ISSUE TITLE
Use email address as username

### ISSUE THREAD

**Issue by ehuggett** [iomad/iomad#314]
The create user form on the IOMAD dashboard has an option to use the users email address as their username.

Some email addresses contain characters (for example, apostrophe ' ) which moodle by default does not allow in usernames. 

For this to always work as expected "Site Policies -> Allow extended characters in usernames" (extendedusernamechars) should be enabled.

Should this option be enabled by default in IOMAD?

**Comment by turf212** [comment]
Good point.  I'm forcing this to happen as part of an local/iomad_settings upgrade and adding it to the local/iomad/db/install.php script for new systems.
