### ISSUE TITLE
New user mails not being send

### ISSUE THREAD

**Issue by Zenkad** [iomad/iomad#317]
Hi, i have iomad 2.7 and when we register a new user, the email with the password (we leave the password field blank) is not being send. SMTP settings are correct because notifications are being sent we use the message system. Cron is also setup correctly. Where do i start to find the solution... Any help is much appreciated!

**Comment by turf212** [comment]
Can you check if anything is being put into the mdl_email table?  It populates with emails specific to Iomad.  Also, are you logging your cron anywhere as this may also provide some further details.

**Comment by turf212** [comment]
I'm going to assume that this is no longer an issue and close the question.  Please answer if this is not the case.

**Comment by pm-tatiana** [comment]
I have the same issue :-/
