### ISSUE TITLE
 Invalid table name {tmp_clsum_users_56ebe03cc0171}: name is too long. Limit is 28 chars.

### ISSUE THREAD

**Issue by jgdk** [iomad/iomad#318]
Hello,

When I hit the icon for: License usage report by course

Then I get an error like this:

Coding error detected, it must be fixed by a programmer: Invalid table name {tmp_clsum_users_56ebe03cc0171}: name is too long. Limit is 28 chars.

Is it an error or just a bug? :-)

BR
Jens

**Comment by jgdk** [comment]
NB: Here is some more info regarding the error message:

Fatal error: Uncaught exception 'ddl_table_missing_exception' with message 'Table "tmp_clsum_users_56ebe2f20fcbc" does not exist' in /home/myiomadaccount/public_html/lib/ddl/database_manager.php:319 Stack trace: #0 /home/myiomadaccount/public_html/lib/dml/moodle_temptables.php(140): database_manager->drop_table(Object(xmldb_table)) #1 /home/myiomadaccount/public_html/lib/dml/moodle_database.php(370): moodle_temptables->dispose() #2 /home/myiomadaccount/public_html/lib/dml/mysqli_native_moodle_database.php(481): moodle_database->dispose() #3 /home/myiomadaccount/public_html/lib/dml/moodle_database.php(152): mysqli_native_moodle_database->dispose() #4 [internal function]: moodle_database->__destruct() #5 {main} thrown in /home/myiomadaccount/public_html/lib/ddl/database_manager.php on line 319

**Comment by turf212** [comment]
Which Database platform are you using?  Both MySQL and PostgreSQL seem to have a 64 character limit but it may be version dependent.  The temporary table isn't being created and this is breaking the code.

**Comment by jgdk** [comment]
I am using MySql version 5.5 with 64 bit. It is the only local iomad plugin that have issues to create a temporary table. I have uninstalled and installed that particular plugin and it did not make a difference.
Please advice.

**Comment by turf212** [comment]
Ok, your DB will support it but there appears to be a hard coded limit in the Moodle code for the XMLDB layer of 28 characters long.  We changed the code for the uniqueness for the temp tables for the reports and it's had a knock on effect to this.  I'll get the temp table names changed and push ASAP.

**Comment by thepurpleblob** [comment]
Hey,

I've seen some cool stuff on the web, this is definitely must have of the season! Look at it here http://advantage.chicagohomeenergyaudit.com/e4wlv

howard@e-learndesign.co.uk
