### ISSUE TITLE
Edit users only shows users with "User" role

### ISSUE THREAD

**Issue by ehuggett** [iomad/iomad#326]
blocks/iomad_company_admin/editusers.php only shows users with the "user" role, company managers and department training managers are not shown.

I was going to include a patch for my one line change, but its seems this behaviour was very recently introduced in be23a189729015e52dadfafc5ba65dd76665d18c

Could someone elaborate on the reasoning for stopping managers from easily editing other managers/department training managers?

**Comment by turf212** [comment]
It was added to stop department managers editing (and changing passwords for) company managers to prevent any possible security issues.  If someone had also added a site admin to the company (for whatever reason) then a company manager could have edited that account and gained full access to the site.

**Comment by ehuggett** [comment]
I never considered external company managers!

I'm going to look at patching editadvanced.php to prevent this

**Comment by ehuggett** [comment]
Just to clarify

A User with the "Department Training Manager" role should be able to modify accounts with the "Department Training Manager" or "User" role in their department or a sub-department of their current department.

A User with the "Company Manager" role should be able to modify accounts with the "Company Manager", "User" or "Department Training Manager" role in their department or a sub-department of their current department, but must not be able to modify external company managers.

---

I'm looking at adding additional checks into company::check_canedit_user() to prevent external managers from being edited by the internal managers in the company they have been added to.

However, I don't see a reliable method of determining if a manager is external or internal to a company.

The only way I can see to do this, which I would not call reliable, is to assume the companyid from the record in the company_users table with the lowest id is the original company.

on a related note, company_managers_form.php does the following when removing the manager role from a user

```
                        // Is this a manager from another company?
                        if ($DB->get_records_sql("SELECT id FROM {company_users}
                                                  WHERE userid = :userid
                                                  AND companyid != :companyid
                                                  AND managertype = 1",
                                                  array('userid' => $removeuser->id,
                                                        'companyid' => $this->selectedcompany))) {
                            // Remove the user from this company.
                            $DB->delete_records('company_users', (array) $userrecord);
```

This works if you want to remove an external company manager from a company but if you attempt to demote the user from manager in their original company they are removed from it instead!

I think both problems (and possibly others, should external managers be excluded from reports?) can be fixed by adding either a companyid column to the moodle users table or a external column to iomad company_users table.

Existing installations could be updated to this schema in a best-effort fashion by assuming the companyid from the record in the company_users table with the lowest id is the original company.

**Comment by turf212** [comment]
Or possibly any manager who is in more than one company is off limits.  Simpler. :)

**Comment by turf212** [comment]
fixed a long time ago.
