### ISSUE TITLE
[IOMAD_30_STABLE] Parse error in local/report_users/userdisplay.php

### ISSUE THREAD

**Issue by erazorbg** [iomad/iomad#328]
PHP version is: 5.4.45

>  PHP Parse error:  syntax error, unexpected '&&' (T_BOOLEAN_AND), expecting ')' in /var/www/iomad/local/report_users/userdisplay.php on line 322

Line in question: https://github.com/iomad/iomad/blob/e957e86d06d3dc649edfa9ec76a70774d3218beb/local/report_users/userdisplay.php#L322

Changing it to `if (!empty($courseid) && !empty($usercompletion[$courseid]))` fixes it but I don't know if that is the intended logic here.

**Comment by turf212** [comment]
Straight up typo.  Good spot.  Thanks :)

**Comment by erazorbg** [comment]
> PHP Parse error:  syntax error, unexpected ')' in local/report_users/userdisplay.php on line 322

You also have to remove one bracket at the end ;)

**Comment by turf212** [comment]
Sigh.  So I do.  Thanks!  :)

**Comment by thepurpleblob** [comment]
Hey,
I've been looking for some interesting info when I found this stuff, please tell me what you think http://advantage.academyimprovements.com/e4nleml
Looking forward, howard@e-learndesign.co.uk

**Comment by thepurpleblob** [comment]
Hi, I just read an article that you might be interested in, you won't regret, please read it here http://article.universaltronics.com/e4woi

My Best, howard@e-learndesign.co.uk
