### ISSUE TITLE
Collaborating to make few changes in Iomad theme

### ISSUE THREAD

**Issue by rosa2** [iomad/iomad#329]
Hello

I have installed Iomad and made some comments around about theming. I have subthemed Iomad theme and make some changes that maybe you are interested to integrate to Iomad. So I propose to pull for making it easier. I know basic git and it would be my first collaboration on github on this. What I want to make is:
- some changes like in #325 and the client logo
- for not subtheming: that css that are included in Iomad theme settings field customcss work (already in my subtheme)
- add a setting field for using less variables like in https://docs.moodle.org/dev/Themes_overview#Programmatically_injecting_LESS https://moodle.org/mod/forum/discuss.php?d=312175 https://moodle.org/mod/forum/discuss.php?d=312175#p1249631
- turn all colors on variables.
- Compile Iomad .css from .less 

If you are interested, I will make the pull, if not, I will make it in my subtheme. Have a good day :)

**Comment by turf212** [comment]
Definitely interested.  Thanks for adding to the project!

**Comment by rosa2** [comment]
I have an article to follow, so I go to read and pull. By other side, if you agree, we can leave this thread as the main organitzation where you answer ok or not, and then I open an issue if needed. Or tell to me how :)))

New proposals:

--**As a themer**: I would like to be able to upload a javascript to make minor changes. For example, my client it is very small and doesn't have departaments so I don't need all the roles that you offer and go perfect for an uneversity. I have not the time to fix that in php, so... I hide it with JQuery :)) Since I have learned how to resolve the settings I wonder if moodle allows to make that... If it is not complicated, I will make it, if not I subtheme only for that :)

--**As a manager**: When I am in Iomad area I would like to have always accesible the menu. Probably in the navbar, next to my login, specially for new managers. They only use that part. I have seen how to do it. Or to create a tab system as in Iomad Dashboard for subareas. I put an image to make me understand... :)

And now to study pull :) and thanks for creating the project and giving your 10% to Moodle. I can't choose the server... so I give a little of testing and debugging.

**Comment by rosa2** [comment]
I have being investigating to make a customless and customjs fields on the company settings but I was not able to save them in the database's company table. Since I don't need it know and I have probably another project where I will need it, I leave this for the future. I made 2 new columns on the table, but the fields were not saved. If you have any tip, it will be wellcome. 

Also, I think that there is not need for an update.php, but I have never done one... so better you to check, please :)

Tomorrow I will test it and upload it. Have a good day :)

**Comment by rosa2** [comment]
All proposals made in the pull request that I made but

--As a manager: When I am in Iomad area I would like to have always accesible the menu. Probably in the navbar, next to my login, specially for new managers. They only use that part. I have seen how to do it. Or to create a tab system as in Iomad Dashboard for subareas. I put an image to make me understand... :)

If you say you are interested, if my actual client asks, I will make for both. Now I have to start working in other areas :)

**Comment by turf212** [comment]
You can make the dashboard block link sticky throughout the site which would have the same effect.  These are also available in the site admin menu structure where an admin can get at all of the Iomad dashboard bits they need.
