### ISSUE TITLE
Company Delete

### ISSUE THREAD

**Issue by andrepazleal** [iomad/iomad#33]
I have been create company, manage departments, assign department users...but can´t find the option to delete a company.

**Comment by turf212** [comment]
I am glad that you are enjoying using the code.  The company delete option has been removed from the current version of Iomad while we work on providing a way to export or save the full company information.  Clearing up all the company information is a non trivial task with questions such as what do you do with the users, the users couse data, the courses assigned to the company and so on.  You can re-purpose a company which you have created by editing and changing the company information as a work around for the moment.

I will change this to an enhancement as it is needed but not yet available.

**Comment by stephenlane** [comment]
Any update on this ?

**Comment by andrepazleal** [comment]
Atenciosamente,

Andre Paz Leal
+55 48 9179 1679

**Comment by pm-tatiana** [comment]
Hi

I would like to know if this is back? It would be so useful.

**Comment by pm-tatiana** [comment]
Is there any updates on this, it would be great to know if you have any thought about this feature.

**Comment by turf212** [comment]
If I'm honest it's not something we have done anything with.  The ability to suspend a company is now there and, thinking about it now, something similar to this (and user deletion in Moodle) would be all that is required.  I.e. a column in the company table which keeps track if a company is deleted.  This can then be checked against in the various places.
