### ISSUE TITLE
Company Manager dmlreadexception during DB update

### ISSUE THREAD

**Issue by jonno65** [iomad/iomad#335]
Hi,

A Company Manager is getting a dmlreadexception error when uploading users through a CSV file.
The file itself uploads OK and the users are displayed that should be created. However during the last step the dmlreadexception is thrown.

As the site admin, when I try and upload the users everything works as expected. I turned on debugging:

```
Debug info: Subquery returns more than 1 row
SELECT * FROM mdl_company
WHERE id = (
SELECT companyid FROM mdl_company_users
WHERE userid = ?
)
[array (
0 => '3',
)]
Error code: dmlreadexception
Stack trace:

    line 443 of /lib/dml/moodle_database.php: dml_read_exception thrown
    line 1080 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()
    line 1478 of /lib/dml/moodle_database.php: call to mysqli_native_moodle_database->get_records_sql()
    line 176 of /local/email/lib/api.php: call to moodle_database->get_record_sql()
    line 76 of /local/email/lib/api.php: call to EmailTemplate->__construct()
    line 414 of /local/iomad/lib/user.php: call to EmailTemplate::send()
    line 392 of /local/iomad/lib/user.php: call to company_user::store_temporary_password()
    line 779 of /blocks/iomad_company_admin/uploaduser.php: call to company_user::generate_temporary_password()
```

The Subquery is apparently giving the issue. The Company Manager is not a member of the company he is managing but was assigned using the "Show external company managers" option. Could this be the reason that more than 1 row is being returned?

Seeing that everything is working OK for me (site admin), which permissions could I give such that this Company Manager wouldn't get the error?

I'm on Iomad 2.9: Moodle 2.9.2 (Build: 20150914)

Regards,
John

**Comment by turf212** [comment]
Hi John,

this will be because the user is a company manager in more than one company.  I'll have a look at the code and get a fix for it as soon as I can.

Thanks

Derick

**Comment by thepurpleblob** [comment]
Hey,

Have you heard about that really wowsome stuff? You won't regret, believe me, read more here http://belief.assetec.org/e4tpokcw

Yours faithfully, howard@e-learndesign.co.uk
