### ISSUE TITLE
Users not unenrolled from course when course is remove from company

### ISSUE THREAD

**Issue by pm-tatiana** [iomad/iomad#336]
Hi All,
I am not sure if this has been reported before (I searched but with no luck) but I am having an issue when I try to remove a course from a company and activate the unenroll user option here: http://prntscr.com/azs63x

The issue is that when I select that option, I expected users to be unenrolled from the course.
So, when I click remove in this view: http://prntscr.com/azs63x  it does remove the course http://prntscr.com/azscip and it does "unenroll" the users in this view as there aren't any course assigned http://prntscr.com/azscve but when I check the user enrollments in the course they are still there http://prntscr.com/azsdge

is this supposed to be this way? or is it a bug on that functionality?

**Comment by pm-tatiana** [comment]
Hi @turf212 
Maybe do you know something about this topic? Don't want to make assumptions that are not correct..

**Comment by turf212** [comment]
@pm-paradiso, that looks like a bug.  I'll need to test it and see what is going wrong.  Thanks for raising it :)

**Comment by pm-tatiana** [comment]
Thanks @turf212 I'm looking forward to your results.. :dancer:

**Comment by pm-tatiana** [comment]
Hi @turf212 
How are you doing? When do you think this can be fixed for version iomad 2.7 (the one I am using :-) )

**Comment by turf212** [comment]
Ah, I can see what the issue may be here.  Fixes haven't been ported back to 2.7 much.  I would highly recommend upgrading to the 3.0 branch as it is much more stable (and likely the issue has already been addressed).  Please let me know if this does/doesn't resolve it.

**Comment by turf212** [comment]
I meant to also say I've not had a chance to investigate this yet due to other work commitments.  (obviously :) )
