### ISSUE TITLE
Using 'LIMIT 1' in SQL 

### ISSUE THREAD

**Issue by SVIeSolutions** [iomad/iomad#340]
Hi there, LIMIT 1 does not work with MSSQL. I am trying to set up an ecommerce block in IOMAD but when I call up the shop the LIMIT 1 causes an error. I'm trying to find a work around with TOP 1 but it's creating other errors...
In general Moodle never using LIMIT one so that it can be used with all types of DataBases... Like : count_records_sql() expects the first field to contain non-negative number from COUNT(), '' found instead.

**Comment by turf212** [comment]
Can you please tell me where in the code this is happening?  The code should be using the appropriate DML from and to options for get_records etc.

Thanks

**Comment by SVIeSolutions** [comment]
in blocks/iomad_commerce/shop.php at line 162

**Comment by turf212** [comment]
also looks like course.php and lib.php too.

**Comment by SVIeSolutions** [comment]
That's true, I just hadn't gotten that far yet :| 
So far everything I've tried has cause other errors... 
Any suggestions?

**Comment by turf212** [comment]
It's happening in a JOIN in the shop.php.  Best solution would be to pull out that parameter into it's own SQL statement.  Can I give you a patch so you can test that it works OK (I don't have a MS SQL DB to test against.  Normally PosgreSQL and MySQL)

**Comment by SVIeSolutions** [comment]
That would be great!

**Comment by turf212** [comment]
Can you try this for shop.php and, if it works, I can change the others to follow the same idea.

`diff --git a/blocks/iomad_commerce/shop.php b/blocks/iomad_commerce/shop.php
index f8bc657..508462a 100644
--- a/blocks/iomad_commerce/shop.php
+++ b/blocks/iomad_commerce/shop.php
@@ -152,8 +152,12 @@ $sql = 'FROM {course_shopsettings} css
             INNER JOIN {course} c ON c.id = css.courseid ' . $sharedsql .'
             ' . $tagjoin . '
             LEFT JOIN {course_shopblockprice} sbp ON (c.id = sbp.courseid
-                                                  AND sbp.id = (SELECT id FROM {course_shopblockprice}
-                                                  WHERE courseid = c.id ORDER BY price LIMIT 1 ))
+                                                  AND sbp.id = (SELECT a.id FROM {course_shopblockprice} a
+                                                  INNER JOIN
+                                                  (SELECT id,min(price) as minprice from {course_shopblockprice} GROUP BY id) b
+                                                  ON (a.id = b.id)
+                                                  WHERE a.price = b.minprice
+                                                  AND a.courseid = c.id))
         WHERE css.enabled = 1
         ' . $tagwhere . $searchwhere . '
         GROUP BY c.id, sbp.id, css.id, c.fullname ORDER BY c.fullname';
`

**Comment by SVIeSolutions** [comment]
The 'price LIMIT 1' is still in your call...

**Comment by turf212** [comment]
If you could please check if this works and, if so, I can update the others to use the same method.

[shop-diff.txt](https://github.com/iomad/iomad/files/252331/shop-diff.txt)

**Comment by turf212** [comment]
I'd tried to put the git diff up in line but I havent found the syntax styling for it and it was broken.  I've added it as a file but the code should now look like :

> $sql = 'FROM {course_shopsettings} css
>             INNER JOIN {course} c ON c.id = css.courseid ' . $sharedsql .'
>             ' . $tagjoin . '
>             LEFT JOIN {course_shopblockprice} sbp ON (c.id = sbp.courseid
>                                                   AND sbp.id = (SELECT a.id FROM {course_shopblockprice} a
>                                                   INNER JOIN
>                                                   (SELECT id,min(price) as minprice from {course_shopblockprice} GROUP BY id) b
>                                                   ON (a.id = b.id)
>                                                   WHERE a.price = b.minprice
>                                                   AND a.courseid = c.id))
>         WHERE css.enabled = 1
>         ' . $tagwhere . $searchwhere . '
>         GROUP BY c.id, sbp.id, css.id, c.fullname ORDER BY c.fullname';

**Comment by SVIeSolutions** [comment]
This is the result after the modification : 

> Coding error detected, it must be fixed by a programmer: count_records_sql() expects the first field to contain non-negative number from COUNT(), '' found instead.

This is the type of error I was at before... Then I replace the count_records with just a get_records to count them afterwards but I got other types of errors...

**Comment by turf212** [comment]
try this?

> // Get the number of companies.
> $objects = $DB->get_records_sql( 'SELECT \* ' . $sql, $sqlparams);
> $objectcount = count($objects);

**Comment by SVIeSolutions** [comment]
Tried that earlier ...
This is the new error 

> Message: [Microsoft][SQL Server Native Client 11.0][SQL Server]Column 'mdl_course_shopsettings.courseid' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause.<br>
> 
> SELECT \* FROM mdl_course_shopsettings css
>       INNER JOIN mdl_course c ON c.id = css.courseid  AND ( c.id in ( select courseid from mdl_company_course where companyid= 2)
>                  or c.id in ( select courseid from mdl_iomad_courses where shared=1)
>                  or c.id in ( select courseid from mdl_company_shared_courses where companyid = 2)) 
> 
> ```
>   LEFT JOIN mdl_course_shopblockprice sbp ON (c.id = sbp.courseid
> 
>   AND sbp.id = (SELECT a.id FROM mdl_course_shopblockprice a
>   INNER JOIN
>   (SELECT id,min(price) as minprice from mdl_course_shopblockprice GROUP BY id) b
>   ON (a.id = b.id)
>   WHERE a.price = b.minprice
>   AND a.courseid = c.id)) WHERE css.enabled = 1  
>   GROUP BY c.id, sbp.id, css.id, c.fullname ORDER BY c.fullname
> ```
> 
> [array (
> )]

**Comment by turf212** [comment]
This isn't code I've written and the person who did is long gone, so apologies.  It looks like it's just doing a count of the records found and then if there are any, processing it separately.  As such, it should need the select \* and should be OK with :

> $objects = $DB->get_records_sql( 'SELECT css.id ' . $sql, $sqlparams);

although it may still break on the next DB select.

**Comment by SVIeSolutions** [comment]
No problem, it happens :) Thanks for your quick reply and help!
It seems to be working... 
It's not so simple setting up this ecommerce though, is there documentation somewhere to help set up up correctly? Is it possible to change the currency, etc, etc? I have a logn list of questions!

**Comment by turf212** [comment]
Documentation is on the long list of things to complete.  I've started a Wiki and need to get back to it when I can.   Currency is also not definable at the moment.  There is another enhancement issue in for that from a while back.

for course.php change the lines to be :

> if ($course = $DB->get_record_sql('SELECT css._, c._, sbp.*
>                                    FROM {course_shopsettings} css
>                                    INNER JOIN {course} c ON c.id = css.courseid
>                                    LEFT JOIN {course_shopblockprice} sbp ON c.id = sbp.courseid
>                                    AND sbp.id =
>                                        (SELECT a.id FROM {course_shopblockprice} a
>                                        INNER JOIN
>                                        (SELECT id,min(price) as minprice from {course_shopblockprice} GROUP BY id) b
>                                        ON (a.id = b.id)
>                                        WHERE a.price = b.minprice
>                                        AND a.courseid = c.id)
>                                    WHERE css.enabled = 1
>                                    AND c.id = :id', array('id' => $courseid))) {
>     $PAGE->navbar->add($course->fullname);
> }

and for lib.php change the lines to be :

> function get_license_block($courseid, $nlicenses) {
>     global $DB;
>     return $DB->get_record_sql('SELECT *
>                                 FROM {course_shopblockprice}
>                                 WHERE courseid = :courseid
>                                 AND price_bracket_start <= :nlicenses
>                                 ORDER BY price_bracket_start DESC
>                                ', array('nlicenses' => $nlicenses, 'courseid' => $courseid), 0, 1);
> 
> }

If they aall work OK I'll push this to the latest 3.0 branch.

**Comment by SVIeSolutions** [comment]
For the course.php change the lines to be,

> css.*, c.*, sbp,*

Plus for the shop.php page, now I get the following error, 

> 'mdl_course_shopsettings.short_description' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause.

If I remove the group by clause, I get the following error,

> Subquery returned more than 1 value. This is not permitted when the subquery follows =, !=, <, <= , >, >= or when the subquery is used as an expression.

**Comment by SVIeSolutions** [comment]
Actually I am getting errors at almost everything I try... 
I created a license on a course, I'm trying to buy a license, if I type 1 in the 'How many licenses?' textfield and click on buy now. I get the following error,

> Cannot insert the value NULL into column 'license_allocation', table 'IOMAD30.dbo.mdl_invoiceitem'; column does not allow nulls. INSERT fails

Stack trace: 

```
line 446 of \lib\dml\moodle_database.php: dml_write_exception thrown
line 291 of \lib\dml\sqlsrv_native_moodle_database.php: call to moodle_database->query_end()
line 398 of \lib\dml\sqlsrv_native_moodle_database.php: call to sqlsrv_native_moodle_database->query_end()
line 984 of \lib\dml\sqlsrv_native_moodle_database.php: call to sqlsrv_native_moodle_database->do_query()
line 1069 of \lib\dml\sqlsrv_native_moodle_database.php: call to sqlsrv_native_moodle_database->insert_record_raw()
line 87 of \blocks\iomad_commerce\buynow.php: call to sqlsrv_native_moodle_database->insert_record()
```

**Comment by turf212** [comment]
Can you please outline the steps you have taken and I'll check here.  I need to make sure that it's not just an MS SQL issue.  Thanks!

**Comment by SVIeSolutions** [comment]
As admin I created courses users could purchase in the 'shop'. When I conect as a manger and I click on the shop I get the following error,

> Subquery returned more than 1 value. This is not permitted when the subquery follows =, !=, <, <= , >, >= or when the subquery is used as an expression.<br>
> 
> SELECT

 c.id AS thecourseid, css._, c.fullname, sbp._ FROM mdl_course_shopsettings css

```
    INNER JOIN mdl_course c ON c.id = css.courseid  AND ( c.id in ( select courseid from mdl_company_course where companyid= 2)
               or c.id in ( select courseid from mdl_iomad_courses where shared=1)
               or c.id in ( select courseid from mdl_company_shared_courses where companyid = 2)) 


    LEFT JOIN mdl_course_shopblockprice sbp ON (c.id = sbp.courseid

    AND sbp.id = (SELECT a.id FROM mdl_course_shopblockprice a

    INNER JOIN

    (SELECT id,min(price) as minprice from mdl_course_shopblockprice GROUP BY id) b

    ON (a.id = b.id)

    WHERE a.price = b.minprice

    AND a.courseid = c.id))

    WHERE css.enabled = 1


    ORDER BY c.fullname ASC OFFSET 0 ROWS  FETCH NEXT 30 ROWS ONLY
```

[array (

> )]

Error code: dmlreadexception

Stack trace: 

```
line 443 of \lib\dml\moodle_database.php: dml_read_exception thrown
line 291 of \lib\dml\sqlsrv_native_moodle_database.php: call to moodle_database->query_end()
line 398 of \lib\dml\sqlsrv_native_moodle_database.php: call to sqlsrv_native_moodle_database->query_end()
line 850 of \lib\dml\sqlsrv_native_moodle_database.php: call to sqlsrv_native_moodle_database->do_query()
line 174 of \blocks\iomad_commerce\shop.php: call to sqlsrv_native_moodle_database->get_recordset_sql()
```

Then if I click on a course category and select 'more info' for a course, I configured it, so that I could be a single purchase or licences. I thought that the price for the license was for many courses but it seems that it's not. Anyway, the price option is for 50 or more licenses, but if I entre 1 and then click 'buy now' I get the error above.

It seems too that if I buy licenses I need to enrol the users in the course, it's not like a first come first serve until there are no more spaces?!? Is that possible?

**Comment by thepurpleblob** [comment]
Hi,

There is somethig very exciting that you are gonna love for sure! Please, take a look <http://always.kmindependent.com/e4kfyol>

Take care, howard@e-learndesign.co.uk
