### ISSUE TITLE
Web Services for IOMAD functionality

### ISSUE THREAD

**Issue by FrankTrog** [iomad/iomad#341]
Good morning,

Are there currently any web service functions for the IOMAD functionality? I can't seem to find any documentation on this and feel like it would be great if such functionality existed.

**Comment by turf212** [comment]
Hi Frank,

two reasons for this.  First is that documentation is on a long list of things to get done and the Wiki I've started isn't anywhere near seeded yet.  Second is that there aren't any web-services for any of the Iomad specific stuff.  :)  Which ones were you thinking of??

**Comment by FrankTrog** [comment]
Mainly assigning users to a company, assigning courses to a user, and the reporting aspect. We are creating a site that talks to Moodle via Web Services as it isn't possible to modify the Moodle Theme to achieve the look we want. 

We are still tinkering with IOMAD to get used to how it works and roles/assignment process.

**Comment by turf212** [comment]
Answering a thread from the dead.  We've added a number of web-services to the IOMAD 3.2 branch to manage companies and users within a company.
