### ISSUE TITLE
Completion report by course

### ISSUE THREAD

**Issue by SVIeSolutions** [iomad/iomad#346]
In the Iomad dashboard I click on 'Completion report by course', I select dates then click on 'Filter results' I get the following error:

> ERROR: missing param "courseid" in query
> 
> More information about this error
> Debug info: 
> 
> Error code: missingkeyinsql
> Stack trace: line 873 of \lib\dml\moodle_database.php: dml_exception thrown
> line 375 of \lib\dml\sqlsrv_native_moodle_database.php: call to moodle_database->fix_sql_params()
> line 850 of \lib\dml\sqlsrv_native_moodle_database.php: call to sqlsrv_native_moodle_database->do_query()
> line 898 of \lib\dml\sqlsrv_native_moodle_database.php: call to sqlsrv_native_moodle_database->get_recordset_sql()
> line 595 of \local\iomad\lib\iomad.php: call to sqlsrv_native_moodle_database->get_records_sql()
> line 200 of \local\report_completion\index.php: call to iomad::get_user_sqlsearch()
> 
> Output buffer: <div class="notifytiny debuggingmessage" data-rel="debugging">Invalid array parameter detected in required_param(): compfrom<ul style="text-align: left" data-rel="backtrace"><li>line 637 of \lib\moodlelib.php: call to debugging()</li><li>line 454 of \local\iomad\lib\iomad.php: call to optional_param()</li><li>line 161 of \local\report_completion\index.php: call to iomad::add_user_filter_params()</li></ul></div><div class="notifytiny debuggingmessage" data-rel="debugging">Invalid array parameter detected in required_param(): compto<ul style="text-align: left" data-rel="backtrace"><li>line 637 of \lib\moodlelib.php: call to debugging()</li><li>line 455 of \local\iomad\lib\iomad.php: call to optional_param()</li><li>line 161 of \local\report_completion\index.php: call to iomad::add_user_filter_params()</li></ul></div>

**Comment by turf212** [comment]
Did you select a course prior to filtering by date? If not then it sounds like this shouldn't be getting displayed as an option yet.

**Comment by turf212** [comment]
reports have been rewritten in 3.6
