### ISSUE TITLE
When permission block/iomad_company_admin:edit_departments assigned, you get redirected to Iomad Dashboard

### ISSUE THREAD

**Issue by rosa2** [iomad/iomad#354]
Hello and thanks for Iomad

I report here for users to know that if enable this permission to a role, if you visit the home and you don't have a company selected, you will be redirected to the Iomad Dashboard. I spent hours until I found it. I have a manager that helps to all companies and is not the main admin. As a result, the manager can't edit the home.

The reason is this function in local/iomad/lib/iomad.php

```
public static function get_my_companyid($context, $required=true) {
        global $SESSION, $USER;

        // are we logged in?
        if (empty($USER->id)) {
            return -1;
        }

        // Set the companyid to bypass the company select form if possible.
        if (!empty($SESSION->currenteditingcompany)) {
            $companyid = $SESSION->currenteditingcompany;
        } else if (self::is_company_user()) {
            $companyid = self::companyid();
        } else if (self::has_capability('block/iomad_company_admin:edit_departments', $context) && $required) {
            redirect(new moodle_url('/local/iomad_dashboard/index.php'),
                                     get_string('pleaseselect', 'block_iomad_company_admin'));
        } else {
            $companyid = 0;
        }
        return $companyid;
    }
```

We have the need of a role that can edit the home without being redirected because the entrance has a commune text. 

Thanks for your work :)

**Comment by rosa2** [comment]
Also with permissions, for seen the block_iomad_company_selector you have to have the permission company_add while there is 'View list of companies' block/iomad_company_admin:company_view . So I will change in /blocks/iomad_company_selector/block_iomad_company_selector.php , line 35:

```
        // Only display if you have the correct capability.
        if (!iomad::has_capability('block/iomad_company_admin:company_add', context_system::instance())) {
            return;
        }
```

to

```
        // Only display if you have the correct capability.
        if (!iomad::has_capability('block/iomad_company_admin:company_view', context_system::instance())) {
            return;
        }
```

Thanks for your work :)

**Comment by turf212** [comment]
There is a client administrator role you can use for this.  I would doubt the permissions would be correct at the start but that was what it was initially designed for :)
