### ISSUE TITLE
Deleting Course and View Course Category in any company

### ISSUE THREAD

**Issue by danialst** [iomad/iomad#356]
Hi
We are using Iomad, but we have some problems 
1- Company Manager Cant Delete Course 
2- Every Company Manager Can see Course Category 

tanx

**Comment by pm-tatiana** [comment]
Hi @danialst  Did you find a way to hide or delete those categories?

**Comment by danialst** [comment]
hi 

not yet, we arranged a team to develop and support IOMAD and we
will solve it as soon as 

because moodle as department is useful for
us. 

On 2016-10-06 17:25, Tatiana wrote: 

> Hi @danialst [1] Did you
> find a way to hide or delete those categories? 
> 
> ## 
> 
> You are
> receiving this because you were mentioned.
> Reply to this email
> directly, view it on GitHub [2], or mute the thread [3].

## Links:

[1] https://github.com/danialst
[2]
https://github.com/iomad/iomad/issues/356#issuecomment-251968204
[3]

**Comment by pm-tatiana** [comment]
Was this ever resolved? I would like to know if there's any capability for this?
