### ISSUE TITLE
Certificate Module - Doesnt generate cert

### ISSUE THREAD

**Issue by laithgate** [iomad/iomad#359]
Hello

I have tried to create the certificate for the completion of the student, I also have a custom background for this - but when I select to generate the certificate from either the management module, or the IOMAD Certificate block, it just generates a blank screen in the browser.

Any pointers? TIA

**Comment by turf212** [comment]
if it's just generating a white screen then its likely throwing an error.  Turn on debug (developer) and try again.  Its likely something in the certificate file or image file.

**Comment by laithgate** [comment]
Thanks Derek.

Kindest Regards
John Papworth - Laithgate Ltd
Mobile: +44 (0)7413 030830 or +44 (0)7544 519802 | Email: john@laithgate.co.ukmailto:john@laithgate.co.uk  |  Skype: john_papworth70  |  Web:www.laithgate.co.ukhttp://www.laithgate.co.uk/

Legal Note: The contents of this Email and any attachments are the property of Laithgate Limited and are intended for the confidential use of the named recipient(s) only. They may contain information which is confidential and may also be privileged and subject to the provisions of the Data Protection Act 1998.
If you are not an addressee please notify us immediately at info@laithgate.co.ukmailto:info@laithgate.co.uk. Any files attached to this email have been checked with virus detection software before transmission.
