### ISSUE TITLE
Unassign user error

### ISSUE THREAD

**Issue by Zenkad** [iomad/iomad#363]
Hi, when unassigning a user from a company i get following error:

Coding error detected, it must be fixed by a programmer: Invalid call to role_unassign(), please use role_unassign_all() when removing multiple role assignments

Here is the debug info:

Debug info:
Error code: codingerror
Stack trace:

```
line 1788 of /lib/accesslib.php: coding_exception thrown
line 133 of /blocks/iomad_company_admin/company_users_form.php: call to role_unassign()
line 188 of /blocks/iomad_company_admin/company_users_form.php: call to company_users_form->process()
```

We're using Iomad 2.7 stable version.

Can you please help?

**Comment by Zenkad** [comment]
Nobody?

**Comment by Zenkad** [comment]
Update: If deleted lines 127 till 134 in /blocks/iomad_company_admin/company_users_form.php and it works now.

**Comment by turf212** [comment]
The 2.7 version of Iomad is quite old and it's likely there are issues with bugs.  I would highly recommend upgrading to the later 2.8 or 3.0 versions as these would have been addressed.

**Comment by Zenkad** [comment]
I know but we've made a lot of customisations to the moodle core so it's impossible to upgrade.
