### ISSUE TITLE
Error with approval block on upgrade from Moodle

### ISSUE THREAD

**Issue by turf212** [iomad/iomad#371]
-->block_iomad_approve_access
PHP Warning:  Creating default object from empty value in /home/eldi31/public_html/blocks/iomad_approve_access/db/install.php on line 36
Default exception handler: Error writing to database Debug: Field 'parentcontextid' doesn't have a default value
INSERT INTO mdl_block_instances (blockname) VALUES(?)
[array (
  0 => 'iomad_approve_access',
)]
Error code: dmlwriteexception
- line 477 of /lib/dml/moodle_database.php: dml_write_exception thrown
- line 1172 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()
- line 1218 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->insert_record_raw()
- line 38 of /blocks/iomad_approve_access/db/install.php: call to mysqli_native_moodle_database->insert_record()
- line 900 of /lib/upgradelib.php: call to xmldb_block_iomad_approve_access_install()
- line 434 of /lib/upgradelib.php: call to upgrade_plugins_blocks()
- line 1742 of /lib/upgradelib.php: call to upgrade_plugins()
- line 181 of /admin/cli/upgrade.php: call to upgrade_noncore()

!!! Error writing to database !!!
!! Field 'parentcontextid' doesn't have a default value
INSERT INTO mdl_block_instances (blockname) VALUES(?)
[array (
  0 =&gt; 'iomad_approve_access',
)]
Error code: dmlwriteexception !!
!! Stack trace: \* line 477 of /lib/dml/moodle_database.php: dml_write_exception thrown
- line 1172 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database-&gt;query_end()
- line 1218 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database-&gt;insert_record_raw()
- line 38 of /blocks/iomad_approve_access/db/install.php: call to mysqli_native_moodle_database-&gt;insert_record()
- line 900 of /lib/upgradelib.php: call to xmldb_block_iomad_approve_access_install()
- line 434 of /lib/upgradelib.php: call to upgrade_plugins_blocks()
- line 1742 of /lib/upgradelib.php: call to upgrade_plugins()
- line 181 of /admin/cli/upgrade.php: call to upgrade_noncore()
  !!

**Comment by turf212** [comment]
this is caused as the local dashboard block hasn't yet been installed on upgrade from Moodle but it's not during initial install.

**Comment by iomad** [comment]
closed.  Added to 3.1 version
