### ISSUE TITLE
Iomad signup notice for event handlers on install

### ISSUE THREAD

**Issue by turf212** [iomad/iomad#372]
-->local_iomad_signup
PHP Notice:  Events API using $handlers array has been deprecated in favour of Events 2 API, please use it instead.\* line 4050 of /lib/deprecatedlib.php: call to debugging()
- line 533 of /lib/upgradelib.php: call to events_update_definition()
- line 1742 of /lib/upgradelib.php: call to upgrade_plugins()
- line 181 of /admin/cli/upgrade.php: call to upgrade_noncore()
  in /home/eldi31/public_html/lib/weblib.php on line 3082

**Comment by iomad** [comment]
closed.  Added to 3.1 version
