### ISSUE TITLE
Course Categories deletion - question

### ISSUE THREAD

**Issue by pm-tatiana** [iomad/iomad#382]
Hi All,
I have noticed that when I create a company, a course category is created automatically in the moodle.
I was wondering, if we are not going to use those categories, can we delete them?

I mean, we are not going to create any course from the companies, they will have courses assigned to them. So I was wondering what is the use of having so many categories, that can confuse our users?

**Comment by turf212** [comment]
Looks like I missed this question.   The categories are created by default when a company is created as it then allows for a default location for the companies dedicated courses.  These categories are stripped from a normal users list so they will only see the categories which they are allowed to.
