### ISSUE TITLE
Documentation: Courses shared among companies

### ISSUE THREAD

**Issue by rosa2** [iomad/iomad#388]
Hello

I have the need that teachers form different companies can see the other companies courses and activities and download these last. Also some courses are shared among companies.

I read in [http://www.iomad.org/main-features/multi-tenancy/](http://www.iomad.org/main-features/multi-tenancy/)
_Sharing of courses – As well as having courses which are only assigned to one company, courses can be shared between selected companies or can be shared across all companies (whilst still retaining their own branding and autonomy for users)._
But I have tried to localize the permissions or form where to do it and I have not being able. 

In [Manage Iomad course settings] in/blocks/iomad_company_admin/iomad_courses_form.php, I have set all courses shared and teachers can see them, but I am unable to see all in a list.

And if I create a course and assign to a company, I can't assign it to a different one.

Please could you explain to me? Thanks

**Comment by turf212** [comment]
How courses are viewed by companies entirely depends on how you set the up for the sharing.
Not shared means that a course can be assigned to one company only using the  "assign course to company screen"
Closed shared means that you can assign the course to more than one company using the "assign course to company screen"
Open shared means that the course automatically is available to every company.

Hopefully this clears this up.

**Comment by rosa2** [comment]
Hello
Thanks a lot for your answer :) I had a lot of work and I was not able to test. My steps:
- I import through CSV a course
- I make it open shared
- I assign to a company
- It can't be assigned to another company while a company has them assigned already.

I would like to create a common course that the other companies can borrow, but I must make something wrong.

**Comment by rosa2** [comment]
Once I assign the course to a company, I can't remove it. I select the course and click the Remove button.

**Comment by rosa2** [comment]
The fields that i import in the csv

```
category     fullname         shortname visible groupsmode  lang
6             Català Nivell 1  C1            1       1      ca

```

the category is for a company

**Comment by rosa2** [comment]
I have the same problem with courses that are created from the iomad dashboard. Steps:
- Select a company
- Create a course
- Make the course shared
- Assign the course to this company
- Change company
- Go to assign the course to a company and the course doesn't shows.

Any help will be very welcome, thanks

**Comment by patrickgaskill** [comment]
I'm having a similar problem.

- Create a course under one company
- Change it to Open Sharing in "Manage Iomad course settings"

I cannot seem to assign this course to any other company. It does not appear in the list of courses in the "Assign to company" screen, or anywhere else.

**Comment by turf212** [comment]
HI Rosa,

This issue was closed so I've missed the traffic on it.  I'll re-open it now.  Can you confirm what type of sharing you are using for this, closed or open.

@patrickgaskill - Open shared courses do not need to be assigned to a company.  By their definition they are automatically available to every company.  If you want to choose which of the companies have access to the same course then you need to use closed sharing.

**Comment by rosa2** [comment]
Thanks @turf212 for reopening and sharing your time teaching us :)

I have tried with open first, and then with closed. With open, I assign the course to a company and then I can't assign to the others. With closed, I don't know where to configure which companies can share. For what I have seen when a course is assigned to a company, it is classified in the company category, so I imagine that because of that, the other companies can't see it, even if it is open shared. But that it's my understanding because I have not the technical skills to know that.

Probably I don't follow the right steps to configure it, so I will much appreciate if you write them here. You say that open shared courses do not need to be assigned to a company, but then, how do you classify to show them to students?

Thanks again for your time :)

**Comment by rosa2** [comment]
Hello again

I put my real need because my bad English can make difficult to understand me.

One organization collaborates with 4 NGOs to give courses with young poor people. They 4 share the classification and courses, thought they make different activities. They want to see one each other courses (I can by making the assigned course open shared) to learn one each other. 
I would like to have the main structure of each course created once and then, they can put the activities that they want. They also use the same categories that I have created in each company/NGO (they are visually the same, but they are duplicates with their unique id). Then inside of each course there are groups uniques to each NGO.

I hope I have explained good enough, thanks

**Comment by bkmarsh** [comment]
I have a similar issue. I created a course called "Voice" and changed the settings to be "open". Based on what I've read it should automatically appear for any company I create, so I have not assigned it to any company. I created a company called "Columbia Arts Academy" and when I try enroll users, the course drop-down doesn't have the course in it, it just has "None". I've attached screen captures, I hope they help.

![course-settings](https://cloud.githubusercontent.com/assets/6110342/22814716/d5e82666-ef23-11e6-95a9-5dfbb9b9fa1b.PNG)
![enroll-users](https://cloud.githubusercontent.com/assets/6110342/22814717/d5ec64a6-ef23-11e6-8b31-41269bcdf693.PNG)

**Comment by jc4316son** [comment]
Im also having this same issue with IOMAD 3.2

**Comment by diloop** [comment]
Exactly the same problem with a fresh installation of IOMAD 3.2.

I have two schools: Arcos Iris and Silkstone. When I assign the course to the first school, it is no longer available for the second one. Then I unassign and it becomes available again. But as soon as I assign to the second school, it is no longer available for the first one.

![courses](https://cloud.githubusercontent.com/assets/26105011/23446650/ade31f46-fe45-11e6-9cdc-2630b8be8251.jpg)

**Comment by diloop** [comment]
In the following screenshot you can see that the Iomad course settings indicate "Open sharing". 
![opensharing](https://cloud.githubusercontent.com/assets/26105011/23538803/62df4a50-ffd6-11e6-9f9d-3179e85ad73e.PNG)

**Comment by diloop** [comment]
Surprisingly, I changed the "Is shared" option to "Closed sharing" value and I was able to assign the course to my two schools!
That means that it is only working wrong for the "Open sharing" case. Perhaps some of you can use "Closed sharing" in the meantime until the developers fix this bug.

**Comment by turf212** [comment]
When courses are open shared they are automatically available to every company without having to assign them to the company.  With closed shared courses you have control over which companies are given access to the course.

The question mark help link beside this does say:

> No - Course is not shared
> Open sharing - Course is shared across all companies
> Closed sharing - Course is shared between selected companies (see Course management > Assign to company)

**Comment by turf212** [comment]
@diloop - Sorry, just for my understanding - You have a course which is open shared which hasn't yet been assigned to any company?  As a rule of thumb/best practice, you need to assign your courses somewhere, wevn if they are going to be shared.  This of it as a course repository company.  So an open shared course can still be assigned to a company once.  But it will still remain automatically available for all companies due to the nature of the sharing.

**Comment by diloop** [comment]
@turf212 - Thank you for the clarification. So the problem in my case was a misunderstanding of the documentation. I am newbie with IOMAD and I thought that the first step was always assigning the course to the companies. I understood the "Open sharing" option as the permission to execute this assignment. If this is the case for the rest of the people in this discussion, this bug should be closed as invalid. Perhaps ading this clarification in the documentation could help other people in the future as well.
