### ISSUE TITLE
Assign Department Users/Managers screen not very clear

### ISSUE THREAD

**Issue by thepurpleblob** [iomad/iomad#393]
Some issues here...

- The layout is messy (in the standard theme anyway)
- Additional dialogues are possible when the role dropdown updates but this involves a screen refresh. This could probably be done more elegantly with a some javascript
- the help option for external managers says it only works for managers - but only appears when the manager role is selected.

**Comment by thepurpleblob** [comment]
blocks/iomad_company_admin/company_managers_form.php

Really, the whole thing is a bit messy. I'm not sure the forms are being constructed properly or in the right place. It all needs a bit of refactoring and, probably, the form functions moved into their own file.

**Comment by turf212** [comment]
We've had a go at this and, while it's still not great, it is a little better.  There was a thought around a bulk user actions style page which would replace this function.  It's something which would likely need sponsored though.
