### ISSUE TITLE
iomad::get_my_companyid seems to have a spurious parameter

### ISSUE THREAD

**Issue by thepurpleblob** [iomad/iomad#397]
The first parameter for this function is $context. I can't think when it wouldn't be the system context. I had a look through quite a few calls and this seems to be the case. 

This should be refactored to remove the parameter and look up system context in the function.

**Comment by turf212** [comment]
true, but the context would have already been looked up in the calling code for other reasons (cap checks and so on) so having it again is another DB lookup we don't need.
