### ISSUE TITLE
Cannot create Activites/Resources

### ISSUE THREAD

**Issue by watcanz** [iomad/iomad#401]
Iomad 3.1, fresh install.

Created a course.
Turned on Editing.
Select Assignment, or anything in list and get

 Fatal error: Class 'core_competency\context_system' not found in /home/fheyshw/public_html/competency/classes/course_competency.php on line 408

And a blank screen.

**Comment by turf212** [comment]
I've tried this as the admin user on a test install and it's working fine.  There were some issues with this previously which had been addressed.  Was this freshly downloaded?

**Comment by turf212** [comment]
The fix wasn't pushed (which is why it was working on the test site).  Pushing this now.

**Comment by watcanz** [comment]
Updated my site.  Issue resolved.  Thank you for the quick attention to this!
