### ISSUE TITLE
No buttons on default dashboard editing page!

### ISSUE THREAD

**Issue by thepurpleblob** [iomad/iomad#408]
The editing page for the default dashboard has no buttons for switching on editing or returning the page to default. Turns out that it's caused by a 'display: none' in blocks/mycourses/style.css

```
div.breadcrumb-button {
    display: none;
}
```

This was done as part of a big commit 6a5bacaf1e45df8337d6c87c9f5dbff12866cc15 "IOMAD: new reporting to use the local iomad track plugin and data"

I'm not clear why :(

**Comment by turf212** [comment]
The page uses the same CSS identifiers as for the user dashboard edit buttons (which was where it was no longer wanted).  If you can separate the two then please do :)
