### ISSUE TITLE
Restoring a course gives errors with roles

### ISSUE THREAD

**Issue by rosa2** [iomad/iomad#418]
![roles_error_restoring_courses](https://cloud.githubusercontent.com/assets/1841507/20650709/7057f16a-b4d5-11e6-89c1-0cb4f03bc251.png)

Hello

I have done a course backup from inside the course and when I restore it I get this errors:

```
The role in the backup file cannot be mapped to any of the roles that you are allowed to assign.
The role in the backup file cannot be mapped to any of the roles that you are allowed to assign.
The Company Manager role in the backup file cannot be mapped to any of the roles that you are allowed to assign.
```
I have test to not save the roles assigned, but I still get this error

I am the moodle admin, so I don't understand not being able to assign a role. I have tried with a company chosen and not.

Thanks for any help :)

**Comment by turf212** [comment]
It's possibly a problem with context.  the Company manager role should be site only and not in the course context.  Did you give someone that role locally?
