### ISSUE TITLE
Two companies can't have same course short name 

### ISSUE THREAD

**Issue by rosa2** [iomad/iomad#419]
Hello

When creating courses for companies if they choose the same short name, the form validation say to the company that tries last that the short name is already in use.

**Comment by turf212** [comment]
Hi Rosa, it's Moodle which is causing the issue as the shortname has to be unique.  I'm open to ideas about how we could change this to work better.  E.g. we could tie the company shortname to the course shortname for uniqueness as a forced prefix (much like we do with the company profile fields) but we may end up with shortnames which become unwieldy or too long to be stored int he data fields.

**Comment by SolutionsDEV** [comment]
The shortname could have initials of the company like 2 or 3 letters followed by a dash, but in the backend this maybe have to be changed to allow the same shortname for another company and rely more on the course ID which with no question should be unique.

Regards,
