### ISSUE TITLE
Creating course category for each company

### ISSUE THREAD

**Issue by jtemerson** [iomad/iomad#429]
I am almost done developing moodle and Iomad for what I need. The only thing left that is bugging me about Iomad is that every time I create a company it automatically creates a category also. I have all my courses under one category and I will assign courses to users from different companies and allow company managers to assign courses to them also, but I dont want any courses under a new category. I don't want course categories named after every single company that I create. When I suspend a company, the category stays. It is really annoying. I only have shared courses. 

Any help is appreciated.

**Comment by turf212** [comment]
Hi, this behaviour is deliberate.  Iomad allows the capability for a company manager to create courses and the course category created is the one where these courses will be stored.  It's to prevent potential unwanted overlap between companies for courses.

Suspending companies doesn't actually remove them.  If you un-suspend a company then they should have access to everything they had before.  Which includes any courses they could have created in their own company category.

I'm open to suggestions as how best to handle this.  The possibility of deleting a company is better now once we move more to using events and triggers.  A lot of the clean up can be done from there.

**Comment by jtemerson** [comment]
So in my situation, there are no company courses or categories. Every company has access to all the same shared courses. The admin creates a company with users and then assigns courses to the users. The company manager can also assign courses to the users. All courses assigned are pre-existing, shared courses. Every company has access to the same courses and cannot create their own company courses. I would just like to take the feature of automatically creating a category with the company away.

**Comment by MrPradeepBisht** [comment]
Hi turf,
When i try to create a course by Iomad then below error display .
![capture2](https://user-images.githubusercontent.com/35295561/34770080-d117f792-f625-11e7-836a-40be7f9f2d0d.PNG)

thanks for help

**Comment by turf212** [comment]
Data issue - company category in the company record has been deleted.
