### ISSUE TITLE
Can not add a block in IOMAD version 3.1 

### ISSUE THREAD

**Issue by rahul-chowdhary** [iomad/iomad#430]
I just installed iomad version 3.1  using Zip from https://github.com/iomad/iomad.
I am using iomad bootstrap theme.
I am not able to add block to dashboard. when a block is selected from blocks dropdown list then nothing happens (block is not added). Neither the arrow icons work to minimise the default block. 
image for reference:-
![download](https://cloud.githubusercontent.com/assets/19282980/21472822/64926c4c-cb10-11e6-9045-0302ff6e93e4.png)

**For iomad bootstrap theme getting following error in console on dashboard** :-

<img width="1280" alt="screen shot 2016-12-26 at 2 00 55 am" src="https://cloud.githubusercontent.com/assets/19282980/21472776/3e385634-cb0f-11e6-9d77-988c1f60d0f2.png">

I also tried a different theme i.e klass theme (https://moodle.org/plugins/pluginversions.php?plugin=theme_klass). This theme works perfectly with moodle 3.1 but having above issues for iomad.
Though no issue is faced with default iomad theme.

Please suggest how this issue can be resolved?

**Comment by thepurpleblob** [comment]
I tried this and couldn't reproduce the problem. However, the theme in your screenshot definitely isn't the 'Iomad Bootstrap' theme.

**Comment by rahul-chowdhary** [comment]
Hi @thepurpleblob, sorry for mix up. i pasted the screen shot for clean theme of moodle. 
I am pasting the screen shot of 'Iomad bootstrap' theme as well. facing same issue in that to.

<img width="1280" alt="screen shot 2017-01-01 at 3 35 47 am" src="https://cloud.githubusercontent.com/assets/19282980/21579438/3a2b7d6c-cfd5-11e6-9c82-b27a1ece113e.png">

<img width="1280" alt="screen shot 2017-01-01 at 3 36 36 am" src="https://cloud.githubusercontent.com/assets/19282980/21579440/4eff2d88-cfd5-11e6-9434-0af092c1785b.png">

![de](https://cloud.githubusercontent.com/assets/19282980/21579441/58dcfde4-cfd5-11e6-8918-e714b3405ed2.png)

Did you got any error in console? Please try adding one or two block. 
After 1 or 2 block, no new block is added.

**Also the Issues occur only on the dashboard page on all other pages every thing works fine**.
I have tried clean and klass theme.

**Comment by thepurpleblob** [comment]
Who are you logged in as? Well, what permissions does your user have? I'll try adding a few blocks as you suggest.

**Comment by rahul-chowdhary** [comment]
I just did a fresh installation and logged in as admin, have the same permissions that come with a fresh installation. I am using MAMP setup.

**Comment by turf212** [comment]
tested and no longer found to be an issue.  Possibly this was a Moodle bug.
