### ISSUE TITLE
Improve mycourses block

### ISSUE THREAD

**Issue by thepurpleblob** [iomad/iomad#432]
Issue #357 addressed the appearance of the block (it wasn't very easy to see which course belonged to which heading). However, the functionality is a bit limited. It's really 'my completion status'. It would be useful to (maybe?) to add courses that do not use completion. At the moment, such courses will be completely ignored (along with courses where the completion cron has not yet run).

**Comment by turf212** [comment]
closed in c48272c0f25cdffcf06f5bad4dbcb451f6dc64db
