### ISSUE TITLE
Courses available list displayed to company manager is incorrect

### ISSUE THREAD

**Issue by gailaustin** [iomad/iomad#434]
I have 120 companies on my Iomad instance, all sharing 36 courses (closed sharing - each company only uses an average of 6 of the courses). Logging in as company manager for one of the programs, when I click Change Course Enrollments for a user in that company, the Courses Available list says "too many courses to display - 416 courses". How con I get this list to just display the available courses for this company? Please help!! I need to demo this to the client tomorrow!

**Comment by thepurpleblob** [comment]
I'm not clear where you are seeing this. Where are you clicking 'Change Course Enrollments'?

**Comment by gailaustin** [comment]
Yes - our team has just signed up for Iomad customer service, so hopefully they can solve this. It is impacting half our Companies on the site.

**Comment by gailaustin** [comment]
Oh I thought you asked were you clicking Change Course Enrollments, but you're actually asking where that link is. It's in User Management, Edit users - each user has a number of links, one of which is Change Course Enrollments.

**Comment by turf212** [comment]
This is the same issue.   I've fixed this and will push ASAP.  @gailaustin is who I was looking at this for :)

**Comment by turf212** [comment]
Closed and fixed as the other issue.
