### ISSUE TITLE
User enrolments throws... Exception - Using $this when not in object context

### ISSUE THREAD

**Issue by thepurpleblob** [iomad/iomad#437]
From dashboard...
- login as company manager
- Select course management tab
- Click user enrolments
- Click enrol/unenrol users button

Above exception occurs. 

Stack trace: 
line 582 of /lib/pear/HTML/QuickForm.php: Error thrown
line 548 of /lib/pear/HTML/QuickForm.php: call to HTML_QuickForm::_loadElement()
line 142 of /lib/form/datetimeselector.php: call to HTML_QuickForm::createElement()
line 546 of /lib/pear/HTML/QuickForm/group.php: call to MoodleQuickForm_date_time_selector->_createElements()
line 163 of /lib/pear/HTML/QuickForm/group.php: call to HTML_QuickForm_group->_createElementsIfNotExist()
line 219 of /lib/form/datetimeselector.php: call to HTML_QuickForm_group->setValue()
line 382 of /lib/pear/HTML/QuickForm/element.php: call to MoodleQuickForm_date_time_selector->onQuickFormEvent()
line 417 of /lib/pear/HTML/QuickForm/group.php: call to HTML_QuickForm_element->onQuickFormEvent()
line 240 of /lib/form/datetimeselector.php: call to HTML_QuickForm_group->onQuickFormEvent()
line 582 of /lib/pear/HTML/QuickForm.php: call to MoodleQuickForm_date_time_selector->onQuickFormEvent()
line 612 of /lib/pear/HTML/QuickForm.php: call to HTML_QuickForm->_loadElement()
line 182 of /blocks/iomad_company_admin/company_course_users_form.php: call to HTML_QuickForm->addElement()
line 944 of /lib/formslib.php: call to company_course_users_form->definition_after_data()
line 376 of /blocks/iomad_company_admin/company_course_users_form.php: call to moodleform->display()

**Comment by turf212** [comment]
ba653da9ea983a5fcdb20a52d70dbddd3cfe504c
