### ISSUE TITLE
Courses disappear in frontpage (for non logged users) if they are assigned to a company

### ISSUE THREAD

**Issue by fortarrigo** [iomad/iomad#438]
Hi.
There's an issue with courses in frontpage for not logged user.
If I create a course with normal procedure (not via IOMAD dashboard) they are correctly displayed in frontpage for not logged user.
But if I assign it to a company, it disappears from frontpage.
The same if I create course via IOMAD Dashboard.
Is it a bug or there is a setting or parameter to view courses in frontpage?

Tested with Adaptable theme and IOMAD theme.

I'm using last stable IOMAD release with the last release of Adaptable theme.

Thanks in advance for your help

**Comment by turf212** [comment]
This is correct behaviour.   Courses only appear for users who should be able to see them.  If a course is assigned to a company, then it is for that company only.  If it is shared, then depending on how it is shared, it will only be seen by people who are in those companies.  The guest user (not logged in) is not a member of a company so will not see these courses.

**Comment by peterhuppertz** [comment]
I would like to display the courses to guest users if they enter from the domain set in the company settings. The current company is available via $SESSION->currenteditingcompany, so Moodle "knows" which courses to show. Any possibility to do so?
