### ISSUE TITLE
Ivy/RTS: Some needed courses not appearing on Create New License and E-Commerce Course picklists

### ISSUE THREAD

**Issue by gailaustin** [iomad/iomad#440]
Hi Derick: Got the first manual registration account out the door:)

Now we are setting up licenses for the e-commerce programs.

For Company Plymouth, there are 22 courses assigned to that company, but only 21 appear in the Create New License screen - Information Systems is the one missing - why is it not displaying so we can set up licenses for it?

For E-Commerce, we've set up 26 courses on the shop, but 12 courses (all of them are Assessment courses) don't appear on the E-commerce course picklist, so we can't set them up on the shop. 16 courses DO appear on the list as Available to set up on the shop, but we've already set up all these courses on the shop. What's going on here? Here is the list of courses that's not appearing for Shop setup:

> Business Law ASSESSMENT ONLY
> Financial Accounting ASSESSMENT ONLY
> Fundamentals of Economics ASSESSMENT ONLY
> Fundamentals of Microeconomics ASSESSMENT ONLY
> Information Systems ASSESSMENT ONLY
> Interactive Business ASSESSMENT ONLY
> International Business ASSESSMENT ONLY
> Managerial Accounting ASSESSMENT ONLY
> Operations Management ASSESSMENT ONLY
> Principles of Management ASSESSMENT ONLY
> Principles of Marketing ASSESSMENT ONLY
> Strategic Management Process ASSESSMENT ONLY
> Understanding Corporate Finance ASSESSMENT ONLY

THANKS for your help with this!
Gail

**Comment by gailaustin** [comment]
This problem has disappeared on its own after 3 hours. Strange but glad it resolved on its own!

**Comment by turf212** [comment]
Closing this as it was likely a caching issue.
