### ISSUE TITLE
When company manager is created, add IomadLink block to Dashboard

### ISSUE THREAD

**Issue by thepurpleblob** [iomad/iomad#478]
Same sort of issue as site admin. When a new company admin first logs in they will see their Dashboard without any clear link to the Iomad Dashboard. The Link block should be added to newly assigned accounts in the same manner as the site admin.

**Comment by turf212** [comment]
Would it not be better adding it to the default dashboard page?  The block displays only if you have the correct permissions and that way it's automatically available.

**Comment by thepurpleblob** [comment]
...or that. I spent some time trying to get that to work and failed miserably. I'll have another go. But anyway, it's just a point that something is really needed as the user just gets hit with a normal Dashboard page and it's far from obvious what to do next.

**Comment by turf212** [comment]
fixed by @thepurpleblob
