### ISSUE TITLE
Company Manager Role Permissions

### ISSUE THREAD

**Issue by bkmarsh** [iomad/iomad#480]
I'm trying to use IOMAD to solve a music school problem. They have multiple franchisees, so franchisee 1 should not be able to do anything with franchisee 2 data. IOMAD seems to have the capabilities I'm looking for, but I'm struggling with it. My question is, does the Company Manager role have all of the permissions it needs with the default installation to have complete control of its company.

For example, can it create a parent role and assign it to a student? I've done it in a pure Moodle installation, but the steps don't seem to work with IOMAD. I've only seen instructions in Moodle using the User functions under Administration. The Company Manager role only shows the IOMAD link and it doesn't allow me to navigate to the user profile page. I'm sure it's a permissions issue, but when I try to add various user permissions to the role it allows me to see users for all companies.

Thanks for any direction you can provide.

**Comment by turf212** [comment]
The default roles for Iomad are capable enough to manage everything in the institution as it exists at the start.  The parent role is something which is not part of this and isn't something which can be managed out of the box.  You will need to be wary of giving other roles course access without having them tied into the forced group for that company.  If you are looking for something to be created for this then we would be happy to help you with this.
