### ISSUE TITLE
Preventing the teachers seeing the enrolled users from other companies

### ISSUE THREAD

**Issue by diloop** [iomad/iomad#482]
I just installed my first IOMAD site some days ago and I created the first course, which you can see in the screenshots with the name Neuronita I.

Then I created two companies called Arco Iris and Silkstone. The site admin is the only user that performs all the necessary user management tasks: he adds new users into the companies, and after doing that he enrolls them into the course.

At the present moment:
- Arco Iris: 4 users
- Silkstone: 3 users

At this point, everything shows fine from the IOMAD dashboard. Users from every company still show separated from each other.

The next step is to defined the role of the users in the course. I choose one user in every company to be the teacher, while the other remain as students.

The problem ocurs when the teacher logs into her account. In the grading screen, she can see 7 users enrolled in the course, while she should only see the users from her company (one teacher should only see 4 users, and the other teacher should only see 3 users). Same problem ocurs if the teacher logs into the Moodle Mobile App.

**Comment by diloop** [comment]
This screenshot shows the 4 users enrolled (from the first company Arco Iris).
![enrolled_users](https://cloud.githubusercontent.com/assets/26105011/23577119/b438e460-00b7-11e7-839d-7a76455b19a6.PNG)

**Comment by diloop** [comment]
This screenshot is the user list that is shown to the Arco Iris teacher when she logs into his account. The users from the other company Silkstone should not be visible to her! 
![teacher](https://cloud.githubusercontent.com/assets/26105011/23577137/f98fdce4-00b7-11e7-98a2-7e0b0d43b20c.PNG)

**Comment by turf212** [comment]
The issue is that the teacher role has rights to see all of the groups with a course by default in Moodle.  Shared courses in Iomad use forced separate course groups to keep the users apart.  You can either change the teacher role to reflect what you want or use the company non editing teacher role instead.

**Comment by pm-tatiana** [comment]
Hi @diloop 

I think you should use IOMAD roles to define the roles of the users in the course. 
A workaround can be the following:

Arco Iris School (company)
Ok. You already have your "students" enrolled into the course (assuming that you assigned the course to "Arco iris", then used the "enroll users" function under "course management" tab) 
Then to defina your "teacher" , do not use the moodle role teacher. You can instead use the IOMAD "Company Manager" role and rename it as "Teacher", then you can modify the permissions similar to a non editing teacher role of Moodle. 
Usually when you assign a course to a company, the company manager is automatically enrolled into the course as "Company manager" and "Client Course access" - you can either modify the company manager role or the client course access to behave the way you need.
hope that helps!
