### ISSUE TITLE
Defining Roles

### ISSUE THREAD

**Issue by coheny** [iomad/iomad#485]
I know this has been raised before, but we need a solution, even if its code based, to define a new mid-level management role for IOMAD.... any help is greatly appreciated!
 
We successfully duplicated the company manager role in the Moodle permissions section, and even see the role on the permissions management tab in IOMAD. But we cannot use the role in any way within IOMAD. Has anyone had any success?

**Comment by turf212** [comment]
The roles which can be added through the Iomad dashboard are hard coded into the code so extra roles can't easily be managed from here.  They tie to the mdl_company_user table with a value for each of the manager types which then tie to the default Iomad roles.

**Comment by rmeske** [comment]
I would be interested in this as well.  So, if we wanted to add a role, do we modify the code or the database tables?  I am assuming it will be code based on your answer, can you point to where in the code these roles are defined?

**Comment by turf212** [comment]
There has been a lot of work around the per company roles and templates in 3.3.  Please let me know if this has addressed your issues.
