### ISSUE TITLE
My Courses Block on Dashboard

### ISSUE THREAD

**Issue by coheny** [iomad/iomad#488]
We have IOMAD running with the Essentials theme, with 3 companies and multiple courses (open shared, licensed per company). Company managers allocate licenses to their users and when the user logs in, he/ she is presented with the "My Courses" block on the dashboard (nothing else). All courses are single topic SCORM packages that only return either passed or completed to the system and in turn mark the course as complete (we know cron is running, courses are completed). 

Until the user begins the course, it shows up nicely under "Courses not Started." Once the student starts the course, though, it disappears from the block entirely instead of moving to the "Courses in Progress" heading. 

When students complete their course, the course also does not show up under the "Courses completed" block. It does, however, show up under the My Courses menu on the navigation bar (next to the language options)

Any ideas/ directions on what to check beyond the above?

**Comment by turf212** [comment]
Iomad uses the course completion settings to populate the courses in progress and completed.  These are not the same as the activity completion within the course but are instead based upon this.  Check that you have some conditions for the courses for completion.

**Comment by coheny** [comment]
We do have a course completion condition set. It points to the completion of the single SCORM package in the course. We tried changing the completion requirements to be both when "ALL" or "one of" the conditions are met, the behavior is still the same.

**Comment by turf212** [comment]
cron issue.
