### ISSUE TITLE
Upload users passwords change

### ISSUE THREAD

**Issue by Zenkad** [iomad/iomad#489]
Hi, we're experiencing a strange problem. When we upload with cvs and choose to create new users and update existing, the passwords of existing users are always updated. Even if we choose not to adjust the password in the settings. No mails are send to these existing users so we don't know their passwords.

This only happens on .../blocks/iomad_company_admin/uploaduser.php
If we use .../admin/tool/uploaduser/index.php everything works ok and the passwords are not overwritten.

We use iomad 3.1

**Comment by turf212** [comment]
The checks for the Iomad code may have become out of step with the standard Moodle admin tools.  I'll have this looked into.

**Comment by Zenkad** [comment]
Hi turf212, any news? Kind regards

**Comment by Zenkad** [comment]
Hi Derick, have you had the time to check this? The problem still exists.
