### ISSUE TITLE
Unable to create course

### ISSUE THREAD

**Issue by inkeyes** [iomad/iomad#49]
When trying to create a course, via the IOMAD dashboard, the operation fails with Coding error detected, it must be fixed by a programmer: invalid enrol instance!

Looking at the server log, PHP reports:

[24-Mar-2014 06:08:01 America/New_York] Default exception handler: Coding error
detected, it must be fixed by a programmer: invalid enrol instance! Debug:
Error code: codingerror
- line 1261 of /lib/enrollib.php: coding_exception thrown
- line 203 of /local/iomad/lib/user.php: call to enrol_plugin->enrol_user()
- line 285 of /local/iomad/lib/company.php: call to company_user::enrol()
- line 253 of /blocks/iomad_company_admin/company_course_create_form.php: call to company->add_course()

The ‘manual’ enrolment plugin is enabled, and the default role for that enrolment is ‘student’.

However, we have tested and the bug is not replicated on the IOMAD demo site. The code on our IOMAD evaluation site was pulled from the IOMAD git repo this morning, and the bug still exists.

PHP version:
PHP 5.4.15-1~lucid+1 (cli) (built: May 12 2013 15:48:50)
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2013 Zend Technologies

**Comment by inkeyes** [comment]
Following up. On our site iomad.lms.cm-hosting.com, if we login a site admin, we can see that the course is created, but the role assignments to allow the manager to edit the courses are failing. As said before, the moodle code is a completely clean IOMAD install as pulled from for your github.

**Comment by turf212** [comment]
Thanks for the details.  I'll test this with a clean installation.  What options did you choose (if any) when creating the course?  Was this just a standard course where users needed to be enrolled onto or was this a licensed course?

Also is this the 2.6 or the 2.5 branch?

Thanks

**Comment by inkeyes** [comment]
Branch IOMAD_25_STABLE
Options: only enrolled by manager

That's it.

Cheers, Nick

**Comment by turf212** [comment]
Do you have any managers created prior to creating the course?

**Comment by inkeyes** [comment]
The sequence we've followed is:
Login as site admin
Create a company
Create a company manager
Logout as admin, and login as that manager
Create course

**Comment by turf212** [comment]
OK I've tested that on a completely clean install on 2.5 and used the following
Install
Set up test company
Create test company manager
log in directly as test company manager
Create course

No errors were reported.  Was this a completely clean installation of Iomad or was it an upgrade?

**Comment by inkeyes** [comment]
Ah, there was a problem with initial user settings that was patched. So, in effect, the site has been upgraded. Shall I'll blitz the database and start the site again? Or, do you want me to provide you with more information?

**Comment by turf212** [comment]
There were some changes made to the enrolments logic as creating a course set them up in the opposite as was expected.

The site should have the following enrolment plugins active as default
manual enrolments
guest access
self enrolments
license enrolment

It's likely that one of these is not on (and it's failing because it's expecting it).  Still a bug as it should handle it.

**Comment by inkeyes** [comment]
Hi. Yes, all of the those enrolments were active, which is what threw me when I'd looked at the code myself.
I've just blitz'd our site, and course creation by a company manager works no problem.

**Comment by inkeyes** [comment]
However, we have now found that the course edit functions are fubar'd.
I'll email the login details for the site, but the situation is now as follows:
Created a company manager (teacher)
Logged in as teacher
Created course
Go to course, enable editing
Select edit topic one... after a wait of about a minute, a huge amount of debug code is output to the browser

Summary of Topic 1
Array ( [OUTPUT] => core_renderer Object ( [contenttype:protected] => text/html; charset=utf-8 [metarefreshtag:protected] => [unique_end_html_token:protected] => %%ENDHTML-beHroJsLu1%% [unique_performance_info_token:protected] => %%PERFORMANCEINFO-beHroJsLu1%% [unique_main_content_token:protected] => [MAIN CONTENT GOES HERE - beHroJsLu1] [opencontainers:protected] => xhtml_container_stack Object ( [opencontainers:protected] => Array ( [0] => stdClass Object ( [type] => header/footer [closehtml] =>  

You are logged in as Teachers McWhisky (Logout)

hmp
%%PERFORMANCEINFO-beHroJsLu1%% .
.
%%ENDHTML-beHroJsLu1%% ) ) [log:protected] => Array ( ) [isdebugging:protected] => ) [page:protected] => moodle_page Object ( [_state:protected] => 2 [_course:protected] => stdClass Object ( [id] => 3 [category] => 3 [sortorder] => 10001 [fullname] => Health Management Plus [shortname] => hmp [idnumber] => [summary] => [summaryformat] => 1 [forma etc etc

**Comment by turf212** [comment]
That's something else.  I'll close the original issue and create a new one for that, however, I have tried that on the same valina site and not got any errors editing topic 1 as a teacher.
