### ISSUE TITLE
What is the "List of company domains" in Company creation/edit for

### ISSUE THREAD

**Issue by delvon** [iomad/iomad#492]
Is this to use sub-domains to have different urls for each company? 
I am looking to use multiple companies but want them to have their own URLs but not sure if this is what happens for this input field.

Or do I have write my own script to use rewrite rules to do this?

Thanks,
Delvon

**Comment by turf212** [comment]
The company domains are for putting people into the correct company when you are allowing users to create their own accounts.  It matches the email domain with the domain in a company and, if they are the same, put the user into that company.

For the single URL, Moodle/Iomad can only allow you to have a single URL which it uses to create all of the links on the site.  If you do get an Apache rewrite set working, could you please post here?

Thanks!

**Comment by delvon** [comment]
Thanks for your response. If we get around to doing that I will post here.

**Comment by turf212** [comment]
Perfect.  Thanks!

**Comment by Ayasaad** [comment]
does the list of company domains allow more than one domain per company ? if so is it comma seperated ?
