### ISSUE TITLE
Update iomad

### ISSUE THREAD

**Issue by aidadbi** [iomad/iomad#493]
Hello,
I use IOMAD and I have an old version.
How do I update for the latest version.

Thanks.
Aida

**Comment by turf212** [comment]
Hi Aida,

Iomad upgrades follow the same method as for Moodle upgrades.  Backup your site first and then you can do one of the following.

If you are using git you can checkout the new version as a new branch on your repository and then click on site administration -> notifications (if you are not prompted with the upgrade pages)

or

You can download the new version of the code to a new directory on your web-server, copy over your config.php file and then switch this new directory with your current html directory on your webserver and again click on notifications on your site.

Please note - if you have any additional Moodle packages installed you will need to make sure these are in the appropriate places in the new code or branch before running the upgrade.
