### ISSUE TITLE
Error when trying to access course that I have been assinged a license in a course

### ISSUE THREAD

**Issue by delvon** [iomad/iomad#496]
Good day,

Hope someone can help with this.

When I try to access the course it times out and gives the error below. This does not happen if the user is enrolled manually through IOMAD, only when they are assigned a license.

Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 84 bytes) in /opt/bitnami/apps/..../lib/dml/mysqli_native_moodle_database.php on line 1180

Just to add that when I check the course as an admin the user was not enrolled on the course as a licensed user so something seem to have gone wrong. I have created the license and went as far as assigning the license to the user but the user was not enrolled on the course when that was done.

**Comment by turf212** [comment]
Something strange is happening in your data.  The query is taking up all of the PHP allowed memory and then fails.   Can you confirm if there is only licensed access enrolment allowed on the course?  This should be the only enrolment method used for a licensed course.

**Comment by delvon** [comment]
The only time I can access an IOMAD course is if it is assigned manually. Whenever I assign a license for the user it does not work and I have check the course and it doesn't show that the user is enrolled.

The licensed enrollment method was the only method on the course at the time.

**Comment by turf212** [comment]
Can you please detail exactly the steps you are undertaking and I'll test this.

Thanks!

**Comment by delvon** [comment]
I used a new database recently and reinstalled IOMAD and then I followed the steps here http://www.iomad.org/wp-content/uploads/2014/05/Iomad_Get_start.pdf.

I then logged in as a user/admin that has been assigned the license for the course and when I click on 
the course name under 'Courses not started' I get an infinite loop until it gives the memory error above.

I have tried it many times but sometimes I get in but then some users get the error. What I know though that once it happens for one user on a course it happens for all of them. I have checked the enrollment method and even when it is only license, it does not work.

I have tried closed sharing and open sharing but same error.

I get this error one time on firefox but not always:

get_role_users() without specifying one single roleid needs to be called prefixing role assignments id (ra.id) as unique field, you can use $fields param for it.

    line 3815 of /lib/accesslib.php: call to debugging()
    line 315 of /enrol/license/lib.php: call to get_role_users()
    line 250 of /enrol/license/lib.php: call to enrol_license_plugin->email_welcome_message()
    line 72 of /enrol/index.php: call to enrol_license_plugin->enrol_page_hook()

Regards,
Delvon

**Comment by delvon** [comment]
Has anyone ever had this issue with the infinite loop when try to access a licensed course or the first time?

**Comment by turf212** [comment]
this was a data issue.  Fixed under support.
