### ISSUE TITLE
Show different certificates for repeat courses

### ISSUE THREAD

**Issue by delvon** [iomad/iomad#497]
Hi all,
The features mentioned: "User course completion archiving. Iomad will archive all user course completions to a separate location, recording course grades and any certificates achieved. This will allow for users to repeat course, such as for compliance, without losing any previous results."

In the IOMAD completion report it has a feature to display historic results but where are these stored in the database and even when I select this I am not sure how historic completion will be shown and the certificates for repeat courses.

Can someone please explain this?

**Comment by turf212** [comment]
The historic results get displayed in the same way as for the results for users currently enrolled on the courses.  We are tucking away the completion info in the local_iomad_track tables along with a copy of the certificate (if you are using the Iomad certificate).  This is created when the user is marked as having completed the course, which means you are safe to clear down the current course activities for the user who has completed.

**Comment by delvon** [comment]
Does that mean that the certificate would then have to be a different activity (have a different course module ID) for it to show multiple certificates for the same user?

**Comment by turf212** [comment]
no, if you clear the user's course responses down it will clear down the course certificate but not the saved certificate (sorry thread from the dead).

**Comment by pamaher** [comment]
I'm trying to use the feature mentioned above: "User course completion archiving. Iomad will archive all user course completions to a separate location, recording course grades and any certificates achieved. This will allow for users to repeat course, such as for compliance, without losing any previous results."

Can you point me to how to do this? I see that the mdl_local_iomad_track table has lots of data -- but when a user retakes a class, they don't get a new certificate. Is there a setting I need to select to enable users to repeat a course and get a new certificate?
