### ISSUE TITLE
Editing topic 1 as a teacher produces this error

### ISSUE THREAD

**Issue by turf212** [iomad/iomad#50]
However, we have now found that the course edit functions are fubar'd.
I'll email the login details for the site, but the situation is now as follows:
Created a company manager (teacher)
Logged in as teacher
Created course
Go to course, enable editing
Select edit topic one... after a wait of about a minute, a huge amount of debug code is output to the browser

Summary of Topic 1
Array ( [OUTPUT] => core_renderer Object ( [contenttype:protected] => text/html; charset=utf-8 [metarefreshtag:protected] => [unique_end_html_token:protected] => %%ENDHTML-beHroJsLu1%% [unique_performance_info_token:protected] => %%PERFORMANCEINFO-beHroJsLu1%% [unique_main_content_token:protected] => [MAIN CONTENT GOES HERE - beHroJsLu1] [opencontainers:protected] => xhtml_container_stack Object ( [opencontainers:protected] => Array ( [0] => stdClass Object ( [type] => header/footer [closehtml] =>

You are logged in as Teachers McWhisky (Logout)

hmp
%%PERFORMANCEINFO-beHroJsLu1%% .
.
%%ENDHTML-beHroJsLu1%% ) ) [log:protected] => Array ( ) [isdebugging:protected] => ) [page:protected] => moodle_page Object ( [_state:protected] => 2 [_course:protected] => stdClass Object ( [id] => 3 [category] => 3 [sortorder] => 10001 [fullname] => Health Management Plus [shortname] => hmp [idnumber] => [summary] => [summaryformat] => 1 [forma etc etc

**Comment by turf212** [comment]
Tested this on a vanilla installation and didn't get any errors.

What theme are you using for this?

**Comment by inkeyes** [comment]
This even happens with the IOMAD theme. I think our site is totally fried... even the activity list, when editing a course, comes up empty now. I'll try creating a complete fresh new site, directly from the github.

**Comment by turf212** [comment]
What are you using for a webserver/database server?  Is this Linux based?

**Comment by inkeyes** [comment]
Yes, Linux based Ubuntu 12.04.3 LTS
Apache/2.2.14 (Ubuntu) 
MySQL 5.1.69 
PHP 5.4.15-1~lucid+1 (cli) (built: May 12 2013 15:48:50)

**Comment by turf212** [comment]
Same spec as the demo site then.  Just wanted to make sure it wasn't something odd.

**Comment by turf212** [comment]
This was a data issue with their site.  Worked on a clean installation.
