### ISSUE TITLE
iomad dashboard in Italian

### ISSUE THREAD

**Issue by ni-ght** [iomad/iomad#500]
Dear sirs,
Are there language packs for the iomad dashboard, particularly in Italian?
Many thanks.

**Comment by turf212** [comment]
we do not, unfortunately.  If you produce a translation for it could you provide it for everyone else?

**Comment by ccomincini** [comment]
Hi I've done some work translating in italian language:

[iomad_it_translations.zip](https://github.com/user-attachments/files/24498579/iomad_it_translations.zip)

Maybe @turf212  you will want to use it
