### ISSUE TITLE
Upload users question

### ISSUE THREAD

**Issue by churasora** [iomad/iomad#503]
Hi, is it possible to upload users with csv and assign them to sub departments?

**Comment by turf212** [comment]
You can but not from the same CSV.  If you use the Iomad user upload page you can select which department you want the users to be uploaded to.

**Comment by turf212** [comment]
Iomad 3.3 now allows for the department shortname to be added in a department column which will put the users into those departments. If the manager cannot manage that department, or the departmen doesn't exist, it reverts back to the default selected department.
