### ISSUE TITLE
Company Logo and Custom Company CSS

### ISSUE THREAD

**Issue by jaychurch** [iomad/iomad#507]
Hi there,
I'm using iomadboost as my theme but cannot get the logo or custom .css to appear in the front end. Is there a further setting I need to enable for this to work?

Grab attached shows:
Edit > Company > Appearance
![screen shot 2017-04-24 at 11 29 34](https://cloud.githubusercontent.com/assets/10885089/25333226/5c202e44-28e1-11e7-9888-23336a69af4c.png)

**Comment by jaychurch** [comment]
...second grab shows front end without custom css rules being applied - Body Background color / Page header h1 font size and color.
![screen shot 2017-04-24 at 11 32 23](https://cloud.githubusercontent.com/assets/10885089/25333398/f165b334-28e1-11e7-993f-051a15ff3f82.png)

**Comment by turf212** [comment]
Definitely a bug.  Closed as part of the duplicate #509
