### ISSUE TITLE
Several issues with competency frameworks in courses

### ISSUE THREAD

**Issue by turf212** [iomad/iomad#512]
able "company_framework_groups" does not exist
Debug info: 
Error code: ddltablenotexist
Stack trace:
·         line 645 of /lib/dml/moodle_database.php: dml_exception thrown
·         line 1330 of /lib/dml/moodle_database.php: call to moodle_database->where_clause()
·         line 109 of /blocks/iomad_company_admin/iomad_frameworks_form.php: call to moodle_database->get_records()

**Comment by ni-ght** [comment]
I believe all '$companytemplates' variables in 'competency/classes/course_competency.php' should be '$companyframeworks'.

https://github.com/iomad/iomad/blob/IOMAD_32_STABLE/competency/classes/course_competency.php#L337

https://github.com/iomad/iomad/blob/IOMAD_32_STABLE/competency/classes/course_competency.php#L412

Thanks
