### ISSUE TITLE
Coding error assign_users webservice

### ISSUE THREAD

**Issue by jnoone** [iomad/iomad#533]
In the file 
/blocks/iomad_company_admin/externallib.php

the method for block_iomad_company_admin_assign_users was not working correctly.  It appeared that the code to access the array of users was not correct. I looked at the code and made the following changes.

the validate_parameters used to read
`$params = self::validate_parameters(self::assign_users_parameters(), $users);`

I changed it to
`$params = self::validate_parameters(self::assign_users_parameters(), array('users' => $users));`

The foreach block used to read
`foreach ($users as $userrecord)`

I changed it to
`foreach ($params['users'] as $userrecord)`

To access the array it used to do
` if (empty($userrecord->userid) || empty($userrecord->companyid))`

I changed it to
`if (empty($userrecord['userid']) || empty($userrecord['companyid']))`

throughout the foreach block the access of the array will need to change.

There are also a few other places in the code that deal with users that are written in correctly.

**Comment by turf212** [comment]
Thanks for finding and fixing.  I'll add these changes in now.
