### ISSUE TITLE
Iomad 3.2: files_rendered.php functions need to be protected and not private

### ISSUE THREAD

**Issue by rosa2** [iomad/iomad#534]
Hello

When I go to edit or create a Company I get this error, in Iomad 3.2

`Fatal error: Access level to theme_bootstrap_core_files_renderer::fm_print_generallayout() must be protected (as in class core_files_renderer) or weaker in /var/www/html/xxx/theme/bootstrap/renderers/files_renderer.php on line 914`

If I change all functions on that file from private to protected, it works. I had to make it also in /var/www/html/xxx/theme/iomadbootstrap/renderers/files_renderer.php . I had made it one by one and tested that all private functions in that file had to be chanded.

In /var/www/html/xxx/theme/boost/classes/output/core/files_renderer.php they were already protected.

Thanks for your time :)

**Comment by turf212** [comment]
Which version is this for?  The functions in the 3.2 iomadbootstrap files_renderer.php are for the most part private.  Only the file picker ones are not.

grep " function " theme/iomadbootstrap/renderers/files_renderer.php
    private function fm_print_generallayout($fm) {
    private function fm_js_template_iconfilename() {
    private function fm_js_template_listfilename() {
    private function fm_js_template_mkdir() {
    private function fm_js_template_message() {
    private function fm_js_template_fileselectlayout() {
    private function fm_js_template_confirmdialog() {
    public function filemanager_js_templates() {
    private function fp_js_template_generallayout() {
    private function fp_js_template_iconfilename() {
    private function fp_js_template_listfilename() {
    private function fp_js_template_nextpage() {
    private function fp_js_template_selectlayout() {
    private function fp_js_template_uploadform() {
    private function fp_js_template_loading() {
    private function fp_js_template_error() {
    private function fp_js_template_message() {
    private function fp_js_template_processexistingfile() {
    private function fp_js_template_processexistingfilemultiple() {
    private function fp_js_template_loginform() {
    public function filepicker_js_templates() {
