### ISSUE TITLE
Site announcements by company

### ISSUE THREAD

**Issue by rosa2** [iomad/iomad#536]
Hello

I would like site announcements by Company in the front page, but I am not able to find how. When an announcement is made, all companies people see it. Could you please help to me? Thanks

**Comment by rosa2** [comment]
I learned how to make it. The home page is course 1 and you have to make a group for each company. Then, when you publish an announcement you can choose if it is for all or for a group. That means that you have to import all the students of a company to its group.

It would be very nice if Iomad made this automatically. I mean that when you create a company, a group was created in the course 1 and when you import students to a company they were assigned to that group.

Tomorrow I will keep working on this and if I find something relevant, I will tell. Thanks for the tool :)

**Comment by turf212** [comment]
You can also use the iomad html block and select which companies it is set for.  The front page course in Moodle (and therefor Iomad) is probably not the best place to be doing this.  Especially as everything moves over more to the dashboard.
