### ISSUE TITLE
3.2 : Group despcription is not translated when creating a course group for a company

### ISSUE THREAD

**Issue by rosa2** [iomad/iomad#537]
Hello and sorry for my English :)

I am checking how Iomad has been working in one installation in catalan language and I see that all groups descriptions are in English. I found in local/iomad/lib/company.php line 1584
`        $data->description = "Course group for ".$company->name;`
So I changed there to
`        $data->description = get_string('coursegroup', 'local_iomad').$company->name;`
And create the string in  local/iomad/lang/en in the last line
`        $string['coursegroup'] = 'Course group for ';`

Thanks for this useful distribution :)

**Comment by rosa2** [comment]
Just in case someone has this problem, I run a SQL in the database to change all occurrences. 
UPDATE `mdl_groups` SET `description` = replace( `description` , 'Course group for', 'Grup del curs per' );

**Comment by turf212** [comment]
Thanks for this.  I'll get that added to core. :)
