### ISSUE TITLE
3.2: Manage Iomad course settings: features request

### ISSUE THREAD

**Issue by rosa2** [iomad/iomad#538]
Hello :)

I would like to suggest two features for increasing the Manage Iomad course settings usability.

- Instead of having a form for each record option, it would be much faster if you have to change several courses to have the options in the top an a check box for each record. After selecting the courses that you want to change, you could choose the option on the top and send the form. In my case I had to make 20 courses open and it mean to load the page 20 times... :)
- Sorting the rows by course alphabetical order. I had to find courses with the web browser on the page... 

Thanks a lot for the distribution, have a nice day!

**Comment by turf212** [comment]
We've made the page sortable and added a course search in 3.6.  Bulk actions is next.
