### ISSUE TITLE
Competency frameworks in courses

### ISSUE THREAD

**Issue by ni-ght** [iomad/iomad#540]
Probably a typo. I believe all '$companytemplates' variables in 'competency/classes/course_competency.php' should be '$companyframeworks'.

https://github.com/iomad/iomad/blob/IOMAD_32_STABLE/competency/classes/course_competency.php#L337

https://github.com/iomad/iomad/blob/IOMAD_32_STABLE/competency/classes/course_competency.php#L412

Thanks

**Comment by turf212** [comment]
It is indeed a copy paste error.  Thanks for highlighting it!
