### ISSUE TITLE
3.2 Iomad's report is not displayed.

### ISSUE THREAD

**Issue by syusanjun** [iomad/iomad#542]
Iomad's report is not displayed.

local/report_completion/index.php
local/report_license/index.php

**Comment by ni-ght** [comment]
Hello. Do you get an error? A blank page? (have you enabled debug messages?)
Could you include attach a screenshot?

**Comment by syusanjun** [comment]
/local/report_license/index.php

Parse error: syntax error, unexpected ':', expecting ';' or '{' in /var/www/html/remote/local/iomad/pchart2/class/pDraw.class.php on line 619
----------------------------------

/local/report_completion/index.php

Parse error: syntax error, unexpected ':', expecting ';' or '{' in /var/www/html/remote/local/iomad/pchart2/class/pDraw.class.php on line 619
-----------------------------------

**Comment by turf212** [comment]
This is likely a PHP version error.  What version of PHP are you using on your server?  Iomad?
Pchart is an external class which we have brought in for the reports and there is a PHP 7 version on the Iomad 32 branch which works but may cause issues with earlier version of PHP.  You can simply lift the pchart version from an earlier branch to replace it.

**Comment by watcanz** [comment]
I am having this error with Iomad 3.3.  Server is using PHP 5.6.30.  What files/folder of pchart would we lift from a previous version?
