### ISSUE TITLE
 Assign company competency frameworks - Error: Not Found

### ISSUE THREAD

**Issue by ni-ght** [iomad/iomad#544]
When in 'lomad Dashboard - Assign company competency frameworks',

I get:
    Error: 
    Not Found
    The requested URL /blocks/iomad_company_admin/company_competencies_frameworks_form.php was not found on this server

This is probably a typo, in the file 'company_competency_frameworks_form.php', line 151
    < $linkurl = new moodle_url('/blocks/iomad_company_admin/company_competencies_frameworks_form.php');
    ---
    > $linkurl = new moodle_url('/blocks/iomad_company_admin/company_competency_frameworks_form.php');

Thanks

**Comment by turf212** [comment]
was a typo in both.
