### ISSUE TITLE
theme_iomad_get_html_for_settings function is undefined in file theme/iomadbootstrap/layout/default.php

### ISSUE THREAD

**Issue by blueyestar** [iomad/iomad#553]
When I use iomad bootstrap theme and login as student, 500 error return on page /my,
I think this error is caused by the function theme_iomad_get_html_for_settings undefined in file theme/iomadbootstrap/layout/default.php

**Comment by turf212** [comment]
Which version is this for?

**Comment by blueyestar** [comment]
It's for IOMAD_32_STABLE.

**Comment by turf212** [comment]
It's not finding the code to generate the HTML from the company.  Fixing and pushing.
