### ISSUE TITLE
All form definitions need checked to make sure setType() defs are correct

### ISSUE THREAD

**Issue by thepurpleblob** [iomad/iomad#56]
Noticed that a significant number of setType() calls are setting an inappropriate data type for the field. Worth running through them all and checking.

**Comment by turf212** [comment]
Testing for 3.0 showed no issues for this.

**Comment by thepurpleblob** [comment]
Hello,

There is some helpful stuff I just found on the web, you may like it too, please read here http://advance.nezmat.com/e4qbsfr

Best, howard@e-learndesign.co.uk
