### ISSUE TITLE
ecommerce question

### ISSUE THREAD

**Issue by mlapl1** [iomad/iomad#560]
I apologize, but I am quite new to Iomad though not to moodle.

I have tried to register a course on the ecommerce system but once I register it, I cannot see it (although it shows one course registered in the iomad dashboard).

I am using the latest open source code and I have attributed the course to a company. Also, I cannot see the "shop".

Clearly I am missing some information - but cannot find it in my google searches.
I would appreciate any advice - thank you - andrew

**Comment by turf212** [comment]
You need to add the shop block somewhere on the site so users can access it.  Edit a page (e.g. the site's front page) and add the eCommerce block.

**Comment by gaurav12y** [comment]
HI i am new in IOMAD,
I have question about IOMAD courses, How to sell courses on IOMAD through eCommerce Courses.

Thanks
