### ISSUE TITLE
User Enrollment

### ISSUE THREAD

**Issue by blueyestar** [iomad/iomad#567]
Version: IOMAD_32_STABLE

When assigning users to courses from this url:
 /iomad/blocks/iomad_company_admin/company_course_users_form.php

- Add a student from the right column and click the Enrol button, but the selected student is not shown in the left column. However, if you refresh the page, the selected user appears in the left column (Unenrol button has similar issue).
- The Group field does not load any company groups other than the default group in the dropdown field.

**Comment by turf212** [comment]
There are a couple of things at play here.  1 The form is not being recreated after processing when it should be, 2 the groupid should be getting posted to the form and 3 a course which is not shared doesn't matter for these groups.
