### ISSUE TITLE
Should manage companies screen also link to other functions...

### ISSUE THREAD

**Issue by thepurpleblob** [iomad/iomad#576]
Rather than having to select the current company and then (e.g.) edit company (possibly others). The 'manage companies' screen could link directly there. For site admins this would be more intuitive and also save a few clicks.

**Comment by turf212** [comment]
Probably.  Top level company managers can manage more than one company so it would also need to work for them.  At the moment they get the same dropdown as an admin but only showing the company they belong to.

**Comment by turf212** [comment]
Company overview report is a likely candidate.  Managers can then look at their own companies information.

**Comment by turf212** [comment]
I've added code in 3.3 to show the company overview report and also to allow the user to select the company from a button (instead of the drop down).

**Comment by turf212** [comment]
this now has overview report, suspend, manage (same as selecting from drop down), create child and suspend.
