### ISSUE TITLE
Remove try..catch blocks from company_edit_form

### ISSUE THREAD

**Issue by thepurpleblob** [iomad/iomad#577]
blocks/iomad_company_admin/company_edit_form.php

This has a couple of try..catch blocks for dealing with invalid/broken themes. There is a rarely a sound reason for using this construct as it tends to mask an underlying problem that could surface in some subtle way later. Remove these blocks and handle any theme errors properly - or simply surface the error and allow the admin to deal with it.

**Comment by turf212** [comment]
agreed.  This is very old code from the first incarnation.  blame M. :)
