### ISSUE TITLE
Need registration page for company managers

### ISSUE THREAD

**Issue by harshitnayak45** [iomad/iomad#581]
How can i add or enable registration for company managers, from which they have registered their companies. Please suggest more on this.

**Comment by harshitnayak45** [comment]
Do you have any suggestion for me ? Let me know asap.

**Comment by turf212** [comment]
There currently isn't a way for companies to be created except by the site administrator or through the use of web-services.   User's cannot create their own company and assign themselves as a company manager.

**Comment by harshitnayak45** [comment]
@turf212  From iomad sighup can we only add company manager. I have disabled the student registration. Please suggest

**Comment by harshitnayak45** [comment]
is their any way so we can send registration links for company managers?

**Comment by turf212** [comment]
As I say, there is no way to create a new company manager or company via the sign up or other methods.  For a start, this could present a large security issue.

Once a company is set up by the site admin and a company manager created, the company manager an create more company managers.  If you want to manage this outside of the interface, you can use the webservice calls to do this.

**Comment by harshitnayak45** [comment]
Hello @turf212 ,
How can i enable eCommerce section. I have configure the setting for eCommerce block but eCommerce block are not showing  on add a block list. Can you suggest me how eCommerce will work with courses. Please guide me step by step so i can enable that.

**Comment by harshitnayak45** [comment]
Also i have enable shop page and found some coding error message check here https://drive.google.com/file/d/0B3fOUuwQLX0-WkZ3cnhvdjlmb1k/view?usp=drivesdk

**Comment by turf212** [comment]
Looks to be a data issue.  Do you have any courses added to the shop?

**Comment by harshitnayak45** [comment]
Yes i have added one course but got that error

**Comment by harshitnayak45** [comment]
Error :   Coding error detected, it must be fixed by a programmer: count_records_sql() expects the first field to contain non-negative number from COUNT(), '' found instead.

**Comment by harshitnayak45** [comment]
I have added courses but all the course_shop tables are empty. Can you please suggest more on this.

**Comment by harshitnayak45** [comment]
Hi @turf212 ,

Can you please help me on that. I need a solution ASAP.

Thanks

**Comment by harshitnayak45** [comment]
Courses are not adding to the shop. Please help.

**Comment by harshitnayak45** [comment]
After adding course to eCommerce , i have seen this https://drive.google.com/file/d/0B3fOUuwQLX0-OGR2VFhXN0UzeTQ/view?usp=drivesdk. no course on the list.

**Comment by harshitnayak45** [comment]
I have changed the theme but nothing happens. Can you please suggest more on this. Please respond me ASAP.

**Comment by harshitnayak45** [comment]
also when i click on more information about error, i have found "Block type ... has been disabled by the administrator". Please suggest

**Comment by harshitnayak45** [comment]
On Iomad demo , i have added one course and add that course to eCommerce course list but thats not added to shop setting. please check and let me know.

**Comment by harshitnayak45** [comment]
Helloooo,

can you please suggest me .  i am in trouble now. please

**Comment by thepurpleblob** [comment]
That link is to Google Drive. It's nothing to do with Moodle/Iomad

**Comment by harshitnayak45** [comment]
thats the screenshot. My issue is :  After adding course to eCommerce, none of course added to shop and also on course list of eCommerce. Also the database tables are empty.

**Comment by harshitnayak45** [comment]
www.siteurl/blocks/iomad_commerce/edit_course_shopsettings_form.php?createnew=1 did not added any of the course.

**Comment by harshitnayak45** [comment]
hi @thepurpleblob 
Do you have any suggestion for me? Please i need a solution urgently.

**Comment by bambang150** [comment]
I am on IOMAD 3.3.5

have this issue been solved yet?  Currently I have the same issue with same response as below:
Coding error detected, it must be fixed by a programmer: count_records_sql() expects the first field to contain non-negative number from COUNT(), '' found instead.

And also

the invoice is not emailed to the buyers while the email setting on moodle is working according to Email Test plugin

and also cannot change unpaid to paid status in Order section
