### ISSUE TITLE
Notices thrown when purchasing a course through eCommerce

### ISSUE THREAD

**Issue by thepurpleblob** [iomad/iomad#59]
Purchasing a single course results in...

( ! ) Notice: Undefined property: stdClass::$invoice_enabled in /Library/WebServer/Documents/iomad26/blocks/iomad_commerce/lib.php on line 170
Call Stack
# Time    Memory  Function    Location

1   0.0002  252936  {main}( )   ../basket.php:0
2   0.6790  52591864    get_enabled_payment_providers_instances( )  ../basket.php:75
3   0.6790  52591896    get_enabled_payment_providers( )    ../lib.php:184
4   0.6791  52592608    payment_provider_enabled( ) ../lib.php:176

( ! ) Notice: Undefined property: stdClass::$paypal_enabled in /Library/WebServer/Documents/iomad26/blocks/iomad_commerce/lib.php on line 170
Call Stack
# Time    Memory  Function    Location

1   0.0002  252936  {main}( )   ../basket.php:0
2   0.6790  52591864    get_enabled_payment_providers_instances( )  ../basket.php:75
3   0.6790  52591896    get_enabled_payment_providers( )    ../lib.php:184
4   0.6793  52592640    payment_provider_enabled( ) ../lib.php:176

**Comment by turf212** [comment]
Its returning a $CFG-> item without checking if its empty first.  Fixing and pushing.
