### ISSUE TITLE
Courses not added to shop

### ISSUE THREAD

**Issue by ankitkatmore** [iomad/iomad#590]
I have added courses to shop page but they are not added to the shop. Also the mdl_course_shopsettings table is empty too. Can you please let me know whats going on here.

**Comment by ankitkatmore** [comment]
Hello @turf212 ,

You there. Can you please help me.

**Comment by ankitkatmore** [comment]
I have checked the Iomad demo , add one course but that are not added to eCommerce part.

**Comment by harshitnayak45** [comment]
I have fixed the issue at my end, form action url is wrong that should be self url. Can you let me know how can i change form action URL ?

**Comment by ankitkatmore** [comment]
Working for me , thanks
