### ISSUE TITLE
Company not displayed in iomad dashboard

### ISSUE THREAD

**Issue by noctilux86** [iomad/iomad#599]
hi all, 

when i select iomad dashboard, it appear that no company is selected. 
but when i open the admin panel, manage company, the companies are there.

anyone can help me?

**Comment by turf212** [comment]
Did you select any of the companies from the company picker?  
![image](https://user-images.githubusercontent.com/1685229/29025652-bbdc305e-7b6f-11e7-82ae-79fa60efc35d.png)

**Comment by noctilux86** [comment]
![img_3789](https://user-images.githubusercontent.com/30791064/29034315-8e3d1324-7bca-11e7-8c9d-61984c27fe84.PNG)


There is no company picker..

**Comment by turf212** [comment]
You have broken your iomad Dashboard.  The iomad company admin block has been removed from it which means you are not getting any of the company management menus or pages.  Un-install and then re-install the local iomad company dashboard plugin.  (you don't want to remove the files just uninstall it from the installation)

**Comment by noctilux86** [comment]
thanks for the clarification. will try to do it.
however, what is the possible cause for this? because we have few admin and they are pointing each other, deleted the thing.

**Comment by turf212** [comment]
One of your admins has deleted the block from the page.  If you look at the log reports it will tell you who.

**Comment by noctilux86** [comment]
i've been looking for the log report for the past few days, and couldnt find anyone that did it.. kindly help me on this
