### ISSUE TITLE
Error message when creating course

### ISSUE THREAD

**Issue by MathiasLarsson** [iomad/iomad#60]
Hi! I plyed around a bit with IOMAD and suddenly this error message was shown when i was trying to create a course within IOMAD: 

Debug info: SELECT \* FROM {course_categories} WHERE id = ?
[array (
0 => '4',
)]
Error code: invalidrecord
Stack trace:

```
line 1403 of /lib/dml/moodle_database.php: dml_missing_record_exception thrown
line 1379 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()
line 2476 of /course/lib.php: call to moodle_database->get_record()
line 194 of /blocks/iomad_company_admin/company_course_create_form.php: call to create_course()
```

**Comment by turf212** [comment]
This sounds like you have gone in and deleted the category which was automatically created for the company.  This is by default where company courses are created.

**Comment by MathiasLarsson** [comment]
Ok, and how can i recreate the course? Reinstallation?

**Comment by turf212** [comment]
Need to recreate the category and assign it to the company within the database in the mdl_company table as the company_category field.
