### ISSUE TITLE
useredit_update_picture() is deprecated.

### ISSUE THREAD

**Issue by turf212** [iomad/iomad#601]
useredit_update_picture() is deprecated. Please use core_user::update_picture() instead.
line 200 of /user/editlib.php: call to debugging()
line 222 of /blocks/iomad_company_admin/editadvanced.php: call to useredit_update_picture()

**Comment by thepurpleblob** [comment]
I think I fixed this in the 3.3 version so it may just be a cherry-pick. Unless you know different!

**Comment by turf212** [comment]
OK.  Can leave it to be fixed in 33.  It's just a notice at the moment.
