### ISSUE TITLE
Clean install of IOMAD_32_STABLE cannot create company.

### ISSUE THREAD

**Issue by Aelrath** [iomad/iomad#624]
Hi

I've tried doing install of IOMAD_32_STABLE a few times of the past few days, most recent with - commit baa66b3 being the latest pull update. It seems like the company table never gets created, but other IOMAD tables do get created like company_course etc. Going to the dashboard after running the install.php (and all standard moodle configs are done) the website loads but going to the IOMAD dashboard brings up following error in debug mode:

`Debug info: Column 'shortname' cannot be null
INSERT INTO mdl_department (shortname,name,company,parent) VALUES(?,?,?,?)
[array (
0 => NULL,
1 => NULL,
2 => NULL,
3 => 0,
)]
Error code: dmlwriteexception
×Stack trace:
line 482 of /lib/dml/moodle_database.php: dml_write_exception thrown
line 1259 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()
line 1305 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->insert_record_raw()
line 699 of /local/iomad/lib/company.php: call to mysqli_native_moodle_database->insert_record()
line 930 of /local/iomad/lib/company.php: call to company::initialise_departments()
line 174 of /blocks/iomad_company_admin/company_edit_form.php: call to company::get_company_parentnode()
line 204 of /lib/formslib.php: call to company_edit_form->definition()
line 45 of /blocks/iomad_company_admin/company_edit_form.php: call to moodleform->__construct()
line 515 of /blocks/iomad_company_admin/company_edit_form.php: call to `company_edit_form-`

I'm using mysql 5.0.11 with php 7.0.22.

**Comment by turf212** [comment]
Will check it out.  Probably broken in a recent code merge.  Thanks for reporting!

**Comment by turf212** [comment]
Tried a clean install on PostgreSQL  company table looks like :

iomad32=# \d mdl_company
                                       Table "public.mdl_company"
       Column        |          Type          |                        Modifiers                         
---------------------+------------------------+----------------------------------------------------------
 id                  | bigint                 | not null default nextval('mdl_company_id_seq'::regclass)
 name                | character varying(50)  | not null default ''::character varying
 shortname           | character varying(25)  | not null default ''::character varying
 city                | character varying(50)  | not null default ''::character varying
 country             | character varying(2)   | not null default ''::character varying
 maildisplay         | smallint               | not null default 2
 mailformat          | smallint               | not null default 1
 maildigest          | smallint               | not null default 0
 autosubscribe       | smallint               | not null default 1
 trackforums         | smallint               | not null default 0
 htmleditor          | smallint               | not null default 1
 screenreader        | smallint               | not null default 0
 timezone            | character varying(100) | not null default '99'::character varying
 lang                | character varying(30)  | not null default 'en'::character varying
 bgcolor_header      | character varying(7)   | 
 bgcolor_content     | character varying(7)   | 
 theme               | character varying(50)  | not null default ''::character varying
 category            | bigint                 | not null default 0
 profileid           | bigint                 | not null default 0
 suspended           | smallint               | not null default 0
 customcss           | text                   | 
 maincolor           | character varying(20)  | default 'null'::character varying
 headingcolor        | character varying(20)  | default 'null'::character varying
 linkcolor           | character varying(20)  | default 'null'::character varying
 emailprofileid      | bigint                 | 
 supervisorprofileid | bigint                 | not null default 0
 managernotify       | bigint                 | not null default 0
 parentid            | bigint                 | not null default 0
 ecommerce           | smallint               | not null default 0
 custommenuitems     | text                   | 
 managerdigestday    | smallint               | not null default 0
Indexes:
    "mdl_comp_id3_pk" PRIMARY KEY, btree (id)

Install on MySQL 5.7.19 looks like :

mysql> desc mdl_company;
+---------------------+--------------+------+-----+---------+----------------+
| Field               | Type         | Null | Key | Default | Extra          |
+---------------------+--------------+------+-----+---------+----------------+
| id                  | bigint(10)   | NO   | PRI | NULL    | auto_increment |
| name                | varchar(50)  | NO   |     |         |                |
| shortname           | varchar(25)  | NO   |     |         |                |
| city                | varchar(50)  | NO   |     |         |                |
| country             | varchar(2)   | NO   |     |         |                |
| maildisplay         | tinyint(2)   | NO   |     | 2       |                |
| mailformat          | tinyint(1)   | NO   |     | 1       |                |
| maildigest          | tinyint(1)   | NO   |     | 0       |                |
| autosubscribe       | tinyint(1)   | NO   |     | 1       |                |
| trackforums         | tinyint(1)   | NO   |     | 0       |                |
| htmleditor          | tinyint(1)   | NO   |     | 1       |                |
| screenreader        | tinyint(1)   | NO   |     | 0       |                |
| timezone            | varchar(100) | NO   |     | 99      |                |
| lang                | varchar(30)  | NO   |     | en      |                |
| bgcolor_header      | varchar(7)   | YES  |     | NULL    |                |
| bgcolor_content     | varchar(7)   | YES  |     | NULL    |                |
| theme               | varchar(50)  | NO   |     |         |                |
| category            | bigint(20)   | NO   |     | 0       |                |
| profileid           | bigint(10)   | NO   |     | 0       |                |
| suspended           | tinyint(1)   | NO   |     | 0       |                |
| customcss           | longtext     | YES  |     | NULL    |                |
| maincolor           | varchar(20)  | YES  |     | null    |                |
| headingcolor        | varchar(20)  | YES  |     | null    |                |
| linkcolor           | varchar(20)  | YES  |     | null    |                |
| emailprofileid      | bigint(20)   | YES  |     | NULL    |                |
| supervisorprofileid | bigint(10)   | NO   |     | 0       |                |
| managernotify       | bigint(10)   | NO   |     | 0       |                |
| parentid            | bigint(20)   | NO   |     | 0       |                |
| ecommerce           | tinyint(1)   | NO   |     | 0       |                |
| custommenuitems     | longtext     | YES  |     | NULL    |                |
| managerdigestday    | tinyint(1)   | NO   |     | 0       |                |
+---------------------+--------------+------+-----+---------+----------------+
31 rows in set (0.00 sec)

Please note the *minimum* supported version of MySQL for Iomad/Moodle 3.2 is 5.5.31  If you are trying to install on 5.0.11 then there could very well be a large number of issues.

**Comment by Aelrath** [comment]
Hi. Thanks for the reply. So sorry I don't know where I copied that version from but when I checked again after your reply it is:

```
mysql> SELECT @@version;
+-------------------------+
| @@version               |
+-------------------------+
| 5.7.19-0ubuntu0.16.04.1 |
+-------------------------+
1 row in set (0.00 sec)
```

Also checked that the collation is correct : utf8mb4_unicode_ci

I will try and clean my source folder, moodledata and database and try again.

Thanks

**Comment by turf212** [comment]
No problem :)   This is the same set up as I have so please let me know how you get on.  If you edit the config.php file and uncomment the lines : 
$CFG->debug = (E_ALL | E_STRICT);   // === DEBUG_DEVELOPER - NOT FOR PRODUCTION SERVERS!
$CFG->debugdisplay = 1;             // NOT FOR PRODUCTION SERVERS!

before you run the installation it will give any details around the table create failure.

**Comment by Aelrath** [comment]
Ok update. I can confirm now there is a mdl_company table (for some reason the filter in phpmyadmin does not show the table if I just filtered by company so I went to terminal and  did a "SELECT table_name FROM information_schema.tables" on my db and can see it. (I actually did have those debug settings on while trying to debug the issue)

So following the installation instructions after "Local Iomad settings" when going to dashboard to do "Create a company" that is when I get ::

`Debug info: Column 'shortname' cannot be null
INSERT INTO mdl_department (shortname,name,company,parent) VALUES(?,?,?,?)
[array (
0 => NULL,
1 => NULL,
2 => NULL,
3 => 0,
)]
Error code: dmlwriteexception
×Stack trace:
line 482 of /lib/dml/moodle_database.php: dml_write_exception thrown
line 1259 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()
line 1305 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->insert_record_raw()
line 699 of /local/iomad/lib/company.php: call to mysqli_native_moodle_database->insert_record()
line 930 of /local/iomad/lib/company.php: call to company::initialise_departments()
line 174 of /blocks/iomad_company_admin/company_edit_form.php: call to company::get_company_parentnode()
line 204 of /lib/formslib.php: call to company_edit_form->definition()
line 45 of /blocks/iomad_company_admin/company_edit_form.php: call to moodleform->__construct()
line 515 of /blocks/iomad_company_admin/company_edit_form.php: call to company_edit_form->__construct()`

I'm logged in as the site admin. Do you need to setup an initial company somehow? Because it seems to be looking for a company shortname to create a default department when going to "Create Company".

Sorry I must be missing something.

Thanks

**Comment by turf212** [comment]
Ah!   That's definitely broken.  It should be offering to create a default company.  I've replicated it.  Looking at fixing it now.

**Comment by thepurpleblob** [comment]
It's the same on 3.3 with a new install as well

**Comment by turf212** [comment]
This is due to the autoenrolment courses code recently added.  It's trying to get a company department parentnode on a company which doesn't exist.

**Comment by turf212** [comment]
I'll cherry-pick the fix to the 33 and master branches.
