### ISSUE TITLE
eCommerce - Invoice provider gives fatal error sending invoice mail

### ISSUE THREAD

**Issue by thepurpleblob** [iomad/iomad#63]
Buy something, and go through checkout. When you complete the purchase this happens...

error/No user was specified or the specified user has no email to send invoice_ordercomplete_admin to.

More information about this error

Debug info: 
Error code: No user was specified or the specified user has no email to send invoice_ordercomplete_admin to.
$a contents:
Stack trace:
line 463 of /lib/setuplib.php: moodle_exception thrown
line 161 of /local/email/lib/api.php: call to print_error()
line 76 of /local/email/lib/api.php: call to EmailTemplate->__construct()
line 82 of /blocks/iomad_commerce/checkout/invoice/invoice.php: call to EmailTemplate::send()
line 99 of /blocks/iomad_commerce/review.php: call to invoice->confirm()

**Comment by turf212** [comment]
This is the email which is being sent to the "shop owner" to tell them that someone has ordered a course.  Its using the $CFG->commerce_admin_email setting which is obviously wrong.  I will change this to be the support email address if it is not set and add a setting for it.
