### ISSUE TITLE
Assigning learning plans to students/individual

### ISSUE THREAD

**Issue by skavita** [iomad/iomad#652]
When a company manager is assigning a learning plan to an individual then other company students are also accessible and can be able to assign the learning plans to them too as well.

I don't know if I had missed some settings but I don't want to show other company users to any other company manager

**Comment by turf212** [comment]
Can you please outline the steps you took to get this and I'll have a look as this shouldn't be happening.

**Comment by bambang150** [comment]
I have the same issue too.

1. Create course A with Quiz A activity
2. Set completion requirement on Quiz Activity
3. Create competency frame works
4. Create learning plan
5. Add competency to learning plan
6. Assign related competency in Competencies setting in course A
7. Assign related competency in Quiz A activty
8. Open Iomad dashboard
9. Assign company and student to course A
10. Assignrelated competency to Company A
11. Assign related learning plan to Company A
12. Open Learning Plan and click 0 to assign student to learning plan

And when we want to assign there are students from other company

Please help
