### ISSUE TITLE
Iomad 3.3 Open Sharing courses

### ISSUE THREAD

**Issue by DAhobby** [iomad/iomad#660]
Hello, 
When I open share a course I receive the following message across the top

•	line 1922 of /local/iomad/lib/company.php: call to company::get_company_group()
•	line 160 of /blocks/iomad_company_admin/iomad_courses_form.php: call to company::company_users_to_company_course_group()

and although the course does stay labeled at Open Sharing, it is not.  
Closed Sharing and No both work as expected.  
Any thoughts?

**Comment by turf212** [comment]
Hi 3.3 isn't released yet.  Can you please confirm which version you are using?  (3.2??)

Does the course have any more settings set in Iomad course settings when you make it open shared?

I did get a notice : 
Notice: Undefined property: stdClass::$groupid in /var/www/html/iomad32/local/iomad/lib/company.php on line 1818

Which I'll address in any case.
