### ISSUE TITLE
How to assign a license including courseid

### ISSUE THREAD

**Issue by eqmiso** [iomad/iomad#664]
- it's possible to create a new licence calling block_iomad_company_admin_create_licenses
- how can we link course and licence ? we're looking for this function

We've manged to archive these steps so far:
1. create new company using block_iomad_company_admin_create_companies()
2. create new user using core_user_create_users()
3. assign new created user to created company using block_iomad_company_admin_assign_users()
4. create new license using block_iomad_company_admin_create_licenses() but without link between license and course

**Comment by turf212** [comment]
There was a recent fix (#648) which addressed this.  You supply the courses as part of the payload to the block_iomad_create_licenses call.  If you patch to the latest version the docs will be there for the webservice.

**Comment by actXc** [comment]
I tried this, but it does not work as expected. See pull request #667

**Comment by eqmiso** [comment]
Any news about this issue ? Do you have solution for that problem ?

**Comment by actXc** [comment]
fixed with pull request #724
