### ISSUE TITLE
"id_company" is hidden

### ISSUE THREAD

**Issue by tzumtobel** [iomad/iomad#676]
When open the IOMAD Dashboard I need to select a company. The Dropdown is hidden by default.

<select onchange="this.form.submit()" name="company" id="id_company" aria-hidden="true" style="display: none;">

**Comment by turf212** [comment]
Have you put your admin user into a company?

**Comment by tzumtobel** [comment]
I just put the admin user into a company - nothing changed.

**Comment by tzumtobel** [comment]
This only happens for the admin user. Every other user works perfect.

**Comment by turf212** [comment]
Can you please confirm the version you are using??  I cannot replicate this issue.  (and tried on several different versions)

**Comment by tzumtobel** [comment]
No Prob - please find attached some informations about our environment

<img width="1189" alt="screen shot 2017-09-04 at 08 32 44" src="https://user-images.githubusercontent.com/13078958/30014526-067495dc-914d-11e7-9061-fa0996f32b5c.png">

<img width="1249" alt="screen shot 2017-09-04 at 08 37 39" src="https://user-images.githubusercontent.com/13078958/30014528-06b215ba-914d-11e7-9a82-6b81a19cb418.png">

<img width="904" alt="screen shot 2017-09-04 at 08 38 13" src="https://user-images.githubusercontent.com/13078958/30014527-06b19ca2-914d-11e7-8164-7a7e260e72df.png">

**Comment by tzumtobel** [comment]
We have tried a lot - and find something interesting. If you use a clean IOMAD, this bug does not happen. If you update an IOMAD Installation, then you get it. But we also found a new problem. If you create a new company (brand new IOMAD), we get an error. Please see the attached screenshot.

<img width="1224" alt="screen shot 2017-09-04 at 09 04 37" src="https://user-images.githubusercontent.com/13078958/30015306-6e47c492-9150-11e7-9fd8-2f5884d6ad3b.png">

**Comment by turf212** [comment]
There is a couple of issues here then.  Which version were you upgrading to and from?
The other needs a check to make sure the templates are not empty first...  I'll raise a separate bug.

**Comment by turf212** [comment]
Looks like a theme issue.  You have a display: none; on the select item itself.  If you look at this in developer tools and remove it does the autocomplete dropdown show again?  If so, check the CSS for your current theme as I think that will be what is breaking it.

**Comment by tzumtobel** [comment]
Found the problem. We setup moodle in german. After a new installation, the german language pack was missing. Now we installed the missing language pack and everything works fine.
