### ISSUE TITLE
Issue with bulk user enrolments

### ISSUE THREAD

**Issue by teddielong** [iomad/iomad#680]
I individually sign course to companies and then use the IOMAD user enrolment tab, however, on doing so with larger organisations I am faced with this screen:

How can I bulk enrol users for larger organisations?

**Comment by turf212** [comment]
you can use the upload users csv to do this.  If you select to update the users and select a course to enrol them on it will enrol them all on the course.  You can do the same with a license too.

Failing this you can either filter by department or search for users.   It may be an idea to have the same Allocate all/unallocate all buttons we have for licenses here too.

**Comment by teddielong** [comment]
Thanks for the response.

I like the idea of allocate/unallocate all buttons - that would be a huge time saver!

**Comment by turf212** [comment]
license add all/remove all already been added to code.  Enrol unenrol all is in #855
