### ISSUE TITLE
Navigation Menu is broken.

### ISSUE THREAD

**Issue by blueyestar** [iomad/iomad#684]
In file /lib/navigationlib.php, line 3245

SELECT category FROM {company_course}

There is no category column in table company_course.

The navigation menu is broken because of above issue.

**Comment by turf212** [comment]
Ah, you are correct.  This is being stored in the company table, not the company_course table.

**Comment by turf212** [comment]
Categories listing version is also breaking in the site causing out of memory errors.  lib/navigation.php has been given a little bit of an overhaul.
