### ISSUE TITLE
Questions about assignments

### ISSUE THREAD

**Issue by johankenz** [iomad/iomad#690]
Hi, we've setup a course with the activity assignement. We've created a role for managers to see and grade the submissions of the students. Now we only want them to see the results of their own departement. Now he sees all submissions of all company users. What are we missing in the settings?

**Comment by turf212** [comment]
You need to have the course with forced groups on, have the manager and their students in the company group and disallow the manager role to see other groups.  The client course access role was created for this purpose but I would always recommend that you check and test the capabilities first.
