### ISSUE TITLE
Iomad Dashboard - Manage competency frameworks

### ISSUE THREAD

**Issue by syusanjun** [iomad/iomad#692]
Clicking on the name of the Competency framework results in an error.

The requested URL /framework/view.php was not found on this server.

$release  = '3.2.4 (Build: 20170710)'
$release  = '3.3.1 (Build: 20170710)

・My Server
CentOS release 6.6 (Final)
PHP 7.0.21 
mysql  Ver 14.14 Distrib 5.5.40

**Comment by turf212** [comment]
link is wrong entirely.
