### ISSUE TITLE
Edit User menu - Change course enrolments not working

### ISSUE THREAD

**Issue by tbelgard** [iomad/iomad#697]
When attempting to enroll a user in a course (Change course enrolments) through IOMAD, 'Edit Users', the company manager gets returned to the User Management tab and user is not added to the course.

Process
1. Proceed to Iomad User management tab
2. Click 'Edit users'
3. Click 'User controls' on specific user
4. Click 'Change course enrolments'
5. Click  course on 'Potential courses' and highlight
6. Click Enrol

Outcome:
Company manager is returned to the User Management tab and on verifying the user enrollment the user has not been added.

Expected Outcome:
Company manager will see the new course under the enrolled course list on the left.

**Comment by blueyestar** [comment]
In file /blocks/iomad_company_admin/company_users_form.php
at line 219  

$linkurl = new moodle_url('/blocks/iomad_company_admin/editusers.php');

It should be
$linkurl = new moodle_url('/blocks/iomad_company_admin/company_users_course_form.php');

Otherwise, data will post to editusers.php file.

**Comment by turf212** [comment]
thanks both.  Will get this sorted.

**Comment by turf212** [comment]
The linkurl is correct (as this allows for the user to go back to the editusers page in the breadcrumb but the form shouldn't be using this URL (as mentioned).

**Comment by tbelgard** [comment]
We made the change and implemented it. It fixed the problem but it appears that it caused a new issue. When we use the other method of enrolling users.
Steps 
1. Proceed to the Course management tab
2. Click User enrolments

Error message - Exception - Call to undefined method company::get_menu_courses()

Any ideas? This was not happening prior to the new patch.
Thanks

**Comment by turf212** [comment]
I have not been able to replicate this error in either 3.2 or 3.3.   The method was added in commit 9860ccdba6b8 as part of the work to allow company managers to have a finer control over groups in courses.  Is your company object being set properly?  If you turn full developer debug on (site admin -> developer -> debugging and switch the level to full developer and tick the option to show it) and repeat the action what is the full error?

**Comment by tbelgard** [comment]
Thanks ,

We did some checking and found the issue. You can close this.
