### ISSUE TITLE
User License Allocation UI not appearing for Company Manager and Training Manager

### ISSUE THREAD

**Issue by cboothwi** [iomad/iomad#700]
Using current build as of 2017-09-07. While logged in as a Company Manager or Dept Training Manager, the controls for assigning users to specific licenses are not displayed. The Select license dropdown is displayed. Then, after selecting a license, the message "License is valid for courses: ...." appears, but nothing is displayed below that line. When this occurs, the user profile menu (upper right corner) is also non-functional. The License Allocation UI works properly for the Site Manager.

**Comment by turf212** [comment]
caused by this -  Non-static method company::get_userlevel() should not be called statically in /var/www/html/iomad33/local/iomad/lib/company.php on line 1214
