### ISSUE TITLE
PHP Lint failure

### ISSUE THREAD

**Issue by danmarsden** [iomad/iomad#702]
PHP Parse error:  syntax error, unexpected ''companyid'' (T_CONSTANT_ENCAPSED_STRING), expecting ')' in lib/classes/event/competency_framework_created.php on line 58"

looks like there's a missing comma - but I'm not sure the data array actually exists in the competency_framework class so that line might need to be deleted?

looks like it was added a while ago in this commit:
https://github.com/iomad/iomad/commit/035e3758f1eb0b9854a398e7cd7e4dceb5a825dd#diff-27117eaee6f282763e597f7d8068c304R59

**Comment by danmarsden** [comment]
looks like it's fine on the 3.2 branch, so might be an accidental conflict merge on the 3.3 branch.

**Comment by danmarsden** [comment]
(except that fixing the conflict by adding the comma doesn't resolve the problem of the data array not existing in the class.)

**Comment by danmarsden** [comment]
also same issue in lib/classes/event/competency_template_created.php on line 58 - missing comma and does the data array actually exist?

**Comment by turf212** [comment]
bad cherry pick merge.  Thanks for reporting.  We did add the company info to the event payload in 1e7ee21a401a   in competency/classes/api.php   Much as I don't like adding core code changes, this one was required.

**Comment by danmarsden** [comment]
I presume you tested it in both events? - data was defined as "private" in one of the parent classes.

**Comment by turf212** [comment]
It's working.  The event is being captured for both a framework and a learning plan template being created and an appropriate record is then being put into the iomad_company_comp tables with the respective template/framework id and the company id.  The payload for the event is exactly the same as for core Moodle, we are just injecting the company ID into the object data and then adding it to the event itself.

Where was this being defined as private in the parent classes??

**Comment by danmarsden** [comment]
$data is a private var defined in the core "persistent" class which is the abstrac class used by core_competency\persistent which is used by core_competency\competency_framework class which is the class used in the create_from_framework function in competency_framework_created.php

I noticed it as my IDE highlighted ->data as not existing in the defined class.

**Comment by danmarsden** [comment]
- if it is working as it stands it might be ok and you might just be able to ignore it. (although I suspect you haven't tested that it works in 3.3 as it was definitely broken before) :-)

**Comment by turf212** [comment]
Hi Dan, yes it was tested against 3.3 as this was the version you raised the issue against.  Interesting that this was not found as when I developing this functionality var_dump gave me the values for data (otherwise I wouldn't have used it).  This was 3.1 though so things may have changed.

Looking back the the 3.2 code the data variable in persistent is also private, so something else somewhere must be breaking it and we have been benefiting from that. :/

**Comment by danmarsden** [comment]
great! - probably ok to ignore for now then!
