### ISSUE TITLE
creating users in 3.3 after install causes exception:

### ISSUE THREAD

**Issue by danmarsden** [iomad/iomad#705]
creating a new user straight after installation gives the following error (presume because no companies exist yet - and the first thing I did after install was create another admin user) - user is created but it probably shouldn't throw a nasty error?

Exception - Call to a member function autoenrol() on null

More information about this error

×Debug info: 
Error code: generalexceptionmessage
×Stack trace:
line 88 of /local/iomad_signup/lib.php: Error thrown
line 39 of /local/iomad_signup/classes/observer.php: call to local_iomad_signup_user_created()
line ? of unknownfile: call to local_iomad_signup_observer::user_created()
line 155 of /lib/classes/event/manager.php: call to call_user_func()
line 75 of /lib/classes/event/manager.php: call to core\event\manager::process_buffers()
line 835 of /lib/classes/event/base.php: call to core\event\manager::dispatch()
line 269 of /user/editadvanced.php: call to core\event\base->trigger()
×Output buffer: <br /> <b>Notice</b>: Trying to get property of non-object in <b>local/iomad_signup/lib.php</b> on line <b>40</b><br /> <br /> <b>Notice</b>: Trying to get property of non-object in <b>local/iomad_signup/lib.php</b> on line <b>46</b><br /> <br /> <b>Notice</b>: Trying to get property of non-object in <b>/local/iomad_signup/lib.php</b> on line <b>60</b><br /> <br /> <b>Notice</b>: Undefined offset: 1 in <b>local/iomad_signup/lib.php</b> on line <b>60</b><br /> <br /> <b>Notice</b>: Undefined variable: company in <b>local/iomad_signup/lib.php</b> on line <b>88</b><br />

**Comment by turf212** [comment]
It looks like the event listener in local/iomad_signup should be doing some more sanity checking on new install.  If the authentication type hasn't been defined in the accepted list  (which is blank on clean install) then it should do nothing.  This setting is only available after companies are defined so will resolve all of the above notices.

**Comment by turf212** [comment]
Just checked and 3.2 is the same.  Thanks @danmarsden, will get these patched :)
