### ISSUE TITLE
Phpunit failures (3.3 branch)

### ISSUE THREAD

**Issue by danmarsden** [iomad/iomad#710]
There seems to be a large number of phpunit failures on the iomad branch - a lot of these appear to be related to companyid type issues. attaching a file here with the failures for your reference.
[iomad-phpunit-failures.txt](https://github.com/iomad/iomad/files/1304898/iomad-phpunit-failures.txt)

**Comment by thepurpleblob** [comment]
There's a lot of these relating to the Iomad install creating additional data that PHPunit doesn't expect to be there (example, there are now more than 8 core roles). I'm a bit unsure what the best way to fix this is... possibilities...
- don't create the additional Iomad structures (but that means we can't test them if I ever write some tests)
- hack Moodle core (we try to keep this to an absolute minimum)
- figure some way of not running these tests as part of core tests, rather create new Iomad tests

**Comment by thepurpleblob** [comment]
I have a plan... 
- create a custom phpunit.xml for Iomad
- add <exclude> elements so the failing tests are not run
- copy them to local/iomad/tests and modify them to suit Iomad
- add the new testsuites to the XML file. Add a README
