### ISSUE TITLE
Only site admin can modify courses

### ISSUE THREAD

**Issue by cboothwi** [iomad/iomad#716]
I want to assign a role that includes permissions to modify course content, but without access to iomad and without the power of the site admin.

I created a new user using Moodle's Add User, and then Assign System Roles to assign the Manager role to the user.  It looked like this was going to work, but the courses were not visible to the user-the course categories are empty.  The Moodle Course Editor role had the same result.  I also tried the (iomad) Client Administrator and (iomad) Client Course Editor, but the user did not have access to any of the Site Administration options with these roles.  The only way to allow a user to modify course content is to add the user to the Site Administrators.

Should the standard Moodle roles (Manager, Course Creator) not be used? If not, should they be hidden?
What role would allow modifying course content but not access to iomad?

**Comment by turf212** [comment]
There is the standard teacher role which will allow users to edit course content and handle users in the course.  You need to be careful of this if you want to keep the users hidden from the account.  It's certainly a good starting point for what you want to achieve.   Similarly the course creator role could be used but you would need to test this.  At this point you are dealing with standard Moodle roles and actions.  You just have to make sure you are not giving those users too much access.

**Comment by cboothwi** [comment]
I understand. My problem is that even when a user is assigned the standard Moodle Manager role at the Site level, they still cannot see any courses under any category.  If I Check Permissions for the user in a particular course, it shows they are a Manager in System and Authenticated user in System, and practically all the capabilities are allowed.  They just can't see the course.

If I enroll the user in the course, it shows up under their My Courses, and they can edit it, but it still doesn't show up under the Courses in Site Administration.

The only other way that has worked for me is assigning the user to the Site Administrators, but I don't want to continue doing that.

**Comment by cboothwi** [comment]
Figured out the problem. Even if a user is assigned the default Moodle Manager role, which should have full access to all courses, the courses are only available if they are set to Open sharing in IOMAD.  This is also true for all other roles, such as the Moodle Course creator.  Only the Site Administrator can access all courses if they are not Open Shared.

We will be using Licensing with all of the courses, so Open Sharing will be enabled for each course.  I would expect that the other default Moodle roles, such as Manager, should have access to all courses regardless if Open Sharing is enabled.
