### ISSUE TITLE
Assign department users/managers button confusingly named

### ISSUE THREAD

**Issue by thepurpleblob** [iomad/iomad#72]
If you change either of the drop-downs then (a bit counter-intuitive in itself) you appear to have to press the button underneath labeled "Select department" to update the select screens. You're not selecting the department - you're pressing 'Go' on either of the changes above. Those drop-downs should really self-submit anyway.

**Comment by thepurpleblob** [comment]
Same thing on Course management > User enrolment, except this time worse. If you change the course to enrol users into the "Choose department" button to actually 'lock in' the course selection is now above the course selection drop down so even more likely to be missed/confused.

**Comment by turf212** [comment]
Agreed that the dropdowns should be self submit.  This is an enhancement.
