### ISSUE TITLE
Company Manager Unable to add activity and resources in the course 

### ISSUE THREAD

**Issue by gaurav12y** [iomad/iomad#721]
After click on the add activity and resources blank activity shows please suggest me what to do to resolved this issue.

**Comment by tbelgard** [comment]
I added the Company Manager to the role of Manager for the created Category and they had no problems creating in the course. Hope that helps.

**Comment by turf212** [comment]
You need to be careful with adding the manager role in the company course category.  If you share out courses from there you will then allow those users to to see users from other companies.  Also, if you let them enrol users they will be able to see everyone on the site.

There is a role called client course editor which is based on the editing teacher role which will allow company managers access to edit their courses.  If they have created a course themselves then this role will be automatically assigned to them for that course.  As always, check that the rolsse you are assigning is suitable for your site.

**Comment by tbelgard** [comment]
Thank you for that information Derek


Tammy Belgarde

LMS Manager

PhishMe

O. (571)325-0966

W. <https://phishme.com/> www.phishme.com<http://www.phishme.com>

Connect with Us: Twitter<https://twitter.com/phishme> |LinkedIn<https://www.linkedin.com/company/1550880/> | Facebook<https://www.facebook.com/phishme/><https://twitter.com/phishme>

________________________________
