### ISSUE TITLE
Iomad boost theme not applied to company 

### ISSUE THREAD

**Issue by tbelgard** [iomad/iomad#722]
I have been unable to successfully apply the Iomad bootstrap theme to a company.
This is the process I have used.

1. Theme selected - Iomad boost
2. Create company
       a. Select Iomad boost
       b. Add logo
       c. Select color

Iomad Boost 2016123100
Iomad 2017090304 
Moodle 3.3.2+

No additional logo or changes are added to the users with the company. I attempted the same method of creating a company and adding a logo to a company on the demo.iomad.org and it was successful there.

**Comment by turf212** [comment]
Some of the renderer information work done for the 3.3. Iomad boost theme didn't get brought back into 3.2.
