### ISSUE TITLE
When updating department name, does not change after saved

### ISSUE THREAD

**Issue by richard0096** [iomad/iomad#725]
If I attempt to edit a department name and save the name reverts to the previous value and does not change.

**Comment by turf212** [comment]
I've tested this with 3.2 and 3.3 and have not been able to replicate.  Steps were:
Create a new company called A
Edit company departments
Add a new department called A1
Edit department A1 and change the long name to A10
Edit department A10 and change the short name to A10

Every step was successful.  Are you trying to use non standard characters in your department names?

**Comment by richard0096** [comment]
I've tried multiple times with different names e.g. "test" and it does not seem to work. Perhaps I am running an outdated version of IOMAD. How do I check this?

**Comment by turf212** [comment]
Possibly.  If you click on site administration -> notifications what version of Moodle do you have installed?

**Comment by richard0096** [comment]
I have Moodle 3.1.4 installed.

**Comment by turf212** [comment]
Latest Moodle version for Iomad 3.1 branch is 3.1.7.  Can  you try upgrading to that version and see if this fixes your issue?

**Comment by turf212** [comment]
failing that you can upgrade to latest 3.3 code (which has a load of other nice new features)

**Comment by richard0096** [comment]
Where can i find 3.1.7? 

I can't really upgrade to Moodle 3.3 as it means most of my themes which are used by customers will no longer be compatible.

**Comment by turf212** [comment]
it's the latest version for the 3.1 branch on the download link.  If you used git to bring in your code you just need to do a git pull and it will pull in the patches.

**Comment by richard0096** [comment]
I've just updated to 3.1.7 and still seem to be having the same issue.

**Comment by richard0096** [comment]
Resolved after upgrading to 3.3
