### ISSUE TITLE
As a company admin editing users always shows the same user

### ISSUE THREAD

**Issue by thepurpleblob** [iomad/iomad#73]
User management > edit users:

Whichever user I select 'edit' always produces the _same_ username on the user form ('admin' in this case). The rest of the details look believable - just the username wrong.

**Comment by turf212** [comment]
Checked this using chrome.  The username is appropriate for the user.  This was as both site admin and as company manager.

**Comment by turf212** [comment]
no fault found.  Possibly this is due to browser saving username??
