### ISSUE TITLE
Company Managers CC'ed on emails, cannot turn off

### ISSUE THREAD

**Issue by tbelgard** [iomad/iomad#730]
Company Manager(s) are receiving user emails for user creations and completions (may be others but not sure).  The Company settings:

Send manager emails : None
Send manager digest emails on : None

How can we turn it off so they do not receive the email?
Moodle Version 3.2.5

**Comment by turf212** [comment]
These get sent to the person who created the user accounts.  It's so they can tell what the username was created as and what the password is and, more importantly, that the email was actually sent and is likely in the new users junk folder.   The email settings for the company are more for the reports which get sent out but could be incorporated to the settings.

I'll add a check for the company manager email settings to turn it off if it's set to none.
