### ISSUE TITLE
IOMAD Shop

### ISSUE THREAD

**Issue by Markrico** [iomad/iomad#731]
Hello all,

I was hoping that someone could provide me some directions as to how to set up the IOMAD shop. When I add a course to the shop it does not stick. 
I have tried with open and closed sharing and with paypal on and off as an enrollment method. 

Thank-you, in advance for any insight that you can provide me.

**Comment by turf212** [comment]
have you set the course up to be licensed enrolment type?  The Iomad shop uses licenses to control access.

**Comment by Markrico** [comment]
Thanks Derrick, since I have updated the IOMAD course this is now working.

**Comment by Markrico** [comment]
I meant IOMAD code
