### ISSUE TITLE
Logged in as company admin can't add teaching location

### ISSUE THREAD

**Issue by thepurpleblob** [iomad/iomad#74]
All I see is the headings in the table with no content. I'm not sure if I _should_ be able to add locations (in which case something is broken) or I should _not_ (in which case there needs to be a message to this affect, or the teaching locations option should not be shown at all).

**Comment by turf212** [comment]
Company managers should be able to add locations.  Its driven by standard capabilities, in this case the add teaching location.   It looks like it is missing from the list of default caps for that role.  Will add it in.
