### ISSUE TITLE
[QUESTION] Is it possible to update IOMAD to 3.2 without updating Moodle (current version 3.1)

### ISSUE THREAD

**Issue by richard0096** [iomad/iomad#754]
Is it possible to update IOMAD to 3.2 without updating Moodle (current version 3.1)?

**Comment by thepurpleblob** [comment]
You *could*  grab all the custom Iomad blocks, themes and local plugins from a newer version of Iomad into an older version of Moodle. However, it is completely untested. There's is no guarantee it would work and no support would be available. 

What's stopping you upgrading to Iomad 3.2/3.3 in full?
