### ISSUE TITLE
[QUESTION] keep the default iomad icons

### ISSUE THREAD

**Issue by demontech** [iomad/iomad#755]
Hi Derick,

Is there a way to keep the original default iomad icons that comes with the iomad boost theme when you switch themes?

![image](https://user-images.githubusercontent.com/8148238/32637369-4497ca78-c56e-11e7-8416-f3934550e852.png)

Thanks!!

**Comment by thepurpleblob** [comment]
All the CSS for the icons is built into the theme (along with other custom stuff for Iomad). We generally recommend building custom themes as children of 'iomadboost'. Itself a child of the core Moodle Boost theme. 

If you need to use some other theme entirely you would need to grab some of the CSS and custom renderer code from iomadboost.
