### ISSUE TITLE
Company logo is not visible in RemUI theme

### ISSUE THREAD

**Issue by ajinkyagadewar** [iomad/iomad#756]
How can we show company logo in RemUI theme? Can anybody help us there?

**Comment by thepurpleblob** [comment]
Iomad themes use custom code to pick up and display the company logo. This is not present in 'standard' Moodle themes. RemUI appears to be a commercial theme. It may be possible to modify it to display the logo but this depends on the theme's license. As we do not have access to the theme code it's hard to say.

**Comment by thepurpleblob** [comment]
See https://github.com/iomad/iomad/blob/IOMAD_33_STABLE/theme/iomadboost/classes/output/core_renderer.php

The (Boost) theme renderer has been modified to display the appropriate logo. Similar modifications would need to be made in RemUI (using the linked renderer as a basis). If your license permits ELD would be happy to quote to do the work for you.

**Comment by ajinkyagadewar** [comment]
Yes I have the developer license. I will check the code and revert.

I have some custom requirement as well, how can we talk about it.

**Comment by thepurpleblob** [comment]
Contact us via  info@e-learndesign.co.uk or call 0845 474 4512 :)
