### ISSUE TITLE
Course Overview block (myoverview)

### ISSUE THREAD

**Issue by demontech** [iomad/iomad#768]
Hi

I have installed a brand new instance with the latest commit 6006369 and for some reason the Course Overview block on the dashboard is not displayed, debugging on doesn't show any errors. If I look for the word overview on the browser it finds "Skip Course overview". I have uninstalled and installed the block back, but it's the same.

![image](https://user-images.githubusercontent.com/8148238/32793587-3f9fb994-c91b-11e7-9002-9bbad18f2da0.png)

Thanks!

**Comment by turf212** [comment]
This is correct behaviour.  The block is set to display none in the CSS for the mycourses block as it handles  courses which have been assigned to the user via license and (now) company shared courses too.  We've moved this to use the same style of tabbed courses as the my overview block and will be continuing to develop it to show much of the same information.
