### ISSUE TITLE
Coding error when course is assigned to a company without subcategories

### ISSUE THREAD

**Issue by tjr007ma** [iomad/iomad#769]
Every time we create a course for a company that never had a subcategory but another company has subcategories, we get the error "Codding error detected, it must be fixed by a programmer: Category path order is incorrect and/or there are missing categories"

The work around was to create subcategories for the company.

**Comment by turf212** [comment]
Iomad expects there to be a course category for the company available on the system. If its not there it will complain. The reason why there is a company default category is so there is a space to put courses which have been created from within the company.  Where does the course go if it's not defined??

This may get changed in the future as there has been suggested an idea defining what the company category is as having it at a top level isn't the best.
