### ISSUE TITLE
Logged in as company admin - Attendance report shows no course options

### ISSUE THREAD

**Issue by thepurpleblob** [iomad/iomad#77]
The only option is "Choose". There obviously are some courses for this "company" so it seems odd that there are no options. If this is correct and (for some reason) there are no courses to choose then a proper explanation should be displayed rather than the empty select box.

**Comment by turf212** [comment]
This report is for courses which have the Training event activity set up on it.  It is to show who is booked and attending the training events.  If you dont have a training even activity in a course which that user can manage then there will be no courses found.
