### ISSUE TITLE
E-commerce not working in IOMAD 3.3 

### ISSUE THREAD

**Issue by Markrico** [iomad/iomad#770]
It appears that the e-commerce block in IOMAD 3.3 is not working. Has anyone else found this to be a problem? Is there a fix coming in the near future? Thanks for any help you can provide.

**Comment by Blacksheeprules** [comment]
Yes, I noticed this same issue. The Shop worked in my 2.7 and when I upgraded to 3.3 it stopped working.

**Comment by rajuptl21** [comment]
E-Commerce shop features is not working with IOMAD 3.3. I also check with IOMAD demo site and it's not working there as well. Please address this issue and provide solution as soon as you can.

**Comment by thepurpleblob** [comment]
If we're talking about the 'Coding error detected', then it seems to be down to this...

``` sql
select count(*) FROM mdl_course_shopsettings css
            INNER JOIN mdl_course c ON c.id = css.courseid  AND ( c.id in ( select courseid from mdl_company_course where companyid= 1)
	               or c.id in ( select courseid from mdl_iomad_courses where shared=1)
	               or c.id in ( select courseid from mdl_company_shared_courses where companyid = 1)) 
            
            LEFT JOIN mdl_course_shopblockprice sbp ON (c.id = sbp.courseid
                                                  AND sbp.id = (SELECT id FROM mdl_course_shopblockprice
                                                  WHERE courseid = c.id ORDER BY price LIMIT 1 ))
        WHERE css.enabled = 1
        
        GROUP BY c.id, sbp.id, css.id, c.fullname ORDER BY c.fullname
```

This is reported around line 163 of /blocks/iomad_commerce/shop.php. I have no idea what the sql is trying to do unfortunately. It dates back to 2013. Anyway, I wouldn't expect a 'GROUP BY' in a count. I don't think it makes sense. As it stands it returns 'null' instead of any valid value. 

If it's not the above 'coding error' can somebody let us know in more detail what problem you are seeing?

**Comment by Markrico** [comment]
Hi, Thanks for providing some help. When I go to the IOMAD dashboard, select eCommerce, then Courses, then add course to shop, then select a course, fill out the page, click save, and nothing is added to the shop. I am using the latest IOMAD 3.3.

**Comment by turf212** [comment]
The URL for the form is wrong when editing the course in the shop.  Just fixing this now.

**Comment by elreydetoda** [comment]
@turf212 there is the same issue in 32 as well 
https://github.com/iomad/iomad/blob/c9831a952ff66fce565341b72aeb90980c23df04/blocks/iomad_commerce/edit_course_shopsettings_form.php#L409
