### ISSUE TITLE
Company Manager not receiving right permissions after upgrade

### ISSUE THREAD

**Issue by richard0096** [iomad/iomad#771]
I've just recently upgraded to IOMAD_33 and I am now having issues with users set with the company manager role. They do not seem to be shown the IOMAD or Site Administration blocks on home screen so cannot access them.

I have checked the permissions and they seem to be correct and have even tried resetting them to default with no luck.

Is this an IOMAD issue or a setup related issue?

**Comment by thepurpleblob** [comment]
Just to confirm - you're talking about the Iomad Dashboard page? And you mean the main Iomad block with all the tabs and options for controlling Iomad. 

I cleaned up a bunch of (I thought) no longer used role capabilities recently, so I'm wondering if it's related.

**Comment by richard0096** [comment]
I solved the issue, for some reason after the upgrade some of the non-iomad permissions had been reset not allowing me to use IOMAD.

**Comment by thepurpleblob** [comment]
Do you remember which? That shouldn't happen...

**Comment by richard0096** [comment]
All permissions had stayed as 'Not set' but this time I had to enable them manually.
