### ISSUE TITLE
company custom css no > possible

### ISSUE THREAD

**Issue by actXc** [iomad/iomad#772]
Sometimes  css needs the character ">"
But the field customcss in company_edit_form.php  filters with PARAM_CLEAN

**Comment by turf212** [comment]
Needs to be changed to PARAM_TEXT

**Comment by teddielong** [comment]
Please can you advise what I need to change?

There are to files to chose from:

/public_html/PACK 1/blocks/iomad_company_admin/company_edit_form.php
--
  | /public_html/blocks/iomad_company_admin/company_edit_form.php

And mutliple references to PARAM_CLEAN within each of the files to do with customcss.  Can someone advise?  Keen to resolve this issue. Thanks :)

**Comment by turf212** [comment]
Hi @teddielong, you just need to pull the latest code from git hub for this branch.  Failing that you can get a patch by clicking on the commit link above in the closed message.
