### ISSUE TITLE
Certificate restictions

### ISSUE THREAD

**Issue by cboothwi** [iomad/iomad#774]
We would like to allow access to the IOMAD Certificate upon completion of a course. The course has its own completion criteria already configured based on completion of various actives, scores, etc.  Is it possible to use the course completion status as the requirement to view the certificate?  If not, it would be great if there was a select all/none when adding the Activity completion restriction, rather than creating a restriction set and a separate restriction for every single activity.

**Comment by turf212** [comment]
All of the conditional access and course completion is using the standard Moodle completion/conditional access rules.  We are not doing anything different here.  The documentation for this is here - https://docs.moodle.org/33/en/Restrict_access_settings
