### ISSUE TITLE
BUG: IOMAD_33_STABLE: 'Enable shop access' leads to suspend comapany!

### ISSUE THREAD

**Issue by zenny** [iomad/iomad#778]
Hi,

When on tries to 'Enable shop access' under Dashboard >> Site administration>>Iomad Dashboard>>Manage companies, it doesn't do what is expected, but asks for confirmation whether one wants to suspend the company, instead?!

Cheers,
/z

**Comment by turf212** [comment]
Ooops.   Missed this one.
