### ISSUE TITLE
IOMAD HTML Block viewable to other users in other companies

### ISSUE THREAD

**Issue by teddielong** [iomad/iomad#779]
Clicking around (as one does) under My Profile and chose to Customise This Page. The names of other companies appeared (IOMAD HTML blocks?)

**Comment by turf212** [comment]
this block needs to be set so that it can't be put on that page by an ordinary user. if you remove the capability:
Block: IOMAD HTML
Add a new Company HTML block to Dashboard
block/iomad_html:myaddinstance

from the authorised user role it will prevent it on your site.
