### ISSUE TITLE
 How to Prevent Learner from Self-Enrolling in Course Already Completed

### ISSUE THREAD

**Issue by moodler3400** [iomad/iomad#780]
I'm new to Moodle and have created a few SCORM-based & pure video-based courses in Moodle 3.2.3.  We're using the IOMAD version of Moodle.  I was able to successfully complete these courses, logged in as a test user, whereby they appear on my Dashboard under Completed Courses, as expected.  However, for 3 out of the 5 courses, if I click on the corresponding course link under Completed Courses, the Enrollment Options page appears, prompting me to self-enroll in order to get to the course content.  For the other 2 out of 5 courses, if I click on their corresponding course link under Completed Courses, I'm brought directly to the course content, as expected, without any Enrollment Options page first appearing.  

How do I ensure that any completed course that's clicked on goes directly to the course content without first displaying an Enrollment Options page?  Any particular settings I should check in order to troubleshoot this issue?

Thanks much for any guidance you may be able to lend this newbie!

**Comment by turf212** [comment]
This all depends on the course enrolment settings.  Moodle docs for these are here - https://docs.moodle.org/22/en/Course_enrolment

Iomad has an additional enrolment option, license, which is only for license based access to the course.
