### ISSUE TITLE
How to upload users into departments? and into cohorts?

### ISSUE THREAD

**Issue by actXc** [iomad/iomad#788]
Upload to departments would be very necessary

**Comment by turf212** [comment]
Upload to departments is available in 3.3.  You can either pick a department from the drop down list or add a department column to the upload and use the short name.

Cohorts isn't available and doesn't make sense in a company setting.

**Comment by teddielong** [comment]
Hi, it is possible to upload a list of the departments?  I tried to find the answer without success and I'm presuming it's REALLY simple.

**Comment by turf212** [comment]
To create them?  yes.  You can use the import departments button when there are none for a company.  If you create a few and export them you will see the format required.
