### ISSUE TITLE
No breadcrumbs in reports

### ISSUE THREAD

**Issue by thepurpleblob** [iomad/iomad#79]
It's quite easy to get lost in reports and not be able to get back without going right back through the menus (Home page... dashboard... report etc.). It would be convenient if the reports could display a breadcrumb trail at the top.

**Comment by turf212** [comment]
Just checked the reports.   They all already display a breadcrumb trail at the top although the company overview report one is slightly broken (and I'll raise an issue to fix)  What theme was this with?

**Comment by thepurpleblob** [comment]
All of this stuff was with the moot demo site

**Comment by turf212** [comment]
Thats what I thought.  They are definitely there.  Above the saltire.

**Comment by thepurpleblob** [comment]
Ok - I didn't see it because the page was scrolled down a bit. I expected them to be underneath the saltire I suppose.

**Comment by turf212** [comment]
not an issue
