### ISSUE TITLE
BUG: Can't create child company

### ISSUE THREAD

**Issue by ndalpe** [iomad/iomad#796]
Dear IOMAD,
Thank you for your great product. I encounter a bug creating a new child company. The bug happen in the update page as well.

When I go to Manage Companies -> Create a child company
 - I add a long + short name
 - Select my parent company from "Parent company"
The page refresh without the info I just typed and the "Parent company" field is blank

In order to create a child company, I have to set the parent company "Advanced Company Settings".

I am using a brand new IOMAD_33_STABLE with default theme. Ask me any question

Hope that help

Thank you

**Comment by turf212** [comment]
The page should stash all of the company info from the form into your SESSION before it refreshes.  The reason why it refreshes is to pick up the defaults from the parent company for a number of fields on the form.  Is there something in your browser which would stop the SESSION from being saved?  Do you have cookies blocked?

**Comment by ndalpe** [comment]
Hi turf212,
I use the browser's default settings for cookies. I have a cookie called "MoodleSession" in my Firefox so I guess cookies get recorded.

On the server side the sessions are enabled in my PHP settings. My server is a Ubuntu 16.04.3 running on vagrant, see session config below.

Does that answer your question?

Thank you for your time

--

Session config from phpinfo()

PHP Variables
$_SERVER['HTTP_COOKIE']  
pll_language=en; adminer_version=4.3.1;MoodleSession=grujkp2d41lq7paapd16oujm52

Apache Environment
HTTP_COOKIE | pll_language=en; adminer_version=4.3.1; MoodleSession=grujkp2d41lq7paapd16oujm52

HTTP Headers Information
Cookie | pll_language=en; adminer_version=4.3.1; MoodleSession=grujkp2d41lq7paapd16oujm52

Session
Session Support 	enabled
Registered save handlers 	files user
Registered serializer handlers 	php_serialize php php_binary wddx

Directive	Local Value	Master Value
session.auto_start	Off	Off
session.cache_expire	180	180
session.cache_limiter	nocache	nocache
session.cookie_domain	no value	no value
session.cookie_httponly	Off	Off
session.cookie_lifetime	0	0
session.cookie_path	/	/
session.cookie_secure	Off	Off
session.entropy_file	/dev/urandom	/dev/urandom
session.entropy_length	32	32
session.gc_divisor	1000	1000
session.gc_maxlifetime	1440	1440
session.gc_probability	0	0
session.hash_bits_per_character	5	5
session.hash_function	0	0
session.lazy_write	On	On
session.name	PHPSESSID	PHPSESSID
session.referer_check	no value	no value
session.save_handler	files	files
session.save_path	/var/lib/php/sessions	/var/lib/php/sessions
session.serialize_handler	php	php
session.upload_progress.cleanup	On	On
session.upload_progress.enabled	On	On
session.upload_progress.freq	1%	1%
session.upload_progress.min_freq	1	1
session.upload_progress.name	PHP_SESSION_UPLOAD_PROGRESS	PHP_SESSION_UPLOAD_PROGRESS
session.upload_progress.prefix	upload_progress_	upload_progress_
session.use_cookies	On	On
session.use_only_cookies	On	On
session.use_strict_mode	Off	Off
session.use_trans_sid	0	0

Hope that helps

Nicolas

**Comment by ndalpe** [comment]
@turf212 How can I help further fixing this bug report?

Thank you
