### ISSUE TITLE
Client Course Editor

### ISSUE THREAD

**Issue by nazakar** [iomad/iomad#798]
How to add user with role thet can delete topisc and add Add an activity or resource? I supose must be Client Course Editor but this role not in list

**Comment by BigWizzo** [comment]
I am also looking for something like this. Did you manage to get a solution?

**Comment by turf212** [comment]
client course editor is added automatically to the company manager's account when they create a course.  There is new functionality for an educator role which can be assigned instead if the option in local iomad settings for enrol manager as non students is unticked.
