### ISSUE TITLE
Email notification to Company Managers not being sent on course completion

### ISSUE THREAD

**Issue by Markrico** [iomad/iomad#803]
3.3.3 (Build: 20171113)       php    7.0.25      cron jobs are running
 
When I upgraded the IOMAD on Nov 30 to the latest code on Git Hub, notifications stopped going to Company Managers. On the edit company settings the send manager emails is set to Completion Emails. I have a stmp mail system that is working and have successfully sent emails to managers with the email test plugin. Does any know if this is a known issue or if it has been fixed?

Thank-you very much for any help you can provide on this issue.

Mark

**Comment by turf212** [comment]
Is there anything being put into the mdl_email table for the managers for the completion event?  Have you set a digest day by accident?  (which would send the emails out on the specified day instead of when the completion even occurs).

**Comment by Markrico** [comment]
Thanks for the help Derrick,

 Yes there are some in the table. Here is the last one.

<p>Dear Wendy</p>
<p>Grant Colantin has completed Canadian Heavy Truck Weight and Dimension Program in Cummins on 2017-11-30
</p>

After Nov 30, when the IOMAD was updated, the emails stopped going out for course completion. There is nothing else in the table after this date, except for the create user emails are still going out. 

Thanks,

Mark

**Comment by Markrico** [comment]
I am not sure where to look for the digest day setting?

**Comment by Markrico** [comment]
Found the digest email. It is set to none.

**Comment by KellisEM** [comment]
Any update on this? I am also not receiving the emails. However no entry is made into the mdl_email table.

**Comment by Markrico** [comment]
Hi,

 

This has been fixed. Update you Iomad code and it should work. 

 

Mark
