### ISSUE TITLE
dashboard

### ISSUE THREAD

**Issue by syusanjun** [iomad/iomad#804]
IOMAD_33_STABLE:
When you display the dash board
Available courses
No courses are available
No courses are available and 2 lines are displayed. Is it correct?

Icons are broken when using chrome.

**Comment by turf212** [comment]
This is correct.  Available courses show courses where the user has either a license granted to a course or (from #802) if there is a self enrol course they are not already enrolled on.

I'll look at the icons.  Thanks for reporting :)

**Comment by syusanjun** [comment]
Thank you very much.

Can I use the moodle standard block, COURSE OVERVIEW (round progress bar is displayed)?

**Comment by turf212** [comment]
this block is hidden in CSS so you would need to override it.  It also doesn't understanda about any courses which a user has been given a license for and has not yet accessed (so doesn't have an enrolment on) which gets listed under the available courses tab in the My Courses block.  Icons are all fixed,
