### ISSUE TITLE
IOMAD 3.3 - Manage IOMAD Course settings - no Search feature? 

### ISSUE THREAD

**Issue by tjr007ma** [iomad/iomad#808]
Working w/IOMAD creating course...on the “Manage IOMAD Course Settings” page — there is no Search feature available.  It is very clear that this courses list will number in the hundreds within 12 mons and will be very difficult to manage.  We need an ability to tag courses and search by tag, search by title, search by text string, potentially by date range.

**Comment by turf212** [comment]
all of this is added in 3.6
