### ISSUE TITLE
e-mail invitation in wrong language.

### ISSUE THREAD

**Issue by rroijackers** [iomad/iomad#810]
I have installed the Iomad 3.3.3 edition. I've set the major language in dutch (nl). When I create a company and set the pereffered language, and create a user in that company, they receives an invitation e-mail in dutch. When I try the import function and describes lang in the sheet, still the e-mail will be sent in dutch and not in german. How can I fix this problem? I've checked in the translations modification and everything is translated.

**Comment by turf212** [comment]
The old system in 3.3. checked the language which the uer who created the acounts had selected and used it.  The new one 3.6 will check the company language and use it depending on the loca iomad settings plugin settings.
