### ISSUE TITLE
Deleting a course breaks completion reports. 

### ISSUE THREAD

**Issue by Markrico** [iomad/iomad#819]
Is there a way to delete a course from the IOMAD dashboard? Since I could not find one I deleted the course from Moodle Site admin> Courses > Manage Courses and Categories. After it was gone so were the completion reports.  The error was roughly data missing in database. I restored the cpanel to get the IOMAD course reports going again.

**Comment by catalinopascual1** [comment]
Hi! Have you tried Iomad Dashboard > Manage Iomad course settings > (At the right of the course) - Delete? Thank you.

**Comment by turf212** [comment]
hooks for course deletions were added a long while back
