### ISSUE TITLE
Translate lang, best way to do it?

### ISSUE THREAD

**Issue by swemax** [iomad/iomad#82]
Hello,

Im trying to figure out the best way to translate iomad. I find some lang-files under moodle/lang? Are there a list of all tables that has to do with iomad? And is this the best way to do it? I run version 2.6.

Thanks in advance!

**Comment by turf212** [comment]
Hi,

There isn't a list of language files as such, but you can get the list of additional plugins which is different from Moodle by clicking on the site administration -> plugins -> plugins overview as a site admin and then clicking on show add-ons only.  If you could follow the guidelines from here http://docs.moodle.org/26/en/Translation#How_do_language_packs_work.3F then this would ensure that everything will work OK.  I would also, if you haven't already, apply the normal Moodle language pack for the language you are translating to as this will give you a much better starting point.

**Comment by swemax** [comment]
Hi,

Thank you very much for you´re answer!
