### ISSUE TITLE
Translation to spanish Iomad

### ISSUE THREAD

**Issue by joenilson** [iomad/iomad#825]
Hi, i want to know if is in progress some translation to spanish or if i can start the translation, to do this i want to know which folders containt the iomad functionality, i see the local folder and the blocks floder, but i'm not sure if i must to see any other folders.

**Comment by turf212** [comment]
As no-one has answered you there isn't anything in translating Iomad to Spanish, so, if you have done this we would be very interested in any resultant work as long as it's generic and not specific to your company.

The list of Iomad plugins are available from the site admin -> plugins -> plugins over view (and then sort by additional plugins only).  Most have Iomad in the title apart from trainingevents and some in local.  There is a bunch in local too.  Core Moodle doesn't have any of them.

I think we need a language project for the tool as it's something we are lacking (as well as docs but we are working on this). I'll close this and raise a help wanted.
