### ISSUE TITLE
Company manager automatic enrolled in all courses?

### ISSUE THREAD

**Issue by rroijackers** [iomad/iomad#829]
Dear,
When I assign a user as a Company Manager, he will see all company courses under my courses in the left corner and he can start all courses. Also the courses that I haven't enrolled him to. How can I disable this, so that under my courses, he only sees the courses that he is enrolled into. 
I've checked that self enrolments has been disabled.

**Comment by pamaher** [comment]
I am having the same issue.

**Comment by turf212** [comment]
If you have not enabled the option in local iomad settings plugin that company manager are real users then the company managers will be given a teacher type role depending on if the course was created by ne of them or not.  If you enable this then the company managers can undertake the course as a normal user and are not automatically enrolled on it.
