### ISSUE TITLE
Licensed Course and Available Courses

### ISSUE THREAD

**Issue by Markbhai** [iomad/iomad#853]
I am looking at the behaviour of licenced courses and am in particular using a Single Activity Scorm course (if this is relevant).

When I allocate a licence to a user the course can be seen in Available Courses, however if the user enrols and does not take the course or if they start the course and abort it, I cannot find the course again in either Available, In Progress or Completed.

Is this normal behaviour?

Any help would assist a very frustrated individual. :-)

Thanks
Mark

**Comment by turf212** [comment]
You don't ahve course completion turned on on your Moodle course and without this, the user will not see the course being moved to the active course list.  It's also useful to turn the "mark users started" system task to run every minute as the current once a day can cause confusion.
