### ISSUE TITLE
Clicking "View More" on front page causes error.

### ISSUE THREAD

**Issue by watcanz** [iomad/iomad#857]
Site is 3.1.6. Cannot upgrade beyond due to separate bug regarding pDraw.  Site set to Combo front page.

Some course category folders disappear from a user's view when new courses have been added.  Clicking on the "view more" text link results in the following error:

Coding error detected, it must be fixed by a programmer: moodle_database::get_in_or_equal() does not accept empty arrays

**Comment by turf212** [comment]
Fixed in 3.6
