### ISSUE TITLE
Course Overview block not showing

### ISSUE THREAD

**Issue by Markbhai** [iomad/iomad#859]
Is there a bug regarding the visibility of the Course oVerview block?  I am trying to add it to my dashboard and it is not in the list of available blocks despite it being enabled and installed in the plugins overview.

Running on Branch 33 with   Moodle 3.3.4 (Build: 20180115)

**Comment by ndalpe** [comment]
Same here. I just updated from 3.4. Now the dashboard of my student is a white page?!?! 

I did inspect the /my page and the block block_myoverview is set to display:none. When I set it to block, I have this weird block display...it looks half done. Would really appreciate feedback on this as this is a big issue for me.

Also, the courses seems to disappear from the navigation menu on the left once they are completed. So if the course is not in the menu and not in the dashboard, this means a completed course cannot be accessed anymore? 

Thank you

Moodle 3.5.3+ (Build: 20181204)
IOMAD 35 STABLE

**Comment by turf212** [comment]
This is correct as the My Courses block is meant to replace it.  The course overview block does not undestand about courses which a user may have access to via a license whereas the My COurses block does.  This is disabled via CSS with a display: none; call for that block.

FYI the my Courses block has been improved in look in 3.6 to provide a % status bar for the users course.
