### ISSUE TITLE
Issues with restoring a course with student data

### ISSUE THREAD

**Issue by rmeske** [iomad/iomad#862]
Hello,

On an existing Moodle (2.9.9+) install, I exported the users, and I backed up a course and included all student data.  The course has a SCORM activity and a Questionnaire activity with completion criteria that both must be completed for the course to be complete.

On a IOMAD (3.3 Stable) install, I created a Company and imported the users to the company.  I then restored the course and Assigned the course to the Company.  

I then tried to run the IOMAD report Completion report by course.  It came back with an error "Can not find data record in database table course."  

ISSUE 1: I then went directly to the course to verify the students data was actually copied over.  I ran the course report Course Completion and it showed the activities were marked complete but not the course.  Apparently the completion setting for the course was not backed up/restored.  I'm not sure if this is a Moodle or IOMAD issue.  

I modified the completion settings for the course and ran the cron job.  I then ran the course report Course Completion and the course completion was recalculated  and now shows correctly.  

ISSUE 2: When I run the IOMAD report Completion report by course I am still getting the error: "Can not find data record in database table course."

ISSUE 3: When I run the IOMAD SCORM overview report it is not showing any data.

Any suggestions on how to go about correcting this?

Regards,
Ron

**Comment by turf212** [comment]
The backup and restore of the course is completely Moodle related.  If you replaced the course with the content then Moodle will remove the original course and create a new one.  The original course will still be tied to the company which is causing your issue with the reports.  (There is another bug in for that but I'm waiting for some fixes to be merged for this).  If you had an empty course and merged the contents then it would have worked OK.

There is another issue, however, in that the user data is not being parsed into the Iomad course datastore.  Which I'll riase separately.

The SCORM report is no longer valid and has been removed in 3.6.  All of that data can be obtained from the SCORM activity reporting in the course itself.
