### ISSUE TITLE
IOMAD Dashboard displays in Navigation Drawer for students

### ISSUE THREAD

**Issue by rmeske** [iomad/iomad#863]
Hello,

The IOMAD Dashboard is displayed in the Navigation Drawer for students.  This should be hidden.  When a student clicks on this they are taken to the IOMAD Dashboard and receive a message that they do not have permission to view.

Running IOMAD 3.3
Theme is IOMAD Boost

Regards,
Ron

**Comment by MarkusKgit** [comment]
I fixed it for myself by changing a few lines at the bottom of theme\iomadboost\layout\columns2.php to:
```
// Add Iomad link
$systemcontext = context_system::instance();
if (has_capability('local/iomad_dashboard:view', $systemcontext))
{
	$url = new moodle_url('/local/iomad_dashboard/index.php');
	$iomaddashboard = navigation_node::create(get_string('iomaddashboard', 'theme_iomadboost'), $url);
	$flat = new flat_navigation_node($iomaddashboard, 0);
	$flat->set_showdivider(true);
	$flat->key = 'iomad';
	$PAGE->flatnav->add($flat);
}
```

No idea if it is the right way® to do it but it seems to fix it.

**Comment by rodlaw** [comment]
You can turn the setting off in administration permissions

**Comment by turf212** [comment]
Thanks Markus.  I've added that fix to core too.
