### ISSUE TITLE
IOMAD Multitenancy Feature Company URL

### ISSUE THREAD

**Issue by oktavianusari** [iomad/iomad#864]
I am interested to use IOMAD for multitenancy feature in Moodle. I have created companies using iomad and added user into it .

i want to see these company as url like
www.mydomain.com/company1 www.mydomain.com/company2 or some thing else but company should be shown in url. So that each company have its own url and user can login from that url.

Is it possible?

Thank you.

**Comment by SGMVictor** [comment]
I'm looking for the same. I need to access from different urls to the companies and this must have it's own company logo.

**Comment by rodlaw** [comment]
Seems like this IOMAD is going to fail if it doesn't allow you to log into a specific company. If it could somehow be designed so you can have a specific company to individual members so they can log into that company this program would succeed. I've added a number of companies and have put them on the front page but individual users would have to select at that company and not be able to login directly to that specific company. I hope that the designers will figure out that there will be much greater success if you can log into individual companies.

**Comment by turf212** [comment]
Iomad is built on top of Moodle which defines only a single URL for the whole site ($CFG->wwwroot).  It uses this setting to create every single menu item and link throughout.   It may be possible to do some fancy rewrites with the webserver which will translate these URLS back and forth but that is completely dependant on which webserver software you are using.

Since #883 there is the capability to define a hostname for a company which will redirect the user to a branded login page which is using the real URL for the site.  You need to point the hostname at the Iomad installation or have it be the default web root for any hostname which matches on the same IP address.

I'm not sure what you mean by log in directly to a specific company.  If you mean self sign up then there are a couple of ways to do this.  Matching email address on defined company domain or using the local/iomad_signup/signup.php page and passing the parameters for company id, shortname and optionally department shortname.

**Comment by rodlaw** [comment]
Thank you for your response.

To simplify things, let's say we have three companies - Schools, each company - School will design their own courses and have their own members. The members would like to login with their particular company- school.

Iomad would be the hub. Each school would have a specific link to advertise their school- company.

I know I could do this by creating a Moodle site for every company, but I was wondering if this could be done with Iomad?

I have created three companies-schools within Iomad and created the courses for each company. But it appears that each company can only be found through the main site login.

I would like for one of the schools, who had, say a thousand members to send an email out to members, hey I have a new lesson and when the members click on the link it just goes directly to the particular school - company and not have to go to the main page and shuffle through a bunch of courses.

Am I confusing IOMADs capabilities?

Many schools, separate members, separate lessons, one hub for each. So far IOMAD is close without any mods.

Am I missing something, can this be done with IOMAD?

Thanks for your time.

**Comment by eve4ever** [comment]
Any news on the subject?

**Comment by actXc** [comment]
Hello Eve4ever,
have you created a student1, that is member of company1?
When student1 enters via login, only company1 courses are there.
Same to other roles, like department manager, company manager etc.

**Comment by eve4ever** [comment]
I'm talking about the login page, before user loges in.
He enters through the hostname, but all the login pages still look the same
- no company logo or anything...

**Comment by turf212** [comment]
if you aren;t using the local/iomad_signup/login.php page then it wont.  As of 3.6 there are hooks to allow for the URL hostname to be matched and a theme to be displayed throughout the site.

**Comment by kulinfx** [comment]
I have installed Iomad on a webserver. It installed without any errors. 
I would like to do the following
have separate domains pointing to separate instances of companies. I can see there is a provision for the same in the field advanced company settings > webserver hostname >

however whatever you enter here should correspond to the iomad installation and there is no clarity on it, whether we should have some kind of domain redirection or how does it work. Kindly someone throw some light on this issue.

**Comment by rafaelg21** [comment]
Hello, good afternoon. Could this be done with Iomad. SubDomain?

There are two companies set up to use their own distinct URLs.  https://testcompany.iomad.org and https://anothercompany.iomad.org Visiting thee links will provide the branding for those companies for login pages and keep the URL throughout for their own users.
