### ISSUE TITLE
IOMAD over Moodle

### ISSUE THREAD

**Issue by jacksonp2008** [iomad/iomad#865]
I have an existing Moodle installation with a ton of plugins, the database is Aurora MySQL 5.6.10a (AWS)  As indicated per another conversation, I left the existing Moodle in place and copied the IOMAD distribution over top.

When I open the webUI to complete the install, it wants to upgrade the database as expected:
```
Upgrading Moodle database from version 3.2.2+ (Build: 20170407) (2016120502.05) to 3.2.7 (Build: 20180115) (2016120507.00)
```
It gets through everything except for `local_iomad`

<img width="528" alt="screen shot 2018-02-09 at 17 12 47" src="https://user-images.githubusercontent.com/1813327/36056819-8e2dee4c-0dbc-11e8-9dc4-f296863dc6c1.png">

I can send the entire stack trace if you want it.  

Any ideas on how to get this going?

Thanks!

**Comment by mdykman** [comment]
As a workaround, open local/iomad/db/install.xml and look for column
definitions which are wider than that. Adjust accordingly.

**Comment by jacksonp2008** [comment]
Thanks, I assume you are referring to the LENGTH=
```
<FIELD NAME="id" TYPE="int" LENGTH="10"
```
Value in this file.

I was unable to find any length values greater than 255 in install.xml

**Comment by jacksonp2008** [comment]
I have answered my own question, so to let folks know.  

The issue is this:  https://tracker.moodle.org/browse/MDL-58931

and the only way I was able to solve it was by migrating the moodle database to native MYSQL instead of Aurora on AWS.
