### ISSUE TITLE
IOMAD over Existing Site - Add users to Company?

### ISSUE THREAD

**Issue by jacksonp2008** [iomad/iomad#867]
IOMAD is running, all of my users enter through OKTA Single Sign-On and there are many in the database.  When pulling up the list of users for any of the companies I created they are all empty even though the existing sites has many.

What is the best method to assign all of my existing users to the various companies being created?  Is this a manual export out of the existing site and import into the new company?

thanks!

**Comment by turf212** [comment]
If you can work out how to identify the users (suing profile information for example) then you can populate the company_users table with the userid/companyid/departmentid for the respective companies.
