### ISSUE TITLE
IOMAD - Company specific pages?

### ISSUE THREAD

**Issue by jacksonp2008** [iomad/iomad#868]
New installation of IOMAD over Moodle - We have customized pages for the existing site.  When I create another "Company", those same pages also show up on the top bar like so:

<img width="961" alt="screen shot 2018-02-12 at 15 06 27" src="https://user-images.githubusercontent.com/1813327/36125244-127ce9b2-1008-11e8-9a59-4c6023639c58.png">

Is there a way to customize those pages per "Company", or do we need to re-engineer our site to only have globally viewable pages and move anything specific to a company into a course?

Thanks!

**Comment by turf212** [comment]
If these are custom menu items in the theme then yes, you can add in per company custom menu items as long as you are using an Iomad theme.
