### ISSUE TITLE
Error when trying to access Iomad Dashboard as Client Administrator

### ISSUE THREAD

**Issue by jchrom** [iomad/iomad#871]
Hi,
on IOMAD_33_STABLE

As Client Administrator (system role)
When I try to access the Iomad Dashboard
I get the following error:

```
Can not find data record in database table company_users.
Debug info: SELECT * FROM {company_users} WHERE userid = ?
[array (
0 => '7',
)]
Error code: invalidrecord
```

**Comment by jchrom** [comment]
Same in 32_STABLE

**Comment by turf212** [comment]
This is a data issue.  The client admin needs to be assigned to at least one company.

**Comment by jchrom** [comment]
@turf212 just to understand how this works:

1. In order to assign company managers (which is what the role description says the Client Admin should be able to do), does the Client Admin need to be assigned to all the companies she is supposed to admin?
2. What is the expected behavior when a Client Admin creates a company - should she be automatically assigned to it? Should it be inaccessible to her?

Thanks,
Jakub
