### ISSUE TITLE
Bulk Upload: If creating custom passwords, unable to force password change on first log in.

### ISSUE THREAD

**Issue by teddielong** [iomad/iomad#873]
When uploading bulk users, IOMAD appears to prevent me from uploading the users with a custom password and then forcing a password change on first log-in.  

This is a feature which doesn't appear to have copied across from other instances of Moodle unless I'm missing something?

https://docs.moodle.org/33/en/Upload_users#Force_password_change

**Comment by shadyshrif** [comment]
Any Plans for this features?
@turf212  I think I can work on it
