### ISSUE TITLE
Not all data is shown in course report

### ISSUE THREAD

**Issue by rroijackers** [iomad/iomad#878]
We only delivers online courses with scorm content. But When Someone starts his course it will gives the following as a result:

12-01-2018 | Not started | - | - | 100% | Certificate not achieved

But the student has it's certificate and the course is 100%. Why is de Certificate not achieved and all the data not updated?

**Comment by turf212** [comment]
FYI the reports in Iomad 3.6 have been completely rewritten to keep all of the user information regarding courses in one reporting table.  This revents there from being "missing" data like this which was cause by confusion over "historic" and not reporting.

**Comment by turf212** [comment]
Oh and the started/non started is due to you not having set up course completion within the Moodle course which is required for reporting to work.
