### ISSUE TITLE
IOMAD not emailing company managers on course completion.

### ISSUE THREAD

**Issue by Markrico** [iomad/iomad#879]
Hi,

I have set send manager emails in the company settings.
My IOMAD mail works as I have tested it with email test and it does not go into spam. 
When a user completes a course it is correctly recorded under course completion reports. 
The company manager does not receive an email. 
I am using the latest code as out Feb 23, 2017
Thank-you very much in advance for any help you can provide on this issue. 

Regards,

Mark

**Comment by turf212** [comment]
FYI there has been a complete rewrite of the Iomad emails to allow for better granularity of control per company in 3.6 which will address exactly this.
