### ISSUE TITLE
Automatic company allocation on self signup.

### ISSUE THREAD

**Issue by accena-group** [iomad/iomad#885]
This is the number one reason I downloaded Iomad and I can't figure out how to get it to work. I have the options selected in site admin > plugins > local plugins > Iomad signup but nothing shows up for the user when they are signing up and everyone gets put into the default company. Is the only option to select the company based on email domain? Is there any way to add a field to the signup page that they can select and be added to the correct company?

Thanks for your help!

**Comment by turf212** [comment]
The self signup uses the user's email domain to automatically put them into the correct company.  Other than this, you can use the local/iomad_signup/signup.php form which requires two parameters, id = company id and code = company shortname and can take a third dept = department shortname.  If you are using the latest 3.3 version you can also have a unique hostname which will automatically provide this URL assuming the hostname points to the initial installation.

**Comment by accena-group** [comment]
Excellent. Thanks for your help!

**Comment by jgdk** [comment]
Good morning Turf:  Regarding: https://github.com/iomad/iomad/issues/885#issuecomment-371201865
Could you write an example for the url to the: local/iomad_signup/signup.php. I mean: local/iomad_signup/signup.php?id=1&code=EC1 does not work - so if you could write an example of the url-syntax after the signup.php it would be a great help. Thank you and all the best wishes for the day :-)
