### ISSUE TITLE
Edit license - expire date set to one year from now

### ISSUE THREAD

**Issue by cboothwi** [iomad/iomad#886]
1. Create a new license. Expire date is pre-populated with date 1 year from now.
2. Set a different expire date and save license.
3. Edit the license.

Expected: The expire date shows the same date that was previously set.
Actual: The expire date shows the date one year from now. This new date is saved when updating the license.

**Comment by MarkusKgit** [comment]
Had the same issue and tried to fix it. Can you test 04cc3353a5dd63f4d05e82936d4b579923fd9c5e ?

**Comment by turf212** [comment]
Thanks for the fix.  Can you make it available to the main repo please?

**Comment by MarkusKgit** [comment]
Created a PR

**Comment by turf212** [comment]
Thank Markus.  Merged it in :)
