### ISSUE TITLE
dept= parameter gives database read error

### ISSUE THREAD

**Issue by accena-group** [iomad/iomad#890]
I have branded login pages set up to put new sign ups into the correct company. When I pass the parameters for id= and code= everything works fine. As soon as I add a parameter for dept= I get "Error reading from database"

Example = 

Sign Up link sends user to "https://example.com/iomad/local/iomad_signup/signup.php?id=1&code=example" -- This url works perfectly, the user signs up in the branded signup page for Example company and gets added to the company.

Sign Up link sends user to "https://example.com/iomad/local/iomad_signup/signup.php?id=1&code=example&dept=exampledept" -- This returns Error reading from database.

I've tried passing the deptid parameter, but it has no effect. The link works just fine, but the user is only created into the company, not the department.

**Comment by turf212** [comment]
This should be a URL Encoded version of the department shortname.  If it doesn't match and you have all of the others correct, the user will be created and dropped into the company top level department.

**Comment by accena-group** [comment]
It looks like the problem is that it is looking for a table in the database called departments, when the actual table is called department. I was passing the right parameters, but it couldn't find the table. So, the actual bug is that the dept= parameter is looking for a table departments when it should be looking for a table department.

**Comment by turf212** [comment]
this is fixed in later versions.  Latest 3.3, 3.4, 3.5 and 3.6 all check that the wanteddepartment exists in in the department table and not the departments table.  Patch the site you have.

**Comment by accena-group** [comment]
Thank you!
