### ISSUE TITLE
IOMAD - Host Name is not working inside IOMAD - Companies - Host Name FAILED

### ISSUE THREAD

**Issue by mselavarasan** [iomad/iomad#895]
Hi,
I have added domain (hostname) inside the Companies but it's not working when accessing via browser.
Here are the steps for your review and advice please.
1. Created one domain and point to IOMAD Web Server
2. Login into Moodle Admin account
3. Create A Company in IOMAD  & Inside the "Advanced Company Settings", specified HOSTNAME.
4. Save and exit
5. when browsing with specified host name but it's always showing main URL instead of Host Name URL
6. I have already created one account inside A Company and tested.

Any Idea?
Thank
Ela

**Comment by mselavarasan** [comment]
Hi Team,
Any idea on the hostname related inquiries?
Would appreciate your comments, please.

Thank you,
Ela

**Comment by turf212** [comment]
This is correct behaviour.  Moodle, which Iomad is based on, has a single URL defined for the site.  Iomad still uses that single URL.  The hostname is simply to allow for users to get a company branded login/signup page instead of having to use the information in the signup/login URL parameters.

**Comment by eve4ever** [comment]
So how will the "branded " login suppose to look?
I've done all the settings, but can't understand what suppose to happen?
The login looks the same for all the companies although they all have logos and names, and the hostname is set.
Can anyone specify how and what suppose to be set and happen?

Thank you!

**Comment by cescc78** [comment]
> * Create A Company in IOMAD  & Inside the "Advanced Company Settings", specified HOSTNAME.

Hi mselavarasan, how do you setup hostnames??
