### ISSUE TITLE
User department wise enrollment

### ISSUE THREAD

**Issue by santoshredchip** [iomad/iomad#896]
When we select the sub- department and then the courses to enroll for. The page refreshes and the sub department selection is removed and replaced with company name. The potential list of students for a particular department is not seen for enrollment.
![1](https://user-images.githubusercontent.com/8309218/37594797-486a3bd8-2b9c-11e8-8fde-e00d000a110c.png)

**Comment by turf212** [comment]
fixed in commit 73c010e784e61578fc6ec4609a624b55cf1e4251
