### ISSUE TITLE
LDAP user and Iomad user

### ISSUE THREAD

**Issue by madriff** [iomad/iomad#899]
Hi everyone;

Im setting up iomad for enterprise. They have Active Directory and connect to Moodle via LDAP server (authencation method = LDAP server). When one user login to system via LDAP, that use belong to moodle, not iomad 

The goal is that the users connecting through the LDAP method will be logged into Iomad's user management.

Please recommend us solution.

Thanks.

**Comment by sangantnk8** [comment]
If you want to build a LDAP to user authentication. You just build a LDAP in AD and connect like normally.
To build LDAPS that is little tricky. You need to follow the link [http://www.javaxt.com/tutorials/windows/how_to_enable_ldaps_in_active_directory](). The guide will help you not to install a Certificate Authority on AD. Finally you need to import the certificate to your moodle server.

**Comment by rmeske** [comment]
This is also something that has come up for us as well.  Is there a way to tie LDAP/AD groups to the IOMAD system and automatically assign users to a Company at a minimum but also to further assign them to a Sub-company, department, role, etc.?

Is it possible to have different LDAP/AD servers tied to different companies?

Thanks,

**Comment by s0n-** [comment]
Or potentially assign users to companies by profile - LDAP could update their profile attributes and then IOMAD could assign to companies by attributes.

**Comment by turf212** [comment]
If you look at the self sign up settings in the local plugins Iomad will capture information on user creation to automatically put users into a company.  You can enable the plugin for LDAP (or similar) which then uses the email domain for the user's account to match against the company domain in edit company and automatically assign them.  You can also define a default company should anyone fall through the gaps.

There is also the local/iomad_signup/signup.php page where you can pass a company code (shortname) and id as well as a department shortname which will create users into a company and assign them to a department (if they have specified one and it exists).   The URLs for this are a little clunky so you can use the company hostname along with webserver settings to allow for multiple URLs which all go to the same webroot.  This then generates the URL for you so the user doesn't have to copy it out.  *note* This does not allow for mulitple URLS on the same site install.  Moodle doesn't handle this so Iomad doesn't.

**Comment by s0n-** [comment]
The functionality is great and helpful but I would assume if people are using LDAP or SAML as a source they are under one email domain but could be using different companies to achieve different things. 

It would be great if there was an additional criteria then email, something in the profile would be very helpful because it could further distinguish people within the same email domain
