### ISSUE TITLE
User summary for course (completion report by course) - Pulls real number for Final Score but shows as a %.

### ISSUE THREAD

**Issue by accena-group** [iomad/iomad#905]
This is an issue on courses where the final score does not equal 100. For example, I have a course with a final score of 10. A user scores 9.8. In the User summary for course (within the completion report by course), the final score shows as 9.8% instead of 98% or 9.8. 

Thanks.

**Comment by turf212** [comment]
The grades in the reports expact you to be using a percent and not a real grade or , as of 3.6, you can set that course not to have a displayed grade.
