### ISSUE TITLE
Individual branding

### ISSUE THREAD

**Issue by Basel4051** [iomad/iomad#907]
Hello IOMAD team

Started with IOMED yesterday. I'm head of training from an international traindriver school and untill yesterday I worked with nearly 8 different Moodle installations for our customers. IOMED already solved a lot of problems for me, but I have a problem with the themes. I use Adaptable as theme for the different customers, as it is important for them to see their own branding.

I installed Adaptable, and for each customer I changed the theme to Adaptable. The first adapation for the look and feel worked perfect, but for the second customer the branding was exactely the same as the first one. That is not what I needed, I need to be able to create the individual branding for each separate customer. Is that not possible or is my thinking to achieve this not correct?

Is IOMAD Boost the only way to change some of the look and feel from the themes?

Best regards from the Swiss alps

Bas

**Comment by thepurpleblob** [comment]
The only theme that supports different branding is IomadBoost. This is not supported by the Adaptable Theme. 

Any theme that supports Iomad branding either needs to be a child of IomadBoost or needs to incorporate the renderers from that theme. 

The stuff that matters is all here - https://github.com/iomad/iomad/blob/IOMAD_34_STABLE/theme/iomadboost/classes/output/core_renderer.php
