### ISSUE TITLE
Iomad 27 Upload User Error Message

### ISSUE THREAD

**Issue by maureen0608** [iomad/iomad#91]
Upload users results
events_trigger() is deprecated, please use new events instead

```
line 283 of /lib/deprecatedlib.php: call to debugging()
line 734 of /blocks/iomad_company_admin/uploaduser.php: call to events_trigger()
```

**Comment by turf212** [comment]
needs to be updated to use the core\event\user_created core\event\user_updated events instead.

**Comment by turf212** [comment]
code changed and sent for testing.

**Comment by turf212** [comment]
closed
