### ISSUE TITLE
Structure of the IOMAD database

### ISSUE THREAD

**Issue by paugarci0610** [iomad/iomad#920]
Greetings

I am currently working on a study about the Moodle LMS platform, more specifically the Multitenant Architecture, for which IOMAD offers this service, so I would like to know more about how the platform is integrated into the Multitenant Architecture and how the scheme  for the  data base is

Any information or documentation that you can provide me with would be very helpful

Thanks

**Comment by thepurpleblob** [comment]
There is no documentation available for the database architecture - sorry.
