### ISSUE TITLE
Upgrade from IOMAD 3.2 to IOMAD 3.3 - Mixed Moodle versions detected, upgrade cannot continue

### ISSUE THREAD

**Issue by jacksonp2008** [iomad/iomad#924]
What's the procedure?  There are no docs that I can find and other issues say to just overlay the new branch.  I running on Moodle 3.2 and IOMAD 3.2 was overlayed.  Now I want to get to IOMAD 3.3.

     git checkout -b myiomad33 origin/IOMAD_33_STABLE
     Branch myiomad33 set up to track remote branch IOMAD_33_STABLE from origin.
     Switched to a new branch 'myiomad33'
     root@ip-172-31-20-15:/var/www/html/iomad# cp -a * ../moodle

However, this returns:
Mixed Moodle versions detected, upgrade cannot continue
![screen shot 2018-04-30 at 17 54 52](https://user-images.githubusercontent.com/1813327/39457022-bb8d4e7e-4c9f-11e8-900e-ce81ca5ebc9e.png)

**Comment by jacksonp2008** [comment]
Also tried upgrading Moodle first to 3.3 then overlaying the latest "IOMAD_33_STABLE" branch.

This also fails:

![screen shot 2018-05-01 at 15 18 19](https://user-images.githubusercontent.com/1813327/39496370-ecb0e14c-4d52-11e8-99be-004bec431623.png)

**Comment by turf212** [comment]
The error you are getting (code is older) means that the version you are trying to install is an older version than the one you currently have installed.  Iomad is kept up to date with normal releases and not weeklies so if your current site is up to date on the weeklies then you will get this error.   To get around this, once you have pulled down the latest Iomad code, add the Moodle git repository in and merge in the MOODLE_33_STABLE (in your case) branch to it.  This will sync all of the Moodle core version numbers.

**Comment by jacksonp2008** [comment]
Yeah, I had done that and it didn't work.  I found a workaround however.

Regards,

-Steve

(415) 320-1102 <https://www.google.com/voice/#phones>
