### ISSUE TITLE
Bulk upload users using csv file sends emails with [blank] password

### ISSUE THREAD

**Issue by Ayasaad** [iomad/iomad#929]
I have written a password in the csv file and tried from the new user password dropdown the two option sends an email as follow : Your current login information is now:

username: test1
password: [blank] 
(you will have to change your password when you login for the first time)

how can i make the password appear in the email and not show as blank ?

**Comment by rroijackers** [comment]
I have the same problem. If you use the same password for users, you can just write the password in the e-mail. I haven't find a solution for this problem.

**Comment by turf212** [comment]
This is a language string issue.  Teh language pack should have {User_Newpassword} as the variable.
