### ISSUE TITLE
Company manager can view,but can't access the iomad dashboard (iomad_34)

### ISSUE THREAD

**Issue by max30272** [iomad/iomad#932]
I have upgraded from iomad_33 to iomad_34 for few days.
And find out the company manager can see the iomad dashboard in the panel, but can't access to the page.
Even a new clean iomad_34 is the same.

Does anyone know which permission of capability need to be allow then the company manager can access the iomad dashboard page?

*Update: Even set all permission of capabilities to be allow still can't access the page. :sob:

**Comment by jeremy-schweitzer** [comment]
I'm seeing this too, but with Client Administrator. From my testing it appears that only full site admins can get to the Iomad Dashboard right now.

**Comment by lokeshalw85** [comment]
Yes, I am getting same issue, when company manager login he get Iomad Dashboard link. but when click on link, page show "The Iomad administrator has not given you permission to do this.". NoPermission issue.

**Comment by max30272** [comment]
After dig in codes for few days. I have got a point.
When you get in the page it will do some permission check.
In`\iomad\local\iomad\lib\iomad.php `
This part(code line:1446)
```
        // Now find out what access is given to each role, going bottom-->up direction
        $allowed = false;
        foreach ($roles as $roleid => $ignored) {
            foreach ($paths as $path) {
                if (isset($accessdata['rdef']["{$path}:$roleid"][$capability])) {
                    $perm = (int)$accessdata['rdef']["{$path}:$roleid"][$capability];
                    if ($perm === CAP_PROHIBIT) {
                        // any CAP_PROHIBIT found means no permission for the user
                        return false;
                    }
                    if (is_null($roles[$roleid])) {
                        $roles[$roleid] = $perm;
                    }
                }
            }
            // CAP_ALLOW in any role means the user has a permission, we continue only to detect prohibits
            $restriction = $DB->get_record('company_role_restriction', array(
                    'companyid' => $companyid,
                    'roleid' => $roleid,
                    'capability' => $capability,
            ));
            if ($restriction) {
                return false;
            }
            $allowed = ($allowed or $roles[$roleid] === CAP_ALLOW);
        }
    
        return $allowed;
```
'$allowed = ($allowed or $roles[$roleid] === CAP_ALLOW);' will always return `false`.
The code didn't update for a long time .
So the moodle 34 should have make some changed.

You can modify the code to let it return `true` then you can get in the page.
But it may have some issue.

**Comment by Coderra** [comment]
I think it's related to this install error I get: 

local_iomad
Exception - Attempt to assign property "roleid" on null

[More information about this error](https://docs.moodle.org/401/en/error/moodle/generalexceptionmessage)

Debug info:
Error code: generalexceptionmessage×Dismiss this notification
Stack trace:
line 58 of /local/iomad/db/install.php: Error thrown
line 767 of /lib/upgradelib.php: call to xmldb_local_iomad_install()
line 1953 of /lib/upgradelib.php: call to upgrade_plugins()
line 721 of /admin/index.php: call to upgrade_noncore()

When upgrading from moodle to iomad I get this and then company managers cannot see iomad. But when doing a clean install without an upgrade from moodle I get this error and then the company manager cannot see iomad.
