### ISSUE TITLE
My Courses block should list completed course better

### ISSUE THREAD

**Issue by turf212** [iomad/iomad#933]
order by coursename and date completed descending.

**Comment by 2w3nn3r** [comment]
Seems that this has changed in newer versions (tested with 3.9). 

I could manage to restore this by commenting out the line:

`ksort($mycompleted, SORT_NATURAL | SORT_FLAG_CASE);`  in blocks/mycourses/localib.php
and adding the ORDER BY statement from https://github.com/iomad/iomad/commit/f4d39dadda04e559fece92acec2fbb92f88a02ba
