### ISSUE TITLE
Issue on eCommerce section

### ISSUE THREAD

**Issue by bambang150** [iomad/iomad#937]
I am on IOMAD 3.3.5
 Currently I have issue (1) with response as below on blocks/iomad_commerce/shop.php?tag=NLP:
Coding error detected, it must be fixed by a programmer: count_records_sql() expects the first field to contain non-negative number from COUNT(), '' found instead.

And also

(2) the invoice is not emailed to the buyers after request payment via invoice while the email setting on moodle is working according to Email Test plugin

(3) and also cannot change unpaid to paid status in Order section (blocks/iomad_commerce/edit_order_form.php?id=1)

**Comment by tuansaharizam** [comment]
Has this issue being solve? 
having the same problem. any solution?

**Comment by turf212** [comment]
shop has since been completely reworked.
