### ISSUE TITLE
fatal error when backing up courses with iomadcertificates

### ISSUE THREAD

**Issue by jamiepratt** [iomad/iomad#94]
In both the 2.5 and 2.6 branch of IOMAD you have forgotten to rename the files in backup/moodle2/ -replacing the old module name certificate with your new one iomadcertificate.

This is causing an error when trying to backup a course including iomadcertificates.

Fatal error: Class 'backup_iomadcertificate_activity_task' not found in /mnt/www/iomad/backup/util/factories/backup_factory.class.php on line 107

**Comment by turf212** [comment]
Backup and restore files are incorrectly named.
