### ISSUE TITLE
Upgrade from iomad 3.3 to 3.4

### ISSUE THREAD

**Issue by glu000** [iomad/iomad#940]
What is the best way to upgrade from iomad 3.3 to 3.4? Would e great if someone could give brief instructions or write a short how-to.

**Comment by actXc** [comment]
Follow the moodle.org documentation.  
Before all: Set Maintenance mode, purge all caches,  make backups of the iomaddata, database and installation folder.
Then start the update.
This will tell you the moodle.org documentaion again:
https://docs.moodle.org/33/en/Upgrading

**Comment by glu000** [comment]
Thanks - will try it!

**Comment by okellog** [comment]
how do I upgrade to moodle 3.9.1 in iomad 3.8. I got a notification to upgrade my moodle to the new version 3.9.1. Tried following the normal moodle upgrade but iomad failed to work.
