### ISSUE TITLE
No IOMAD Dashboard for Managers

### ISSUE THREAD

**Issue by Markrico** [iomad/iomad#943]
I just updated IOMAD with the code from May 25. My managers now have no IOMAD dashboard. I checked the Restrict Capabilities and the box is checked for view IOMAD dashboard. When I put in the address:
https://fsisafety.com/transportation/local/iomad_dashboard/index.php
I get the message:
The Iomad administrator has not given you permission to do this.

More information about this error

When I checked the dashboard under assign manager, the managers are already listed.  I tried removing and adding again with no change. 

Thank-you for any help you can provide on this issue.

**Comment by fesaner** [comment]
I also have the same problem. Department Managers cannot access the IOMAD Dashboard.  It worked in 3.3, but is broken in the 3.4 upgrade.

**Comment by thepurpleblob** [comment]
Closed in #932 earlier today. Please download the latest version from Github
