### ISSUE TITLE
Non-Iomad Certificate Paper Size

### ISSUE THREAD

**Issue by KellisEM** [iomad/iomad#945]
When using a non-iomad certificate size of letter (letter non-embeded) the default code should show LETTER not Letter
This will correctly set the page size.

``$pdf = new PDF($iomadcertificate->orientation, 'pt', 'Letter', true, 'UTF-8', false);``

Should read

`$pdf = new PDF($iomadcertificate->orientation, 'pt', 'LETTER', true, 'UTF-8', `false);``

**Comment by turf212** [comment]
fixed in commit d4bb662beb76cfef13caf3858c1f696ffc18f2c9
