### ISSUE TITLE
How to customise and use other themes other than Iomad Boost

### ISSUE THREAD

**Issue by BigWizzo** [iomad/iomad#947]
Hie

I have installed Iomad 33 with Iomad Boost theme. I had everything going fine untill I wanted to customise my theme. 

1. I could not find the Iomad Boost theme under appearence-->themes. How do I change my Logos and Favicons in Iomad Boost theme.

2. My second problem was when I tried to use other moodle themes. Boost, Clean etc. My company managers could no longer access the Iomad Dashboard.

So is there a way I can customise the Iomad Boost theme or a way I can use Moodle themes with Iomad in a way that allows my Company managers to view the Iomad dashboard. 

Thanx in advance

**Comment by actXc** [comment]
After selecting a company,
go to "Edit company"
then you are able to customize the appearance of this company in the "appearance" section.

If you want to use other themes, its possible but needs some programming to adapt them to iomad to have all the features of the iomad themes.

**Comment by BigWizzo** [comment]
Thank You. Lemme try that

**Comment by thepurpleblob** [comment]
The IomadBoost theme overrides a number of the standard renderers to add the custom features. If your own theme has IomadBoost as its parent then it should "just work". If you inherit from some other theme or are building a theme from scratch then you will need to copy the  custom renderer code from the IomadBoost theme.

**Comment by BigWizzo** [comment]
Thanks Very much I managed to get it right.
