### ISSUE TITLE
User login to wrong company allows login when using branded login via Webserver hostname 

### ISSUE THREAD

**Issue by jtsafran** [iomad/iomad#948]
For example, consider a single Iomad install with 2 companies: 

CompanyA (companyA.iomadsite.com)
CompanyB (companyB.iomadsite.com)

Create User1 and assign to CompanyA.  However, if User1 happens to visit the link for CompanyB (companyB.iomadsite.com) and then logs in, User1 will be shown the information for CompanyB, of which they do not belong.

The expected behavior should be to either:

A) Restrict the login with an error message as the user belongs to another company (preferred) 
-or-
B) Redirect the user to their assigned company after login

Let me know if that makes sense and if there are any further questions or pieces I missed!  Thanks!

Jesse Safran

**Comment by actXc** [comment]
A and B are much better than let a user see the other companys content.
A is my favorite.

**Comment by eve4ever** [comment]
Hey, are there any news about it?

**Comment by turf212** [comment]
Before the user logs in the only way we can tell which company they are in is via the URL they are coming in on.  If you have information specific to a company on the page prior to log in then there is very little we can be to prevent this from happening.  Once the user is logged in they will be given their current company details and assignation.

So, what, in particular, was the unlogged in user seeing that they should have and where?

**Comment by jtsafran** [comment]
It was after they logged in:

Create User1 and assign to CompanyA. However, if User1 happens to visit the link for CompanyB (companyB.iomadsite.com) and **then logs in**, User1 will be shown the information for CompanyB, of which they do not belong.

**Comment by davidramos010** [comment]
Any solution for that matter? I have the same problem, if the user of the company1 starts session in the company2, allows him to enter with the company information2

**Comment by nielsharma** [comment]
Are you able to share with us how you set up the URLs for companya.iomadsite.com and companyb.iomadsite.com?

**Comment by bavdalimbaev** [comment]
@nielsharma you now how create urls for companyA and CompanyB?

**Comment by turf212** [comment]
knowledge base articles for this are on www.iomad.org
