### ISSUE TITLE
IOMAD user Roles and Permissions

### ISSUE THREAD

**Issue by BigWizzo** [iomad/iomad#949]
Hie IOMAD family

When I try to create a new user. only three options are given to me.
1. User
2. Department Manager
3. Company Manager 

I would like to be able to utilize the Teacher and Student role (just like moodle). how can I use these roles in IOMAD. 

Or if there is a way I can edit the three IOMAD users to achieve Teacher and the Student roles.

Thanks in Advance.

**Comment by BigWizzo** [comment]
Anyone Please

**Comment by actXc** [comment]
I use it like this: Teacher role is set in the course, any iomad function role can be a teacher.

**Comment by smuglet** [comment]
@BigWizzo did you figure this out?  We've tried setting up and allocating Moodle roles to users but don't "think" they are being listened to... I could be wrong, they may jus tnot influence the iomad side even though we fiddle with iomad permissions.  We wanted to create some restricted iomad roles in our case.

For example Team Leader (who just saw iomad report but couldn't add users etc.

**Comment by Basel4051** [comment]
Having the same problem overhere. Need the possibility that a trainer can see the results of a test...doesn't work, only if I acces as Admin. I can't give all the different companies the Admin acces, so how can I change the roles and rights?

**Comment by turf212** [comment]
There is some new functionality after #962 which takes away the default behaviour of company manager gets a teacher type role on unlicensed courses.  If you have 3.3 or 3.4 code from beyond this point , you can untick the option in the local Iomad settings block that company managers get enrolled as non students.

This creates a new option of Educator in the assign managers/departments screen which can be assigned to any user in the company.  This educator user type instead gets the client course editor (Editing teacher type) or client course access (non editing teacher type) system roles on unlicensed courses depending if they are shared or not.

For licensed courses it unlocks an educator license type which can only be assigned to an educator user.  When the license is used the educator again gets the correct teacher type role, depending on if the course is shared or not.

**Comment by smuglet** [comment]
Where do you find the "Iomad Settings" block?

**Comment by turf212** [comment]
Site administration -> plugins -> local plugins.

**Comment by BigWizzo** [comment]
Thanks @turf212 Let me try that out
