### ISSUE TITLE
General Exception Message Error in Learning Paths

### ISSUE THREAD

**Issue by jeremy-schweitzer** [iomad/iomad#960]
When attempting to add courses to a learning path (siteurl/local/iomad_learningpath/courselist.php?id=1) I'm getting the following error with every role, except full site admin:

General Exception Message

File: /local/iomad/lib/iomad.php 
Line 1501 

Error code: generalexceptionmessage
* line 1501 of /local/iomad/lib/iomad.php: Error thrown
* line 1529 of /local/iomad/lib/iomad.php: call to iomad::has_capability()
* line 147 of /local/iomad_learningpath/externallib.php: call to iomad::require_capability()
* line 228 of /lib/externallib.php: call to local_iomad_learningpath_external::getprospectivecourses()
* line 59 of /lib/ajax/service.php: call to external_api::call_external_function()

I went and added every Iomad permission and reasonable underlying Moodle permission (see hidden categories, manage categories, etc.) I could think of to a test role and still got the error. 

I also seem to be able to trigger the error by clicking the "eye" icon to make the path available (on this page siteurl/local/iomad_learningpath/manage.php).

**Comment by thepurpleblob** [comment]
Yep - I can see the bug here.

**Comment by thepurpleblob** [comment]
Fix committed. You'll need to pull the latest version. Let me know if there are still any problems.

**Comment by jeremy-schweitzer** [comment]
Just tested and looks good to me. Thanks!
