### ISSUE TITLE
Multi language in create user form

### ISSUE THREAD

**Issue by ndalpe** [iomad/iomad#961]
Hi Guys,
I noticed that the course full name in create user form are not multi language compatible.

1 - Make sure Multi-Language Content (v2) is working properly

2 - Install at least 2 language packs. Mine is en and es.

3 - Create a course with min 2 languages in the title
ie: {mlang en}first course{mlang}{mlang en}{mlang es}Primer Curso{mlang}

4 - Create a new user in the company
In this form, under the "Assign courses" tab the course name should be displayed as in #3

Fix
local/course_selector/lib.php
Line 611
Replace 
```
        $bits = array(
            $course->fullname
        );
```
By
```
        $bits = array(
            format_string($course->fullname, true, 1)
        );
```

This fixed it for me. Maybe it is a Moodle bug I am not sure. 

Every suggestion to make this solution better is welcome.

Hope it helps

Thank you

**Comment by MarkusKgit** [comment]
This is quite similar to #891 and probably applies to more places

**Comment by ndalpe** [comment]
Continued in #891 as advice by @MarkusKgit 

thx
