### ISSUE TITLE
Migrating existing site with existing user data to use IOMAD

### ISSUE THREAD

**Issue by jamiepratt** [iomad/iomad#97]
Hi,

We have an existing Moodle 2.6 based web site.

We want to migrate the site with existing courses, enrolled users and their user data over to an IOMAD web site.

It was easy to merge the latest MOODLE_26_STABLE into the IOMAD code to get rid of the error we saw at first about the version of Moodle we were using being older than the database version. And the IOMAD database installed itself.

Right now none of our users are assigned to groups. We are hoping that we can use IOMAD to assign these users to companies and thus to have them assigned to groups within each of the courses they are already enrolled in.

Primarily we want to solve the problem of being able to give our clients' managers the ability to view the quiz grades and certificates issued for users from the same company but not from other companies.

Jamie

**Comment by turf212** [comment]
Hi Jamie,

Thank you for your post.  This is a support issue and not really a bug.  I noticed that you have sent in a separate email to ourselves at E-Learn Design.  There is no issue with ad hoc support and we will contact directly regarding this.  Look forward to helping you with this.

regards

Derick

**Comment by turf212** [comment]
closing as not an issue.

**Comment by Johnfredadams** [comment]
@jamiepratt did you manage to get your company managers to assign users into groups etc? We're looking at a similar problem. Can't immediately see how moodle native groups are going to work together with iomad.

**Comment by jamiepratt** [comment]
We didn't end up using IOMAD John we customised Moodle instead.
