### ISSUE TITLE
Delete Course = Broken Reports

### ISSUE THREAD

**Issue by smuglet** [iomad/iomad#978]
Continuing to test.  A fairly clean setup.

So assuming that you delete a course from "Site Admin" as I can't find anywhere else to do so.

It does not clean up the "mdl_company_course" table as a entry remains which then breaks the "Completion report by course" report... and probably some other stuff I've not stumbled upon.

I made sure Cron had ran a few times before this also.... Anyone else experience this?

Maybe I'm deleting a course from the wrong bit of UI for Iomad but I can't find anywhere else to do it, either in Iomad dashboard for on the course (there is a "Recyle Bin" option but that didn't seem to remove the course at all.

Help?!

Oh I tracked down the issue using Moodle debug, here is the report from that (15 is the ID of the course I deleted).  However I have tested this multiple times and is happens every time.

Debug info: SELECT id,category FROM {course} WHERE id = ?
[array (
0 => '15',
)] 
Error code: invalidrecord
×Stack trace:
line 1546 of \lib\dml\moodle_database.php: dml_missing_record_exception thrown
line 1522 of \lib\dml\moodle_database.php: call to moodle_database->get_record_select()
line 6457 of \lib\accesslib.php: call to moodle_database->get_record()
line 92 of \local\report_completion\locallib.php: call to context_course::instance()
line 246 of \local\report_completion\index.php: call to report_completion::get_course_summary_info()

**Comment by smuglet** [comment]
Soz, mine is a duplicate of: https://github.com/iomad/iomad/issues/819

I have a manual fix (delete the hanging about entry from DB manually but that's not a solution for users).

**Comment by smuglet** [comment]
Steps to delete =  Remove course from Iomad company... THEN... delete from Site Admin -> Course Management otherwise the above occurs.  I believe a fix is pending.

**Comment by catalinopascual1** [comment]
Hi! Has anyone tried Iomad Dashboard > Manage Iomad course settings > (At the right of the course) - Delete? Thank you.
