### ISSUE TITLE
Refected XSS in pchart2

### ISSUE THREAD

**Issue by sangantnk8** [iomad/iomad#979]
Hi,

I found a Reflected XSS in session.php. The server does not filter the input of user before output it.

Source code: https://github.com/iomad/iomad/blob/IOMAD_34_STABLE/local/iomad/pchart2/examples/sandbox/script/session.php#L18-L21

The attacker can take advantage of the vulnerability to steal information of user or do any possible action on behavior of victim user.

**Comment by turf212** [comment]
Pchart is now no longer used.
