### ISSUE TITLE
License by Instant Access does not enrol in all courses

### ISSUE THREAD

**Issue by fesaner** [iomad/iomad#987]
I am using IOMAD_34_STABLE downloaded today.  The issue is that a License, configured for Instant Access and a Program of Courses, enrols a user in the first course, but then throws a fatal error and does not enrol the user in other courses associated with the Program of Courses.

The error message is:
Exception - Call to protected method enrol_license_plugin::email_welcome_message() from context 'company'    More information about this error
×Debug info: Error code: generalexceptionmessage
×Stack trace:
line 2941 of /local/iomad/lib/company.php: Error thrown
line 137 of /local/iomad/classes/observer.php: call to company::user_license_assigned()

I looked at file  /local/iomad/lib/company.php,  Line 2941: $enrol->email_welcome_message($instance, $user);  There is no protected method, email_welcome_message () in the file.

The code also generates a non-fatal warning: Warning: array_shift() expects parameter 1 to be array, object given in /local/iomad/lib/company.php on line 356.

Thanks for looking into this.
Floyd Saner

**Comment by turf212** [comment]
Hi Floyd.  Turn off the welcome message from the course, it's not needed (and has been removed as an option in later versions).  Iomad will send a license allocated email to the users anyway so it/s redundant.
