### ISSUE TITLE
Completion report showing number of users enrolled but no users listed as not started

### ISSUE THREAD

**Issue by rajephcote** [iomad/iomad#988]
Completion report showing number of users enrolled but no users listed as not started - users also do not show on course summary
![image](https://user-images.githubusercontent.com/7266007/42941258-18ba2ad4-8b54-11e8-80f1-9d17029a27f5.png)
![image](https://user-images.githubusercontent.com/7266007/42941296-37231e04-8b54-11e8-80a3-d1503e16004d.png)
there do not appear to be any records in the course completion table for these users

**Comment by rroijackers** [comment]
I have the same issue.

**Comment by turf212** [comment]
You need to .have course completion turned on in your Moodle courses otherwise the reports will simply not work
