### ISSUE TITLE
[HELP] Assign learning plan to student can be done with other companies

### ISSUE THREAD

**Issue by bambang150** [iomad/iomad#997]
Have issue with assigning  learning plans to students/individual. 

When a company manager is assigning a learning plan to an individual then other company students are also accessible and can be able to assign the learning plans to them too as well.

These are my steps:
1. Create course A with Quiz A activity
2. Set completion requirement on Quiz Activity
3. Create competency frame works
4. Create learning plan
5. Add competency to learning plan
6. Assign related competency in Competencies setting in course A
7. Assign related competency in Quiz A activty
8. Open Iomad dashboard
9. Assign company and student to course A
10. Assignrelated competency to Company A
11. Assign related learning plan to Company A
12. Open Learning Plan and click 0 to assign student to learning plan
13. And when we want to assign there are students from other company

Please help

**Comment by turf212** [comment]
closed in #1609
