### ISSUE TITLE
Custom Profile Fields common to all Companies

### ISSUE THREAD

**Issue by fryeguy63** [iomad/iomad#998]
I am running iomad 34. Is it possible to add custom profile fields that are available to all companies? I have hundreds of companies to add and they all need some additional fields. If this is not available today, I would like to suggest it as a feature.

Would it make sense to solve this issue with a plugin?

**Comment by turf212** [comment]
yes.  Put them into a profile field category which is not tied to a company.  E.g. create one called "Other" and put your fields in there.
